### ISSUE TITLE
System.Runtime.InteropServices.FieldOffset не работает на перезапись

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#1007]
Если декомпилировать [библиотеку из этого архива](https://github.com/pascalabcnet/pascalabcnet/files/2229028/0.zip) - там есть тип `AngleSingle` и в нём объявлены следующие поля:
```
    [FieldOffset(0)]
    private float radians;
    [FieldOffset(0)]
    private int radiansInt;
```
Если написать то же самое на паскале:
```
{$reference SharpDX.Mathematics.dll}

uses System.Runtime.InteropServices;

type
  MyAngleSingle=record
    
    [FieldOffset(0)] radians: single;
    [FieldOffset(0)] radiansInt: integer;
    
  end;

begin
  sizeof(SharpDX.AngleSingle).Println;
  sizeof(MyAngleSingle).Println;
end.
```
Для размера `SharpDX.AngleSingle` выдаёт 4, а для размера `MyAngleSingle` - 8.

Похоже, это своеобразная реализация `union`. В той библиотеке это используется чтоб получать хеш-код, то есть на перезапись и считывание работает `radians`, а хеш-код получают из `radiansInt`.

Ну, впрочем, не мне вам объяснять на сколько полезен может был `union`.

**Comment by ibond84** [comment]
Вы не правильно код написали. Так правильно

```
uses System.Runtime.InteropServices;

type
  [StructLayout(LayoutKind.&Explicit)]
  MyAngleSingle=record
    
    [FieldOffset(0)] radians: single;
    [FieldOffset(0)] radiansInt: integer;
    
  end;

begin
  sizeof(MyAngleSingle).Println;
end.
```
