### ISSUE TITLE
Выбирается неправильная подпрограмма, если второй параметр - процедура

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#1010]
```
procedure test(i: int64; proc:procedure);
begin
  
end;

procedure test(r: real; proc:procedure);
begin
  test(System.Convert.ToInt64(r), proc);
end;
begin
  test(2.3, nil);
end.
```
Эта программа будет вызывать вторую процедура в бесконечном цикле и даст в итоге стак оверфлоу и это:
![image](https://user-images.githubusercontent.com/27270190/43247153-89fd0de8-90bc-11e8-8d57-5c1901aec8a8.png)

Если заменить `procedure` на любой другой тип, к примеру, `object` - всё работает нормально.

**Comment by ibond84** [comment]
Упростил пример кода.
