### ISSUE TITLE
Не правильная ошибка, при невозможности вывести <T> для оператора

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#1013]
```
type
  t1=class end;

procedure object.operator+=<T>(a,b:t1) := exit;

begin
  var a := new t1;
  a += new t1;
end.
```
Тут выдаёт следующую ошибку:
`Невозможно вывести типы-параметры generic-подпрограммы += (укажите типы-параметры явно)`

Но если убрать `object.`:
```
type
  t1=class end;

procedure operator+=<T>(a,b:t1) := exit;

begin
  var a := new t1;
  a += new t1;
end.
```
То оператор не видит:
`Операция '+=' не применима к типу t1 `

Как сказал @miks1965 [тут](https://github.com/pascalabcnet/pascalabcnet/issues/987#issuecomment-410055686):

>Вывести тип T будет невозможно, поэтому операция никогда не применится. Но она запоминается во внутренних структурах.

То есть компилятор должен запоминать оператор, хоть он и не правильный.
И, значит, правильную ошибку выводит в первом случае. А второй надо исправить.

**Comment by ibond84** [comment]
Ошибки нет. Вы неправильно описываете extension-оператор. Правильное описание
```
procedure operator+=<T>(a,b:t1); extensionmethod := exit;
```
выдает ту же самую ошибку, что и с object

**Comment by SunSerega** [comment]
Подождите, а если оно не правильное - почему тогда компилятор на описание этого оператора не ругается?
