### ISSUE TITLE
Безопасный срез неправильно форматируется

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#1017]
```
begin
  var a := Arr(0);
  a := a?[1:];
end.
```
После форматирования получаем:
```
begin
  var a := Arr(0);
  a := a?[11:];
end.
```

**Comment by SunSerega** [comment]
@ibond84 Проверьте ещё это:
```
begin
  var a := Arr(0);
  a := a?[1+1:];
end.
```
Я, конечно, не сильно там во всё исправили, но на сколько я могу судить - вы исправили только для констант, не выражений.

**Comment by ibond84** [comment]
Ну все корректно форматируется
