### ISSUE TITLE
$include файлы берёт из папки когда они открыты в IDE

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#1021]
Основная программа:
```
begin
  {$include 'inc_file'}
end.
```
inc_file:
```
writeln(1);
```
Запускаем - выводит 1.

Теперь в IDE меняем 1 на 2 в inc_file.
Не сохраняя запускаем основную программу. Выводит всё равно 1.
И, хоть опция "сохранять файлы после компиляции" включена - его не сохранило.

**Comment by miks1965** [comment]
Это не pas-файл. Строго говоря, это не единица компиляции. Потому и не сохраняет.
