### ISSUE TITLE
Запретить описывать не extension-операторы в модуле

### ISSUE THREAD

**Issue by ibond84** [pascalabcnet/pascalabcnet#1023]
```
type
  t1=class end;

procedure operator+=<T>(a,b:t1) := exit;

begin
  var a := new t1;
  a += new t1;
end.
```

**Comment by miks1965** [comment]
А где не extension операторы можно описывать? Я считал, что только как статические методы класса.

**Comment by miks1965** [comment]
А, ну, в смысле - не в классе без extensionmethod. Согласен.

**Comment by SunSerega** [comment]
По моему, стоит вообще разобраться нормально, расписать какой тип операторов где можно описывать. Раз вы сами не понимаете))

**Comment by miks1965** [comment]
Мы уже разобрались. Код неправильный.
На неправильный код выдаётся неправильная ошибка. Исправим.
