### ISSUE TITLE
Преобразование делегата к object - где-то выскакивает второе неверное преобразование

### ISSUE THREAD

**Issue by miks1965** [pascalabcnet/pascalabcnet#1029]
```
function f := 1;
 
begin
  var ff: ()->integer := f;
  var r: object := ff;
end.
```
a2.pas(5) : Возможны два преобразования типа: к типу object и к типу null
null - это следствие того, что тип, к которому преобразуется, - нулевой. Что неверно разумеется

**Comment by miks1965** [comment]
Сделал чтобы в этом случае был вызов делегата. Это вроде ничему не противоречит.

**Comment by SunSerega** [comment]
А как в этом случае сделать чтоб был не вызов а именно запаковка функции в объект?

**Comment by SunSerega** [comment]
При присвоении переменной это явное указания типа этой переменной.
При вызове шаблонного метода это явное указание шаблонных параметров.
А как тут?

**Comment by SunSerega** [comment]
А, точно, так можно...
```
function f := 1;
 
begin
  var ff: ()->integer := f;
  var r: object := System.Delegate(ff);
end.
```
