### ISSUE TITLE
Не видит Result в лямбде из try except end

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#1032]
```
begin
  var f1:function:byte := ()->
  begin
    Result := 1;//ok
  end;
  
  var f2:function:byte := ()->
  try
    Result := 2;//Ошибка
  except
    Result := 3;//Ошибка
  end;
end.
```

**Comment by miks1965** [comment]
Всё правильно. ()->оператор - это лямбда-процедура, там нет никаких Result.

**Comment by SunSerega** [comment]
А давайте вы всё же будете смотреть не со стороны как кишки были задуманы, потому что программисты которые не углубляются в дебаг как я не будут интересоваться кишками. Вместо этого надо думать о применении, как это выглядит на фоне остальных фич языка.

Если оператор это не что то вроде `raise` - результат лямбды вполне уместен. И если запрещать его  - будет надо писать лишние `begin end`, необходимость в которых выглядит странно и очень криво. У вас уже проверяется если ли `Result` в лямбде состоящей из `begin end`, почему не сделать так для операторов?

То есть сейчас это процедура:
```
()->
begin
end;
```
, а это функция:
```
()->
begin
Result := 5;
end;
```
, компилятор может их отличить без проблем.

**Comment by miks1965** [comment]
Еще раз - одиночный оператор - признак процедуры. А Result может быть переменной из ее внешнего окружения.

**Comment by SunSerega** [comment]
>Еще раз - одиночный оператор - признак процедуры

Ещё раз: вы делаете правило чисто чтоб было правило? Что сломается если вместо "всегда процедура, потому что я так сказал" будет "если есть Result - функция, если нет - процедура"?

>А Result может быть переменной из ее внешнего окружения

Нет, не может потому что:
a) это порождает неординарность в других случаях
b) то ли вы, то ли @ibond84 на форуме говорили что так делать нельзя и это должно быть запрещено
c) потому что не может, вы сами попробуйте

>Нормальный человек напишет разумеется

Это был лишь пример чтоб показать разницу лямбды с `Result` и без. А точнее что компилятор может их отличить. И, на сколько я помню - именно с этим проблема было только одна (#793).

А так - всё зависит от того что "нормальный человек" пытается достичь. К  примеру, что если надо следующее:
```
()->
try
  //сделать что то что может вызвать исключение
  Result := {что то что мы из этого получили};
except
  Result := -1;//или что то типа того
end;
```
Если не разрешать писать так - приходится добавлять лишние `begin end`.

И если вы хотя бы на секунду, всё же, попробуете встать на место человека который не интересно изучить каждый миллиметр этого компилятора (то есть, на место, по определению - **нормального человека**, такого как большинство) - вы поймёте что это выглядит глупо.

Я не говорю про то что сложно обработать в голове правило что все лямбды из оператора это процедуры. Я говорю про то, что это не удобно использовать на практике.

А самое не приятное - что это правило не обосновано. Даже если вы вдруг передумаете, и разрешите захватывать `Result` верхнего уровня в лямбде-процедуре, тогда получается что и в данном случае:
```
//мы в функции
var p:procedure;
p := ()->
begin
writeln(Result)
end;
```
надо будет разрешить. Ведь из контекста можно вполне понять что это лямбда не может иметь возвращающее значение, а значит `Result` это внешняя переменная. Иначе опять же, это поведение которое будет выглядеть непонятно, пока не закопаешься глубоко в устройство компилятора.

**Comment by miks1965** [comment]
Мы правило не делаем - я хочу подчеркнуть - мы его уже сделали
