### ISSUE TITLE
Паскаль разучился преобразовывать указатель к объекту

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#1033]
Всюду но не во `write` и `writeln`:
```
procedure MyPrint(o:object) := exit;

begin
  var i := 5;
  var p := @i;
  Writeln(@i);//компилируется и выводит в шестнадцатеричном виде адрес (я находил когда то, там специально для указателей код прописан, чтоб выписать их значение в шестнадцатеричном виде)
  //Write(@i);//и это так же
  Print(@i);//Ошибка: нет перегрузки для этих параметров
  MyPrint(@i);//Ошибка: нельзя преобразовать указатель к объекту
end.
```
Хотя подходящие объявления `Print` и `Write` тут одинаковые:
```
procedure Write(params args: array of object);
procedure Print(params args: array of object);
```
Вроде, это раньше работало всюду, и в пользовательских подпрограммах тоже...

**Comment by ibond84** [comment]
Все правильно, указатели и тип object несовместимы. Writeln это магическая функция. В object там передается форматированный адрес объекта.

**Comment by miks1965** [comment]
MyPrint(integer(@i))

**Comment by SunSerega** [comment]
Я не говорю это для пользовательский процедур разрешить. Я говорю только про то, чтоб сделать `Print` на столько же магической как `Write`, раз они обе стандартные. Тем более, раз вы считаете в целом `Print` более правильной в широком использовании.

И не забывайте, про то что `Write` выводит адрес указателя в 16-ичном виде, что занимает добрые несколько десятков знаков в строчке, что делает `Print` бесполезной для указателей.

**Comment by miks1965** [comment]
В C# тоже нельзя:
Не удается неявно преобразовать тип "int*" в "object"

**Comment by SunSerega** [comment]
В C# и во `write` указатели передавать нельзя. Ну ведь это обе ваши стандартные функции вывода и вы говорили что `print` предпочтительнее. С чего вы вдруг её обделяете.

**Comment by miks1965** [comment]
Print - обычная библиотечная. Она предпочтительна для начинающих. 
Write - волшебная. Она предпочтительна для продолжающих и заканчивающих )
Волшебная - значит вмонтированная в компилятор. Так Вирт придумал - мы его часто вспоминаем
