### ISSUE TITLE
Падает union тип с объектами классов

### ISSUE THREAD

**Issue by miks1965** [pascalabcnet/pascalabcnet#1035]
```
uses System.Runtime.InteropServices;

type
  [StructLayout(LayoutKind.&Explicit)]
  SomeValType = record
    [FieldOffset(0)]
    b: byte; // Поля b и x перекрываются
    [FieldOffset(0)]
    x: integer; // в экземплярах этого класса.
    [FieldOffset(0)]
    s: string; // в экземплярах этого класса.
  end;

begin
  
end.
```
() : Внутренняя ошибка компилятора в модуле [pabcnetc.exe] :'System.Exception: System.TypeLoadException: Не удалось загрузить тип "attroffs.SomeValType" из сборки "attroffs, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null", так как он содержит поле объекта со смещением 0, которое неверно выровнено или перекрыто полем, не представляющим объект.
   в System.Reflection.Emit.TypeBuilder.TermCreateClass(RuntimeModule module, Int32 tk, ObjectHandleOnStack type)
   в System.Reflection.Emit.TypeBuilder.CreateTypeNoLock()
   в System.Reflection.Emit.TypeBuilder.CreateType()
   в PascalABCCompiler.NETGenerator.ILConverter.CloseTypes()
   в PascalABCCompiler.NETGenerator.ILConverter.ConvertFromTree(IProgramNode p, String TargetFileName, String SourceFileName, CompilerOptions options, String[] ResourceFiles)
   в PascalABCCompiler.Compiler.Compile()'

**Comment by SunSerega** [comment]
Это компилируется:
```
uses System.Runtime.InteropServices;

type
  [StructLayout(LayoutKind.&Explicit)]
  SomeValType = record
    //[FieldOffset(0)]
    //b: byte; // Поля b и x перекрываются
    //[FieldOffset(0)]
    //x: integer; // в экземплярах этого класса.
    [FieldOffset(0)]
    s: string; // в экземплярах этого класса.
    [FieldOffset(0)]
    s2: string; // в экземплярах этого класса.
  end;

begin end.
```
То есть надо чтоб было хоть 1 поле-запись и хоть 1 поле-класс.

**Comment by ibond84** [comment]
Этот код падает и в C# (при выполнении). Надо выдавать ошибку компиляции. Правда непонятно, в каких случаях ее выдавать...

**Comment by ibond84** [comment]
Так, поля ссылочных типов не могут перекрывать поля, занимающие меньше 8 байт (в 64-битной винде)

**Comment by SunSerega** [comment]
И меньше 4 байт в х32-битной?
