### ISSUE TITLE
"case ... of;" не правильно форматируется

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#1039]
```
begin
  var i := 1;
  case i of;
  1:Write(2);
  else Print(666)
  end
end. 
```
Форматируется в:
```
begin
  var i := 1;
  case i of1: Write(2);
  else Print(666)
  end
end. 
```
Похоже, ставить `;` после `case ... of` разрешили [тут](https://github.com/pascalabcnet/pascalabcnet/commit/fa6270ce7d43827a913ca953cf67197624d9ce94).

Тест на компиляцию поставили, а на форматирование нет... Разве не оба надо делать для каждого изменения синтаксиса?

**Comment by miks1965** [comment]
У меня не компилируется и по этой причине не форматируется

**Comment by miks1965** [comment]
Ещё раз просьба - прежде чем писать что-то в Issue - обновите версию

**Comment by SunSerega** [comment]
Перейдите по ссылке которую я дал - там была добавлена эта программа в тесты.

**Comment by miks1965** [comment]
Да. В ошибочные тесты. Смотрите внимательнее
