### ISSUE TITLE
Типизированные файлы со string[255]

### ISSUE THREAD

**Issue by miks1965** [pascalabcnet/pascalabcnet#1042]
```
type
  t1 = record
    f2: string[255];
  end;

var
  f: file of t1;
  b: t1;

begin
  Rewrite(f,'MyFile.bin');
  b.f2 := 128*'*';
  f.Write(b);
  f.Close
end.
```
Здесь в файл записывается 257 бит. Причина - дескриптор строки со 128 символов становится двухбайтовым.

Если в этой программе 128 исправить на 127, то записывается 256 бит - дескриптор - однобайтовый.

Что приводит к ошибкам

**Comment by SunSerega** [comment]
Я на форуме это раз 3-5 написал (а может и больше), но вы используете `System.IO.BinaryWriter.Write(string)`, который сохраняет длину строки в 7-битном формате.

- 7-битный формат сохранения числа:
Если число меньше 128 - его записывает в младшие 7 бит первого байта и на этом всё заканчивается. Если 128 или больше - младшие 7 бит записываемого числа записываются в младшие 7 бит первого байта. В старший бит первого байта при этом ставится `True`, что означает что следующий байт тоже будет частью записываемого числа. В младшие биты второго байта записываются 7-13 (считая с 0=младший бит) бит и т.д. Всего в 7-битной кодировке на число может быть потрачено 5 байт, если больше - получаем исключение.

- 8-битная кодировка:
Это самая стандартная, записывает 4 байта числа "as is".

- Кодировка которая нам нужна:
Записать в первый байт младшие 8 бит числа, и на этом всё. То есть сохранить только первый из 4 байт обычной 8-битной кодировки.

**Comment by AlexRnD61** [comment]
Еще раз перепишу с форума формулировку ошибки.

При работе с типизированным файлом, если в структуре записи есть символьные поля с длиной более 127 байт и реальное содержимое этих полей в записях может иметь длину как от 0 до 127 байт, так и более 127 байт, типизированный файл формируется некорректно. Он перестает быть совместимым с более ранними версиями Паскаль и даже с PascalABC. Полученный файл корректно читается последовательным доступом, но в прямом доступе (с поиском записей по Seek) работа фактически невозможна из-за ошибочного подвода записей.

Решение: Формировать всегда однобайтный дескриптор. Проверить, как будут работать операция чтения такого файла и операция поиска Seek при однобайтном дескрипторе со значением 128..255

**Comment by miks1965** [comment]
> При этом остаются другие проблемы, не вызывающие аж на столько грубых ошибок, но являющиеся несовместимыми со старыми паскалями (к примеру, приватные поля записей не записывает в файл и не пытается прочитать). Это не такое грубое, потому что можно просто делать все поля публичными. Но Если вы придерживаетесь совместимости - это тоже надо исправить.

Я не считаю несохранение приватных полей ошибкой. Более того - так было задумано. О каком Вирте и совместимости вы говорите, если во времена Вирта не было приватных полей? 

Сформируем однобайтовый дескриптор - не проблема. Вопрос - в какой кодировке писать? Если хотим совместимости на уровне файлов со старыми версиями, то это однобайтовая кодировка. Но видимо это неправильно - надо сохранять в двухбайтовую, и тогда совместимости на уровне файлов естественно не будет. Как и у текстовых кстати :)

**Comment by AlexRnD61** [comment]
Почему Вы решили, что у текстовых файлов кодировка двухбайтная?
```
begin
  WriteAllText('Res.txt', 'Дает корова молоко' + NewLine +
      'Писать, конечно не легко')
end.
```
```
C4	Е0	Е5	F2	20	ЕА	ЕЕ	F0	ЕЕ	Е2	Е0	20	ЕС	ЕЕ	ЕВ	ЕЕ
ЕА	ЕЕ	0D	0А	CF	Е8	F1	Е0	F2	FC	2С	20	ЕА	ЕЕ	ED	Е5
F7	ED	ЕЕ	20	ED	Е5	20	ЕВ	Е5	ЕЗ	ЕА	ЕЕ
```
Обычная однобайтная кодировка CP-1251

**Comment by AlexRnD61** [comment]
Но поскольку типизированный файл - фактически бинарник, сохраняя там строки в двухбайтной кодировке мы получим не только несовместимость, но и невозможность читать файлы от старых задач, причем, не только паскалевских. Если cейчас еще можно наложить строку string на фрагмент поля, то двухбайтная кодировка сделает это недоступным при нечетном числе байт. А впрочем - пофигу! Если язык рассматривать исключительно, как учебный, - какая разница, какой там формат у этих файлов?

**Comment by miks1965** [comment]
Вряд ли старые файлы будут использоваться как источник.

Все текстовые файлы можно сейчас сохранять в любой кодировке.

Принципиальным является следующее. В бинарных файлах информация хранится как в оперативной памяти. Я думаю, это не вызывает спор. Строки хранятся как двухбайтовые. Поэтому и сохранять надо как двухбайтовые. А то мы не сможем в бинарный файл вообще записать строки, содержащие шведские символы или какой-то юникод. Можно конечно кодировку указывать как доппараметр при создании бинарных файлов.

**Comment by AlexRnD61** [comment]
Ну не знаю. Я только что из Экселя 2010 данные выгрузил в CSV - никакого намека на Юникод, однобайтная кодировка русских букв. В PasclalABC.NET чтобы прочитать будут пляски с бубном?

Как в памяти строки хранятся - это их интимное дело. Но вот если не будет опционального указания кодировки, чтобы читать/писать 1 или 2 байта на символ - это некрасиво.

**Comment by miks1965** [comment]
csv - текстовый формат

**Comment by AlexRnD61** [comment]
Естественно. Но лежать будет в файле и почему бы не определить для него запись с подходящими полями, чтобы сразу получить массив нужных данных?

**Comment by SunSerega** [comment]
Ну, по моему последний спор без дела, от параметра с типом `System.Text.Encoding` и значением по умолчанию - точно ничего плохого не произойдёт))

**Comment by spectatorBH** [comment]
csv тут не причем, там каждая строка -- с полями переменной длины, их в общем случае невозможно читать как типизированный файл. Но, в любом случае, ручное управление кодировкой для чтения/записи строковых полей в типизированных файлах было бы полезным, в этом нет ничего сложного.

Странно, что тут нет пометки `bug`. Главная проблема ведь не в том, что бинарная совместимость с другими Паскалями нарушена (хотя это само по себе уже нежелательно), а в том, что если в типизированном файле попадется хотя бы одна строка с фактической длиной более 127 символов, то _ни одна запись после неё уже не сможет быть правильно прочитана/записана в режиме произвольного доступа через Seek()_. А это уже как минимум искажение, а после перезаписи -- **гарантированная потеря данных**!

**Comment by AlexRnD61** [comment]
Если, к примеру, перекачиваете строки из таблицы Экселя с регулярной структурой, там с определенного места все записи фиксированной длины. Но не суть важно.

**Comment by miks1965** [comment]
Закрыли баг простым образом.

**Comment by miks1965** [comment]
Потестируйте кто принимал участие

**Comment by SunSerega** [comment]
[коммит](https://github.com/pascalabcnet/pascalabcnet/commit/9c523689d5c894fbe9853e1a42196b420a6680cc), если кому надо

**Comment by SunSerega** [comment]
Скачал только что новый билд - ничего не изменилось, вы точно не забыли добавить изменения в установщик?

**Comment by miks1965** [comment]
Скачайте еще - только сейчас выложил. Разрешать произвольную кодировку в типизированном файле нельзя - если выбрать Utf8 - она переменной длины

**Comment by AlexRnD61** [comment]
Рано закрыли. Пишет прекрасно, а чтение не идет, слетает по семибитному дескриптору.
Я выкладывал тестовые программы на форуме, но он недоступен, приложу тут. Там одна программа создает файл, две другие читают. Обе с чтением слетают на второй записи.

[err.zip](https://github.com/pascalabcnet/pascalabcnet/files/2298420/err.zip)

**Comment by SunSerega** [comment]
Да, потому что сохранение поменяли а загрузку нет (см. ссыль на коммит выше).

**Comment by SunSerega** [comment]
И ещё, сделайте какую то кодировку параметром по умолчанию во всех `Reset` и т.п. Чтоб в старом стиле, без её указания можно было работать. Это ведь все самые элементарные программы сломает, если не сделать.

**Comment by miks1965** [comment]
Сделать возможность указания кодировки в типизтрованных файлах?

**Comment by SunSerega** [comment]
Я говорю про вот эти изменение в [этом коммите](https://github.com/pascalabcnet/pascalabcnet/commit/9c523689d5c894fbe9853e1a42196b420a6680cc):

![image](https://user-images.githubusercontent.com/27270190/44297997-a4be2200-a2e3-11e8-8c2b-4c6d7a7a5cae.png)

Вы получается сделали так, что тебе нельзя НЕ указывать кодировку. Вот я и говорю, сделайте кодировку - параметром по умолчанию, чтоб можно было её не указывать.

**Comment by SunSerega** [comment]
[коммит2](https://github.com/pascalabcnet/pascalabcnet/commit/6b66e564ed15b807def9ea7decb0e403a804daa2)

**Comment by SunSerega** [comment]
```
type
  r1=record
    
    b1:byte;
    b2:byte;
    s:string[255];
    b3:byte;
    
    constructor := exit;//без этого не может прочитать
    
    constructor(id:byte);
    begin
      b1 := $FF;
      b2 := id;
      s := '*'*id;
      b3 := $EE;
    end;
    
    procedure Validate;
    begin
      if s <> '*'*s.Length then
        writeln('Строка прочитана не правильно:{#10}{s}');
    end;
    
    public function ToString:string; override :=
    $'(${b1.ToString(''X'')}, {b2}, [''*''*{s.Length}], ${b3.ToString(''X'')})';
    
  end;

begin
  
  var sz := 3+1+255;  
  var f:file of r1;
  Rewrite(f,'temp.bin');
  
  loop 5 do
    for var i := 0 to 255 do
      f.Write(new r1(i));
  
  f.Close;
  writeln('запись ok');
  
  
  
  if System.IO.FileInfo.Create('temp.bin').Length <> sz*5*256 then
    writeln($'Длина файла не правильная. Должна быть {sz*5*256}, а не {System.IO.FileInfo.Create(''temp.bin'').Length}');
  
  
  
  Reset(f);
  
  for var i0 := 1 to 5 do
    for var i := 0 to 255 do
    begin
      var el := f.Read;
      el.Validate;
      var sb := new r1(i);
      if el <> sb then
        writeln($'Элемент #{i0}:{i} записан не правильно{#10}el:{el}{#10}sb:{sb}');
    end;
  
  f.Close;
  writeln('последовательное чтение ok');
  
  
  
  Reset(f);
  
  for var i0 := 1 to 5 do
    for var i := 0 to 255 do
    begin
      f.Seek(i0*255+i);
      var el := f.Read;
      el.Validate;
      var sb := new r1(i);
      if el <> sb then
        writeln($'Элемент #{i0}:{i} записан не правильно{#10}el:{el}{#10}sb:{sb}');
    end;
  
  f.Close;
  writeln('Seek чтение ok');
  
end.
```
У меня падает из за чтения после конца потока. Записывается всё правильно, но прочитать не может.

Интересно что оно почему то решило что у строки в первой записи длина 255, хотя она 0. У второй показывает 0 хотя записана 1, у следующей 1 хотя записано 2 и т.д.
Это странно, потому что оно откуда то берёт ещё и `255` знаков `*` в строке первой записи, хотя в файле их нету.

Возможно ошибка у меня в коде, но я вроде проверил несколько раз, да и негде там ошибку допустить...

**Comment by AlexRnD61** [comment]
Мои тестовые примеры нормально прошли.

**Comment by SunSerega** [comment]
А, да, у меня было пара ошибок, поправил. Всё правильно читает.

**Comment by AlexRnD61** [comment]
Меня несколько изумили строки в 256 байт, как и попытка в байт записать число 256

**Comment by SunSerega** [comment]
Ну почти, константы всё ещё сохраняет и пытается загрузить. И приватные поля не сохраняет. Но это другие issue.

**Comment by SunSerega** [comment]
>Меня несколько изумили строки в 256 байт, как и попытка в байт записать число 256

Где вы это видите?))

**Comment by AlexRnD61** [comment]
Константы сохранять не надо?

**Comment by SunSerega** [comment]
Константные поля работают как статичные (и статичные константные делать не даёт). И попытка загрузить константное поле вызывает исключение.

**Comment by AlexRnD61** [comment]
Да то так, с перепугу))) 0..255 - это просто 256 комбинаций

**Comment by AlexRnD61** [comment]
что за константное поле, где вы слов таких набрались? ))

**Comment by SunSerega** [comment]
Вот: #1050.
Как не погляди - `r1.c1` там поле. И оно константное.

**Comment by AlexRnD61** [comment]
А, это снова этот сишный @!#$@#%... Констанота - она константа и есть, фига ли ее модифицировать пытаться?

**Comment by SunSerega** [comment]
Так в том и ошибка, что её пытается модифицировать, хотя не должно.

**Comment by AlexRnD61** [comment]
Ну так Вы запись читаете, она свои поля раздает...

**Comment by AlexRnD61** [comment]
Это значит лишь, что не надо пытаться учить старых собак новым штукам. Типизированные файлы задумывались не для того, чтобы классовые поля ублажать, а чтобы обмениваться между файлом и "комбинированными типами" Н.Вирта, которые сейчас зовутся записями, а в приличных языках именовались структурами ))

**Comment by SunSerega** [comment]
Ну, вот я и говорю, надо не через .Net делать костылями, а реализовать именно как задумывалось. И проблемы вроде того что приватные поля записи вообще не видит - никак не исправишь костылями, но если записывать как задумывалось, блоками - всё работает правильно без костылей.

**Comment by miks1965** [comment]
Закрываю
