### ISSUE TITLE
LayoutKind.Explicit сломано для шаблонных записей

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#1045]
```
uses System.Runtime.InteropServices;

type
  [StructLayout(LayoutKind.&Explicit)]
  t1<T>=record
    
  end;

begin end.
```
`Undefined FileName(0) : Поле должно иметь атрибут FieldOffset`

Не важно что поставить в тело `t1`. Будут там поля с `FieldOffset` или нет - всё равно будет выдавать эту ошибку.

+потеря контекста.

**Comment by ibond84** [comment]
Так, запрещаю LayoutKind.&Explicit для генерик-записей. .NET это не поддерживается (выбрасывает TypeLoadException)

**Comment by SunSerega** [comment]
Где это не поддерживается? У меня это компилируется:
```
using System.Runtime.InteropServices;

namespace ConsoleApp6
{
    [StructLayout(LayoutKind.Explicit)]
    struct r1<T>
    {

    }
    class Program
    {
        static void Main(string[] args)
        {
        }
    }
}
```

**Comment by ibond84** [comment]
Ну запустите код (объявив переменную типа r1<int>) и посмотрите результат...

**Comment by SunSerega** [comment]
О как, понятно...
