### ISSUE TITLE
ElementAt(n) - неточность в тексте сообщения об ошибке 

### ISSUE THREAD

**Issue by AlexRnD61** [pascalabcnet/pascalabcnet#1049]
```
begin
  var s := Seq(5, 8, -4, 9, 2, 6, -2, 5).Println;
  s.ElementAt(0).Println;
  s.ElementAt(-1).Println
end.
```
При поиске элемента с номером -1 выдается сообщение

> Program1.pas(4) : Ошибка времени выполнения: Индекс за пределами диапазона. Индекс должен быть положительным числом, а его размер не должен превышать размер коллекции. Имя параметра: index

На самом же деле индексы при обращении к элементам последовательности указываются от нуля и не смогут превышать размера коллекции минус 1. Ноль - это не положительное число, поэтому корректно писать, что индексы должны быть неотрицательными.

**Comment by SunSerega** [comment]
`ElementAt` это встроенный в .Net метод. Это ошибка тех кто переводил ошибку:
```
Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
```
На русский.

**Comment by AlexRnD61** [comment]
Именно так: неверен текст сообщения об ошибке. Если посмотрите в заголовок issure

**Comment by SunSerega** [comment]
Да, но перевод делали не разработчики, я же говорю, это встроено в .Net .

**Comment by miks1965** [comment]
Это к Microsoft. Положительных от неотрицательных чисел отличить не могут
