### ISSUE TITLE
Нельзя наследовать от типа PascalABCCompiler.TreeRealization.compiled_type_node

### ISSUE THREAD

**Issue by miks1965** [pascalabcnet/pascalabcnet#105]
```
type фигня = class(System.DateTime)
end;
```
Плохое сообщение об ошибке
Нельзя наследовать от типа PascalABCCompiler.TreeRealization.compiled_type_node

**Comment by ibond84** [comment]
Такого раньше не было

**Comment by miks1965** [comment]
Ну, я вроде ничего такого не менял
