### ISSUE TITLE
При использовании безымянных вложенных записей выдавать предупреждение, что они не могут захватывать переменные из контекста объемлющего класса

### ISSUE THREAD

**Issue by miks1965** [pascalabcnet/pascalabcnet#1053]
```
type
  TExample<T> = class
    fX: record
          x: T;
        end;
  end;
 
begin
end.
```
Не видит T. Вложенные классы у нас запрещены. А здесь - ляп.

Взято отсюда: http://www.cyberforum.ru/pascalabc-net/thread2312798.html

**Comment by SunSerega** [comment]
А почему обязательно запрещать вложенные безымянные записи, почему это сразу ляп а не фича?

**Comment by AIexandrKotov** [comment]
Запретите использование вложенных обобщённых типов между классами и записями, а не локальные безымянные записи. Последние прекрасно работают. Не хочется создавать мусорные типы для такого. Модификаторов доступа для типов-то ещё нет.

**Comment by miks1965** [comment]
Там не только это - там надо запрещать любой захват из внешнего контекста 
```
type
  A = class
    y: integer;
    fX: record
          x := y;
        end;
  end;
 
begin
end.
```
- а это всю таблицу символов надо перелопачивать

**Comment by AIexandrKotov** [comment]
Только вот эту запись:
```
type
  A = class
    y: integer;
    fX: record
          x := y;
        end;
  end;
 
begin
end.
```
Можно преобразовать в
```
type
  A = class
    y: integer;
    fX: record
          x: integer;
        end;
    constructor (_y: integer);
    begin
      y:=_y;
      fX.x:=y;
    end;
  end;
 
begin
end.
```
И всё прекрасно работает
К тому же, в чём смысл описывать нестатичные переменные на лету?
Безымянные записи отлично работают как мусорка данных, которые нужны по всему проекту.

**Comment by miks1965** [comment]
Да, запретили

В них то же самое:
```
var
  A: record
    y: integer;
    B: record
          x := y;
        end;
    end;
```

**Comment by SunSerega** [comment]
(Ради контекста всё же стоит упомянуть что у @AIexandrKotov сейчас программа на 20к строк всюду юзающая это)

Хотя я лично за то что от таких костылей надо просто избавится.

**Comment by AIexandrKotov** [comment]
> всюду юзающая это

Там просто две записи, которые даже на лету не описываются, с тремя-четырьмя по штук десять вложенными. Я это писал когда ещё "мал" был. Если подобная конструкция будет запрещена, то мне придётся создать сотню другую мусорных типов-записей.

**Comment by miks1965** [comment]
Да, мы понимаем. У нас нет никакой возможности проверять, что внутренние записи захватывают какие-то переменные из контекста внешнего класса. Дело в том, что такие записи создаются во внешнем контексте, несмотря на то, что описываются во внутреннем, поэтому они имеют доступ только ко внешним именам. В этой схеме проверять ошибки доступа к внутренним именам невозможно.

**Comment by AIexandrKotov** [comment]
Тогда обязательно ли брать и запрещать абсолютно все вложенные записи? Может, добавите что-то типа static/abstract у классов, но для записей, что бы дать понять компилятору то, что эта запись может быть вложена в какой-то класс или другую запись и поставить запрет на присвоение на лету переменных внутри этой записи? Только результаты функций, экземпляры классов через new и литералы. А уже в блоке без разницы что там чему присваивается.

**Comment by miks1965** [comment]
Самый нормальный вариант был тот, который был. Вложенные записи просто не видели имён из внешнего класса. Он вам не понравился. И вообщем-то правильно - это неожидаемое поведение.

С другой стороны архитектура компилятора не позволяет проверять имена из внешних классов. Поэтому и запретили.

Все предложения сводятся в итоге к тому чтобы мы как-то это проверяли. Это сложно и нуждается в переделке ощутимой части компилятора.

**Comment by AIexandrKotov** [comment]
Тогда в чём проблема разрешить обратно? В том, что в некоторых особых случаях оно не будет работать? Поставьте что-то вроде предупреждения для вложенных записей, как с **for i**, типа использовать можно, но не рекомендуется.

**Comment by miks1965** [comment]
Можем разрешить обратно. Предупреждение выдавать можно. Если это спасёт ситуацию, то да

**Comment by miks1965** [comment]
Да, это идея

**Comment by AIexandrKotov** [comment]
Я правда за это время уже переписал свой проект, добавив 104 мусорных типа, но да ладно...

**Comment by miks1965** [comment]
104 - это много

**Comment by miks1965** [comment]
Нет, запретили. Вложенные описания классов запрещены.

**Comment by miks1965** [comment]
Сделаем, сделаем
