### ISSUE TITLE
анализатор кода не видит value в расширенных свойствах

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#1056]
```
type
  t1=class
    property p1:byte write writeln(value);
  end;

begin end.
```
Вообще не видит, не в Ctrl+Space, никак. Я думал это в не выпущенных билдах, но вроде теперь уже давно так.

Как раз ещё возможность сделать чтоб его выделяло как `Result`, голубым цветом. Того же вида ведь слово. Значение противоположное, вид тот же, так что логично так же выделять. Это ведь тоже к анализатору кода относится, нет?

**Comment by miks1965** [comment]
Нет.

Сделайте нормальный заголовок. 

Это - не ошибка компиляции. Компилятор всё видит.

**Comment by SunSerega** [comment]
Ну, с тем же успехом вы могли добавить лейбл `Intellisense`, это ведь тоже объясняет что речь идёт только про анализатор кода.

**Comment by ibond84** [comment]
Тем не менее, issues должны быть четко составлены. issues вроде "не видит конструктор" (кто не видит?) нежелательны.

**Comment by SunSerega** [comment]
Хорошо, учту на будущее...
