### ISSUE TITLE
Тихий режим установщика сбивает все настройки

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#1059]
Если запустить установщик паскаля с аргументами командной строки `"/S"` - все настройки редактора собьются. Обычный режим их не сбивает.

Вот пример кода: [PABCNETDownloader.pas.zip](https://github.com/pascalabcnet/pascalabcnet/files/2302788/PABCNETDownloader.zip)

Если в этой программе убрать `"/S"` из аргуметов командной строки - настройки не собьются, но установка будет не в тихом режиме.

**Comment by SunSerega** [comment]
Ага, установщик удаляет файл `PascalABCNET.ini` если запускать его в тихом режиме. Но теперь его мне создаёт в каждой папке, в которой я работаю. Куда его надо кинуть пока вы не исправили, чтоб настройки глобально установились?

**Comment by miks1965** [comment]
Да, забавная проблема. Я вылечил тем, что прописал при установке путь c:\PABCWork.NET

Как избавиться - не знаю. То есть как запретить тихую установку. Потому что в ней происходит что-то невообразимое

**Comment by SunSerega** [comment]
В смысле его (путь) надо передать как параметр? Важно до или после `"/S"`?

**Comment by SunSerega** [comment]
А тихую установку, пока свою не сделаете - запрещать не стоит)).

**Comment by miks1965** [comment]
Я закрываю этот странный Issue.  Установщик - не наш.

Если удалить часть файлов, тоже всё слетит.
