### ISSUE TITLE
Размеры окна в GraphWPF не обновляются при переходе в полно экранный режим

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#1066]
```
uses GraphWPF;

begin
  BeginFrameBasedAnimation(()->begin
    
    Circle(Window.Width-30,Window.Height-30,30);
    
  end);
end.
```
Эта программа рисует круг в нижнем правом углу. Но если развернуть на полный экран (кнопкой сверху справа на окне) - круг рисуется не там, потому что `Window.Width` и `Window.Height` не обновляются.

Интересно что если перейти в полно экранный режим через `Window.Maximize` - всё обновляется.

**Comment by miks1965** [comment]
Вот я боялся, что сюда начнут писать эту библиотечную ерунду. Не знаю. Стандартная оконная компонента возвращает такую Width в немаксимизированном состоянии. Пространство Issues окажется безумно захламлено.

**Comment by miks1965** [comment]
Предлагаю Вам посмотреть самому, в чем там дело. Исходники есть

**Comment by SunSerega** [comment]
Ну, вы можете сделать отдельный репозиторий под `GraphWPF` и хранить там оригинал этого модуля. А в этот репозиторий копировать от туда. В таком случае будет отдельные issue и пуллреквесты под него. Ну, эта ошибка вроде простенькая, не закрывайте уже, сейчас найду.

**Comment by SunSerega** [comment]
Да, нашёл.
Замените `MainWindow.Width` на `MainWindow.ActualWidth`. И так же для высоты и т.п.

**Comment by miks1965** [comment]
Этого мало - там еще отступ примешивается:

```
function WindowTypeGetWidthP := MainWindow.Width - wplus;
```

**Comment by SunSerega** [comment]
Да, их трогать не надо:
```
uses GraphWPF;
uses System.Windows;

var
  wnd:Window;

//Эти 4 функции тупо из GraphWPFBase скопированы
function wplus := SystemParameters.WindowResizeBorderThickness.Left + SystemParameters.WindowResizeBorderThickness.Right;
function hplus := SystemParameters.WindowCaptionHeight + SystemParameters.WindowResizeBorderThickness.Top + SystemParameters.WindowResizeBorderThickness.Bottom;
//но в последних 2 я добавил "Actual"
function WindowTypeGetWidthP := wnd.ActualWidth - wplus;
function WindowTypeGetHeightP := wnd.ActualHeight - hplus;

procedure Redraw;
begin
  Circle(WindowTypeGetWidthP-30,WindowTypeGetHeightP-30,30);
end;

begin
  //Этот костыль вытаскивает `MainWindows` из `GraphWPFBase`.
  wnd := (System.Reflection.Assembly.GetCallingAssembly.GetType('GraphWPFBase.GraphWPFBase').GetField('MainWindow').GetValue(nil) as System.Windows.Window);
  
  BeginFrameBasedAnimation(Redraw);
end.
```
Эта программа рисует как надо.

**Comment by miks1965** [comment]
Сделал
