### ISSUE TITLE
"Файл не найден", при ошибке в не сохранённом файле

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#1070]
1. Открываем IDE через .exe файл (ну или ярлык к нему)
2. Компилируем ничего не написав и не сохранив его никуда (можно и написать что, главное чтоб выдало ошибку)
3. Получаем:
![image](https://user-images.githubusercontent.com/27270190/44423395-b5de8b80-a58e-11e8-91c3-bf33dd75cd24.png)

Это выскочило в 1 из последних билдов.

**Comment by ibond84** [comment]
Не воспроизводится. Как видно из скриншота, слетела рабочая папка. Возможно связано с вашими экспериментами с тихой установкой.

**Comment by miks1965** [comment]
Да, именно так. После тихой установки у меня тоже всё слетело

**Comment by SunSerega** [comment]
@miks1965 вы сказали что указывали `C:\PABCWork.NET` в аргуметах командной строки чтоб не удаляло файл настроек. Как именно? Я делал так:
```
    pr.StartInfo.Arguments := '"/S" "C:\PABCWork.NET"';
```
