### ISSUE TITLE
Не позволяет описывать массивы в формате C#, если тип T их элементов есть generic

### ISSUE THREAD

**Issue by MrSpecular** [pascalabcnet/pascalabcnet#1072]
```
begin
  new Dictionary&<byte, byte>[0];
end.
```
Workaround:
```
type
  T = Dictionary<byte, byte>; // <--
  
begin
  new T[0];
end.
```
Доказательство:
```
begin
  new System.Collections.ArrayList[0]; // Компилируется, ArrayList - не generic.
end.
```

**Comment by miks1965** [comment]
Ну да, правильно. Так по грамматике. В new T[n] T является или именем или именем с точками. Для чего-то более сложного - введите синоним имени как Вы и сделали.

Это - ограничение синтаксиса, это не ошибка.

**Comment by MrSpecular** [comment]
Понял. А рассматриваете ли Вы такое предложение как выделить это в отдельную ошибку и явно говорить это пользователю?

**Comment by miks1965** [comment]
Если все тесты пройдут, расширю синтаксис

**Comment by miks1965** [comment]
Сделал. Теперь можно
```
var a := new Dictionary<integer,integer>[10];
```
