### ISSUE TITLE
Неадекватная реакция IDE при переименовании файла-пространства имён [cyberforum]

### ISSUE THREAD

**Issue by MrSpecular** [pascalabcnet/pascalabcnet#1075]
[Источник](http://www.cyberforum.ru/pascalabc-net/thread2312276-page2.html)

**Comment by SunSerega** [comment]
Пространства имён ещё не готовы. Для них не сделали [анализатор кода](https://github.com/pascalabcnet/pascalabcnet/issues/510), поэтому переименование и форматирование будут работать криво. Когда сделают анализатор кода - само исправится. Поэтому закройте.

**Comment by MrSpecular** [comment]
> Поэтому закройте.
Почему нельзя оставить **Issue** открытой до момента исправления? Ведь, **Issue** будет напоминать разработчикам, что еще не сделано.

**Comment by SunSerega** [comment]
Да, но это дубыль #510. На 1 проблему - 1 issue.

**Comment by MrSpecular** [comment]
[Intellisense для пространств имен](https://github.com/pascalabcnet/pascalabcnet/issues/510)
