### ISSUE TITLE
Переименование класса, записи, перечислимого типа, синонима типа (псевдонима) или типа функции/процедуры в PascalABC.Net в модуле работает неправильно, независимо от того, указан ли тип в формате ИмяМодуля.Тип или просто Тип во втором модуле. [cyberforum]

### ISSUE THREAD

**Issue by MrSpecular** [pascalabcnet/pascalabcnet#1076]
[Источник](http://www.cyberforum.ru/pascalabc-net/thread2312276-page2.html)

Первый модуль:
```
unit TestUnit;
 
type
  __TSomeName = class
  end;
end.
```
Второй модуль:
```
unit TestUnit2;
uses TestUnit;
 
type
  TA = TestUnit.__TSomeName;
end.
```

**Comment by miks1965** [comment]
Скопируйте тексты программ. Еще лучше упростите их

**Comment by MrSpecular** [comment]
На мой взгляд, они уже упрощены. Не совсем Вас понял, как их можно было бы упростить?

**Comment by SunSerega** [comment]
>На мой взгляд, они уже упрощены. Не совсем Вас понял, как их можно было бы упростить?

Если так считайте - просто скопируйте, не упрощая. Но уже не надо:

>TestUnit.pas:
>```
>unit TestUnit;
> 
>type
>  __TSomeName = class
>  end;
>end.
>```
>TestUnit2.pas:
>```
>unit TestUnit2;
>uses TestUnit;
> 
>type
>  TA = TestUnit.__TSomeName;
>end.
>```
>Нажимаем ПКМ над __TSomeName в TestUnit и набираем имя "MyType".
В TestUnit2.pas получаем:
>```
>unit TestUnit2;
>uses TestUnit;
> 
>type
>  MyTypeTSomeName;
>end.
>```
>если откатить изменение в TestUnit2, то получим:
>```
>unit TestUnit2;
>uses TestUnit;
> 
>type
>  MyTypeit.__TSomeName;
>end.
>```
>, откатив еще раз, вернем коду нормальный вид.

Прошу обратить внимание, что пример про классы, но из названия понятно что это много ещё с чем работает. Когда будете исправлять - протестируйте ещё с перечислимыми типами и т.п.

**Comment by MrSpecular** [comment]
@SunSerega, в теме [Ошибки PascalABC.Net](http://forum.mmcs.sfedu.ru/t/oshibki-pascalabc-net/126/1956) я писал:

> Я **проверял** перед отправкой на GitHub. У меня они воспроизводятся.

**Comment by SunSerega** [comment]
Ну хорошо, но исходники и описание проблемы локально надо всё равно сохранить всё равно.
