### ISSUE TITLE
Неправильно выводится тип ключей и значений словаря, создаваемых через функцию Dict [intellisence]

### ISSUE THREAD

**Issue by MrSpecular** [pascalabcnet/pascalabcnet#1077]
```
begin
  var d0 := Dict&<byte, byte>(KV&<byte, byte>(0, 0)); // Все правильно, так как тип ключей и значений указан явно.
  var d1 := Dict(KV&<byte, byte>(0, 0)); // Отображает Dictionary<KeyValuePair<byte, byte>, KeyValuePair<byte, byte>>, вместо Dictionary<byte, byte>.
end.
```

![image](https://user-images.githubusercontent.com/42602899/44461888-567a8d00-a61b-11e8-8524-066168104f91.png)

Тот же самый эффект при немного упрощенном коде:

```
begin
  var d0 := Dict&<integer, integer>(KV(0, 0));
  var d1 := Dict(KV(0, 0));
end.
```

**Comment by miks1965** [comment]
Это не ошибка компилятора. Вывод типов это в первую очередь компилятор

**Comment by MrSpecular** [comment]
Я понимаю. Это проблема intellisence.

**Comment by SunSerega** [comment]
Да, мне тоже об этом недавно писали. Если не написано проблема чего - считается что проблема компилятора. Исправьте в названии issue что проблема именно анализатора кода (intellisence-а).

**Comment by ibond84** [comment]
Уже есть issue
