### ISSUE TITLE
Возможность вызова метода без скобочек - неоднозначная ситуация

### ISSUE THREAD

**Issue by MrSpecular** [pascalabcnet/pascalabcnet#1078]
```
function F() := 1;

begin
  var (x, y) := (F, F());
  Writeln($'x.GetType() = {x.GetType()}, y.GetType() = {y.GetType()}');
  Writeln($'x = {x}, y = {y}');
end.
```
Повторюсь, можно было бы предположить, что **x** - ссылка на подпрограмму-функцию **F**, но это не так - это **результат ее выполнения.** Предлагаю устранить неоднозначность в плане вызова подпрограмм следующим образом - запретить вызывать подпрограммы без скобочек. Данное ограничение есть в C#, оно _позволяет избегать подобных неоднозначных моментов_.

**Comment by SunSerega** [comment]
Обсуждения проходят [тут](http://forum.mmcs.sfedu.ru/t/zamechaniya-i-predlozheniya/143/979). А в issue надо заливать только то - что однозначно ошибка. Но вообще именно эту тему уже давно обсуждали и пришли к выводу что в паскале всегда если неоднозначный момент - это вызов функции.

**Comment by MrSpecular** [comment]
@SunSerega, да, конечно, обсуждения, как я вижу, уже были на эту тему. Но повод ли это оставить эту неоднозначность и искать другие ошибки? На мой взгляд, чем меньше неоднозначностей, тем легче учащимся воспринимать материал. Поэтому, если это возможно, я бы оставил эту Issue открытой до окончательного решения этого вопроса. Тем более мы с @Gleb уже это обсуждали сегодня, он считает это ошибкой. Мое мнение - такое же. Неоднозначность - не самое приятное явление.

**Comment by miks1965** [comment]
> запретить вызывать подпрограммы без скобочек

Сразу закрываю. Не пишите такое больше
