### ISSUE TITLE
Ошибка с Ctrl+Z

### ISSUE THREAD

**Issue by MrSpecular** [pascalabcnet/pascalabcnet#1079]
Пусть повисит, пока не будет исправлена. Так меньше вероятность о ней забыть, если она в открытых Issue.

**Comment by SunSerega** [comment]
@miks1965 а действительно, добавьте лэйбл `wontfix`, но пусть висит. Может когда то и соберётесь ловить.

**Comment by miks1965** [comment]
Я знаю её. Если бы я знал как ее проклятую найти

**Comment by miks1965** [comment]
В какой строчке хотя бы?

**Comment by SunSerega** [comment]
Ну смотрите. На сколько я помню - ошибка Ctrl+Z вызывает исключение, которое обрабатывается только в последний момент. Как насчёт того, чтоб перед тем как вызвать окно в котором говорится что произошла ошибка - проверить не было ли нажато Ctrl+Z недавно. Если было - вывести подробное описание того что происходило и попросить отправить эту информацию разработчикам.

**Comment by MrSpecular** [comment]
Справедливости ради стоит заметить, что после того, как появляется окно с данной ошибкой редактирование текущего файла невозможно. Остается лишь комбинациями клавиш скопировать и перенести код в новую вкладку.

**Comment by SunSerega** [comment]
Это не относится к тому как найти причину ошибки. Смягчать симптомы тоже стоит, но это не тут.

**Comment by miks1965** [comment]
Еще раз, если не будет конкретики: скриншота, при каких условиях происходит, можно ли как то прогнозируемо получить, я снесу этот Issue. Потому что нельзя бороться с несуществующим

**Comment by miks1965** [comment]
Я еще немного жду. Если никто не отловит ошибку с Ctrl-Z, её не существует. Скриншот и условия.

**Comment by SunSerega** [comment]
Можете пока закрыть, если обсуждение на форуме будет.

**Comment by miks1965** [comment]
Я жду скринов. После этого сделаю debug-версию и снова буду ждать скринов

**Comment by SunSerega** [comment]
http://forum.mmcs.sfedu.ru/uploads/default/optimized/2X/0/01abb44c0e9990a8aa0b7c5671909a82f6783af7_1_690x387.png

**Comment by SunSerega** [comment]
Если бы у меня ещё гитхаб работал... Даёт только отправлять, и писать...

Ну в общем этот скрин отсюда: http://forum.mmcs.sfedu.ru/t/neulovimaya-oshibka-ctrl-z-pravda-ili-mif/2421/12?u=sun_serega

Мне удалось сегодня воспроизвести этот баг, но только 1 раз и только после того как я изнасиловал IDE кликером. Там же я сказал что, по моему, является причиной и как можно исправить. Хотя исходники я не смотрел, это лишь спекуляция, так что лучше перепроверьте.
