### ISSUE TITLE
Не позволяет использовать синтаксис кортежей (Item1, Item2, ...) для возврата кортежа двух функций или процедур

### ISSUE THREAD

**Issue by MrSpecular** [pascalabcnet/pascalabcnet#1084]
```
function F(): (() -> byte, () -> byte);
begin
  Result := (() -> 0, () -> 0);
end;
              
begin
end.
```
При этом, выдается **неправильная** ошибка:
> Program11.pas(3) : Встречено ')', а ожидалось выражение

@Admin предложил решение - использовать явно **System.Tuple<T, T1, ...>**:
```
function F(): (() -> byte, () -> byte);
begin
  Result := new System.Tuple&<() -> byte, () -> byte>(() -> 0, () -> 0);
end;
              
begin
end.
```
Справедливости ради, стоит заметить, что с **Action'ами** похожая история:
```
function F(): () -> (() -> (), () -> ());
begin
  //Result := () -> new System.Tuple&<() -> (), () -> ()>(procedure() -> exit, procedure() -> exit);
  Result := () -> (procedure() -> exit, procedure() -> exit); // Program11.pas(4) : Встречено 'procedure', а ожидалось выражение
end;
              
begin
end.
```

**Comment by miks1965** [comment]
Поэкспериментировать с грамматикой. Может, и получится

**Comment by MrSpecular** [comment]
Протестировал и с **Action'ами**. История похожая. Так как ошибки, на мой взгляд, родственные, то не буду создавать отдельный **Issue**.

```
function F(): () -> (() -> (), () -> ());
begin
  //Result := () -> new System.Tuple&<() -> (), () -> ()>(procedure() -> exit, procedure() -> exit);
  Result := () -> (procedure() -> exit, procedure() -> exit); // Program11.pas(4) : Встречено 'procedure', а ожидалось выражение
end;
              
begin
end.
```

**Comment by miks1965** [comment]
Да, придётся отказаться от идеи использовать в кортежах лямбды. Грамматика сразу сильно конфликтует.

**Comment by SunSerega** [comment]
Тогда сделайте объясняющую ошибку.

**Comment by miks1965** [comment]
Это невозможно. Если грамматика ожидала увидеть end вместо (, по этому невозможно понять контекст и сделать объясняющую ошибку. Объясняющую ошибку можно делать на семантическом уровне когда мы всё в грамматике уже разобрали
