### ISSUE TITLE
Некорректность в Справке

### ISSUE THREAD

**Issue by AlexRnD61** [pascalabcnet/pascalabcnet#1086]
В Справке (Методы расширения одномерных динамических массивов) указано;

> function FindLastIndex<T>(Self: array of T; p:  T->boolean): integer;
> Выполняет поиск индекса последнего  элемента в массиве, удовлетворяющего предикату. Если не найден, возвращается  нулевое значение соответствующего типа

На самом деле в этом случае возвращается -1.

> function FindLastIndex<T>(self: array of T;  start: integer; p: T->boolean): integer;
> Выполняет поиск  индекса последнего элемента в массиве, удовлетворяющего предикату, начиная с  индекса start. Если не найден, возвращается нулевое значение соответствующего  типа
> 

На самом деле должно быть что-то типа

function FindLastIndex<T>(self: array of T;  end: integer; p: T->boolean): integer;
Выполняет поиск  индекса последнего элемента в массиве, удовлетворяющего предикату, просматривая элементы от первого и не далее индекса end. Если не найден, возвращается -1.

**Comment by miks1965** [comment]
Да
