### ISSUE TITLE
Улучшить пространства имён

### ISSUE THREAD

**Issue by MrSpecular** [pascalabcnet/pascalabcnet#1087]
1) Позволить описываться нескольким пространствам имён в [одном файле](http://forum.mmcs.sfedu.ru/t/moduli-vs-namespaces/2406/106).
2) Позволить размещать одно пространство имён в различных файлах.

Думаю, что лучше будет, если данная **Issue** повисит, так как в этом случае разработчики гарантированно **не** забудут об этом.

**Comment by miks1965** [comment]
Первое под вопросом.

Я писал на форуме, что в Oxygene принято другое решение. 

Второе вроде сделано как пишет ibond. Только я синтаксиса не знаю.

**Comment by miks1965** [comment]
Еще раз. Неконкретные, неоформленные Issue я буду сносить. Прошу также их не делать. Вначале надо договориться о синтаксисе и семантике namespaceов. Потом заводить Issue. Конкретный. Или  несколько маленьких конкретных. Не наоборот.
