### ISSUE TITLE
Не работает предописание шаблонных классов. 

### ISSUE THREAD

**Issue by miks1965** [pascalabcnet/pascalabcnet#109]
```
type 
  A<T> = class;
  B = class
    a1: A<integer>;
  end;
  A<T> = class
  end;
begin
end.  
```
Для обычных работает

**Comment by ibond84** [comment]
Интересно, а как это может работать, если например where идет только при полном описании класса. Я считаю, что ошибки нет. Конечно, все эти атавизмы 80-х годов мешают. Я бы вообще отменил эти предописания классов. Анализировать надо в два прохода.

**Comment by miks1965** [comment]
Да. Закрываем
