### ISSUE TITLE
Не может неявно преобразовать тип T1 в T2, если это тип элемента кортежа

### ISSUE THREAD

**Issue by MrSpecular** [pascalabcnet/pascalabcnet#1090]
```
type
  TA = class
    property P: byte read 1;
  end;
  
  TB = class
    property P: (byte, byte) read (1, 1); // Program9.pas(8) : Нельзя преобразовать тип Tuple<integer,integer> к Tuple<byte,byte>
  end;

begin
end.
```
```
    type
      TA = class
        property P: real read 1;
      end;
      
      TB = class
        property P: (real, real) read (1, 1); // Program9.pas(7) : Нельзя преобразовать тип Tuple<integer,integer> к Tuple<real,real>
      end;
    
    begin
    end.
```
```
    type
      TA = class
        property P: string read '1';
      end;
      
      TB = class
        property P: (string, string) read ('1', '1'); // Program9.pas(7) : Нельзя преобразовать тип Tuple<char,char> к Tuple<string,string>
      end;
    
    begin
    end.
```
```
type
  TFirst = class
  end;
  
  TSecond = class(TFirst)
  end;
  
type
  TA = class
    property P: TFirst read new TSecond();
  end;
  
  TB = class
    property P: (TFirst, TFirst) read (new TSecond(), new TSecond()); // Program9.pas(15) : Нельзя преобразовать тип Tuple<TSecond,TSecond> к Tuple<TFirst,TFirst>
  end;

begin
end.
```
```
type
  TA = class
    function P(): byte := 1;
  end;
  
  TB = class
    function P(): (byte, byte) := (1, 1); // Program10.pas(7) : Нельзя преобразовать тип Tuple<integer,integer> к Tuple<byte,byte>
  end;

begin
end.
```
```
type
  TA = class
    function P(): string := '1';
  end;
  
  TB = class
    function P(): (string, string) := ('1', '1'); // Program10.pas(7) : Нельзя преобразовать тип Tuple<char,char> к Tuple<string,string>
  end;

begin
end.
```
```
type
  TA = class
    function P(): real := 1;
  end;
  
  TB = class
    function P(): (real, real) := (1, 1); // Program10.pas(7) : Нельзя преобразовать тип Tuple<integer,integer> к Tuple<real,real>
  end;

begin
end.
```
```
type
  TFirst = class
  end;
  
  TSecond = class(TFirst)
  end;

type
  TA = class
    function P(): TFirst := new TSecond();
  end;
  
  TB = class
    function P(): (TFirst, TFirst) := (new TSecond(), new TSecond()); // Program10.pas(14) : Нельзя преобразовать тип Tuple<TSecond,TSecond> к Tuple<TFirst,TFirst>
  end;

begin
end.
```

**Comment by miks1965** [comment]
Ну собственно в C# это тоже не работает:
```
(double a, double b) = new Tuple<int, int>(1, 2);
```

**Comment by MrSpecular** [comment]
В C# работает это:
```
class MainClass
{
	public (byte, byte) P1 => (1, 1);

	public (double, double) P2 => (1, 1);

	public static void Main (string[] args)
	{
	}
}
```

**Comment by miks1965** [comment]
Возможно. Но тогда кортежи на уровне языка перестанут работать у тех, у кого стоит .NET 4.0

**Comment by spectatorBH** [comment]
> сделать так, чтобы кортежи с синтаксисом (Item1, Item2, ...) основывались на System.ValueTuple<T, T2, ...>? Не уверен, но, возможно, это решило бы эту проблему.

Этот вопрос уже подымался недавно на [форуме](http://forum.mmcs.sfedu.ru/t/valuetuple-ili-tuple/2355/14), хотя и в несколько ином контексте, но разработчики пока не определились, что с этим делать. Но проблема отсутствия типа ValueTuple в .NET ниже 4.7, по-моему, элементарно решается принудительным включением в состав инсталлятора (или скачиванием уже во время инсталляции через nuget) свежей версии [пакета System.ValueTuple](https://www.nuget.org/packages/System.ValueTuple/) (после проверки установленной макс. версии .NET на клиенте), как, собственно, и [рекомендует всем делать сам MS](https://docs.microsoft.com/ru-ru/dotnet/csharp/tuples).

**Comment by spectatorBH** [comment]
Кстати, почему (1, 1) у нас приводится к (integer, integer), а не к (byte, byte)? Вроде бы логично брать _наименьший общий тип_, способный хранить значения констант.

**Comment by miks1965** [comment]
Микрософт может рекомендовать что угодно. Но мы ставим базовую версию NET - она у нас входит в инсталлят. И - заметьте, что программы наши откомпилированные будут работать на всех компьютерах где установлена NET 4.0 и где есть обычные пользователи, которые не понимают что такое нугет и зачем что-то надо им самим докачивать.

Еще раз - я не против ValueTuple, но на многих компьютерах PascalABC.NEt просто перестанет работать. Ну как Вам еще это объяснить?

**Comment by spectatorBH** [comment]
Не перестанет -- если этого типа не хватает на конкретной платформе, его можно легко получить рекомендуемым методом -- недостающий в системе пакет можно доставить автоматом в процессе инсталляции Паскаля для тех клиентов, у которых версия .NET < 4.7. 

Можно скачивать его через nuget в процессе сборки инсталлята или уже в процессе самой инсталляции (nuget у вас уже входит в инсталлят, хоть и не самый свежий). Это все будет работать и на XP -- в чем тут невозможность?

**Comment by spectatorBH** [comment]
Хотя нет, сорри, немного поторопился -- вроде бы минимальная *официально* поддерживаемая версия фреймфорка для этого пакета = 4.5, т.е. возможность его работы под XP на .NET 4.0 пока что под вопросом -- надо проверять (т.к. версия 4.0 и XP официально сняты с поддержки, но это еще не значит, что в них обязательно чего-то не хватает или реально не будет работать). 

Может быть сделать поддержку ValueTuple на уровне отдельной директивы, если станет окончательно понятно, что XP + .NET 4.0 не совместимы с ним никак?

**Comment by miks1965** [comment]
Приведите примеры хорошей производительности ValueTupe

**Comment by spectatorBH** [comment]
Вот вам пример на многократное структурное сравнение кортежей из 3-х элементов. У меня разница в Release варианте иногда достигает 450 (!) раз. Конечно, это синтетика, но отчетливо показывает потенциал статической ValueTuple для некоторых алгоритмов.
```
uses 
  System.Diagnostics;
const
  Cycles = 10000000;
type 
  MyTuple1 = System.Tuple<integer, real, char>;
  MyTuple2 = System.ValueTuple<integer, real, char>;

begin
  var sw1 := Stopwatch.StartNew();
  var a1 := new MyTuple1(123, 1.23, 'a');
  var b1 := new MyTuple1(123, 1.23, 'a');
  loop Cycles do
    if a1 = b1 then;
  sw1.Stop();
  Println('Tuples =', sw1.ElapsedMilliseconds / 1000);
  
  var sw2 := Stopwatch.StartNew();
  var a2 := new MyTuple2(321, 3.21, 'z');
  var b2 := new MyTuple2(321, 3.21, 'z');
  loop Cycles do
    if a2 = b2 then;
  sw2.Stop();
  Println('ValueTuples =', sw2.ElapsedMilliseconds / 1000);
  
  Println($'Ratio = {sw1.ElapsedTicks/sw2.ElapsedTicks :f2}');
end.
```

**Comment by ibond84** [comment]
Закрываю, генерики в паскале инвариантны. ValueTuple как стандарт можно будет ввести, когда XP вымрет.

**Comment by miks1965** [comment]
А тут ValueTuples хуже:
```
uses 
  System.Diagnostics;
const
  Cycles = 100000000;
type 
  MyTuple1 = System.Tuple<integer, real, char>;
  MyTuple2 = System.ValueTuple<integer, real, char>;

begin
  var sw1 := Stopwatch.StartNew();
  var a1 := new MyTuple1(123, 1.23, 'a');
  
  loop Cycles do
  begin
    var b1 := new MyTuple1(123, 1.23, 'a');
    a1 := b1;
  end;
    
  sw1.Stop();
  Println('Tuples =', sw1.ElapsedMilliseconds / 1000);
  
  var sw2 := Stopwatch.StartNew();
  var a2 := new MyTuple2(321, 3.21, 'z');
  
  loop Cycles do
  begin
    var b2 := new MyTuple2(321, 3.21, 'z');
    a2 := b2;
  end;
    
  sw2.Stop();
  Println('ValueTuples =', sw2.ElapsedMilliseconds / 1000);
  
  Println($'Ratio = {sw1.ElapsedTicks/sw2.ElapsedTicks :f2}');
end.
```
У меня раза в полтора

**Comment by SunSerega** [comment]
Ну правильно, в первом случае ведь вы ничего не делаете, кроме копирования ссылки. А во втором - копируются все значения. Но это редкая операция, большие value-типы надо как var параметры всегда передавать так то, то есть по ссылке, тоже.

**Comment by miks1965** [comment]
А, понятно
