### ISSUE TITLE
Компилятор не может подставить "char.IsDigit" в "sequence of char.All"

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#1093]
```
begin
  var s := '1234';
  writeln(s.All(char.IsDigit));
end.
```
1 из перезагрузок `char.IsDigit` - принимает `char` и возвращает `boolean`, поэтому это должно работать.

**Comment by MrSpecular** [comment]
@SunSerega, если явно указать тип параметра:
`writeln(s.All&<char>(char.IsDigit));`
, то компилируется. Но, не думаю, что это удобно (указывать явно).

**Comment by SunSerega** [comment]
Ну как решение это действительно не очень. А вот как ещё 1 доказательство что это таки ошибка - большое спасибо))

**Comment by miks1965** [comment]
Это не ошибка, а слабый вывод типов. Слабее чем в C#

**Comment by MrSpecular** [comment]
Предлагаю его улучшить, чтобы стал сильнее. :)

**Comment by MrSpecular** [comment]
Создал [тему](http://forum.mmcs.sfedu.ru/t/slabyj-vyvod-tipov-reshenie-voprosa/2423), посвященную специально этому вопросу.

**Comment by MrSpecular** [comment]
Было бы полезно узнать как у Вас автовыводятся типы.

**Comment by miks1965** [comment]
Тут не только автовывод типов, тут выбор перегруженной версии функции. Алгоритм этот сложен, не берусь его приводить полностью. Кстати, в C# это также не сделано.

**Comment by miks1965** [comment]
Здесь я думаю когда один параметр - ситуация проста, и можно исправить. Но надо смотреть.

**Comment by miks1965** [comment]
Я имею в виду, что нигде в документации C# не приведен исчерпывающий алгоритм вывода типов при перегрузке

**Comment by miks1965** [comment]
Кстати, если интересно, почитайте вот это:
http://pascalabc.net/wiki/index.php?title=%D0%92%D1%8B%D0%B2%D0%BE%D0%B4_%D1%82%D0%B8%D0%BF%D0%BE%D0%B2_%D0%BF%D1%80%D0%B8_%D0%B2%D1%8B%D0%B7%D0%BE%D0%B2%D0%B5_%D0%BE%D0%B1%D0%BE%D0%B1%D1%89%D0%B5%D0%BD%D0%BD%D1%8B%D1%85_%D0%BC%D0%B5%D1%82%D0%BE%D0%B4%D0%BE%D0%B2_%D1%81_%D0%BB%D1%8F%D0%BC%D0%B1%D0%B4%D0%B0%D0%BC%D0%B8_%D0%B8_%D0%BF%D0%B5%D1%80%D0%B5%D0%B3%D1%80%D1%83%D0%B7%D0%BA%D0%BE%D0%B9_%D1%84%D1%83%D0%BD%D0%BA%D1%86%D0%B8%D0%B9

**Comment by ibond84** [comment]
https://github.com/pascalabcnet/pascalabcnet/actions/runs/475964123
