### ISSUE TITLE
Запретить array, file, set of (рекурсивно) record end в параметрах подпрограмм

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#1103]
```
type
  t1 = class 
    
    constructor := exit;//Ошибка: Предописание функции без описания
    
    procedure p1(a: array of record end) := exit;
    
  end;

begin end.
```

**Comment by MrSpecular** [comment]
@SunSerega, в этом случае такая же реакция:
```
    //...
    constructor Create();
    begin
    end;
    //...
```

**Comment by SunSerega** [comment]
Ну да, не обязательно короткая запись. Ну тут ошибка то в не том. Ошибка в том - что позволяет объявится приватную запись тут.

**Comment by MrSpecular** [comment]
@SunSerega, на мой взгляд, здесь сразу две ошибки:
1) Выдает ошибку с конструктором.
2) И, как Вы правильно сказали, позволяет создавать приватную запись.
. Кстати, если убрать приватную запись - никакой ошибки с конструктором не будет.

**Comment by MrSpecular** [comment]
@miks1965, а как Вы проводите границу между **small bug** и **bug**?

**Comment by miks1965** [comment]
В данном случае ошибка лежит на задворках (в реальной жизни написать такое трудно) и просто исправляется.

А вообще - субъективно.

**Comment by miks1965** [comment]
Надо запретить запись record ... end везде кроме объявления типа.
