### ISSUE TITLE
Нелогичные запреты-разрешения инициализаторов массивов

### ISSUE THREAD

**Issue by miks1965** [pascalabcnet/pascalabcnet#1105]
Так можно
```
var a := new byte[](1, 2, 3, 4, 5);
```
Так нельзя
```
var c := new byte[,]((1, 2), (3, 4), (5, 6));
```
Привести в соответствие.
Думаю, запретить первое. И так много способов.

**Comment by MrSpecular** [comment]
Не думаю, что стоит отказываться от этого функционала, если можно доработать второй.

**Comment by miks1965** [comment]
Наверное. Я написал об этом на форуме.

Но проблема, что такое непонятно как инициализировать:
```
var c := new Tuple<integer,integer>[]((1, 2), (3, 4), (5, 6));
```
Njxytt xnj,s bybwbfkbpbhjdfnm? yflj uke,jrj fyfkbpbhjdfnm nbg/ Gjnjve xnj ytzdyst bybwbfkbpfnjhs vfccbdjd b rjhnt;b rjyrehbhe.n/

**Comment by ibond84** [comment]
Ну, массивы важнее кортежей

**Comment by MrSpecular** [comment]
@miks1965, попробовал так:
```
begin
  var c := new System.Tuple<integer, integer>[](Rec(1, 2), Rec(3, 4), Rec(5, 6));
end.
```
, компилятор упал:
![image](https://user-images.githubusercontent.com/42602899/44629574-09b7ee80-a95a-11e8-9b9e-623734345efa.png)
.

**Comment by miks1965** [comment]
Ну, это баг. Падение - это баг

**Comment by miks1965** [comment]
Так всё работает:
```
begin
  var c := new byte[3,2]((1, 2), (3, 4), (5, 6));
  c.Println
end.
```
В 2-мерном случае надо указывать размерности явно.

Закрываю Issue

**Comment by MrSpecular** [comment]
> В 2-мерном случае надо указывать размерности явно.
Как-то неравномерно: в одномерном это делать **необязательно**, в двумерном - **обязательно**. **Неравномерность** может создать трудности в обучении, а главное породить такие вопросы как **Почему это так**?

**Comment by miks1965** [comment]
Здесь всё логично. Вы сами видели, что в одномерном случае посчитать количество элементов - не проблема. В двумерном уже могут быть разные размерности - и неочевидно, что делать. поэтому в n-мерном запрещены. Можем запретить в одномерном, но это представляется необязательным.

**Comment by MrSpecular** [comment]
В C# размерность первой строки матрицы диктует размерности остальных строк:
```
using System;

class MainClass
{
  public static void Main (string[] args)
	{
    int[,] x = new int[,] {{1, 2}, {1, 2, 3}}; // main.cs(7,36): error CS0847: An array initializer of length `2' was expected
		int[,] y = new int[,] {{1, 2, 3}, {1, 2}}; // main.cs(8,37): error CS0847: An array initializer of length `3' was expected
  }
}
```
.
