### ISSUE TITLE
Грамматические ошибки при virtual в интерфейсе

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#1111]
```
type
  I1=interface
    procedure p1; virtual;
  end;

begin end.
```
Ошибка: Данн**ЫЙ** а**ТТ**рибут**Ы** недопустим в интерфейсе

Хотя, конечно, непонятно ещё ошибка ли то что это запрещено)).

**Comment by miks1965** [comment]
Да, спасибо
