### ISSUE TITLE
"Нельзя объявить указатель на запись, содержащую ссылочные поля" даже если ссылочное поле статично

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#1114]
```
type
  r1=record
    class o := new object;
  end;

begin
  var ptr: ^r1;//Ошибка: Нельзя объявить указатель на запись, содержащую ссылочные поля
end.
```

**Comment by MrSpecular** [comment]
Разве это неправильно?

**Comment by SunSerega** [comment]
Их не может содержать потому - что сборщик мусора может менять ссылки, и тогда начинается куча проблем с указателями на запись содержащую эту ссылку. А в данном случае - ссылочный объект статичен, он никак не касается экземпляров типа `r1`. Это поле работает во всём как глобальное, кроме факта что нужно написать `r1.` чтоб получить доступ к нету.

**Comment by MrSpecular** [comment]
Спасибо, не знал этого в отношении классовых полей.

**Comment by miks1965** [comment]
У нас всё попало под раздачу.

Нечего даже зарождать мысль, что допустимо смешивать ссылки и указатели
