### ISSUE TITLE
Требует ставить & при явном указании шаблонных параметров подпрограммы

### ISSUE THREAD

**Issue by MrSpecular** [pascalabcnet/pascalabcnet#1115]
```
begin
  Lst<byte>(1); // Program2.pas(2) : Встречено '<', а ожидалось ';'
end.
```

**Comment by SunSerega** [comment]
В первых 2 случаях это имя класса, и в нём всегда не обязательно ставить `&`.
А то что заставляет его ставить для последнего случаях, того что с функцией - это потому что разработчики не могут заставить его без `&` работать.

**Comment by MrSpecular** [comment]
Разве этот вопрос снят, чтобы закрывать Issue?

**Comment by miks1965** [comment]
Этот вопрос многократно пояснялся и снят. В грамматике срабатывает < . Это известная проблема во всех компиляторах.

**Comment by SunSerega** [comment]
Если бы до него ещё не было бы так сложно дотягиваться)))

**Comment by MrSpecular** [comment]
> Если бы до него ещё не было бы так сложно дотягиваться)))
На то он и C# - неповторимый и единственный. :)

**Comment by SunSerega** [comment]
Я про `&`.
