### ISSUE TITLE
Не требует & перед ключевым словом

### ISSUE THREAD

**Issue by MrSpecular** [pascalabcnet/pascalabcnet#1121]
```
function &if(x: byte) := exit;

begin
  var x := System.Type.EmptyTypes; // Работает и без &.
  &if(1); // Обязательно &.
end.
```

**Comment by miks1965** [comment]
После точки это уже не ключевое слово. Можно не использовать &. 
А отдельный идентификатор - нужно. 

Я не знаю, как Вам лучше поступать. Но заводить Issue в этом случае неправильно. По-существу, это вопрос. Ну, задайте мне его в личку на форуме

**Comment by MrSpecular** [comment]
Хорошо.
