### ISSUE TITLE
Ключевое слово generictypeof для получения типов без учёта их шаблонных параметров

### ISSUE THREAD

**Issue by MrSpecular** [pascalabcnet/pascalabcnet#1122]
Предлагаю ввести ключевое слово **generictypeof** для получения типов **без** учёта их шаблонных параметров.
```
begin
  var x := new List<byte>();
  //Writeln(x.GetType().GetGenericTypeDefinition() = typeof(List<>)); // List<> - не тип в контексте компилятора PascalABC.Net.
  Writeln(x.GetType().GetGenericTypeDefinition() = typeof(List<byte>).GetGenericTypeDefinition());
  //Writeln(x.GetType().GetGenericTypeDefinition() = generictypeof(List<byte>)); // При введении данного ключевого слова, выше написанная строчка, могла бы выглядеть так.
end.
```

**Comment by miks1965** [comment]
А зачем? И есть ли что то подобное в c#?

**Comment by MrSpecular** [comment]
В C#, например, **Dictionary<>** является типом, а значит **можно** проверить на соответствие типов так:
```
var list = new Dictionary<int, string>();
var type = list.GetType().GetGenericTypeDefinition();
Console.WriteLine(type == typeof(Dictionary<,>));
```
. В **PascalABC.Net** это - **не** тип, а значит, проверить так на соответствие не получится. Тем более, если вызывать GetGenericTypeDefinition() явно, то строка кода сильно растягивается.

**Comment by ibond84** [comment]
Лучше разрешить ```typeof(T<,>)```

**Comment by MrSpecular** [comment]
@ibond84, поддерживаю. Мне переименовать этот Issue, или создать новый?

**Comment by ibond84** [comment]
Создайте новый

**Comment by MrSpecular** [comment]
[Созданный Issue](https://github.com/pascalabcnet/pascalabcnet/issues/1125).
