### ISSUE TITLE
Убрать определение типа через StartsWith, заменив его на определение типа через GetGenericTypeDefinition

### ISSUE THREAD

**Issue by MrSpecular** [pascalabcnet/pascalabcnet#1123]
[Здесь ](https://github.com/pascalabcnet/pascalabcnet/commit/e9fbcc473f3f5e04fe19df3f63012c71348afe65)я привёл аргумент **в пользу** использования **GetGenericTypeDefinition**. Предлагаю **оставить** эту **Issue**, подправив исходный код компилятора _при наличии свободного времени и желания_.

**Comment by miks1965** [comment]
Приведите код, как это сделать. А лучше сделайте Pull request

**Comment by MrSpecular** [comment]
Если перейти по ссылке, то там будет решение оптимизации определения типа объекта.

**Comment by ibond84** [comment]
Там 7 или 8 классов Tuple. Сравнение семи ссылок будет длится столько же, сколько StartsWith. Да и StartsWith действительно короче.

**Comment by MrSpecular** [comment]
@ibond84, Вы же посмотрели результаты тестов по приведенной мною ссылке?

**Comment by miks1965** [comment]
Вы предлагаете нам улучшить производительность мизерной части компилятора? Зачем?

**Comment by MrSpecular** [comment]
Улучшение производительности - **важная** задача. **Ничего** плохого в этом **не** вижу. Почему бы п**ри наличии свободного времени и желания не оптимизировать эту часть компилятора**?

**Comment by miks1965** [comment]
Вот почему. Компилятор, особенно его front-end работает со строками. Таблица символов вся на строках. Строки постоянно сравниваются друг с другом. Для небольших программ сравнений будет сотни и тысячи. 

И тут Вы предлагаете одно сравнение убрать.

Это называется преждевременная оптимизация. А она как известно - зло.
