### ISSUE TITLE
Позволяет именовать шаблонные параметры так же как и содержащие их типы, методы или подпрограммы

### ISSUE THREAD

**Issue by MrSpecular** [pascalabcnet/pascalabcnet#1124]
```
public class T<T>
{
}
```
Реакция C#: **error CS0694: Type parameter `T' has same name as containing type, or method**.

В ниже приведенном коде непонятно о каком **T** идет речь: о _классе_ или о _шаблонном параметре_.
```
type
  T<T> = class
    procedure Method();
    begin
      var x: T; // Какое из двух T имеется ввиду?
    end;
  end;

begin
end.
```

**Comment by ibond84** [comment]
Без <T> параметр шаблона, с <T> класс T.

**Comment by ibond84** [comment]
Не вижу смысла запрещать. параметр T находится в другой области видимости. а T и T<T> это разные имена. Никаких конфликтов здесь нет.

**Comment by MrSpecular** [comment]
Точнее, решение разработчиков C# по Вашему неправильно?

**Comment by SunSerega** [comment]
В C# вроде в данной записи:
`t1<T>=class end;`
`t1` будет полноценным именем. Но не в паскале.

**Comment by MrSpecular** [comment]
В смысле полноценным?

**Comment by SunSerega** [comment]
Ну, в смысле, в C# можно ведь написать `o is t1`, где `t1` - шаблонный тип, так? А вот в паскале нет. Хотя я не уверен, никогда не проверял это в C#, но слышал об этом несколько раз.
