### ISSUE TITLE
Разрешить запись typeof(List<>)

### ISSUE THREAD

**Issue by MrSpecular** [pascalabcnet/pascalabcnet#1125]
Пример:
```
begin
  writeln(typeof(List<>).FullName);
end.
```

**Comment by miks1965** [comment]
В C# это не работает:
```
Console.WriteLine(List<>);
```
У нас это не работает:
```
Writeln(List<integer>);
```
Закрывать Issue?

**Comment by ibond84** [comment]
Исправил некорректный issue

**Comment by miks1965** [comment]
А, ну, это другое дело. То есть, в контексте typeof разрешить использование открытых типов.

Так сразу и надо было писать

**Comment by MrSpecular** [comment]
@miks1965, извиняюсь, моя ошибка.

**Comment by ibond84** [comment]
сделал
