### ISSUE TITLE
Секция const предпочитает ссылку на функцию её результату

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#1129]
```
const
  TempFile = System.IO.Path.GetTempFileName;

begin
  writeln(TempFile);
  writeln(TempFile);
end.
```
Эта программа выпишет 2 разных имени файлов.
То есть `TempFile` хранит функцию а не `string`.
Хотя анализатор кода показывает `string`.

**Comment by miks1965** [comment]
Да, это ограничение констант. 
Напоминаю, что борясь с побочными эффектами и неинициализацией констант, мы запретили вызовы пользовательских функций при инициализации констант. Именно поэтому инициализация обычной функцией - это именно инициализация ссылкой на функцию. Для .NET-функций это поведение естественно сохранено.

```
function f := Random(5);

const c = f;
//const c1 = f(); - так нельзя

begin
  c.Print;
end.
```

**Comment by SunSerega** [comment]
1. Значит - надо исправить анализатор кода.
2. Тут тоже присваивается ссылка на функцию, хотя скобочки указаны.
````
const
  TempFile = System.IO.Path.GetTempFileName();

begin
  writeln(TempFile);
  writeln(TempFile);
end.
```

**Comment by miks1965** [comment]
Последнее для меня загадка. Во всех внутренних структурах компилятора - это вызов метода

**Comment by SunSerega** [comment]
Так как, открывать для этих проблем issue, или вы эту переоткроете?

**Comment by miks1965** [comment]
Открывайте новую
