### ISSUE TITLE
Небольшая коррекция сообщения о новой версии + фичи авто-скрытие и горизонтальная прокрутка в настройки

### ISSUE THREAD

**Issue by CryVICSky** [pascalabcnet/pascalabcnet#1130]
![default](https://user-images.githubusercontent.com/26967868/44801378-944e5700-abc1-11e8-8ba9-cf1163b028f2.jpg)
Рекомендую оформить сообщение так:
> Доступна новая версия PascalABC.NET.
> 
> Установленная версия: 3.4.0.1767;
> Доступная версия: 3.4.0.1770;
> 
> Перейти на страницу скачивания?

![-](https://user-images.githubusercontent.com/26967868/44801829-ca400b00-abc2-11e8-8602-37171f7df137.jpg)
Фичу авто-скрытие вынесите, пожалуйста, в настройки, чтобы она была в виде пункта с возможностью поставить галочку и сохранить подобное поведение без необходимости каждый раз при перезапуске среды на неё нажимать, чтобы скрыть общую консольку (окно вывода, список ошибок и прочее). То же самое касается и горизонтальной прокрутки (скроллинга).

Буду чрезмерно признателен и благодарен, если услышите и реализуете эти простые, но крайне важные элементы.

**Comment by miks1965** [comment]
Доступна новая версия PascalABC.NET.

    Установленная версия: 3.4.0.1767;
    Доступная версия: 3.4.0.1770;

    Перейти на страницу скачивания?

Честно говоря, я не вижу особой разницы между нашим и вашим вариантами. И даже не вижу логики в вашем варианте.

**Comment by SunSerega** [comment]
Вопрос всегда ставят в самом конце, перед выбором. Это более логично.

**Comment by MrSpecular** [comment]
> Вопрос в конце.

Каким образом он может быть в **самом** конце, если ниже него **находится**, как Вы выразились, поясняющая информация?

**Comment by miks1965** [comment]
Еще раз повторю - это вкусовщина.

А кто-то любит всё большими буквами. И будет стоять до последнего.

**Comment by CryVICSky** [comment]
> Еще раз повторю - это вкусовщина.
> А кто-то любит всё большими буквами. И будет стоять до последнего.

Красота и изящность - это не вкусовщина. Большие же буквы - это проявление напыщенности, а не красоты.

**Comment by AlexRnD61** [comment]
Напомнить, чем кот занимается, когда ему делать нечего? Правильно, пишет предложения поменять слова местами.

**Comment by MrSpecular** [comment]
Не думаю, что человек предложил улучшить сообщение об ошибке только по тому, как Вы выражайтесь

> делать нечего

.

**Comment by AlexRnD61** [comment]
Ваши личные предпочтения и мнения по отношению к действиям других людей, пожалуйста, отражайте в другом месте, тут они абсолютно неуместны.

**Comment by MrSpecular** [comment]
@AlexRnD61, будьте добры соблюдать порядок и культурно вести себя здесь. Раз пришли - высказывайтесь по делу. Если нечего по делу сказать, то лучше промолчать.

**Comment by AlexRnD61** [comment]
> чтобы не было конфликтов 

Чтобы их не было, по-видимому, здесь не должно быть Вас. Потому что до этого все было тихо. И тут, и на известном Вам форуме. А уж если пришли, то не надо пытаться модерировать чужие сообщения. Когда уж Вы это поймете?

**Comment by MrSpecular** [comment]
> Чтобы их не было, по-видимому, здесь не должно быть Вас.

Я бы предпочёл так не выражаться - переход на личности.

**Comment by SunSerega** [comment]
Были, но никого они не касались. А то что онлайн стал больше (даже при том что проблем с ним тоже стало больше) - это однозначно хорошо.

**Comment by AlexRnD61** [comment]
>  А то что онлайн стал больше

Онлайн любыми средствами - это далеко не хорошо. Может быть Вам знакомо выражение "Лучше меньше, да лучше" ?

**Comment by miks1965** [comment]
> Фичу авто-скрытие вынесите, пожалуйста, в настройки
Нигде такая мелочь не выносится в настройки.
Закрываю.

**Comment by SunSerega** [comment]
Не выносится, но везде сохраняется. В студии и продуктах JetBrains точно.

**Comment by miks1965** [comment]
Я закрыл ровно два пункта, которые предлагались в данной Issue

**Comment by SunSerega** [comment]
В смысле исправили? Ну тогда ладно, хотя ни в установщике, не в репозитории я не увидел (от вас сегодня нет коммитов).
