### ISSUE TITLE
Не достаточно понятные сообщения об ошибке в форматной строке

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#1131]
```
begin
  var s := $'     {' '}rfty        ';
end.
```
Тут правильное сообщение об ошибке:
`Встречена неправильная форматная строка`
```
begin
  var s0 := '';
  var s := $'  {s0}   {' '}rfty        ';
end.
```
А тут тоже правильно, вроде, но очень невразумительное:
`Встречено ''}rfty        '', а ожидалось ';'`

1. Проблема в обоих случаях одинаковая - внутренние `'` надо заменить на `''`. А сообщение выдаётся разное.
2. Эти сообщения никак не помогают найти что не так. А второе ещё и пугает. Это ещё упрощённый вариант, я у себя в программе получил следующее:
`Встречено '')}{#9*2}</t>'', а ожидалось ';'`

**Comment by ibond84** [comment]
Что тут невразумительного? Неожиданный символ ' поэтому и пишет, что ожидалось ;

**Comment by SunSerega** [comment]
1. Всё равно, сообщение об ошибке изменяется от того что добавляем `{s0}`, так не должно быть.
2. Там не может быть `;`, нечего его ожидать.
3. Этот оборванный текст ( `'')}{#9*2}</t>''` ) сбивает с толку. Это основная тема этой issue.

Лучше уж `Встречена неправильная форматная строка`, хотя лучше получить что то типа `Форматная строка не может закончится с открытой "{"`, или что то типа того. Чтоб сразу было понятно что проблема в том, что `'` воспринимает как конец строки, и чтоб его так не воспринимало - надо заменить на `''`.

**Comment by ibond84** [comment]
Отредактировал issue, чтоб было понятно, что это экранированная строка. Зачем там пробел ставить надо было, непонятно.

**Comment by SunSerega** [comment]
Пробел - это символ который я передавал в функцию в форматной строке:
```
  Result := $'<t style="margin-left: {Result}px">{l.TrimStart('' '').Replace(''<'',''&lt'')}{#9*2}</t>';
```

**Comment by ibond84** [comment]
Понятно. Это у нас там такая конкатенация строк.
```
begin
  var s0 := 'a' 'b';
  writeln(s0);
end.
```

**Comment by spectatorBH** [comment]
> Это у нас там такая конкатенация строк.
`var s0 := 'a' 'b';`

@ibond84 Это баг или новая фича?

**Comment by SunSerega** [comment]
Скорее очень старая фича, о которой знают только избранные.

**Comment by spectatorBH** [comment]
> Скорее очень старая фича, о которой знают только избранные.

Избранные -- это сами разработчики? В любом случае, это ненормально. Это должно быть либо описано формально как фича в справке, либо исправлено как ошибка, т.к. на данный момент такое написание явно противоречит синтаксису Паскаля (причем любого, впрочем, как и С#). Откуда вообще такое чудо появилось?

Если бы такую "старую фичу для избранных" использовал какой-нибудь школьник, ему бы это засчитали как ошибку, и были бы правы.
