### ISSUE TITLE
Неправильная подсветка вложенных интерполированных строк

### ISSUE THREAD

**Issue by MrSpecular** [pascalabcnet/pascalabcnet#1134]
![image](https://user-images.githubusercontent.com/42602899/44948810-19897400-ae2d-11e8-9dbb-d72db7d95ff0.png)

```
begin
  Writeln($'{$'{something}'}');
  Writeln($'{$'{$'{something}'}'}');
end.
```

**Comment by SunSerega** [comment]
Знаки `'` внутри строки надо заменять на `''`. Это своеобразное экранирование, вроде `\'` в большинстве языков. То есть у вас в коде это надо заменить так:
```
begin
  Writeln($'{$''{something}''}');
  Writeln($'{$''{$''{something}''}''}');
end.
```
Тогда подсветка правильная.

**Comment by MrSpecular** [comment]
> Знаки ' внутри строки надо заменять на ''. Это своеобразное экранирование, вроде \' в большинстве языков.

Данное решение имеет место быть, однако код становится менее читабельным при использовании данного метода решения проблемы.
