### ISSUE TITLE
Показывает лишний метод Max/Min для sequence of T

### ISSUE THREAD

**Issue by MrSpecular** [pascalabcnet/pascalabcnet#1135]
![image](https://user-images.githubusercontent.com/42602899/44953985-5cd2f980-aea4-11e8-9d11-dfdd5cd9c196.png)

Отображает не только **Max<>**, но и **Max**. С Min аналогично.

**Comment by ibond84** [comment]
Это не лишний метод. Один обобщенный, другой обычный

**Comment by SunSerega** [comment]
Но в по точке он лишний, потому что какой не выбери - поставить просто `Max`, без `<>`. И после открытия скобочки после `Max` показывает и шаблонные и не_шаблонные перегрузки.

**Comment by ibond84** [comment]
Ничего он не лишний. Раз есть метод, надо его показывать
