### ISSUE TITLE
Добавить аналог using из C#

### ISSUE THREAD

**Issue by MrSpecular** [pascalabcnet/pascalabcnet#1136]
```
begin
  using (var instance: FinalizeableObject := new FinalizeableObject()) do
  begin
    // Actions
  end;
end.
```
[Оператор using (Справочник по C#)](https://docs.microsoft.com/ru-ru/dotnet/csharp/language-reference/keywords/using-statement)

Предлагаю оставить эту **Issue**, пометив её как **enhancement**.

**Comment by ibond84** [comment]
Вы привели какую-то смесь из C# и паскалевского кода. Не принимается.

**Comment by MrSpecular** [comment]
Приведите аргументы против этой смеси. Разве PascalABC.Net не является смесью лучшего из языков Pascal, C# и Haskell (возможно, список больше)?

**Comment by ibond84** [comment]
ну, синтаксис смешивать же не надо. = это равно в паскале, а не присвоить. типы описываются после переменной. придумайте что-то ближе к паскалю.

**Comment by MrSpecular** [comment]
Подправил.

**Comment by SunSerega** [comment]
Кстати, в паскале есть уже ключевое слово `with`, почему его не использовать? У него ведь похожее значение. То есть
```
begin
  with a: T := new T() do
  begin
    //
  end;
end.
```

**Comment by MrSpecular** [comment]
@SunSerega, скорее всего потому, что в C# и Oxygen оно для этой цели не используется. С with другая ассоциация - упрощение доступа к членам класса или записи. Я думаю, что если использовать with, то это может создать трудности при переходе на C# или Oxygen (в том плане, что будет не совсем привычно).

**Comment by SunSerega** [comment]
Зато в паскале нет `using`. И всё же, у них похожие значения. В C# ведь using используется для подключения пространства имён ещё (то есть, для влития их в основное пространство имён). А в паскале работает следующее:
```
begin
  with System.IO do
  begin
    var f := new FileInfo('');
  end;
end.
```
(ну или [почти](https://github.com/pascalabcnet/pascalabcnet/issues/1137)).

**Comment by MrSpecular** [comment]
Почему у Issue нет метки enhancement?

**Comment by AlexRnD61** [comment]
Почитал на Хабре [статью](https://habr.com/post/89720) и еще раз убедился, что этот using если и понадобится когда, то наверно только самому автору issue.

Слишком замороченная вещь. Для языка, ориентированного на обучение, на мой взгляд эта фишка - лишняя. Можно еще несколько десятков такого же счастью напредлагать. Школьники и новички-студенты с IDispose явно работать никогда не будут - им знаний не хватит, потому что ручные игры с памятью - это не для начинающих. А не студенты "не-новички" сделают именно то, для чего PascalABC.NET создавался? благополучно изучив на нем основы, перейдут на C#. И останется такая реализация в языке памятником "здесь был Вася".

**Comment by AlexRnD61** [comment]
А можете сказать, кому конкретно это надо? Скольким людям, какому проценту от числа потенциальных пользователей? 0.0001% ? Или еще меньше? И давно стали язык подгонять под нужды такого количества?

**Comment by SunSerega** [comment]
Можно подумать вы можете)))
Зато, я могу сказать что новичков надо сразу приучать правильно, то есть ставить закрытие файла в `try finally`, всегда когда его используют. Иначе это порождает кучу сложно-вылавливаемых ошибок.

**Comment by AlexRnD61** [comment]
> Зато, я могу сказать что новичков надо сразу приучать правильно, то есть ставить закрытие файла в try finally

Это пусть в "сущеглупом языке Цэ" приучают.  А Паскаль специально сделан так, чтобы новички не копались в низкоуровневых объедках, а могли приложить свои усилия к пониманию базы - алгоритмов и приемов работы с современными информационными структурами.

**Comment by SunSerega** [comment]
Так в том то и дело, это высокоуровневая замена для `try finally` с финализацией.

**Comment by AlexRnD61** [comment]
Высокоуровневое - это когда человек не должен думать про разные открытия/закрытия файлов и прочие финализации.

**Comment by MrSpecular** [comment]
@AlexRnD61, видимо, представления о высокоуровневом у нас расходятся. Но это вовсе не означает, что мнение @SunSerega:
> Так в том то и дело, это **высокоуровневая** замена для try finally с финализацией.

 в этом отношении неправильное.

**Comment by AlexRnD61** [comment]
> Человека лучше приучать к тому, что все само собой не работает

Пишите на ассемблере или С - и приучайте себя, а не какого-то "человека". Не надо решать за него, что ему лучше, потому что тогда для начала придется убрать из языка весь синтаксический сахар.

>  Скрытие таких операций как открытие и закрытие файлов (это всего лишь пример) от взгляда начинающих в дальнейшем вызовет большие трудности при переходе на C# 

Это Ваше личное, ничем не обоснованное мнение. Разработчики создавали язык, имея в виду последующий переход на С#, более того, они имеют значительный положительный опыт по такому переходу. Если бы им действительно была нужна такая возможность, они бы ее и без Вас включили в Паскаль.

> Я бы не советовал так резко выражаться.

Советы свои, пожалуйста, оставьте для тех, кто у Вас их спрашивает. Не пытайтесь в очередной раз подменять собой модератора - кроме снисходительной улыбки ("Бодливой корове бог рогов не дал") это ничего не вызывает.

> Ваше субъективное и ничем еще не доказанное мнение

А это был вопрос, вовсе не величина, требующая обоснования. Вы пытаетесь в язык просунуть очередную, бесполезную для него с точки зрения зрения вещицу - Вам и доказывать, для чего и кому это надо.

**Comment by MrSpecular** [comment]
> Пишите на ассемблере или С - и приучайте себя, а не какого-то "человека".
По Вашему приучать писать правильный код - неправильно? Это не зависит от языка, это должен делать программист на любом языке.

> Советы свои, пожалуйста, оставьте для тех, кто у Вас их спрашивает.
Не указывайте мне что мне делать.

> Вы пытаетесь в язык просунуть очередную, бесполезную для него с точки зрения зрения вещицу
Раз считайте, что это бесполезная вещь, то докажите.

**Comment by AlexRnD61** [comment]
> По Вашему приучать писать правильный код - неправильно?

Нет, неправильно считать единственно верным использование прямого обращения к функциям операционной системы там, где без него легко обойтись.

> Раз так считайте, то докажите. Я пока не увидел от Вас ни одного доказательства.

Я тоже не увидел от Вас никаких "доказательств". Вы считаете, что это нужно, я считаю - что нет. В виде возражений привожу доводы в отношении массовой аудитории, на которую язык рассчитан. Вы кроме фраз с "докажите", вообще никаких аргументов не приводите. "Учение правильно, потому что оно верно" - вот стиль Ваших "доводов". Он порочен.

**Comment by MrSpecular** [comment]
> Нет, неправильно считать единственно верным использование прямого обращения к функциям операционной системы там, где без него легко обойтись.

Заметьте, я нигде не указал, что это должен быть единственный способ. Я лишь указал на то, что хорошо бы понимать устройство этих функций изнутри, хотя бы приблизительно.

**Comment by SunSerega** [comment]
А почему, всё же, не `with`?

**Comment by devapromix** [comment]
Видимо потому, что тут происходит еще и освобождение ресов.

**Comment by miks1965** [comment]
Верно. Предвижу, что тут сейчас начнется бешеный тред за отстаивание with и о том, что у нас свой путь.

Прошу - поберегите слова для чего-то более высокого :)

**Comment by ibond84** [comment]
Уже не вижу смысла в этом, если можно вызывать Dispose

**Comment by miks1965** [comment]
Ну в смысле Close.

Там такая фишка - если происходит исключение в секции using, то файл всё равно закрывается. А f.Close в этом случае не сработает и файл останется висеть открытым. И надо будет try finally городить

**Comment by ibond84** [comment]
Нет, Dispose. Close просто закрывает файл

**Comment by MrSpecular** [comment]
> Предвижу, что тут сейчас начнется **бешеный тред** за отстаивание with и о том, что у нас свой путь.

Все решает голосование.

**Comment by PABCSoft** [comment]
А касательно данной записи:
```
using WinForms = System.Windows.Forms;
Begin
End.
```
Переопределение имени неймспейса или модуля для текущего файла кода.

**Comment by DanielArgent** [comment]
Позвольте обобщить имеющиеся варианты.

**Необходимость данной конструкции.**
Мне кажется очевидным, что использование оператора `using` является более предпочтительным, нежели использование конструкции `try ... except ... end;` в сочетании с вызовом метода `IDisposable.Dispose()`.

**Варианты дизайна.**
Несмотря на желание многих людей использовать ключевое слово `with`, оно уже является зарезервированным для других целей. Использовав его мы можем пойти двумя путями:
1. Изменить его для новых целей, тем самым отказавшись от его прежнего назначения и потеряв обратную совместимость.
2. Добавить новую семантику к уже имеющейся, тем самым добавив неоднозначность, вероятно сломав обратную совместимость (ведь теперь любой `IDisposable` объект в операторе `with` будет неожиданно для пользователя освобождать ресурсы).

_Следовательно, использование with невозможно._

Я вижу 2 потенциально возможных ключевых слова: `using` и `try`. 

Использование `try` (практикующееся в Java 7 и выше) удобно тем, что нам не нужно вводить новое ключевое слово, оно подходит по смыслу и с ним конструкция может выглядеть так:
```
try var f := OpenRead('a.txt') do
begin
  ...
end;
```
Возможная трудность при таком подходе: дать понять парсеру что это не обычный механизм обработки исключений (то есть это не начало `try ... except ... end;`):
```
// RAII-конструкция
try var f := OpenRead('a.txt') do
  ...

// Обработка исключений
try 
  var f := OpenRead('a.txt')
  ...
```
Из примеров выше видно, что при парсинге следует обращать внимание на символ новой строки и ключевое слово `do`.

Использование using, как уже отмечалось выше, более знакомо программистам на C#. Оно явно помечается ещё не использованным ключевым словом, так что будет разбираться легче.
```
using var f := OpenRead('a.txt') do
begin
  ...
end;
```
Кроме того, у этой формы есть ещё одно преимущество. В дальнейшем можно сделать механизм, появившийся в C# 8: использование using до конца текущей области видимости
```
function myFunc(fileName: string);
begin
  using var f := OpenRead('a.txt');
  f.ReadlnString.Print;
  // f.Dispose() here
end;
```
Таким образом, наиболее рациональным кажется использование `using` в форме
```
using var <var-name> = <resource-initialization> do
  <body>
```

**Способ реализации.**
Реализовать можно, воспринимая выражение 
```
using var <var-name> = <resource-initialization> do
  <body>
```
аналогом
```
do
  var <var-name> = <resource-initialization>;
  try
    <body>
  finally
    <var-name>.Dispose();
  end;
end;
```
Очевидно, что если `<resource-initialization>` возвращает объект, не реализующий интерфейс `IDisposable`, должно генерироваться  исключение времени компиляции.
