### ISSUE TITLE
Не отображать в Intellisense имена, начинающиеся с # и < (при использовании расширенных свойств и не только)

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#1138]
```
type
  t1<T>=class
    property p1: integer read System.Runtime.InteropServices.Marshal.SizeOf(typeof(T));
  end;

begin
  var a:t1<byte>;
  a.
end.
```

![image](https://user-images.githubusercontent.com/27270190/44956602-4f7f3480-aecf-11e8-98a6-695a17638f21.png)

**Comment by MrSpecular** [comment]
Пример можно упростить:
```
type
  TClass = class
    property P: byte read 1;
  end;

begin
  new TClass().
end.
```
. 
![image](https://user-images.githubusercontent.com/42602899/44956695-c36e0c80-aed0-11e8-87c4-9543e4c82166.png)

**Comment by SunSerega** [comment]
>Думаю, что название Issue можно уточнить

Можно, но в этом не сильно много смысла. А за упрощение спасибо, но пусть останется в вашем комменте.

**Comment by ibond84** [comment]
Можно было и доллар использовать. Это стандарт для скрытых методов

**Comment by ibond84** [comment]
Ах, он в парсере не поддерживается. Плохо. Ладно
