### ISSUE TITLE
Добавить ключевое слово when в контексте except on (потому что так сделано в C#)

### ISSUE THREAD

**Issue by MrSpecular** [pascalabcnet/pascalabcnet#1139]
В контексте **except on**:
```
begin
  try
    Writeln(1 / 0);
  except
    on e: System.DivideByZeroException when e.Message.Contains('1') do
      Writeln('Все плохо, Вы поделили на 0.');
  end;
end.
```
[when (справочник по C#)](https://docs.microsoft.com/ru-ru/dotnet/csharp/language-reference/keywords/when)

**Comment by AlexRnD61** [comment]
Опять эти бредовые идеи тащить в синтаксис все, что ни поподя...

**Comment by MrSpecular** [comment]
Если в match-with есть when, то почему Вы называйте бредом добавить его для case и для except on?

**Comment by AlexRnD61** [comment]
>  то почему Вы называйте бредом добавить его для case и для except on?

Я называю бредом идеи тащить в PascaslABC.NET все подряд, что ни подвернется под руку, из других языков лишь на основании того, что Вам это **кажется** полезным.

> разработчики приняли неправильное решение, что добавили when в match-with?

Это сочли нужным сделать разработчики языка С#. Который **ни малейшего отношения** к PascalABC.NET не имеет.

**Comment by MrSpecular** [comment]
> Это сочли нужным сделать разработчики языка С#. Который ни малейшего отношения к PascalABC.NET не имеет.

Если так, то почему when здесь присутствует:
```
var o: Object;
...
match o with
  Person(name,age) when name='Иванов': Print('Это персона и он - Иванов');
end
```
?

**Comment by MrSpecular** [comment]
@AlexRnD61, если бы это было сиюминутным исмпульсом, то в C# этого бы не было.

**Comment by AlexRnD61** [comment]
@MrSpecular , "сиюминутный импульс" - это Ваша идея всунуть очередную опцию C# в Паскаль. Разработчики C# тут вообще ни при чем.

**Comment by MrSpecular** [comment]
@AlexRnD61, повторюсь еще раз - when поддерживается в контексте match. Отсутствие его поддержки в case выглядит неравномерно.

**Comment by AlexRnD61** [comment]
>  when поддерживается в контексте match. Отсутствие его поддержки в case выглядит неравномерно

"Мама, у тебя на правой щеке родинка; отсутствие родинки на левой щеке выглядит неравномерно".

**Comment by MrSpecular** [comment]
@AlexRnD61, занялись бы Вы чем-нибудь полезным, например, написанием книги, вместо того, чтобы спамить в комментариях.

**Comment by AlexRnD61** [comment]
@MrSpecular, занялись бы Вы лучше чем-нибудь полезным для общества, (хоть бы ту же книгу написали, что ли - или кишка тонка?) вместо того, чтобы засорять issure своими бесконечными, гм... как бы это поприличнее сказать? - идеями.

**Comment by MrSpecular** [comment]
**### @AlexRnD61, прекратите переходить на личности.**

**Comment by AlexRnD61** [comment]
@MrSpecular , переходить на личности первым начали Вы.

**Comment by MrSpecular** [comment]
@AlexRnD61, я **нигде не** начинал Вас первый оскорблять.

**Comment by AlexRnD61** [comment]
@MrSpecular, я Вас тоже не оскорблял, более того, я даже не пытаюсь Вас поучать, как себя вести и что делать, что не делать - в отличие от Вас.

**Comment by MrSpecular** [comment]
>  Вас тоже не оскорблял

Можно оспорить:
> У Вас логика дошкольника
> или кишка тонка?
.

**Comment by AlexRnD61** [comment]
Оспорьте. Если человеку сказать, что он пользуется примитивной логикой - это ни разу не оскорбление. Я же не написал, что у Вас ум дошкольника.

**Comment by MrSpecular** [comment]
@AlexRnD61, это, во-первых, переход наличности, а во-вторых оскорбление другого участника GitHub.

**Comment by AlexRnD61** [comment]
С каких пор высказывание мнения, о том, что логика каком-то суждении примитивна, стало переходом на личности?

**Comment by MrSpecular** [comment]
С таких, что это явно относилось к моей логике и было сказано совсем не в мягкой форме. И Вы явно решили это высказать прямо в Issue, даже не заметив, что тема Issue совсем не обсуждение того, у кого какая логика.

**Comment by AlexRnD61** [comment]
Безусловно, к Вашей. А что, у Вас логика непогрешима и не подлежит обсуждению, если она смотрится примитивной? Не слишком ли Вы о себе высокого мнения?

**Comment by MrSpecular** [comment]
> А что, у Вас логика непогрешима и не подлежит обсуждению, если она смотрится примитивной?

Нет, не подлежит обсуждению, особенно не через личные сообщения.

**Comment by AlexRnD61** [comment]
В дальнейшем, буде такое желание возникнет, я просто стану писать свое мнение в Ваших постах и не буду реагировать на Ваши реплики.

**Comment by MrSpecular** [comment]
@AlexRnD61, спасибо за хорошую идею. Лично я не против делать то же самое по отношению к Вашим Issue или постам. Но предоставляя аргументы за/против. И ведя конструктивную беседу, коей эту никак не назовешь.

**Comment by miks1965** [comment]
Ну, не предмет перврй необходимости добавить в Except, но я не противник этого. Сам никогда таким не пользовался.

Что касается case, то нет. Обращаю ваше внимание, что в c# добавили элементы pattern matchingа в switch , мы же напротив ввели новый оператор match чтобы не смешивать эти две концепции. Так что архитектурное решение в c# с нашей точки зрения плохое. Кроме этого, case в Паскале не эквивалентен switch в c#, поэтому вот так просто и бездумно переносить эти концепции нельзя

**Comment by MrSpecular** [comment]
В соответствии с названием подправил содержание **Issue**.

**Comment by ibond84** [comment]
Фича мутная

`catch (HttpRequestException e) when (e.Message.Contains("301")) {
           return "Site Moved";
       }
       catch (HttpRequestException e) when (e.Message.Contains("404")) {
           return "Page Not Found";
       }`

Да, а кодов-то много и писать портянку из catch-ей как-то неприятно.

**Comment by miks1965** [comment]
Вообще, с учетом ниши языка это абсолютно бесполезная фича. Даже в профессиональном программировании я практически не встречал примеры её использования.

**Comment by SunSerega** [comment]
Для этого есть IL оператор `filter`, он не так уж сложно работает.

>с учетом ниши языка это абсолютно бесполезная фича

Если не считать что в обучение входит то что понадобится в жизни - то и лямбды не нужны. А `when` всё же не менее полезно чем лямбды.

>я практически не встречал примеры её использования

@ibond84 только что привёл пример с msdn, вот он же, только полностью:
```
using System;
using System.Net.Http;
using System.Threading.Tasks;

class Program
{
   static void Main()
   {
      Console.WriteLine(MakeRequest().Result);
   }

   public static async Task<string> MakeRequest()
   { 
       var client = new System.Net.Http.HttpClient();
       var streamTask = client.GetStringAsync("https://localHost:10000");
       try {
           var responseText = await streamTask;
           return responseText;
       } 
       catch (HttpRequestException e) when (e.Message.Contains("301")) {
           return "Site Moved";
       }
       catch (HttpRequestException e) when (e.Message.Contains("404")) {
           return "Page Not Found";
       }
       catch (HttpRequestException e) {
           return e.Message;
       }
   }
}
```
В паскале это ещё и не так страшно смотрится:
```
try
  Result := await streamTask;
except
  on e: HttpRequestException when e.Message.Contains('301') do Result := 'Site Moved';
  on e: HttpRequestException when e.Message.Contains('404') do Result := 'Page Not Found';
  on e: HttpRequestException do Result := e.Message;
end;
```

**Comment by miks1965** [comment]
А слабО сделать if в обработчике?

**Comment by SunSerega** [comment]
Лямбды тоже можно заменить обычными подпрограммами. Но выглядеть будет, как и тут - ужасно.

**Comment by miks1965** [comment]
Это демагогия. Сравнивать лямбды с нижайше редким кодом, не выигрывающим ничего в записи и говорить, что это одинаково

**Comment by ibond84** [comment]
Ерунда это все. Не будем делать
