### ISSUE TITLE
Зависание оболочки

### ISSUE THREAD

**Issue by miks1965** [pascalabcnet/pascalabcnet#114]
```
begin
  var t := ('Иванов',23);
  var t1 := t+1;
end.
```

**Comment by cergean** [comment]
Причем зависает только при компиляции, если сразу запустить - то выполняется как ни странно.

**Comment by miks1965** [comment]
Теперь это не компилируется с сообщением 
Program1.pas(4) : Нет перегруженной подпрограммы с такими типами параметров

**Comment by ibond84** [comment]
Что такое Program1.pas?

**Comment by miks1965** [comment]
Я скопировал в Program1.pas вот такой текст:

```
begin
  var t := ('Иванов',23);
  var t1 := t+1;
end.
```
Выводится сообщение
Program1.pas(3) : Нет перегруженной подпрограммы с такими типами параметров

**Comment by ibond84** [comment]
Странно, у меня работает

**Comment by miks1965** [comment]
Да, работает - наверное, не обновился до этого. Закрываю
