### ISSUE TITLE
Анализатор кода не/неправильно подсказывает то, что надо экранировать

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#1140]
```
uses System.Runtime.InteropServices;

begin
  LayoutKind.
end.
```
Если из списка получаемого по точке выбрать `Explicit` - его поставит без экранирования, что не компилируется.
Если попытаться поставить `&` - этот список закроется и откажется открываться по Ctrl+Space.

**Comment by miks1965** [comment]
explicit выделит жирным - и человек догадается. Невозможно бесконечно нагружать анализатор кода мелкими замечаниями
