### ISSUE TITLE
file of T отказывается работать с .Net записями

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#1141]
```
begin
  var f: file of System.DateTime;
end.
```
`Типизированый файл не может содержать элементы такого типа `.

`System.DateTime` это запись, имеющая 1 приватное поле типа `int64`, `file of T` должен без проблем его сохранять (теперь, когда приватные поля таки сохраняет).

При чём, как и написано в названии issue - это касается не только `DateTime`, а всех записей из .Net .

**Comment by miks1965** [comment]
Я думаю, читая это всё, что я запрещу пожалуй использовать в типизированных файлах любые записи с методами, свойствами и приватными полями. Иначе это будет бесконечно

**Comment by miks1965** [comment]
Я думаю, читая это всё, что я запрещу пожалуй использовать в типизированных файлах любые записи с методами, свойствами и приватными полями. Иначе это будет бесконечно

**Comment by SunSerega** [comment]
Подождите, зачем? Если сохранять и загружать только поля (даже если они приватные) - вы должно нормально работать, вне зависимости от свойств и методов.

**Comment by AlexRnD61** [comment]
> Иначе это будет бесконечно

Возможно, там подводных камней еще навалом. Типизированных файлов не зря нет в современных языках с ООП. В Паскале, слава богу, они есть. А когда их начинают наполнять тем, чего отродясь не было в Паскале, проблемы и лезут. Собственно, что за нужда совать в файл записи с методами?

**Comment by SunSerega** [comment]
1. К примеру такая программа для чего то типа логов:
```
  LogEntry=record
    time:System.DateTime;
    id:integer;
    data:int64;
  end;
```
2. Всё там нормально. Теперь, когда приватные поля сохраняет и загружает - проблем не должно быть.

**Comment by ibond84** [comment]
>Собственно, что за нужда совать в файл записи с методами?

Методы в файл не суются. Они вообще никому не мешают.

**Comment by miks1965** [comment]
В .NET-типе могут быть скрытые ссылки в виде приватных полей. Поэтому они и запрещены.

**Comment by SunSerega** [comment]
Приватные поля у типа можно увидеть, чтоб проверить, нет ли в нём ссылок.

**Comment by SunSerega** [comment]
Вот:
```
uses System.Reflection;

function HasRefT(t:System.Type):boolean :=
t.GetFields(
  BindingFlags.GetField or
  BindingFlags.Instance or
  BindingFlags.Public or
  BindingFlags.NonPublic
)
.Where(fi->not fi.IsLiteral)
.Select(fi->fi.FieldType)
.Where(ft->ft<>t)//к примеру integer имеет поле типа integer, без этой строчки StackOwerflow
.Any(
  ft->
  ft.IsClass or//IsByRef возвращает что то не то, зато IsClass работает и на указатели тоже
  HasRefT(ft)  //Аплодисменты, майкрасовт))
);

type
  r0=record
    private o:object;
  end;
  r1=record
    b:byte;
    a:r0;
    i:integer;
  end;
  r2=record
    p:Pointer;
  end;
  r3=record
    p:PByte;
  end;

begin
  var o: System.DateTime;
  writeln(HasRefT(o.GetType));
  writeln(HasRefT(typeof(r1)));
  writeln(HasRefT(typeof(r2)));
  writeln(HasRefT(typeof(r3)));
end.
```
В `System.DateTime` нету ничего передаваемого по ссылке, всё нормально.

**Comment by SunSerega** [comment]
Ну так что? Раз скрытые ссылочные поля - не проблема, в чём тогда проблема?
