### ISSUE TITLE
with не работает с пространствами имён

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#1143]
```
begin
  with System.IO do
  begin
    var f := new FileInfo('');
  end;
end.
```
`Неизвестное имя 'FileInfo'`

**Comment by miks1965** [comment]
А uses System.IO не хотите использовать?

**Comment by SunSerega** [comment]
@ibond84 только что [написал](https://github.com/pascalabcnet/pascalabcnet/issues/1137), что это должно компилироваться. Анализатор кода видит `FileInfo`. Если у вы не согласны с тем что этот код должен компилироваться - исправьте анализатор кода.

**Comment by MrSpecular** [comment]
В справке указано следующее:

> Оператор with позволяет сократить обращение к **полям записи, а также к полям, методам и свойствам объекта.**

Тут ничего не сказано про то, что можно писать после with имена пространств имён.
