### ISSUE TITLE
Неправильная ошибка при неизвестном имени в sequence. Any/All

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#1144]
```
begin
  var s: sequence of byte;
  s.Any(b->not_a_name);//Нет перегруженной подпрограммы с таким количеством параметров Any
  s.All(b->not_a_name);//Неверное количество параметров функции
end.
```

**Comment by MrSpecular** [comment]
Наверное, это правильно:

```
begin
  Seq(1).Any(x -> 1);
end.
```
Аргументом Any/All ожидается предикат, а ему подается какое-то выражение, им не являющееся.

**Comment by MrSpecular** [comment]
Упрощенный пример:

```
begin
  Seq(1).Any(x -> y > 0);
end.
```
.

**Comment by SunSerega** [comment]
Я б не назвал его упрощённым:

1. Если создание перменное на той же строчке что и ошибка - оно может быть причиной.
2. У меня переменная которой не должно быть выделена соответствующим именем.
