### ISSUE TITLE
Не могу выбрать подходящий парсер для файла при попытке форматирования кода программ на VB.Net/C#

### ISSUE THREAD

**Issue by MrSpecular** [pascalabcnet/pascalabcnet#1145]
![image](https://user-images.githubusercontent.com/42602899/45000701-e9c6a180-afcf-11e8-9d79-35028fc20a45.png)

Пусть данная **Issue** повисит, **когда будет время и желание у разработчиков - займутся доработкой этого момента**.

**Comment by miks1965** [comment]
Всё работает. 

Зачем в Issue эти длинные сообщения?

**Comment by MrSpecular** [comment]
> Всё работает.

![image](https://user-images.githubusercontent.com/42602899/45045340-48952500-b07b-11e8-8e8b-e1561b145602.png)

Вы уверены?

**Comment by miks1965** [comment]
Уверен

**Comment by MrSpecular** [comment]
Заметьте, я тестировал в последней версии. Разве скриншоты не развеяли Вашу уверенность? :)

**Comment by SunSerega** [comment]
Скиньте лучше файл который вы компилируете, и точный набор шагов или ещё лучше видео (я бандикам юзаю, к примеру).

**Comment by MrSpecular** [comment]
```
'Rextester.Program.Main is the entry point for your code. Don't change it.
'Compiler version 11.0.50709.17929 for Microsoft (R) .NET Framework 4.5

Imports System
Imports System.Collections.Generic
Imports System.Linq
Imports System.Text.RegularExpressions

Namespace Rextester
    Public Module Program
        Public Sub Main(args() As string)
        End Sub
    End Module
End Namespace
```

**Comment by miks1965** [comment]
Переименуйте ишью что это связано с автоформатированием
