### ISSUE TITLE
Выводит лишнее предупреждение

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#1148]
```
type
  t1 = class
    arr: array of t1;
  end;

procedure p1(o: t1);
begin
  o.arr.ForEach(p1)//Обнаружена бесконечная рекурсия
end;

begin end.
```
Тут процедура `p1` вызывается не для тех параметров, которые передали в неё, поэтому тут бесконечной рекурсии нет.

**Comment by MrSpecular** [comment]
Следующий код выдает 4 предупреждения, 2 из которых, на мой взгляд не должны присутствовать:
1) В случае or и and используется краткая проверка на выполнения условия, точнее: если первый аргумент для or равен true, то дальше проверка не идёт; если первый аргумент для and равен false, то дальше проверка не идёт.
2) Однако, несмотря на это, для P1 и P4 выдаются предупреждения.
```
function P1(): boolean := true or P1(); // Infinite recursion detected
function P2(): boolean := false or P2();
function P3(): boolean := true and P3();
function P4(): boolean := false and P4(); // Infinite recursion detected

begin
end.
```

**Comment by SunSerega** [comment]
Это хорошо, но это отдельная issue.

В этой issue говориться что предупреждение вызывается, хоть `p1` вызывается с разными параметрами.
А у вас - не проверяется досрочный выход из оператора, и за которого ваша процедура не вызовется.
