### ISSUE TITLE
Выдает лишние предупреждения без учёта краткого вычисления истинности условий

### ISSUE THREAD

**Issue by MrSpecular** [pascalabcnet/pascalabcnet#1151]
Следующий код выдает **4** предупреждения, **2** из которых, на мой взгляд, **не** должны присутствовать:
1) В случае **or** и **and** используется **краткая проверка на выполнения условия**, точнее: _если первый аргумент для **or** равен **true**, то дальше проверка **не** идёт; если первый аргумент для **and** равен **false**, то дальше проверка не **идёт_**.
2) Однако, несмотря на это, для **P1** и **P4** выдаются предупреждения.
```
function P1(): boolean := true or P1(); // Infinite recursion detected
function P2(): boolean := false or P2();
function P3(): boolean := true and P3();
function P4(): boolean := false and P4(); // Infinite recursion detected

begin
end.
```

**Comment by AlexRnD61** [comment]
Насколько я помню, вычисления по "короткой схеме" оставляют реализацию порядка вычислений на усмотрение разработчика/компилятора. Для конструкции x or y (для примера) это означает, что если значение одного из операндов True, второй не рассматривается. Но что рассматривать первым - x или y - "короткая схема" не постулирует. Поэтому предупреждения лучше оставить хотя бы для того, чтобы впоследствии не столкнуться с разным поведением при вычислении true or q и q or true. Мало ли какие идеи по оптимизации кода могут посетить при доработках.

**Comment by SunSerega** [comment]
>Но что рассматривать первым - x или y - "короткая схема" не постулирует

Нет, левый всегда первый. Это в многочисленных реализациях C++ встречается так что некоторые начинают складывать слева, а некоторые справа, в паскале такого нет, и слава богу.

**Comment by AlexRnD61** [comment]
Это с чего Вы так решили, что "В паскале нет" ? И почему считаете, что если нет, так и не будет никогда? Еще раз - принцип "коротких вычислений" **не постулирует**, какой операнд рассматривать первым. Безотносительно языка или реализации.

**Comment by SunSerega** [comment]
1. В справке, как раз, сказано именно так:

>Выражения с and и or вычисляются по короткой схеме: 
>
>в выражении x and y если x ложно, то все выражение ложно, и y не вычисляется;
>в выражении x or y если x истинно, то все выражение истинно, и y не вычисляется.

2. У этого паскаля только 1 реализация, и в ней сделали так. Как я и сказал, в отличии от C++ .

**Comment by MrSpecular** [comment]
> Но что рассматривать первым - x или y - "короткая схема" не постулирует

Зато справка постулирует. Совет - чаще заглядывайте в справку.

**Comment by AlexRnD61** [comment]
> В IL коде который генерируется паскалем - видно что это специально сделали, так - чтоб какая бы не была реализация JIT-а - всегда вычислялось слева на право.

Вы меня на этот раз убедили

**Comment by MrSpecular** [comment]
Доказательство того, что краткая проверка ведётся слева направо:
```
type
  bool = boolean;

function F(x: bool): bool;
begin
  Writeln('exexuted');
  Result := x;
end;

var
  x: bool;

begin
  Writeln('Or:');
  Writeln('Первое true:');
  x := F(true) or F(true);
  Writeln();
  x := F(true) or F(false);
  Writeln('Первое false:');
  x := F(false) or F(true);
  Writeln();
  x := F(false) or F(false);
  
  Writeln('And:');
  Writeln('Первое true:');
  x := F(true) and F(true);
  Writeln();
  x := F(true) and F(false);
  Writeln('Первое false:');
  x := F(false) and F(true);
  Writeln();
  x := F(false) and F(false);
end.
```
.
