### ISSUE TITLE
Ошибка в описании в разделе Что нового

### ISSUE THREAD

**Issue by MrSpecular** [pascalabcnet/pascalabcnet#1154]
![image](https://user-images.githubusercontent.com/42602899/45045017-7cbc1600-b07a-11e8-84e1-3750d034b37c.png)

Интерфейсы классами или записями **не наследуются**, а **реализуются**.

**Comment by miks1965** [comment]
Нет. В Issue я не буду принимать сайт

**Comment by MrSpecular** [comment]
Под «нет» подразумевается несогласие с:

> Интерфейсы классами или записями не наследуются, а реализуются.

?

**Comment by SunSerega** [comment]
Не беспокойтесь, уже исправили))

Но всё же, @miks1965, так не хорошо - вы тоже подумайте о других, тех кто постит ошибки. Дайте свою альтернативу перед тем как говорить что всё не так.

**Comment by MrSpecular** [comment]
Ещё не исправили. Только что проверил.

**Comment by miks1965** [comment]
Нехорошо замусоривать Issue

**Comment by SunSerega** [comment]
Да, я согласен, но я говорил о другом.
Скажите, куда об этом сообщать.

**Comment by miks1965** [comment]
Ну на форум, можно в личку
