### ISSUE TITLE
Почистить код модуля PABCSystem

### ISSUE THREAD

**Issue by MrSpecular** [pascalabcnet/pascalabcnet#1157]
![image](https://user-images.githubusercontent.com/42602899/45108237-bfe2bb80-b144-11e8-895e-dbbe9756a595.png)

Много подобных отрывков кода. Предлагаю почистить код системного модуля, дабы не захламлять код, когда появится желание и свободное время.

**Comment by MrSpecular** [comment]
Причина закрытия Issue не была указана. Я не телепат, чтобы догадываться почему она закрыта.

**Comment by miks1965** [comment]
Issue не относится к ошибкам компилятора
