### ISSUE TITLE
Фиксировать указатели только с параметром Pinned

### ISSUE THREAD

**Issue by ibond84** [pascalabcnet/pascalabcnet#1159]

**Comment by SunSerega** [comment]
Ну хорошо, а всё всё же проблема прописать .Free в конце блока, раз уже блокируете?

**Comment by SunSerega** [comment]
```
begin
  loop 1 do
  begin
    var a := new byte[1024];
    var ptr := @a[0];
    ptr^ := 0;
  end;//тут "a" выходит из зоны видимости, поэтому ".Free" будет безопасно вызвать прямо перед "end"
end.
```

**Comment by ibond84** [comment]
Это нельзя сделать. Указатель может передаться куда-то еще, в нативную функцию и т.д. Освобождением указателя обязан заниматься сам программист.

**Comment by SunSerega** [comment]
А вот как раз если надо передать указатель как результат - надо использовать `System.Runtime.InteropServices`, это в многочисленных дублях на стак оверфлоу сказано. И C#-ное решения, по моему, тут лучше чем то, что предлагаете вы.

**Comment by ibond84** [comment]
Ну fixed нет и не появится в ближайшее время. Поэтому создавайте все руками.
