### ISSUE TITLE
Несогласованность действий компилятора с действиями Intellisence при возврате нового экземпляра класса/записи методом без явного указания возвращаемого значения

### ISSUE THREAD

**Issue by MrSpecular** [pascalabcnet/pascalabcnet#1161]
```
type
  T = class 
    function Method() := new T(); // Program10.pas(3) : Ни один конструктор не найден
  end;

begin
end.
```
Но **Intellisence** видит конструктор:

![image](https://user-images.githubusercontent.com/42602899/45165234-0a277380-b1fd-11e8-92d4-6b1cf8a4d94a.png)

.

**Comment by ibond84** [comment]
Интеллисенс не обязан всегда согласываться с компилятором. Здесь конструктор создается автоматически, потому что интеллисенс толерантен к ошибкам.
