### ISSUE TITLE
Ошибка выполнения в C:\PABCWork.NET\Samples\Graph3D\Часы.pas

### ISSUE THREAD

**Issue by MrSpecular** [pascalabcnet/pascalabcnet#1165]
Ошибка выполнения:

> Часы.pas(4) : Ошибка времени выполнения: Ссылка на объект не указывает на экземпляр объекта.

при запуске из под оболочки.

**Comment by miks1965** [comment]
Нет, всё работает

**Comment by SunSerega** [comment]
У меня тоже нормально.

**Comment by MrSpecular** [comment]
Чтобы не быть голословным:

![image](https://user-images.githubusercontent.com/42602899/45179265-b169d200-b220-11e8-84eb-0542c079d1be.png)

.

**Comment by SunSerega** [comment]
@MrSpecular ну так что, ошибка пропала или что?
