### ISSUE TITLE
Проводится лишняя инициализация записи

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#1166]
```
type
  r1 = record 
    public function InitI1:integer;
    begin
      Result := 1;
      writeln('Инициализирован новый экземпляр r1');
    end;
    
    public i1: integer := InitI1;
  end;

begin
  var a := new r1;
end.
```
Эта программа инициализирует `a` 2 раза.

**Comment by ibond84** [comment]
Ну это как посмотреть. Первая инициализация всегда при объявлении переменной. А вторая при присваивании...

**Comment by SunSerega** [comment]
1. Это не присвоение а инициализация переменной заданным значением.
2. Если посмотреть в декомпилированный вариант - там вообще создаёт 2 переменные, обе инициализирует, при этом первую не использует, а второй, как надо, инициализирует заданным значением.

То есть надо первую переменную убрать, она лишняя.

**Comment by ibond84** [comment]
Да какая разница. Записи в паскале инициализируются автоматически при входе в подпрограмму. Инициализация (очередное присваивание) не требуется.

**Comment by SunSerega** [comment]
Это был минималистичный пример
```
type
  r1 = record 
    public function InitI1:integer;
    begin
      Result := 1;
      writeln('Инициализирован новый экземпляр r1');
    end;
    
    public i1: integer := InitI1;
    public i2: integer;
    
    constructor(i2:integer) :=
    self.i2 := i2;
  end;

begin
  var a := new r1(5);
end.
```
Это тоже так же сломано.

**Comment by miks1965** [comment]
Ну я бы все таки сказал, что это баг. Если функция readreal два раза вызывалась бы - это точно нежелательное поведение
