### ISSUE TITLE
Анализатор кода не знает про особенность констант

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#1167]
```
const
  TempFile = System.IO.Path.GetTempFileName;

begin end.
```
Для `TempFile` показывает тип `string`, хотя он `function: string`.

**Comment by ibond84** [comment]
Не знаю про такую особенность. Компилятор считает TempFile сторокой и правильно.

**Comment by ibond84** [comment]
Док-во

```
const
  TempFile = System.IO.Path.GetTempFileName;

begin 
writeln(TempFile.GetType);
end.
```

System.String

**Comment by SunSerega** [comment]
https://github.com/pascalabcnet/pascalabcnet/issues/1129#issuecomment-419720626

@miks1965 
>Да, это ограничение констант.
Напоминаю, что борясь с побочными эффектами и неинициализацией констант, мы запретили вызовы пользовательских функций при инициализации констант. Именно поэтому инициализация обычной функцией - это именно инициализация ссылкой на функцию

Если Admin не прав - переоткройте ту issue.
