### ISSUE TITLE
Вызов функции в инициализаторе константы работает как передача её ссылки

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#1168]
```
const
  TempFile: string = System.IO.Path.GetTempFileName();

begin
  writeln(TempFile);
  writeln(TempFile);
end.
```
Это выводит 2 разных имени.

Вроде, это потому что компилятор инлайнит эту константу, но это не точно.

**Comment by ibond84** [comment]
Константы-вызовы функции, а также свойства всегда инлайнятся в том месте, где вызываются. В делфи кстати const x = sin(2) не работает и правильно, именно по причине, что функции могут иметь побочные эффекты.

**Comment by SunSerega** [comment]
Константа, по определению, это то - что не может менять своё значение.
Вызовы функций инлайнить неправильно, в данном случае `TempFile` сделана константой потому - что это переменная, которую нельзя изменить после инициализации.

**Comment by miks1965** [comment]
Основная проблема - когда эти побочные эффекты затрагивают переменные в нашем коде. Если это вызов из .NET кода, он не может менять наши переменные. 

Конечно можно запретить в инициализаторах вызов любых функций, в т.ч. и NET-овских, но жалко.
По идее, константа должна получать значение первый раз вызовом этой функции и потом уже не менять своё значение.

**Comment by SunSerega** [comment]
Та нет же, надо запретить инлайн, если константа инициализировалась с вызовом функции и всё. Если константа инициализирована значением, которое нельзя посчитать на этапе компиляции - надо обрабатывать её как переменную.

**Comment by ibond84** [comment]
Я бы это безобразие вообще запретил. Нигде такого нет

**Comment by miks1965** [comment]
Ну, жалко. Я бы так оставил. Вызовами .NET-функций корректно инициализировать - они не используют переменные из своей программы. 

Остался только один редкий случай инициализации константы функцией с недетерминированным поведением.

Но если нигде в стандартных модулях и примерах этого нет, то можно и запретить

**Comment by ibond84** [comment]
Ну оставить только статические свойства из сборок .NET (вроде clBlack v GraphABC)

**Comment by SunSerega** [comment]
Всё равно останется проблема если присвоить константе `System.DateTime.Now`.

**Comment by ibond84** [comment]
Ну, статические readonly свойства только разрешить, какие проблемы. System.DateTime.Now это вообще не константа.
