### ISSUE TITLE
Бинарные файлы в репозитории и отсутствие .gitignore

### ISSUE THREAD

**Issue by Newlifer** [pascalabcnet/pascalabcnet#117]
Собственно, почему в репозитории бинарники и для какой цели? Может, стоит от них избавиться  и перенести в зависимости (если требуется)? Иначе репозиторий очень тяжёлый.

Кроме того, много лишнего мусора (вроде персональных настроек разработчиков) попадает из-за отсутствия настроенного .gitignore.

**Comment by ForNeVeR** [comment]
Товарищи, в первую очередь хотелось бы разобраться (и, возможно, документировать?), какова функциональность бинарников в репозитории. У случайного читателя создаётся впечатление (вполне вероятно, что ложное) о том, что не весь код платформы открыт.

**Comment by ibond84** [comment]
Какие бинарники вы имеете в виду?

**Comment by ibond84** [comment]
Увидел проприетарный и неиспользуемый болле PerformanceTools. Удалим. Остальные exe-файлы это наши утилитки, они редко изменяются, но часто используются, поэтому удалять exe-шники нельзя.

**Comment by miks1965** [comment]
Да, документируем, для чего какие бинарники нужны. Вообщем-то все они с исходными кодами.

**Comment by ForNeVeR** [comment]
Имеются в виду вот эти бинарники (их там довольно много): https://github.com/pascalabcnet/pascalabcnet/tree/master/bin

В идеале хотелось бы, чтобы все части, от которых есть исходники, из этих исходников и собирались.

Также есть вопрос по поводу вложенных в репозиторий исходников от некоторых библиотек (`ICSharpCode.TextEditor`, `Debugger.Core`). В идеале их бы, наверное, нужно устанавливать из Nuget? Или тут хранятся модифицированные версии? Как минимум один коммит в Debugger.Core уже был: https://github.com/pascalabcnet/pascalabcnet/commit/9318d45f850610bbaf8eb891805087840207a7a4

Возможно, стоит отправить его в апстрим или ещё как-то решить вопрос?

**Comment by ibond84** [comment]
Это сторонние библиотеки. В Nuget они врядли будут. Они очень древние. Debugger.Core в свое время сильно менялся. TextEditor тоже. Но сейчас они практически не меняются, поэтому ради экономии времени не включены в сам проект. Заменять их новыми версиями нет никакой возможности (и нужды тоже), потому что команда SharpDevelop там все сломала непонятно зачем.

**Comment by ForNeVeR** [comment]
Да, это несколько меняет дело. В такой постановке, пожалуй, приемлемо их исходники хранить у себя. Вопрос с этими библиотеками снимается.

**Comment by ForNeVeR** [comment]
Ну то есть при желании можно легко залить в Нугет, конечно, но практического смысла в этом, пожалуй, не очень много.

**Comment by ibond84** [comment]
Я думаю, issue можно закрыть. Генерируемые бинарники и прочий мусор должны быть untrackable, чтобы их можно было удалить с помощью git-clean.

**Comment by Newlifer** [comment]
@ibond84, вот славно-то! =)

**Comment by wisestump** [comment]
Я все-таки обращу внимание на отсутствие gitignore. Это добавляет ряд сложностей при разработке:

- При коммите невозможно найти добавленные файлы в куче не отслеживаемых файлов.

-  `git status` возвращает огромный список, в котором, опять же, невероятно сложно сориентироваться.

- При работе, к примеру, с NodesGenerator возникают неудобства в связи с тем, что его бинарники включены в репозиторий, в то время как SciLexer.dll - не отслеживается. В результате после выполнении `git clean` необходимо снова копировать необходимые библиотеки.

Подводя итог, gitignore, который исключал все артефакты тестов и остальной мусор, и оставлял библиотеки был бы исключительно полезен. Что касается фразы 

> Генерируемые бинарники и прочий мусор должны быть untrackable, чтобы их можно было удалить с помощью git-clean

У команды git clean есть параметр -X, который запускает очистку всех игнорируемых файлов, оставляя нетронутыми вручную созданные файлы.
