### ISSUE TITLE
ToIntegers и ToReals неэффективно реализовано

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#1171]
```
/// Преобразует строку в массив целых
function ToIntegers(Self: string): array of integer; extensionmethod;
begin
  Result := Self.ToWords().Select(s -> StrToInt(s)).ToArray();
end;

/// Преобразует строку в массив вещественных
function ToReals(Self: string): array of real; extensionmethod;
begin
  Result := Self.ToWords().Select(s -> StrToFloat(s)).ToArray();
end;
```
Select.ToArray работает медленно, потому что `ToArray` в этом случае не будет знать нужную длину и ему придётся создать много лишних массивов (временных). Надо использовать ConvertAll, оно создаёт только 1 массив.

**Comment by miks1965** [comment]
Не очень понимаю, но предложите решение

**Comment by SunSerega** [comment]
Я имею в виду заменить в обоих случаях
`.Select(s -> StrToInt(s)).ToArray()`
на
`.ConvertAll(s -> StrToInt(s))`

Я всё это когда то декомпилировал и смотрел:
- Когда `ToArray` вызывается для yield последовательности - он сначала создаёт массив в 4 элемента и начинает сохранять элементы в него. Если места не хватит - увеличивает вместимость в 2 раза. И так повторяет пока элементы не кончатся. Когда это произойдёт - оно создаёт ещё 1 массив, уже нужной длины и в него сохраняет все элементы. То есть, минимум будет создано 2 массива.
- А `ConvertAll` уже знает длину массива, поэтому оно создаёт сразу же массив правильной длины. То есть, всегда будет создан только 1 массив.

**Comment by miks1965** [comment]
Переименовал
