### ISSUE TITLE
ConvertAll неэффективно реализовано

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#1172]
```
/// Преобразует элементы массива и возвращает преобразованный массив
function ConvertAll<T, T1>(Self: array of T; converter: T->T1): array of T1; extensionmethod;
begin
  Result := System.Array.ConvertAll(self, t -> converter(t));  
end;
```
`t -> converter(t)` надо заменить на `converter`. Это лишний вызов метода.

**Comment by miks1965** [comment]
У нас это не автовыводится. И все маленькие методы инлайнятся, так что скорость такая же

**Comment by SunSerega** [comment]
А... А про то что не автовыводятся типы по возвращаемому значению `converter` - можно открыть в виде `enhancement` issue?
