### ISSUE TITLE
Компилятор считает класс-потомок абстрактным, если его абстрактный класс-предок имеет абстрактный метод

### ISSUE THREAD

**Issue by MrSpecular** [pascalabcnet/pascalabcnet#1182]
```
type
  TFirst = abstract class
    procedure Method(); abstract;
  end;
  
  TSecond = class(TFirst)
  end;
  
begin
end.
```
![image](https://user-images.githubusercontent.com/42602899/45553098-91976700-b83b-11e8-9da8-877bbd2b63ea.png)

[Источник](http://www.cyberforum.ru/pascalabc-net/thread2321050.html)

**Comment by SunSerega** [comment]
Нет, в .Net класс потомок становится абстрактным, если не все методы реализованы.

**Comment by MrSpecular** [comment]
```
namespace Test1
{
	abstract class TestClass
	{
		protected abstract int Method();
	}
	
	class TestClass2 : TestClass
	{
	}
	
	class Program
	{
		public static void Main(string[] args)
		{
		}
	}
}
```
Тогда почему тут выдает ошибку компиляции, а не делает второй класс абстрактным?
