### ISSUE TITLE
разрешает $reference для .dll в другой папке, но неправильно компилирует

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#1188]
[1.zip](https://github.com/pascalabcnet/pascalabcnet/files/2385885/1.zip)
`0.pas`:
```
{$reference 'folder\Lib.dll'}

begin
  p1('abc');
end.
```
`folder\Lib.pas`:
```
library Lib;

procedure p1(s: string) := writeln(s);

end.
```
При выполнении программы получаем:
```
Ошибка времени выполнения: System.IO.FileNotFoundException: Не удалось загрузить файл или сборку "Lib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" либо одну из их зависимостей. Не удается найти указанный файл.
Стек:
   в 0.Program.$Main()
   в 0.Program.Main()
```
Если посмотреть декомпилятором - он говорит что не может найти `Lib.dll`
Если скопировать Lib.dll в папку к `0.pas` - всё нормально запускается.

**Comment by MrSpecular** [comment]
Компилятор **не должен** реагировать падением на экзотические ошибки в коде.

**Comment by SunSerega** [comment]
Ну хорошо, но ошибка неправильная, и она должна быть на этапе компиляции а не выполнения.

**Comment by MrSpecular** [comment]
> она должна быть на этапе компиляции а не выполнения
Согласен.

**Comment by SunSerega** [comment]
> В C# например все подключенные dll копируются в место exe файла

Как вариант - сделать чтоб компилятор сам копировал все подключённые .dll в папку .exe
Это ведь не сложно реализовать?

**Comment by MrSpecular** [comment]
По-моему в проектах уже такое есть:

![image](https://user-images.githubusercontent.com/42602899/45589248-42c8fa80-b92b-11e8-9491-6add44e62d0c.png)

.

**Comment by ibond84** [comment]
В проектах сборки копируются. Простая компиляция не обязана ничего копировать.

**Comment by SunSerega** [comment]
Ну так а ошибку исправить? На этапе выполнения она не должна возникать.

**Comment by SunSerega** [comment]
@ibond84, @miks1965, ошибка всё ещё выдаётся неправильная.
Ещё раз:
Раз $reference не должен принимать полный путь к библиотеке:
>Тогда надо запретить писать путь в $reference при "обычной компиляции".

**Comment by ibond84** [comment]
А сделал автоматическое копирование в текущую папку
