### ISSUE TITLE
Отображение модификаторов доступа рядом с именем поля/свойства/метода класса/записи

### ISSUE THREAD

**Issue by MrSpecular** [pascalabcnet/pascalabcnet#1194]
```
type
  TClass = class
  private
    x: integer;
  end;

begin
end.
```
Сейчас при наведении курсора на x отображается **var TClass.x: integer**. Предлагаю сделать подсказку более информативной - отображение **[private] var TClass.x: integer**. В Pascal секции **private/protected/internel/public** могут растягиваться на много строк и очень важно знать к **какой** переменной ты обращаешься - чтобы **не** нарушить один из принципов ООП - инкапсуляцию. В **Visual Studio и #Develop** не зря так сделали.

**Comment by ibond84** [comment]
Студия не показывает никаких модификаторов доступа. Не считаю, что надо добавлять модификаторы доступа. Ибо если что-то показывается при наведении курсора, то к нему точно можно обращаться и это абсолютно не нарушает принципов ООП.

**Comment by MrSpecular** [comment]
#**Develop 4.4.1:**
![image](https://user-images.githubusercontent.com/42602899/45595001-266da200-b9ad-11e8-8d0d-e429609ec41f.png)

.

**Comment by ibond84** [comment]
SD5 вообще сейчас портянку какую-то показывает. Не надо брать с них пример.

**Comment by MrSpecular** [comment]
@ibond84, хорошо.
