### ISSUE TITLE
Написать в справке про атрибуты в Справочник по языку->Классы->Атрибуты

### ISSUE THREAD

**Issue by MrSpecular** [pascalabcnet/pascalabcnet#1195]
Сколько раз не заглядывал в этот раздел, про атрибуты ничего не было. Надеюсь, что это **Issue** мотивирует разработчиков пополнить этот раздел справки.

**Comment by SunSerega** [comment]
Атрибуты это фича из .Net, на msdn у них достаточно описания. Сделать, конечно, можно, но не обязательно.

**Comment by MrSpecular** [comment]
Тогда лучше убрать этот раздел.

**Comment by SunSerega** [comment]
Вы про какой раздел?

**Comment by MrSpecular** [comment]
Про **Справочник по языку->Классы->Атрибуты**.

**Comment by miks1965** [comment]
Написано
