### ISSUE TITLE
По разному располагает поля/свойства в зависимости от того, нажато ли Ctrl+Space или .

### ISSUE THREAD

**Issue by MrSpecular** [pascalabcnet/pascalabcnet#1198]
При нажатии **точки**:

![image](https://user-images.githubusercontent.com/42602899/45595977-4f962e80-b9bd-11e8-8b49-8b0ee211b3b9.png)

, а при нажатии **Ctrl+Space** (точка уже должна быть и курсор должен быть после нее):

![image](https://user-images.githubusercontent.com/42602899/45595986-718fb100-b9bd-11e8-84cb-de350f93afbe.png)

. В **Visual Studio и #Develop 4.4.1** в обоих случаях поведение **одинаковое**.

**Comment by ibond84** [comment]
Это не баг, а фича. В студии все по алфафиту сортируется. А у нас после точки члены класса группируются по их типу.
