### ISSUE TITLE
Кодировка файлов в репозитории

### ISSUE THREAD

**Issue by ForNeVeR** [pascalabcnet/pascalabcnet#120]
На данный момент присутствует не совсем понятный момент с кодировкой файлов в репозитории.

Всего я насчитал 2672 файла `*.cs`. Из них BOM не указан в 2053. И эти файлы в смешанных кодировках: кое-где в UTF-8, кое-где cp1251, а некоторые (например, из каталога `Debugger.Core`) местами вообще непонятно в какой.

Считаю, что следует по крайней мере сконвертировать все наши файлы из cp1251 в юникод. Возможно, стоит также добавить везде UTF-8 BOM (обсуждаемо).

Без приведения кодировок в порядок очень сложно контрибьютить в проект с машин с нерусской локалью. Например, я несколько раз был вынужден перезаливать файл [ConsoleCompiler.cs](https://github.com/pascalabcnet/pascalabcnet/pull/119/files#diff-0de5b174fef3ea9699312fe663bb49ebL4), прежде чем вышло это сделать, не портя в нём кодировку и не меняя лишнего.

Я готов заняться этим и написать скрипт для конвертации (и просмотреть затем результаты вручную, чтоб убедиться, что скрипт нигде не поменял хорошую кодировку на плохую), но нужна дополнительная информация: в каких каталогах находится непосредственно код проекта (т.е. PascalABC.NET), а в каких всякие дополнительные библиотеки, в которые мне не нужно лазить скриптом?

**Comment by ulysses4ever** [comment]
Я хоть и не разработчик, но несу ответственность за этот бардак и полностью поддерживаю наведение порядка. Я в своё время сделал кое-как, потому что просто невозможно было на ГитХабе читать сорцы — он cp1251 не отображал. Но уже не помню, как делал и почему часть не конвертнулась (хотя догадываюсь, что такие программы могут ошибаться: определение кодировок наука не вполне точная, вроде как).

А можно вопрос: каковы практические преимущества BOM?

**Comment by ForNeVeR** [comment]
Да, гитхаб до сих пор не умеет отображать cp1251.

Практические преимущества BOM заключаются в том, что все (ну или почти все) инструменты от Microsoft узнают кодировку файла именно по BOM. Например, если на машине с английской локалью в Visual Studio открыть приснопамятный файл `ConsoleCompiler.cs`, то нарисуются кракозяблы (и при сохранении этот файл вообще необратимо испортится). Проблема в том, что при открытии файла без BOM студия до сих пор считает, что он был сохранён в локальной кодировке, которая в общем случае на каждой машине своя (но иногда может для разнообразия открыть корректно и юникодовый файл).

И самое неприятное последствие отсутствия BOM в файлах: некоторые файлы открываются студией нормально (потому, что в них вообще нет русского текста), но при добавлении русских комментариев и сохранении этих файлов они смело сохраняются в cp1251 (или в кодировке локали). Именно это умолчальное поведение студии, как мне кажется, привело в итоге к "бардаку". Я думаю, что изначально файлы были преобразованы корректно [вот в этом коммите](https://github.com/pascalabcnet/pascalabcnet/commit/49378a6750a8ee31b5083e0a2f0876bc3e2aee4c), но потом их редактировали (и добавляли русский текст туда, где его раньше не было), что и вызвало итоговые проблемы.

В мире пользователей Linux, напротив, обычно текстовые файлы считаются сохранёнными в UTF-8 (хотя это и зависит от системной локали, но она почти у всех уже давно в UTF-8), а к практике сохранения BOM в текстовых файлах относятся с неодобрением. Именно поэтому я не уверен, что будет приемлемо для всех участников проекта. Хотя в своих собственных проектах (как открытых, так и при коммерческой разработке) на C# строго соблюдаю правило добавления UTF-8 BOM во все текстовые файлы.

**Comment by ulysses4ever** [comment]
Ой, замечательно вы написали — теперь всё стало на свои места. Осталось добавить, что я как раз пользователь Линукса и моё отношение к BOM соотвествтующее :) Но! Я думаю, что в данном случае и с учётом вашего описания было бы разумно сконвертировать всё в BOM. Я думаю, что разработчики сказали бы вам спасибо. Не знаю, чего они молчат: заняты, наверное.

**Comment by ibond84** [comment]
Хорошо, отконвертируем. Debugger.Core сторонняя библиотека, там кодировка Windows1252. Спасибо студии за

**Comment by ibond84** [comment]
Студия понимает UTF8 и без BOM.

**Comment by ForNeVeR** [comment]
Да, это верно. Изначально я написал, что не понимает, но быстро исправил.

**Comment by miks1965** [comment]
ForNeVeR, я вот не понял, есть проблема в Студии с UTF8 без BOM? ibond84 пишет, что нет, Вы пишете, что изначально написали, что есть, потом исправили, но ничего не исправили.

**Comment by ForNeVeR** [comment]
Проблема в студии с UTF-8 без BOM **есть**, только её несколько сложно обрисовать в двух словах.

Файлы в UTF-8 без BOM _открываются_ нормально (именно это я сначала описал неправильно, т.к. в некоторых очень редких случаях всё-таки файлы открываются криво, но в основном нормально). Плохо **сохраняются** файлы с UTF-8 без BOM, в которых нет ни одного символа за пределами ASCII, если в них добавить русский текст.

Вот простой эксперимент, который показывает проблему:

1. Создайте текстовый файл в обычном виндовом блокноте со словом "test". Поскольку в этом файле нет ни одного символа за пределами ASCII, этот файл может считаться "UTF-8 без BOM".
2. Откройте этот текстовый файл в Visual Studio.
3. Добавьте строчку русского текста, например, "тест".
4. Сохраните файл.

На выходе получите файл в cp1251 (если локаль на машине русская), хотя _на самом деле_ хотелось бы UTF-8 без BOM, потому что исходный файл мы считали "UTF-8 без BOM".

Именно это сейчас может произойти при редактировании исходного кода, если кто-нибудь добавит русские комментарии.

**Comment by miks1965** [comment]
А-а, понял. В двух словах так: если текст - из ASCII-символов, то без BOM его можно трактовать и как cp1251 и как UTF-8.

Тогда переводите все .cs в UTF-8 с BOM.

**Comment by miks1965** [comment]
Так, закрываю тему с кодировками. Никто не захотел перевести - и ладно
