### ISSUE TITLE
Добавить теги для документирования

### ISSUE THREAD

**Issue by MrSpecular** [pascalabcnet/pascalabcnet#1200]
Пример документирования в **Visual Studio**:
```
/// <summary>
/// Описание самого метода.
/// </summary>
/// <param name="x">Описание параметра x.</param>
/// <returns>int</returns>
```
. Предлагаю сделать упрощенный аналог (на усмотрение разработчиков). Это будет полезно тем, кто пишет более-менее серьезные программы, требующие документирования. Конечно, не вещь первой необходимости, но все-же.

**Comment by ibond84** [comment]
Они давно есть

**Comment by MrSpecular** [comment]
Вы хотите сказать, что многое что есть в Visual Studio для документирования (в плане тегов) здесь есть?
