### ISSUE TITLE
Убрать "грязную" конкатенацию строк

### ISSUE THREAD

**Issue by MrSpecular** [pascalabcnet/pascalabcnet#1201]
Обсуждение [здесь](http://forum.mmcs.sfedu.ru/t/konkatenacziya-strok/2511/13).

**Comment by miks1965** [comment]
Ну, это кто где грязь видит знаете. Во Free Pascal это есть, у нас - совместимость.

**Comment by MrSpecular** [comment]
Хорошо. Принято.

**Comment by spectatorBH** [comment]
@miks1965 Извините, я не понял, о какой совместимости конкретно идет речь? Такой код НЕ работает во Free Pascal 3.0.4:
```
var s: string;
begin
  s := 'aaa' 'bbb' 'ccc';
end;
```
**Fatal: Syntax error, ";" expected but "const string" found**

Именно такая ситуация и была вами названа на форуме, как "грязная реализация конкатенации с литералами-символами, что надо убирать". Почему же тогда закрыли issue?

**Comment by miks1965** [comment]
Это уже не работает

**Comment by spectatorBH** [comment]
Так при чем тогда ссылка на совместимость с FP? О чем речь? 

К тому же в последней публичной сборке 1790 это ЕЩЕ работает по-старому, несмотря на коммит da91abdad497fa138917eeeb535b7f64fafa5714

**Comment by miks1965** [comment]
Мы закрываем Issue не для наших читателей, а потому что Issue выполнен и закрыт. Смотрите коммиты

**Comment by SunSerega** [comment]
@miks1965 я согласен с тем что issue не для читателей закрываются, но как тому кто постоянно тестирует и находит ошибки в паскале - мне очень неудобно когда вы не добавляете в коммит референс к хотя бы 1 issue которая как то связана с коммитом.

Достаточно добавить " #1201 ", даже не " fix #1201 ", и даже не в основной текст - а в описание (вторая строчка названия коммита). Потом искать в каком коммите что было исправлено, без этого - очень сложно.

**Comment by spectatorBH** [comment]
> Во Free Pascal это есть, у нас - совместимость.

@miks1965 Может быть, вы поясните все-таки как этот issue связан с упомянутой вами совместимостью с Free Pascal? А то, мне кажется, у нас тут иногда получается разговор слепого с глухим. Кто-то задает один вопрос, вы же отвечаете на какой-то свой и при этом советуете "не задавать вопросов".

**Comment by miks1965** [comment]
Это неправильно:
```
var s: string;
begin
  s := 'aaa' 'bbb' 'ccc';
end.
```
Мы это убрали.

Это правильно:
```
var s: string;
begin
  s := 'aaa'#10 'bbb'#10 'ccc';
end.
```
мы это оставили

**Comment by ibond84** [comment]
а в чем смысл, если пробел между строками можно все равно ставить?

**Comment by SunSerega** [comment]
1. На сколько я понял - в FP это можно.
2. Это:
```
begin
  var s :=
  'aaa'#10
  'bbb'#10
  'ccc';
end.
```
Лучше чем это:
```
begin
  var s := 'aaa'#10'bbb'#10'ccc';
end.
```
