### ISSUE TITLE
Ошибки в Общие сведенья->Отличия языка PascalABC.Net от Delphi Object Pascal

### ISSUE THREAD

**Issue by MrSpecular** [pascalabcnet/pascalabcnet#1203]
[Ссылка 1](http://forum.mmcs.sfedu.ru/t/zamechaniya-i-predlozheniya/143/1033)
[Ссылка 2](http://forum.mmcs.sfedu.ru/t/zamechaniya-i-predlozheniya/143/1037)

**Comment by ibond84** [comment]
Ничего не понятно

**Comment by ibond84** [comment]
Так оформленные issue не рассматриваются

**Comment by MrSpecular** [comment]
Отредактировано.
