### ISSUE TITLE
class от предописаний классов подсвечивается

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#1206]
```
type
  t1=class;
  t1 = class
    
  end;

begin end.
```
![image](https://user-images.githubusercontent.com/27270190/45634248-8dbd4c00-baaa-11e8-8e63-0e3e61537819.png)

Это так работает и если после предописания класса будет описание, к примеру, интерфейса. Поэтому надо полностью запретить подсвечивание предописаний.

**Comment by MrSpecular** [comment]
@ibond84, Issue не исправлена. Все так же подсвечивается.

**Comment by SunSerega** [comment]
билд 1790 вышел 15.09 (это можно посмотреть в "Помощь>>О программе"). А коммит был выпущен 17.09 . Коммиты не сразу попадают в релиз.
