### ISSUE TITLE
"Нельзя преобразовать function: t1 к Func<t1>" при присвоении конструктора лямбде

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#1208]
```
type
  t1=class
    constructor := exit;
  end;

begin
  var f: ()->t1 := t1.Create;
end.
```
`Ошибка: Нельзя преобразовать тип function: t1 к Func<t1>`

Как минимум надо нормальную ошибку.
Хотя желательно разрешить копировать указатель на конструктор, а не только вызывать его, во всех выражениях.

**Comment by ibond84** [comment]
Не понял, где тут ошибка.

**Comment by SunSerega** [comment]
`function: t1` и `Func<t1>` совместимые типы, их можно друг к другу преобразовать:
```
type
  t1=class end;

begin
  var f1: function: t1;
  var f2: Func0<t1>;
  f2 := f1;//работает
end.
```

Если получать ссылку на конструктор нельзя - надо или написать
`Нельзя преобразовать тип t1 к Func<t1>`, то есть как если это вызов конструктора, или свою собственную ошибку.

А если можно - то исправить то, что компилятор ругается на этот код.

**Comment by MrSpecular** [comment]
@SunSerega, насколько знаю, C# не выполняет преобразования делегатов при соответствии их сигнатур.

**Comment by SunSerega** [comment]
Если бы тут в 1 неоднородности было дело... Если написать так:
```
type
  t1=class
    constructor := exit;
  end;

begin
  var f: function: t1 := t1.Create;
end.
```
Получаем:
`Нельзя преобразовать тип function: t1 к $delegate0`

С `Func` ошибка и то лучше.

**Comment by MrSpecular** [comment]
@SunSerega, на мой взгляд, эта ошибка показывает внутренности компилятора, что неправильно. На мой взгляд, такого быть не должно.

**Comment by SunSerega** [comment]
> внутренности компилятора, что неправильно

Конечно, но тут 2 ошибки наложились друг на друга. То, что тут показывает внутренности - пропадёт если исправить ошибку описанную в заголовке это issue.

Но, кстати, названия внутренние делегатов много где ещё так светит, можете найти другой пример, где это единственная ошибка - и вот с ним уже можно создавать issue.

**Comment by MrSpecular** [comment]
[Issue](https://github.com/pascalabcnet/pascalabcnet/issues/1227) сделано.

**Comment by ibond84** [comment]
Сейчас выводится правильное сообщение об ошибке:

```
Нельзя преобразовать тип t1 к Func<t1>
```

Закрываю
