### ISSUE TITLE
Внутренняя TypeLoadException при замене Action0 на procedure в сигнатуре виртуальной функции

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#1211]
```
type
  I1 = interface
    function f1: Action0;
  end;
  t1 = class(I1)
    public function f1: procedure := nil;
  end;

begin end.
```
```
() : Внутренняя ошибка компилятора в модуле [pabcnetc.exe] :'System.Exception: System.TypeLoadException: Отсутствует реализация метода "f1" в типе "0.t0" из сборки "0, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null".
   в System.Reflection.Emit.TypeBuilder.TermCreateClass(RuntimeModule module, Int32 tk, ObjectHandleOnStack type)
   в System.Reflection.Emit.TypeBuilder.CreateTypeNoLock()
   в System.Reflection.Emit.TypeBuilder.CreateType()
   в PascalABCCompiler.NETGenerator.ILConverter.CloseTypes()
   в PascalABCCompiler.NETGenerator.ILConverter.ConvertFromTree(IProgramNode p, String TargetFileName, String SourceFileName, CompilerOptions options, String[] ResourceFiles)
   в PascalABCCompiler.Compiler.Compile()'
```

**Comment by SunSerega** [comment]
А вот так всё становится хуже, на много:
```
type
  t0 = class
    function f1: Action0; virtual := ()->writeln(1);
  end;
  t1 = class(t0)
    public function f1: procedure; override := ()->writeln(2);
  end;

begin
  var a: t0 := new t1;
  a.f1()();
end.
```
Ошибки не выдаёт, зато виртуальная цепочка разорвана. Эта программа выводит 1.

**Comment by miks1965** [comment]
В последнем случае это разные типы так что всё правильно

**Comment by MrSpecular** [comment]
На примере **C#**:
```
using System;

namespace ConsoleApp1
{
	public delegate void MyAction();
	
	interface I1
	{
		Action Method();
	}
	
	class T1 : I1
	{
		public MyAction Method()
		{
			return null;
		}
	}
	
    class Program
    {
        static void Main(string[] args)
        {
        	MyAction x1;
        }
    }
}
```
правильное поведение:

> ConsoleApp1.T1 не реализует член интерфейса "ConsoleApp1.I1.Method()". "ConsoleApp1.T1.Method()" не удается реализовать "ConsoleApp1.I1.Method()", поскольку он не содержит соответствующего типа возвращаемого значения "System.Action". (CS0738) - C:\Users\Admin\Documents\SharpDevelop Projects\Test1\Test1\Program.cs:21,8

.

**Comment by MrSpecular** [comment]
@SunSerega, Ваш код выдает ошибку компиляции:
![image](https://user-images.githubusercontent.com/42602899/45733272-cf541100-bbe8-11e8-81f9-a7aa1ccc4f26.png)

. PascalABC.Net 3.4.2.1782.

**Comment by SunSerega** [comment]
>всё правильно

Нет, раз разные типы - должно выдавать ошибку при попытке поставить `override`:
`Нет метода для переопределения`
А оно втихую делает вид что всё в порядке, а потом на рантайме невозможно понять что пошло не так.
