### ISSUE TITLE
StrToFloat и TryStrToFloat не согласны друг с другом

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#1213]
```
begin
  StrToFloat('1.1').Println;//работает - 1.1
  var v: real;
  TryStrToFloat('1.1', v).Println;//false
end.
```

**Comment by SunSerega** [comment]
На сроках 7919-7920 в PABCSystem надо заменить `nil` на `new Globalization.NumberFormatInfo`.
Это сделает так, что для при проверке будет использована нейтральная культура, вместо языка системы.

**Comment by miks1965** [comment]
> На сроках 7919-7920 в PABCSystem надо заменить nil на new Globalization.NumberFormatInfo (или nfi, это переменная хранящая готовый экземпляр).
> Это сделает так, что для при проверке будет использована нейтральная культура, вместо языка системы.

Согласен
