### ISSUE TITLE
Проект перестал собираться

### ISSUE THREAD

**Issue by miks1965** [pascalabcnet/pascalabcnet#122]
после того как я откомментировал безобидные методы Add для тьюплов

**Comment by ibond84** [comment]
Тесты падают?

**Comment by miks1965** [comment]
Да. Обычные тесты проходят. Падает в третьем наборе тестов, которые по-моему делаются с подключенным ускорением из-под оболочки. Рубится на первом же файле, содержащем метод add, с сообщением: 
![untitled-1](https://cloud.githubusercontent.com/assets/10325391/13930896/e283f322-efb1-11e5-8359-36be8723cea8.jpg)
