### ISSUE TITLE
Intellisence не выводит описание любых членов (типы, методы, поля и т.д), определенных в сторонних сборках

### ISSUE THREAD

**Issue by MrSpecular** [pascalabcnet/pascalabcnet#1223]
![image](https://user-images.githubusercontent.com/42602899/45725126-f5b28600-bbc1-11e8-81f7-fe21f6536ae0.png)

**Comment by SunSerega** [comment]
Да, что то есть, но словить сложно, потому что у всех что то своё сломано. У меня вот `System.Math.Cos` показывает своё описание. Но когда я находил и писал о вещах которые у меня не показывает - разработчики говорили что всё показывается и на этом разговор заканчивался.

**Comment by MrSpecular** [comment]
Я предлагаю оставить эту Issue и собрать больше информации, создав соответствующую тему на форуме. То, что у разработчиков не воспроизводится - не очень весомый аргумент на фоне того, что у других ошибки проявляются.

**Comment by ibond84** [comment]
PascalABC.NET + Microsoft .NET Framework v4.7 (Setup, 71 Mb)
Для первой установки
Содержит:
Система программирования PascalABC.NET
Задачник PT4
Платформа Microsoft .NET Framework v4.7.1
Russian Language Pack for .NET v4.0 (русификация сообщений о ошибках времени выполнения)
**Framework Class Library Help (документация для всплывающей подсказки)**

Подсказки есть в full-версии. Можете еще закачать в $WINDIR\Microsoft.NET\Framework64\v4.0.30319\ru\ содержимое папки ReleaseGenerators\DotNet471\Tooltips\ репозитория
