### ISSUE TITLE
Подсказка Intellisence для DynamicInvoke в определениях подпрограмм уезжает в сторону :=

### ISSUE THREAD

**Issue by MrSpecular** [pascalabcnet/pascalabcnet#1226]
![image](https://user-images.githubusercontent.com/42602899/45730933-6f0ba200-bbdd-11e8-9975-27020bc01f94.png)

Код:
```
procedure P(x: Action0) :=                 x.DynamicInvoke();

begin
end.
```

Вне подпрограмм с все нормально:
![image](https://user-images.githubusercontent.com/42602899/45730979-b2661080-bbdd-11e8-9f54-62316e437daf.png)
.

**Comment by SunSerega** [comment]
Добавьте код программы, чтоб было легче воспроизвести.

**Comment by ibond84** [comment]
У меня не воспроизводится

**Comment by SunSerega** [comment]
Не спешите сразу закрывать. У меня воспроизводится.

**Comment by SunSerega** [comment]
@MrSpecular может на форуме что то напишите по этому поводу?))

**Comment by MrFresnel** [comment]
Да, разумеется.
