### ISSUE TITLE
Intellisence отображает () -> () как System.Action

### ISSUE THREAD

**Issue by MrSpecular** [pascalabcnet/pascalabcnet#1228]
```
begin
  var x1: () -> (); // Sytem.Action
  var x2: procedure(); // procedure
  
  var y1: () -> byte; // () -> byte
  var y2: function(): byte; // function: byte
end.
```

Следует обратить внимание на то, что тип **x1** показывается как **System.Action**. Разве это правильно показывать **System.Action**, если у меня совершенно другой **анонимный тип делегата**, только совпадающий по сигнатуре с **System.Action**? Разумеется, **нет**. К примеру, код **C#**:
![image](https://user-images.githubusercontent.com/42602899/45732021-1b9c5280-bbe3-11e8-995a-fcfdca3c2528.png)
, здесь я объявил переменную **x1** типа **MyAction**, сигнатура типа делегата **MyAction** равна сигнатуре типа делегата **System.Action**, но почему тогда там тип **x1** не показывается как **System.Action**?

**Comment by miks1965** [comment]
У нас это синоним Action

**Comment by MrSpecular** [comment]
Тогда почему procedure не синоним Action?

**Comment by miks1965** [comment]
Это разные типы. Это не завичит от того что Вам хочется

**Comment by MrSpecular** [comment]
Intellisence был другого мнения на счёт Func<T>.
