### ISSUE TITLE
Функции возвращающие делегат вызываются 2 раза

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#1229]
```
function f1: procedure;
begin
  writeln(1);
  Result := ()->writeln(2);
end;

begin
  var p: procedure;
  p := f1();
  p();
end.
```
Вывод:
```
1
1
2
```
Если декомпилировать - видим следующее:
```
function f1: procedure;
begin
  writeln(1);
  Result := ()->writeln(2);
end;

begin
  var p: procedure;
  p := ( f1()=nil )? nil : f1();
  p();
end.
```
Надо как минимум вывести результат `f1()` в отдельную переменную, хотя я не совсем понимаю зачем тут нужно бред вроде `(b=true)?true:false`.

**Comment by ibond84** [comment]
Ну надо читать оригиналы, а не бредовые выхлопы декомпилятора

  IL_0000:  nop
  IL_0001:  call       class Program1306.$delegate0 Program1306.Program::f1()
  IL_0006:  ldnull
  IL_0007:  ceq
  IL_0009:  brfalse    IL_0014
  IL_000e:  ldnull
  IL_000f:  br         IL_0024
  IL_0014:  call       class Program1306.$delegate0 Program1306.Program::f1()
  IL_0019:  ldftn      instance void Program1306.$delegate0::Invoke()
  IL_001f:  newobj     instance void Program1306.$delegate1::.ctor(object,
                                                                   native int)
  IL_0024:  stloc.0
  IL_0025:  ldloc.0
  IL_0026:  callvirt   instance void Program1306.$delegate1::Invoke()

А так, да. Надо сохранять в переменной
