### ISSUE TITLE
Readme says that building and running tests on Linux and OSX requires sudo

### ISSUE THREAD

**Issue by MyLittleRobo** [pascalabcnet/pascalabcnet#123]
Why?

**Comment by ibond84** [comment]
_RebuildReleaseAndRunTests.sh installs the PABCRtl.dll assembly in the Mono GAC.

**Comment by MyLittleRobo** [comment]
The reason should be stated clearly and the workaround should be provided (setting MONO_PATH?)

Even with no workaround I guess there's no point in running the whole script as root. If you run script with sudo all generated files will have set their owner to root which is bad because repository is usually cloned by regular user.

**Comment by ibond84** [comment]
gacutil requires the root privileges. 

>If you run script with sudo all generated files will have their owner set to root which is bad because repository is usually cloned by regular user.

Yes, you are right. I have changed the script and readme
