### ISSUE TITLE
Intellisence показывает () -> T вместо Func<T>

### ISSUE THREAD

**Issue by MrSpecular** [pascalabcnet/pascalabcnet#1230]
```
begin
  var x: () -> (); // Sytem.Action
  var y: () -> byte; // () -> byte, вместо System.Func<byte>
end.
```

**Comment by ibond84** [comment]
Это абсолютно идентичные записи. Или я что-то не понимаю?

**Comment by ibond84** [comment]
Ну я оставлю () -> (). Это более наглядно, чем какие-то Action

**Comment by miks1965** [comment]
Там наоборот. У Вас отображается как раз Action

**Comment by miks1965** [comment]
Считаю, что подсказка Action более информативная, чем ()->()
А для остального надо так и оставить. В частности, integer->integer

**Comment by MrFresnel** [comment]
> Считаю, что подсказка Action более информативная

Тогда лучше привести в соответствие и случай с `() -> T:` сделать, чтобы **Intellisence** отображал тип как `Func<T>`.

**Comment by miks1965** [comment]
А T->T - как Func<T,T>? Вы считаете это более информативным?

**Comment by MrFresnel** [comment]
Да, считаю.

**Comment by miks1965** [comment]
Ясно. Мы так не считаем. Тип T->T делался как более человеческий и принятый в других языках.

Просьба не тянуть сюда бэкграунд из C#
