### ISSUE TITLE
Использование abstract и virtual вместе для методов разрешено

### ISSUE THREAD

**Issue by MrSpecular** [pascalabcnet/pascalabcnet#1231]
```
type
  TClass = abstract class
    procedure Method1(); abstract; virtual;
    procedure Method2(); virtual; abstract;
    
    function Method3(): byte; abstract; virtual;
    function Method4(): byte; virtual; abstract;
  end;

begin
end.
```
В **C#**:
```
using System;

namespace ConsoleApp1
{
	public abstract class cl<T>
	{
		public abstract virtual void m();
	}
	
	class Program
	{
		static void Main(string[] args)
		{
		}
	}
}
```
аналогичный код выдаст **ошибку компиляции**:

> Абстрактный метод "ConsoleApp1.cl<T>.m()" не может быть помечен как виртуальный (CS0503) - C:\Users\Admin\Documents\SharpDevelop Projects\Test1\Test1\Program.cs:16,32

.

**Comment by ibond84** [comment]
В паскале так можно

**Comment by MrSpecular** [comment]
А здравый смысл уже не учитывается? Покажите мне доказательство на другом диалекте Pascal где так можно. Иначе от Вас ни одного аргумента я так и не увидел.
