### ISSUE TITLE
Абстрактные свойства могут иметь реализацию

### ISSUE THREAD

**Issue by MrSpecular** [pascalabcnet/pascalabcnet#1232]
```
type
  TClass = abstract class
    fName: byte;
    property Name1: byte read fName write fName; abstract;
    property Name2: byte read 0 write begin end; abstract;
  end;

begin
end.
```
Если тип свойства **(T, T2, ...)** или свойство **readonly/writeonly**:
```
type
  TClass = class
    property X1: (integer, integer) read (0, 0); abstract;
    property X2: byte read 0; abstract;
  end;

begin
end.
```
, то компилятор **упадет**:

![image](https://user-images.githubusercontent.com/42602899/45792728-c110fe00-bc97-11e8-84f8-1435335a9429.png)

.
В **C#**:
```
using System;

namespace ConsoleApp1
{
	public abstract class cl<T>
	{
		int property;
		
		public abstract int Property {
			get { return property; }
			set { property = value; }
		}
	}
	
	class Program
	{
		static void Main(string[] args)
		{
		}
	}
}
```
аналогичный код выдаст **ошибку компиляции**:

> "ConsoleApp1.cl<T>.Property.get" не может объявить тело, так как помечен как абстрактный (CS0500) - C:\Users\Admin\Documents\SharpDevelop Projects\Test1\Test1\Program.cs:19,4

> "ConsoleApp1.cl<T>.Property.set" не может объявить тело, так как помечен как абстрактный (CS0500) - C:\Users\Admin\Documents\SharpDevelop Projects\Test1\Test1\Program.cs:20,4

.

**Comment by MrFresnel** [comment]
![image](https://user-images.githubusercontent.com/42812113/45925319-88815680-bf1b-11e8-83aa-bbebe9613312.png)

Issue не исправлена.

**Comment by ibond84** [comment]
Ну это другая какая-то ошибка с автосвойствами. Это к @miks1965

**Comment by ibond84** [comment]
Исправлено
