### ISSUE TITLE
Методы расширения не отображаются по Ctrl+Space для целочисленных литералов

### ISSUE THREAD

**Issue by MrSpecular** [pascalabcnet/pascalabcnet#1235]
![image](https://user-images.githubusercontent.com/42602899/45800107-81a6d980-bcb8-11e8-993a-8399bac3adf8.png)

```
procedure Extension(self: integer); extensionmethod := exit;

begin
  1.
end.
```

**Comment by miks1965** [comment]
Это правильно. Мы думаем, что Вы хотите написать вещественное число

**Comment by spectatorBH** [comment]
Я так понимаю, нюанс был именно в принудительном вызове контекстной подсказки по Ctrl-Space, а не срабатывание по нажатию точки. Эти события в Intellisense можно отличать вообще?

**Comment by spectatorBH** [comment]
> Вопрос закрыт

@miks1965 Мда... А потом вы удивляетесь, что кто-то обижается и начинает писать везде про вас и ваше детище разный негатив. Зачем же такой резкий тон в общении со своими активными тестерами? Человек написал вполне валидный issue, а вы просто повторили свой не очень сильный аргумент и "бросили микрофон". Нехорошо.  :-/

Я бы понял, если бы не было технической возможности отличить одно состояние от другого (нажатие точки от Ctrl-Space). Или просто: *нам недосуг фиксить такую мелочь, извините!* -> [WONTFIX] 

А так обрубать, игнорируя чужие аргументы...

**Comment by MrSpecular** [comment]
@miks1965, вопрос не закрыт. Вы так и не ответили мне на:
> Разве нельзя это Issue оставить, а потом, при наличии времени и желания, исправить?
.

**Comment by MrFresnel** [comment]
Повторю свой вопрос:
> Почему Visual Studio так не думает?
.
