### ISSUE TITLE
При подключении PT4Exam к пустой программе программа падает при выполнении

### ISSUE THREAD

**Issue by MrSpecular** [pascalabcnet/pascalabcnet#1236]
```
uses PT4Exam; 
begin 
end.
```
При выполнении выдает:

> PABCSystem.pas(5893) : Runtime exception: Для файловой переменной не вызвана процедура Assign

![image](https://user-images.githubusercontent.com/42602899/45826755-b7ba7c80-bcfd-11e8-9ff3-083050aaf325.png)

.

**Comment by miks1965** [comment]
Это недокументированные модули. Не загружайте их
