### ISSUE TITLE
Выдает неправильную ошибку при abstract/sealed record

### ISSUE THREAD

**Issue by MrSpecular** [pascalabcnet/pascalabcnet#1237]
```
type
  TRecord = sealed record // или abstract
  end;

begin
end.
```
Выдает ошибку:
> Program4.pas(2) : Встречено 'record', а ожидалось sealed

, что **неправильно**, более того, эта ошибка лишь путает. В ошибке должно указываться на то, что **abstract/sealed не применим к record**, как в **#Develop 4.4.1**, например:
![image](https://user-images.githubusercontent.com/42602899/45828741-fa7e5380-bd01-11e8-82f3-bf5c8a412ceb.png)

.

**Comment by ibond84** [comment]
Ну в грамматике record не может иметь атрибутов. Все правильно.

**Comment by SunSerega** [comment]
Да, не может, это ошибочный код, но ошибку надо сделать нормальную. Эта ничего не объясняет.

**Comment by SunSerega** [comment]
@ibond84, @miks1965 ошибку всё ещё выводит неправильную.

**Comment by miks1965** [comment]
Надо в грамматике разрешить всю эту хрень и на неё ругаться

**Comment by ibond84** [comment]
Но только не доводить до семантики. Там этих проверок на абстрактные запечатанные интерфейсы уже тьма.

**Comment by miks1965** [comment]
Это можно прямо в файле грамматики проверить. Только скажите, что. Какие ещё слова проверить перед record?

**Comment by SunSerega** [comment]
Ну, вроде только `abstract`, `sealed` и `static`. @MrSpecular а вы не помните что то ещё?

**Comment by MrFresnel** [comment]
Нет... Не припоминаю.

**Comment by SunSerega** [comment]
А, ещё может быть `auto`.
