### ISSUE TITLE
Должна выдаваться ошибка компиляции

### ISSUE THREAD

**Issue by miks1965** [pascalabcnet/pascalabcnet#124]
```
procedure p<T>(i: integer);
begin

end;

begin
  
end.
```

**Comment by ibond84** [comment]
А почему она должна выдаваться? Программа абсолютно корректная. В C# все компилируется.

**Comment by ibond84** [comment]
а при вызове p(2) будет ошибка компиляции: надо инстанцировать явно

**Comment by miks1965** [comment]
Да, действительно - я не прав - в C# работает. Закрываю.
