### ISSUE TITLE
Разрешить абстрактные события

### ISSUE THREAD

**Issue by MrSpecular** [pascalabcnet/pascalabcnet#1240]
```
type
  TClass = class
    event fX: Action0; abstract; // Запрещено.
  end;

begin
end.
```
В **C#** это разрешено:
```
using System;
 
namespace ConsoleApp1
{
	abstract class I1
	{
		public abstract event Action e;
	}
	
	class Program
	{
		static void Main(string[] args)
		{
		}
	}
}
```
.

**Comment by miks1965** [comment]
У нас не C#

**Comment by MrSpecular** [comment]
Где конкретика? Точнее, конкретно почему не желайте их разрешить?

**Comment by miks1965** [comment]
Абстрактные события - это свойство языка. В другом языке их может не быть.

Для ниши PascalABC.NET (учебная, академическая) у этой фичи нет применения.

Поэтому мы не приняли вашу enhancement.

Обращаю также ваше внимание, что мотивировка "В C# так сделано" не может служить аргументом.

**Comment by MrFresnel** [comment]
Может только если подкрепляется и другими аргументами.

**Comment by miks1965** [comment]
> match-with не должно быть в языке, следуя такой логике.
Нет, Вы ошибаетесь. Это частично используется например в курсе оптимизирующих компиляторов.

Академическая сфера может превосходить промышленную сферу по мощности. В частности, именно поэтому в C# нет того, что мы условно называем type-классами или впоследствии будем называть концептами

**Comment by MrFresnel** [comment]
Хорошо. Вас понял.
