### ISSUE TITLE
Компилятор падает при описании абстрактного индексатора в абстрактном классе

### ISSUE THREAD

**Issue by MrSpecular** [pascalabcnet/pascalabcnet#1242]
```
type
  TClass = class // Если добавить abstract, то все нормально.
    property X[index: byte]: byte read write; abstract; // Работает также и для readonly/writeonly индексаторов.
  end;

begin
end.
```
**Issue** из [этой ](https://github.com/pascalabcnet/pascalabcnet/issues/1238)серии.

**Comment by miks1965** [comment]
readonly/writeonly
У нас нет таких ключевых слов

**Comment by ibond84** [comment]
Ну, имелось в виду read без write и наоборот

**Comment by miks1965** [comment]
Надо так и писать. А то шарады разгадывать не хочется

**Comment by MrFresnel** [comment]
> Надо так и писать. А то шарады разгадывать не хочется

Да, согласен с Вами.
