### ISSUE TITLE
Добавить writeonly для свойств и индексаторов

### ISSUE THREAD

**Issue by MrSpecular** [pascalabcnet/pascalabcnet#1243]
```
type
  TClass = class
    property X: byte read 0;
    property Y: byte write begin end;
  end;

begin
end.
```
Неравномерно сделано - **readonly** есть, а **writeonly** - нет. Если есть на то причины, то приведите их здесь.

**Comment by miks1965** [comment]
readonly вроде нет такого ключевого слова

**Comment by MrSpecular** [comment]
Вроде?

**Comment by miks1965** [comment]
Я бы убрал это readonly. Мне оно не нравится, т.к. сбивает. Достаточно оставить read

**Comment by miks1965** [comment]
В подсказке надо писать 

read;

write;

или ничего

**Comment by MrFresnel** [comment]
Хорошо. Согласен на read/write.

**Comment by SunSerega** [comment]
Если что - `writeonly` свойства таки добавили.

**Comment by miks1965** [comment]
writeonly - нет у нас такого ключевого слова. write-свойства были всегда

**Comment by SunSerega** [comment]
Это не ключевое слово, а название понятия в программировании.
То есть вот ключевое слово - это `match`. А название понятия в этом случае - паттерн мачинг.
