### ISSUE TITLE
Ошибка в Справочник по языку -> Типы данных -> Кортежи

### ISSUE THREAD

**Issue by MrFresnel** [pascalabcnet/pascalabcnet#1245]
> Кортеж - это тип данных, являющийся разновидностью **записи**. 

В PascalABC.Net кортежи - **классы**, а **не** записи.

В доказательство можно привести следующий код:
```
begin
  Writeln((1, 2, 3).GetType().IsValueType); // False
end.
```
.

**Comment by miks1965** [comment]
Да. Исправили. "являющийся аналогом"

**Comment by MrFresnel** [comment]
Нет. Кортеж System.Tuple<T, T2, ...> - не тип значения, а ссылочный тип.

**Comment by miks1965** [comment]
Вы почему-то концентрируетесь на внутреннем представлении. Это всего лишь малая часть сходств и отличий. Более того, низкоуровневая. Это стандартная ошибка, когда детали затуманивают абстракцию.

Кортеж, как и запись и как и класс, содержит поля разных типов. Его внутреннее представление второстепенно.

**Comment by MrFresnel** [comment]
> Это стандартная ошибка, когда детали затуманивают абстракцию.

Не вижу каким образом они ее затуманивают в данном случае. Понимание затруднится от того, что я скажу что **System.Tuple<T, T2, ...>**  является ссылочным типом?

**Comment by miks1965** [comment]
Кортеж - это не System.Tuple, а (T1,T2). А System.Tuple - да - ссылочный

**Comment by MrFresnel** [comment]
Исправил неточность. Кортеж - объект типа **System.Tuple<T, T2, ...>**.

**Comment by miks1965** [comment]
В будущем реализация может поменяться. В справке это отмечено

**Comment by MrFresnel** [comment]
Я бы не менял реализацию, а добавил новую. В C# есть два варианта кортежей. Первые - ссылочные оставлены по большей части из-за обратной совместимости, вторые - новые. В данном случае фактор обратной  совместимости я бы не стал игнорировать.
