### ISSUE TITLE
Неверная инициализация записи в IL

### ISSUE THREAD

**Issue by miks1965** [pascalabcnet/pascalabcnet#1248]
```
type
  B = record
    x := 1;
    constructor Create(xx: integer);
    begin
      x := xx
    end;
  end;

begin
  var bb := new B(10);
  System.Console.Writeline(bb.x);
end.
```
Выводит 1

Вот такой странный код генерируется
```
public struct B
{
	public int x;
	public void $Init$()
	{
		this.x = 1;
	}
	public B(int xx)
	{
		this.x = xx;
	}
}
public static void $Main()
{
	B b;
	b.$Init$();
	B b2 = new B(10);
	b2.$Init$();
	b = b2;
	Console.WriteLine(b.x);
}
```
Если record заменить на class, то всё ОК.
$Init$() при этом вызывается в прологе конструктора

**Comment by ibond84** [comment]
Да, код писался во времена, когда не было никаких полей записей с инициализаторами и new для записей. $Init$() надо в конструкторы засунуть. И не вызывать снаружи. А переменные инициализировать вызовом конструктора.

**Comment by miks1965** [comment]
Точно. Это же при генерации IL-кода делается?
