### ISSUE TITLE
Неверное сообщение об ошибке

### ISSUE THREAD

**Issue by miks1965** [pascalabcnet/pascalabcnet#125]
'''
{$reference 'System1.dll'}

begin
end.
'''
Пишет: Путь к сборке имеет недопустимые символы

**Comment by ibond84** [comment]
У меня пишет: сборка System1.dll не найдена.

**Comment by miks1965** [comment]
Да. Странно. Теперь у меня тоже пишет. Закрываю.

**Comment by Petrprogs** [comment]
> Да. Странно. Теперь у меня тоже пишет. Закрываю.

Здравствуйте, я столкнулся с тем же самым, что вы сделали чтобы решить проблему?

**Comment by SunSerega** [comment]
На сколько я понимаю - ничего, потому что оно само исправилось.
И вряд ли у вас тот же самый случай - считая дату и специфичность случая из заголовка.

Лучше ищите минимальный код и оформляйте новую issue.
