### ISSUE TITLE
Реализовать Reset для yield последовательностей

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#1255]
```
function f1: sequence of integer;
begin
  yield sequence ArrGen(10, i -> i+1);
end;

begin
  var enm := f1.GetEnumerator;
  
  loop 5 do enm.MoveNext;
  enm.Reset;
  
  while enm.MoveNext do
    writeln(enm.Current);//начинает с 6, проигнорировав Reset
end.
```

Сейчас тело `Reset` просто пустое.
Если вы откажетесь реализовывать - засуньте в тело `Reset` вызов исключения, объясняющего что не так.

**Comment by miks1965** [comment]
А что там в вашем любимом C#?

**Comment by SunSerega** [comment]
С чего вдруг любимом?)) Я в нём только несколько раз програмил, всё на паскале делаю))

Но, далеко копаться не надо - Select реализовано через C#-овские `yield`-ы:
```
begin
  var enm := ArrGen(10, i -> i+1).Select(i->i).GetEnumerator;
  
  loop 5 do enm.MoveNext;
  enm.Reset;//Ошибка времени выполнения: Метод или операция не реализована.
  
  while enm.MoveNext do
    writeln(enm.Current);//начинает с 6, проигнорировав Reset
end.
```
Повторюсь:
>Если вы откажетесь реализовывать - засуньте в тело `Reset` вызов исключения, объясняющего что не так.
