### ISSUE TITLE
Сворачивание первой подпрограммы, описанной через := при отсутствии program сворачивает весь код программы

### ISSUE THREAD

**Issue by MrFresnel** [pascalabcnet/pascalabcnet#1264]
```
program Name;

function F() := 0; // <-- Если нажать на сворачивание для F, то весь код свернется, однако, только если убрать program.

begin
end.
```
В Visual Studio сворачивание expression-body методов (в PascalABC.Net это методы/подпрограммы, описываемые через :=) запрещено:

![image](https://user-images.githubusercontent.com/42812113/46077350-364d6900-c199-11e8-9720-2ae729ae19a1.png)

, поэтому предлагаю запретить сворачивание/разворачивание методов/подпрограмм, описанных через :=.

**Comment by ibond84** [comment]
Это нормально поведение. Фолдинг у нас неразрывный. И начинается на первом элементе программы. В C# пространства имен только фолдятся. Поэтому его пример здесь не очень уместен.
