### ISSUE TITLE
finally реализовано как ужасный костыль

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#1267]
```
begin
  try
    //тело try
  finally
    //тело finally
  end;
end.
```
Разворачивается в:
```
begin
  var flag := false;
  try
    //тело try
    
    flag := true;
    raise new Exception;
  except
    on e: Exception do
    begin
      //тело finally
      
      if not flag then raise e;
    end;
  end;
end.
```
Я приводил в порядок тесты скорости для `BlockFileOfT`, и ужаснулся, если убрать 2 `try-finally` из кода - блочное сохранение в 1.5-2 раза быстрее. Но если добавить назад (только в блочное сохранение, в обычном они не нужны) - блочное сохранение становится в 3-5 раз медленнее (относительно обычного).

Это всё потому - что вызов исключения работает очень сложно, их всюду рекомендуется не использовать в обычных ситуациях. На то они и исключения, чтоб срабатывать в исключительных случаях, как сообщение об ошибке, или срочный выход из программы.

Кроме того, реализация `foreach` использует IL-операторы отвечающие за `try-finally`, так что вы не можете сказать что это сложно.

**Comment by ibond84** [comment]
Ужас какой-то. Тот, кто это ваял, не знал, что в IL есть finally
