### ISSUE TITLE
Build fails on Fedora 23 & Mono 4.2.2

### ISSUE THREAD

**Issue by RomanBelkov** [pascalabcnet/pascalabcnet#127]
There is an error that I get when running build script on my machine:

![mono-pascal-fail](https://cloud.githubusercontent.com/assets/5811999/14139259/98fa9948-f67a-11e5-8883-f44efc9ae551.jpg)

I tried looking into the matter but was unable to find out what is causing the trouble.

**Comment by ibond84** [comment]
fixed
