### ISSUE TITLE
Позволить инициализировать автосвойства при объявлении

### ISSUE THREAD

**Issue by MrFresnel** [pascalabcnet/pascalabcnet#1271]
Позволить инициализировать автосвойства при объявлении с использованием синтаксиса:
```
 type
  TClass = class
    auto property X: byte read := 1;
    auto property Y: byte write := 1;
    auto property Z: byte read write := 1;
  end;

begin
end.
```
Разумеется, после того как будут готовы сами автосвойства. В C#, например, это разрешено:
```
public int MyProperty { get; set; } = 2;
```
. Это позволит сделать код конструкторов чище, так как инициализация свойств будет вынесена из них.

**Comment by ibond84** [comment]
Зачем нужны эти автосвойства? Можно таким макаром и обычными полями обойтись.

**Comment by SunSerega** [comment]
Об этом уже говорили и много, почитайте на форуме.

**Comment by miks1965** [comment]
А разве мы уже согласились на автосвойства?

**Comment by miks1965** [comment]
Давайте-ка я пока закрою это Issue, потому что непонятно, будут ли у нас автосвойства

**Comment by MrFresnel** [comment]
@miks1965, переоткройте, пожалуйста, Issue, ведь автосвойства уже есть.
