### ISSUE TITLE
Невозможно вывести типы-параметры generic-подпрограммы Create при явном указании типа кортежа

### ISSUE THREAD

**Issue by MrFresnel** [pascalabcnet/pascalabcnet#1272]
```
type
  TClass = class
  end;

var
  //x1 := (nil, nil);
  //x2 := (default(TClass), nil);
  //x3 := (default(TClass), default(TClass));
  
  //y1: (TClass, TClass) := (nil, nil); // Неправильно
  //y2: (TClass, TClass) := (default(TClass), nil); // Неправильно
  y3: (TClass, TClass) := (default(TClass), default(TClass));

begin
end.
```
В первых трёх случаях поведение правильное. В четвёртом и пятом - нет, так как тип кортежа явно указан.

**Comment by miks1965** [comment]
Проблема в том, что вначале определяется тип выражения (nil, nil). А он непонятно какой

**Comment by MrFresnel** [comment]
Это нельзя исправить?

**Comment by SunSerega** [comment]
Может ввести особый тип "nil", чтоб тут было `System.Tuple<TClass,nil>`, чтоб дальше можно было его посчитать, но после этого поставить проверку, чтоб в конечных кодах, которые заливает в `Reflection.Emit` этого типа небыло?

**Comment by MrFresnel** [comment]
@miks1965, если:

> вначале определяется тип выражения (nil, nil)

, то почему здесь нет ошибки:
```
type
  TClass = class
  end;

var
  x1: TClass := nil;

begin
end.
```
компиляции?

**Comment by SunSerega** [comment]
>почему здесь нет ошибки

Потому что nil не во что не обёрнут. В случае кортежа - надо ещё вычислить тип кортежа.

>Можно поподробней

Даже не знаю, как тут подробнее... Ну, я говорил про то, чтоб ввести внутренний, несуществующий тип, чтоб обрабатывать `nil`. А в конце компиляции, проверять чтоб он нигде не остался.

**Comment by MrFresnel** [comment]
Спасибо за пояснения.

**Comment by miks1965** [comment]
Да, именно так. для nil в нескольких местах это вмонтировано в компилятор. Потому что nil - особое значение. А вот кортеж - составной тип - он должен быть вначале создан и все входящие в него типы определены.
