### ISSUE TITLE
Второй операнд слипается с последним множественным +/- при форматировании

### ISSUE THREAD

**Issue by MrFresnel** [pascalabcnet/pascalabcnet#1276]
```
procedure P(x: byte) := exit;

begin
  P(   2   +   +   2   );
end.
```
После форматирования:
```
procedure P(x: byte) := exit;

begin
  P(2 + +2   );
end.
```
Следует заметить, что это не зависит от того где расположено выражение с множественными +/-.

**Comment by SunSerega** [comment]
Первый плюс - это бинарный оператор+, а второй - унарный. Всё правильно.
И если их больше сделать - тоже:
```
procedure P(x: byte) := exit;

begin
  P(2 + +++2   );
end.
```
Тут все кроме первого - это унарные операторы.
