### ISSUE TITLE
Анализатор кода неправильно авто-определяет тип в инициализаторе полей типа

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#1282]
```
type
  t1=class
    l := new List<byte>;//для l показывает тип byte
  end;

begin end.
```
Вроде это уже работало раньше...

**Comment by ibond84** [comment]
Да и сейчас работает. Поменяйте что-нибудь в программе и интеллисенс обновится

**Comment by SunSerega** [comment]
Не обновляется. И я всегда пробую обновить всячески, перед тем как заливать.
Версия у меня вчерашняя, она же последняя доступная.

**Comment by SunSerega** [comment]
Да, это совсем недавно сломалось, у меня таких списков было полно в программе и они точно нормально работали. А теперь все сломаны.

**Comment by MrFresnel** [comment]
@SunSerega, лучше сразу выкладывать скриншоты, чтобы не возникало лишних вопросов и недоразумений.

**Comment by SunSerega** [comment]
Перезагрузка компьютера пока что починила, но всё же напрягает что эта ошибка появилась как минимум в 3 разных программах и при отдельных запусках IDE.
