### ISSUE TITLE
Undefined FileName при компиляции кода с попыткой получения результата выполнения метода через ?.

### ISSUE THREAD

**Issue by MrFresnel** [pascalabcnet/pascalabcnet#1283]
```
type
  TClass = class
    function F() := 0;
  end;

begin
  var x := (new TClass())?.F; // Обязательно без скобок.
end.
```
> Undefined FileName(0) : Операции над размерными типами и nil недопустимы

**Comment by SunSerega** [comment]
Нет, тут будет вызов. Для получения ссылки - надо чтоб или у `F` были параметры, или явно указать тип `x`.

**Comment by MrFresnel** [comment]
> Тут, скорее всего, дело как раз в том - что ?. разворачивается в ...=nil?nil:0;, и получается что слева от : будет nil, а справа integer, вот вам и пишет ошибку про это.

integer == System.Int32, который является структурой. Результат ?. - Nullable<T>, который является ссылочным типом, причём, где T - структура. То есть, никаких причин нет для введения данного запрета. На C# аналогичный код успешно компилируется:
```
using System;

namespace Test
{
    class Program
    {
        public int P() => 0;

        public static void Main(string[] args)
        {
            int? x = new Program()?.P();
            Console.ReadKey(true);
        }
    }
}
```
