### ISSUE TITLE
IDE падает при попытке форматирования кода с ?.

### ISSUE THREAD

**Issue by MrFresnel** [pascalabcnet/pascalabcnet#1286]
Пример кода, вызывающего падение IDE при попытке форматирования:
```
begin
  var x := 0;
  var y := x?.Sqr();
end.
```

![image](https://user-images.githubusercontent.com/42812113/46240485-f234b100-c3b0-11e8-9723-33737083b10e.png)

**Comment by SunSerega** [comment]
А это нельзя считать дублем #1284? Ведь анализатор кода и форматирование это одинаковая часть кода, разве нет?

**Comment by MrFresnel** [comment]
Я бы все-же разделил это на две Issue - в одном показывается, что ?. ломает Intellisence, в данной - показываются последствия форматирования. Я согласен, что эти Issue очень близки по своему значению, но все-же. Лично я бы оставил их разделёнными.

**Comment by SunSerega** [comment]
Хах и в итоге эту issue закрыли раньше #1284)))
