### ISSUE TITLE
Единая форма методов расширения в intellisense 

### ISSUE THREAD

**Issue by miks1965** [pascalabcnet/pascalabcnet#129]
Методы интеллисенс, пришедшие из .NET и определенные в Паскале, подсказываются по-разному:

```
<расширение> function IEnumerable<>.Distinct<>(): sequence of TSource;

<расширение> function Cycle<T>(Self: sequence of T): sequence of T;
```

Мне нравится второе и не нравится первое. Предлагаю всё сделать в стиле второго.

**Comment by ibond84** [comment]
Довольно спорно. Первое более читабельно, ибо сразу видно что расширяем. А паскалевские методы расширения выводятся так, потому что нельзя написать 
function <array of T>.Sum()

**Comment by miks1965** [comment]
Предлагаю всё-таки вернуться к этому вопросу - и сделать для Distinct вот такую подсказку:

```
<расширение> function Distinct<T,TSource>(Self: sequence of T): sequence of TSource;
```
Понятно, что расширяется первый параметр

**Comment by ibond84** [comment]
Нет, self: sequence of T это плохо и мешает интеллисенсу подсвечивать параметры после ввода запятой. В студии тоже  используется нотация ```IEnumerable<>```. Так что привел в соответствие форму паскалевских методов расширения. Для массивов и прочих типов с пробелом в имени  выводится так
(расширение array of T) Shuffle();
