### ISSUE TITLE
Анализатор кода сломан для лямбды в заголовке foreach

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#1296]
```
begin
  var s: array of string;
  foreach var w in s.Select(l -> l.ToWords) do//тут не показывает подсказки не для чего из лямбды
end.
```
[видео в архиве.zip](https://github.com/pascalabcnet/pascalabcnet/files/2431577/bandicam.2018-09-30.16-15-37-524.zip)

**Comment by miks1965** [comment]
А по-русски можно? А то не соотносятся слова ни в заголовке ни в русском комментарии в коде. В чем проблема?

**Comment by MrFresnel** [comment]
В том, что для l/ToWords Intellisence ничего не показывает.

**Comment by ibond84** [comment]
Во-первых грамматически неправильно. Во-вторых, "сломал" указывает на то, что оно раньше работало?

**Comment by SunSerega** [comment]
> сломал

А, так вот оно в чём дело... СлО'маН
