### ISSUE TITLE
Неправильные ошибки при описании конструкторов без предописания

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#1297]
```
type
  t1=class end;
  
constructor t1.Create;//Ошибка: Повторное объявление 
begin
  
end;

constructor t1.Create(b: byte);//Ошибка: Нет метода Create с такими параметрами в классе t1
begin
  
end;

begin end.
```
Правильно так:
`Нет описания конструктора без параметров в классе t1`
И
`Нет конструктора с такими параметрами в классе t1`

**Comment by miks1965** [comment]
Всё правильно. В классе всегда есть конструктор по умолчанию. И второе сообщение об ошибке абсолютно правильное

**Comment by SunSerega** [comment]
>В классе всегда есть конструктор по умолчанию

Знаю, но его нет в коде. Поэтому это не второе объявление.

>второе сообщение об ошибке абсолютно правильное

С какого момента метод и конструктор это одно и тоже? Они же везде позиционируются как совершенно разные вещи.

**Comment by SunSerega** [comment]
>Конструктор - это разновидность метода

Ладно, я где то видел что то что противоречит, но допустим, может потом найду. Хотя уточнение не помешало бы.

>код, который в класс генерируется

Да, я понимаю, но это внутренние вещи компилятора. Внутренности компилятора никогда не должны быть видны программисту и он не должен думать о них, когда составляет свою программу. А вот чтоб понять что значит эта ошибка - нужно всё же об этом задуматься.

Ещё раз, конструктор который создаёт поумолчанию - не объявлен в программе которую пишет программист, поэтому ошибка неправильная.

**Comment by miks1965** [comment]
Правильная. Это в документации есть.
