### ISSUE TITLE
Добавить модификатор readonly для полей и записей

### ISSUE THREAD

**Issue by MrFresnel** [pascalabcnet/pascalabcnet#1298]
Для полей:
```
type
  TClass = class
    fX: byte; readonly;
  end;

begin
end.
```
Для записей:
```
type
  TRecord = readonly record
  end;

begin
end.
```
[readonly (Справочник по C#)](https://docs.microsoft.com/ru-ru/dotnet/csharp/language-reference/keywords/readonly#readonly-struct-example)

**Comment by miks1965** [comment]
Забудьте C#

**Comment by MrFresnel** [comment]
Аргументов по закрытию Issue не было приведено.

**Comment by SunSerega** [comment]
Так же как и причин добавить.

Их уже приведу я:
`Microsoft.Win32.Registry.ClassesRoot` - поле которое можно только читать. И это ещё много где есть.

**Comment by MrFresnel** [comment]
> Так же как и причин добавить.

Согласен. Не успел написать.

**Comment by SunSerega** [comment]
> Не успел

Не считается. У вас было всё время мира, перед тем как нажать на кнопку создания issue.

**Comment by MrFresnel** [comment]
> Не считается.

Я и не спорю...
