### ISSUE TITLE
Размерные типы могут выступать в качестве ограничения

### ISSUE THREAD

**Issue by MrFresnel** [pascalabcnet/pascalabcnet#1303]
Следующий код успешно проходит компиляцию, хотя не должен, так как ограничение в виде размерного типа фактически означает что только он сможет быть подставлен вместо шаблонного параметра, точнее generic-подпрограмма вырождается в самую обычную подпрограмму.
```
procedure P<T>();
where T: byte;
begin
end;

begin
end.
```
В C# на аналогичный код:
```
namespace Test
{
	class Program
	{
		public static void Method<T>() where T: byte
		{
			
		}
		
		public static void Main(string[] args)
		{
		}
	}
}
```
появится сообщение об ошибке компиляции:

> "byte" не является допустимым ограничением. Тип, используемый как ограничение, должен быть интерфейсом, нестерильным классом или параметром типа. (CS0701) - C:\Users\Admin\Documents\SharpDevelop Projects\Test1\Test1\Program.cs:13,43

**Comment by ibond84** [comment]
Какой-то бред. Не вижу смысла запрещать, если в IL работает

**Comment by MrFresnel** [comment]
Я пояснил почему это лучше запретить. Это не имеет смысла.

**Comment by ibond84** [comment]
Да все эти ограничители по сути и так бессмысленны. Интерфейс можно запхнуть в тип параметра и избавиться от генериков. Почему тогда надо обделять только размерные типы?

**Comment by MrFresnel** [comment]
> Почему тогда надо обделять только размерные типы?
Суть ограничения в том, чтобы указать какие типы могут быть подставлены на место шаблонного параметра. В отношении размерных типов данное ограничение обрубает возможность использования любого другого типа, так как сможет использоваться лишь единственный конкретный тип.

**Comment by miks1965** [comment]
Ну, то в C# так. У нас может. Если я хочу вызывать p только с параметром byte. Имею право.
Впоследствии может быть расширю, а пока так. Не вижу особых противоречий.

**Comment by MrFresnel** [comment]
> Если я хочу вызывать p только с параметром byte. Имею право.

Не используйте шаблонные параметры и все.

**Comment by miks1965** [comment]
Мы закрыли как раз потому, что причиной не может быть то, что вы смысла в этом не видите.

**Comment by MrFresnel** [comment]
Не один один человек, а также и C#. Но если Вы будете реализовывать потом, тогда ладно.

**Comment by MrFresnel** [comment]
> Мы закрыли как раз потому, что причиной не может быть то, что один человек смысла в этом не видит.

Разумеется, закрывать по этой причине Issue вполне обосновано. Но, в данном случае, хочу заметить, что кроме личного мнения приведены и аргументы в защиту моей точки зрения, например, код на C#. Если Вы планируйте это исправить, не сейчас, а потом, то, прошу переоткрыть Issue, хотя бы по той причине, что открытая Issue будет о себе напоминать и Вы о ней не забудете.

**Comment by miks1965** [comment]
Вам два разработчика ответили. Мы не планируем это исправлять.
