### ISSUE TITLE
Анонимные типы делегатов не могут содержать в типах входных параметров T?

### ISSUE THREAD

**Issue by MrFresnel** [pascalabcnet/pascalabcnet#1316]
```
{function F(): byte? -> byte; // Встречено '->', а ожидалось ';'
begin
end;}

{var
  x: byte? -> byte;} // Встречено '->', а ожидалось ';'

begin
end.
```
Если разрешено описание анонимных типов делегатов, то почему запрещено использовать `T?` в типах входных параметров таких типов делегатов?

**Comment by miks1965** [comment]
Это не делегаты, а процедурные переменные. Их короткие типы могут содержать лишь простые имена, точки и обобщения. Это ограничение. Не нравится - пользуйтесь Func
