### ISSUE TITLE
При явном указании типа ошибка:  Встречено '.', а ожидалось ';'

### ISSUE THREAD

**Issue by vdjenjer** [pascalabcnet/pascalabcnet#1318]
```
begin
  var a: integer := '123'.Length
end.
```
Если не указывать тип переменной `а`, всё работает. Если ```'123'``` заменить на строковую переменную -- тоже работает. То есть вот так всё нормально:
```
begin
  var s := '123';
  var a: integer := s.Length
end.
```
И вот так тоже работает:
```
begin
  var a := '123'.Length
end.
```

**Comment by vdjenjer** [comment]
Кстати, в похожем случае выдаётся другая ошибка.
```
begin
  var s := ReadlnString;
  var n: integer := s[1::2].sum(x -> x.toDigit);
end.
```
Program22.pas(3) : Встречено ':', а ожидалось ')'

Опять же при автовыведении типа переменной всё в порядке.

**Comment by miks1965** [comment]
Пожалуйста следуйте практике - одна ошибка или улучшение - один Issue

**Comment by spectatorBH** [comment]
@MrFresnel Ваши примеры (№ 1, 3, 4) не учтены в данном коммите. Ваш пример №2 со срезами, аналогичный #1319, был закрыт как не имеющий пока(?) решения по техническим причинам (неустранимые конфликты в грамматике). Не знаю, относится ли это также к полям, свойствам и методам. Возможно, имеет смысл создать для них отдельные issue?

**Comment by SunSerega** [comment]
>Возможно, имеет смысл создать для них отдельные issue

Я бы сначала подождал следующего билда. Если там не исправится - тогда уже создавать отдельные issue.

**Comment by miks1965** [comment]
Я создал issue для s[::]

**Comment by miks1965** [comment]
Не понял. '123'.Length - уже работает

**Comment by spectatorBH** [comment]
> Я бы сначала подождал следующего билда. Если там не исправится - тогда уже создавать отдельные issue.

> Не понял. '123'.Length - уже работает

@miks1965 А ситуации, как в примерах № 1, 3 и 4 -- еще нет (сборка 1825 от 07.10.2018). @MrFresnel Делаем отдельные issues?

**Comment by miks1965** [comment]
```
begin
  var s := ReadlnString;
  var n: integer := s[1::2].sum(x -> x.toDigit);
end.
```
Это не будет работать. Там лямбда в правой части, конфликтует в грамматике с другими инициализаторами переменной с явным указанием типа

**Comment by miks1965** [comment]
Примеры 1-4 компилируются

**Comment by vdjenjer** [comment]
> 
> 
> ```
> begin
>   var s := ReadlnString;
>   var n: integer := s[1::2].sum(x -> x.toDigit);
> end.
> ```
> 
> Это не будет работать. Там лямбда в правой части, конфликтует в грамматике с другими инициализаторами переменной с явным указанием типа

Ясно. Только там и без лямбд всё плохо. Вот такая же ошибка:

**Comment by miks1965** [comment]
Попробуйте еще раз. Закачал новую версию. Отпишитесь. У меня всё работает

**Comment by SunSerega** [comment]
Скачал последнюю версию - примеры 1, 3 и 4 всё же не компилируются:
1)
```
type
  T = class // или record
    function F() := self;
  end;

begin
  var x1: T := new T();
  //var x2: T := (new T()).F(); // Встречено '.', а ожидалось ';'
  
  var y1 := new T();
  var y2 := (new T()).F();
end.
```
3)
```
type
  T = class // или record
    fX: T;
  end;

begin
  var x1: T := new T();
  //var x2: T := (new T()).fX; // Встречено '.', а ожидалось ';'
  
  var y1 := new T();
  var y2 := (new T()).fX;
end.
```
4)
```
type
  T = class // или record
    property X: T read nil;
  end;

begin
  var x1: T := new T();
  //var x2: T := (new T()).X; // Встречено '.', а ожидалось ';'
  
  var y1 := new T();
  var y2 := (new T()).X;
end.
```

Я брал из сообщения @MrFresnel-а, а вы откуда?

**Comment by miks1965** [comment]
А, понятно. У Вас там комментарий стоит. Пишите ошибочный код без комментариев. И сделайте новый Issue

**Comment by vdjenjer** [comment]
> 
> 
> Попробуйте еще раз. Закачал новую версию. Отпишитесь. У меня всё работает

Да, с новой версией пошло.

**Comment by miks1965** [comment]
Нет. Мы уже пытались это делать - это закомменчено:
```
/*    | tkRoundOpen const_expr tkRoundClose 
        { 
            if (!parsertools.build_tree_for_formatter) 
            {
                $2.source_context = @$;
                $$ = $2;
            } 
			else $$ = new bracket_expr($2, @$); 
        }*/
```
Там начинаются бешеные конфликты в грамматике. Причем именно если для переменной объявлен тип. Дело в том, что эта часть грамматики пересыщена всевозможными старыми дельфийскими инициализаторами.
