### ISSUE TITLE
Разрешить срезы в инициализаторах с типом

### ISSUE THREAD

**Issue by miks1965** [pascalabcnet/pascalabcnet#1319]
```
begin
  var s := ReadlnString;
  var n: string := s[1::2];
end.
```

**Comment by miks1965** [comment]
Не получается сделать в грамматике. Много конфликтов

**Comment by ibond84** [comment]
А с чем конфликтует?

**Comment by miks1965** [comment]
Практически со всем. Там const_expr - это клоака какая-то. Оно почти повторяет expr, только везде const-аналоги. И всё из-за возможности инициализировать массивы и записи в стиле Delphi

**Comment by ibond84** [comment]
Да, помню. Делфийский мусор мешает.

**Comment by miks1965** [comment]
Я еще попытаюсь

**Comment by ibond84** [comment]
только не в ущерб инициализаторам массивов.

**Comment by miks1965** [comment]
Нет, я не могу такое запрещать единолично.

Я попытаюсь сделать константный аналог a:b:c

**Comment by miks1965** [comment]
Сюда же:
```
var a: real := 1.Sqrt;
begin end.
```

**Comment by miks1965** [comment]
```
begin
  var s := 'gsfdhj';
  var n: string := s[1::2]
end.
```
Это работает
