### ISSUE TITLE
оператору+= можно объявить возвращаемое значение, но получить его нельзя

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#1320]
```
type
  t1=class
    
    b: boolean;
    v: integer;
    
    class function operator+=(var a1:t1; a2:t1): boolean;//компилируется
    begin
      Result := a1.v=a2.v;
      if Result then
        a1.v += a2.v;
    end;
    
  end;

begin
  var a1 := new t1;
  var a2 := new t2;
  //var b1: boolean := a1 += a2;//Ошибка: Встречено '+=', а ожидалось ';'
  //var b2 := a1 += a2;//Ошибка: Встречено '+=', а ожидался оператор
end.
```

**Comment by ibond84** [comment]
Ну в C# можно, в паскале нельзя. Если писать библиотеку, то надо определять оператор как функцию

**Comment by SunSerega** [comment]
А, то есть возможность делать его функцией оставлена только для .dll-ок?
И, это на столько уж принципиально, чтоб он всегда был оператором, а не только в случае со стандартными типами? @miks1965, хотело бы от вас тоже услышать что то по этому поводу.

**Comment by MrFresnel** [comment]
Оператор += в C# нельзя [перегружать](https://docs.microsoft.com/ru-ru/dotnet/csharp/programming-guide/statements-expressions-operators/overloadable-operators).

**Comment by ibond84** [comment]
Да ну попробуй запрети. В системном модуле такое используется

```
function operator+=<T>(a: List<T>; x: T): List<T>; extensionmethod;
begin
  a.Add(x);
  Result := a;
end;
```

**Comment by SunSerega** [comment]
А зачем, кстати, ему возвращаемое значение, если получить его нельзя? И это ведь уже не .dll, это то что только из паскаля можно использовать...

Может всё же разрешить += использовать не только как оператор, но и как выражение?

**Comment by MrFresnel** [comment]
> В системном модуле такое используется

Зачем? Какая польза от возвращаемого значения?

**Comment by MrFresnel** [comment]
Получается, что будет три категории операторов:
1) Функции-операторы, возвращающие значение.
2) Функции-операторы, изменяющие входные параметры и возвращающие значение.
3) Процедуры-операторы, изменяющие входные параметры.

**Comment by MrFresnel** [comment]
> Не операторы, а операции.

Возможно, в контексте PascalABC.Net другая терминология, нежели в [C#](https://docs.microsoft.com/ru-ru/dotnet/csharp/programming-guide/statements-expressions-operators/overloadable-operators).

**Comment by miks1965** [comment]
Это Вы пользуетесь автоматическим переводчиком.

**Comment by MrFresnel** [comment]
Спасибо.
