### ISSUE TITLE
Сделать копирование строки при передаче символа строки по ссылке

### ISSUE THREAD

**Issue by ibond84** [pascalabcnet/pascalabcnet#1328]
Строки должны оставаться интернированными и такими же эффективными как в C# (если они не меняются).

**Comment by SunSerega** [comment]
Вот программа для тестирования:
```
procedure p1(var ch: char) :=
ch := '_';

begin
  var s := '123';
  var s1 := s;
  var s2 := '123';
  p1(s1[2]);
  Assert(s<>s1);
  Assert(s2<>s1);
end.
```

**Comment by SunSerega** [comment]
Как и у массивов. Они особенные.

**Comment by MrFresnel** [comment]
Разве что в контексте PascalABC.Net.

**Comment by ibond84** [comment]
https://github.com/pascalabcnet/pascalabcnet/actions/runs/998044911
