### ISSUE TITLE
Разрешить обращаться индексатору строк по умолчанию к символам строковых литералов

### ISSUE THREAD

**Issue by MrFresnel** [pascalabcnet/pascalabcnet#1329]
```
procedure P(var x: char) := exit;

begin
  P('123'[1]); // Program1.pas(4) : Встречено '[', а ожидался оператор
end.
```
В C# аналогичный код успешно компилируется:
```
using System;
 
namespace Test
{	
	class C
	{	
		public static void Main(string[] args)
		{
	        	Console.WriteLine("123"[0]);
	        	Console.ReadLine();
		}
	}
}
```

**Comment by AlexRnD61** [comment]
Опять дурацкий аргумент "А в С# так можно" !
Ну не будет из Паскаля С#, не будет никогда. Потому что C# и так уже есть.

**Comment by MrFresnel** [comment]
Высказывайтесь, пожалуйста, вежливо.

**Comment by MrFresnel** [comment]
Убедительная просьба - оставьте всю свою некультурную терминологию за рамками GitHub, в противном случае мне придется обратится к администрации.

**Comment by MrFresnel** [comment]
> дурацкий

Воздержитесь, пожалуйста, от некультурной лексики.

**Comment by MrFresnel** [comment]
> Слово дурацкий - некультурное? И давно это у Вас такое понятие о культуре? Это литературное слово, разрешенное к употреблению даже в парламентах.

Никакого отношения к Issue данный комментарий не имеет.
