### ISSUE TITLE
Должно выводить правильное сообщение об ошибке

### ISSUE THREAD

**Issue by miks1965** [pascalabcnet/pascalabcnet#133]
```
function operator+(Self: procedure; p: procedure): procedure; extensionmethod;
begin
  Result := Self;
  Result += p;
end;
```
Выдается ошибка:
Различные имена параметров в описании подпрограммы left и ее предописании Self

**Comment by ibond84** [comment]
Ну, сообщение об ошибке должно быть корректным. А так компилироваться не должно. + это встроенный оператор для делегатов (как синоним Delegate.Combine). Его надо запрещать переопределять во избежание множества проблем.

**Comment by miks1965** [comment]
Согласен. Но что-то у нас не так и с + для делегатов

**Comment by ibond84** [comment]
Просто это методы, не имеющие тела, а вычисляемые в compile_time_executor. Поэтому компилятор думает, что это реализация этого метода.
