### ISSUE TITLE
Добавить ключевое слово extended в отношении расширенных свойств

### ISSUE THREAD

**Issue by MrFresnel** [pascalabcnet/pascalabcnet#1333]
Добавить ключевое слово extended в отношении расширенных свойств для исключения неоднозначности.

**Comment by miks1965** [comment]
Там всё однозначно

**Comment by MrFresnel** [comment]
> Хороший пример, спасибо. Делайте Issue, а мы подумаем, разрешать такое или нет. Здесь конкурируют старые и новые свойства. Возможно, такое нельзя будет сделать. То есть, если это простое имя в Readerе, то это - старые свойства, если составное, - то новые. Пока логика такая, и она более-менее интуитивно понятная. **Если разрешить это, старые и новые свойства сольются.** Ну например, если X - это вызов внешней функции без параметров. Здесь хорошо ожидаемое поведение, а так программист не будет понимать, что происходит
