### ISSUE TITLE
Неправильное сообщение об ошибке при указании шаблонных параметров для необобщенного интерфейса

### ISSUE THREAD

**Issue by MrFresnel** [pascalabcnet/pascalabcnet#1335]
Следующий код при компиляции:
```
type
  I1 = interface
  end;
  
  T = class(I1<byte>)
  end;

begin
end.
```
выдаст:
> Program1.pas(5) : I1 не является именем шаблонного класса

, что неправильно. Ожидалось:
> Program1.pas(5) : I1 не является именем шаблонного интерфейса

**Comment by ibond84** [comment]
Ну одно сообщение на всех. Зачем плодить еще одно?

```
type
  I1 = array of integer;
  
  T = class(I1<byte>)
  end;

begin
end.
```
