### ISSUE TITLE
Re: Не может выбрать из 2 подпрограмм

### ISSUE THREAD

**Issue by MrFresnel** [pascalabcnet/pascalabcnet#1338]
```
procedure p1() := exit;

procedure p1(p: byte := 0) := exit;

begin
  p1(); // Program1.pas(6) : Несколько подпрограмм могут быть вызваны
end.
```
Первая [Issue](https://github.com/pascalabcnet/pascalabcnet/issues/852).

Ожидался вызов первой подпрограммы. В C# аналогичный код:
```
using System;

class Program
{
    static void M() => Console.WriteLine(1);

    static void M(byte x = 0) => Console.WriteLine(2);

    static void Main(string[] args)
    {
        M();
        Console.ReadLine();
    }
}

```
вызовет первый метод - пойдет по пути наименьшего сопротивления.

**Comment by miks1965** [comment]
Всё верно. У нас не C#. С нашей точки зрения ваш код - ошибка проектирования, которая будет приводить к путанице, особенно когда обе функции разведены в пространстве.

**Comment by MrFresnel** [comment]
Хорошо. Понял.
