### ISSUE TITLE
Intellisence ничего не отображает при наведении курсора на Tuple

### ISSUE THREAD

**Issue by MrFresnel** [pascalabcnet/pascalabcnet#1343]
```
uses System;

begin
  new Tuple<byte, byte>(1, 1);
end.
```

**Comment by miks1965** [comment]
Над кстати - как я уже и говорил - разделить Issue на те, которые связаны с ошибками и неточностями компилятора от остальных. Потому что захламляют и забивают главное.

Я думаю, что надо сделать фиктивный проект на Github - IDE и Intellisense в PascalABC.NET и кидать этот мусор туда

**Comment by SunSerega** [comment]
И как тогда референсить коммиты к issue? Разберитесь лучше всё же с лейблами,
`-label:Intellisense -label:IDE `
И будет вам счастье...

**Comment by miks1965** [comment]
Не надо давать советы. Я не даю вам советы - заметьте.

Скорее всего - если @ibond сочтет это нужным - мы перенесём Issue, не касающиеся компилятора, в новый проект.

**Comment by SunSerega** [comment]
Это не совет а просьба. Референсы коммитов помогают понимать устройство паскаля, хоть на сколько то, и составлять тесты для следующей issue. Вы конечно всё ещё сможете вставлять ссылку на нужную issue в название коммита, но это будет криво. Или вы говорите о том, чтоб перенести модули анализатора кода и IDE в отдельный проект?

**Comment by MrFresnel** [comment]
> мусор

Это Вы так назвали данную Issue?

**Comment by miks1965** [comment]
Для исправления важных ошибок, связанных с языком и компилятором, эти являются мусором и мешают анализу собственно ошибок компилятора. Именно поэтому я и говорю про то чтобы их вынести в отдельное место. Там они мусором являться не будут, поскольку проект будет создан ровно для этого.

Референсы коммитов. Я думаю, что для Intellisense они не очень важны.

**Comment by MrFresnel** [comment]
Спасибо... Очень приятно, несмотря на ситуацию с Issue'ами.
