### ISSUE TITLE
& может быть использован при инстанцировании

### ISSUE THREAD

**Issue by MrFresnel** [pascalabcnet/pascalabcnet#1344]
```
type
  TName<T> = class
  end;

begin
  new TName<&byte>();
end.
```
Аналогичный код на C#:
```
namespace Test
{	
	class Name<T>
	{
		
	}
	
	class Program
	{	
		public static void Main(string[] args)
		{
			var x = new Name<@byte>();
		}
	}
}
```
выдаст ошибку компиляции:
> Не удалось найти имя типа или пространства имен "byte" (пропущена директива using или ссылка на сборку?) (CS0246) - C:\Users\Admin\Documents\SharpDevelop Projects\Test1\Test1\Program.cs:22,21

**Comment by miks1965** [comment]
У нас не C#.

У нас & снимает "ключёвость" если есть, что снимать, в противном случае ничего не делает.

**Comment by MrFresnel** [comment]
Спасибо, не знал этот нюанс.

**Comment by AlexRnD61** [comment]
> У нас не C#.
Печально, что об этом постоянно приходится напоминать...
