### ISSUE TITLE
Оператор-процедура может быть описан в интерфейсе

### ISSUE THREAD

**Issue by MrFresnel** [pascalabcnet/pascalabcnet#1345]
```
type
  I1 = interface
    procedure operator+=(x, y: I1);
  end;

begin
end.
```
При компиляции аналогичного кода на C#:
```
namespace Test
{	
	interface I1
	{
		I1 operator+(I1 x, I2 y);
	}
	
	class Program
	{	
		public static void Main(string[] args)
		{
		}
	}
}
```
получаем:
> Интерфейсы не могут содержать операторы (CS0567) - C:\Users\Admin\Documents\SharpDevelop Projects\Test1\Test1\Program.cs:15,6

**Comment by miks1965** [comment]
Да, интерфейсы не должны содержать операторы
