### ISSUE TITLE
Неизвестное имя "exit" в расширенных свойствах

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#1348]
```
type
  i1= interface
    
    property p1: byte write;
    
  end;
  t1=class(i1)
    
    public property p1: byte write exit;//Ошибка: Неизвестное имя 'exit'
    
  end;

begin end.
```
Обычно, exit удобен для указания что тело процедуры пусто:
```
procedure p1 := exit;
```
Так очень коротко получается. И - exit работает во многом как ключевое слово, а значит это не простое имя и спутать с классическими свойствами его нельзя.

**Comment by miks1965** [comment]
Это проблема совмещения обычных и расширенных свойств. Если в Readerе или Writerе - простое имя, то это расценивается как обычное свойство, и имя должно быть именем поля или процедуры в текущем классе. Текст ошибки неудачный - согласен.

**Comment by SunSerega** [comment]
Ну вот исправьте хотя бы ошибку. Но как я и сказал:

>И - exit работает во многом как ключевое слово, а значит это не простое имя и спутать с классическими свойствами его нельзя

Вы говорили в остальных случаях что это будет путать - так в этом запутаться нельзя, потому что `exit` это не простое имя.

**Comment by miks1965** [comment]
exit - обычное имя.
```
var exit: integer;
```

**Comment by MrFresnel** [comment]
Функции? Не процедуры?

Подтверждение того, что это подпрограмма:
```
procedure P() := exit();

begin
end.
```

**Comment by SunSerega** [comment]
> exit()

Стоп что?! По моему это ошибка...

**Comment by miks1965** [comment]
Оператор вызова процедуры - это оператор. 

В списке ключевых слов его естественно нет.

**Comment by SunSerega** [comment]
Да, но:

>exit являются **не процедурами**, а именно операторами

**Comment by miks1965** [comment]
А, нет, - это враньё. Процедурами. Волшебными. Сейчас исправлю.

Это писалось еще для PascalABC, с тех пор не переделали.

**Comment by SunSerega** [comment]
Ну, меня сильно удивили скобочки всё же)) Это большая разница, никогда не думал что так можно...

Но, как насчёт улучшить ошибку?

**Comment by miks1965** [comment]
А как её улучшить?

**Comment by MrFresnel** [comment]
> А как её улучшить?

Например, так:

> Процедура exit не может быть использована в геттере расширенного свойства, если кроме неё в геттере ничего нет.

**Comment by SunSerega** [comment]
Ну, `exit` не неизвестное имя. Что то про то что "в качестве ацессора можно использовать только методы этого класса".

**Comment by miks1965** [comment]
Да, согласен. Поля ещё. И это при условии, что это - простое имя.

**Comment by MrFresnel** [comment]
Проверил. Сообщение об ошибке адекватное.
