### ISSUE TITLE
Позволяет реализовывать свойство интерфейса методом

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#1350]
```
type
  i1= interface
    
    property p1: byte read;
    
  end;
  t1=class(i1)
    
    public function get_p1: byte := 0;
    
  end;

begin end.
```
Надо добавить `$` в название этой внутренней функции (как и в название соответствующей функции `set`), чтоб она не путалась с функциями, которые сделает пользователь.

К примеру, в данном случае - получаем неправильный вывод для `a1.p1`:
```
type
  i1= interface
    
    property p1: byte read;
    
  end;
  t1=class(i1)
    
    public function get_p1: byte := 1;
    
    public property p1: byte read get_p1+1;
    
  end;

begin
  var a1: i1 := new t1;
  var a2: t1 := new t1;
  writeln(a1.p1);//1
  writeln(a2.p1);//2
end.
```

**Comment by miks1965** [comment]
А что там в C#? Там же тоже таким методом можно определить свойство

**Comment by ibond84** [comment]
Это не ошибка. Так надо.

**Comment by ibond84** [comment]
В IL геттеры и сеттеры имеют префиксы get_ и set_. Так что все правильно.

**Comment by SunSerega** [comment]
И то, что позволяет описать 2 реализации сразу это правильно? И то что при этом ломается виртуальность этого свойства?

**Comment by ibond84** [comment]
Правильно. Неправильное использование спецметодов это проблемы программиста, а не компилятора.

**Comment by ibond84** [comment]
К тому же эти спецметоды не надо определять явно (но можно)

**Comment by SunSerega** [comment]
Если мыслить в этом направлении - тут тоже не должно быть ошибки:
```
type
  t1 = interface
    
    procedure p1;
    
  end;
  t2=class(t1)
    
    procedure p1 := exit;
    
    procedure p1 := exit;
    
  end;

begin end.
```
Компилятор должен говорить программисту, когда тот делает что то однозначно неправильное. По крайней мере в таких, простых для отслеживания случаях.

**Comment by SunSerega** [comment]
Или вот лучше пример - указатели на ссылочные типы вы ведь запретили. Как раз по той же причине, это вызывает неопределённое поведение. Произвольное ломание виртуальной цепочки - это тоже неопределённое поведение.

**Comment by MrFresnel** [comment]
> А что там в C#?

Запрещено так делать.
