### ISSUE TITLE
Сеттеры или геттеры свойств могут иметь уровень доступности, превышающий уровень доступности самого свойства

### ISSUE THREAD

**Issue by MrFresnel** [pascalabcnet/pascalabcnet#1352]
```
type
  T = class
  public
    function GetX() := 0;
  
  private
    property X: integer read GetX;
  end;

begin
end.
```
Явное нарушение инкапсуляции. Свойства призваны ей обеспечить, ограничивая доступ к внутренностям класса. В приведённом выше коде данный принцип ООП легко нарушается.

Аналогичный код на C#:
```
namespace Test
{	
	class T0
	{
		private int X { public get; set; }
	}
	
	class Program
	{	
		public static void Main(string[] args)
		{
		}
	}
}
```
при компиляции выдаёт:
> Модификатор доступности функции доступа "Test.T0.X.get" должен содержать более жесткие ограничения, чем свойство или индексатор "Test.T0.X" (CS0273) - C:\Users\Admin\Documents\SharpDevelop Projects\Test1\Test1\Program.cs:15,26

Однако, если сделать свойство частным (private) в C#, но у геттера или сеттера не указать модификатор доступа явно, то компиляция пройдет успешно.

**Comment by miks1965** [comment]
Не забывайте, что это не C# и геттер в частности может выступать как обычная функция. В C# нет именованных геттеров и сеттеров, поэтому вообще сравнение неуместно.

**Comment by MrFresnel** [comment]
Понял, спасибо.
