### ISSUE TITLE
Позволить создавать предописания для записей

### ISSUE THREAD

**Issue by MrFresnel** [pascalabcnet/pascalabcnet#1356]
```
type
  T = record; // Встречено ';', а ожидался идентификатор
  
  T = record
  end;

begin
end.
```

**Comment by SunSerega** [comment]
А что в этом неправильного?

**Comment by MrFresnel** [comment]
Не компилируется.

**Comment by SunSerega** [comment]
А, "позволить", а не "позволяет")) Неправильно прочитал...

**Comment by SunSerega** [comment]
>Такого ж нигде нет

В C# ведь в любом порядке типы можно писать, то есть, по сути есть.

>Там же размер должен быть известен - это ж вам не классы

Для чего? Это ведь можно только с помощью атрибутов закрепить, а так - размер будет выбран исходя из параметров системы и процессора.

Во всяком случае, это дело не компилятора паскаля, в IL он не передаёт информацию о размере. А IL-компилятору нет дела до порядка расположения записей, они всё равно будут все в одной куче.

**Comment by miks1965** [comment]
Ещё раз напомню, что мы сравниваем в первую очередь не с вражеским языком, а с Delphi, а потом уже со всеми остальными.

Предописания типов делались в первую очередь для ликвидации проблемы рекурсивной зависимости между типами. С записями построить подобный пример невозможно. 

Именно поэтому так опаздывает долгожданный пример кода, который, как известно, лудшее доказательство.

Закрываю.

**Comment by MrFresnel** [comment]
> вражеским языком

Не согласен в отношении данного термина...

**Comment by SunSerega** [comment]
@miks1965 пример есть.

@MrFresnel на почту не присылает сообщение, когда сообщение было изменено, поэтому никто узнать не может что вы что то добавили.

**Comment by MrFresnel** [comment]
Это, в частности, мешает сделать перечислитель записью:
```
uses System;
uses System.Collections;

type
  TEnumerator = class;
  
  TCollection = class(IEnumerable)
  internal
    items: array of integer;
  
  public
    constructor Create(items: array of integer);
    
    function GetEnumerator(): TEnumerator;
    
    function IEnumerable.GetEnumerator() := IEnumerator(GetEnumerator());
  end;
  
  TEnumerator = class(IEnumerator)
  private
    target: TCollection;
    position: integer := -1;
    
    function GetCurrent(): integer;
    
  public
    property Current: integer read GetCurrent;
    
    function IEnumerator.get_Current(): object := GetCurrent();
    
    constructor Create(target: TCollection);
    
    function MoveNext(): boolean;
    
    procedure Reset();
  end;


{$region TCollection}
constructor TCollection.Create(items: array of integer) := self.items := items;

function TCollection.GetEnumerator() := new TEnumerator(self);
{$endregion}

{$region TEnumerator}
function TEnumerator.GetCurrent(): integer;
begin
  try
    Result := target.items[position];
  except
    on IndexOutOfRangeException do
      raise new InvalidOperationException();
  end;
end;
    
constructor TEnumerator.Create(target: TCollection) := self.target := target;

function TEnumerator.MoveNext(): boolean;
begin
  position += 1;
  Result := position < target.items.Length;
end;

procedure TEnumerator.Reset() := position := -1;
{$endregion}

begin
  var x := new TCollection(Arr(1, 2, 3));
  foreach var item in x do
    Writeln(item);
end.
```

**Comment by miks1965** [comment]
Да, спасибо. Отличный пример, не знал.

Не будем делать по следующим причинам.
1. Сложность реализации
2. Чрезвычайная редкость использования
3. Для ниши проекта - образовательная, академическая - это имеет ничтожный интерес
4. В Delphi этого до сих пор нет
5. В Delphi эта фича полезна для хелперов - у нас в языке хелперов нет

**Comment by MrFresnel** [comment]
> Для ниши проекта - образовательная, академическая - это имеет ничтожный интерес

typeclass'ы разве имеют для ниши PascalABC.Net интерес чуть более чем ничтожный? Не думаю, что это является аргументом.

**Comment by miks1965** [comment]
typeclass'ы - это академический интерес. Вынужден напомнить, что академические разработки могут быть сложнее фич языка.

> Что мешает реализовать это при наличии времени и желания?
Мы подчеркнули уже, закрыв этот Issue, что нет как раз и того и другого

> Далеко не везде PascalABC.Net равняется на Delphi. 
Несомненно. Мы рассматриваем это как ненужную и малоиспользуемую фичу

**Comment by MrFresnel** [comment]
Не назвал бы её ненужной...
