### ISSUE TITLE
Неправильная ошибка при попытке создания объекта базового типа через new

### ISSUE THREAD

**Issue by MrFresnel** [pascalabcnet/pascalabcnet#1359]
```
begin
  var x := new byte(); // Program2.pas(2) : Ни один конструктор не найден
end.
```
Если это запрещено делать, то лучше выводить следующий текст:

> Создание объектов базовых типов через new запрещено

Реакция C# на аналогичный код:
```
namespace Test
{	
	class Program
	{	
		public static void Main(string[] args)
		{
			var x = new byte();
		}
	}
}
```
это успешная компиляция.

**Comment by miks1965** [comment]
Нет, это придирки. В типе byte нет конструктора без параметров - это и выводится. Был бы - работало.

**Comment by MrFresnel** [comment]
Почему тогда в C# компилируется?

**Comment by miks1965** [comment]
Это не к нам, а к Microsoft
Запустите код:
```
begin
  typeof(System.Byte).GetConstructors.PrintLines;
end.
```
Что выдаётся?

**Comment by miks1965** [comment]
О! Вот!

Будете закрывать Issue?

**Comment by MrFresnel** [comment]
Вы его же закрыли. :)

**Comment by miks1965** [comment]
Не может быть! 

А, точно, закрыл! Это автоматически...

**Comment by miks1965** [comment]
Ну, там вопрос некорректный. Потому что это разные языки.

**Comment by MrFresnel** [comment]
Byte является типом-значения, а для типов-значений всегда доступен конструктор без параметров.

**Comment by miks1965** [comment]
Ну, как видите - нет его
