### ISSUE TITLE
Написать в справке о возможности реализации геттера и сеттера расширенного свойства методом

### ISSUE THREAD

**Issue by MrFresnel** [pascalabcnet/pascalabcnet#1363]
Судя по всему, это [запрещать](https://github.com/pascalabcnet/pascalabcnet/issues/1350) Вы, разработчики, не собираетесь. Если так, то, укажите эту возможность в справке, чтобы пользователи не могли это счесть за косяк компилятора.

**Comment by miks1965** [comment]
Нет, это проблема реализации в NET. Описывать в справке нижний уровень мы не будем.

**Comment by MrFresnel** [comment]
> Нет, это проблема реализации в NET. Описывать в справке нижний уровень мы не будем.

1) Хотелось бы увидеть ссылки на источники, подтверждающие, что это проблема .Net.
2) Откуда тогда пользователь узнает об этих тонкостях работы со свойствами, разве что читая наш форум и просматривая GitHub? Но, не все же этим занимаются.

**Comment by SunSerega** [comment]
@miks1965, @ibond84, проблема всё же не решена, потому что программист может случайно натолкнуться на эту "фичу". Раз ни в 1 паскале и ни в 1 .Net языке такого нету - надо хотя бы описать в справке. Иначе, из за того, как неожиданно может быть испорчена виртальность - это очень неприятно, неожиданно натолкнутся на это.

Хотя лучше, конено, запретить, как это сделали в C#.
