### ISSUE TITLE
Лишние пробелы по бокам от region/endregion не удаляются при форматировании

### ISSUE THREAD

**Issue by MrFresnel** [pascalabcnet/pascalabcnet#1369]
Исходный код:
```
{$   region   }
{$   endregion   }
begin
end.
```
После форматирования:
```
{$   region   }
{$   endregion   }
begin
end.
```
Ожидаемый результат:
```
{$region}
{$endregion}
begin
end.
```
Если же изначальный код имел следующий вид:
```
{$region   SomeText   }
{$endregion   SomeText   }
begin
end.
```
, то ожидаемый результат был бы следующим:
```
{$region SomeText}
{$endregion SomeText}
begin
end.
```

**Comment by ibond84** [comment]
Перестаньте закрывать и заново открывать все issue.

**Comment by ibond84** [comment]
Студия тоже не удаляет пробелы. Форматировать комментарии не надо. Кому-то может захочется красиво отцентрировать регион по центру.
