### ISSUE TITLE
При использовании поля базового шаблонного класса в шаблонном классе потомке компилятор падает

### ISSUE THREAD

**Issue by MrFresnel** [pascalabcnet/pascalabcnet#1379]
```
type
  TA<T> = class
    fX: byte;
  end;
  
  TB<T> = class(TA<T>)
    //procedure P() := self.fX := 0; // В процедуре или функции обязательно обращаемся через self.
    //function F() := self.fX;
    
    //property X1: byte read fX;
    //property X2: byte write self.fX := 0; // Обязательно обращаемся через self.
    //property X3: byte read fX write fX := 0;
  end;

begin
end.
```
От того используется ли краткая форма записи метода или нет падение компилятора не зависит.

[Источник](https://github.com/pascalabcnet/pascalabcnet/issues/907)

**Comment by SunSerega** [comment]
Я так понимаю, это было попытка лучше описать источник ошибки, тем самым помочь вам в её исправлении.

**Comment by miks1965** [comment]
Да мы знаем источник - это Self.X, где X - унаследованное поле

**Comment by MrFresnel** [comment]
> Я так понимаю, это было попытка лучше описать источник ошибки, тем самым помочь вам в её исправлении.

Да, именно так.
