### ISSUE TITLE
Разрешает делать указатели на записи со строками, но неправильно их потом разыменовывает

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#1380]
```
type
  r1 = record
    o: string;
  end;
  r2 = record
    o: object;
  end;
 
begin
  var p1: ^r1;//ok
  var p2: ^r2;//Ошибка: Нельзя объявить указатель на запись, содержащую ссылочные поля
end.
```
Если это так и должно быть - надо исправить это:
```
type
  r1 = record
    next: byte;
    s: string;
  end;
 
begin
  var p: ^r1;
  writeln(p^);
end.
```
![image](https://user-images.githubusercontent.com/27270190/46809171-9f76d400-cd76-11e8-8128-18d7ea42efdf.png)

**Comment by miks1965** [comment]
а чего это вы разыменовываете неинициализированный указатель?

**Comment by SunSerega** [comment]
Понятно что должна быть ошибка, но не вылет. Вот смотрите, если, к примеру, не будет поля `next: byte`:
```
type
  r1 = record
    s: string;
  end;

begin
  var p: ^r1;
  writeln(p^);//Ошибка времени выполнения: Ссылка на объект не указывает на экземпляр объекта.
end.
```
То получаем адекватную ошибку.

**Comment by SunSerega** [comment]
Но всё же, зачем разрешены указатели на записи со строками? Я понимаю короткие строки, для совместимости (хотя из за того что они ссылочные - можно словить неопределённое поведение), но зачем для обычных строк разрешать?

**Comment by SunSerega** [comment]
Нет ну подождите. Access Violation происходит при разыменовании указателя который не nil. Если значение указателя nil - должна выдаваться соответствующая ошибка.

**Comment by miks1965** [comment]
Причина непонятной работы программы - не повод делать Issue. Разберитесь вначале на форуме

**Comment by miks1965** [comment]
А, вижу проблему:
```
type
  r1 = record
    s: integer;
  end;

begin
  var p: ^r1 := nil;
  var o := object(p^);
end.
```
Этот код виснет. Сделаю-ка я новую Issue
