### ISSUE TITLE
Добавить инициализаторы классов по аналогии с инициализаторами записей

### ISSUE THREAD

**Issue by MrFresnel** [pascalabcnet/pascalabcnet#1383]
```
type
  TPoint = record // Если использовать class, то будет ошибка компиляции: Program2.pas(7) : Несовместимые типы 'TPoint' и record.
    x, y: byte;
  end;

var
  pnt: TPoint := (x: 1; y: 2);

begin
end.
```
Нынешнее состояние инициализаторов не соответствует заголовку [этой](http://pascalabc.net/wiki/index.php?title=Инициализаторы_полей_в_записях_и_классах) статьи.

**Comment by miks1965** [comment]
Нет, это неправильно. Инициализаторы записей - это дельфийское старьё, из-за которого у нас проблемы с грамматикой. Я бы их с удовольствием запретил.

А классы так инициализировать нельзя - для этого должен быть конструктор с синтаксисом new
