### ISSUE TITLE
Добавить подсветку ключевых слов typeclass и instance

### ISSUE THREAD

**Issue by MrFresnel** [pascalabcnet/pascalabcnet#1387]

**Comment by ibond84** [comment]
А разве это есть в релизе уже?

**Comment by MrFresnel** [comment]
Нет. Я на будущее, чтобы не забыли.

**Comment by miks1965** [comment]
Если это войдёт в релиз, обязательно подсветим. Собсвенно, в ветке с typeclasses всё уже подсвечено - после того как ветки будут слиты - это случится автоматически.
