### ISSUE TITLE
Чтение char игнорируется, если оно стоит в Readln после другой переменной

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#1391]
```
begin
  var i: integer;
  var ch: char;
  Readln(i, ch);
end.
```
Разворачивается в:
```
      PABCSystem.PABCSystem.Read(ref Program.i);
      PABCSystem.PABCSystem.Read(ref Program.ch);
      PABCSystem.PABCSystem.Readln();
```
Независимо от того - чем разделять `i` и `ch` при вводе (пробелом или переносом строки) - ch не прочитает (в него запишет или пробел или знак переноса строки). При этом если читать ещё что то после char - получаем "входная строка имел неправильный формат".

**Comment by AlexRnD61** [comment]
Ни в коем случае! Тогда Паскаль перестанет принимать данные через пробел.
Ввод в одном операторе символьных/строковых и прочих данных в Паскале канонически не рекомендован.

**Comment by MrFresnel** [comment]
> операторе 

Readln - процедура.

![image](https://user-images.githubusercontent.com/42812113/46992959-60010c80-d115-11e8-921b-adf9df3bb111.png)

**Comment by SunSerega** [comment]
> Тогда Паскаль перестанет принимать данные через пробел

А, так он всё же должен уметь это... Сейчас исправлю issue.

**Comment by AlexRnD61** [comment]
Все несколько иначе. В Паскале признаком окончания ввода служит одновременное наступление двух событий: нажата клавиша Enter (получен[ы] эквивалентный код) и список ввода исчерпан. Символьные и строчные данные отличаются от прочих тем, что они способны принимать символы с кодами x0D/x0A в качестве содержимого. Прием данных с клавиатуры в Паскале идет через буфер клавиатуры, где накапливаются коды нажатых клавиш. Если указана модификация с "ln", например, Readln, а не Read, то после завершения ввода буфер клавиатуры очищается. При "грязном" буфере его остаток может быть воспринят символьной/строковой переменной, как содержимое. Именно поэтому мы не можем смешивать ввод символьных/строковых данных с прочими типами в одной порции ввода. Посему абсолютно бесполезно указывать в списке ввода, к примеру, целочисленную переменную и строковую. Это - классика Паскаля и она описана (другой вопрос, насколько внятно) в любом учебнике по языку.

**Comment by AlexRnD61** [comment]
> Readln - процедура, а не оператор.

В языке программирования Паскаль все завершенные (самостоятельные) конструкции именуются операторами.

**Comment by MrFresnel** [comment]
![image](https://user-images.githubusercontent.com/42812113/47163839-7e2a6080-d2ff-11e8-96d6-9a97236870e8.png)

Справка, конечно, не идеальна, но в данном случае я такого же мнения, как и она на счёт Write/Writeln и ем подобных вещей.

**Comment by miks1965** [comment]
Вроде всё правильно работает. Приведите пример ввода, когда по-вашему что то неправильно

**Comment by SunSerega** [comment]
```
begin
  var i: integer;
  var ch: char;
  Readln(i, ch);
  writeln(i);
  writeln($'"{ch}"')
end.
```
![image](https://user-images.githubusercontent.com/27270190/47170266-45de4e80-d30e-11e8-96c1-39a23665d392.png)

**Comment by miks1965** [comment]
Ну правильно. Целое считывается до пробела, пробел остаётся во входном потоке. Он и считывается в Ch. А Вы хотели следующий после пробела символ? Считайте в Ch дважды

**Comment by SunSerega** [comment]
Ну, я это понять могу. Но это из задания на куберфоруме. Там как раз проблема была в том что непонятно, с чего вдруг оно не работает.

**Comment by miks1965** [comment]
Оно работает. Правильно. Целое считывается. Символ после целого - нет

**Comment by AlexRnD61** [comment]
> Можем. Но очень осторожно. Пример это показывает
Пример показывает, что обычный ввод не работает и надо идти на ухищрения, например, писать Readln(i, ch, ch); А это уже шаманство

**Comment by miks1965** [comment]
Ну не знаю. Лучше конечно написать Readln(i, ch, ch1) и сказать, что после целого идёт символ пробела, а после него символ Ё. Ровно они и считываются

**Comment by AlexRnD61** [comment]
Лучше написать Readln(i); Readln(ch); и никому ничего не говорить ))))
