### ISSUE TITLE
Добавить директиву для иконки

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#1392]
Генератор иконок и то, как им пользоваться - [тут](http://forum.mmcs.sfedu.ru/t/zamechaniya-i-predlozheniya/143/1066?u=sun_serega).

**Comment by ibond84** [comment]
Не работает ваш rc.exe. exe-шники не получают иконку

**Comment by SunSerega** [comment]
На самом деле всё это один большой костыль, даже если бы всё ещё работало...
Надо будет как-нибудь нормально в этом разобраться.
