### ISSUE TITLE
Тип шаблона не подставляет в имя класса при наведении мышки на метод

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#1393]
```
type
  c1<T>=class
    
    procedure p1 := exit;
  
  end;

begin
  var a := new c1<byte>;
  
  a.p1;//показывает "c1<>.p1()" вместо "c1<byte>.p1()"
end.
```

**Comment by ibond84** [comment]
так задумано

**Comment by SunSerega** [comment]
Как "так"?

Всюду в остальных местах подставляет:
```
type
  c1<T>=class
    
    function f1(a: T):T := exit;
  
  end;

begin
  var a := new c1<byte>;
  
  a.f1;
end.
```
![image](https://user-images.githubusercontent.com/27270190/47856172-36233780-ddef-11e8-9251-7bef6d773d47.png)

![image](https://user-images.githubusercontent.com/27270190/47856235-5f43c800-ddef-11e8-849f-4cd47aec8463.png)

Не надо, пожалуйста, убивать issue только потому что вам сейчас не хочется этим заниматься.
