### ISSUE TITLE
Перечисления могут быть обобщёнными

### ISSUE THREAD

**Issue by MrFresnel** [pascalabcnet/pascalabcnet#1395]
```
type
  Enum<T> = (X, Y);

begin
end.
```
Аналогичный код на C#:
```
enum Name<T> { X, Y }

class MainClass
{
  public static void Main (string[] args)
  {
  }
}
```
вызывает ошибку компиляции:

> Enums cannot have type parameters

**Comment by SunSerega** [comment]
Вариант на паскале не компилируется, нужно добавить ещё 1 параметр.

А компилятор ведёт себя неадекватно с таким типом:
```
type
  Enum<T> = (X,Y);

begin
  var o := X;//Ошибка: Неизвестное имя 'X'
  var a := Enum&<byte>.X;
  var b := Enum&<word>.X;
  Println(a,b);
  Println(a=b);//Ошибка: Операция '=' не применима к типам (X,Y) и (X,Y)
end.
```

**Comment by MrFresnel** [comment]
@SunSerega, уже подправил, но спасибо, что обратили внимание.

**Comment by SunSerega** [comment]
>Перечисления более чем с одним элементом

У перечислений в паскале вообще не может быть меньше 2 параметров... Хотя я не уверен фича ли))

**Comment by MrFresnel** [comment]
> У перечислений в паскале вообще не может быть меньше 2 параметров...

Спасибо, что обратили внимание.

**Comment by miks1965** [comment]
Надо запретить обобщённые перечисления. Смысла в них нет никакого. Спасибо за Issue - перечисления и обобщения часто используются, поэтому это горячее место в языке

**Comment by miks1965** [comment]
Да-а, в C# аналоги синонимов типов крайне бедные. Например, так можно:
```
using DT = System.Collections.Generic.List<int>;
```
И то только с указанием полного пространства имен.

А так уже нельзя:
```
using DT<T> = System.Collections.Generic.List<T>;
```
Дикий язык! В PascalABC.NET так уже лет 10 можно!

**Comment by MrFresnel** [comment]
> Дикий язык! В PascalABC.NET так уже лет 10 можно!

Давайте не будем начинать беседу на тему «плохой язык». Я про Ваш язык могу сказать то же самое, но я ведь этого не делаю.
