### ISSUE TITLE
Не зависимо от того, правильно ли описан тег документирующего комментария или нет, Intellisence отображает описание

### ISSUE THREAD

**Issue by MrFresnel** [pascalabcnet/pascalabcnet#1397]
```
type
  ///<summary>
  ///Описание класса.
  ///</summary>
  T1 = class
  end;
  
  ///</summary>
  ///Описание класса.
  ///</summary>
  T2 = class
  end;

  ///</summary>
  ///Описание класса.
  ///<summary>
  T3 = class
  end;
  
  ///<summary>
  ///Описание класса.
  ///<summary>
  T4 = class
  end;
  
  ///<ummary>
  ///Описание класса.
  ///<summary>
  T5 = class
  end;

  ///<summary>
  ///Описание класса.
  ///<ummary>
  T6 = class
  end;

begin
end.
```
Во всех случаях, кроме первого, Intellisence не должен показывать документирующего комментария, поскольку тег summary в них описан неправильно. На данный момент Intellisence только для T5 не показывает документирующего комментария. Visual Studio ничего не отобразит из описания, если тег записан неверно:

![image](https://user-images.githubusercontent.com/42812113/47161537-e75ba500-d2fa-11e8-92b9-c391c6cdee85.png)

**Comment by miks1965** [comment]
у нас еще есть сокращение в виде просто /// - все документирующие комментарии в системном модуле построены именно так. Видимо они и срабатывают

**Comment by MrFresnel** [comment]
Лучше это исправить. Пусть будет два варианта документирования, но они не будут мешать друг другу.

**Comment by ibond84** [comment]
Это не ошибка. Просто берется ///Описание класса. и все
