### ISSUE TITLE
Компилятор по-разному реагирует на закомментированные директивы

### ISSUE THREAD

**Issue by MrFresnel** [pascalabcnet/pascalabcnet#1399]
В следующем примере регионы могут быть свёрнуты:

Закомментированность не влияет на работу следующих директив:
apptype:
```
//{$apptype console}

uses GraphABC;
begin
end.

gendoc:

//{$gendoc true}

///Что-то делает.
procedure P() := exit;

begin
end.

region/endregion:

//{$region} 
procedure P1() := exit; 

procedure P2() := exit; 
//{$endregion} 

begin 
end.
```
Но, в данном примере закомментированная директива не действует:

Закомментированность влияет на работу следующих директив:
defined, ifdef, ifndef, else, endif:
```
//{$define Name} 

{$ifdef Name} 
procedure P() := exit; 
{$endif} 

begin 
P(); 
end.
```

**Comment by SunSerega** [comment]
$reference тоже действует если его закомментировать. Стоит пройтись по всем директивам из справки

**Comment by miks1965** [comment]
Вот более новый Issue:
https://github.com/pascalabcnet/pascalabcnet/issues/2037
Я его закрыл, потому что он непонятный - в шапке приведен код на C# зачем-то

**Comment by AIexandrKotov** [comment]
Это конкретные места компилятора, в которых и ингорируются комментарии. А здесь ещё и дезинфа с регионами.

**Comment by ibond84** [comment]
Это было еще в марте исправлено

**Comment by AIexandrKotov** [comment]
Странно, в июле воспроизводилось. Ну и ладно
