### ISSUE TITLE
Подключение библиотеки делает использование PABCSystem. глючным (получаются два PABCSystem)

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#1400]
lib.pas:
```
library lib;

end.
```
0.pas:
```
{$reference lib.dll}
uses System;

begin
  PABCSystem.Randomize;// Ошибка: Неизвестное имя 'Randomize'
end.
```
[0.zip](https://github.com/pascalabcnet/pascalabcnet/files/2495918/0.zip)

Если убрать `{$reference lib.dll}` - ошибка остаётся до перезагрузки IDE.
Если убрать `uses System;` - ошибка сразу пропадает.

**Comment by KawaiLoli** [comment]
Я бы ещё проверил падают ли любые другие модули при использовании польз. библиотек. Из всех issue это надо исправлять в первую очередь.

**Comment by SunSerega** [comment]
Нет, дело только в `PABCSystem`, пользовательские модули от этого не страдают. И если библиотека не пользовательская а стандартная - тоже всё нормально.

**Comment by miks1965** [comment]
Понятен источник проблемы. В любую dll вносится набор из примерно 64 имен PABCSystem вместе с пространством имен PABCSystem. А тут мы пытаемся из PABCSystem вызвать функцию Randomise, которой нет в этом списке. В результате рассматривается именно пространство имен PABCSystem, зашитое в dll, а не стандартный модуль

**Comment by miks1965** [comment]
Обращаю также внимание, что даже если мы это сделаем, есть несколько классов в пространстве имен PABCSystem в dll. Из них самым пугающим является Text. То есть тип Text в основной программе будет не совместим с типом Text из библиотеки.

Вот например вполне благопристойный код
```
library lib;

procedure p(t: Text);
begin
end;

end.

{$reference lib.dll} 

begin
  var t: Text;
  p(t)
end.
```
вылетает с ошибкой 
0.pas(7) : Нельзя преобразовать тип Text к PABCSystem.Text

ibond прошу откликнуться.

**Comment by ibond84** [comment]
Ну, вы же понимаете, что здесь решение только одно и оно не в стиле паскаля: использовать только PABCRtl.dll, а не зашивать модули в exe-шник.

**Comment by miks1965** [comment]
Я предлагаю вторую проблему просто прописать в документации. Я собственно это уже сделал. 
А вот первую проблему я бы переформулировал так: давать пространству имен PABCSystem, импортируемому в библиотеку, имя PABCSystem_ИмяБиблиотеки.

**Comment by miks1965** [comment]
Вообщем, исправил так: SymbolTable.cs 963 (FindAllInAreaList)
```
if (sc is DotNETScope && name.ToLower() != "pabcsystem") // имя pabcsystem при поиске в сборках игнорировать!
```
То есть, при поиске в сборках имя pabcsystem игнорируется
