### ISSUE TITLE
«Отрицательная длина массива (0) не допустима» при использовании integer в [] в контексте массивов

### ISSUE THREAD

**Issue by MrFresnel** [pascalabcnet/pascalabcnet#1402]
```
uses System;

type
  T1 =  array [SByte] of byte;
  T2 =  array [Byte] of byte;
  //T3 =  array [Int32] of byte; // Program1.pas(6) : Отрицательная длина массива (0) не допустима
  T4 =  array [Char] of byte;

begin
end.
```

**Comment by miks1965** [comment]
Да, спасибо. Именно для типа Int32 такая странная ошибка.

**Comment by AlexRnD61** [comment]
> Именно для типа Int32 такая странная ошибка.

Странного как раз ничего нет. У статического массива длина не может быть бесконечной, там счетчик стоит.
T3 =  array [1..2147483647] of byte; - это еще можно описать, а вот 
T3 =  array [0..2147483647] of byte; описать уже нельзя. Посему и большую длину тоже нельзя описать. Надо только сообщение компилятора на более внятное переделать, как в случае с 
T4 =  array [int64] of byte;

**Comment by SunSerega** [comment]
А можете, пожалуйста, проверить теперь как будет с `array[int64]`?

**Comment by AlexRnD61** [comment]
А Вы что, сами не можете? Изменений не вносили, для int64 было прежде сообщение, что в массиве слишком много элементов.

**Comment by SunSerega** [comment]
Это в старом релизе. А в новом этого нет. Раньше длину конвертировало в int32 и когда длинна была максимальным значением int32 - получалась такая странная ошибка. А исправили - заменив int32 на int64, вот я и думаю - не будет ли теперь такая же ошибка для int64...

**Comment by AlexRnD61** [comment]
Что за "новый релиз"? У меня пока что сборка 1837 и на сайте другого для скачивания нет..

**Comment by SunSerega** [comment]
Вот да, я имел в виду сборку. А то что и как исправили видно [тут](https://github.com/pascalabcnet/pascalabcnet/commit/421a7dd8652c217f8869bc7303e7239c53e48787).

> А в целом это все из разряда заоблачной экзотики

Да, это и должно выдавать ошибку далее, но правильную (`Слишком большой диапазон`, как сейчас у `array[int64]`), а отрицательный 0 - это явно что то не то.

**Comment by miks1965** [comment]
```
T3 = array [0..2147483647] of byte;
```
Сейчас выводится "Слишком большой диапазон". Неправильное сообщение об ошибке исправлено.

**Comment by SunSerega** [comment]
Так а для `T3 = array [int64] of byte;`? Я именно про него спрашивал.

**Comment by miks1965** [comment]
Program1.pas(1) : Слишком большой диапазон
