### ISSUE TITLE
match - неверное поведение int-double

### ISSUE THREAD

**Issue by miks1965** [pascalabcnet/pascalabcnet#1406]
```csharp
       static void Main(string[] args)
        {
            var a = 1;
            switch (a)
            {
                case byte i: Console.WriteLine(111);
                    break;
            }
        }
```
В C#: Выражение типа "int" не может быть обработано шаблоном типа "byte".	

У нас такой код проходит:
```pascal
begin
  var pp: integer;
  match pp with
    byte(var p): Print(1);
  end;
end.
```
Разумеется, не матчится

**Comment by SunSerega** [comment]
А в C# соответствующий этому код:
```
begin
  case 5 of
    3: writeln(e);
  end;
end.
```
Нормально выполняется? Если нет - то и `match` менять не надо. В паскале ведь не нужно это `else break` чтоб показать что и так нормально.

**Comment by miks1965** [comment]
Это следствие более простого.
В C#
```csharp
bool q = 1 is byte b;
```
это не компилируется.

В PABC компилируется, что неверно:
```pascal
var x := 1 is real (var rr);
```

**Comment by miks1965** [comment]
Собственно, сделать эту семантическую проверку - её просто нет.

типы должны либо совпадать либо один быть наследником другого.

Для интерфейсов всё свободнее: интерфейс можно матчить с любым другим интерфейсом, поскольку могут быть классы, реализующие оба интерфейса.

**Comment by wisestump** [comment]
Fixed in 9e7bd5df513b4ba5949a122b385e974eeed3aa0c & 3e2f74ec12f09553fb1c67d41d92771fa6b99168

**Comment by SunSerega** [comment]
Кхм, @wisestump вы разделили на MatchedExpression и MatchedExpressionAndType, можете показать примеры обоих?

Say, if you don't understand Russian.

**Comment by wisestump** [comment]
Это для удобства внутри компилятора: MatchedExpression для проверок сопоставляемого выражения, MatchedExpressionAndType для проверки совместимости сопоставляемого выражения и типа образца

**Comment by wisestump** [comment]
Пример первого - проверка на запрет указателей, второй - этот issue
