### ISSUE TITLE
match разрешает повторение типа

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#1408]
```
begin
  match new object with
    integer(i): ;
    integer(i): ;
  end;
end.
```

**Comment by miks1965** [comment]
Не вижу ошибки. Всё нормально. match у нас - это куча вложенных цепочечных  if. И если кто-то написал if с одинаковыми условиями,только первый сработает.

**Comment by SunSerega** [comment]
Весь смысл `match` - объединять несколько if+is-var -ов. Чтоб код был читабельнее и чтоб компилятор помогал находить мелкие баги.
Если `match` будет только сахаром над if - толку от него мало.
