### ISSUE TITLE
function f := f(0); в классе не работает если f(i) описана позже

### ISSUE THREAD

**Issue by miks1965** [pascalabcnet/pascalabcnet#1424]
```
type
  A = class
    function f := f(0);
    function f(i: integer) := i;
  end;

begin
  
end.  
```
Program1.pas(3) : Неверное количество параметров функции

**Comment by ibond84** [comment]
Это уже много раз обсуждалось. Для вычисления типа f надо **сразу** распарсить f(0), а оно описано позже, поэтому надо явно определять тип возвращаемого значения.

**Comment by SunSerega** [comment]
Или проходить по классу несколько раз. Я что то похожее в SAC делал, вам достаточно проходить по все методам, помечая какие не удалось спарсить. Потом пройтись ещё раз, и если не удалось ни 1 нового спарсить - тогда бросать "Нельзя вычислить тип". И так проходить пока все не спарсятся.

**Comment by ibond84** [comment]
Не надо ничего по 20 раз проходить. Сигнатуры методов должны проходиться один раз.

**Comment by SunSerega** [comment]
К чему такая принципиальность? Это будет медленно? С чего вдруг?

**Comment by ibond84** [comment]
Это усложняет компилятор. Ради синтаксического сахара не должна донельзя усложняться семантика.
