### ISSUE TITLE
Добавить директиву, для добавления файлов манифеста

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#1426]
Я писал несколько раз на форуме, но вы игнорите. Поэтому пишу тут.

**Comment by miks1965** [comment]
Это я не понимаю что это

**Comment by SunSerega** [comment]
На форуме я объяснял, что это необходимо чтоб обойти UIPI. Вот описание с msdn:

https://docs.microsoft.com/en-us/windows/desktop/SbsCs/manifests

>Manifests are XML files that accompany and describe side-by-side assemblies or isolated applications. Manifests uniquely identify the assembly through the assembly's assemblyIdentity element. They contain information used for binding and activation, such as COM classes, interfaces, and type libraries, that has traditionally been stored in the registry. Manifests also specify the files that make up the assembly and may include Windows classes if the assembly author wants them to be versioned. Side-by-side assemblies are not registered on the system, but are available to applications and other assemblies on the system that specify dependencies in manifest files.
>
>Manifest files enable administrators and applications to manage side-by-side assembly versions after deployment. Every side-by-side assembly must have a manifest associated with it. The installation of Windows XP installs the supported Microsoft side-by-side assemblies with their manifests. If you develop your own side-by-side assemblies, you must also install manifest files. For more information, see Installing Side-by-Side Assemblies and Manifest Files Reference.

Через него так же правильно запрашивать UAC и там же куча всего другого, связанного с безопасностью и правами.

**Comment by SunSerega** [comment]
> Не помню такого на форуме.

http://forum.mmcs.sfedu.ru/t/pomoshh-novichkam/263/1581?u=sun_serega

> PascalABC.NET не является средством профессионального программирования

Запрос UAC (окна в котором запрашиваются права админа) - это не такая уж и страшная вещь. Это вполне может быть нужно и в мелких программах (мне не раз надо было). Я пока что извращался через перезапуск программы через cmd и параметрами вызывающими UAC, когда её запустили без этих параметров.

На куберфоруме были про это вопросы, но ни 1 нормального ответа. Разве это хорошо при обучении программированию?

**Comment by SunSerega** [comment]
Чтоб оно было одним файлом. Вот у меня установщик SAC - он должен запрашивать UAC, потому что ему нужен доступ в реестр и Program Files.

**Comment by miks1965** [comment]
Ну, мы это не умеем делать. Мы также редактор ресурсов не умеем писать многое чего...
