### ISSUE TITLE
Arr&<byte>().SomeExtension(x -> 0) - нужно зачем-то явное приведение типа

### ISSUE THREAD

**Issue by MrFresnel** [pascalabcnet/pascalabcnet#1428]
```
function SomeExtension<T>(self: sequence of T; f: Func<T, T>): sequence of T; extensionmethod;
begin
end;

begin
  Arr&<byte>().SomeExtension(x -> byte(0)); // Без оператора приведения типов не скомпилируется.
end.
```
Однако, в следующем примере компиляция пройдёт успешно:
```
begin
  var x := 2455;
  var y: byte := x;
end.
```

**Comment by miks1965** [comment]
Ну да, лямбда не соответствует прототипу Func<T, T> - у неё типы аргумента и возвращаемого значения разные

**Comment by SunSerega** [comment]
В основном да, но можно считать что шаблонные типы вычисленные из self - имеют больший приоритет. Чтоб было как у обычных методов:
```
type
  t1<T>=class
    procedure SomeMethod(f: Func<T,T>) := exit;
  end;

begin
  t1&<byte>.Create.SomeMethod(b->word(b));
end.
```
Это откомпилируется, потому что T уже вычислен из self. И по параметрам уже не пытается вычислить T.
