### ISSUE TITLE
Нельзя получить ссылку на процедуру new, даже если экранировать его

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#1430]
```
begin
  var p1 := new;//  Ошибка: Ожидался тип после new
  var p2 := &new;// Ошибка: Ожидался тип после new
end.
```
При этом анализатор кода в обоих случаях считает что ссылку можно получить (даёт соответствующий тип для p1 и p2).

**Comment by ibond84** [comment]
И правильно не дает.  New это intrinsic-процедура,

**Comment by SunSerega** [comment]
Нет, я не про new которое ключевое слово, а про вот это:
```
begin
  var p: ^byte;
  new(p);
end.
```
