### ISSUE TITLE
Методы библиотеки - методы класса в одноимённом неймспейсе

### ISSUE THREAD

**Issue by AIexandrKotov** [pascalabcnet/pascalabcnet#1437]
lib.pas:
```
library lib;

function s: sequence of integer;
begin
  Result:=Seq(1,2,3);
end;

function d: integer;
begin
  Result:=0;
end;

procedure p:=exit;

type
  k = class end;

begin
  
end.
```

Методы s, d, p не показываются при обращении к библиотеке (неймспейсу, так его показывает анализатор кода), но показываются классы библиотеки:
![2](https://user-images.githubusercontent.com/44296606/47620860-9c167300-db00-11e8-9362-dcb2209a3b27.png)

Но при этом методы доступны через класс lib в неймспейсе lib:
![3](https://user-images.githubusercontent.com/44296606/47620871-c9632100-db00-11e8-8964-88e2cb41686b.png)
И ошибки такое обращение не вызовет.

У класса lib нет никаких конструкторов, но показывается Create.

**Comment by miks1965** [comment]
Ну, а в чём ошибка?

**Comment by SunSerega** [comment]
Глобальные методы библиотеки не показывает просто в `lib.`. Зато из показывает в `lib.lib.`.

**Comment by miks1965** [comment]
Ну, lib - это пространство имен, внутри него - класс lib - внутри него все методы. В чем ошибка?

**Comment by miks1965** [comment]
Intellisense отображает содержимое dll независимо от языка. В dll всё ровно так. Компилятор не знает, на каком языке dll создана.

Как бы ни можно было в IL, в паскале сделано так: класс Lib автоматически создаётся компилятором внутри пространства имен lib.

При подключении библиотеки пространство имён подключается автоматически. 
Таким образом, lib.p правильно трактуется компилятором как lib.lib.p. Это не отображается в Intellisense поскольку Intellisense делает предпочтение считать lib пространством имён - раз оно есть в dll.

**Comment by SunSerega** [comment]
А просто `p;` почему не показывает?
И - тогда надо сделать чтоб анализатор кода объединял lib который класс и lib который пространство имён. Иначе он дезинформирует.

**Comment by miks1965** [comment]
Потому что в пространстве имен lib нет p - потому и не показывает.

Дезинформирует - согласен - потому что компилятор оказывается более умным чем Intellisense. Но это - крайне редкая ситуация, когда пишут lib.p. Начнем с того что это даже не отображается в Intellisense.

Нет, Intellisense не будет ничего объединять. То, что Вы предлагаете - это кошмар. Чтобы Intellisense одновременно считал lib типом и пространством имён. И всего-то из-за мнимого того что Вам кажется, что так должно быть

**Comment by SunSerega** [comment]
Анализатор кода должен отображать не меньше чем позволяет компилятор, а обычно больше. Не помню или вы или @ibond84 под этим предлогом разрешил отображать тут по точке методы типа `byte`:
```
function f1(b: byte) := b;

begin
  f1.
end.
```
И - я не предлагал устраивать кошмар вроде того чтоб анализатор кода воспринимал lib как суперпозицию пространства имён и класса. Я предлагал лишь когда нажимается точка - добавлять в список кроме элементов пространства имён, ещё и элементы класса. Этого уже будет достаточно.

> Замечу, что Intellisense C# будет отображать только lib.lib.p и будет прав. Собственно, у нас тоже так отображает

Вот это точно не тот случай когда на C# надо ориентироваться. В C# пространство имён из библиотеки не добавляется в основное без `using`. А если добавить `using` - то и анализатор кода будет показывать.

**Comment by MrFresnel** [comment]
> Замечу, что Intellisense C# будет отображать только lib.lib.p и будет прав. Собственно, у нас тоже так отображает
Повторю Вашу любимую фразу:
> У нас не C#
