### ISSUE TITLE
Help for ReadMatr* functions

### ISSUE THREAD

**Issue by Evg503** [pascalabcnet/pascalabcnet#1438]
На старанице http://pascalabc.net/downloads/pabcnethelp/index.htm отсутствуют описания функций ReadMatr*

**Comment by miks1965** [comment]
Не пишите сюда про ошибки на сайте. Справка на сайте обновляется редко - там много чего нет

**Comment by SunSerega** [comment]
@Evg503 пишите лучше [сюда](http://forum.mmcs.sfedu.ru/t/zamechaniya-i-predlozheniya/143/1092). issue тут больше для ошибок компилятора/анализатора кода.
