### ISSUE TITLE
Не видит inherited метод в функции с yield

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#1440]
```
type
  t1=class
    function f1: sequence of byte; virtual := new byte[](1);
  end;
  t2=class(t1)
    function f1: sequence of byte; override;
    begin
      yield (inherited f1).First;//Ошибка: Неизвестное имя 'f1' 
    end;
  end;

begin end.
```

**Comment by miks1965** [comment]
Нужно в классе t2 делать функцию inhf1 с теми же параметрами, что и у f1 базового класса. Так в C#.

К сожалению, у нас не такой сильный анализатор - если класс t1 находится в другой dll, то всё это придётся делать на семантическом уровне, делая обёртки для .NET - кода. Проще запретить inherited в yield-функциях - пусть пишут обёртки сами.
