### ISSUE TITLE
"Несколько подпрограмм могут быть вызваны" при переопределении operator=

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#1441]
```
type
  t1=class
    static function operator=(a,b: t1): real := 5;
  end;

begin
  var a := new t1;
  var b := new t1;
  var c := a=b;//Ошибка: Несколько подпрограмм могут быть вызваны
end.
```
Если возвращаемое значение `operator=` будет иметь тип целого числа или boolean - ошибки нет.

**Comment by miks1965** [comment]
Ну так и есть. Если вы переопределяете стандартное сравнение ссылок на равенство, то будет вызываться эта реализация. А если вы определяете что-то новое, то возникают два оператора = с разным типом возвращаемого значения.

**Comment by miks1965** [comment]
Это странно. Посмотрю

**Comment by miks1965** [comment]
Это странное поведение связано со следующей странной возможностью явного преобразования:
```
begin
  var b: boolean;
  var w: word;
  //b := boolean(w);
  w := word(b);
end.
```
Странно, что даже явно такое можно сделать.

Но также странно, что явные преобразования участвуют в выборе более хорошей функции - должны вроде участвовать только неявные
