### ISSUE TITLE
System.Delegate(f1) вызывает функцию вместо получения ссылки

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#1442]
```
function f1: byte := 0;

begin
  var d1 := f1 as System.Delegate;//Ошибка: Ожидался класс-потомок или класс-предок
  var d2 := System.Delegate(f1);//Ошибка: Невозможно явно преобразовать тип byte к типу System.Delegate
end.
```

**Comment by miks1965** [comment]
Это особенность PascalABC.NET - в выражениях имя функции без параметров означает её вызов.
Пишите так:
```
function f1: byte := 0;

begin
  var g: ()->byte := f1;
  var d1 := g as System.Delegate;
  var d2 := System.Delegate(g);
end.
```
Это единственный случай когда имя функции воспринимается как указатель на функцию.

**Comment by SunSerega** [comment]
У вас же уже функция воспринимается как суперпозиция вызова и ссылки. Надо лишь сделать чтоб при преобразовании пробовало не только вызов а ещё и получение ссылки.

**Comment by miks1965** [comment]
Есть только одно место, где этот выбор делается - в инициализаторах переменных. Я вам этот приём показал
