### ISSUE TITLE
SplitAt вычисляет последовательность 2 раза

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#1451]
```
function f1: sequence of byte;
begin
  writeln('stating');
  yield 1;
  yield 2;
end;

begin
  writeln(f1.SplitAt(1));
end.
```
```
stating
stating
([1],[2])
```
Если посмотреть реализацию - всё понятно:
```
/// Разбивает последовательности на две в позиции ind
function SplitAt<T>(Self: sequence of T; ind: integer): (sequence of T, sequence of T); extensionmethod;
begin
  Result := (Self.Take(ind), Self.Skip(ind));
end;
```
Надо заменить на это:
```
///--
function EnmrCount<T>(enm: IEnumerator<T>; c: integer): sequence of T;
begin
  while (c <> 0) and enm.MoveNext do
  begin
    yield enm.Current;
    c -= 1;
  end;
end;

/// Разбивает последовательности на две в позиции ind
function SplitAt<T>(Self: sequence of T; ind: integer): (sequence of T, sequence of T); extensionmethod;
begin
  var enm: IEnumerator<T> := self.GetEnumerator;
  var s1 := EnmrCount(enm, ind);
  s1 := s1.ToList;//без этого при выводе получаем неправильный порядок вычисления
  var s2 := EnmrCount(enm, -1);
  Result := (s1, s2);
end;
```
Я протестировал, работает правильно.

**Comment by miks1965** [comment]
Последовательности не должны работать с побочными эффектами. 
```
writeln('stating');
```
- это побочный эффект. Не делайте этого, а если делаете - не обижайтесь.

Ровно такая реализация - в известной библиотеке расширений MoreLINQ

**Comment by SunSerega** [comment]
Не в том дело, эта строчка только чтоб показать. Без побочных эффектов - результат будет тот же, но производительность на много ниже.

Ни 1 из стандартных функций последовательностей не вычисляет их больше 1 раза. Вот к примеру `Reverse` - оно не проходит по всем элементами кучу раз, а создаёт список и проходит по нему в обратном порядке. Поэтому и тут надо так же.

Кроме того, побочные эффекты не всегда удаётся избежать. К примеру при чтении файла - бывают случаи (уже не раз мне встретились) когда неприемлемо держать в памяти сразу весь файл, но надо как то обработать его строчки. Могу скинуть коды в которых это понадобилось.

**Comment by SunSerega** [comment]
P.S. не знаю что вы где нашли, но вот реализация [Split из MoreLINQ](https://github.com/morelinq/MoreLINQ/blob/master/MoreLinq/Split.cs):
```
        public static IEnumerable<TResult> Split<TSource, TResult>(this IEnumerable<TSource> source,
            Func<TSource, bool> separatorFunc, int count,
            Func<IEnumerable<TSource>, TResult> resultSelector)
        {
            if (source == null) throw new ArgumentNullException(nameof(source));
            if (separatorFunc == null) throw new ArgumentNullException(nameof(separatorFunc));
            if (count <= 0) throw new ArgumentOutOfRangeException(nameof(count));
            if (resultSelector == null) throw new ArgumentNullException(nameof(resultSelector));

            return _(); IEnumerable<TResult> _()
            {
                if (count == 0) // No splits?
                {
                    yield return resultSelector(source);
                }
                else
                {
                    List<TSource> items = null;

                    foreach (var item in source)
                    {
                        if (count > 0 && separatorFunc(item))
                        {
                            yield return resultSelector(items ?? Enumerable.Empty<TSource>());
                            count--;
                            items = null;
                        }
                        else
                        {
                            if (items == null)
                                items = new List<TSource>();

                            items.Add(item);
                        }
                    }

                    if (items != null && items.Count > 0)
                        yield return resultSelector(items);
                }
            }
        }
```
В ней не только не используются методы вычисляющие последовательность 2 раза, в ней ещё и разбиение идёт на последовательность списков (списки преобразуется селектором, но по-умолчанию он не выполняет преобразования ни к чему, кроме как список=>последовательность).

То есть в итоге, тут создаётся по списку на каждую последовательность (а в моей программе только для первой).

**Comment by SunSerega** [comment]
P.P.S. да, я написал программу, чтоб найти где есть хоть какое то упоминание Split - нигде нету такого как у вас. Может там так реализовали как костыль, то есть временно, а потом сделали нормальную реализацию? Потому что всё же методы последовательностей никогда не должны вычислять их больше 1 раза. Это общее правило, которого придерживаются все функции последовательностей.

**Comment by miks1965** [comment]
Ага, хорошо, давайте переоткрою

**Comment by miks1965** [comment]
Нет, не будем переделывать. Всё правильно, Вы просто неправильно этими функциями пользуетесь. Там много таких функций: Partition, UnZipTuple, требующие 2 прохода по последовательности. И их так просто не переделаешь

**Comment by SunSerega** [comment]
Ничего там сложного. Я могу написать вам замены им. Другое дело - сейчас оно противоречит одному из основных правил функций последовательностей.

**Comment by SunSerega** [comment]
В общем я исправлю сам и кину пулл-реквест...

Буду писать о том как идёт - тут:
http://forum.mmcs.sfedu.ru/t/funkczii-posledovatelnostej-iz-pabcsystem-realizovannye-kostylyom/2671

**Comment by MrFresnel** [comment]
> Всё правильно

Оно работает, но это не значит, что эффективно.

**Comment by miks1965** [comment]
Последовательности вообще менее эффективны чем массивы.

То, что предлагается, - записать последовательность в список, - существенно менее эффективное решение - по времени и по памяти
