### ISSUE TITLE
Запретить перенос описания типа sequence of T на строку с объявлением переменной данного типа

### ISSUE THREAD

**Issue by MrFresnel** [pascalabcnet/pascalabcnet#1461]
Изначальный код
```
begin
  var x: array
  of
  byte;
  
  var y: set
  of
  byte;
  
  var z: sequence
  of
  byte;
end.
```
После форматирования:
```
begin
  var x: array
  of
  byte;
  
  var y: set
  of
  byte;
  
  var z: sequence of byte;
end.
```
Ожидаемый результат:
```
begin
  var x: array
  of
  byte;
  
  var y: set
  of
  byte;
  
  var z: sequence
  of
  byte;
end.
```

**Comment by MrFresnel** [comment]
Причина закрытия Issue?

**Comment by ibond84** [comment]
Я вам в соседних issues уже объяснил.

**Comment by MrFresnel** [comment]
Я согласился с Вами и поэтому сделал Issue, чтобы описание типа последовательности не переносилось на строку с объявлением переменной.

**Comment by miks1965** [comment]
Я предлагаю две стратегии автоформатированиядля любителей расставлять пробелы где им нравится. 

Первая. Оставлять их форматирование как есть. Так в частности поступает Студия когда не может понять ничего в записи
```
this IEnumerable<
T

                        > 
```
Она оставляет всё это безобразие как есть. 

Вторая. Сворачивать устойчивые идиомы в одно целое. Например, имя типа, разбитое по нескольким строчкам, сворачивать до 
```
var z: sequence of byte;
```
Если это несложно технически.

**Comment by SunSerega** [comment]
Это уже есть. Где то есть настройка - агрессивное форматирование. По-умолчанию=true, и оно удаляет все лишние пробелы. А если убрать - не должно (хотя я не пробовал).
