### ISSUE TITLE
Запретить использовать PABCSystem.TypedSet непосредственно

### ISSUE THREAD

**Issue by MrFresnel** [pascalabcnet/pascalabcnet#1466]
```
begin
  var x := new TypedSet();
end.
```
То, что можно использовать TypedSet без проблем - не очень хорошо. Ладно, если не ломается никакая логика внутри программы, то это еще терпимо (но, нежелательно), но это не всегда так. Детали внутренней реализации по-хорошему должны быть скрыты от пользователя и защищены от несанкционированного доступа.

**Comment by miks1965** [comment]
Считайте, что его нет. Его нет в справке, в Intellisense.

Потому что как его ни защищай - знающий доберётся до него отражением.

**Comment by MrFresnel** [comment]
> Считайте, что его нет.

Это никак не аргумент. Это просто нежелание что-то исправлять.

**Comment by MrFresnel** [comment]
> Все другие виды Issue нами отвергаются.

То есть, улучшение качества кода, генерируемого Вашим компилятором, не входит в Вашу задачу?
