### ISSUE TITLE
Конструктор внутреннего класса ставится в генерируемом компилятором коде перед конструктором предка при захвате лямбдой в конструкторе переменной

### ISSUE THREAD

**Issue by MrFresnel** [pascalabcnet/pascalabcnet#1467]
Если лямбда в конструкторе захватывает какую-то переменную, то конструктор внутреннего класса ставит перед конструктором предка. Это не ломает ничего, но плохой тон.

![image](https://user-images.githubusercontent.com/42812113/48080652-382a3380-e1ff-11e8-8e5f-05c4aef5a2d3.png)

**Comment by miks1965** [comment]
Некрасивый код - не повод для Issue. Сломайте что-нибудь - и пишите.

**Comment by MrFresnel** [comment]
> Сломайте что-нибудь - и пишите.

Не надо указывать мне что мне делать и когда. Я же Вам не указываю.

**Comment by MrFresnel** [comment]
То есть, улучшение качества кода, генерируемого Вашим компилятором, не входит в Вашу задачу?
