### ISSUE TITLE
Undefined FileName при yield функции возвращающей sequence of procedure

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#1469]
```
function f1: sequence of procedure;
begin
  yield nil;//не важно что елдить, можно и не nil
end;

begin end.
```
`Undefined FileName(0) : Нельзя преобразовать тип clyield#1 к IEnumerator<procedure()>`

**Comment by SunSerega** [comment]
Скорее всего дело в том - что `procedure` это анонимный тип, поэтому одно `IEnumerator<procedure>` не равно другому:
```
begin
  var e1: IEnumerator<procedure>;
  var e2: IEnumerator<procedure>;
  e1 := e2;
end.
```
Только тип `e2` это `clyield#1` (тип создаваемый yield), но он наследует от `IEnumerator<procedure>`.

То есть, надо чтоб если функция с `yield` возвращает элементы анонимного типа - этот тип отдельно выносило, как то так:
```
type
  clyield#1anon_type#1=procedure;

function f1: sequence of clyield#1anon_type#1;
begin
  yield nil;//не важно что елдить, можно и не nil
end;

begin end.
```
(я проверил, если в этой программе заменить все `#` на что то типа `_` - ошибки нет).

Прошу так же обратить внимание, что не только тип элемента, а и тип его шаблона может быть анонимным:
```
function f1: sequence of (byte,IEnumerable<procedure>);
begin
  yield nil;
end;

begin end.
```
То есть надо пройтись рекурсивно по всем шаблонным типам (в том числе и вложенным).

**Comment by ibond84** [comment]
Запретить нафиг sequence of procedure

**Comment by ibond84** [comment]
с yield

**Comment by SunSerega** [comment]
А к чему такая радикальность?

**Comment by ibond84** [comment]
Потому что procedure и procedure это разные типы.
