### ISSUE TITLE
При выборе extensionmethod-а - даёт приоритет sequence of T над T

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#1470]
```
begin
  var hs := new HashSet<object>;
  hs += new object;
  hs += nil;
end.
```
`hs += nil` вызывает
`operator+=<T>(var Self: HashSet<T>; x: sequence of T): HashSet<T>`
что даёт ошибку на этапе выполнения.

А надо чтоб или давало ошибку (потому что nil может быть и `object` и `sequence of object`) или вызывало это:
`operator+=<T>(var Self: HashSet<T>; x: T): HashSet<T>`

К примеру тут:
```
procedure p1(s: sequence of object) :=
writeln('sequence');

procedure p1(s: object) :=
writeln('object');

begin
  p1(nil);
end.
```
Даёт приоритет просто `object`, поэтому, наверное, надо и в `extensionmethod`-ах так же

**Comment by ibond84** [comment]
Ну, добавить проверку в operator+=<T>(var Self: HashSet<T>; x: sequence of T): HashSet<T> и все. nil не имеет типа,

**Comment by SunSerega** [comment]
Не только в нём дело, в PABCSystem полно таких функций.

Я же говорю, надо чтоб одинаково работало.
```
procedure p1(s: sequence of object) :=
writeln('sequence');

procedure p1(s: object) :=
writeln('object');

begin
  p1(nil);
end.
```
Тут для `nil` всё же выбирает тип `object`.

Я вообще предлагают давать ошибку - несколько подпрограмм могут быть вызваны, потому что так и есть.

**Comment by miks1965** [comment]
При перегрузке если это возможно, то выбирается более специализированная версия. Так что должна выбираться sequence of object. Ошибка про несколько подпрограмм возникает когда расстояние до нескольких версий одинаково.

**Comment by SunSerega** [comment]
> Беда в том, что nil не имеет типа.

Если с этой стороны смотреть - как раз надо давать `несколько подпрограмм могут быть вызваны`.
Потому что он на столько же не `object`, на сколько не `sequence of object`.

А если воспринимать тип `nil` как суперпозицию `object` и `pointer` - становится однозначно что в обоих случаях должно выбираться `sequence of object`.

**Comment by SunSerega** [comment]
А, стоп, я упустил очень важный момент:
```
procedure p1(s: sequence of object) :=
writeln('sequence');

procedure p1(s: object) :=
writeln('object');

begin
  p1(object(nil));
end.
```
Тут тоже выбирается подпрограмма для `object`, то есть дело не в типе `nil`.

**Comment by miks1965** [comment]
Здесь правильно - здесь точное соответствие типа.

А с nil - не придумывайте новые правила. Выбирается более специализированная версия. Ну, должна выбираться.

**Comment by miks1965** [comment]
Еще раз посмотрел изначальный пример. Всё правильно. Из sequence of T и T выбирается sequence of T потому что она имеет ссылочный тип. А T может иметь размерный

Поэтому если не предложите другой неработающий пример, - закрою

**Comment by SunSerega** [comment]
> А T может иметь размерный

Но ведь уже известно, что `T` будет заменён на `object`.

**Comment by miks1965** [comment]
Перегрузке
```
operator+=<T>(var Self: HashSet<T>; x: T): HashSet<T>
```
это неизвестно. Там нет ограничений на T.

Закрываю Issue
