### ISSUE TITLE
Последний ползунок вкладок "Локальные переменные" и "Просмотр выражений" не двигается

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#1472]
Чтоб появились эти вкладки в IDE - запустите отладку.

[bandicam 2018-11-07 14-23-17-496.zip](https://github.com/pascalabcnet/pascalabcnet/files/2557386/bandicam.2018-11-07.14-23-17-496.zip)

**Comment by ibond84** [comment]
А можно прямую ссылку на видео?

**Comment by SunSerega** [comment]
Не даёт на гитхаб загрузить. Сейчас на ютуб попробую.

**Comment by SunSerega** [comment]
https://www.youtube.com/watch?v=ndnP3Xv_MjI&feature=youtu.be

**Comment by ibond84** [comment]
Ну это особенность DataGridView. Средняя колонка имеет AutoSizeMode Fill. А это фиксирует последнюю колонку. Без Fill не получится выставить ширины колонок. Закрываю

**Comment by SunSerega** [comment]
А почему тогда остальные ползунки работают? И - в чём проблема убрать авто вычисление размера и выставлять что то вручную, как половина ширины экрана?

**Comment by ibond84** [comment]
Ну если есть желание, можете поэкспериментировать с настройками грида здесь

https://github.com/pascalabcnet/pascalabcnet/blob/master/VisualPascalABCNET/DockContent/DebugVariablesListWindowForm.cs

И прислать пулл-реквест.. :)

**Comment by SunSerega** [comment]
Напомните, какой батник там запускать чтоб построить билд?
