### ISSUE TITLE
Рекурсивный вызов функции в if всегда считает бесконечной рекурсией

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#1475]
```
function f1(bl: object): boolean;
begin
  if bl is byte then
    if f1(nil) then
end;

begin end.
```
При чём этот код:
```
function f1(bl: object): boolean;
begin
  if bl is byte then
    f1(nil)
end;

begin end.
```
Не даёт предупреждения о бесконечной рекурсии

**Comment by miks1965** [comment]
А если изменить сообщение об ошибке на "Возможна бесконечная рекурсия" ?

**Comment by SunSerega** [comment]
Зачем закрывать то? Я же говорю, сообщение пропадает или появляется, в зависимости от того - находится ли вызов в `if`. Посмотрите внимательно:
```
function f1(bl: object): boolean;
begin
  if bl is byte then
  begin
    if f1(nil) then
  end;
end;

function f2(bl: object): boolean;
begin
  if bl is byte then
  begin
    var flag := f1(nil);
    if flag then
  end;
end;

begin end.
```
Эти 2 функции генерируют абсолютно идентичный IL код, но предупреждение бросается только для первой.

**Comment by miks1965** [comment]
Ну, надо бросать и для второй.

Насколько я понимаю, этот анализ не очень точный и даёт много ложных срабатываний. 
Поэтому если сообщение об ошибке будет более мягким и выдаваться не всегда, - считаю, это решит ситуацию.

Если это кому-то не нравится, есть путь оставить всё как есть либо же вообще не выдавать это предупреждение.

**Comment by SunSerega** [comment]
>Ну, надо бросать и для второй.

Нет, из за проверки `if bl is byte then` - не надо. Всегда если рекурсивный вызов находится в блоке начинающемся с `if` - это предупреждение не бросается.

Вот к примеру:
```
procedure p1;
begin
  if ReadBoolean then
    p1;
end;

begin end.
```
Тут предупреждение не бросается, потому что вызов происходит не обязательно. Поэтому и в случае с `f1`/`f2` предупреждения нужно убрать.

**Comment by miks1965** [comment]
Подумать о том, чтобы вообще убрать это предупреждение. Много ложных срабатываний, причем, в схожих ситуациях они то выводятся то нет.

Вообще, на этапе статического анализа кода это если не гиблая, то весьма сложная задача.

**Comment by SunSerega** [comment]
> Вообще, на этапе статического анализа кода это если не гиблая, то весьма сложная задача.

Пожалуй, соглашусь. Изменить заголовок issue?

**Comment by miks1965** [comment]
Это решение может принимать только ibond. Пусть всё остаётся как есть - он увидит

**Comment by ibond84** [comment]
Убрал все предупреждения про бесконечную рекурсию. Желания еще и эту ерунду фиксить нет никакого.
