### ISSUE TITLE
Подсветка class-end при установке курсора на end сломалась

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#1476]
```
type
  t1=class
    
  end;

begin end.
```
Если поставить курсор на class - подсвечивается и class и end. А если поставить на end - ничего не подсвечивается.

Ещё недавно это работало.

**Comment by miks1965** [comment]
А точно работало?

**Comment by SunSerega** [comment]
Точно, я этим часто пользовался чтоб находить начало класса, когда их много и больших.

**Comment by ibond84** [comment]
Да оно никогда не работало. И правильно, что не работает. Знак равно надо разделять пробелами :)

**Comment by SunSerega** [comment]
А, понятно, то есть оно не работает из за того что `=` написано слитно с `class`... То то смотрю - странно это, с чего бы оно сломалось вдруг...

**Comment by miks1965** [comment]
:))
