### ISSUE TITLE
В проектах при создании нового файла выбор между неймспейсом и модулем происходит по наведении курсора

### ISSUE THREAD

**Issue by AIexandrKotov** [pascalabcnet/pascalabcnet#1481]
1) Создаём новый проект
2) Кликаем ПКМ по названию проекта -> добавить -> новый файл
3) Наводим курсор на "Модуль" или "Пространство имён"

Для выбора используется не клик ЛКМ (вернее он используется, но в паре с наведением), а наведение курсора

**Comment by miks1965** [comment]
Не отвлекайте пожалуйста разработчиков несущественными пожеланиями. Настоятельно просим.

**Comment by MrFresnel** [comment]
> Не отвлекайте пожалуйста разработчиков несущественными пожеланиями. Настоятельно просим.

Несущественность пожелания не означает его ненужность.
