### ISSUE TITLE
Если в проектах создать неймспейс, то он получает имя проекта

### ISSUE THREAD

**Issue by AIexandrKotov** [pascalabcnet/pascalabcnet#1482]
Проблема ясна из названия.

**Comment by ibond84** [comment]
Ну правильно, это же не модуль, чтобы получать имя файла. Пространства имен сквозные, иначе смысла в них никакого нет.

**Comment by SunSerega** [comment]
А разве они компилируются если их имя получает что то кроме имени файла?

**Comment by ibond84** [comment]
Конечно, компилируется. Ради чего все это и городилось. Чтоб не совать все классы в один модуль-файл.

**Comment by AIexandrKotov** [comment]
@ibond84, а если проект имеет в своём имени пробел? Ничего тогда не скомпилируется.
