### ISSUE TITLE
Конструктор ссылается на метаданные string, если использовать в нём ?:

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#1485]
```
type
  t1=class
    constructor(i: byte) := exit;
  end;

begin
  new t1(true?0:1);
end.
```
Зажмите Ctrl и нажмите на `t1`  на строчке `new t1(...`.
Откроется окно метаданных для строки, вместо того чтоб переставить курсор к конструктору `t1`.

**Comment by ibond84** [comment]
Все из-за дурацкого Nullable.
