### ISSUE TITLE
Позволить использовать default без скобок для указания значения по умолчанию для заранее известного типа T

### ISSUE THREAD

**Issue by MrFresnel** [pascalabcnet/pascalabcnet#1490]
```
type
  TName<T> = class
    fX: T := default; // А не default(T);
  end;

begin
end.
```
Это позволит сокращать код и не писать default(T), если ясно о значении по умолчанию какого типа идёт речь.

**Comment by miks1965** [comment]
Пожалуйста, не отвлекайте разработчиков мелочными ненужными идеями о расширении языка.

**Comment by MrFresnel** [comment]
> Пожалуйста, не отвлекайте разработчиков мелочными ненужными идеями о расширении языка.

 Пожалуйста, обосновывайте закрытие Issue.
