### ISSUE TITLE
Позволить использовать распаковку кортежа при объявлении полей класса или записи

### ISSUE THREAD

**Issue by MrFresnel** [pascalabcnet/pascalabcnet#1492]
```
type
  TName = class
    (fX, fY) := (1, 2); // Объявил два поля, причём fX = 1, fY = 2.
  end;

begin
end.
```
Это позволит сокращать код, а также логически группировать поля и подчёркивать их связность.

**Comment by miks1965** [comment]
Пожалуйста, не отвлекайте разработчиков мелочными ненужными и неоднозначно трактуемыми идеями о расширении языка.

**Comment by MrFresnel** [comment]
> Пожалуйста, не отвлекайте разработчиков мелочными ненужными и неоднозначно трактуемыми идеями о расширении языка.

Пожалуйста, обосновывайте закрытие Issue.
