### ISSUE TITLE
Позволить использовать суффиксы для указания типа литерала

### ISSUE THREAD

**Issue by MrFresnel** [pascalabcnet/pascalabcnet#1494]
```
namespace CSrharpApplicationTest
{
    class Program
    {
        static void Main(string[] args)
        {
            float x = 2.0f; // Суффикс f.
        }
    }
}
```
[Здесь](https://docs.microsoft.com/ru-ru/dotnet/csharp/language-reference/keywords/value-types) в подразделах можно о суффиксах почитать. В PascalABC.Net это выглядело бы примерно так:
```
begin
  var x := 2.0f;
end.
```

**Comment by miks1965** [comment]
Пожалуйста, не отвлекайте разработчиков мелочными ненужными идеями о расширении языка.

В Delphi такого нет. Bcgjkmpeqnt zdyjt ghbdtltybt nbgf/

**Comment by MrFresnel** [comment]
> В Delphi такого нет. Используйте явное приведение типа.

И что? Теперь только на него ориентироваться что ли?

**Comment by AlexRnD61** [comment]
C# никогда и не был аргументом у разработчиков - они создали диалект другого языка. Если что, он называется Pascal, а не C#. А C# - это лишь для Вас аргумент. Ну и нескольких сочувствующих.

**Comment by MrFresnel** [comment]
> А C# - это лишь для Вас аргумент. 

Считайте как хотите. Это лишь Ваша точка зрения.
