### ISSUE TITLE
Неправильная ошибка в is/as для предописания класса

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#1495]
```
type
  t2=class;
  
  t1=class
    constructor;
    begin
      writeln(self is t2);//Ошибка: Ожидался класс-потомок или класс-предок
    end;
  end;
  t2=class(t1) end;

begin end.
```
Та ошибка сейчас - только запутывает.
Надо писать что то типа "нельзя выполнить is/as для класса до его описания".

Ну или реализовать это, если возможно.

**Comment by miks1965** [comment]
Сообщение об ошибке правильное. Никто не может определить, что хочет написать программист в будущем

**Comment by SunSerega** [comment]
Я и не говорил определять это. Я говорил про то чтоб сделать ошибку которая не запутывает программиста.

**Comment by miks1965** [comment]
На мой взгляд, ошибка не запутывает, а как раз говорит о проблеме. Программист прекрасно понимает, в чём проблема. И может её решить, разместив код не в интерфейсе класса.

**Comment by SunSerega** [comment]
Конечно, когда объявления t1 и t2 находятся на экране одновременно - всё понятно.

Но вот у меня соответствующие классы были разнесены на несколько сотен строк, поэтому это уже не так интуитивно.

**Comment by miks1965** [comment]
Это как правило признак плохого проектирования. Если есть предописание класса, то единственная операция, которая имеет смысл, - это описать переменную этого класса.

Технически для нас сложно сделать то, о чем Вы говорите - у нас во внутреннем представлении нет различия между предописанием и описанием класса. Класс пополняется методами и информацией о предках по мере их появления.
