### ISSUE TITLE
Провести рефакторинг подсистемы ошибок по всему проекту

### ISSUE THREAD

**Issue by miks1965** [pascalabcnet/pascalabcnet#1505]
Подсистем ошибок писалась в разное время и содержит множество несуразностей. Их необходимо устранять.

**Issue, помеченные меткой "refactoring", могут писать и комментировать только разработчики.**

**Comment by miks1965** [comment]
В парсере и сканере добавление ошибки выполняется с помощью `parsertools.AddErrorFromResource`

**Comment by ibond84** [comment]
Ну метод AddError это официальный метод в семантике. Там просто throw (которых полно в generic.cs) надо заменить на вызов AddError()

> Пока из этого можно сделать вывод, что бросать исключение - правильная затея (поскольку мы ищем первую ошибку), а помещать ошибку в список надо только избранных случаях когда перебираются потенциально неправильные версии функций (при выборе перегруженной версии и инстанцировании функции по вызову). Но это лишь догадка.

да, исключения крайне медленные (что заметно на лямбдах), поэтому иногда надо просто возвратить null

bad_node это вообще по сути ерунда и не нужен. парсер вообще не строит дерево, если программа неправильная.

**Comment by miks1965** [comment]
#2403
