### ISSUE TITLE
В is-var ссылка на функцию имеет больший приоритет чем её вызов

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#1506]
```
type
  t1=class end;
  t2=class(t1) end;

function f1 := new t1;

begin
  if f1 is t2(var a) then//Ошибка:  Выражение типа function: t1 не может быть сопоставлено с образцом типа t2
end.
```

**Comment by VanillaFlame** [comment]
Мне кажется это вполне правильное поведение, ведь
`if f1() is t2(var a) then`
работает без ошибок в этом случае, а без скобочек у f1 матчит ссылку на функцию, что достаточно логично.

**Comment by SunSerega** [comment]
В паскале вызов функции имеет больший приоритет чем получение ссылки на неё.
Получение ссылки происходит только в случаях когда ну совсем никак вызвать не получится, или тип результата не подходит.

**Comment by miks1965** [comment]
В выражениях у нас f1 - это вызов. Исключения - сравнение f1 с nil и использование f1 для инициализации процедурной переменной
