### ISSUE TITLE
Повторно объявленный идентификатор при 2 is-var вне if, с одинаковыми именами переменных

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#1510]
```
begin
  var o := new object;
  var b: boolean;
  
  b := o is byte(var i);
  b := o is word(var i);//Ошибка: Повторно объявленный идентификатор i
  
end.
```
Это очень похоже на #1413. Но тут не нужен `yield`.

**Comment by ibond84** [comment]
А в чем ошибка, если оказывается i добавляется в область видимости begin-end??
Что мне крайне не нравится, ибо я считаю, что такие конструкции допустимы только в if и while. И только там им и место

**Comment by ibond84** [comment]
И опять нагрузка на интеллисенс, который должен проходить все выражения в поисках этих var i

**Comment by SunSerega** [comment]
По моему, `i` тут не должно добавляться в области видимости `begin-end`, потому что тогда получается что она может быть не инициализирована. Такой код нужен только в данном виде:
```
begin
  var o := new object;
  var b: boolean;
  
  b := (o is byte(var i)) and (i > 5);
  
end.
```
Если надо чтоб i появилось в области видимости - это выражение должно быть в `if`. Потому что нет смысла присваивать ещё переменной `b`.

А в примере из заголовка - я упростил до минимума вызывающего ошибку. Но та запись бесполезна.

**Comment by ibond84** [comment]
Да ну? Такое компилируется

`
begin
  var o := new object;
  var b: boolean;
  
  b := o is byte(var i);
  writeln(i);
  
end.
`

**Comment by ibond84** [comment]
о, сразу видно, майкрософт купил гитхаб. теги для кода неправильно добавляются..
```
begin
var o := new object;
var b: boolean;

b := o is byte(var i);
writeln(i);

end.
```

**Comment by SunSerega** [comment]
Да, сейчас работает, но это ведь неправильно... Я же говорю, это работает только если использовать переменную только на строчке с объявлением, типа добавить ещё условия...

**Comment by miks1965** [comment]
Закрываю Issue.

Переменная i описывается второй раз - ровно это выводится в ошибке.
