### ISSUE TITLE
" ':=' не применима к типу function " при yield для указателя на функцию

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#1511]
```
type
  t1 = class
    function f0(b:byte):=0;
    function f1: sequence of object;
    begin
      yield f0;//Ошибка: Операция ':=' не применима к типу function(b: byte): integer 
    end;
  end;

begin end.
```
Присвоение можно применять к типу функции, поэтому ошибка, как минимум, неправильная.

**Comment by SunSerega** [comment]
Но вообще так работает:
```
function f1(b: byte) := b;

begin
  
  var o1: object;
  o1 := f1;//ok
  
end.
```
Поэтому и код из заголовка issue должен компилироваться.

**Comment by SunSerega** [comment]
Нет не будет. Не хватает параметров для вызова. Если у функции не будут нужны параметры - всё работает нормально.

**Comment by miks1965** [comment]
#1439 - дубль

**Comment by miks1965** [comment]
Проблема в том, что нельзя делать это:
```
cfr.field.type = from.type;
```
если from - имя метода

**Comment by miks1965** [comment]
Само пофиксилось

**Comment by SunSerega** [comment]
Стоит в таких случаях писать в названии коммита так:
```
bug fix #1439
and fix #1511
```
Тогда бы и #1511 автоматом закрыло.

**Comment by miks1965** [comment]
Ага, спасибо
