### ISSUE TITLE
IDE ломается если быстро нажать Ctrl + (A, BackSpace)

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#1518]
https://youtu.be/B6K2fn95oF8

Что я делал:

1. Набрал `be` и нажал `Shift`+`Space`.
2. Быстро нажал `Ctrl`+`A` и сразу `BackSpace`.

Чтоб воспроизвести это в нормальных условиях - надо очень быстро умудрится выполнить п.2 . Но у меня лагало IDE в момент когда я получил это первый раз, поэтому воспроизвелось хотя я делал всё не так быстро как на видео.

**Comment by miks1965** [comment]
Не воспроизводится

**Comment by miks1965** [comment]
Давайте так - я выложу Debug-версию, а Вы позапускаете и скажете номер строки, в которой это происходит

**Comment by SunSerega** [comment]
Давайте

**Comment by miks1965** [comment]
http://pascalabc.net/downloads/w1.zip

**Comment by miks1965** [comment]
И как - есть ошибка?

**Comment by SunSerega** [comment]
Я ещё не тестировал, я пока компилятор SAC дебажу, не могу IDE вырубить...

**Comment by miks1965** [comment]
Там можно просто распаковать и запустить на вашей машине

**Comment by SunSerega** [comment]
Кхм, чёт не пишет строчку, только стек вызовов:
```
System.ArgumentOutOfRangeException: index should be between 0 and 0
Имя параметра: index
Фактическое значение было 2.
   в ICSharpCode.TextEditor.Document.LineSegmentTree.GetNode(Int32 index)
   в ICSharpCode.TextEditor.Document.DefaultDocument.GetLineSegment(Int32 line)
   в ICSharpCode.TextEditor.TextView.CountColumns(Int32& column, Int32 start, Int32 end, Int32 logicalLine, Graphics g)
   в ICSharpCode.TextEditor.TextView.GetDrawingXPos(Int32 logicalLine, Int32 logicalColumn)
   в ICSharpCode.TextEditor.TextArea.SetDesiredColumn()
   в ICSharpCode.TextEditor.Actions.WordBackspace.Execute(TextArea textArea)
   в ICSharpCode.TextEditor.TextArea.ExecuteDialogKey(Keys keyData)
   в ICSharpCode.TextEditor.TextArea.ProcessDialogKey(Keys keyData)
   в System.Windows.Forms.Control.PreProcessMessage(Message& msg)
   в System.Windows.Forms.Control.PreProcessControlMessageInternal(Control target, Message& msg)
   в System.Windows.Forms.Application.ThreadContext.PreTranslateMessage(MSG& msg)
```

**Comment by SunSerega** [comment]
Я тут потестил пытаясь воспроизвести с SAC (чтоб вы могли автоматично воспроизводить, и не надо было быстро тыкать)... И понял как легче воспроизвести:

1. Набрать `begin-end.` как раньше, тут ничего не поменялось
2. Нажать на Ctrl
3. Нажать A
4. Нажать бекспейс (напомню, Ctrl мы ещё не отжимали)
5. Вуаля, вот и ошибка

Вот код для SAC если всё же надо:
```
KeyP KeyCode("B")
KeyP KeyCode("E")

Sleep 500

KeyD KeyCode("LShift")
KeyP KeyCode("SpaceBar")
KeyU KeyCode("LShift")

Sleep 500

KeyD KeyCode("LCtrl")
KeyP KeyCode("A")
KeyP 8 //BackSpace
KeyU KeyCode("LCtrl")
```
