### ISSUE TITLE
case в лямбде ломает анализатор кода

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#1523]
```
function f1<T>(self: sequence of T; f: T->()): sequence of T; extensionmethod := self;

begin
  Arr(0)
  .f1(i->case i of end)
end.
```
Точка не работает после `f1`.

**Comment by miks1965** [comment]
После f1 нет точки

**Comment by SunSerega** [comment]
Если поставить точку без чего то дальше - анализатор кода вообще не загрузится.
Поставьте точку для результата `f1` в котором `case` - окно подсказки не появится. И если написать что то после точки - наведение тоже не работает:
```
function f1<T>(self: sequence of T; f: T->()): sequence of T; extensionmethod := self;

begin
  Arr(0)
  .f1(i->case i of end)
  .Print//тут анализатор кода не видит Print
end.
```

**Comment by SunSerega** [comment]
@AIexandrKotov протестил последний билд - проблема не исправлена.

**Comment by ibond84** [comment]
Не знаю, что там за билд. Но в мастере всe исправлено.

**Comment by SunSerega** [comment]
Странно... Билд создавался запуском `_ReBuildRelease.bat` а затем `ReleaseGenerators\PascalABCNET_ALL.bat`, это неправильно?
Особо странно потому, что #1521 в полученном билде всё же было исправлено.
