### ISSUE TITLE
Компилятор не может получить рефлексию перечислимого типа из WMPLib.dll, но только в лямбде

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#1524]
[0.zip](https://github.com/pascalabcnet/pascalabcnet/files/2612435/0.zip)

```
{$reference wmplib.dll}

begin
  
  var p: procedure := ()->
  begin
    var t := typeof(WMPLib.WMPPlayState);//Ошибка: В данной версии компилятора не поддерживается замыкание данного типа символов
  end;
  
end.
```

**Comment by MrFresnel** [comment]
Рефлек**ц**ию?

**Comment by SunSerega** [comment]
`System.Reflection`
Ну правда тип `System.Type`, но он всё равно наследник `System.Reflection.MemberInfo`. А в `System` он только потому - что чаще нужен.

**Comment by MrFresnel** [comment]
Исправьте заголовок.

**Comment by SunSerega** [comment]
РефлексИя (от слова рефлекС) это медицинский термин. На него авто-исправляет только потому что он давно существует, а рефлЕкция (от слова reflect) это что то вроде экстенш-метод, то есть английское слово русскими буквами.
