### ISSUE TITLE
Убрать подсветку для ключевого слова template

### ISSUE THREAD

**Issue by MrFresnel** [pascalabcnet/pascalabcnet#1529]

**Comment by SunSerega** [comment]
Да и вообще зачем оно в ключевых словах, оно ничего не делает, но так запрещено:
```
begin
  var template: byte;
end.
```

**Comment by ibond84** [comment]
Не надо убирать, так как это ключевое слово. Зачем для него какие-то исключения делать

**Comment by SunSerega** [comment]
А где оно используется?

**Comment by ibond84** [comment]
Это что-то вроде шаблонов C++. Недокументированная экспериментальная фича, разрабатывавшаяся 10 лет назад еще до генериков.

**Comment by SunSerega** [comment]
Да, я на C++ программировал и знаю. Но в паскале то оно к чему? Весь функционал реализован C#-овскими шаблонами. Ну кроме шаблонов-переменных...

**Comment by MrFresnel** [comment]
> Это что-то вроде шаблонов C++.

Можете пример показать?
