### ISSUE TITLE
Intellisense неверно выводит Random

### ISSUE THREAD

**Issue by miks1965** [pascalabcnet/pascalabcnet#153]
```
uses System;

begin
  var r := Random(10);  
end.
```

**Comment by ibond84** [comment]
Не, это в компиляторе ошибка. :) Если в списке имен есть методы, то вызов функции должен иметь приоритет перед преобразованием типа.

**Comment by miks1965** [comment]
А вот при открытии скобки по-прежнему показываются функции Random из системного модуля, сбивая нестойких форумчан :)

**Comment by ibond84** [comment]
Форумчане вообще-то должны соображать, что пишут. Если пишет скобку, значит хочет функцию, вот пусть его получает... :)
