### ISSUE TITLE
Ошибка при результате лямбды-функции в try-except-end, у которого не хватает ;

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#1533]
```
procedure p1(f: real-> real) := exit;

begin
  
  p1(r ->
  begin//Ошибка: Нельзя преобразовать тип procedure(: ) к Func<real,real>
    try
      Result := r;
    except
    end
  end);
  
end.
```
При чём позиция ошибки неправильная (сдвинута на строчку ниже).

Если добавить точку с запятой после `except-end` - ошибки нет.

**Comment by miks1965** [comment]
А давайте разберемся, когда лямбду считать процдурой, а когда функцией.
Например, здесь:
```
var f: real-> real := r ->
  begin
    try
      Result := r;
    except
    end
  end;

begin  
end.
```
Program1.pas(4) : Неизвестное имя 'Result'

**Comment by miks1965** [comment]
Тогда варианты:
```
r->begin var x := Result end;
```
и 
```
r->begin var Result := r end;
```

**Comment by SunSerega** [comment]
`var Result` запретить - так же как в обычных функциях нельзя объявить переменную `Result`.

`:= Result` - если `Result` не нигде является lvalue (и не передаётся как var-параметр) - это процедура, и тут надо выдавать неизвестное имя или что то типа того.

**Comment by miks1965** [comment]
Там не всё так просто.

```
procedure p(x) -> begin var Result := 1; end;
```
можно.

И глупо считать функцией то, у чего Result только в правой части присваивания

**Comment by SunSerega** [comment]
```
procedure p(x) -> begin var Result := 1; end;
```
Да, потому что вы указали явно что это процедура. Это всё касается только лямбд которые не понятно чем должны оказаться.

>глупо считать функцией то, у чего Result только в правой части присваивания

Да так и сказал:

>если Result не нигде является **L**value (и не передаётся как var-параметр) - это процедура

```
var p: procedure := ()->Inc(Result);
```
Тут нет `begin-end`, вы только недавно запретили это.

**Comment by miks1965** [comment]
Тут конечно Вы неправы. 

В C# ну и вообще при выводе типов в подобных случаях используется схема обратного вывода типов параметров и возвращаемого значения лямбды по типу переменной, которую она инициализирует.

То есть, в ситуации 
```
var f: integer->integer := x->x;
```
типы x выводятся по типу f. 

В данном случае тип p - процедура, и лямбда должна быть процедурой. То есть, код 
```
var p: ()->integer := ()->begin Inc(Result); end;
```
не должен компилироваться, что и происходит.

Ровно то же происходит и в C#
```
Action<int> f = x=> { return x };
```

**Comment by miks1965** [comment]
Это всё сильно усложняет алгоритм. Беда в том, что на том уровне, где принимается решение, - функция это или процедура, - это уровень синтаксиса. У нас по крайней мере так. То есть, можно просмотреть тело и увидеть там несколько result, но сказать, что такое Inc, ещё нельзя. А функцию или процедуру уже надо сгенерировать. Поэтому выводить по var параметрам то, функция это или процедура, не получится. Может потому мягко и посылаю.

Нужно более простое правило - возможно менее точное, чем в C#, но простое, которое позволило бы сразу сказать, функция это или процедура. А потом уж вывелось или нет - это другой вопрос.

Так вот. Всё-таки неявным критерием того, что это - функция, является то, что мы переменной Result присваиваем некоторое значение в блоке begin-end. Если это отдельный оператор, то я бы запретил использование в нем Result вообще, оставив его для лямбд-процедур.

**Comment by SunSerega** [comment]
>Если это отдельный оператор, то я бы запретил использование в нем Result вообще, оставив его для лямбд-процедур.

А это зачем?

**Comment by miks1965** [comment]
Интуитивно x->выражение это функция, а x->оператор - процедура. 

В редких случаях надо делать сложную функцию более чем из одного выражения - и тогда надо писать begin-end и внутри можно использовать result. Если переменной Result не присваивается значение, то это выглядит как ошибка.

Это - простые правила.

Можно с ними спорить, но они простые.

Их легко прописать в справке.

В любом случае знающий их легко напишет нужную функцию или процедуру.

Усложнение этих правил приводит к спорным моментам - всё равно найдутся несогласные и будет интуитивно непонятно большему кругу людей.

**Comment by SunSerega** [comment]
Вы смотрите на это со стороны как оно выглядит во внутренних структурах компилятора.

А со стороны юзвера - более интуитивно "если без begin-end; или есть Result - значит функция".
При этом "если Result в основном блоке - считается, а если он в ещё 1 засунут - уже нет" это лишнее усложнение.

**Comment by miks1965** [comment]
Не совсем так. Я смотрю на то, как это реализовать без ошибок и не внося излишнюю сложность.

Я согласен с тем, что можно попробовать Result := писать не в основном блоке, а во вложенном. Первое вхождение тут всегда можно найти. У нас по первому вхождению Result := expr вычисляется тип Result. Но считать конструкцию x->begin Inc(Result) end; функцией я отказываюсь. По двум причинам. Интитивно это уже не очень похоже на функцию. Особенно когда вместо Inc стоит непонятно что. Во-вторых, мы это всё равно не выведем, и ошибка будет дальше. Теперь вопрос - зачем тратить год на изменение сложного алгоритма вывода типов в лямбдах если всё равно будет ошибка.

**Comment by SunSerega** [comment]
Да, это я понял что по `var`-параметрам не получится вычислять. Но `Inc` это же не оператор. А вы сказали именно

>Если это отдельный оператор

**Comment by SunSerega** [comment]
Ну ладно, в общем решение есть.

А насчёт 2 видов операторов - я бы называл операторы те что 1 строчка с какой то командой, типо присвоения переменной и вызова процедуры - стейтменом, а вот сами `:=`, `+=`, и т.п. - операторами. Так же и в англ. и при их перегрузке - пишется `operator+=`.

**Comment by miks1965** [comment]
Называйте )
В русской литературе есть устоявшиеся варианты перевода.
