### ISSUE TITLE
Не подставляет имя и тип параметров, лямбды не правильного типа, в текст ошибки

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#1534]
```
procedure p1(f: real-> real) := exit;

begin
  
  p1(r ->//Ошибка: Нельзя преобразовать тип procedure(: ) к Func<real,real>
  begin
  end);
  
end.
```
Получили/Ожидали:
`Нельзя преобразовать тип procedure(: ) к Func<real,real>`
`Нельзя преобразовать тип procedure(r: real) к Func<real,real>`

**Comment by miks1965** [comment]
Тут всё верно. Компилятор видит, что в теле лямбды нет Result и считает её процедурой. А у Вас функция.

**Comment by SunSerega** [comment]
Да, я не говорил что это должно компилироваться. Я говорил про текст ошибки. Прочитайте внимательно.

**Comment by miks1965** [comment]
Ну, я тоже согласен с ошибкой. Компилятор принципиально считает это процедурой и даже не приступает к выводу типов, поскольку это - сложный алгоритм и он рассчитан на правильные программы.

**Comment by SunSerega** [comment]
Но типы ведь уже выведены. Они известны из контекста лямбды. И имя переменной тоже.
И если вы их не подставляете - зачем ставить двоеточие и пробел? Это больше похоже на то что там $'{var_name}: {var_type}', но `var_name` и `var_type` оказываются `nil`.

**Comment by miks1965** [comment]
Типы не выведены - ещё раз говорю. Потому что может быть несколько перегруженных версий p. 

Двоеточие по крайней мере указывает что это процедура с одним параметром.

**Comment by SunSerega** [comment]
Если параметров несколько - двоеточие всё равно одно.

**Comment by MrFresnel** [comment]
> Типы не выведены - ещё раз говорю.

В этом случае лучше было бы:

> Нельзя преобразовать тип procedure(x: T) к Func<real,real>

**Comment by SunSerega** [comment]
>подставлять x1, x2

Лучше по аналогии с тем что уже есть:
![image](https://user-images.githubusercontent.com/27270190/49066552-24845280-f22a-11e8-93f0-837237a75b7d.png)

**Comment by miks1965** [comment]
Я склонен закрыть этот Issue.

Дело в том, что тип тип procedure(r: real) нельзя вывести. Там параметром функция, и компилятор даже не пытается её сопоставлять. И тип процедуры остаётся неизвестным. Точнее, тип параметра процедуры. То есть, тип procedure(: ) считаю самым адекватным. Внутри там - procedure(#Item1: #any_type)

**Comment by SunSerega** [comment]
В таком случае давайте писать `procedure(...)`, двоеточие не интуитивно выглядит, а троеточие сразу даст понять что там какие то параметры, но не понятно какие.

**Comment by SunSerega** [comment]
Но вообще, всё же посмотрите, будет ли там несколько параметров для такого кода:
```
procedure p1(f: (real, real) -> real) := exit;

begin
  
  p1((r1,r2) ->//Ошибка: Нельзя преобразовать тип procedure(: ) к Func<real,real>
  begin
  end);
  
end.
```
Если для него будет такое:
```
procedure(#Item1: #any_type, #Item2: #any_type)
```
То должно быть не сложно сделать чтоб выводило:
```
procedure(arg1: T1, arg2: T2)
```

**Comment by miks1965** [comment]
Тогда Вы первый будете кричать, что имена T1 T2 arg1 arg2 могут перекрывать уже существующие имена, а если они и впрямь будут перекрывать...

**Comment by SunSerega** [comment]
Нет, не буду)))
А `arg1` и т.д. я уже писал выше, их уже в другом месте показывает:
![image](https://user-images.githubusercontent.com/27270190/50180517-7c3a4900-0312-11e9-818d-68af6515fd92.png)

**Comment by miks1965** [comment]
Ну, Вы не будете - другой кто-то будет. Дело вкуса знаете ли

**Comment by miks1965** [comment]
Тут другое дело - типы выведены, а имена не важны.

Можно конечно так: procedure (arg1: ?; arg2: ?)

**Comment by SunSerega** [comment]
Выглядит не плохо.

**Comment by ibond84** [comment]
Щас вроде нормальное сообщение об ошибке выводится
```
Нельзя преобразовать тип procedure(_: λ_anytype) к Func<real,real>
```
Закрываю
