### ISSUE TITLE
Попытаться разрешить указывать шаблонные параметры подпрограмм и методов без &

### ISSUE THREAD

**Issue by MrFresnel** [pascalabcnet/pascalabcnet#1540]
Попытаться разрешить указывать шаблонные параметры подпрограмм и методов без &:

```
procedure P<T>() := exit;

begin
   P<byte>(); // Вместо P&<byte>();
end.
```

Предлагаю оставить до поры до времени. Пусть эта Issue будет напоминанием об этом.

**Comment by miks1965** [comment]
Проблему знаем. Мы бы рады. Но это - только - замена парсера на ручной. Это всё равно как переписать компилятор.

Вот - основняя проблема:
```
begin
  var a,b,c: boolean;
  var x := a<b>(c);
  Print(x);
end.
```
Это работает. Если допустить обобщенные параметры подпрограмм без &, то будет неустранимый конфликт в грамматике.

Проблема - из учебников по компиляторам. Только ручной парсинг. В C# - именно такой.

**Comment by SunSerega** [comment]
Я просматриваю коммиты, и, вроде, @ibond84 для фикса 1 из issue сделал так - что если компиляция не прошла как есть - перед `<` добавляется `&` и перекомпилируется. Конечно, костыль, но наверное всё же лучше чем если вообще не работает...

**Comment by miks1965** [comment]
Нет, так делать нельзя, это какой-то жуткий способ, дестабилизирующий компилятор, и всё равно не решающий проблему. А что за фикс - я не понял?

**Comment by ibond84** [comment]
Ну то для парсинга выражений в интеллисенсе. Там это делается, чтобы пропарсивался код
```
List<integer>
```

**Comment by miks1965** [comment]
Чудес не бывает))
