### ISSUE TITLE
Внутренняя ошибка при циклическом наследовании интерфейсов

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#1541]
```
type
  I1<T> = interface;
  I2<T> = interface;
  
  I1<T> = interface(I2<T>)
    
  end;
  
  I2<T> = interface(I1<T>)
    
  end;
  
begin end.
```
```
() : Внутренняя ошибка компилятора в модуле [pabcnetc.exe] :'System.Exception: System.TypeLoadException: Не удалось загрузить тип "Program1.I1`1" из сборки "Program1, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null".
   в System.Reflection.Emit.TypeBuilder.TermCreateClass(RuntimeModule module, Int32 tk, ObjectHandleOnStack type)
   в System.Reflection.Emit.TypeBuilder.CreateTypeNoLock()
   в System.Reflection.Emit.TypeBuilder.CreateType()
   в PascalABCCompiler.NETGenerator.ILConverter.CloseTypes()
   в PascalABCCompiler.NETGenerator.ILConverter.ConvertFromTree(IProgramNode p, String TargetFileName, String SourceFileName, CompilerOptions options, String[] ResourceFiles)
   в PascalABCCompiler.Compiler.Compile()'
```

**Comment by MrFresnel** [comment]
Обязательно обобщённые интерфейсы?

**Comment by SunSerega** [comment]
Ну, для классов не вылетает:
```
type
  t1<T> = class;
  t2<T> = class;
  
  t1<T> = class(t2<T>)
    
  end;
  
  t2<T> = class(t1<T>)
    
  end;
  
begin end.
```
Но выдаёт странную ошибку:
`Конструктор по умолчанию в базовом классе t2<T> не найден`

Ну, это должно исправится после того как запретят циклические наследование.

**Comment by ibond84** [comment]
Ничего не падает

**Comment by SunSerega** [comment]
У меня падает:

![image](https://user-images.githubusercontent.com/27270190/49701547-86fc2c00-fbf6-11e8-94e0-bee1e7b068ea.png)

Билд 1889.

**Comment by SunSerega** [comment]
Ну и? Исправлять то будете?

**Comment by ibond84** [comment]
Ну, для начала соберите у себя проект и посмотрите, воспроизводится ли ошибка. Что там не работает в релизе двухнеделельной давности, меня не интересует.

**Comment by SunSerega** [comment]
Вообще он был 5 дней назад... Но ладно, сейчас соберу.

**Comment by SunSerega** [comment]
Ну да, не вылетает... В обычном понимании:

![image](https://user-images.githubusercontent.com/27270190/49835416-ca49cc80-fda7-11e8-84df-3ddc56776e2d.png)

То есть теперь ломается вся IDE, вместо того чтоб показать ошибку. (откомпилировать ничего после этого не даёт)

И всё равно, каким бы чудом оно само себя не правило - текст ошибки "циклическое наследование запрещено", который надо выдавать и для классов и для интерфейсов, придётся осознанно добавить.

**Comment by ibond84** [comment]
Ну, не надо в одном issue писать разные ошибки. То, что в самом issue, работает. Давайте еще будем дальше и дальше расширять программу и говорить, что issue не исправлен...

**Comment by SunSerega** [comment]
Проблема одна и та же и не менялась. Нужна ошибка запрещающая циклическое наследование.

>Давайте еще будем дальше и дальше расширять программу и говорить, что issue не исправлен...

Сама часть вызывающая ошибку не поменялась. Пришлось только добавить код который обходит рандомно появившийся костыль в компиляторе, заменяющий хоть какое то окно ошибки - полным вылетом.
