### ISSUE TITLE
Неправильная ошибка при наследовании от Nullable

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#1542]
```
type
  t1<T> = class(System.Nullable<T>)
    
  end;
  
begin end.
```
`Невозможно инстанцировать, так как у типа T нет конструктора без параметров с уровнем доступа public`

**Comment by miks1965** [comment]
Текст ошибки правильный кстати

**Comment by miks1965** [comment]
А почему неправильная?

**Comment by SunSerega** [comment]
Потому что надо говорить что нельзя наследовать от `Nullable`, как говорит для всех остальных записей.
А конструктор `T` тут вообще не при чём:
```
begin
  var a := new System.Nullable<BigInteger>(0);
end.
```
У `BigInteger` нет публичного конструктора без параметров. А инстанцировать можно.

Вообще я не совсем понимаю, где бывает нужен конструктор по-умолчанию для инстанцирования... То есть где эта ошибка может быть к месту.

**Comment by ibond84** [comment]
Исправилось одновременно с исправлением #2191 
Ограничения при наследовании от генерик-класса теперь проверяются позднее.
