### ISSUE TITLE
Компилятор и анализатор кода предпочитают ссылку на функцию её результату, если функция хранится в переменной

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#1544]
```
begin
  var f: ()->real := ()->0;
  var r := f;
  writeln(r.GetType)
end.
```
Для `r` показывает тип `()->real` хотя должен быть `real`.

**Comment by SunSerega** [comment]
И если поставить скобочки после вызова `f` - компилятор чинится, а анализатор кода нет.

**Comment by miks1965** [comment]
f - это делегат. Это не имя функции без параметров - это делегат. По идее, используя автовыведение типов, вы понимаете, что делаете.

**Comment by SunSerega** [comment]
Когда явно вызов - скобочки всё равно даёт не ставить.
Другое дело - вы на форума давно ещё решили:
Если есть выбор между ссылкой и результат - приоритет всегда идёт результату.

**Comment by miks1965** [comment]
Ну, я же писал о том, что есть исключения. 

Более того, тут как раз не исключение. Обратите внимание, что f - не функция. То есть, у функций  - да - везде скобочки кроме того когда мы инициализируем типизированную переменную.

Но f - не функция, а делегат. Это его прямое назначение - быть делегатом. Это переменная, хранящая указатель на функцию.

Поэтому когда мы присваиваем эту переменную другой такой же - и тип у неё должен быть такой же
