### ISSUE TITLE
Анализатор кода показывает вложенные internal типы

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#1547]
```
begin
  var e1: HashSet<byte>.Enumerator;
end.
```
В этом случае, и в случае если добавит `&` перед `<` - анализатор кода видит и показывает по Ctrl+Space тип `Enumerator`, хотя он имеет уровень доступа `internal`.

**Comment by ibond84** [comment]
Enumerator публичная запись. Просьба проверять сначала все в MSDN.
