### ISSUE TITLE
PCU - Компилятор не видит метод WriteLines для массива строк

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#1549]
```
begin
  Arr('').WriteLines('');
end.
```
При этом если на входе для `WriteLines` будет подаваться последовательность строк а не массив - работает.

**Comment by miks1965** [comment]
Это проблема PCU. Такой код:

```
uses AA;

function Product(Self: sequence of integer): integer; extensionmethod;
begin
  Result := 1;
  foreach var x in Self do
    Result *= x;
end;

begin
  Arr(1.0,2.0,3.1).Product.Print;  
end.
```
работает.

Если функцию перенести в модуль, то после первой компиляции будет работать, а после второй - уже нет.
