### ISSUE TITLE
Необрабатываемое исключение при Ctrl-щелчке в C#-коде

### ISSUE THREAD

**Issue by AIexandrKotov** [pascalabcnet/pascalabcnet#1550]
```
using System;

class Program
{
  public static void Main(String[] args)
  {
    Random rnd = new Random();
  }
}
```
!Обязательно создаём новый файл, если открыть уже имеющийся .cs, то ошибка не воспроизводится.

Нажимаем на конструктор Random() Ctrl-щелчком и получаем следующее:
![30](https://user-images.githubusercontent.com/44296606/49286715-134a7880-f4ac-11e8-90ad-bf31a4ec20e1.png)

**Comment by miks1965** [comment]
А почему c# код до сих пор не закрыт от использования?

**Comment by AIexandrKotov** [comment]
Не нужно его закрывать. Ошибка не настолько критическая.

**Comment by SunSerega** [comment]
Надо только анализатор кода отключат во всех не- `.pas` файлах. А компилятор пусть работает, кому то так удобно.

**Comment by MrFresnel** [comment]
Анализатор кода можно будет пока отключить во всех не .pas файлах. Только, что мешает его сделать потом?

**Comment by ibond84** [comment]
Надо бы заменить эти "не могу" и "не хочу" на нормальный страдательный залог или безличные предложения.
