### ISSUE TITLE
Неправильная ошибка при отсутствии описания конструктора

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#1553]
```
type
  t1=class
    constructor;//Ошибка: Предописание функции без описания
  end;

begin end.
```
Это не функция, это конструктор.

**Comment by miks1965** [comment]
Ну, в C++ хуже:
Ошибка	LNK2019	ссылка на неразрешенный внешний символ "public: __thiscall aa::aa(int)" (??0aa@@QAE@H@Z) в функции _main

**Comment by SunSerega** [comment]
Ну, я и не сомневался)))) Но в паскале, всё же, в большинстве случаев отдельная ошибка для конструктора.

**Comment by SunSerega** [comment]
Нет, деструктор всюду воспринимает как процедуру, и правильно. Это пережиток прошлого, у него даже нет никакого функционала. А с конструкторами всё же надо поддерживать тенденцию, вот, к примеру, первое что я попробовал:
```
type
  t1=class
    constructor(i: integer) := exit;
  end;

begin
  new t1(1,2);//Ошибка: Нет конструктора с таким числом параметров
end.
```
