### ISSUE TITLE
Снова разрешить константные кортежи

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#1555]
```
const
  t = (5, '', 1.2);

begin end.
```
В предыдущих версиях это работало. Я взял это из программы которую давно писал. Сейчас она не компилируется, хотя раньше было нормально.

**Comment by AlexRnD61** [comment]
Это уже объясняли, а я забыл? Или не объясняли? Если кортеж по определению неизменяем, то зачем нужен константный кортеж ?

**Comment by SunSerega** [comment]
Элементы кортежа нельзя изменить. А переменной всё равно можно что то присвоить.
Если пользоваться этой логикой - контрасты и для строк не нужны, потому что их внутренности тоже неизменяемые.

**Comment by AlexRnD61** [comment]
А, ну да, я все время забываю об этой Вашей странной для меня заботе о каких-то программистах с болезнью Альцгеймера, то и дело пытающихся стать злобными буратинками и напакостить самим себе.

**Comment by miks1965** [comment]
Раз в C# запрещено, то и мы не будем делать.
