### ISSUE TITLE
Компилятор не может вычислит тип возвращаемого значения для функции с пред-описанием

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#1557]
```
type
  t1=class
    function f1: object;
  end;

function t1.f1 := nil;//Ошибка: Нельзя вычислить тип nil

begin end.
```
Это реализация функции которая уже описана. Там не надо вообще ничего вычислять. Вместо этого надо брать возвращаемое значение из описания.

**Comment by ibond84** [comment]
Как это не надо вычислять? Надо сначала узнать сигнатуру метода и уже потом сравнивать с описанием метода. Такой алгоритм, и незачем его ломать ради коротких функций.

**Comment by SunSerega** [comment]
Это короткие функции не надо ломать, только ради того чтоб алгоритм, про который нигде не написано продолжал работать так как понятно только разработчикам.

**Comment by ibond84** [comment]
Ерунда какая-то. Описывайте тип явно
