### ISSUE TITLE
Intellisense видит результат ArrGen как array of function, если в нём используется функция

### ISSUE THREAD

**Issue by AIexandrKotov** [pascalabcnet/pascalabcnet#1562]
```
begin
  var x := ArrGen(4, x -> ReadInteger);
end.
```

![37](https://user-images.githubusercontent.com/44296606/49466415-0e215c80-f811-11e8-8a36-2653b2577bc3.png)

Показывает **array of function**, а должен **array of integer**

**Comment by ibond84** [comment]
дубль
