### ISSUE TITLE
Запретить остатки вложенных записей или разрешить их с ограничениями

### ISSUE THREAD

**Issue by miks1965** [pascalabcnet/pascalabcnet#1574]
```
type 
  A = class
    i: integer;
    procedure p();
    type b = record
      //x := i;
    end;
    var c: record
      //x := i;
    end;
    begin
    
    end;
  end;
  
begin
  
end.  
```
Всё это тоже запретить

**Comment by MrFresnel** [comment]
Зачем запрещать? В классическом Паскале, насколько знаю, это разрешено. В обучении может пригодится.

**Comment by AIexandrKotov** [comment]
Это и вне классов не работает:
```
procedure p();
type
  TTT = integer;
  r = record//Неизвестное имя 'TTT'
    a: TTT;
  end;
begin
  
end;

begin end.
```

**Comment by AIexandrKotov** [comment]
Ну, всё же вы хозяин среды и вам решать, запрещать это или всё же сделать рабочим. Абсолютно все эти проблемы с записями исправятся, если вы сделаете рабочим захват имён, описанных в объемлющем объекте.

**Comment by miks1965** [comment]
Вложенные безымянные записи уже обработаны.

Остались еще вложенные типы.

**Comment by miks1965** [comment]
Всё сделано
