### ISSUE TITLE
Имена из библиотеки добавляет в основное пространство имён только для программы

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#1575]
lib.pas:
```
library lib;

type
  t1=class end;

end.
```
0.pas:
```
{$reference lib.dll}
procedure p1;
begin
  var o := new t1;
end;

begin end.
```
mdl.pas:
```
unit mdl;

{$reference lib.dll}
procedure p1;
begin
  var o := new t1;
end;

end.
```
[0.zip](https://github.com/pascalabcnet/pascalabcnet/files/2659700/0.zip)

Программа компилируется нормально.
А модуль - нет, пишет что `t1` это неизвестное имя.
Если сделать mdl библиотекой - будет та же ошибка.

**Comment by SunSerega** [comment]
При чём uses для пространства имён lib тоже не работает. Вместо него пытается подключить библиотеку, и пишет что ожидался модуль а встречена библиотека.

**Comment by SunSerega** [comment]
И, кстати, это всё касается только компилятора.
В анализатор кода в основное пространство имён всё всегда добавляется.

**Comment by miks1965** [comment]
Всему виной вот этот дурацкий код в NetHelper.cs
```
if (SemanticRules.AllowGlobalVisibilityForPABCDll && entry_type != null)
```
Если заменить его на 
```
if (entry_type != null)
```
то всё работает
