### ISSUE TITLE
Позволить описывать сразу несколько автосвойств через auto property X1, X2, ... XN: T

### ISSUE THREAD

**Issue by MrFresnel** [pascalabcnet/pascalabcnet#1576]
Позволить описывать сразу несколько автосвойств:
```
type
  TVector3D = class
  public
    auto property X, Y, Z: integer;
  end;

begin
end.
```
по аналогии с полями:
```
type
  TVector3D = class
  public
    fX, fY, fZ: integer;
  end;

begin
end.
```

**Comment by miks1965** [comment]
Свойства описываются только по одному. Поэтому для автосвойств не будем делать по-другому

**Comment by SunSerega** [comment]
Да но у свойств это невозможно только из за того что аццесоры не могут быть общими. А с автосвойствами такой проблемы нет.

**Comment by MrFresnel** [comment]
Тем более, снятие этого ограничение позволит компактнее записывать код.
