### ISSUE TITLE
as и is не работает для типа, описанного с ключевым словом

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#1581]
```
begin
  var a := (new object) as array of byte;
end.
```
`Встречено 'array', а ожидался идентификатор`

**Comment by AIexandrKotov** [comment]
Если же объявить синоним типа, то всё работает
```
type
  Arr<T> = array of T;
  
begin
  var a := (new object) as Arr<byte>;
end.
```

**Comment by miks1965** [comment]
Пользуйтесь синонимом типа. Таковы правила языка

**Comment by AIexandrKotov** [comment]
Может тогда конструкцию из C# (byte[]) сделаете в этом контексте рабочей? Зачем использовать синоним, если можно его не использовать
