### ISSUE TITLE
IDE ломается при циклическом наследовании интерфейсов

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#1583]
Re: #1541.

```
type
  I1<T> = interface;
  I2<T> = interface;
  
  I1<T> = interface(I2<T>)
    
  end;
  
  I2<T> = interface(I1<T>)
    
  end;

type t1=class(I1<byte>) end;
  
begin
  new t1;
end.
```

![image](https://user-images.githubusercontent.com/27270190/50002978-a86c6780-ffaa-11e8-88a3-40e5f5fb7fc8.png)

С классами лучше, но ошибка невнятная:
```
type
  C1<T> = class;//Ошибка: Конструктор по умолчанию в базовом классе C2<T> не найден
  C2<T> = class;
  
  C1<T> = class(C2<T>)
    
  end;
  
  C2<T> = class(C1<T>)
    
  end;

begin end.
```

Нужно и в классах, и в интерфейсах запретить циклическое наследование, тогда везде будет выдаваться правильная ошибка.

**Comment by miks1965** [comment]
Да, падает

**Comment by miks1965** [comment]
Предописание не может быть использовано как предок

**Comment by SunSerega** [comment]
А для классов значит отдельную issue?

**Comment by ibond84** [comment]
Какие классы? Исправляется всегда только одна ошибка, которая в заголовке, а не в десяти комментариях после.

**Comment by ibond84** [comment]
И то, там ошибка правильная, просто курсор не туда ставится.
