### ISSUE TITLE
Отладчик дохнет когда контактирует bin\Errors.pdb

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#1584]
[bin.zip](https://github.com/pascalabcnet/pascalabcnet/files/2681031/bin.zip)

Все файлы взяты из папки `bin` после запуска `_GenerateAllSetups.bat`, в локальной копии этого репозитория.
(без запуска того `.bat` - `Errors.dll` нету, как и его `.pdb`)

Единственное что изменено - `TestRunner.pas` упрощён до минимального кода с которым воспроизводится:
```
{$reference Errors.dll}

procedure p1;
begin
  var err: PascalABCCompiler.Errors.Error;
end;

begin
  p1;
end.
```
Если поставить точку останова после или внутрь вызова `p1` - отладчик зависает (показывает что выполняется, но тратит 0% процессора).

Так же с F8/F7.

Если удалить `Errors.pdb`, оставив `Errors.dll` - всё в порядке.

Вот видео пример:
https://www.youtube.com/watch?v=hPvcn-Tunoc

При запусках я нажимал:
-1) F8, F7
-2) F8, F8
-3 и 4) Только кликал мышью, на видео видно куда

**Comment by SunSerega** [comment]
И, похоже, так с большинством .pdb из той папки (если не со всеми).

**Comment by miks1965** [comment]
Без pdb всё работает. Я думаю, просто отладчик не рассчитан на работу с pdb

**Comment by SunSerega** [comment]
С паскалевскими .pdb, вроде, всё в порядке. А `Errors.dll` (а значит и его `.pdb`) делалось в C#, не так ли?

**Comment by miks1965** [comment]
Да, значит, с C#повским pdb. А зачем вам pdb при трассировке?

**Comment by SunSerega** [comment]
Незачем, оно уже там было. Просто сделайте тогда чтоб его не хватало, а то каждый раз удалять... И может быть случай когда для дебага не надо, но потом зачем то понадобится другой программе, которая будет эту .dll использовать.
