### ISSUE TITLE
Разрешить описывать extension-операторы преобразования типов вне классов и записей

### ISSUE THREAD

**Issue by MrFresnel** [pascalabcnet/pascalabcnet#1586]
```
type
  T1 = class
  end;
  
  T2 = class
  end;
  
function operator implicit(x: T1): T2; extensionmethod := new T2();

begin
end.
```
Этот код не компилируется, выдавая ошибку:

> Program1.pas(8) : extension-операторы преобразования типов допустимы только для классов из других сборок .NET

Тема обсуждения этого вопроса [здесь](http://forum.mmcs.sfedu.ru/t/oshibka-extension-operatory-preobrazovaniya-tipov-dopustimy-tolko-dlya-klassov-iz-drugih-sborok-net/2716).

**Comment by miks1965** [comment]
extensionы предназначены для ситуаций когда тип нельзя изменить. То есть, он откомпилирован. Если тип создаётся программистом, то операция преобразования типа реализуется как static-член.
