### ISSUE TITLE
Сделать константу DEBUG для директивы $if компилятора

### ISSUE THREAD

**Issue by miks1965** [pascalabcnet/pascalabcnet#159]
Тогда можно в теле Assert просто эту константу использовать как простейшую реализацию

**Comment by ibond84** [comment]
Нужно сохранять узлы синтаксического дерева внутри блока $if в pcu. Или у нас это уже реализовано? Я помню, кто-то делал $if.

**Comment by ibond84** [comment]
Добавил в IParser.BuildTree опциональный параметр List<string> DefinesList = null, в котором передается константы DEBUG и RELEASE. Думаю, это решение правильное, ведь лексер ничего не знает об опциях компиляции, а просто получает константы.
