### ISSUE TITLE
Показывает кишки компилятора при присвоении инициализатора массива переменной неправильного типа

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#1595]
```
begin
  var p: byte := (1, 2, 3);
end.
```
`Нельзя преобразовать тип ArrayConst к byte`

Надо заменить `ArrayConst` на что то человеко-читаемое.

**Comment by MrFresnel** [comment]
Например, на:

> Нельзя преобразовать тип инициализатора массива к byte
