### ISSUE TITLE
Анализатор кода не показывает описание стандартных типов

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#1597]
```
begin
  var b: byte;
end.
```

![image](https://user-images.githubusercontent.com/27270190/50048370-dd73d980-00d2-11e9-91fa-38cdb0cc3181.png)

Хотя описание у него явно есть, и паскаль видит его в метаданных (их показывает если зажать Ctrl и нажать на `byte`):

![image](https://user-images.githubusercontent.com/27270190/50048378-fd0b0200-00d2-11e9-9fce-94dfa8a52065.png)

**Comment by ibond84** [comment]
Ну, иногда не показывает. Специально ловить не буду. Как поймаю ошибку, так и исправлю

**Comment by MrFresnel** [comment]
> У меня никогда не показывает.

Аналогично.

**Comment by AIexandrKotov** [comment]
Всё показывает (3.4.2.1889)
![46](https://user-images.githubusercontent.com/44296606/50053697-8c9fc780-014a-11e9-821b-2b0943c93a6c.png)
