### ISSUE TITLE
Позволить инициализировать автосвойства при объявлении

### ISSUE THREAD

**Issue by MrFresnel** [pascalabcnet/pascalabcnet#1605]
Позволить инициализировать автосвойства при объявлении с использованием синтаксиса:
```
 type
  TClass = class
    auto property X: integer := 1;
  end;

begin
end.
```
В C#, например, это разрешено:
```
public int MyProperty { get; set; } = 2;
```
. Это позволит сделать код конструкторов чище, так как инициализация свойств будет вынесена из них.

**Comment by SunSerega** [comment]
Продолжение #1271, пусть будет референс.
