### ISSUE TITLE
Запретить Self в параметре метода

### ISSUE THREAD

**Issue by miks1965** [pascalabcnet/pascalabcnet#1606]
```
type A = class
  procedure p1(self: integer); 
  begin
  end;
end;

begin 

end.
```
Ещё в каком-то Issue с лямбдами было - посмотреть

**Comment by SunSerega** [comment]
>в каком-то Issue с лямбдами

Наверное, #855.

**Comment by MrFresnel** [comment]
В C# использование this как имя параметра запрещено.

**Comment by SunSerega** [comment]
Почитайте рассуждения @miks1965 из #855 для начала. Он и про это сказал, там `this` - ключевое слово. Экстеншн-методы по другому работают, для них `self` разрешено как имя параметра метода.
