### ISSUE TITLE
#0 вызывает неопределённое поведение и работает по разному в режимах c/без отладки

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#1608]
```
begin
  var a := Arr(#65,#0,#65);
  foreach var ch in a do
    write(ch);
  writeln;
  writeln(a.Length);
end.
```
В режиме без отладки выведет только 1 `A`, а в режиме с отладкой выводит сразу оба A, и не забывает вывести длину массива на следующей строчке.

Да, то что #0 ломает IDE это древний баг, но раз он вызывает неопределённое поведение в зависимости от того, включена отладка или нет - теперь это серьёзная проблема.

**Comment by miks1965** [comment]
А можно уточнить про то что #0 это древний баг Ide. Я про это ничего не знаю

**Comment by miks1965** [comment]
Я думаю, что это мог писать тот ненормальный, который про нас гадости везде в интернете пишет из хулиганских соображений. Поэтому Вы не повторяйте неподтверждённое.

По поводу того что #0 это управляющий символ вы вообще в курсе?

**Comment by SunSerega** [comment]
>Я думаю, что это мог писать

Не, это было раньше, на много, и вроде это был кто то из своих, вроде @RAlex-а.

>#0 это управляющий символ вы вообще в курсе?

`#0` это дефолтный символ:
```
begin
  var ch: char;
  writeln(ch=#0);//True
end.
```
Могу предположить, что где то внутри IDE, вывод программы передаёт неуправляемыми массивами символов, которые оканчиваются символом, вместо того чтоб передавать свою длину вместе с собой `#0` (так, вроде, в C++ часто делают).

Но дело не в потоке вывода процесса, это вполне работает:
```
begin
  if CommandLineArgs.Length=0 then
  begin
    var p := new System.Diagnostics.Process;
    p.StartInfo.FileName := GetEXEFileName;
    p.StartInfo.Arguments := 'arg';
    p.StartInfo.UseShellExecute := false;
    p.StartInfo.RedirectStandardOutput := true;
    p.Start;
    
    while not p.HasExited do
    begin
      foreach var ch in p.StandardOutput.ReadLine do
        writeln(word(ch));
      writeln('-'*20);
      Sleep(10);
    end;
    
  end else
  begin
    
    loop 10 do
    begin
      writeln(#65#0#65);
      Sleep(1000);
    end;
    
  end;
end.
```
Это именно в коде IDE что то.

**Comment by miks1965** [comment]
Примерно так. Текст разбивается порциями на части. Видимо это и сказывается. Думаю, что в других системах программирования, например, в Lasarus, такой код тоже будет работать по разному в разных режимах. Потому что он ошибочен

**Comment by SunSerega** [comment]
Консоль от этого не ломается. Неустойчивое поведение в любом случае не должно происходить. А разбивать текст знаками `#0` - это прошлый век, сейчас и памяти и производительности хватить передавать длину текста перед самим текстом.

И ещё раз - это именно проблема IDE, `Process.StandardOutput` от этого знака не ломается, значит это он у вас текст внутри где то неправильно передаётся.

**Comment by miks1965** [comment]
```
textBox.AppendText(Text); 
```
не добавляет ничего если Text начинается с \0

**Comment by SunSerega** [comment]
Так:
```
textBox.AppendText(Text.Replace(#0, ' ')); 
```
Чтоб было как в консоли.

Или так:
```
textBox.AppendText(Text.Remove(#0)); 
```
Чтоб было как в блокноте (если в файле есть символ `#0` - блокнот его просто не показывает).

>и сами себе критикуем предположенное:

Я имел в виду что это так у вас, и что то как сейчас - плохо, что это прошлый век. Я не предлагал так реализовывать, ни в коем случае.

**Comment by miks1965** [comment]
Ясно. Ну то есть из-за неправильной программы замедлять вывод. 

Это плохое предложение.

**Comment by SunSerega** [comment]
Какое там замедление? Вывод на экран всё равно в отдельном потоке, он ничего не делает программе. Не говоря уже о том, что эта операция очень быстрая, даже для строк в сотни тысяч знаков она проходит моментально.

Другое дело - на это попадаются новички, и им сложно понять что не так. Уже попались, точнее. Как для языка для обучения - это не допустимо.

**Comment by SunSerega** [comment]
Вот, смотрите:
```
begin
  var s := new string(ArrGen(100*1000, i->char(Random(2))));
  var t1 := DateTime.Now;
  loop 10*1000 do
    s.Replace(#0, ' ');
  var t2 := DateTime.Now;
  writeln(t2-t1);
end.
```
У меня показывает ~3 сек для 10к операций `.Replace`, для строки из 100к символов. Если вам так уж важна скорость - вы бы уже давно IDE переделали, там много чего улучшить можно. И даже если так, это изменения кина не сделает, ни на сколько.

**Comment by miks1965** [comment]
Вот такой код:
```
begin
  Write('aaa',#1,#2,#3,#4,#5,#6,#7,#8,#9,'bbb');
end.
```
даёт сильно разный вывод по F9 и по Shift-F9. А по Shift-F9 ещё и звук издаёт - причём у всех разный. Надеюсь, Вы не будете настаивать чтобы мы во всех режимах обеспечивали одинаковый писк?

А новички пусть учат матчасть - управляющие символы выводить нельзя.

**Comment by miks1965** [comment]
Вот Rider - в нем программа 
```
Console.WriteLine("abc"+(char)(6)+(char)(7)+(char)(8)+"def");
```
выводит abdef

**Comment by MrFresnel** [comment]
> И - Вы неправильно понимаете язык для обучения, тем более, что PascalABC.NET таковым не является.

Разве? По-моему договорились, что PascalABC.Net [занимает образовательную нишу](http://forum.mmcs.sfedu.ru/t/nisha-pascalabc-net/2340/6).
