### ISSUE TITLE
Неправильная ошибка, при попытке сделать не-шаблонный синоним указателя на шаблонную запись

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#1617]
```
type
  
  PNode = ^TNode<T>;
  
  TNode<T> = record end;
  
begin end.
```
`Неизвестное имя 'TNode'`

Если поставить объявление `PNode` `TNode` - ошибка правильная:
```
type
  
  TNode<T> = record end;
  
  PNode = ^TNode<T>;
  
begin end.
```
`Неизвестное имя 'T'`

Если `PNode` тоже шаблонный - всё проходит:
```
type
  
  PNode<T> = ^TNode<T>;
  
  TNode<T> = record end;
  
begin end.
```
Это компилируется без ошибок.

**Comment by miks1965** [comment]
Ошибка правильная. Просто у вас две ошибки и компилятор выбирает одну из них

**Comment by SunSerega** [comment]
Кроме всего прочего, тут тоже получаем ошибку:
```
type
  
  PNode = ^TNode<byte>;//Ошибка: Неизвестное имя 'TNode'
  
  TNode<T> = record end;
  
begin end.
```
Хотя это уже однозначно правильный код.

**Comment by miks1965** [comment]
Нет, этот код неправильный. Возможность "заглядывать вперёд" в той же секции type - это большое исключение, калька со старого паскаля, и она реализована только для "равных" типов - то есть, никаких опережающих инстанций типов. На тип (ровно такой же) можно сделать опережающее объявление - т.е. на TNode<T> и больше ни на что.
