### ISSUE TITLE
Падает yield

### ISSUE THREAD

**Issue by miks1965** [pascalabcnet/pascalabcnet#162]
```
var a := 5;

function Gen: sequence of integer;
begin
  for var i:=1 to 10 do
    yield i*a;
  if True then
  for var i:=1 to 10 do
    yield i*a;
end;

begin
  Gen.Println;
end.
```

**Comment by frninja** [comment]
https://github.com/pascalabcnet/pascalabcnet/commit/bb6734d2dc7001fb43d6a4c9b8f4a6812f16ccdb

**Comment by frninja** [comment]
Закрыто коммитом
https://github.com/pascalabcnet/pascalabcnet/commit/bb6734d2dc7001fb43d6a4c9b8f4a6812f16ccdb
