### ISSUE TITLE
Отладка не показывает значение переменных, захваченных лямбдой

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#1622]
```
begin
  var i: integer;
  var p: ()->() := ()->
  begin
    i := 5;
  end;
  
  writeln(i);
end.
```
Отладка не будет видеть `i` тут.

**Comment by ibond84** [comment]
Ну вы не вызвали p(). При заходе в лямбду переменная i видна

**Comment by SunSerega** [comment]
Ну так из основного контекста она тоже должна быть видна. Раз компилятор видит то и отладка должна видеть.
