### ISSUE TITLE
"Метод не найден" во время выполнения, в случае с библиотеками и экстеншн-методами из PABCSystem

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#1624]
[0.zip](https://github.com/pascalabcnet/pascalabcnet/files/2717316/0.zip)
`lib.pas`:
```
library lib;

procedure p1;
begin
  Arr(0).MinBy(i->i);
end;

end.
```
`0.pas`:
```
{$reference lib.dll}

begin
  p1;
end.
```

1.1) Открываем `lib.pas` и компилируем его из IDE;
1.2) Открываем `0.pas` и тоже компилируем его из IDE;
1.3) Запускаем `0.pas` - всё нормально.

2.1) Заменяем в обоих файлах `p1` на `p2`;
2.2) Компилируем `lib.pas` и затем `0.pas`;
2.3) Запускаем `0.pas`:
```
0.pas(4) : Ошибка времени выполнения: Метод не найден: "!!0 PABCSystem_implementation______.PABCSystem_implementation______.MinBy(System.Collections.Generic.IEnumerable`1<!!0>, System.Func`2<!!0,!!1>)".
```

3.1) Закрываем IDE.
3.2) Удаляем все `.pdb`, `.dll` и `.exe`.
3.3) Снова выполняем пункты 1.1) и 1.2)
3.4) И снова `0.pas` благополучно запускается и выполняется без ошибок.

**Comment by ibond84** [comment]
Не воспроизводится. Проверьте еще раз.

**Comment by SunSerega** [comment]
Да, исправилось само.
