### ISSUE TITLE
Неправильно подсвечивает знаки "/", если их больше 3

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#1626]
![image](https://user-images.githubusercontent.com/27270190/50549521-0b2a5800-0c67-11e9-9e1b-4d25fa1b0672.png)
То есть все кроме последних 3 отображает как незакомментированные. Хотя они тут все являются 1 большим комментарием.

Раньше, вроде, это правильно отображалось.

**Comment by MrFresnel** [comment]
Насколько помню - так было всегда.
