### ISSUE TITLE
Показывает оператор по точке для последовательности

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#1627]
```
begin
  var s := Seq(0);
  s.
end.
```
![image](https://user-images.githubusercontent.com/27270190/50549809-1e8bf200-0c6c-11e9-9d5d-541b3d2c3087.png)

Операторы нельзя вызвать по точке, поэтому их и показывать там не должно.

При чём, в 1 из последних билдов этого небыло.

**Comment by ibond84** [comment]
Ну это только в дебаг-версии с включенной опцией "не запускать компилятор в отдельном процессе" и после запуска с ускорением. В релизе такое невозможно.

**Comment by SunSerega** [comment]
У меня это было в релизе. При чём в официальном (я запостил это до того как перешёл на собранную руками версию).
