### ISSUE TITLE
Подпрограмма Pred системного модуля приоритетнее

### ISSUE THREAD

**Issue by AIexandrKotov** [pascalabcnet/pascalabcnet#1633]
```pas
function pred(a: integer) := a=1;

begin
  pred(1);//Несколько подпрограмм могут быть вызваны
end.
```
А должна быть приоритетнее pred(a: integer): boolean
`(наверное)`

**Comment by AIexandrKotov** [comment]
Не только ведь Pred, Со всеми функциями, аргументы и имя которых такие же, как в функциях из PABCSystem, а тип результата иной.
```pas
function succ(n: integer) := n = 1;

begin
  succ(1);//Несколько подпрограмм могут быть вызваны
end.
```
```pas
function IntToStr(a: integer) := a = 1;

begin
  IntToStr(1);//Несколько подпрограмм могут быть вызваны
end.
```

**Comment by ibond84** [comment]
Ну правильно ошибка выдается. Функции имеют одинаковые параметры, поэтому неоднозначность. И не важно, где они расположены. Перекрытие работает, только если функции одинаковы.
