### ISSUE TITLE
Сделать выделение жирным шрифтом ключевых слов read и write

### ISSUE THREAD

**Issue by MrFresnel** [pascalabcnet/pascalabcnet#1634]

**Comment by miks1965** [comment]
Ну, над контекстной подсветкой мы не властны - там компонент подсветки это не позволяет

**Comment by MrFresnel** [comment]
Нет. Я не требую контекстной подсветки.

**Comment by miks1965** [comment]
Обычная подсветит обычную Write, которая используется существенно чаще чем свойства
