### ISSUE TITLE
<T,T1,T2> и <T1,T2,T> - в первом случае ошибка, во втором - нет

### ISSUE THREAD

**Issue by miks1965** [pascalabcnet/pascalabcnet#1636]
```
function operator*<T,T1,T2>(f: T1 -> T2; g: T -> T1): T -> T2; extensionmethod;
begin
  Result := x->f(g(x));
end;

begin
end.
```
fg1.pas(1) : Повторное объявление 

Если так:
```
function operator*<T1,T2,T>(f: T1 -> T2; g: T -> T1): T -> T2; extensionmethod;
begin
  Result := x->f(g(x));
end;

begin
end.
```
то ошибки нет!

**Comment by ibond84** [comment]
Ну первый оператор конфликтует с

```
function operator*<T1, T2, TResult>(Self: T2->TResult; composer: T1->T2): T1->TResult; extensionmethod;
begin
  if composer = nil then
    raise new System.ArgumentNullException('composer');
  Result := Self.Compose(composer);
end;
```
из PABCSystem. A extension-методы переопределять у нас нельзя

**Comment by ibond84** [comment]
Не вижу здесь ошибки.

**Comment by miks1965** [comment]
Щас... Я рассуждал так. Не может изменение порядка generic-параметров влиять на поведение. А оно влияет.

**Comment by SunSerega** [comment]
То есть `Повторное объявление` надо выдавать в обоих случаях?

**Comment by miks1965** [comment]
Понятно. На самом деле это всего лишь проверка на одноименные чуть-чуть сбоит. А код-то правильно компилируется в обоих случаях
