### ISSUE TITLE
Неговорящий текст ошибки при использовании открытого типа в default/sizeof

### ISSUE THREAD

**Issue by MrFresnel** [pascalabcnet/pascalabcnet#1642]
Исходный код:
```
begin
  var x := default(List<>);
end.
```
Текст ошибки:
> Program1.pas(2) : Встречено '<>', а ожидалось ')'

Такое сообщение об ошибке мало о чём говорит. В C# на аналогичный код:
```
using System.Collections.Generic;

namespace CSrharpApplicationTest
{
    public class Program
    {
        public static void Main(string[] args)
        {
            var x = default(List<>);
        }
    }
}
```
выдаётся такое сообщение об ошибке:
> Неожиданное использование несвязанного универсального имени.

Предлагаю и в PascalABC.Net исправить текст ошибки. Например, на:

> Использование открытых типов в контексте default и sizeof запрещено

**Comment by ibond84** [comment]
Ну, в грамматике нет правила для этого. Нельзя для каждой неправильной синтаксической конструкции выдавать какие-то особые сообщения об ошибке. Не надо переусложнять.
