### ISSUE TITLE
Assert в WDE перестал выдавать номер строки и имя файла

### ISSUE THREAD

**Issue by miks1965** [pascalabcnet/pascalabcnet#165]
```
begin
  Assert(False);
end.
```

**Comment by ibond84** [comment]
А это не будет работать из-за того, что ехе-шники запускаются ProgrammRunner.exe

**Comment by miks1965** [comment]
Закрывать? Или ещё помороковать? Или исправить сообщение об ошибке?

**Comment by ibond84** [comment]
Ну есть одна идея. Добавить в функцию assert два опциональных параметра line и col. 
```
procedure assert(mes: string; line: integer := __get_current_line__(); col: integer := __get_current_col__());
begin
  
end;
```
__get_current_line__ и __get_current_col__ будут функциями, вычисляемыми на этапе компиляции. Это и в Linux будет работать.

**Comment by miks1965** [comment]
А как реализовать эти функции?

**Comment by ibond84** [comment]
Можно сделать проще, без этих функций. А просто передавать при вызове assert номер строки и имя файла
