### ISSUE TITLE
Выдаёт неправильную ошибку при вызове статичного метода через экземпляр

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#1653]
```
type
  t1 = class
    static procedure p1(b: byte) := exit;
  end;

begin
  var a := new t1;
  a.p1;
end.
```
`Неверное количество параметров процедуры`
А надо выдавать:
`Нельзя вызвать статический метод p1 через ссылку на экземпляр`
И так же если типы параметров неправильные.

Ошибка которая сейчас - сильно запутывает. Первоочерёдная проблема в том что у экземпляров типа `t1` нету метода `p1`.

**Comment by ibond84** [comment]
В фры-паскале еще круче сообщение об ошибке: "illegal expression" ;)

**Comment by ibond84** [comment]
Проверка на "Нельзя вызвать статический метод" происходит ясное дело после вызова select_function, который ищет подходящий метод и выдает эту ошибку. 
И считаю, что она более правильная, чем "Нельзя вызвать статический метод p1 через ссылку на экземпляр", потому что перегрузки могут быть одновременно и статическими и экземплярными.

**Comment by ibond84** [comment]
Компилятор C# выдает такую же ошибку. Закрываю
