### ISSUE TITLE
Индексное свойство пытается показать во время отладки

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#1656]
```
type
  t1 = class
    property p1[i: integer]: integer read i+1;
  end;

begin
  var a := new t1;
end.
```
![image](https://user-images.githubusercontent.com/27270190/51557526-d4221d80-1e85-11e9-9806-895660143cc8.png)

Проблема в том, что отладчик пытается показать значение `a.p1`, но индексному свойству нужен 1 параметр, поэтому вместо результата он получает ошибку.

Наверное, надо убрать индексные свойства из вкладки "Локальные переменные", т.к. отладчик не может знать какие значения в него можно передать.

**Comment by MrFresnel** [comment]
В Visual Studio 2017 для аналогичного кода для x ничего не отображается:

![image](https://user-images.githubusercontent.com/42812113/51598037-c31cef00-1f0d-11e9-83f5-6b041997d10c.png)
