### ISSUE TITLE
Форматирование между wordA и wordB ломается, если между ними есть комментарий

### ISSUE THREAD

**Issue by MrFresnel** [pascalabcnet/pascalabcnet#1660]
Исходный код:
```
type
  T0   {}   =   {}   auto   {}   class
  end;

begin
end.
```
После форматирования:
```
type
  T0 {}   =   {} auto   {}   class
  end;

begin
end.
```
Предлагаю убрать форматирование между словами wordA и wordB, если между ними есть комментарий. Это лучше, чем непредсказуемость результата форматирования. Так, например, сделано в Visual Studio 2017.

**Comment by ibond84** [comment]
Ломания не увидел. И вообще код с комментариями форматируется как получится, но пытается сохранять исходное форматирование.

**Comment by SunSerega** [comment]
Между `T0` и `{}` и потом межу `{}` и `auto` удалило часть пробелов. То есть 2 рандомные части удалило, а остальное оставило. А надо чтоб везде было одинаково.
