### ISSUE TITLE
Запретить перегружать += как функцию - всё равно это не работает (спорно - говорят, что для dll это нужно)

### ISSUE THREAD

**Issue by miks1965** [pascalabcnet/pascalabcnet#1666]
```
function operator+=<T>(a: LinkedList<T>; x: T): LinkedList<T>; extensionmethod;
begin
  a.AddLast(x);
  Result := a;
end;

begin
  var l := new LinkedList<integer>;
  Print(l += 2);
end.
```

**Comment by SunSerega** [comment]
Я уже писал об этом. @ibond84 сказал что это для .dll-ок. Если C# программа подключит паскалевскую библиотеку с этой функцией - должно работать.

**Comment by miks1965** [comment]
А, может быть. Ну пускай повисит пока не разберёмся, зачем это для dll-ок

**Comment by SunSerega** [comment]
Но в стандартных функциях вроде `List+=` возвращаемое значение всё же стоит убрать:
```
function operator+=<T>(a, b: List<T>): List<T>; extensionmethod;
begin
  a.AddRange(b);
  Result := a;
end;
```
Вот тут оно точно бесполезно.

**Comment by miks1965** [comment]
Я так понимаю, что если это использовать в C#, то надо определять именно как функцию.

Не будем запрещать.
