### ISSUE TITLE
Отключать анализатор кода в .cs и .vb файлах

### ISSUE THREAD

**Issue by MrFresnel** [pascalabcnet/pascalabcnet#1672]
![image](https://user-images.githubusercontent.com/42812113/51725614-5d974280-2074-11e9-8b6c-c3eadd64d00e.png)

Показывать то, что сделано для Pascal в .cs и .vb файлах - некорректно.

**Comment by ibond84** [comment]
У меня ничего не выводится

**Comment by MrFresnel** [comment]
Погодите, зачем закрывать то? Я выше привёл скрин, может у кого то такая же ситуация.

**Comment by SunSerega** [comment]
Воспроизводится:

![image](https://user-images.githubusercontent.com/27270190/52118427-eedf5980-261e-11e9-80eb-cbb8f4ba676b.png)

Но только со второго нажатия Ctrl+Space.
