### ISSUE TITLE
Падение компилятора - обращение к generic-полю надкласса из generic-процедуры

### ISSUE THREAD

**Issue by miks1965** [pascalabcnet/pascalabcnet#1674]
```
type
  Base<T> = class
    XYZW: T;
  end;
  
  Derived<T1> = class(Base<T1>)
  end;

procedure pppp<TProc>(dd: Derived<TProc>); 
begin
  var a := new Derived<TProc>;
  a.XYZW := default(TProc);
end;

begin
end.
```

**Comment by miks1965** [comment]
Здесь попроще. В NetGenerator.cs 1561
```
FldInfo fldinfo = helper.GetField(icfn);
```
ВОЗВРАЩАЕТ NULL ПОТОМУ ЧТО В value.used_members есть var XYZW: T1 вместо var XYZW: T
Думаю, надо заменить на var XYZW: T - и всё наладится

**Comment by SunSerega** [comment]
(это продолжение #1632, пусть будет ссылка)

**Comment by miks1965** [comment]
Нет, не продолжение - не сбивайте пожалуйста. Это совершенно другая ветка и другие причины.
