### ISSUE TITLE
.Take/Skip-Last реализованы ужасно не эффективно

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#1678]
Сейчас оно реализовано так:
```
/// Возвращает последние count элементов последовательности
function TakeLast<T>(Self: sequence of T; count: integer): sequence of T; extensionmethod;
begin
  Result := Self.Reverse.Take(count).Reverse;
end;

/// Возвращает последовательность без последних count элементов 
function SkipLast<T>(self: sequence of T; count: integer := 1): sequence of T; extensionmethod;
begin
  Result := Self.Reverse.Skip(count).Reverse;
end;
```

`.Reverse` (которых по 2 сейчас вызывается) создаёт кучу массивов, пытаясь угадать какой размер будет у последовательности. В то время как мы можем создавать только 1 массив, сразу нужной длины, и то не всегда:
```
/// Возвращает последние count элементов последовательности
function TakeLast<T>(Self: sequence of T; count: integer): sequence of T; extensionmethod;
begin
  if count<1 then
  begin
    Result := new T[0];
    exit;
  end;
  
  if self is ICollection<T>(var coll) then
  begin
    Result := coll.Skip(coll.Count-count);
    exit;
  end;
  
  var buff := new T[count];
  var enm: IEnumerator<T> := self.GetEnumerator;
  for var i := 0 to count-1 do
    if enm.MoveNext then
      buff[i] := enm.Current else
    begin
      Result := buff.Take(i);
      exit;
    end;
  
  while enm.MoveNext do
  begin
    System.Array.Copy(buff,1,buff,0,count-1);
    buff[count-1] := enm.Current;
  end;
  
  Result := buff;
end;

/// Возвращает последовательность без последних count элементов 
function SkipLast<T>(self: sequence of T; count: integer): sequence of T; extensionmethod;
begin
  if count<1 then
  begin
    yield sequence self;
    exit;
  end;
  
  if self is ICollection<T>(var coll) then
  begin
    yield sequence coll.Take(coll.Count-count);
    exit;
  end;
  
  var buff := new T[count];
  var enm: IEnumerator<T> := self.GetEnumerator;
  for var i := 0 to count-1 do
    if enm.MoveNext then
      buff[i] := enm.Current else
      exit;
  
  while enm.MoveNext do
  begin
    yield buff[0];
    System.Array.Copy(buff,1,buff,0,count-1);
    buff[count-1] := enm.Current;
  end;
  
end;

/// Возвращает последовательность без последнего элемента
function SkipLast<T>(self: sequence of T): sequence of T; extensionmethod :=
self.SkipLast(1);
```

**Comment by MrFresnel** [comment]
```
/// Возвращает последовательность без последнего элемента
function SkipLast<T>(self: sequence of T): sequence of T; extensionmethod :=
self.SkipLast(1);
```
Почему бы просто не использовать значение count равным 1 по умолчанию?

**Comment by miks1965** [comment]
Там много что неэффективно. 

Есть другие резоны. Весь стандартный модуль в нашей реализации поднимается в память в виде семантического дерева. Весь. Поэтому компактность кода, содержащегося в нем, - одна из основных задач.

Второе. Если уж реализовывать, то надо посмотреть реализацию в NetCore: https://docs.microsoft.com/ru-ru/dotnet/api/system.linq.queryable.takelast?view=netcore-2.0

Вы вот откуда взяли этот код? Не сами же писали?

**Comment by ibond84** [comment]
>Весь стандартный модуль в нашей реализации поднимается в память в виде семантического дерева. Весь.

Ну, это если перекомпилировать модуль. А с PCU только то, что используется. В интеллисенсе вообще только скоупы да переменные хранятся.

**Comment by SunSerega** [comment]
> Почему бы просто не использовать значение count равным 1 по умолчанию?

А вы попробуйте поставьте там значение по умолчанию... Компилятор не даёт, разработчики не говорят зачем это запрещено.

> https://github.com/dotnet/corefx/issues/13842

Ага, вижу, мне показалось что прокручивать индекс будет криво работать. Сделаю примерно как [тут](https://github.com/dotnet/corefx/issues/13842#issuecomment-261823388):
```
/// Возвращает последние count элементов последовательности
function _TakeLast<T>(Self: sequence of T; count: integer): sequence of T; extensionmethod;
begin
  if self=nil then raise new System.NullReferenceException('self');
  
  if count<1 then
  begin
    Result := new T[0];
    exit;
  end;
  
  if self is ICollection<T>(var coll) then
  begin
    Result := coll.Skip(coll.Count-count);
    exit;
  end;
  
  var buff := new T[count];
  var enm: IEnumerator<T> := self.GetEnumerator;
  for var i := 0 to count-1 do
    if enm.MoveNext then
      buff[i] := enm.Current else
    begin
      Result := buff.Take(i);
      exit;
    end;
  
  var ind := 0;
  while enm.MoveNext do
  begin
    buff[ind] := enm.Current;
    ind := (ind+1) mod count;
  end;
  
  Result := buff.Skip(ind) + buff.Take(ind);
end;

/// Возвращает последовательность без последних count элементов 
function _SkipLast<T>(self: sequence of T; count: integer): sequence of T; extensionmethod;
begin
  if self=nil then raise new System.NullReferenceException('self');
  
  if count<1 then
  begin
    yield sequence self;
    exit;
  end;
  
  if self is ICollection<T>(var coll) then
  begin
    yield sequence coll.Take(coll.Count-count);
    exit;
  end;
  
  var buff := new T[count];
  var enm: IEnumerator<T> := self.GetEnumerator;
  for var i := 0 to count-1 do
    if enm.MoveNext then
      buff[i] := enm.Current else
      exit;
  
  var ind := 0;
  while enm.MoveNext do
  begin
    yield buff[ind];
    buff[ind] := enm.Current;
    ind := (ind+1) mod count;
  end;
  
end;

/// Возвращает последовательность без последнего элемента
function _SkipLast<T>(self: sequence of T): sequence of T; extensionmethod :=
self._SkipLast(1);

begin
  foreach var s in Arr(
    Seq(1,2,3,4,5),
    Seq(1,2,3,4,5).Where(i->true)
  ) do
  begin
    
    Assert(s._SkipLast(2)   .SequenceEqual(Arr(1,2,3)));
    Assert(s._SkipLast(6)   .SequenceEqual(new integer[0]));
    Assert(s._SkipLast(-20) .SequenceEqual(Arr(1,2,3,4,5)));
    
    Assert(s._TakeLast(2)   .SequenceEqual(Arr(4,5)));
    Assert(s._TakeLast(6)   .SequenceEqual(Arr(1,2,3,4,5)));
    Assert(s._TakeLast(-20) .SequenceEqual(new integer[0]));
    
  end;
end.
```

**Comment by miks1965** [comment]
В NetCore:
```
        public static IEnumerable<TSource> TakeLast<TSource>(this IEnumerable<TSource> source, int count)
        {
            if (source == null)
            {
                throw Error.ArgumentNull(nameof(source));
            }

            return count <= 0 ?
                Empty<TSource>() :
                TakeLastIterator(source, count);
        }

        private static IEnumerable<TSource> TakeLastIterator<TSource>(IEnumerable<TSource> source, int count)
        {
            Debug.Assert(source != null);
            Debug.Assert(count > 0);

            Queue<TSource> queue;

            using (IEnumerator<TSource> e = source.GetEnumerator())
            {
                if (!e.MoveNext())
                {
                    yield break;
                }

                queue = new Queue<TSource>();
                queue.Enqueue(e.Current);

                while (e.MoveNext())
                {
                    if (queue.Count < count)
                    {
                        queue.Enqueue(e.Current);
                    }
                    else
                    {
                        do
                        {
                            queue.Dequeue();
                            queue.Enqueue(e.Current);
                        }
                        while (e.MoveNext());
                        break;
                    }
                }
            }

            Debug.Assert(queue.Count <= count);
            do
            {
                yield return queue.Dequeue();
            }
            while (queue.Count > 0);
        }
    }
```

**Comment by SunSerega** [comment]
Этот выполнит несколько лишних выделений памяти. И прокрутка через `Queue<T>` будет не самым эффективным образом происходить тоже, куча лишних действий. Я вкладку оставил открытой, завтра сделаю тесты скорости для моего варианта, списков и очереди. Сегодня я уже плохо соображаю, могу что то пропустить.

**Comment by miks1965** [comment]
Не забывайте, что это промышленная текущая реализация

**Comment by MrFresnel** [comment]
> А вы попробуйте поставьте там значение по умолчанию... Компилятор не даёт, разработчики не говорят зачем это запрещено.

Новая Issue. Да, сорян, что не заметил такого запрета компилятором.

**Comment by SunSerega** [comment]
[тесты скорости](https://github.com/pascalabcnet/pascalabcnet/files/2813230/0.zip)

Результаты слегка колеблются, но в целом массивы чуть чуть быстрее списков и очередей.

**Comment by miks1965** [comment]
Спасибо!
У меня на компьютере все тесты дают одинаковый результат

**Comment by SunSerega** [comment]
Это какой? И - вы поэкспериментируйте ещё со строчкой 440:
```
        var counts := tests.ConvertAll(a-> *** );
```
Она выбирает какое число будет передаваться в качестве параметра, и похоже она сильно влияет на результат.

**Comment by miks1965** [comment]
При 
```
var counts := tests.ConvertAll(a-> 1);
```
![default](https://user-images.githubusercontent.com/10325391/52012936-e981f200-24ec-11e9-874a-f960e23b11c5.png)


При 
```
var counts := tests.ConvertAll(a-> a.Length - 1);
```
![default](https://user-images.githubusercontent.com/10325391/52012972-00284900-24ed-11e9-88f2-f3f6ac9cba43.png)
При 
```
var counts := tests.ConvertAll(a-> a.Length div 2);
```
![default](https://user-images.githubusercontent.com/10325391/52013054-2a7a0680-24ed-11e9-8770-89bf9e0b1fd9.png)

Разница туда-сюда 2%, так что я бы не заморачивался и использовал более короткий код.

Вообще, крутое исследование - не хотите статью опубликовать?

**Comment by miks1965** [comment]
Честно говоря, я об этом не задумывался. Но можно подумать - статья достойная.

Вон, на Хабре например ;-) - там вообще всё публикуют 

Более целевой вариант - у нас на сайте, но на нем вряд ли будет нужная аудитория

**Comment by miks1965** [comment]
Кстати, в NetCore в реализации с очередями нет ICollection<T>, а без этого куска кода
в случае a.Length div 2 вот что творится:
![default](https://user-images.githubusercontent.com/10325391/52014389-74182080-24f0-11e9-9e51-ee1c101b4493.png)

**Comment by SunSerega** [comment]
Аааа я понял, нет, я накосячил немного... Самая главная часть кода не вызывается из за этого куска, никогда, всё считается по короткой схеме. Само создание и заполнение того буфера. Вот тут:
```
        var tests := ArrGen(c2, i->ArrFill(Random(sma),1));
```
Надо сделать по другому:
```
///Обычное AsEnumerable не подойдёт, оно только копирует ссылку, а нам нужна yield последовательность
function ToEnumr<T>(self: sequence of T): sequence of T; extensionmethod;
begin
  yield sequence self;
end;

***

        var tests := ArrGen(c2, i->ArrFill(Random(sma),1).ToEnumr);
```
(Ну и там на строчке выбора `count` - `a.Length` превращается в `a.Count`. не важно что медленнее, измерения скорости в этот момент приостановлены)

[новые тесты](https://github.com/pascalabcnet/pascalabcnet/files/2814624/0.zip)

Без этого всегда вызывался одинаковый кусок кода, во всех 4 реализациях. Но он является лишь мелкой проверкой, которая не всегда будет полезна (хотя когда полезна - даёт огромное преимущество). А проверяли тесты в итоге не то.

И вот теперь преимущество массивов явно видно:
![image](https://user-images.githubusercontent.com/27270190/52015407-927b1d80-24ea-11e9-95a6-153e66d682b4.png)

Может ещё где то не так, но уже завтра лучше допроверю, ибо полночь...

**Comment by miks1965** [comment]
Ну я и говорю - самое главное - реализация в NetCore - плохая. Хотя о хорошей писали в комментах

**Comment by miks1965** [comment]
Вот код:
```
/// Возвращает последние count элементов последовательности
function TakeLast1<T>(Self: sequence of T; count: integer): sequence of T; extensionmethod;
begin
  if self=nil then raise new System.NullReferenceException('self');
  
  if count<1 then
  begin
    Result := System.Linq.Enumerable.Empty&<T>;
    exit;
  end;
  
  if self is ICollection<T>(var coll) then
  begin
    Result := coll.Skip(coll.Count-count);
    exit;
  end;
  
  var buff := new T[count];
  var enm: IEnumerator<T> := self.GetEnumerator;
  for var i := 0 to count-1 do
    if enm.MoveNext then
      buff[i] := enm.Current else
    begin
      Result := buff.Take(i);
      exit;
    end;
  
  var ind := 0;
  while enm.MoveNext do
  begin
    buff[ind] := enm.Current;
    ind := (ind+1) mod count;
  end;
  
  Result := buff.Skip(ind) + buff.Take(ind);
end;

begin
  var n := 100000000;
  var a := ArrRandom(n);
  Milliseconds;
  a.TakeLast(2).Println;
  MillisecondsDelta.Println;
  a.TakeLast1(2).Println;
  MillisecondsDelta.Println;
end.
```
Вот результаты:
```
90 40
154
90 40
298
```
Как вы объясните, что ваш хвалёный алгоритм работает в 2 раза медленнее плохого?

**Comment by miks1965** [comment]
Ладно. Нет ответа. В сухом остатке. После множества тестов теперешний алгоритм в одну строку работает быстрее. Закрываю.

**Comment by SunSerega** [comment]
У меня было много дел. А чтоб ответить мне надо ещё кучу тестов сделать, поэтому я пока не могу. Но сделаю.

**Comment by miks1965** [comment]
Хорошо. Здесь еще надо четко сформулировать, что мы оптимизируем. Память или быстродействие. И поскольку они конкурируют, то с какими весами.

**Comment by SunSerega** [comment]
Ок, я наконец нашёл время, а в месте с ним и источник оставания:

Создание буфера в `.Reverse` использует ещё 1 оптимизацию:
```
      ICollection<TElement> elements = source as ICollection<TElement>;
      if (elements != null)
      {
        length = elements.Count;
        if (length > 0)
        {
          array = new TElement[length];
          elements.CopyTo(array, 0);
        }
      }
```
Вот эта `.CopyTo` даёт большое преимущество если на вход подаётся `IList<T>`, потому что в таком случае копируется кусок памяти 1 махом, вместо копирования всех элементов. Это быстрее чем перебирать их энумератором:
```
/// Возвращает последние count элементов последовательности
function TakeLast1<T>(Self: sequence of T; count: integer): sequence of T; extensionmethod;
begin
  if self=nil then raise new System.NullReferenceException('self');
  
  if count<1 then
  begin
    Result := System.Linq.Enumerable.Empty&<T>;
    exit;
  end;
  
  if self is ICollection<T>(var coll) then
  begin
    if self is IList<T> then
    begin
      var buff := new T[coll.Count];
      coll.CopyTo(buff,0);          //на прямую скопировать в res - не хватает функционала. Но так всё равно быстрее чем через Reverse, потому что там то же самое произойдёт 2 раза
      var res := new T[count];
      System.Array.Copy(buff,coll.Count-count, res,0, count);
      Result := res;
      exit;
    end else
    begin
      Result := coll.Skip(coll.Count-count);
      exit;
    end;
  end;
  
  var buff := new T[count];
  var enm: IEnumerator<T> := self.GetEnumerator;
  for var i := 0 to count-1 do
    if enm.MoveNext then
      buff[i] := enm.Current else
    begin
      Result := buff.Take(i);
      exit;
    end;
  
  var ind := 0;
  while enm.MoveNext do
  begin
    buff[ind] := enm.Current;
    ind := (ind+1) mod count;
  end;
  
  Result := buff.Skip(ind) + buff.Take(ind);
end;

begin
  var n := 100000000;
  var a := ArrRandom(n);
  Milliseconds;
  a.TakeLast(2).Println;
  MillisecondsDelta.Println;
  Milliseconds;
  a.TakeLast1(2).Println;
  MillisecondsDelta.Println;
  readln;
end.
```
Таким образом время сравнялось.

Но из за ограничености общего `.CopyTo` - приходится создавать отдельный буфер. Но, хоть классов `IList` и много ([тут можно посмотреть все стандартные](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.ilist-1?redirectedfrom=MSDN&view=netframework-4.7.2)), но как вы и сказали, оптимизация во всех случаях не нужна. Из всех те классов - есть только 2 которые встречаются действительно часто, а точнее массив и список. Если оптимизировать под них:
```
/// Возвращает последние count элементов последовательности
function TakeLast1<T>(Self: sequence of T; count: integer): sequence of T; extensionmethod;
begin
  if self=nil then raise new System.NullReferenceException('self');
  
  if count<1 then
  begin
    Result := System.Linq.Enumerable.Empty&<T>;
    exit;
  end;
  
  if self is ICollection<T>(var coll) then
  begin
    
    if self is IList<T> then
    begin
      var res := new T[count];
      
      if self is System.Array(var arr) then
      begin
        System.Array.Copy(arr,arr.Length-count, res,0, count);
      end else
      if self is List<T>(var lst) then
      begin
        lst.CopyTo(lst.Count-count, res,0, count);
      end else
      begin
        var buff := new T[coll.Count];
        coll.CopyTo(buff,0);
        System.Array.Copy(buff,coll.Count-count, res,0, count);
      end;
      
      Result := res;
    end else
      Result := coll.Skip(coll.Count-count);
    
    exit;
  end;
  
  var buff := new T[count];
  var enm: IEnumerator<T> := self.GetEnumerator;
  for var i := 0 to count-1 do
    if enm.MoveNext then
      buff[i] := enm.Current else
    begin
      Result := buff.Take(i);
      exit;
    end;
  
  var ind := 0;
  while enm.MoveNext do
  begin
    buff[ind] := enm.Current;
    ind := (ind+1) mod count;
  end;
  
  Result := buff.Skip(ind) + buff.Take(ind);
end;

begin
  var n := 100000000;
  var a := ArrRandom(n);
  Milliseconds;
  a.TakeLast(2).Println;
  MillisecondsDelta.Println;
  Milliseconds;
  a.TakeLast1(2).Println;
  MillisecondsDelta.Println;
  readln;
end.
```
Теперь время выполнения моего метода просто **упало в 0**! И если заменить создание `a` на:
```
  var a := ArrRandom(n).ToList;
```
то тоже.

**Comment by SunSerega** [comment]
Теперь про память:
```
begin
  var n := 100000000;
  var a := ArrRandom(n);
  while true do
    foreach var o in a.TakeLast(2) do;
end.
```
Запустите эту программу и посмотрите в мониторинг ресурсов. Только для начала сядьте 😉.

У меня использование оперативной памяти прыгает с сумашедшей скоростью от 0.5 до 3 гигабайт. Хорошо я это на пк попробовал, ноут это быстро убило бы.

Это как раз из за тех 2 `.Reverse`, которые постоянно создают 2 буфера того же размера что и исходный массив. И как я сказал выше, эти выделения и потом освобождения памяти влияют на производительность, поэтому в предыдущем сообщении время первого теста колебалось.

В то же время мой метод:
```
/// Возвращает последние count элементов последовательности
function TakeLast1<T>(Self: sequence of T; count: integer): sequence of T; extensionmethod;
begin
  if self=nil then raise new System.NullReferenceException('self');
  
  if count<1 then
  begin
    Result := System.Linq.Enumerable.Empty&<T>;
    exit;
  end;
  
  if self is ICollection<T>(var coll) then
  begin
    
    if self is IList<T> then
    begin
      var res := new T[count];
      
      if self is System.Array(var arr) then
      begin
        System.Array.Copy(arr,arr.Length-count, res,0, count);
      end else
      if self is List<T>(var lst) then
      begin
        lst.CopyTo(lst.Count-count, res,0, count);
      end else
      begin
        var buff := new T[coll.Count];
        coll.CopyTo(buff,0);
        System.Array.Copy(buff,coll.Count-count, res,0, count);
      end;
      
      Result := res;
    end else
      Result := coll.Skip(coll.Count-count);
    
    exit;
  end;
  
  var buff := new T[count];
  var enm: IEnumerator<T> := self.GetEnumerator;
  for var i := 0 to count-1 do
    if enm.MoveNext then
      buff[i] := enm.Current else
    begin
      Result := buff.Take(i);
      exit;
    end;
  
  var ind := 0;
  while enm.MoveNext do
  begin
    buff[ind] := enm.Current;
    ind := (ind+1) mod count;
  end;
  
  Result := buff.Skip(ind) + buff.Take(ind);
end;

begin
  var n := 100000000;
  var a := ArrRandom(n);
  Milliseconds;
  a.TakeLast(2).Println;
  MillisecondsDelta.Println;
  Milliseconds;
  a.TakeLast1(2).Println;
  MillisecondsDelta.Println;
  readln;
end.
```
Держится стабильно на 400 мегабайтах, и виндоус не выделяет дополнительной памяти а лишь использует небольшой буфер в несколько мегабайт, потому что те единственные массивы что создаёт, по 2 элемента, в него помещаются:

![image](https://user-images.githubusercontent.com/27270190/52782313-69649c00-3057-11e9-8d2d-bef76e5b635e.png)

**Comment by SunSerega** [comment]
Вот обновлённая версия этих методов, с оптимизацией для массивов и списков.

[0.zip](https://github.com/pascalabcnet/pascalabcnet/files/2864751/0.zip)

Обратите внимание, `TakeLast` там не так же самая что в предыдущих 2 сообщениях! Там не хватало защиты от дурака в паре мест.

Как в случае `(new byte[3]).SkipLast(5)` - версия из предыдущих 2 сообщений выдаст ошибку, а та что в архиве - вернёт копию массива, который в неё передали, по аналогии с обычными `.Take`/`.Skip`.

**Comment by miks1965** [comment]
Оптимизацию для массивов и списков можно сделать и у нас - тогда будет проверка на IList и невыделение памяти в этом случае с мгновенной работой.

Вы проверяете TakeLast(5) - а вы проверьте TakeLast(n-2) - и в вашем алгоритме будет выделяться память, сравнимая с n.

**Comment by SunSerega** [comment]
> Оптимизацию для массивов и списков можно сделать и у нас

Можно, но при чём тут это? случай с `yield`-последовательностью у меня всё равно и быстрее, и памяти меньше выделяет. При всех возможных значениях.

> и в вашем алгоритме будет выделяться память, сравнимая с n.

Я вот эту часть не совсем понял. Где что сравнивать будет?

Про `.TakeLast(5)` я вообще написал в плане выдачи правильного ответа. В архиве выше есть тесты для всех ситуаций.

**Comment by miks1965** [comment]
Посмотрите. У вас выделяется память в count элементов. Если count=n-2, то это примерно n - как у нас.

**Comment by SunSerega** [comment]
> Если count=n-2, то это примерно n - как у нас.

Нет, у вас минимум `n*2`, потому что `.Reverse` вызывается 2 раза.

Но второй раз он вызывается для `yield` последовательности, поэтому там происходит куча лишних выделений памяти (буфер не знает сколько в итоге будет элементов и поэтому ему приходится выделять сначала на 4 элемента, потом на 8 и т.д). Поэтому там ещё больше.

**Comment by SunSerega** [comment]
Ну так что теперь то?

**Comment by miks1965** [comment]
Пытаюсь разобраться в вашем коде.
Вот зачем Вы 
```
lst.CopyTo(ind_st, res,0, count);
```
здесь копируете в дополнительный массив? Почему нельзя пройтись - yieldами вернуть?

**Comment by SunSerega** [comment]
> Почему нельзя пройтись - yieldами вернуть?

Тут энумераторы медленно работают. В несколько десятков раз. Сами попробуйте, заменить на
```
Result := lst.Skip(ind_st);
```
не сложно, но тогда полностью пропадает смысл писать отдельный код для списков и массивов, ибо их преимущество сразу пропадает.

**Comment by miks1965** [comment]
Посмотрите дописанный комментарий выше

**Comment by miks1965** [comment]
Нет, тут я имел в виду, что вместо lst.Skip(ind_st) написать хелпер, который начинает возвращать значения в ILIst с ind_st. И преимущество не пропадает.

Но - еще раз говорю - не нужно делать это преимущество, потому что в стандартной библиотеке его нигде нет.

**Comment by SunSerega** [comment]
> Я смотрю реализацию Skip например - так вот, она пропускает значения, не проверяя, что это - массив, список или IList

Потому что брать/пропускать элементы из начала последовательности легко. Они не могут создать Огромные ямы в оперативной памяти как ваша реализация через `.Reverse`.

Хотя почему они чтение `IList`-ов не оптимизировали - не понятно. Это и к коду не добавило бы сильно, максимум раза в 2 больше стало бы. Вполне возможно что и просто лень.

> не нужно делать это преимущество, потому что в стандартной библиотеке его нигде нет.

Я с утверждениями типа "они делают плохо значит и нам можно" принципиально не согласен. Но тут ещё 1 фактор - в вашей реализации была эта оптимизация (внутри `.Reverse`). Только чтоб не отставать от той реализации ни в чём я и добавил эту часть.

В принципе - я не настаиваю чтоб оставлять оптимизацию под массивы и списки. Но она хуже не делает. По скорости лучше. По памяти - можно действительно хелпер написать, сейчас попробую. И кол-ву кода, за который вы зачем то так держитесь - проекты на несколько тысяч строк компилируются на стареньких компьютерах за меньше секунды. Так что пара сотен строк ничего не изменит.

**Comment by miks1965** [comment]
Нет, смотрите - мы будем выглядеть глупо. 56 функций будут не учитывать списки, а две крайне редких причем нестандартных - вдруг будут. Это неправильно делать так неравномерно.

А реализацию с Reverse мы заменим. Просто еще в голове не уложилось, как

**Comment by SunSerega** [comment]
> мы будем выглядеть глупо

С чего вы решили?)) Кто туда вообще будет смотреть?

И - я не против в свободное время по 1 оптимизировать все методы из PABCSystem. И я уже не раз показывал это желание.

---

Насчёт хелпера. Да, он не только не медленнее - а ещё и быстрее, раз в 7-8! Ну и памяти, конечно, вообще почти не надо: 
[1.zip](https://github.com/pascalabcnet/pascalabcnet/files/2872446/1.zip)

По аналогии и с `SkipLast`. Которое, почему то, было медленнее вашего... Забыл протестировать, наверное. Но теперь моё таки быстрее:
[1.zip](https://github.com/pascalabcnet/pascalabcnet/files/2872455/1.zip)

При чём удалось сильно упростить, потому что скорость функции-хелпера меньше обычного `.Take`, если мы уже знаем сколько элементов (это уже проверено).

---

В итоге я подчистил код, теперь на хелперы уходит 40 строк и ещё 80 на сами функции:
[0.zip](https://github.com/pascalabcnet/pascalabcnet/files/2872462/0.zip)

Хотелось бы заметить что с хелперами вместо копирования в буфер - моя `TakeLast` отстаёт от вашей если давать ей неадекватно большие значения. Оно и понятно, `.MoveNext` вызывается в 2 раза чаще, потому что хелпер создаёт дополнительный энумератор.

**Comment by miks1965** [comment]
А нельзя YieldLast<T>(a: IList<T> только оставить? Зачем перегружать? Оставьте одну версию - это будет так же эффективно

**Comment by miks1965** [comment]
Сделал
