### ISSUE TITLE
.cs и .vb файлы в проектах имеют иконку .pas файлов

### ISSUE THREAD

**Issue by MrFresnel** [pascalabcnet/pascalabcnet#1689]
![image](https://user-images.githubusercontent.com/42812113/52061896-7f1a9180-2580-11e9-8be9-8cd0e503c120.png)

Предлагаю для них вообще иконку не отображать.

**Comment by ibond84** [comment]
Ну, на иконке паскаль не написан. Без иконки будет смотреться коряво. А так как среда только для паскаля, то желания для всех языков рисовать иконки никакого нет.
