### ISSUE TITLE
Сделать оператор возведения в степень **

### ISSUE THREAD

**Issue by ibond84** [pascalabcnet/pascalabcnet#169]

**Comment by miks1965** [comment]
А степень целая или вещественная?

**Comment by ibond84** [comment]
вещественная

**Comment by miks1965** [comment]
А чему будет равно 0**5?

**Comment by ibond84** [comment]
Ну 0. Не вижу проблемы.

**Comment by miks1965** [comment]
Предлагаю для прозрачности реализовать оператор вначале в PABCSystem, а потом связать его со степенью **

**Comment by miks1965** [comment]
А, ну, собственно, надо связать этот оператор с power - и всё. Можно даже чтобы для целых он вовращал целое

**Comment by AlexRnD61** [comment]
power действительно отлично написан, он корректно возводит в целые степени и неположительные числа, в отличие от случаев использования формулы exp(b*ln(a)).
Операцию ** было бы очень приятно увидеть, особенно если её можно будет перегружать.

**Comment by AlexRnD61** [comment]
Эх, год уже идея висит. А жаль!

**Comment by ibond84** [comment]
сдeлал
