### ISSUE TITLE
Позволить использовать begin-end и Result для геттеров расширенных свойств

### ISSUE THREAD

**Issue by MrFresnel** [pascalabcnet/pascalabcnet#1693]
Позволить использовать begin-end и Result для геттеров расширенных свойств.

**Comment by miks1965** [comment]
Это обсуждали примерно три раза.

Формат расширенных свойств такой:

```
property Prop: тип read выражение write оператор;
```

**Comment by MrFresnel** [comment]
Извините, но почему?

**Comment by MrFresnel** [comment]
То есть улучшать расширенные свойства уже Вы не хотите?
