### ISSUE TITLE
Не подсвечивать ключевые слова после точки

### ISSUE THREAD

**Issue by AIexandrKotov** [pascalabcnet/pascalabcnet#1700]
Продолжение #1687 
Код:
```pas
type
  T = static class
    public static &do: real;
  end;

begin
  T.do := 0;
end.
```
do в 7 строке подсвечивается.

**Comment by miks1965** [comment]
У нас подсветчик синтаксиса не контекстный к сожалению

**Comment by AIexandrKotov** [comment]
@miks1965 , в подсветке же можно сделать, если после точки имя идёт. Как с амперсандом сделали.

**Comment by AIexandrKotov** [comment]
Можно просто убрать и точку из 14й строки, а в кейворды BeginEnd добавить "end.". Всё равно точка нигде больше не должна подсвечиваться. Верно, @ibond84 ?

**Comment by AIexandrKotov** [comment]
Хотя нет. Тогда не будут подсвечиваться стандартные типы, если после них идут точки (integer.MaxValue, например). Плохое решение проблемы. Если у вас нет идей как это реализовать без костылей — закрывайте issue.
