### ISSUE TITLE
IDE падает при наследовании интерфейса IName<T> от IName, расположенных в разных файлах

### ISSUE THREAD

**Issue by MrFresnel** [pascalabcnet/pascalabcnet#1703]
IDE падает при наследовании интерфейса IName<T> от IName, расположенных в разных файлах.

[Одноименные интерфейсы ломают IDE.zip](https://github.com/pascalabcnet/pascalabcnet/files/2831678/IDE.zip)

**Comment by miks1965** [comment]
Это Intellisense роняет среду
