### ISSUE TITLE
Неожиданная ошибка при реализации классом 2 интерфейсов, наследующих от общего

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#1707]
```
type
  I0 = interface end;
  
  I1 = interface(I0) end;
  I2 = interface(I1) end;
  
  t1 = class(I0, I2) end;
  //t2 = class(I1, I2) end;//тоже вызывает ошибку, но "I0, I1" не вызывает
  
begin end.
```

**Comment by miks1965** [comment]
Измените заголовок чтобы было понятно, что на правильную программу выдается неправильное сообщение

**Comment by SunSerega** [comment]
Я не совсем понимаю что сделать, можете сами?

**Comment by MrFresnel** [comment]
Насколько я понимаю, заголовок предлагают изменить на нечто подобное: `Неожиданное сообщение об ошибке при попытке реализовать типом T два интерфейса IB и IC, наследуемых от IA`. Под T подразумевается либо класс, либо запись (с записями тоже воспроизводится ошибка).

**Comment by AIexandrKotov** [comment]
![image](https://user-images.githubusercontent.com/44296606/52338602-e40c3680-2a1b-11e9-9354-cab9ec021ec6.png)
Решил проверить на версии 3.4.2.1883 (от 24.11.18) — всё работает. Скорее всего, вы допустили какую-то ошибку, когда исправляли циклическое наследование (хотя об этом говорила и сама ошибка).
