### ISSUE TITLE
$omp не работает с loop

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#1708]
```
begin
  {$omp parallel for}
  loop 5 do
  begin
    ;
  end;
end.
```
В этом коде $omp игнорируется, хотя его вполне можно сделать рабочим, потому что в `loop`, как и в `for`, известно кол-во повторений.

**Comment by miks1965** [comment]
Написано же - parallel for, а не parallel loop

По существу. Это никто переделывать не будет. Эта работа была закончена человеком 7 лет назад.
