### ISSUE TITLE
Вложенные лямбды неистово жрут память

### ISSUE THREAD

**Issue by AIexandrKotov** [pascalabcnet/pascalabcnet#1711]
Файл: [test.zip](https://github.com/pascalabcnet/pascalabcnet/files/2838074/test.zip)

![98](https://user-images.githubusercontent.com/44296606/52370403-d5497200-2a63-11e9-842f-8a4590b68b03.png)

**Comment by miks1965** [comment]
А с какого уровня вложения?

**Comment by AIexandrKotov** [comment]
В лямбдах KTX'а 18 лямбд - это 2,5 гигабайта на компиляцию, выше уже не компилировалось вообще (я мало ждал). Здесь расплодил лямбды для наглядности.

**Comment by miks1965** [comment]
А что такое KTX?

**Comment by AIexandrKotov** [comment]
Это мой модуль. Изначально хотел кинуть это тестирование, но потом решил сделать простой пример.
[Program100.zip](https://github.com/pascalabcnet/pascalabcnet/files/2838435/Program100.zip)
Разумеется, лично мне не нужны 20 вложенных лямбд. Но мне почему-то кажется, что они не должны столько съедать памяти. @SunSerega думает, что скорее всего не очищаются какие-то буферы, ведь потребление памяти возрастает с геометрической прогрессией.

**Comment by miks1965** [comment]
Вообще любой приличный компилятор - Тьюринг-полный. Это значит, что на нем можно написать программу, которая будет компилироваться нарастающе долго. У нас работал специалист по метапрограммированию на C++ - так вот - он ездил на крутую научную конференцию и делал там доклад, как решать задачу о расстановке восьми ферзей на шахматной доске на этапе компиляции на C++. Так вот - он жаловался, что один из компиляторов так и не доводил компиляцию до конца за обозримое время.

По поводу вашего теста. Посчитайте пожалуйста приемлемое количество вложенных лямбд по времени и по памяти - мы просто ограничим это число.

**Comment by SunSerega** [comment]
А как насчёт перед тем как прикреплять костыль всё же посмотреть что с этим можно сделать?

Разумеется не всё можно оптимизировать. И тип с несколькими тысячами шаблонных параметров будет лагать. Но это как раз приемлемо, а вот сжирание 7 гигабайт на < 20 лямбдах - это не дело.

И обратите внимание, я говорю именно про память сейчас, производительность это другое дело.

Если где то выделяется аж так много памяти - значит где то создаётся куча копий одних и тех же данных, иначе им неоткуда взяться.

Или скажите как из студии можно запустить компилятор, я сам посмотрю на каком моменте сжирается память.

**Comment by AIexandrKotov** [comment]
Максимальное количество вложенных лямбд будет зависеть от аппаратной мощности. По поводу геометрической прогрессии - в инициализации (вложенных) записей у вас ведь такая же фигня. Может, оно связано? Я понимаю, что вам совсем не хочется переделывать алгоритм, <b>но вдруг</b>?

```
x Лямбд = y ГБ_оперативной_памяти (z секунд_компиляции)
17 = 1,2 (25,8)
18 = 2,37 (51,4)
19 = 4,7 (105)
```

На глаз, ибо измерить затраты памяти никак, кроме как на глаз, невозможно. Время компиляции зависит от аппаратной мощности моего ноута.

`Тогда теоретически 20 - 9,3 гб и 208,5 секунд; 21 - 18,4 гб и 419 с; а 22 - 36,4 гб и 842 секунды.`

Оборудование:
<b>CPU</b>: Inter Core i3-2330M 2 cores 4 threads 2,2 GHz
<b>RAM</b>: 8 GB RAM 1333 MHz CL-9 (9-9-9-24)
<b>OS</b>: Windows 7 Home Basic SP1 64 bit

Не вырубил отладку, но, как я понял и протестировал после, она не повлияла от слова совсем.

Если и ограничивать лямбды, то двадцатью ( <b>20</b> ). Но я бы переделал алгоритм) Если бы, конечно, понимал в этом что-то... Надеюсь на вас и на @SunSerega ))

**Comment by miks1965** [comment]
Посмотрим. Алгоритм сложный и это - непонятно за чем гнаться.

Еще раз повторю, что в случае вложенного чего-то это - взаимодействие каждого с каждым. Это память и время. Если 
вложенности нет, время =1, 
одна вложенность - время = 2, 
две вложенности - время = 4 
и т.д. - геометрическая прогрессия.

20 вложенных - это бессмысленное число - в реальных программах 3 вложенных как максимум. Переделывается что-то на ситуации, которая может возникнуть в реальной программе. Класть компилятор на лопатки - это отдельный спорт, мы в него не играем.

Еще раз - прошу посмотреть, что там в C#.

**Comment by miks1965** [comment]
Посмотрел. 10 вложенных подойдёт?

![default](https://user-images.githubusercontent.com/10325391/52391681-8fb29680-2aaf-11e9-855e-f09b1b76eaed.png)

**Comment by SunSerega** [comment]
> Еще раз - прошу посмотреть, что там в C#.

Подождёте несколько дней - я посмотрю. Для таких тестов хотя бы 8 гигов оперативки надо, иначе по скорости сбивается, да и нет желания лишний раз доводить комп до зависания винды.

И ещё раз, пожалуйста, скажите как запустить компилятор из студии, я сам не находил какой файл (.sln) в ней надо запускать. Я отлажу, посмотрю.

Ну это реально бред, некуда там аж столько оперативки тратить, даже если всё на всё ссылается. Максимум, в случае не эффективного графа получаем 19*19 = 361 соединений, а не 875000000, которые помещаются в те 7 гигов.

**Comment by miks1965** [comment]
Должен заметить, что мечты будут оставаться мечтами пока к проекту не подключится больше разработчиков, пишущих и исправляющих код и предлагающих pull requestы. 

Это - наши мечты

**Comment by ibond84** [comment]
Он че там, всю память копирует?

**Comment by miks1965** [comment]
Там действительно неэффективный алгоритм и экспоненциальная сложность - при каждой вложенной лямбде время работы возрастает в 2 раза. Подозреваю, что и память тоже. 

Пока разбираюсь, можно ли что-то сделать заплатками кода или надо переписывать весь алгоритм. В syntax_tree_visitor.cs  в строках 6900 и 6963 происходят вызовы convert_strong(en) для одного выражения - это главный источник, и непонятно, можно ли от этого избавиться.

**Comment by miks1965** [comment]
Для такой программы 
```
procedure p(i: integer->integer);
begin
  
end;

begin
  p(x->x);
end.
```

**Comment by ibond84** [comment]
>Файл: test.zip
У меня переполнение стека возникает. И это не баг

**Comment by AIexandrKotov** [comment]
Переполнение стека это часть рантайма, а issue про геометрически возрастающих время и память при компиляции.

**Comment by ibond84** [comment]
Ну я откомпилировал test0.pas. Память не расходуется. Компилятор просто упал с переполнением стека

**Comment by SunSerega** [comment]
А у компилятор сожрал 10 гигов оперативки, тем самым убив браузер, поэтому мне пришлось его пристрелить.
