### ISSUE TITLE
Должно работать - x->x.Print() не распознаётся как лямбда-процедура

### ISSUE THREAD

**Issue by miks1965** [pascalabcnet/pascalabcnet#172]
```
type Shape = class
  procedure Print; virtual;
  begin
    writeln('Shape');
  end;
end;

begin
  var l := new List<Shape>;
  l.Foreach(x->x.Print());
end.
```

Program1.pas(10) : Ожидалась функция, встречена процедура PascalABCCompiler.TreeRealization.common_method_node

Ещё и сообщение об ошибке дурацкое. Что-то где-то слетело!

**Comment by ibond84** [comment]
>Ещё и сообщение об ошибке дурацкое

Ну это один программист передавал объект common_method_node в string.Format...

**Comment by ibond84** [comment]
А это вообще реализовано? Когда надо использовать procedure?
Например в этом коде без procedure не компилируется...
var proc: Shape->() := procedure (x) -> x.Print();

**Comment by miks1965** [comment]
А так работает:

```
type Shape = class
  procedure Print; virtual;
  begin
    writeln('Shape');
  end;
end;

begin
  var l := new List<Shape>;
  l.Foreach(x->Print(x));
end.
```

**Comment by miks1965** [comment]
Да, проблема понятна. В x->x.Print() 
x еще не выведено к моменту когда принимается решение, лямбда-функция это или лямбда-процедура

Чтобы это сделать необходимо всё переделывать и выносить это на более поздний уровень. 
даже не знаю, стОит ли с этим возиться. Дело в том, что при одном x x.Print() может быть процедурой, при другом x - функцией или не существовать вообще

**Comment by miks1965** [comment]
Вообщем, это самый сложный алгоритм, связанный еще и с выбором перегруженной версии при наличии дженериков
