### ISSUE TITLE
Показывать предупреждение, если имя интерфейса не начинается с "I"

### ISSUE THREAD

**Issue by MrFresnel** [pascalabcnet/pascalabcnet#1721]
```
type
  Name = interface
  end;

begin
end.
```
Тест предупреждения может быть таким:
> Имя интерфейса рекомендуется начинать с "I"

В Visual Studio отображается предупреждение при нарушении этого соглашения именования интерфейсов:

![image](https://user-images.githubusercontent.com/42812113/52518818-15764380-2c62-11e9-849e-ab9dd240f1be.png)

**Comment by miks1965** [comment]
Я закрою этот Issue. Вот почему. Если этим заниматься, то не эпизодически, вырывая из стандарта кода C# наиболее понравившиеся вещи, а системно. Т.е. делать предупреждения по стандарту кода, делать опции в среде и проч.

Посмотрите для начала список всех предупреждений, которые есть в C#
