### ISSUE TITLE
Отображать доступные сниппеты в анализаторе кода 

### ISSUE THREAD

**Issue by MrFresnel** [pascalabcnet/pascalabcnet#1723]
Предлагаю отображать доступные сниппеты в анализаторе кода. В Visual Studio 2017 это выглядит так:
![image](https://user-images.githubusercontent.com/42812113/52524145-dcae8c80-2caa-11e9-9d61-57af80950060.png)

**Comment by miks1965** [comment]
Предложения по улучшению среды без поддержки в виде Pull Request просим не писать в Issue
