### ISSUE TITLE
Запретить подсветку всего, кроме парных скобок, во всех не .pas/.cs/.vb файлах

### ISSUE THREAD

**Issue by MrFresnel** [pascalabcnet/pascalabcnet#1725]
Сейчас это не запрещено:
![image](https://user-images.githubusercontent.com/42812113/52534322-3cf80980-2d51-11e9-9720-9eddf3c79946.png)

Парные скобки подсвечивать - это еще нормально, но class-end и тому подобное в данном случае подсвечивать неправильно.

**Comment by miks1965** [comment]
Это мелочёвка. Примем только в виде Pull Request.
