### ISSUE TITLE
Многострочные перечисления неправильно форматируются

### ISSUE THREAD

**Issue by MrFresnel** [pascalabcnet/pascalabcnet#1727]
Исходный код:
```
type
  Enum = (X,
    Y,
    Z
  );

begin
end.
```
После форматирования:
```
type
  Enum = (X,
    Y,
    Z);

begin
end.
```
`);` должно оставаться ровно под первой буквой названия перечисления, а не слипаться с последним его элементом.

**Comment by SunSerega** [comment]
Уже исправляли в #886. Добавьте пожалуйста для этого тесты, а то снова сломается.

**Comment by ibond84** [comment]
>После форматирования ничего не меняется, хотя, если перечисление многострочное, то должен быть соблюдён принцип `один элемент - одна строка`.

Неправильно. Сколько элементов в строке, решает разработчик, и форматтер не должен ничего там менять.

**Comment by ibond84** [comment]
>Уже исправляли в #886. Добавьте пожалуйста для этого тесты, а то снова сломается.

Ну, вы посмотрите сначала, что там исправлялось.

**Comment by miks1965** [comment]
Единые конструкции, разбитые пользователем на несколько строк, не будем форматировать по чьему-то требованию. Как форматировать - это вкусовщина. Лично мне нравится как есть.

**Comment by SunSerega** [comment]
Когда пересекается несколько видов предпочтений в форматировании - форматирование не должно ничего менять.
По крайней мере такой политики придерживался @ibond84, на сколько я помню.

И - допустим если `X` находится на одной строчкой с первой скобочкой, можно расценивать что это следующий стиль:
```
type
  Enum = (X,
          Y,
          Z);

begin end.
```
Который довольно распространён.

Но этот следующий так же распространён:
```
type
  Enum = (
    X,
    Y,
    Z
  );

begin end.
```
Поэтому его ломать точно не должно.

**Comment by miks1965** [comment]
Здесь логика такая. Форматируется начало и концовка. Остальное нет.
