### ISSUE TITLE
Подсказка анализатора кода не смещается автоматически к месту курсора после вставки сниппета 

### ISSUE THREAD

**Issue by MrFresnel** [pascalabcnet/pascalabcnet#1728]
Пусть в `template.pct` есть:
```
[class]
type
  T| = class
  end;
```
Открываем IDE, набираем `class` и нажимаем `Shift+Space`:
![image](https://user-images.githubusercontent.com/42812113/52535228-c52fdc00-2d5c-11e9-8bdc-2f869f07ae5a.png)

Это особенно мешает, когда курсор смещается вниз, так, что подсказка анализатора кода закрывает набираемый текст.

**Comment by miks1965** [comment]
Это мелочёвка, которая ещё и ресурсоёмко реализуется. Примем если опубликуете Pull Request

**Comment by MrFresnel** [comment]
Как говорил мой знакомый: «Качество ПО складывается из мелочей.».
