### ISSUE TITLE
Позволить множественные | в сниппетах

### ISSUE THREAD

**Issue by MrFresnel** [pascalabcnet/pascalabcnet#1729]
Точнее, чтобы можно было писать так:
```
[prop]
public auto property |: |;
```
И после вставки сниппета можно было переключаться с ввода имени на тип свойства и наоборот через `Tab` и `Shift+Tab`. Как в Visual Studio 2017 со сниппетом `prop` и многими другими.

**Comment by miks1965** [comment]
Мы не принимаем Issue по улучшению среды программирования, а лишь по исправлению ошибок и неточностей.

Улучшение среды программирования мы принимаем лишь в одном виде - в виде Pull Requests
