### ISSUE TITLE
Позволить сворачивать секции public/internal/protected/private с более чем одним членом класса или записи

### ISSUE THREAD

**Issue by MrFresnel** [pascalabcnet/pascalabcnet#1730]
Позволить сворачивать секции public/internal/protected/private. Такое возможно в Lazarus 1.8.4:

![image](https://user-images.githubusercontent.com/42812113/52536388-f44d4a00-2d6a-11e9-926e-15ac98963695.png)

Можно, конечно, на данный момент, оборачивать секции в регионы для сворачивания и разворачивания, но они загружают код.

**Comment by SunSerega** [comment]
Это не везде подойдёт, я вот пишу отдельный `public`, `private` и т. д. для каждого элемента класса, в таком случае точки сворачивания только помешают.

Предлогаю показывать точку сворачивания если под одним модификатором доступа идёт >1 строчки с элементами.

**Comment by miks1965** [comment]
Мы не принимаем Issue по улучшению среды программирования, а лишь по исправлению ошибок и неточностей. 

Улучшение среды программирования мы принимаем лишь в одном виде - в виде Pull Requests
