### ISSUE TITLE
yield sequence не запрещён внутри with, в отличие от yield

### ISSUE THREAD

**Issue by MrFresnel** [pascalabcnet/pascalabcnet#1731]
```
type
  T = record
  end;

function F(): sequence of byte;
begin
  with new T() do
    yield sequence Seq&<byte>(); // <--
end;

begin
end.
```
Компилируется успешно.

**Comment by miks1965** [comment]
Исправили

**Comment by SunSerega** [comment]
([тут](https://github.com/pascalabcnet/pascalabcnet/commit/bfc6ac8a846def6ba835ba7ed8b7da72174a6f06))

**Comment by SunSerega** [comment]
А в чём, кстати, проблема разрешить `yield` с `with`? Пример из этой issue вроде нормально работал. Проблемы возникают в более сложных случаях?

**Comment by miks1965** [comment]
Там с захватом дела плохи

**Comment by SunSerega** [comment]
Может то давно было, но уже и исправили всё? Вот до вашего комита это работает:
```
type
  T = record
    s: sequence of byte;
  end;
  
function F: sequence of byte;
begin
  
  with new T() do
    yield sequence s;
  
end;

begin end.
```
И если поставить `s` в локальные/глобальные переменные, или даже в параметры `F` - всё компилируется без проблем.

**Comment by miks1965** [comment]
Мы не хотим совмещать with с крутыми новыми конструкциями. Это может спровоцировать ошибки в этом месте в будущем. Мы уже встречали ошибочное взаимодействие двух сахарных и одной устаревшей конструкции. Причем попарно они дружили.
