### ISSUE TITLE
Обобщения из PABCSystem могут использоваться в with

### ISSUE THREAD

**Issue by MrFresnel** [pascalabcnet/pascalabcnet#1732]
Обобщения могут использоваться в with:
1) `new TSome&<T, T2, ...>` -  если псевдоним TSome есть в PABCSystem.
1) `SomeFunction&<T, T2, ...>(arg1, arg2, ...)` -  если SomeFunction есть в PABCSystem.
```
type
  TSomeGeneric<T> = record // Или class.
  end;

function F<T>() := new TSomeGeneric<T>();

procedure P();
begin
  //with F&<byte>() do // Ok.
  //with new TSomeGeneric<byte>() do // Ok.
  with new List&<byte>() do // Должна быть ошибка.
  with Lst&<byte>() do // Должна быть ошибка.
end;

begin
end.
```

**Comment by SunSerega** [comment]
А с чего вообще выдавать ошибку в этих случаях?

**Comment by MrFresnel** [comment]
Ибо обобщения запрещали в with, но не до конца, видимо. Раскомментируй строки и увидишь ошибку компиляции.

**Comment by SunSerega** [comment]
Я про первые 2 строки и говорил.

**Comment by MrFresnel** [comment]
Аа... На форуме помню эта тема обсуждалась давно.

**Comment by miks1965** [comment]
А что, разве есть ошибка с этим кодом?

**Comment by miks1965** [comment]
Вообщем закрываю пока не найдёте весомых аргументов

**Comment by SunSerega** [comment]
По моему проблема в обратном, то что `with` не работает с пользовательскими обобщениями:
```
type
  t1<T> = class end;

begin
  with new t1<byte> do
end.
```
Потому что вы перестарались с запретами.

**Comment by miks1965** [comment]
Не работает. Какую?

**Comment by SunSerega** [comment]
Ну, с обобщениями из `PABCSystem` - `with` работает без проблем. Почему тогда для остальных не разрешить? Не все же типы в `PABCSystem` волшебные, иначе ломалось бы.

**Comment by miks1965** [comment]
Нет. With насколько я помню работает без проблем с полностью откомпилированными обобщениями. Из .NET. А с теми, которые созданы на Паскале, - нет. Мы даже разбираться не стали почему. With - это порядочная гадость

**Comment by MrFresnel** [comment]
Аа... Вот как ситуация обстоит. Спасибо за пояснение.
