### ISSUE TITLE
yield не считает синонимы sequence последовательностями

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#1733]
```
type
  seqT = sequence of byte;

function f1: seqT;
begin
  yield 0;
end;

function f2: IEnumerable<byte>;
begin
  yield 0;
end;

begin end.
```
Для обоих функций пишет:
`Функции с yield должны возвращать последовательность`

**Comment by MrFresnel** [comment]
С первым согласен - ошибка. Со вторым - нет. Разработчики, насколько помню, осознанно запретили использование `IEnumerable<T>`, как в данном случае, напрямую. Она из причин - простота объяснения новичкам последовательностей - избавляет от нужды объяснять что такое интерфейсы и что такое `IEnumerable<T>`.

**Comment by SunSerega** [comment]
> простота объяснения новичкам последовательностей - избавляет от нужды объяснять что такое интерфейсы

Ну так а кто им мешает не говорить что так вообще можно? Зато для продвинутых, и для тех кто на других .Net языках програмил - самое то так объявлять.
