### ISSUE TITLE
Анализатор кода показывает AliasName<T, T2, ...> = T в модуле при использовании обобщения из dll

### ISSUE THREAD

**Issue by MrFresnel** [pascalabcnet/pascalabcnet#1735]
Анализатор кода показывает AliasName<T, T2, ...> = T в модуле при использовании обобщения из dll.

Код библиотеки:
```
namespace PascalABCNETTest
{
    public class SomeGeneric<T1, T2>
    {
    }
}
```
Код модуля:
```
{$reference PascalABCNETTest.dll}
unit &Unit;

type
  TGeneric<T1, T2> = PascalABCNETTest.SomeGeneric<T1, T2>;

end.
```
![image](https://user-images.githubusercontent.com/42812113/52679817-5bbff100-2f47-11e9-9b78-d859610bc981.png)

Это работает для обобщённых: классов, структур и интерфейсов.

**Comment by ibond84** [comment]
Исправлено
