### ISSUE TITLE
Неправильная ошибка, при отсутствии перегрузки and для nil и записи

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#1738]
```
type
  t1 = record
    
    static function operator and(a: object; b: t1) := 0;
    
  end;

begin
  var a := object.Create and t1.Create;//ok
  var b := nil and t1.Create;          //ok
  var c := nil and object.Create;      //Правильная ошибка: Операция 'and' не применима к типам nil и object
  var d := nil and true;             //Неправильная ошибка: Операции над размерными типами и nil недопустимы
end.
```
В последнем случае надо выдавать так же как в предпоследнем:
`Операция 'and' не применима к типам nil и boolean`

**Comment by miks1965** [comment]
Почему? Не придумывайте. Операции над размерными типами и nil недопустимы. Всё чётко

**Comment by SunSerega** [comment]
Посмотрите внимательно на вторую строчку. Это операция `and`, произведённая над `nil` и размерным типом (записью). И там всё законно. Поэтому последняя ошибка неправильная.

**Comment by miks1965** [comment]
Ну конечно. Вы так определили. Это можно. 

Сообщение об ошибке не предполагает переопределённые операции.
