### ISSUE TITLE
Не работает with для методов расширения

### ISSUE THREAD

**Issue by ibond84** [pascalabcnet/pascalabcnet#174]

**Comment by ibond84** [comment]
ух ты, в интелисенс все работает

**Comment by miks1965** [comment]
Запретить with в методах расширения - и всё тут. Там в каком-то визиторе есть запрос - HasStatement - одной строкой и запретить

**Comment by ibond84** [comment]
Так чтобы запретить, надо сначала найти этот метод расширения

**Comment by ibond84** [comment]
Ошибка связана с нашей системой скоупов. У нас есть скоупы с методом Find. А есть метод find в классе type_node. with ищет только в скоупах, хотя поиск extension-методов идет только в методе find.
