### ISSUE TITLE
Полная дестабилизация компилятора после компиляции библиотеки с подключённой пользовательской непустой библиотекой 

### ISSUE THREAD

**Issue by MrFresnel** [pascalabcnet/pascalabcnet#1740]
Полная дестабилизация компилятора после компиляции библиотеки с подключённой пользовательской непустой библиотекой, содержащей хотя бы один класс, запись или интерфейс.

Код основной библиотеки:
```
{$reference Other.dll}
library Some;

end.
```
Код подключаемой библиотеки:
```
library Other;

type
  Something = class
  end;

end.
```
Если запустить IDE, откомпилировать Other с классом/записью или интерфейсом, затем Some, то компилятор упадёт и не будет работать до перезагрузки IDE. Если же IDE перезагрузить, убрать класс/запись или интерфейс, откомпилировать Other, затем Some, то падения компилятора не произойдёт. И больше он не упадёт при компиляции библиотеки Some.

**Comment by miks1965** [comment]
Всё работает, ничего не падает

**Comment by MrFresnel** [comment]
Странно. У меня падало.

**Comment by SunSerega** [comment]
И я использовал уже подобное, да ещё и с дополнительными наворотами, у себя. У вас наверное ещё  что то было, что ввело IDE в состояние особой падучести.

**Comment by MrFresnel** [comment]
Не могу воспроизвести ошибку. Закрываю до выяснения обстоятельств.
