### ISSUE TITLE
Перегрузка :=не разрешает присвоение nil записям

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#1742]
```
type
  t1 = record
    
    static procedure operator:=(a: t1; o: object) := exit;
    
  end;

begin
  var a: t1;
  a := new object;//ok
  a := nil;       //Ошибка: Операции над размерными типами и nil недопустимы
end.
```
В https://github.com/pascalabcnet/pascalabcnet/issues/1738 вы сказали что перегрузка имеет больший приоритет чем утверждение "Операции над размерными типами и nil недопустимы", а значит это должно работать.

**Comment by miks1965** [comment]
Считайте это исключением )
Присваивание вообще у нас недокументируемая операция, а здесь присваивание nil размерному типу... Это не должно компилироваться никогда.
