### ISSUE TITLE
Итераторы не могут иметь параметров по умолчанию

### ISSUE THREAD

**Issue by MrFresnel** [pascalabcnet/pascalabcnet#1745]
```
function Get(x: integer := 0): sequence of integer;
begin
  yield 0;
end;

begin
end.
```
При компиляции получаем:

> Program1.pas(1) : Функция с yield не должна иметь параметров по умолчанию

Причина данного запрета не ясна. В C#, например, аналогичный код прекрасно компилируется и работает:

```
using System.Collections.Generic;

namespace CSrharpApplicationTest
{
    public class Program
    {
        public static IEnumerable<int> Get(int x = 0)
        {
            yield return 0;
        }

        public static void Main(string[] args)
        {
        }
    }
}
```

**Comment by ibond84** [comment]
Ну дубль же

**Comment by MrFresnel** [comment]
Вы об [этом](https://github.com/pascalabcnet/pascalabcnet/issues/1638)? Только там идёт речь о params, а тут о параметрах по умолчанию

**Comment by ibond84** [comment]
#1681

**Comment by MrFresnel** [comment]
Спасибо. Не заметил, извиняюсь.
