### ISSUE TITLE
Компилятор падает, если при подключении стандартного модуля PABCSystem написать его имя в неправильном регистре

### ISSUE THREAD

**Issue by MrFresnel** [pascalabcnet/pascalabcnet#1748]
```
uses PABCSystem;
begin
end.
```
Компилируется. Но, следующий код роняет компилятор:
```
uses PABCSysTem;
begin
end.
```

![image](https://user-images.githubusercontent.com/42812113/52990270-7519df00-3418-11e9-9dac-696d74bee481.png)

Текст ошибки:
```
Внутренняя ошибка компилятора в модуле [pabcnetc.exe] :'System.Exception: System.NullReferenceException: Ссылка на объект не указывает на экземпляр объекта.
   в PascalABCCompiler.SystemLibrary.SystemLibInitializer.RestoreStandardFunctions()
   в PascalABCCompiler.Compiler.ClosePCUReadersAndWriters()
   в PascalABCCompiler.Compiler.Compile()'
```

**Comment by miks1965** [comment]
У меня всё работает

**Comment by MrFresnel** [comment]
Странно. Давайте подождём результатов от других.

**Comment by SunSerega** [comment]
Воспроизводится:

![image](https://user-images.githubusercontent.com/27270190/53001202-c6cf6300-3432-11e9-963d-0daac8def232.png)

Билд 1979, win10x64.

И - по моему оба случая всё равно компилироваться не должны, надо запретить подключать `PABCSystem` с таким же сообщением как тут:
```
uses GraphWPF;
uses GraphWPF;//Повторное подключение модуля graphwpf в секции uses

begin end.
```
Только для `PABCSystem` это сообщение выдавать уже в первом `uses`, потому что они типо как поумолчанию подключено.

**Comment by ibond84** [comment]
Да, падает

**Comment by AIexandrKotov** [comment]
> И - по моему оба случая всё равно компилироваться не должны, надо запретить подключать PABCSystem с таким же сообщением как тут

Вообще-то повторное подрубание PABCSystem нужно для понижения приоритета системного модуля.

**Comment by miks1965** [comment]
Именно так. Это из Delphi пришло
