### ISSUE TITLE
Запретить использовать begin-end для краткого объявления членов классов/записей и подпрограмм

### ISSUE THREAD

**Issue by MrFresnel** [pascalabcnet/pascalabcnet#1750]
```
type
  T = class
    procedure P() :=
      begin
        // Какой-то код.
      end;
  end;

begin
end.
```
Сейчас это проходит компиляцию, хотя не должно. В данном случае короче будет использовать обычный синтаксис метода:
```
type
  T = class
    procedure P();
    begin
      // Какой-то код.
    end;
  end;

begin
end.
```
Ладно, для if'ов, циклов, try'ев и тому подобного это разрешено ибо оправдано - сокращает код. Но в данном случае это добавляет избыточности коду. И тем более для функций такое запрещено. 

В C#, например, это запрещено:
```
namespace CSrharpApplicationTest
{
    public class Program
    {
        public static void F() => {}; // 

        public static void Main(string[] args)
        {
        }
    }
}
```

**Comment by miks1965** [comment]
begin - end - это тоже оператор. Синтаксис: procedure ... := оператор
