### ISSUE TITLE
Термин финальные классы

### ISSUE THREAD

**Issue by MrFresnel** [pascalabcnet/pascalabcnet#1753]
```
type
  T = static class
    procedure P(); abstract; // Program1.pas(3) : Финальные классы не могут содержать абстрактные методы
  end;

begin
end.
```
Правильнее было бы:

> Статические классы не могут содержать абстрактные методы

`Финальные классы` - ассоциируется с вот [этим](https://javarush.ru/groups/posts/1403-metodih-i-klassih-final-java).

**Comment by SunSerega** [comment]
> ассоциируется с вот [этим](https://javarush.ru/groups/posts/1403-metodih-i-klassih-final-java)

Зачем какие то ссылки, в паскале это `sealed`.

И - на абстрактность методы проверять лишнее. Только экземплярные методы могут быть абстрактными, а они уже запрещены в статичных классах.

**Comment by MrFresnel** [comment]
Я к тому, что сообщение об ошибке не очень хорошее. Я не встречал термина `финальные классы` в таком понимании как выше. Это `статичный` класс, а не `финальный`.

**Comment by ibond84** [comment]
Статические классы это финальные классы. Не надо плодить лишние сообщения об ошибках

**Comment by SunSerega** [comment]
Нет, финальные это как раз `sealed`. Финальными их называют потому что цепочка наследования классов не может продолжаться после них.

А в статичных классах никакое наследование невозможно, поэтому и финальными их назвать нельзя.
