### ISSUE TITLE
Неговорящая ошибка при использовании статического деструктора в классе/записи

### ISSUE THREAD

**Issue by MrFresnel** [pascalabcnet/pascalabcnet#1754]
```
type
  T = class
  public
    static destructor P();
    begin
    end;
  end;

begin
end.
```
Сейчас на этот код такая ошибка компиляции:

> Program1.pas(4) : Встречено 'destructor', а ожидался идентификатор

Лучше же показывать следующее:

> Program1.pas(4) : Деструкторы не могут быть статическими

В C# принято следующее решение:

```
namespace CSrharpApplicationTest
{
    public class Program
    {
        static ~Program() // Модификатор "static" недопустим для этого элемента.
        {
        }

        public static void Main(string[] args)
        {
        }
    }
}
```

**Comment by miks1965** [comment]
В Паскале деструкторов нет. Слово оставлено для совместимости с Delphi.

**Comment by MrFresnel** [comment]
Может, тогда убрать их совсем? Какой смысл держаться за совместимость, которой почти не осталось?

**Comment by miks1965** [comment]
Очень просто. Берёшь код на Delphi - и он компилируется. Или компилируется с минимальными правками. Если другой язык, это призрачно
