### ISSUE TITLE
Выдавать предупреждение, если каким-то параметрам, переданным в деконструктор, не назначено значение до выхода из тела метода

### ISSUE THREAD

**Issue by MrFresnel** [pascalabcnet/pascalabcnet#1755]
```
type
  T = class
  public
    procedure Deconstruct(var x: byte) := exit;
  end;

begin
end.
```
В данном случае предупреждение могло бы быть таким:

> Переменной x не назначено значение до выхода из тела деконструктора

**Comment by ibond84** [comment]
Deconstruct это что магическая функция? Зачем для нее делать исключения и называть деконструктором?

**Comment by SunSerega** [comment]
Да, это особая функция:
```
type
  T = class
  public
    procedure Deconstruct(var x: byte) := exit;
  end;

begin
  if nil is T(var x: byte) then
end.
```
Если деконструктор не присвоет значение 1 из своих параметров - это неправильный код. Поэтому выдавать предупреждение как с результатом функций - есть смысл.

**Comment by miks1965** [comment]
Будет множество ложных срабатываний. Невозможно с уверенностью сказать, присвоено ли значение по какой-то ветке.

**Comment by MrFresnel** [comment]
Я понимаю, что в PascalABC.NET не всё так шикарно, как в C#, но разве это повод отказываться от этого? Разве это не возможность улучшить PascalABC.NET?

**Comment by miks1965** [comment]
Да бросьте. Гораздо шикарнее, чем в C#. А это не улучшение, - это провоцирование ложных срабатываний. Ухудшать мы не будем.
