### ISSUE TITLE
Undefined FIleName при деконструировании объекта в переменные в лямбде, тип которой не совпадает с типом переменной типа Action0

### ISSUE THREAD

**Issue by MrFresnel** [pascalabcnet/pascalabcnet#1756]
```
type
  T = class
  public
    procedure Deconstruct(var x: byte) := exit;
  end;

begin
  var lambda: Action0 := () -> new T() is T(var x); // Обязательно Action0
end.
```

![image](https://user-images.githubusercontent.com/42812113/52999212-401c8500-3436-11e9-972b-dc8be1a78d18.png)

Программа, разумеется, неверная, но Undefined FileName быть тоже не должно.

**Comment by miks1965** [comment]
В syntax_tree_visitor.cs
```
LambdaHelper.InferTypesFromVarStmt(tn, fld1, this);
```
в конце - return_type убирается т.к. мы присваиваем процедуре. Result := - не очень хорошее сообщение
