### ISSUE TITLE
Лишняя проверка is object для значимых типов в ToString() автоклассов

### ISSUE THREAD

**Issue by MrFresnel** [pascalabcnet/pascalabcnet#1758]
Исходный код:
```
type
  T = auto class
  public
    fX: integer;
  end;

begin
end.
```
При декомпиляции имеем:
```
using System;

namespace ToDecompile
{
  public class T
  {
    public int fX;

    public void \u0024Init\u0024()
    {
    }

    public T(int ffX)
    {
      base.\u002Ector();
      this.\u0024Init\u0024();
      this.fX = ffX;
    }

    public void Deconstruct(ref int ffX)
    {
      ffX = this.fX;
    }

    public override string ToString()
    {
      return "(" + ((ValueType) this.fX is object ? this.fX.ToString() : "nil") + ")";
    }

    protected internal T()
    {
      base.\u002Ector();
      this.\u0024Init\u0024();
    }
  }
}
```
Особое внимание обратите на ToString():
```
    public override string ToString()
    {
      return "(" + ((ValueType) this.fX is object ? this.fX.ToString() : "nil") + ")";
    }
```
Зачем тут `is object`? Почему нельзя просто вызвать ToString()?

**Comment by SunSerega** [comment]
Для `value`-типов надо просто `.ToString`, а для ссылочных - надо проверку `=nil` вместо `is object`.

**Comment by miks1965** [comment]
Мы не принимаем подобные Issue с мелочной и мнимой неэффективностью. При преобразовании к ToString ни скорость ни объём кода практически не страдают.

**Comment by MrFresnel** [comment]
Тут вопрос не в эффективности, а в том, что вывод реализован криво.

**Comment by miks1965** [comment]
Вывод отображается неправильно?

**Comment by MrFresnel** [comment]
Нет. Отображается все нормально.

**Comment by MrFresnel** [comment]
> Ещё одно замечание. Вы смотрите через инструменты, преобразующие код в C#. Это ошибка. Они могут врать.

А Вы что посоветуете использовать?

**Comment by SunSerega** [comment]
Это не какойнибудь критический баг, и вас никто не просит его исправлять прямо сразу. Это говнокод. Его стоит подчистить когда будет настроение править компилятор но не будет сил разбираться в сложных багах.

>Вы смотрите через инструменты, преобразующие код в C#. Это ошибка. Они могут врать.

IL код тоже проверили.

Проверка `is object` это костыль, заменяющий на равество нулю (`nil`), которое всегда является одной из освновных команд процессора.

А для value-типов она вообще не нужна. Хотя, конечно, для `Nullable` типов без неё будет выводить пустую строку вместо `nil`.

Есть ещё вариант - использовать `PABCSystem._ObjectToString`, которая как раз для вывода и предназначена. Она медленнее, но зато вывод будет более стандартизирован.

**Comment by MrFresnel** [comment]
> Это говнокод.

Убрать его в различных местах, если он там есть, и глядишь баги перестанут с такой скоростью лезть.

**Comment by SunSerega** [comment]
Это и так уже делают, смотри внимательно в комиты.

Вот только пока что это делают нецентрализовано. Иметь возможнось выбрать issue с правильным тегом лучше, чем выискивать и по случаю всё исправлять.

**Comment by MrFresnel** [comment]
Да, знаю, просто на поэзию потянуло.

**Comment by miks1965** [comment]
> Неправильная проверка - на `is object`. Для значимых типов надо использовать просто `.ToString()`, для ссылочных - проверку на null перед вызовом `.ToString()`

У нас автоклассы генерируются на синтаксическом уровне. Там невозможно сказать, размерное поле или ссылочное.

**Comment by SunSerega** [comment]
Ну а что насчёт использования `PABCSystem._ObjectToString` тогда?

**Comment by miks1965** [comment]
PABCSystem._ObjectToString работает не так как это нужно для использования в автоклассах и существенно сложнее. То есть, вы пытаетесь убрать сложность, а получается сложнее.
