### ISSUE TITLE
Нельзя преобразовать тип AnonymousType#1 к T

### ISSUE THREAD

**Issue by MrFresnel** [pascalabcnet/pascalabcnet#1760]
Исходный код:
```
begin
  var x: byte := new class(fX := 0); // Нельзя преобразовать тип AnonymousType#1 к byte
end.
```
Лучше показывать такую ошибку:

> Нельзя преобразовать тип анонимного класса к byte

Ибо та, которая есть сейчас вызывает больше вопросов, чем проясняет ситуацию, у новичков, в частности.

**Comment by miks1965** [comment]
Там не анонимный класс, а невыведенный тип

**Comment by MrFresnel** [comment]
Погодите, но ведь объект анонимного класса уже создан, его тип выведен и имеет имя `AnonymousType#1`. Проблема лишь в том, что при ошибке преобразования типов показываются детали реализации - имя класса.
