### ISSUE TITLE
Улучшение сообщения об ошибке при указании типа свойства анонимного класса

### ISSUE THREAD

**Issue by MrFresnel** [pascalabcnet/pascalabcnet#1763]
Исходный код:
```
begin
  new class(x: byte := 1);
end.
```
Сейчас отображается такая ошибка при компиляции:

> ToDecompile.pas(2) : Встречено ':', а ожидалось '='

Для новичков не совсем информативно. Я предлагаю отображать такую ошибку:

> В анонимных классах явное указание типа свойства не допускается

Примерно также происходит и в Visual Studio:
```
namespace CSrharpApplicationTest
{
    public class Program
    {
        public static void Main(string[] args)
        {
            var c = new { int p = 1 }; // Неверное определение члена анонимного типа. Члены анонимного типа должны быть объявлены присваиванием члена, простым именем или доступом к члену.
        }
    }
}
```

**Comment by miks1965** [comment]
Это надо ухудшать грамматику, вводя в неё заведомо ошибочные конструкции. 
Мы не будем этого делать - это дестабилизирует грамматику.
Новичок нажмёт F1 и посмотрит в справке.
