### ISSUE TITLE
PascalABCVersion - улучшение реализации

### ISSUE THREAD

**Issue by MrFresnel** [pascalabcnet/pascalabcnet#1764]
```
function PascalABCVersion: string;
begin
  Result := '3.2.0.1364'{PABC_VERSION};
end;
```
Хотя, давно уже как 3.4.2. Лично у меня стоит билд 1978. Может, стоит как-то автоматизировать этот процесс, чтобы не менять вручную строку в этой функции?

**Comment by SunSerega** [comment]
Это волшебная функция. Не смотри в реализацию, смотри что она реально возвращает.

Хотя реализаци можно было бы заменить на что то такое:
```
function PascalABCVersion: string;
begin
  Result := 'Эту строку заменит на версию в таком формате: 3.2.0.1364';
end;
```
Чтоб люди которые умеют использовать использовать Ctrl+клик - не пугались увидев что возвращается неправильное значение.

**Comment by MrFresnel** [comment]
> Чтоб люди которые умеют использовать использовать Ctrl+клик - не пугались увидев что возвращается неправильное значение.

Да, так было бы правильней.
