### ISSUE TITLE
Тип-указатель не может выступать в качестве параметра управляемого шаблона при использовании его в sequence of T

### ISSUE THREAD

**Issue by MrFresnel** [pascalabcnet/pascalabcnet#1765]
```
begin
  var x: sequence of pointer; // Тип-указатель не может выступать в качестве параметра управляемого шаблона
end.
```
1) У нас не C++, чтобы называть обобщения шаблонами.
2) Использование интерфейса последовательности было скрыто намеренно. Здесь его не видно явно. У начинающего может возникнуть вполне разумный вопрос: `Какого шаблона?`. Я бы предложил выдавать такую ошибку:

> Последовательность не может содержать указатели

**Comment by SunSerega** [comment]
Это не ошибка последовательностей. Это общее сообщение:
```
procedure p1<T> := exit;

begin
  p1&<pointer>;
end.
```
И ограничение это потому что в .Net неуправляемые указатели и объекты несовместимы:
```
begin
  var p: pointer;
  var o: object := p;
end.
```

**Comment by MrFresnel** [comment]
Для множеств сделано отдельное сообщение об ошибке.
