### ISSUE TITLE
Использование интерфейсов разрешено в with

### ISSUE THREAD

**Issue by MrFresnel** [pascalabcnet/pascalabcnet#1777]
```
type
  I = interface
  end;
  
begin
  with I do
end.
```
Сейчас это успешно компилируется. С обобщёнными интерфейсами тоже работает.

**Comment by miks1965** [comment]
А чему это противоречит?

**Comment by MrFresnel** [comment]
Ладно, если мы бы работали с объектом через какой-то интерфейс в with, но передавать сам интерфейс в with - бессмысленно.

**Comment by SunSerega** [comment]
В отличии от остальных типов, у интерфейсов не может быть статичных полей, методов и т.п. Для типов которые не_интерфейсы надо оставить, но для интерфейсов это безсмысленно.

**Comment by miks1965** [comment]
Ещё появятся - не переживайте так
