### ISSUE TITLE
Запретить вызов операторов через TypeName.operator@

### ISSUE THREAD

**Issue by MrFresnel** [pascalabcnet/pascalabcnet#1778]
```
type
  T = class
  public
    static procedure operator+=(x, y: T) := exit;
  end;

begin
  T.operator+=(new T(), new T());
end.
```
Сейчас это компилируется. Следует запретить вызов операторов через `TypeName.operator@`, где @ - знак перегружаемой операции. В C# это запрещено:
```
namespace CSrharpApplicationTest
{
    public class Program
    {
        public static int operator +(Program x, Program y) => 0;

        public static void Main(string[] args)
        {
            Program.operator+(new Program(), new Program());
        }
    }
}
```

**Comment by miks1965** [comment]
Аргументация "В C# это запрещено" неверна. Например, в C++ это разрешено. Если никаких ошибок из-за этого нет, я закрываю Issue.

**Comment by MrFresnel** [comment]
Ну, мы прежде всего на C# равняемся, а не на C++.

**Comment by miks1965** [comment]
Мы знаем, что Вы равняетесь ))

**Comment by MrFresnel** [comment]
Ну, многое оттуда все - таки в нашем Паскале. Так, что не только я. :D
