### ISSUE TITLE
Анализатор кода показывает доступные операторы

### ISSUE THREAD

**Issue by MrFresnel** [pascalabcnet/pascalabcnet#1779]
![image](https://user-images.githubusercontent.com/42812113/53299081-1c4aac00-3847-11e9-89b7-f9a637c92cf0.png)

Сейчас анализатор кода показывает доступные операторы. Следует запретить их отображение. Аналогично сделано в Visual Studio 2017 в C#:

![image](https://user-images.githubusercontent.com/42812113/53299096-42704c00-3847-11e9-945f-dd4d330e01d1.png)

**Comment by miks1965** [comment]
Это хорошо что показывает. Сразу видно, что мы перегрузили. В C# страдают из-за отсутствия этого

**Comment by MrFresnel** [comment]
Не сказал бы, что прямо страдают. Можно посмотреть всегда есть ли операторы для данного типа перегруженные или нет через `Ctrl+ЛКМ`.
