### ISSUE TITLE
Self как имя параметра оператора-функции в одних случаях допустим, в других - нет. Стандартизировать

### ISSUE THREAD

**Issue by MrFresnel** [pascalabcnet/pascalabcnet#1783]
```
type
  T = class
  public
    //static procedure operator+=(self, x: T) := exit; // Program1.pas(4) : Параметр метода не может иметь имя Self
  
    static function operator+(self, x: T) := 0; // <-- Компилируется, что неверно.
  end;

begin
end.
```
Думаю, будет правильно оставить self в качестве имени первого параметра исключительно для методов расширения (не extension-операторов). В остальных же случаях при попытке использовать self в именах параметров методов или операторов - выдавать ошибку, что это не допустимо.

**Comment by miks1965** [comment]
Почему неверно? Это не ключевое слово, перекрыть можно - пользователь имеет право.

**Comment by SunSerega** [comment]
Тогда почему первое не компилируется?

И - вы сами ранее запретили `self` в качестве параметров методов, потому что там появляются 2 одинаковых `self` в общем пространстве имён, в случае с экземплярными методами. Если на статичные это не распространяется - нужно разрешить первый пример. А если распространяется - запретить второй.

**Comment by miks1965** [comment]
Ага. Увидел нелогичность. Переоткрываю.

**Comment by SunSerega** [comment]
Лучше разрешите во всех статичных. Особенно для операторов типа +=,-= и т.п. это полезно, потому что первый параметр, как, главный. И в обычных статичных методах тоже может понадобится примерно в том же смысле.

**Comment by AIexandrKotov** [comment]
Это вообще закрыть

**Comment by miks1965** [comment]
Закрыл. Переписали начисто: https://github.com/pascalabcnet/pascalabcnet/issues/2039
