### ISSUE TITLE
Запретить определять оператор присваивания с произвольным количеством параметров

### ISSUE THREAD

**Issue by MrFresnel** [pascalabcnet/pascalabcnet#1785]
...

**Comment by miks1965** [comment]
В последнем примере у меня выводится 0, что логично и правильно

**Comment by MrFresnel** [comment]
Да, извиняюсь, я не то там в комментарии написал. И всё же - зачем компилятор позволяет определять операторы, где нет конкретных типов? В нашем случае это оператор, который возвращает 1.

**Comment by miks1965** [comment]
А почему этого нельзя делать? Это будет распространяться на все типы, в которых нет операции +

Я пока вижу одну ошибку - оператор += может иметь только два параметра. Если Вы перепишете Issue, будет здорово.

**Comment by miks1965** [comment]
Это тоже - правильный Issue

**Comment by miks1965** [comment]
Issue правильная. Восстанавливаю.



    procedure operator+=<T>(x: T); extensionmethod := exit;

    function operator+<T>(x: T): integer; extensionmethod := 0;

    begin
    end.

    Сейчас это компилируется. Это неверно, поскольку не ясно какой тип T расширяет оператор. Правильно было бы, если присутствовал хотя бы один универсальный тип:

    type
      TGeneric<T> = class // <--
      end;

    procedure operator+=<T>(x, y: TGeneric<T>); extensionmethod := exit;

    function operator+<T>(x, y: TGeneric<T>): integer; extensionmethod := 0;

    begin
    end.

    Здесь ясно, что операторы расширяют TGeneric<T>. Тем более, если есть такая ситуация:

    type
      TSome = class
      end;

    function operator+(x, y: TSome): integer; extensionmethod := 0;

    function operator+<T>(x, y: T): integer; extensionmethod := 1;

    begin
      var a := new TSome() + new TSome();
      Writeln(a); // 0
    end.

    , то не ясно какой оператор использовать.

    procedure operator+=<T>(x, y, z: T); extensionmethod := exit;

    begin
    end.
