### ISSUE TITLE
Запретить возможность перегрузки оператора присваивания

### ISSUE THREAD

**Issue by MrFresnel** [pascalabcnet/pascalabcnet#1787]
Тест 1:
```
type
  T = class
    static procedure operator :=(arg0, arg1: T) := exit; // <-- Либо через функцию-оператор.
  end;

begin
end.
```
Тест 2:
```
type
  T = class
  end;

procedure operator :=(arg0, arg1: T); extensionmethod := exit; // <-- Либо через функцию-оператор.

begin
end.
```
Перегрузка `:=` ломает использование оператора присваивания:
```
type
  T = class
    static procedure operator :=(arg0, arg1: T) := exit; // <-- Либо через функцию-оператор.
  end;

begin
  var (x, y) := (new T(), new T()); // Program3.pas(7) : Несколько подпрограмм могут быть вызваны
  x := y;
end.
```

**Comment by miks1965** [comment]
Вообще-то, это - недокументированные возможности.

Может, Вы просто не умеете ими пользоваться?

**Comment by MrFresnel** [comment]
Может, стоит тогда их документировать?

**Comment by miks1965** [comment]
Недокументированные возможности - они потому и недокументированные ))

Вы пытаетесь переопределять уже существующую операцию, поэтому их становится две. А переопределение := основано на том, что присваивается другой тип.

**Comment by MrFresnel** [comment]
> А переопределение := основано на том, что присваивается другой тип.

Так есть же операторы преобразования implicit и explicit. Поясните, пожалуйста.

**Comment by miks1965** [comment]
Если надо присвоить скажем вашему типу T тип integer.

Конкретно - срезы на запись будут работать с использованием перегрузки :=

**Comment by MrFresnel** [comment]
Я все же не до конца понял - разве операторы явных и неявных преобразований не позволяют сделать то же, что Вы собираетесь осуществить через перегрузку оператора присваивания?

**Comment by miks1965** [comment]
В C++ преобразование типа тоже делается двумя способами - и ничего страшного. 

Неявное преобразование типа - это косвенный приём, в некоторых случаях нужно сделать именно прямое действие - переопределить именно присваивание. В умелых руках в этом ничего страшного нет.
