### ISSUE TITLE
Запретить объявлять типы анонимных записей в контексте процедурных и функциональных типов

### ISSUE THREAD

**Issue by MrFresnel** [pascalabcnet/pascalabcnet#1791]
Сейчас данный код:
```
type
  T1 = () -> record end;
  T2 = () -> (record end, record end);
  T3 = Func0<record end>;
  T4 = Func0<(record end, record end)>;
  
  T5 = Action<record end>;
  T6 = Action<(record end, record end)>;
  
begin
end.
```
компилируется. Проблема в том, что потом никак нельзя использовать переменные типов (`T1`-`T6`) - присвоение значения им не представляется возможным.

**Comment by SunSerega** [comment]
И в чём тут проблема?

**Comment by MrFresnel** [comment]
В том, что потом эти типы не используешь. Даже если и объявил переменную какого-либо из этих типов, то как ты вернёшь тип анонимной записи?

**Comment by MrFresnel** [comment]
В том, что их не используешь.

**Comment by SunSerega** [comment]
Ну вообще так:
```
type DT = Action<record end>;

begin
  var d: DT;
  //d := r->writeln(r);
end.
```
Но если разкомментировать последнюю строчку - получаем неадекватную ошибку.

**Comment by MrFresnel** [comment]
Нет, именно присвоить, а не объявить. Тем более, мы уже начинали проводить запреты анонимных типов записей. Думаю, что с этим надо заканчивать. Почему, например запрещено следующее:
```
procedure P(x: record end) := exit; // Тип параметра или возвращаемого значения не может быть описанием записи или описанием массива с границами

begin
end.
```
? Я думаю, что надо сделать запреты - более равномерными.

**Comment by miks1965** [comment]
> Почему, например, запрещено следующее:

Для записей - именная эквивалентность типов. Это значит, что вы не передадите в процедуру ничего - все типы будут несовместимы.
