### ISSUE TITLE
Константы могут быть описаны в интерфейсах

### ISSUE THREAD

**Issue by MrFresnel** [pascalabcnet/pascalabcnet#1800]
```
type
  I0 = interface
    const x = 5;
  end;

begin
end.
```

**Comment by miks1965** [comment]
И в чём противоречие?

**Comment by ibond84** [comment]
Какой-то бред выдается сейчас, если описать переменную в интерфейсе
Члены интерфейса не могут иметь определение
Заменить на "Члены интерфейса не могут иметь поля, константы и реализацию методов"

**Comment by MrFresnel** [comment]
И операторов.

**Comment by MrFresnel** [comment]
Лучше:

> Члены интерфейса не могут быть полями, константами или операторами

**Comment by miks1965** [comment]
> Члены интерфейса не могут иметь определение
Вот ровно в вашей хвалёной Студии такое сообщение

**Comment by ibond84** [comment]
Моя немецкая студия выдает (в переводе): интерфейсы не могут содержать поля

**Comment by MrFresnel** [comment]
@ibond84, моя тоже это выдаёт, но я считаю, что это неточность. Правильнее было бы:
> Интерфейсы не могут содержать поля и константы

**Comment by miks1965** [comment]
> Да, моя русская тоже. Это на поля. А на реализацию методов - "Члены интерфейса не могут иметь определение"

**Comment by miks1965** [comment]
Я заменю на такое: 
"Интерфейсы не могут содержать поля, константы и реализацию методов"

Хотя, константы - это тоже поля, поэтому на такое:
"Интерфейсы не могут содержать поля и реализацию методов"

Забавно, но это в трёх местах надо исправлять
