### ISSUE TITLE
Операция отмены переименования требует ровно столько отмен, сколько членов было переименовано

### ISSUE THREAD

**Issue by MrFresnel** [pascalabcnet/pascalabcnet#1805]
Пусть имеем такой код:
```
type
  T = class
  end;
  
var
  x: T;
  y: T;
  z: T;

begin
end.
```
Переименуем `T` в `T1`. Для отмены потребуется сделать 4 `Ctrl+Z`: для каждой из переменных и для самого класса.

**Comment by miks1965** [comment]
Верно

**Comment by SunSerega** [comment]
В какой ситуации это хорошо/полезно?

**Comment by MrFresnel** [comment]
Переименование - одна операция, почему для отмены одной операции надо несколько раз жать `Ctrl+Z`?

**Comment by miks1965** [comment]
Это для нас техническое ограничение. Редактор, который мы используем, не поддерживает групповую отмену. Так конечно я с вами согласен - это неудобно.

**Comment by MrFresnel** [comment]
А в будущем, Вы планируете переход на другой редактор?

**Comment by miks1965** [comment]
Это надо менять редактор, а вместе с ним и всю оболочку. Это слишком глобальное изменение чтобы писать такое в Issue.

Циклическая отмена - это потенциальный источник багов - так не делается. В редакторе должен быть специальный сервис.
