### ISSUE TITLE
Сделать автоматическую реализацию интерфейсов IEquatable<T> и ICloneable автоклассами 

### ISSUE THREAD

**Issue by MrFresnel** [pascalabcnet/pascalabcnet#1816]
Было бы хорошо, если бы исходный код:
```
type
  Person = auto class
  public
    auto property Name: string;
    auto property Age: integer;
  end;

begin
end.
```
чтобы разворачивался в:
```
type
  Person = class(System.ICloneable, System.IEquatable<Person>)
  public
    auto property Name: string;
    auto property Age: integer;
    
    constructor(name: string; age: integer);
    begin
      self.Name := name;
      self.Age := age;
    end;
    
    function Clone(): Person := new Person(Name, Age);
    
    function System.ICloneable.Clone(): object := Clone();
        
    function Equals(other: Person) := (Name = other.Name) and (Age = other.Age);
    
    // Остальное, что уже есть.
  end;

begin
end.
```

**Comment by miks1965** [comment]
ToString в автоклассе и так переопределяется

**Comment by MrFresnel** [comment]
Ну, да, знаю, просто для общей картины.

**Comment by miks1965** [comment]
А почему Clone() возвращает Object?

**Comment by MrFresnel** [comment]
Ну, потому что это реализация `ICloneable.Clone`.

**Comment by SunSerega** [comment]
https://stackoverflow.com/questions/536349/why-no-icloneablet

**Comment by MrFresnel** [comment]
Всегда можно сделать generic версию этого интерфейса, например ICloneableAs<T> и её реализовывать.

**Comment by miks1965** [comment]
А зачем реализовывать ICloneable? Тем более, что он возвращает неудобный тип Object, требующий понижающего преобразования?

**Comment by MrFresnel** [comment]
Можно сделать Clone, который возвращает объект требуемого класса, а также явную реализацию `ICloneable`.

**Comment by miks1965** [comment]
Я это к тому, насколько часто вы используете интерфейс ICloneable. Я вот никогда. Он нужен в специфических ситуациях.

**Comment by MrFresnel** [comment]
Ну, я выше код подправил - посмотрите.

**Comment by miks1965** [comment]
Да, я понял - так и делают. Надо какой-то общий Issue для совершенствования автоклассов.

**Comment by MrFresnel** [comment]
Вы имейте ввиду Milestone?

**Comment by miks1965** [comment]
Мне кажется, там еще пара Issue есть про усовершенствование автоклассов.
