### ISSUE TITLE
var x := [1, '1'] компилируется, хотя не должно

### ISSUE THREAD

**Issue by MrFresnel** [pascalabcnet/pascalabcnet#1821]
```
begin
  var x := [1, '1'] // set of integer, хотя по справке должно быть set of object
end.
```
Тем более, это нетипобезопасно:
```
begin
  var x := [1, 'a'];
  var a := Lst(0);
  foreach var item in x do
    a.Add(integer(item)); // Program5.pas(5) : Ошибка времени выполнения: Заданное приведение является недопустимым.
end.
```
Я предлагаю запретить писать значения разных типов в конструктор множества также как и запретили писать [var s := [1..'4']](https://github.com/pascalabcnet/pascalabcnet/issues/1775).

**Comment by miks1965** [comment]
Ну справку хотя бы почитайте. Вычисляется общий тип. В данном случае это Object.

**Comment by SunSerega** [comment]
Тогда проблема в анализаторе кода. Надо отдельную issue создать?

**Comment by miks1965** [comment]
Да
