### ISSUE TITLE
Точку ошибки ставит не туда, если вызывать исключение в if

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#1827]
```
begin
  
  if true then
    raise new Exception;
  
  writeln('безобидный оператор');
  
end.
```
![image](https://user-images.githubusercontent.com/27270190/53912147-f7351500-4060-11e9-8359-c46d93d1c980.png)

Не важно как форматировать if-raise, даже если они будут на одной строчке, и даже если добавить `begin-end` - точку ошибки будет показывать на следующий оператор, после того который на самом деле вызвал исключение.

**Comment by ibond84** [comment]
Это баг .NET. В C# такое же поведение.

**Comment by SunSerega** [comment]
Вы про что? Как такое может быть правильно?

![image](https://user-images.githubusercontent.com/27270190/53991727-e30e1800-4133-11e9-879b-4d869f04451f.png)

**Comment by SunSerega** [comment]
Да куда там...

![image](https://user-images.githubusercontent.com/27270190/53992539-beb33b00-4135-11e9-83a4-cc55ce59734a.png)

Даже студия так не глючит.

Если это таки баг .Net - это не повод оставлять вывод неправильным. Но, ведь, точками ошибок обычно как то управляют IL операторами nop, что уже ваша работа, разве нет?

**Comment by ibond84** [comment]
![unbenannt-1](https://user-images.githubusercontent.com/3121955/54046537-f8874e80-41d4-11e9-835b-af60b05c01b1.png)

**Comment by ibond84** [comment]
Что еще можно тут обсуждать? Глюки рантайма и все. 

>Если это таки баг .Net - это не повод оставлять вывод неправильным.
ась?
