### ISSUE TITLE
Undefined FileName при обращении к членам переменной типа T? через ?.

### ISSUE THREAD

**Issue by MrFresnel** [pascalabcnet/pascalabcnet#1830]
```
var
  x: integer?;

begin
  x?.GetValueOrDefault();
end.
```
![image](https://user-images.githubusercontent.com/42812113/53956093-bafac680-40eb-11e9-818b-f3b089fb6f74.png)

**Comment by miks1965** [comment]
Ну там в коде ошибка

**Comment by MrFresnel** [comment]
Даже если и так - то такой реакции у компилятора быть не должно (Undefined FIleName).

**Comment by miks1965** [comment]
Да, исправили.
