### ISSUE TITLE
Компилятор не трактует (a, b, ...) как кортежи, даже если тип элементов массива (T, T2, ...) указан явно

### ISSUE THREAD

**Issue by MrFresnel** [pascalabcnet/pascalabcnet#1831]
```
type
  T = class
  end;

function F() := new T();

begin
  var x: array of (T, T) := ((F(), F())); // Program4.pas(8) : Нельзя преобразовать тип T к Tuple<T,T>
end.
```
Тип элементов массива указан явно как кортеж - компилироваться должно. С `Arr<T>` - работает нормально.

**Comment by miks1965** [comment]
Здесь конкурируют синтаксис кортежей и синтаксис старых инициализаторов массивов. Вместе оставить это невозможно. Надо чему-то отдавать предпочтение, а что-то запрещать.

Проблема еще и в том, что в отличие от C# правая и левая части принадлежат к разным конструкциям и парсятся раздельно. Поэтому ((F(), F())) парсится как сырая конструкция. И получение ей типа проходит не всегда удачно.

**Comment by MrFresnel** [comment]
Вы хотите сказать, что на момент парсинга не ясно что это кортеж или инициализатор?

**Comment by miks1965** [comment]
Не совсем так. На момент части парсинга, парсящей правую часть, - это инициализатор массива. Но что такое ((1,2),(1,2))? Это неясно до тех пор пока не будет вычислен тип. А тип (синтаксический) вычисляется позже в другой конструкции. И поскольку нет еще семантики, этого может быть недостаточно.
