### ISSUE TITLE
Имя из модуля приоритетнее имени модуля

### ISSUE THREAD

**Issue by AIexandrKotov** [pascalabcnet/pascalabcnet#1833]
Version.pas:
```pas
unit Version;

const
  Build = 1;
  
begin

end.
```
Program.pas:
```
uses Version, System;

begin
  Version.Build.Print //Нельзя обратиться к свойству Build через тип
end.
```
[Архив ZIP - WinRAR.zip](https://github.com/pascalabcnet/pascalabcnet/files/2942817/ZIP.-.WinRAR.zip)

С одной стороны да, приоритет System выше благодаря uses. Но есть одно но. Если к System.Version.Build обратиться можно через имя модуля, то вот к Version.A обратиться никак не получится, так как класс System.Version перекрыл имя модуля.
### Имена модулей должны быть приоритетнее имён внутри самих модулей.

**Comment by miks1965** [comment]
В Delphi имена модулей - это обычные имена, и правила для них такие же как и для обычных имён. Перекрыл имя - оно скрылось. Бывает, что обратиться к нему уже нельзя даже если хочется.

Предложение понятно, но не принимается. Исключения типа "одни имена приоритетнее других" сделают язык и компилятор запутанными и сложными.
