### ISSUE TITLE
Сделать краткое описание автоклассов

### ISSUE THREAD

**Issue by MrFresnel** [pascalabcnet/pascalabcnet#1834]
Синтаксис:
```
type
  Sword = auto class(Damage, Durability: integer);
```
Чтобы это разворачивалось в полное описание автокласса с двумя автосвойствами и [реализациями интерфейсов](https://github.com/pascalabcnet/pascalabcnet/issues/1816) `ICloneable` и `IEquatable<T>`.

**Comment by miks1965** [comment]
Еще по-моему WithDamage и WithDurability полезно реализовать. Это - клон с изменением одного поля

**Comment by MrFresnel** [comment]
Да, можно сделать магический метод With, который клонирует данный объект, но позволяет сразу же настраивать копию.

**Comment by miks1965** [comment]
А почему магический? Там никакой магии. 

В C# это сделано за счет того что можно параметры по умолчанию указать в любом порядке с именами и со значениями не по умолчанию.

Классная штука для изменения синтаксического дерева в Roslyn

**Comment by MrFresnel** [comment]
Ну, меня просто смущает тот факт, что у нас нельзя пока что параметры в произвольном порядке указывать. Если Вы реализуйте такое - это будет здорово.

**Comment by miks1965** [comment]
С виду - хорошая штука, но 
1. Никогда не пользовался - не могу оценить полезность )) 
2. Не могу оценить трудоёмкость реализации

По этим причинам пока не знаю, стОит ли тянуть это в язык
