### ISSUE TITLE
Разрешить именованные аргументы

### ISSUE THREAD

**Issue by MrFresnel** [pascalabcnet/pascalabcnet#1836]
Пример синтаксиса:
```
type
  SomeType = class
  public
    static procedure Method(arg0: integer; arg1: char) := exit;
  end;

begin
  SomeType.Method(arg1: '1', arg0: 0);
end.
```
Это пригодится для реализации [With ](https://github.com/pascalabcnet/pascalabcnet/issues/1834)для автоклассов.

**Comment by miks1965** [comment]
Нет, прошу крутые enhancement Issue не писать

**Comment by MrFresnel** [comment]
А куда тогда писать? Вообще не писать никуда?

**Comment by miks1965** [comment]
Это серьёзное изменение языка. И - возможно - приносящее проблемы. 
У нас эта фича в голове - года два. 

Да - не пишите никуда - мы её имеем в виду. Но сделаем или нет - обещать не буду.
