### ISSUE TITLE
Ctrl+клик перестал работать для экстеншн-методов из .Net

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#1837]
```
begin
  var s: sequence of byte;
  s.Except(s);
  s.Select(b->b);
end.
```
Тут Ctrl+клик не работает ни для `Except`, ни для `Select`.

Совсем недавно это работало и я этим активно пользовался.

**Comment by miks1965** [comment]
Да, перестал. Это плохо.

**Comment by MrFresnel** [comment]
В билде 1987 это воспроизводится.
