### ISSUE TITLE
Элемент константного массива не считает константой

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#1838]
```
const
  a1: array of byte = (1,2,3);
  a2: array[1..3] of byte = (1,2,3);
  
  b1 = a1[0]; //Ошибка: Ожидалось константное выражение
  b2 = a2[1]; //Ошибка: Ожидалось константное выражение
  
begin end.
```

**Comment by MrFresnel** [comment]
Попробовал ради интереса в C# сделать константный массив:
```
namespace CSrharpApplicationTest
{
    public class Program
    {
        public static void Main(string[] args)
        {
            const int[] x = { 1, 2, 3 }; // Назначаемое для "Program.x" выражение должно быть константным
        }
    }
}
```

**Comment by ibond84** [comment]
В делфи тоже не компилируется. И правильно

**Comment by MrFresnel** [comment]
Погодите, @ibond84, но почему правильно? Поделитесь с нами.

**Comment by miks1965** [comment]
Константное выражение - это не то, которое имеет значением константу, а то, которое компилятор может вычислить на этапе компиляции. На этапе компиляции невозможно проводить сколько-нибудь серьёзные вычисления, поэтому данное выражение не считается константным. Как видите, еще два языка это подтверждают.

**Comment by MrFresnel** [comment]
@miks1965, а почему доступ к созданию Issue/комментированию был временно заблокирован?
