### ISSUE TITLE
Yield: Баг с меткой при наличии определения лямбды

### ISSUE THREAD

**Issue by miks1965** [pascalabcnet/pascalabcnet#184]
```
function f: sequence of integer;
begin
  var k: integer->integer := x->x;
  for var i:=1 to 5 do
    yield i;
end;

begin
  f.Println;
end.
```

```
function f: sequence of integer;
begin
  var a := SeqGen(5,x->x);
  for var i:=1 to 5 do
    yield i;
end;

begin
  f.Println;
end.
```
Любое наличие лямбды в теле функции с yield приводит к ошибке вида 
() : Повторное определение метки lb#4

**Comment by frninja** [comment]
// TODO: Пока обрабатываются только блок функции и основной блок, необходимо обрабатывать случаи появлений лямбд в var_def_statement

**Comment by miks1965** [comment]
Нет, Вы ошибаетесь - дело не в этом. Думаю, комментарий уже неактуален.

ВОт такой код всё равно не работает:

```
function f: sequence of integer;
begin
  var k: integer->integer;
  k := x->x;
  for var i:=1 to 5 do
    yield i;
end;

begin
  f.Println;
end.
```
Тут нет определения лямбды в var_def_statement

Это какая-то проблема на вашей стороне. Сообщение об ошибке ведь Ваше?
