### ISSUE TITLE
nil нельзя использовать в конструкторе множества, даже если тип переменной-множества заранее известен

### ISSUE THREAD

**Issue by MrFresnel** [pascalabcnet/pascalabcnet#1840]
```
begin
  var x: set of object := [nil];
end.
```
Здесь тип множества известен заранее, поэтому никаких проблем с nil быть не должно.

**Comment by miks1965** [comment]
Литеральные множества не являются волшебными и не смотрят на то, чему присвоены - они должны иметь тип в результате компиляции записи [...]. Поскольку в случае nil такой тип вычислить невозможно, - это запрещено.
