### ISSUE TITLE
Разрешить использовать default в конструкторе множества

### ISSUE THREAD

**Issue by MrFresnel** [pascalabcnet/pascalabcnet#1841]
```
begin
  var x: set of object := [default(object)]; // Program4.pas(2) : Встречено 'default', а ожидалось выражение
end.
```
Причина запрета не ясна.

**Comment by miks1965** [comment]
Вы не решите этим проблему - default(object) - это nil, а nil не имеет типа. default - это ненужная иусложняющая конструкция для конструирования множеств в Паскале. Пишите явные значения.

**Comment by SunSerega** [comment]
Нет, вы съели одно звено в своей логичиской цепочке. `default(object)` имеет тип `object`.
```
begin
  var null := default(object); //У null тип известен, это object
  var s := [object(nil)];      //И так делать можно
end.
```
И даже если запрещать `default` в конструкторе множества - нужно соответствующее сообщение.
То что сейчас - свидетельствует что эта часть компилятора в принципе не реализована.

**Comment by ibond84** [comment]
nil во множествах бессмыслица. он туда вообще не добавляется, потому что ключ хеш-таблицы не может быть nil.

**Comment by SunSerega** [comment]
1. Хашсет, к примеру, даёт nil-у хеш-код 0:
```
begin
  var hs := new HashSet<object>;
  writeln(hs.Contains(nil));
  hs.Add(nil);
  writeln(hs.Contains(nil));
end.
```
2. Ошибка всё равно неправильная. `default(object)` это выражение.

**Comment by miks1965** [comment]
Это не ошибка

**Comment by SunSerega** [comment]
Не переходите, пожалуйста, на неоргументированные ответы.
Ошибку даёт явно неправильную, и я уже несколько раз сказал почему.

**Comment by miks1965** [comment]
Давайте еще раз. Это не ошибка. Это наше ограничение. Таков наш язык.

Вы желаете сделать улучшение. С нашей точки зрения бесполезное.
