### ISSUE TITLE
Форма GraphWPF зависает, если вызвать read в её потоке

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#1845]
```
uses GraphWPF;

begin
  OnMouseDown += (x,y,b)->
  begin
    ReadlnString.Println;
  end;
end.
```
Ввод и вывод через консоль работают нормально, но форма не отвисает после окончания ввода.

Из простых решейний - можно вызывать все эвенты вроде `OnMouseDown` в тасках (`System.Threading.Tasks.Task`). Тогда форма не будет зависать даже пока пользовать вводит текст в консоли.

Но по хорошему - надо всё же найти что вызывает зависание. И, как видно по `.Println` - поток не зависает после `read`. Он зависает только после завершений `OnMouseDown`.

**Comment by miks1965** [comment]
У меня всё работает. Что значит не отвисает?

Второй раз жмёшь мышью - и снова

**Comment by miks1965** [comment]
Вызов ивента в таске должен делать программист. Это везде - и в C# как Вы понимаете

**Comment by miks1965** [comment]
Пока закрываю. Нет повторяемости ошибки
