### ISSUE TITLE
Падение компилятора при SomeType = record(IComparable<SomeType>) 

### ISSUE THREAD

**Issue by MrFresnel** [pascalabcnet/pascalabcnet#1847]
Код:
```
type
  SomeType = record(IComparable<SomeType>) 
  public
    function CompareTo(other: SomeType): integer; 
    begin
      Result := 1;
    end;
  end;
  
begin  
end.
```
() : Внутренняя ошибка компилятора в модуле Compiler.Compile[Program1.pas] :'System.TypeLoadException: Отсутствует реализация метода "CompareTo" в типе "Program1.SomeType" из сборки "Program1, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null".

**Comment by miks1965** [comment]
Если SomeType = record(IEquatable<OtherType>)

По идее надо обработать TypeResolve

**Comment by miks1965** [comment]
Для тестирования: 
```
type
  SomeType = record(IComparable<SomeType>) 
  public
    function CompareTo(other: SomeType): integer; 
    begin
      Result := 1;
    end;
  end;
  
begin  
end.
```

**Comment by miks1965** [comment]
Это всё один баг. Надо два бага объединить в один

**Comment by miks1965** [comment]
Ну, это надо исправлять

**Comment by miks1965** [comment]
Пока не научимся обрабатывать TypeResolve, я бы запретил записям наследовать от обобщенных интерфейсов

**Comment by ibond84** [comment]
Не работает только записей. Уже хорошо. Знаем где искать

**Comment by miks1965** [comment]
Я смотрел эту жуть. Посмотрите событие TypeResolve и книгу 
Albahari c# 7.0_in_a_nutshell стр 827.

Смысл в том, что запись, в отличие от класса, когда не полностью определена, требует бОльшей обработки ввиду рекурсивного определения.

Но в документации Microsoft я увидел лишь скупые примеры

**Comment by ibond84** [comment]
Самое интересное, что если подавить исключение, то ехе-шник сгенерируется, но ошибка возникнет при запуске. Сравнил сигнатуры с ехе-шником от С#. Вроде все одинаково.

**Comment by miks1965** [comment]
Мистика

**Comment by miks1965** [comment]
Отлично! Это был важный Issue!
