### ISSUE TITLE
PropertyName не объявлен в типе SomeType при попытке использования свойства, реализованного через get_PropertyName/set_PropertyName

### ISSUE THREAD

**Issue by MrFresnel** [pascalabcnet/pascalabcnet#1855]
```
type
  I0 = interface
    property X: integer read;
  end;
  
  T0 = class(I0)
  public
    function get_X(): integer := 0;
  end;

begin
  (new T0()).X.Println(); // Program3.pas(12) : X не объявлен в типе T0
end.
```
Если закомментировать строку с `Println` - всё компилируется. Вторая ошибка - это то, что `get_X` - показывается в анализаторе кода:
![image](https://user-images.githubusercontent.com/42812113/54472575-57ebec80-47db-11e9-9453-2e25661024c1.png)

, в случае явной реализации - как метод расширения, в случаи просто реализации интерфейса - как метод.

P.S. В справке стоит прописать возможность реализовывать свойства таким образом.

**Comment by ibond84** [comment]
Ну, надо описывать свойство в классе. get_X это все внутренняя кухня

**Comment by MrFresnel** [comment]
Да, но через неё можно реализовывать свойства (раньше так можно было) по крайней мере. Опишите, пожалуйста случаи когда get_X позволено использовать тогда.

**Comment by SunSerega** [comment]
Эти get_ и set_ создают довольно большую путаницу.
Конечно, продолжать говорить "не лезте" проще, но вряд ли это что то изменит))

Может, проще было бы запретить давать любому члену класса имена `get_Prop1` и `set_Prop1`, если в классе, или его предке есть свойство `Prop1`? Это, вроде, должно решить все проблемы и путаницу.

И реализовать это не сложно, потому что все ошибки которые находил @MrFresnel появлялись вне класса, то есть можно производить проверку по окончанию прохода по классу и этого уже хватит.
