### ISSUE TITLE
Подсказки по типам, свойствам, индексаторам, делегатам и методам .NET не отображаются

### ISSUE THREAD

**Issue by MrFresnel** [pascalabcnet/pascalabcnet#1856]
![image](https://user-images.githubusercontent.com/42812113/54472648-d9904a00-47dc-11e9-9ca5-a11a64227cd2.png)

Вы, когда-то говорили, что исправите, но закрыли ту Issue, я думаю, что лучше, чтобы Issue по этому вопросу была открыта и напоминала бы Вам о наличии такой проблемы. Забыть легко, особенно с таким количеством Issue.

**Comment by ibond84** [comment]
Подсказки есть только в full-версии. Подпункт Framework Class Library Help в Microsoft .NET Framework.

**Comment by ibond84** [comment]
Скачивайте и устанавливайте только Framework Class Library Help

**Comment by MrFresnel** [comment]
Погодите, но почему в Visual Studio тогда отображаются они?

**Comment by ibond84** [comment]
Причем тут студия? В студии нет разделения на полную (со всеми причиндалами) и обычную версию (для обновлений). Студия всегда обновляется скачиванием гигабайтов, сам процесс занимает по несколько часов. Это не наш путь.

**Comment by SunSerega** [comment]
У меня full и вроде было несколько неотбражающихся. Но в основном это в глубоко закопанных классах, как в некоторых ноунеймов из `System.Net`.

Я так понимаю - тут проблема в первую очередь что у них нету русского перевода на сайте микрософта?
