### ISSUE TITLE
В качестве имён меток могут быть использованы вещественные числа

### ISSUE THREAD

**Issue by MrFresnel** [pascalabcnet/pascalabcnet#1859]
```
label 1.1;

begin
end.
```

**Comment by ibond84** [comment]
Что-то все понамешано. Тест 3 правильно не работает. Тесты 2,4; не вижу ничего криминального

**Comment by MrFresnel** [comment]
Ну, использование имён типов в качестве меток может быть полезно в `match-with`, например. В C# - switch. Это по тесту 2.

По 4-ому - думаю, это может создать проблемы - такие имена меток.

Хоть на справку иногда лучше не ориентироваться (бывает, что там что-то упущено, например, или случайные ошибки), но там сказано:
>В качестве меток могут быть использованы идентификаторы и положительные целые числа:

**Comment by ibond84** [comment]
label break в других паскалях работает. правьте issue, оставляя только label 1.2

**Comment by MrFresnel** [comment]
> label break в других паскалях работает

Если работает - оставляем.
