### ISSUE TITLE
Запретить использование анонимных делегатов для свойств в интерфейсах

### ISSUE THREAD

**Issue by MrFresnel** [pascalabcnet/pascalabcnet#1866]
```
type
  I0 = interface
    property X: procedure read write;
    //event X: procedure; // <-- error
    //procedure P(arg0: procedure); // <-- error
  end;

begin
end.
```
Причина по которой только для свойств можно использовать анонимные делегаты - неясна, для однообразия лучше запретить для всего использовать анонимные делегаты в интерфейсах (или разрешить, но я склоняюсь к запрету, так как в большинстве случаев это запрещено).

**Comment by DjArt** [comment]
Сейчас всё верно. Это, кстати, ни разу не анонимный делегат, а просто ключевое слово. Требуется, чтобы показать, что у свойства есть `get` или `set`, а что-то из этого может и отсутствовать. В случае событий есть два аццессора - add и remove, и, поскольку они обязательны, смысла указывать их нет. Ну а про методы - таких вещей там никогда не было.

**Comment by MrFresnel** [comment]
1) Ключевые слова `add` и `remove` недоступны в PascalABC.NET. Это в C#.
2) > Сейчас всё верно.

Нет стандартизации. Почему для свойств в интерфейсах можно использовать анонимные делегаты, а для событий и процедур - нет? Чем они отличились, чтобы для них это запрещать?

3) Есть два варианта стандартизации - выдавать ошибку везде при использовании анонимного делегата в интерфейсе, либо разрешить их использовать везде.

**Comment by DjArt** [comment]
> Ключевые слова add и remove недоступны в PascalABC.NET. Это в C#.
Слов нет, методы есть. Просто в PascalABC.NET они задаются неявно. И при реализации их можно перегрузить(в CLI точно).
> Почему для свойств в интерфейсах можно использовать анонимные делегаты, а для событий и методов - нет?
Объясните, пожалуйста, что вы понимаете под анонимным делегатом? Кстати, `property` в данном контексте лишь ключевое слово, употребление которого можно избежать.

**Comment by MrFresnel** [comment]
> Объясните, пожалуйста, что вы понимаете под анонимным делегатом?

Под анонимным делегатом я понимаю то, что описывает тип подпрограммы/метода:
```
var x: procedure; // В данном случае под анонимным делегатом я понимаю procedure. В конечном итоге создаётся (неявно) специальный класс делегата (можно декомпилировать и посмотреть).
```

**Comment by DjArt** [comment]
А, до меня дошло о чём вы. Глаз замылился, я было подумал что это **не тип**. В таком случае `procedure` должно быть алиасом `Action` и разрешено везде.

**Comment by MrFresnel** [comment]
Это, конечно, не по теме, но может, стоит продолжить нашу беседу где-нибудь [вне GitHub](https://vk.com/mrfresnel)?

**Comment by DjArt** [comment]
Я бы с радостью, но меня можно найти только [тут](https://t.me/luke_w)

**Comment by SunSerega** [comment]
> В таком случае procedure должно быть алиасом Action и разрешено везде.

Нет, каждое употребление `procedure` или `function` в имени типа - создаёт новый тип делегата, так и задумано. Правильно - описывать свой тип делегата так же как в C#, и его использовать там где надо.

А возможность использовать `procedure` и `function` в имени типа - это сокращённая запись создания типа делегата. Так же как лямбда это сокращённая запись самой процедуры/функции. Так же, 2 одинаковых лямбды - не равны:
```
begin
  var f1: real->real := x->x*x;
  var f2: real->real := x->x*x;
  writeln(f1=f2); // False
end.
```
