### ISSUE TITLE
procedure p := (p1 + p2); не должно работать. Разобраться

### ISSUE THREAD

**Issue by miks1965** [pascalabcnet/pascalabcnet#1867]
```
procedure p1 := write(1);
procedure p2 := write(2);

procedure p := (p1 + p2);

begin
  
end.
```

**Comment by SunSerega** [comment]
А я думал это фича, и я давно таким пользуюсь:
```
procedure p1 := write(1);
procedure p2 := write(2);

begin
  p1 + p2; // это выражение
  (p1 + p2); //а это вызов
end.
```

**Comment by miks1965** [comment]
По грамматике вроде фича. Но неожиданная. Подумаем.
 Может, оставим.

**Comment by AlexRnD61** [comment]
> ```
> begin
>   p1 + p2;   // это выражение
>   (p1 + p2); // а это вызов
> end.
> ```
На самом деле, по грамматике даже ((((((( p1 + p2 ))))))) все равно выражение. Вопрос лишь в том, как его компилятор рассматривает.

**Comment by miks1965** [comment]
Да. Но не всякое выражение можно превратить в оператор.

Это надо как-то объяснять в описании языка. Фича-то удобная.

Например, для вызова двух команд Робота я использовал код
```
var p := Paint + Right;
p;
```
А можно было оказывается 
```
(Paint + Right);
```

**Comment by AlexRnD61** [comment]
Именно, надо объяснить, что есть отдельные случаи, когда выражение может быть компилятором истолковано, как оператор. Фича удобная, с этим по-моему никто и не спорит. Ну т.е. это вопрос всего-лишь изменений в Справке.

**Comment by miks1965** [comment]
> Может быть, сказать, что она трактуется так в случае, если тип выражения в скобках является процедурным? 

Да, ровно так. Без скобок - указатель на процедуру без параметров, в скобках - вызов процедуры без параметров

**Comment by miks1965** [comment]
Оставляем как фичу
