### ISSUE TITLE
Атрибут DebuggerDisplay не влияет на отображение объекта в отладчике

### ISSUE THREAD

**Issue by MrFresnel** [pascalabcnet/pascalabcnet#1869]
В PascalABC.NET отображается `Program2.T`, вместо `field = 0`:
![image](https://user-images.githubusercontent.com/42812113/54541300-b1eedc80-49aa-11e9-9112-2507068aafeb.png)

```
uses System.Diagnostics;

type
  [DebuggerDisplay('field = {field}')] // Program2.pas(4) : Неизвестное имя 'field'
  T = class
    field: integer;
  end;

begin
  var x := new T();
  Writeln();
end.
```

В Visual Studio 2017:

![image](https://user-images.githubusercontent.com/42812113/54537834-40ac2b00-49a4-11e9-8527-c83e2545f67e.png)

Код на C#:
```
using System;
using System.Diagnostics;

namespace CSrharpApplicationTest
{
    [DebuggerDisplay("field = {field}")]
    public class T
    {
        int field;
    }

    public class Program
    {
        public static void Main(string[] args)
        {
            var x = new T();
            Console.WriteLine();
        }
    }
}
```

**Comment by miks1965** [comment]
Это атрибуты для отладчика студии, но вовсе необязательно отладчики должны это поддерживать

**Comment by MrFresnel** [comment]
Погодите, но почему у нас также не сделать? Разве это плохая идея?

**Comment by miks1965** [comment]
Идея прекрасная.

Хороших идей много. Их некому реализовывать.
