### ISSUE TITLE
Добавить real.Ceil

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#1875]
```
begin
  var r: real;
  r.Trunc; // Это есть
  r.Round; // Это есть
  r.Ceil;  // А этого нет
end.
```
Если уже есть `.Trunc` и `.Round` - `.Ceil` тоже надо добавить...

Ну и варианты для `BigInteger` соответственно тоже:
```
begin
  var r: real;
  r.TruncBigInteger; // Это есть
  r.RoundBigInteger; // Это есть
  r.CeilBigInteger;  // А этого снова нет
end.
```

**Comment by miks1965** [comment]
Trunc и Round наиболее распространены. Всё более редкое вынесено во внешние функции - их миллион.

**Comment by SunSerega** [comment]
Их не миллион. Есть только 3 функции выполняют одно и тоже (округление), немного по разному.
Round, конечно, имеет ещё дополнительные перегрузки, но это уже как раз для особых случаев.

А `Trunc` и `Ceil` это 2 зеркальных близнеца. С чего вы решили что `Trunc` лучше - я не понял.

**Comment by miks1965** [comment]
Trunc и Round - стандартные функции Delphi:
http://www.delphibasics.ru/navSystem.php

То что вам лично понадобилась какая-то функция из эстетических или еще каких побуждений не означает, что её мигом надо включать как метод расширения.

Если вам она нужна как метод расширения - напишите и пользуйтесь. 

Напомню кстати, что в C# нет такой функции
