### ISSUE TITLE
Вопрос: GtkSharp (или другой модуль) для поддержки графических модулей на Linux

### ISSUE THREAD

**Issue by Wohlstand** [pascalabcnet/pascalabcnet#1877]
Как я обнаружил, Linux/macOS-реализация PABC выполнена с полным отключением графических модулей. Для Linux существует модуль GtkSharp (и даже некоторые другие), с помощью которого очень даже возможно поддерживать графические модули и на Linux, и даже macOS. Почему бы не начать его использовать?

**Comment by miks1965** [comment]
Мне кажется, вопросы уместнее задавать не в Issues, а на форуме проекта

**Comment by Wohlstand** [comment]
Хорошо, там и задам.

**Comment by SunSerega** [comment]
Сутки уже прошло... Если что, форум проекта это тут:
http://forum.mmcs.sfedu.ru/c/pascalabcnet

**Comment by Wohlstand** [comment]
Вчера я быстро уснул, поэтому не написал, а так спасибо за ссыль :fox_face: :+1:

**Comment by Wohlstand** [comment]
Написал вчера перед сном, только вот премодерация, поэтому мой пост появиться потом...
