### ISSUE TITLE
Компилятор неправильно видит тип Dictionary.Values.GetEnumerator

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#1879]
```
begin
  var d := new Dictionary<byte, word>;
  var r1: real := d.Values.GetEnumerator(); // Ошибка: Нельзя преобразовать тип Enumerator<byte,word> к real
  var r2: real := d.Values.GetEnumerator;   // Ошибка: Нельзя преобразовать тип function: Enumerator к real
end.
```
В обоих ошибках должно быть `IEnumerator<word>`.
Ибо, 1. типа `Enumerator` нет, а 2. у `IEnumerator` 1 шаблонный параметр, не 2 и не 0.

**Comment by miks1965** [comment]
Тип Enumerator есть - посмотрите аналогичную ошибку на C#

**Comment by SunSerega** [comment]
Понятно... #Develop пишет так:
```
Неявное преобразование типа "System.Collections.Generic.Dictionary<byte,char>.ValueCollection.Enumerator" в "double" невозможно (CS0029)
```

**Comment by miks1965** [comment]
Да, я знаю

**Comment by SunSerega** [comment]
Ну, наверное, правильнее всего тогда было бы писать:
`Dictionary<byte,char>.ValueCollection.Enumerator`

**Comment by miks1965** [comment]
Да, разумеется

**Comment by miks1965** [comment]
Сейчас этот код выдает ошибку - несколько функций могут быть вызваны
```
begin
  var d := new Dictionary<byte, word>;
  d.Values.GetEnumerator();
end.
```

**Comment by miks1965** [comment]
А знаете - всё правильно. Это ровно тип Enumerator<byte,word>. Дело в том, что это внутренний класс, описанный в Dictionary<K,V> - и он неявно наследует все generic-параметры от объемлющего класса. Поэтому ровно Enumerator<byte,word>

**Comment by SunSerega** [comment]
Даже если так - `Enumerator<byte,word>` это не полная информация об ошибке.
Надо хоть куда то `Dictionary.ValueCollection.` припахать.

**Comment by miks1965** [comment]
![изображение](https://user-images.githubusercontent.com/10325391/84948410-60c12180-b0f4-11ea-929e-2dff3e1397c4.png)
Вот как отображается этот тип в студии. Это не "даже если так" - это так

**Comment by miks1965** [comment]
Если вы научитесь из RuntimeType извлекать рефлексией имя типа в том виде, в котором вы хотите, - пришлите этот код нам

**Comment by miks1965** [comment]
Для нас в этой Issue остаётся одна ошибка - 

begin
  var d := new Dictionary<byte, word>;
  var r2: real := d.Values.GetEnumerator;   // Ошибка: Нельзя преобразовать тип function: Enumerator к real
end.
d.Values.GetEnumerator должна возвращать Enumerator

**Comment by SunSerega** [comment]
Так а что там учится:
```
begin
  var d := new Dictionary<byte, word>;
  var o := d.Values.AsEnumerable.GetEnumerator();
  var t := o.GetType;
  Writeln(t.DeclaringType.Name);
  Writeln(t.DeclaringType.DeclaringType.Name);
  Writeln(t.DeclaringType.DeclaringType.DeclaringType?.Name);
end.
```

**Comment by miks1965** [comment]
Там у compiled_type_node есть PrintableName. Принимаем pull requestы
