### ISSUE TITLE
Неправильная ошибка, если один из типов в типе-кортеже не объявлен, а другой - шаблонный параметр

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#1882]
```
type
  t1<TemplateParameter> = class
    
    t: (UndefinedName, TemplateParameter); // Ошибка: Повторно объявленный идентификатор TemplateParameter
    
  end;
  
begin end.
```

**Comment by miks1965** [comment]
А чем же она неправильная? Каждый перечислимый тип в Паскале вводит в пространство имён кучу именованных констант. И если в этом пространстве имён уже есть такие имена, то ошибка.

Вот аналогичная ситуация:

```
type TemplateParameter = integer;

var 
    t: (UndefinedName, TemplateParameter); // Ошибка: Повторно объявленный идентификатор TemplateParameter
  
begin end.
```

**Comment by SunSerega** [comment]
А я думал я кортеж объявляю))

**Comment by miks1965** [comment]
Там сложное поведение типов. Если какой-то тип неизвестен, то это перечислимый тип, если все типы известны, то кортеж.

Неисповедимы пути твои...
