### ISSUE TITLE
Разрешить параметры по умолчанию в подпрограммах и методах с params

### ISSUE THREAD

**Issue by MrFresnel** [pascalabcnet/pascalabcnet#1883]
```
procedure P(x: integer := 0; params y: array of integer); // Program2.pas(1) : В подпрограмме с params-параметром недопустимы значения по умолчанию
begin
end;

begin
end.
```
Причина ограничения не ясна. В справке про этого ничего не сказано. В C# следующий код работает:
```
public class Program
{
    public static void Method(int x = 0, params object[] y)
    {
    }

    public static void Main(string[] args)
    {
    }
}
```
То есть, если я вызываю Method с одним переданным аргументом, то это значение передаётся в метод через x, если два и больше, то тут в работу вступают params.

**Comment by miks1965** [comment]
Всё есть, читайте внимательнее:

> Параметры по умолчанию должны передаваться по значению и идти последними в списке параметров.

> В списке параметров ключевое слово params может указываться только для последнего параметра, причем, этот параметр не должен быть параметром по умолчанию.

**Comment by MrFresnel** [comment]
Это техническое ограничение?

**Comment by miks1965** [comment]
Да, но не только. Это дестабилизирует разбор и делает неочевидными множественные перегрузки для пользователей. Должны быть простые правила. Простое правило одно - всё умолчательное - в конце и в одном экземпляре
