### ISSUE TITLE
foreach по TA = class(IEnumerable<TB>) в случае реализации двух GetEnumerator (явного и неявного) падает

### ISSUE THREAD

**Issue by miks1965** [pascalabcnet/pascalabcnet#1888]
```
type 
  TB = class
  
  end;
  
  TA = class(IEnumerable<TB>)
    l := new List<TB>;
  public  
    function GetEnumerator: IEnumerator<TB> := l.GetEnumerator;
    function System.Collections.IEnumerable.GetEnumerator: System.Collections.IEnumerator := l.GetEnumerator;
  end;

begin
  var a := new TA;
  foreach var x in a do
    Print(1);
end.
```
() : Внутренняя ошибка компилятора в модуле Compiler.Compile[err3.pas] :'System.NotSupportedException: Указанный метод не поддерживается.
   в System.Reflection.Emit.TypeBuilderInstantiation.GetMethodImpl(String name, BindingFlags bindingAttr, Binder binder, CallingConventions callConvention, Type[] types, ParameterModifier[] modifiers)
   в System.Type.GetMethod(String name)
   в PascalABCCompiler.NETGenerator.ILConverter.visit(IForeachNode value)
   в PascalABCCompiler.NETGenerator.ILConverter.ConvertStatement(IStatementNode value)
   в PascalABCCompiler.NETGenerator.ILConverter.visit(IStatementsListNode value)
   в PascalABCCompiler.NETGenerator.ILConverter.ConvertStatement(IStatementNode value)
   в PascalABCCompiler.NETGenerator.ILConverter.visit(IStatementsListNode value)
   в PascalABCCompiler.NETGenerator.ILConverter.ConvertBody(IStatementNode body)
   в PascalABCCompiler.NETGenerator.ILConverter.ConvertFunctionBody(ICommonFunctionNode func)
...

**Comment by miks1965** [comment]
ibond - гляньте пожалуйста вот это. В своё время Вы реализовывали явные интерфейсы. А тут дело доходит до IL-кода - и я уже ничего не понимаю

**Comment by SunSerega** [comment]
А почему вы не откомментировали 2 строчки в тесте `nullable2`?
В билде 2199 они проходят тест, в случаем не забыли про них?
