### ISSUE TITLE
Не видит поле предка, описанного в библиотеке

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#1896]
`lib.pas`:
```
library lib;

type
  t1 = class
    
    public f: real;
    
  end;

end.
```
`0.pas`:
```
{$reference lib.dll}

type
  t2 = class(t1)
    
    function f1: real := f; // Ошибка: Неизвестное имя 'f'
    
  end;

begin end.
```
[0.zip](https://github.com/pascalabcnet/pascalabcnet/files/3026920/0.zip)

**Comment by miks1965** [comment]
Это давняя ошибка.
В SymbolTable.cs, строка 821
```
tn = cl.BaseClassScope.Symbols.Find(name);
```
в cl.BaseClassScope.Symbols пусто.

**Comment by miks1965** [comment]
В SymbolTable.cs строка 819 неожиданно у класса t2 
cl.BaseClassScope оказывается равным null. Понятно, что вообще ничего не находится!
