### ISSUE TITLE
Лямбда не захватывает переменную в loop

### ISSUE THREAD

**Issue by miks1965** [pascalabcnet/pascalabcnet#1897]
```
begin
  var n := 10;
  loop n do
    Print(1);
  var p: procedure;
  p := ()->begin
    Print(n);
  end; 
end.
```
Забыли...

**Comment by miks1965** [comment]
```
begin
  var n := 10;
  loop n*2 do
    Print(1);
  var p: procedure;
  p := ()->begin
    Print(n);
  end; 
end.
```
Так работает

**Comment by miks1965** [comment]
Что самое потрясающее - это то, что loop заменяется на for на сахарном уровне и к моменту работы лямбд там - for. Но for работает!

**Comment by miks1965** [comment]
Это из-за
```
sl.Add(new semantic_check_sugared_statement_node(typeof(loop_stmt), new List<syntax_tree_node> { loop.count }, loop.source_context));
```

**Comment by miks1965** [comment]
Исправление "не заходить повторно в semantic_check_sugared_statement_node" не сработало - другие тесты падают

**Comment by AlexRnD61** [comment]
Занятно, что если после loop стоит любое выражение, содержащее n, все нормально работает. Кстати, если n описать, как const, тоже все работает нормально.
