### ISSUE TITLE
Плавающее внутреннее исключение при компиляции файла с подключенными пользовательскими модулями после исправления кода, который была попытка скомпилировать, если переопределён собственный ресурс

### ISSUE THREAD

**Issue by AIexandrKotov** [pascalabcnet/pascalabcnet#1899]
Текст ошибки:
```
() : Внутренняя ошибка компилятора в модуле Compiler.Compile[game.pas] :'System.ArgumentException: Собственный ресурс уже определен.
   в System.Reflection.Emit.ModuleBuilder.DefineUnmanagedResourceFileInternalNoLock(String resourceFileName)
   в System.Reflection.Emit.AssemblyBuilder.SaveNoLock(String assemblyFileName, PortableExecutableKinds portableExecutableKind, ImageFileMachine imageFileMachine)
   в System.Reflection.Emit.AssemblyBuilder.Save(String assemblyFileName, PortableExecutableKinds portableExecutableKind, ImageFileMachine imageFileMachine)
   в PascalABCCompiler.NETGenerator.ILConverter.ConvertFromTree(IProgramNode p, String TargetFileName, String SourceFileName, CompilerOptions options, String[] ResourceFiles) в C:\Users\Kotov\Documents\GitHub\pascalabcnet\NETGenerator\NETGenerator.cs:строка 919
   в PascalABCCompiler.CodeGenerators.Controller.Compile(IProgramNode ProgramTree, String TargetFileName, String SourceFileName, CompilerOptions options, Hashtable StandartDirectories, String[] ResourceFiles) в C:\Users\Kotov\Documents\GitHub\pascalabcnet\NETGenerator\CodeGenerator.cs:строка 28
   в PascalABCCompiler.Compiler.Compile() в C:\Users\Kotov\Documents\GitHub\pascalabcnet\Compiler\Compiler.cs:строка 2147'
```

Отладочная инфа весьма устаревшая, происходило в коде (NETGenerator.cs)
```
if (comp_opt.target == TargetType.Exe || comp_opt.target == TargetType.WinExe)
{
    if (comp_opt.platformtarget == NETGenerator.CompilerOptions.PlatformTarget.x86)
    ab.Save(an.Name + ".exe", PortableExecutableKinds.Required32Bit, ImageFileMachine.I386);
    //else if (comp_opt.platformtarget == NETGenerator.CompilerOptions.PlatformTarget.x64)
    //    ab.Save(an.Name + ".exe", PortableExecutableKinds.PE32Plus, ImageFileMachine.IA64);
    else ab.Save(an.Name + ".exe");
    //сохраняем сборку
}
```

Примерный алгоритм:
1) Создаём модули, создаём файл, в котором будем использовать модули. Чем больше зависимости между модулями и больше в целом их содержимое, тем чаще будет вылетать данная ошибка.
2) Определяем любую директиву из этого списка: **product, version, company, trademark, title, description**
3) Делаем намеренную ошибку в коде одного из модулей
4) Пытаемся скомпилировать
5) Исправляем ошибку в коде
6) Компилируем снова.
7) Ошибка получена. Хотя шанс получить её очень низкий.

**Comment by SunSerega** [comment]
Вылет компилятора это не ошибка IDE, это именно ошибка компилятора (даже если воспроизводится только из IDE).

Что касается воспроизведения - такой код вроде даёт ту же самую ошибку:
```
begin 
var ab := System.Reflection.Emit.AssemblyBuilder.DefineDynamicAssembly(new System.Reflection.AssemblyName('test'), System.Reflection.Emit.AssemblyBuilderAccess.Save); 
ab.DefineVersionInfoResource('abc','1.1.0', 'abc comp', 'abc (c)', 'abc...'); 
ab.DefineVersionInfoResource('abc2','1.1.0', 'abc2 comp', 'abc2 (c)', 'abc2...'); 
end.
```
Скорее всего дело в добавлении таких типов данных (у @AIexandrKotov эта ошибка вылетает в консольном проекте, у которого определены данные о версии, копирайтинге и т.п.)

**Comment by miks1965** [comment]
Давайте так - мы пока не закроем, я выложу Debug-версию, где в этом окне будет указан номер строки

**Comment by miks1965** [comment]
Вот - ловите: http://pascalabc.net/downloads/w1.zip

Issue пока не закрываю

**Comment by miks1965** [comment]
Ну как там продвигается? Закрывать Issue?

**Comment by AIexandrKotov** [comment]
Не ловится. Но я не так интенсивно кодингом занимаюсь. Не хочется обещать, что я её точно словлю, но ведь никаких сильных изменений в среде не было, вряд ли оно само пофиксилось

**Comment by miks1965** [comment]
Мы не хотим надолго оставлять висячий Issue

**Comment by AIexandrKotov** [comment]
Я понимаю. Переоткрою, если будут результаты.
И вопрос - как скомпилировать дебаг-версию среды?

**Comment by miks1965** [comment]
Я выложил скомпилированный вариант

**Comment by AIexandrKotov** [comment]
Попалась, родимая))
```
Внутренняя ошибка компилятора в модуле Compiler.Compile[game.pas] :'System.ArgumentException: Собственный ресурс уже определен.
   в System.Reflection.Emit.ModuleBuilder.DefineUnmanagedResourceFileInternalNoLock(String resourceFileName)
   в System.Reflection.Emit.AssemblyBuilder.SaveNoLock(String assemblyFileName, PortableExecutableKinds portableExecutableKind, ImageFileMachine imageFileMachine)
   в System.Reflection.Emit.AssemblyBuilder.Save(String assemblyFileName, PortableExecutableKinds portableExecutableKind, ImageFileMachine imageFileMachine)
   в PascalABCCompiler.NETGenerator.ILConverter.ConvertFromTree(IProgramNode p, String TargetFileName, String SourceFileName, CompilerOptions options, String[] ResourceFiles) в C:\Users\Kotov\Documents\GitHub\pascalabcnet\NETGenerator\NETGenerator.cs:строка 919
   в PascalABCCompiler.CodeGenerators.Controller.Compile(IProgramNode ProgramTree, String TargetFileName, String SourceFileName, CompilerOptions options, Hashtable StandartDirectories, String[] ResourceFiles) в C:\Users\Kotov\Documents\GitHub\pascalabcnet\NETGenerator\CodeGenerator.cs:строка 28
   в PascalABCCompiler.Compiler.Compile() в C:\Users\Kotov\Documents\GitHub\pascalabcnet\Compiler\Compiler.cs:строка 2147'
```

**Comment by miks1965** [comment]
Закрываю. Ошибка не возникала ни разу. Непонятен алгоритм её получения. Непонятно, существует ли она.

**Comment by AIexandrKotov** [comment]
По поводу существования:

У меня была идея собирать в отдельный альбом все картинки с этим исключением. Я его уже раз 200 ловил. Один раз (дней 5 назад) словил и в консольном компиляторе:

![image](https://user-images.githubusercontent.com/44296606/60389825-9333d200-9ad1-11e9-883e-febe649ff0bf.png)

Она бесит только из-за того, что нужно перезапускать всю IDE чтобы продолжить работать, иначе "прекращена работа программы". Нет никакого алгоритма, потому она и плавающая. Она может вылететь почти сразу после запуска IDE, через несколько компиляций, а может сутки не вылетать.

> Ошибка не возникала ни разу

Пишите что-нибудь большое. Реально большое, куча пространств имён, модулей и т. д. и будете весьма часто ловить это. Ошибка всегда вылетала при компиляции после неудачной компиляции.

Да, ошибка очень сложная, но issue откройте. Вдруг я или @SunSerega настолько её возненавидим, что сами решим этим заняться. Или вы случайно обнаружите, где собственный ресурс мог создаться дважды.

**Comment by miks1965** [comment]
А действительно вылет - в произвольной программе? Или - в проектах? Или - в проектах, содержащих какие-то ресурсы?

**Comment by AIexandrKotov** [comment]
В проектах или произвольной программе, в которой определены директивы типа {$copyright} (или они определены в .pabcproj), а также подключаются модули. Без модулей всего этого нет. Как и без директив.

Я понимаю, что такую ошибку отладить нереально, но как-то её исправить надо.

**Comment by AIexandrKotov** [comment]
Потенциальная конструкция, которая может это выдать (Compiler.cs строки 2242-2280):

```
//на случай если мы вывалились по исключению но у нас есть откомпилированные модули
            try
            {
                ClosePCUReadersAndWriters();
            }
            catch (Exception e)
            {
                ErrorsList.Add(new Errors.CompilerInternalError("Compiler.ClosePCUReadersAndWriters", e));
            }
            bool need_recompiled = false;
            if (ErrorsList.Count > 0)
            {
                if (compilerOptions.UseDllForSystemUnits && !has_only_syntax_errors(ErrorsList) && compilerOptions.IgnoreRtlErrors)
                {
                    compilerOptions.UseDllForSystemUnits = false;
                    ErrorsList.Clear();
                    
                    need_recompiled = true;

                }
            }
            OnChangeCompilerState(this, CompilerState.CompilationFinished, CompilerOptions.SourceFileName);
            if (ClearAfterCompilation)
            ClearAll();
            
            
            OnChangeCompilerState(this, CompilerState.Ready, null);
            if (ErrorsList.Count > 0)
            {
                return null;
            }
            else if (need_recompiled)
            {
                //Compiler c = new Compiler(sourceFilesProvider,OnChangeCompilerState);
                //return c.Compile(this.compilerOptions);
                return Compile();
            }
            else
                return CompilerOptions.OutputFileName;
```

**Comment by miks1965** [comment]
Исправьте пожалуйста чтобы из названия следовало, что ошибка возникает обязательно при создании проекта и обязательно при наличии директивы {$copyright}. А то когда читаешь Issue, понимаешь, что автор сталкивается с ней каждый день в ЛЮБОМ проекте, и поскольку у нас никогда за 10 лет такой ошибки не было и у наших пользователей - тоже - естественно подобный Issue закрываешь.

**Comment by miks1965** [comment]
Правильно ли я понимаю, что не очищается внутренняя ошибка при предыдущей компиляции?

**Comment by AIexandrKotov** [comment]
Ещё раз, примерный алгоритм:
1) Компилируем неверный код (ошибка должна быть где-то в модулях). Компиляция прерывается. Происходит ошибка из-за неверного кода (неважно, семантическая или синтаксическая). Она не внутренняя.
2) При компиляции после исправления той ошибки в коде вылетает внутренняя ошибка.

Сейчас всё напишу

**Comment by miks1965** [comment]
Еще раз - была ли эта ошибка когда вы не создавали проект, а просто компилировали программу с модулями? И при этом в модулях не было ничего особенного - подключения директив title, description и проч?

Дело в том, что у нас этой ошибки не было ни разу. А мы кодим как вы понимаете на паскале сильно больше вашего, в т.ч. отлаживаем стандартные модули, которые ощутимо большие

**Comment by AIexandrKotov** [comment]
Встречалось и там, и там. Подключением директив в модулях я не занимался.

> Дело в том, что у нас этой ошибки не было ни разу. А мы кодим как вы понимаете на паскале сильно больше вашего, в т.ч. отлаживаем стандартные модули, которые ощутимо большие

При работе только с модулей (не с программой и не с проектом), она не ловится. Поймать её с одним модулем весьма трудно (хотя та ошибка в консольном компиляторе была именно такого плана). А ещё я очень часто перекомпилирую программу, это тоже сильно влияет. Про модули — их надо МНОГО. Штук 10. Со связями друг с другом (но не циклическими).  Intellisense от этого вообще умирает и бесконечно долбит ядро процессора на 100%

**Comment by miks1965** [comment]
Пришлите программу с большим количеством модулей без проекта и директив типа description

**Comment by AIexandrKotov** [comment]
Репозиторий: https://github.com/AIexandrKotov/Biker-3

Открывайте проект (game.pabcproj), там все директивы уже описаны. Или опишите в game.pas директивы и запускайте его. Без всего этого ошибка ведь не воспроизводится. Попробуйте писать какие-нибудь новые классы в модулях (вроде Gameplay.pas, он как бы наиболее большой), делать намеренные ошибки, исправлять их, удалять и компилировать после этого проект.

Но не запускайте, а компилируйте, а то много где разных файлов создаётся (или в VersionInfo.pas Release.Portable поставьте true), да и музыка заменена бесконечно повторяющимся щелчком, ибо гитхаб не позволяет залить больше 25 мб файл.

Я понимаю, что нужно время, а из-за того, что ошибка плавающая, его нужно очень много, потому  я надеюсь, что для отладки у вас ошибка вылезет **как можно скорее**.

**Comment by miks1965** [comment]
Ясно. Я не буду это тестировать - проект действительно большой. Тем более, что если ошибка попадется, для тестирования это будет ноль, поскольку она не повторяется

**Comment by miks1965** [comment]
У меня в saving.pas
Saving.pas(194) : Повторно объявленный идентификатор s

**Comment by miks1965** [comment]
Дальше. Закомментировал тело метода с ошибкой.

ConsoleHelper.pas(63) : Ошибка времени выполнения: Неверный дескриптор.

**Comment by SunSerega** [comment]
1. Запускать не надо, ошибка ведь при компиляции.
2. Неверный дескриптор всегда выскакивает когда консольное приложение запускают не по Shift+F9.

**Comment by AIexandrKotov** [comment]
> ConsoleHelper.pas(63) : Ошибка времени выполнения: Неверный дескриптор.

А, ну да. Проект же консольный, его никак не отладить. +Звук тоже отладкой не воспринимается. Я его всегда запускаю. А баги ищу по логам и сам в коде как обезьяна по дереву лазаю). Этот подход, кстати, данную ошибку мог бы исправить, другой вопрос: кто этим заниматься будет?)

> может ты видео сделаешь с воспроизведением бага

Да дело в том, что я Biker 3 активно переписываю под пространства имён и модулей в нём по сути уже нет. А кодить нарочно в своём же устаревшем коде, который, к тому же, при перемещении в пространства имён, был повреждён и не работает без портативной версии, мне что-то не хочется.

**С пространствами имён эта ошибка не встречается. И в целом, после полного перехода на пространства имён, дальнейшая судьба этой ошибки мне уже будет безразлична.**

Такую ошибку лучше всего исправить именно проанализировав код, от которого она получается. Я его приводил ранее. Надо как-то обнулить при рекомпиляции VersionInfo AssemblyBuilder'а ab из NETGenerator'а. Только как?

Отчего такие выводы? Это из-за критерия ошибки. Я, когда писал директивы title и description, заметил, что ab.DefineVersionInfo(...) идёт через условие, когда одна из директив среди product, version, company, trademark объявлена. Без этого мои директивы не работали, даже несмотря на то, что описаны вне этого условия, потому я в сеттеры NeedDefineVersionInfo тоже делал true. И именно это условие запросто может дать ошибку повторно определённого ресурса. Хотя странно, что только при сохранении сборки. Может быть, всё гораздо хуже и надо копаться в кишках NETGenerator'а.

**Comment by miks1965** [comment]
Вынужден вас огорчить - пространства имен в своём текущем состоянии не останутся в PascalABC.NET. Синтаксически они будут выглядеть по-другому - я уже писал об этом синтаксисе - без директив компилятора

**Comment by AIexandrKotov** [comment]
Синтаксически код не изменится от слова совсем. Тем более, что перед тем, как подобное делать, надо это обсудить.

**Comment by AIexandrKotov** [comment]
Казалось бы, без модулей живи да радуйся, но оказывается, эта ошибка встречается и при использовании пользовательских библиотек, что уже не добрый знак:

![image](https://user-images.githubusercontent.com/44296606/62005859-b6928100-b152-11e9-8a87-05ec7442a88a.png)

**Comment by miks1965** [comment]
Перечитал этот треш. Ничего не понял. Ошибки нет. Закрывать?

**Comment by AIexandrKotov** [comment]
>Ошибки нет.

Ошибка есть.

> Закрывать?

Как хотите.

Но если кто-то в будущем будет настолько же глубоко погружаться в PascalABC.NET как я, то он с этой ошибкой однозначно столкнётся. А плавающие ошибки людей всегда отпугивают, ибо они непредсказуемы.

**Comment by miks1965** [comment]
Ладно. Пусть висит тут всегда

**Comment by ibond84** [comment]
Ну, это скорее все связано с тем, что при ошибке генерации сборки (файл занят процессом или антивирусом) компилятор вызывает Save повторно. Соответственно, m_strResourceFileName в ModuleData уже инициализирован, но Reflection.Emit как дурак выбрасывает ошибку

**Comment by ibond84** [comment]
Убрал повторный вызов Save для сборок с нативными ресурсами

**Comment by ibond84** [comment]
Будет тогда выскакивать официальная "ошибка при сохранении сборки" вместо исключения

**Comment by miks1965** [comment]
Так гораздо лучше конечно
