### ISSUE TITLE
Стандартизировать поведение с анонимными процедурными и функциональными типами

### ISSUE THREAD

**Issue by MrFresnel** [pascalabcnet/pascalabcnet#1906]
```
procedure P() := exit;

begin
  var x: procedure := P;
  var a: sequence of procedure := Seq(x); // Program2.pas(4) : Нельзя преобразовать тип IEnumerable<procedure()> к IEnumerable<procedure()>
end.
```
, однако это компилируется:
```
procedure P0() := exit;

procedure P1(x: procedure) := exit;

var x: procedure := P0;

begin
  P1(x);
end.
```
Думаю, следует сделать одинаковое поведение и там и там - либо выдавать ошибку компиляции, либо допускать такой код.

**Comment by SunSerega** [comment]
Нет, тут всё правильно.
$delegate0 можно неявно преобразовывать к $delegate1.
А `IEnumerable<$delegate0>` и `IEnumerable<$delegate1>` не имеют неявного преобразования.

**Comment by MrFresnel** [comment]
Да, что-то я фигню написал.
