### ISSUE TITLE
TypeLoadException при использовании C# библиотеки 

### ISSUE THREAD

**Issue by sadrapid** [pascalabcnet/pascalabcnet#1908]
TypeLoadException при использовании C# библиотеки 

Ошибка:
>Ошибка времени выполнения: System.IO.FileNotFoundException: Не удалось загрузить файл или сборку "simple_math, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" либо одну из их зависимостей. Не удается найти указанный файл.
Стек:
   в _smath.Program.$Main()
   в _smath.Program.Main()
>

_smath.pas:
(Версия PascalABC: 3.4.2, сборка 1991)
>{$reference 'simple_math.dll'}
uses simple_math_test;
var 
a, b, c: integer;
begin
a := 2;
b := 3;
c := smath.sum(a, b);
end.
>

simple_math.dll:
(Версия .NetFramework: 4.6)
>namespace simple_math_test
{
    public static class smath
    {
        public static int sum(int a, int b)
        {
            return a + b;
        }
    }
}
>

**Comment by SunSerega** [comment]
Код маркдауном выделяется так:

\```
код
\```

**Comment by miks1965** [comment]
Это вы переименовали библиотеку dll. Так просто это делать нельзя. В C# та же ошибка:
![изображение](https://user-images.githubusercontent.com/10325391/56237745-67d64500-6095-11e9-8d9c-430b45cd8ffd.png)

**Comment by sadrapid** [comment]
> Это вы переименовали библиотеку dll. Так просто это делать нельзя. В C# та же ошибка:
> ![изображение](https://user-images.githubusercontent.com/10325391/56237745-67d64500-6095-11e9-8d9c-430b45cd8ffd.png)

Я новичок, может чего-то не понимаю, но, где я её переименовал? У меня солюшн в VS называется simple_math, отсюда и название dll: simple_math.dll. Я ничего нигде не менял, и в других проектах VS у меня эта библиотека работает. Для не-VS проектов нужен какой-то другой подход к созданию DLL?

**Comment by sadrapid** [comment]
> Это вы переименовали библиотеку dll. Так просто это делать нельзя. В C# та же ошибка:
> ![изображение](https://user-images.githubusercontent.com/10325391/56237745-67d64500-6095-11e9-8d9c-430b45cd8ffd.png)

Просто, я и раньше пытался использовать свои библиотеки C# в проектах на PascalABC, и всегда получал ту же ошибку, что и здесь. Вы уверены что проблема во мне? Даже паскаль подсвечивает синтаксис комманд, но выдаёт ошибку что файл не найден. Это как? Как я уже сказал, это не первый раз так. 
![image](https://user-images.githubusercontent.com/37913484/56290184-3d36cb80-612b-11e9-8bc5-283892a9b6fb.png)

**Comment by SunSerega** [comment]
Ну, а я тоже уже использовал C# библиотеки, и у меня было норм. Попробуйте, что ли, больше поэксперементировать, включая будет ли так же ошибка если не переименовывать библиотеку.

**Comment by sadrapid** [comment]
> Ну, а я тоже уже использовал C# библиотеки, и у меня было норм. Попробуйте, что ли, больше поэксперементировать, включая будет ли так же ошибка если не переименовывать библиотеку.

Я уже написал, что ничего не я не переименовывал.

**Comment by SunSerega** [comment]
А, не увидел... Но тем не менее, у меня всё норм:
![image](https://user-images.githubusercontent.com/27270190/56290593-293f9980-612c-11e9-8816-05c06ac941a2.png)

Скиньте архивом оба проекта, и библиотеку и всё паскалевское, включая готовые .exe, .pdb и что ещё там будет.

**Comment by sadrapid** [comment]
> А, не увидел... Но тем не менее, у меня всё норм:
> ![image](https://user-images.githubusercontent.com/27270190/56290593-293f9980-612c-11e9-8816-05c06ac941a2.png)
> 
> И я тоже создавал .dll через студию.
> 
> Скиньте архивом оба проекта, и библиотеку и всё паскалевское, включая готовые .exe, .pdb и что ещё там будет.

Самое смешное, что на самом деле я забыл в папку с экзешником кинуть длл. И в этом и была проблема. Ибо синтаксис паскаль подсвечивал, и я думал что .dll там есть. Но, оказывается, её всё таки надо было туда закинуть чтобы проект компилировался. А господин @miks1965 мне рассказывал, что я якобы что-то там переименовывал, интересно. Видимо, я не один чего-то не понимаю. 
Всё, тема закрыта. Извиняюсь за потраченное время.

**Comment by SunSerega** [comment]
> Почему бы тогда её и не копировать автоматически в папку с аутпутом? Просто, иначе путаница получается.

Он уже это делает, последние месяцев 4 вроде. У вас точно последняя версия?

**Comment by sadrapid** [comment]
У меня версия от 03.03.2019
Но, да, не последняя, и почему то такой функции нет. Буду проверять на последней

**Comment by sadrapid** [comment]
> Код маркдауном выделяется так:
> 
> ```
> код
> ```
> 
> Знак ` находится в англ раскладке за Ё.

``` 
writeln('Спасибо за подсказку. Первый раз пишу что-то на гите. Не знал.');
```
