### ISSUE TITLE
Нельзя преобразовать T к T в случае с библиотекой и модулем

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#1909]
[Взято отсюда](http://www.cyberforum.ru/pascalabc-net/thread2438041.html).

`lib.pas`:
```
library lib;

uses u;

function GetT1 := new t1;

end.
```
`u.pas`:
```
unit u;

type t1 = class end;

end.
```
`0.pas`:
```
{$reference lib.dll}
uses u; // это не подключение модуля, при наведении на u - показывает что это пространство имён. И подключение пространства имён имеет больше смысла чем подключение модуля

begin
  var o: t1 := lib.lib.GetT1();//Ошибка: Нельзя преобразовать тип u.t1 к t1
end.
```

[0.zip](https://github.com/pascalabcnet/pascalabcnet/files/3088294/0.zip)

**Comment by miks1965** [comment]
В двух разных сборках используются одинаковые имена. Но это разные сущности. Так что ошибка правильная.

Мелкие ошибки intellisense, распознающие модуль как пространство имён, надо писать в другом месте.

**Comment by SunSerega** [comment]
Ещё раз, подключение модуля таким макаром - не имеет никакого смысла. Потому что:
1. Он уже содержится в библиотеке, в пространстве имён с тем же именем.
2. Если исходники библиотеки и .exe находятся в 1 папке - придётся всегда писать `u.t1` в исходниках .exe. Что ужасно неудобно.

Поэтому лучше сделать чтоб это было именно подключение пространства имён а не модуля.

**Comment by miks1965** [comment]
Ничего не понял. Вы предлагаете изменить язык? Или создать новый?

Подключение модуля - это штатная операция. Она имеет смысл всегда.

В библиотеке все модули, которые были использованы, растворяются. Неважно, как создана библиотека. После её компиляции о модулях в ней можно забыть.

**Comment by miks1965** [comment]
Почему? Тут всё правильно. Нет второго описания типа.

В библиотеке используется модуль u, значит, имя u находится на глобальном уровне и в библиотеке доступно. Через него можно обратиться и к его типу - вполне естественно.

А зачем вы глобальную функцию из библиотеки вызываете как lib.lib.GetT1() ? Нельзя просто GetT1()?

**Comment by SunSerega** [comment]
> А зачем вы глобальную функцию из библиотеки вызываете как lib.lib.GetT1() ? Нельзя просто GetT1()?

Чтоб показать что это именно из библиотеки функция.

> Почему? Тут всё правильно. Нет второго описания типа.

Вы прямо перед этим сказали:

> В библиотеке все модули, которые были использованы, растворяются.

И вообще это правильнее. Для пространств имён есть специальный тип файлов.

Но если модуль всё же добавляет своё публичное пространство имён в библиотеку - надо чтоб для этого пространства имён работал `uses`, иначе получается ужасно неудобно.

С другой стороны, если всё же чтоб только `namespace` файлы создавали свои пространства имён - это всё будет работать на много логичнее:
- Тогда бОльший смысл имеет давать приоритет `uses` пространству имён чем .pas файлу, ибо если дать его .pas файлу - он вообще компилироваться не станет.
- Если модули добавляют свои кишки в библиотеки - они становятся стильно неконтролируемые. К примеру подключил я стандартный модуль OpenGL к библиотеке - и уже все кто подключат мою библиотеку видят лишнее пространство имён, что нарушает инкапсуляцию. А добавлять весь код из модуля куда то тип implementation части - тоже не камильфо.

**Comment by miks1965** [comment]
> Но если модуль всё же добавляет своё публичное пространство имён в библиотеку - надо чтоб для этого пространства имён работал uses, иначе получается ужасно неудобно.

Этой фразы я не понял. Во-первых, все пространства имен публичные. Во-вторых, у любого модуля есть пространство имён. В данном случае это u. В третьих, если это пространство имён в dll есть, то от этого нельзя защититься - можно пользоваться всем, что есть в этом пространстве имён через u. .

Про бОльший смысл тоже не понял. uses для модуля всегда подключает модуль и его пространство имён. И то и другое. Изменить это нельзя.

Что такое кишки модуля я тоже не очень понимаю. Для программиста на C# надо считать, что если мы пишем в библиотеке uses u, то в C# файл добавляется using u, кроме того, файл с модулем добавляется в проект. Это не кишки - это то, что происходит в любой многофайловой C#-программе.

**Comment by SunSerega** [comment]
>Этой фразы я не понял. Во-первых, все пространства имен публичные. Во-вторых, у любого модуля есть пространство имён. В данном случае это u. В третьих, если это пространство имён в dll есть, то от этого нельзя защититься - можно пользоваться всем, что есть в этом пространстве имён через u. .

Если все типы модуля сделать `internal` - пространство имён станет невидимым.

Проблема добавления всех типов модуля в библиотеку в публичном виде - я описал выше, это делает невозможной инкапсуляцию, при этом если в 1 папке находятся .pas файлы модуля, библиотеки и программы - пространством имён модуля, которое находится в библиотеке пользоваться неудобно, потому что для него не работает uses.

**Comment by miks1965** [comment]
+При этом если в 1 папке находятся .pas файлы модуля, библиотеки и программы - пространством имён модуля, которое находится в библиотеке пользоваться неудобно, потому что для него не работает uses.

Так не сваливайте два проекта в одну папку. В C# тоже так можно сделать и получить те же проблемы
