### ISSUE TITLE
Неправильная ошибка если вызывать шаблонную функцию из рекурсивной функции с коротким определением

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#1912]
```
function f0<T>(o1,o2: T) := o1;

function f1 := f0(0,f1); // Ошибка: Generic-функция f0 не может быть вызвана с данным набором фактических параметров

begin end.
```
На сколько я понимаю, эту ошибку выдаёт потому что первый параметр `f0` это `integer`, а второй - `#Und`. Компилятор считает что типы разные и даёт эту ошибку. Это можно ловить и давать ошибку `Нельзя вычислить тип`, которая тут лучше.

А вообще, раз шаблонный параметр `f0` можно вычислить из `0` - компилятор может дать возвращаемому значению `f1` тот же тип, это было бы вообще замечательно.

**Comment by miks1965** [comment]
Эта ошибка правильная. Действительно, не может быть вызвана. Потому что Вы не указали тип f0. Тип у неё неопределённый, поэтому и не может.

**Comment by MrFresnel** [comment]
Но тип T же известен. Разве нет?
