### ISSUE TITLE
Добиться чтобы Pascal работал без папки Lng

### ISSUE THREAD

**Issue by miks1965** [pascalabcnet/pascalabcnet#1918]

**Comment by AIexandrKotov** [comment]
Почему нет-то? Зачем эти Lng таскать вместе с компилятором?

![image](https://user-images.githubusercontent.com/44296606/60395302-3caeae00-9b3a-11e9-8351-c0d8ce1ed512.png)

**Comment by miks1965** [comment]
Многое что надо делать. Нельзя написать одно и умолчать о тысяче других.
