### ISSUE TITLE
Программа с константой, значение которой невозможно вычислить на этапе компиляции, компилируется

### ISSUE THREAD

**Issue by MrFresnel** [pascalabcnet/pascalabcnet#1928]
```
const
  X = Sin(ReadlnInteger());

begin
  Writeln(X);
end.
```
На этапе компиляции значение X невозможно вычислить, соответственно это не должно компилироваться. Вообще, использование функций в качестве значений констант, думаю, лучше полностью запретить. Не будете же Вы прописывать в компиляторе конкретные имена функций (таких как ReadlnInteger), которые нельзя использовать с константами. Ведь, это костыль.

**Comment by miks1965** [comment]
Совсем запрещать использование стандартных функций - плохо.

Правила у нас такие.

Запрещено использование пользовательских функций, которые могут использовать побочные эффекты в виде обращения к глобальным переменным. Функции из стандартных модулей использовать можно. Они не дают побочных эффектов.

Здесь константа вычисляется первый раз при запуске, и потом её значение нельзя поменять.

**Comment by MrFresnel** [comment]
Погодите, но как Вы будете отличать какие функции можно использолвать в константах, а какие - нет?

**Comment by MrFresnel** [comment]
Но, ведь константа на то и константа, что при компиляции её значение известно. А с ReadlnInteger - это не так.

**Comment by miks1965** [comment]
Тут важный момент. 

Константа на протяжении всей программы не меняет значение. Это значение может вычисляться как во время компиляции, так и при начальном запуске программы (подпрограммы). От этого её смысл не меняется - после инициализации её значение нельзя изменить.

Да, это в какой-то степени можно считать readonly-полем. Но в терминах PascalABC.NET - это - константа.

**Comment by miks1965** [comment]
Во Free Pascal правила более жесткие чем у нас. Там действительно константы вычисляются на этапе компиляции, что резко сужает класс используемых функций. У нас же допустимы все функции из PABCSystem. Цена этого - вычисление значения константы на этапе выполнения.

**Comment by miks1965** [comment]
В C++ можно ещё больше:

```
int a=2;

int f()
{
	return a;
}

int main()
{
	const double d = f();
	std::cout << d;
}
```
У нас помнится в этом случае были какие-то проблемы.

**Comment by SunSerega** [comment]
> В C++ можно ещё больше

В С++ слово `const` значит только невозможность изменять переменную. Что, по моему, лучше того что творится в паскале с ними, ибо у вас в одном месте что то запрещено потому что "константы должны считаться на этапе компиляции" (с) вроде вы же, а в другом разрешено, как в коде из заголовка этой issue, потому что ¯\_(ツ)_/¯.

**Comment by miks1965** [comment]
Нет, у нас константы-выражения не вычисляются на этапе компиляции. Собственно, никогда не считались.

**Comment by SunSerega** [comment]
Как это не вычисляются?! Вычисляются! Но, конечно, только когда могут:
```
const
  c1 = 5+3;
  c2 = c1*2;

begin
  writeln(c2);
end.
```
```
  public class Program
  {
    public const int c1 = 8;
    public const int c2 = 16;
    ...
```

**Comment by miks1965** [comment]
А, ну да, но это - простая оптимизация. Вот если мы видим функцию, пусть и стандартную, никакой возможности вычислить её на этапе компиляции у нас нету. А инициализировать функцией константу хочется.
