### ISSUE TITLE
[Указатели] Невозможно скомпилировать проект

### ISSUE THREAD

**Issue by DjArt** [pascalabcnet/pascalabcnet#1929]
https://github.com/DjArt/TILauncher
Компиляция проекта выше просто зависает без потребления ресурсов. Выяснилось, что проблема конкретно в этой строке: https://github.com/DjArt/TILauncher/blob/3265304156f0b059e4603e0d181298ef6af94ee7/TILauncher.pas#L56, если закомментировать, то компиляция проходит успешно.

**Comment by MrFresnel** [comment]
Попытайтесь минимизировать код. Разработчикам будет легче искать проблему, если код укладывается в 10-20 строк (надеюсь, Вы мою мысль уловили).

**Comment by miks1965** [comment]
Нужен минимальный код. А там какие-то dll с непонятным содержимым

**Comment by SunSerega** [comment]
Вот минимальный код:
```
{$reference PInvoke.Kernel32.dll}

procedure p1;
begin
  var startupInfo := PInvoke.Kernel32.STARTUPINFO.Create();
  var poin : ^char;
  startupInfo.lpDesktop := poin;
end;

begin end.
```
И файл проекта ему не нужен.

Если попытаться сделать такую же запись как `PInvoke.Kernel32.STARTUPINFO` в этой программе - ошибки нет.

@miks1965 библиотеки вызывающие ошибку - не нативные. Те external функции используют стандартные библиотеки из system32, но эти функции не нужны для воспроизведения.

но

@DjArt, всё же, предоставьте их исходники. Я, конечно, могу достать их DotPeek-ом, но это тонна лишней работы. А лучше - сами найдите минимальный код воспроизведения, так будет быстрее.

**Comment by SunSerega** [comment]
А не, там всё просто:
`lib.pas`:
```
library lib;

type
  r1 = record
    
    p: ^char; // тип обязательно типизированный указатель
    
  end;

end.
```
`0.pas`:
```
{$reference lib.dll}

procedure p1;
begin
  var r: lib.r1; // запись обязательно из библиотеки
  var p: ^char;
  r.p := p; // обязательно присвоить полю значение переменной. если присваивать nil - не воспроизводится
end;

begin end.
```
[0.zip](https://github.com/pascalabcnet/pascalabcnet/files/3164441/0.zip)

Компиляция `0.pas` зависает.

**Comment by miks1965** [comment]
О, великолепно! "@SunSerega, спасибо!

**Comment by ibond84** [comment]
Ничего там не не зависает. У меня выдается неправильная ошибка "Нельзя преобразовать тип ^char к System.Char*" Ее и буду исправлять.

**Comment by SunSerega** [comment]
В последней версии похоже не зависает, раньше зависало.

**Comment by miks1965** [comment]
У меня в последней версии виснет при компиляции

**Comment by SunSerega** [comment]
Сейчас проверил - у меня тоже зависает. (билд 2069)

А у @AIexandrKotov, на сколько я понял - не зависает.
