### ISSUE TITLE
Неверный текст ошибки "Операции над размерными типами и nil недопустимы" при работе с экземплярами типа-параметра T

### ISSUE THREAD

**Issue by MrFresnel** [pascalabcnet/pascalabcnet#1935]
```
type
  Generic<T> = class
    procedure P(x: T);
    begin
      if x = nil then // Program3.pas(5) : Операции над размерными типами и nil недопустимы
    end;
  end;

begin
end.
```
Неизвестно чем является `T` - экземпляром класса или записи, поэтому текст ошибки неверный. Правильнее было бы:

> Сравнение типа T с nil невозможно, так как T может быть типом значения

**Comment by SunSerega** [comment]
> x is null

Это не то же самое что `==  null`.

В паскале аналогом `x is null` будет `not (x is object)`, и работать это должно.
