### ISSUE TITLE
Использование посредника-модуля или -библиотеки между изначальной библиотекой на C# и программой на PascalABC.NET ломает анализатор кода в программе

### ISSUE THREAD

**Issue by MrFresnel** [pascalabcnet/pascalabcnet#1939]
Код изначальной библиотеки:
```
namespace TestLibrary
{
    public class SomeClass
    {
        public int field;

        public int Property { get; set; }

        public void Method()
        {
        }

        public static int staticField;

        public static int StaticProperty { get; set; }

        public static void StaticMethod()
        {
        }
    }
}
```
Если попробовать использовать эту библиотеку напрямую из программы, то анализатор кода видит всё, что описано в библиотеке:
![image](https://user-images.githubusercontent.com/42812113/57793500-209dab80-774a-11e9-98f3-ca78ae18adb0.png)
Если же создать модуль (или библиотеку) - обёртку над изначальной на C#:
```
unit WrapperTestLibrary;
type
  SomeClassT = TestLibrary.SomeClass;
end.
```
, то в программе, использующей эту обёртку, анализатор кода сломается:

![image](https://user-images.githubusercontent.com/42812113/57794024-60b15e00-774b-11e9-8741-bc7815bc1666.png)
```
uses WrapperTestLibrary;
begin
  WrapperTestLibrary.SomeClassT.
end.
```

После `SomeClassT` ничего по точке не отображается.
[Bug.zip](https://github.com/pascalabcnet/pascalabcnet/files/3183645/Bug.zip)

**Comment by miks1965** [comment]
Пожалуйста - перенесите Issue по анализатору кода в pascalabcnetide

**Comment by SunSerega** [comment]
Только разработчики могут переносить issue. Остальные могут только пересоздать.

**Comment by MrFresnel** [comment]
Обе последние Issue пересоздал в разделе для IDE.

**Comment by miks1965** [comment]
Ага, спасибо
