### ISSUE TITLE
Вложенный uses не запрещает, но и не поддерживает

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#1940]
```
uses System;
uses Reflection; // это ошибку не даёт

begin
  var a: FieldInfo; // но ни 1 имя из System.Reflection не видит
end.
```
Надо или запретить `uses Reflection`, или, лучше - дописать, чтоб работала вся эта программа.

**Comment by miks1965** [comment]
Это не вложенный uses

**Comment by MrFresnel** [comment]
@miks1965, а как в том же FreePascal дела с подобным кодом обстоят? Насколько помню, там имелось некое подобие пространств имён.

**Comment by miks1965** [comment]
Я не разбираюсь в тонкостях диалекта Free Pascal.

**Comment by SunSerega** [comment]
> Это не вложенный uses

Ну, я не знаю как лучше это назвать...

**Comment by miks1965** [comment]
Безобразие это - вот как назвать

**Comment by SunSerega** [comment]
Вы исправили или... ?
