### ISSUE TITLE
Yield: Неизвестное имя 'CompareTo' - ошибки быть не должно 

### ISSUE THREAD

**Issue by miks1965** [pascalabcnet/pascalabcnet#195]
```
function f<T>(t1: T): sequence of T; 
  where T: System.IComparable<T>;
begin
  if t1.CompareTo(t1)=1 then
  yield t1;
end;

begin
end.
```
Ошибка: Неизвестное имя 'CompareTo'

Ошибки быть не должно

**Comment by frninja** [comment]
Теперь работает

**Comment by miks1965** [comment]
Здравствуйте, Олег!

Я посмотрел код с дублирующейся меткой.

Ошибка здесь:

if (lab.is_defined)
             {
                 AddError(get_location(_labeled_statement.label_name), 
"LABEL_{0}_REDEFINED", _labeled_statement.label_name.name);
             }

Обратите внимание - lab - вот где описана:
label_node lab = si.sym_info as label_node;

Поэтому на семантическом уровне lab.is_defined где-то получает значение 
true, а потом та же метка (та же, а не другая) используется где-то еще.
Мне кажется, это происходит при вашем клонировании. Отловите этот момент.

Когда я комментирую эту ошибку - всё работает. То есть, эта ошибка - 
простая. ОтлОвите этот момент - всё заработает.

Ещё.

Вот такой код после комментирования ошибки заработал:

function f: sequence of integer;
begin
   var a := SeqGen(5,x->x);
   for var i:=1 to 5 do
     yield i;
end;

Но выдаётся другое сообщение: поля класса не могут инициализироваться 
лямбда-выражениями. По всей видимости, Вы переносите это описание в класс:

type Cl = class
   a: тип := SeqGen(5,x->x);

Это неправильно - подобное у нас запрещено на семантическом уровне. 
Поэтому нужно сделать следующее. Создать для класса конструктор по 
умолчанию, и в него перенести подобные присваивания:

type Cl = class
   a: тип;
   constructor;
   begin
     a := SeqGen(5,x->x);
   end;
end;



Кстати, обратите внимание, что теперь Этот пример не падает:

function f: sequence of integer;
begin
   for var i:=1 to 5 do
     yield SeqGen(5,x->x);
end;

begin
   f.Println;
end.

но выдается сообщение об ошибке

Функции с yield не могут использовать result

Это разумеется неправильно.



Вообщем, исправляйте


С уважением,
   Михалкович Станислав

**Comment by miks1965** [comment]
При таком коде:

function f: sequence of integer;
label 666;
begin
   666: yield 1
end;

ваши метки вообще не генерируются, но

visit(SyntaxTree.labeled_statement _labeled_statement)

обходится трижды!!!

Это очень странно - почему трижды? Без yield - всего один раз.

При таком коде:

function f: sequence of integer;
label 666;
begin
   var g: integer->integer := x->x;
   666: yield 1
end;

ваши метки не генерируются, но возникает ошибка повторного определения 
метки всё равно - во второй обход - не знаю, был ли бы третий - не дошло 
до этого.

Собственно, именно этот случай, думаю, надо тестировать - тут метка не 
ваша - это тестировать проще.

С.С.

**Comment by miks1965** [comment]
Ещё - как версия - можно заменить в клонированной Вами функции имена 
меток на уникальные.

Но если Вы кидаете метки не в те пространства имен (точнее, не Вы, а 
сочетание вашего кода и кода с лямбдами), тогда и это не поможет - будут 
какие-то другие ошибки.

Но попробовать стоит

**Comment by miks1965** [comment]
09.06.2016 10:29, Oleg Batashov пишет:
> Closed #195 <https://github.com/pascalabcnet/pascalabcnet/issues/195>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/pascalabcnet/pascalabcnet/issues/195#event-686873230>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AJ2Njw5Y3RBwkMzXy-7ogUYuJynnG-vmks5qJ8DcgaJpZM4Irbcl>.

Ну собственно - не Ваша ошибка:

https://github.com/pascalabcnet/pascalabcnet/issues/199

Пытаемся исправить

С.С.
