### ISSUE TITLE
Task&<byte>.Run(()->default(byte)) даёт ошибку компиляции из за того что Run(Func<Task>) выбирается как предпочтительная по сравнению с Run<int>(Func<int>)

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#1952]
Код из #1946:
```
begin
  System.Threading.Tasks.Task&<byte>.Run(()->default(byte));
end.
```
Теперь не падает, но всё равно не компилируется. У `Run` есть много перегрузок, принимающих разные лямбды. В самом начале можно видеть перегрузку, принимающую функцию без параметров, возвращающую `T` (`byte` в данном случае). Однако при компиляции получаем:
```
Нельзя преобразовать тип byte к System.Threading.Tasks.Task
```
Похоже, компилятор видит только 1 другую перегрузку, принимающую `()->Task`.

Но, кстати, если использовать не лямбду а функцию:
```
function f1 := default(byte);

begin
  System.Threading.Tasks.Task&<byte>.Run(f1);
end.
```
всё компилируется.

**Comment by miks1965** [comment]
У Run - слишком много перегрузок. У нас в алгоритме выбора перегруженной версии нет выбора по функциям с одинаковым (нулевым) набором параметров и отличающихся только типами возвращаемых значений.

**Comment by miks1965** [comment]
Я бы закрыл. Это не баг, это необходимость непомерно сложного вывода перегрузок в .NET-библиотеках. PascalABC.NET с этим не справляется.

**Comment by SunSerega** [comment]
Это однозначно баг, вне зависимости от того - как вам сложно и не хочется его исправить.

Я понимаю что это сложно поэтому торопить вас не буду, но костыли которые это заставляет делать - ну очень не красивые. Поэтому когда то но исправить надо.

**Comment by miks1965** [comment]
А что такое баг по-вашему?

**Comment by SunSerega** [comment]
В случае языка программирования - это не задокументированное поведение, делающее написание программ неудобным.

Вы, конечно, можете задокументировать это.
Но что я имел в виду - это совершенно не правильно, усложнять язык при этом делая его менее удобным, только потому что на исправление надо найти много времени и сил.

issue как раз хороши тем, что их можно просто оставить лежать и забыть до лучших времён. Когда хотите исправить несколько простых issue, так чтоб сложное не попадалось под руку - просто [смотрите так](https://github.com/pascalabcnet/pascalabcnet/issues?q=-label%3A"Сложное+в+реализации"+is%3Aopen).

И потом, не обязательно же вам самим такое исправлять. Вы поручаете студентам в виде экзамена, или чего там, делать всякие паттерн мачинги. Почему не поручить исправить какой то баг требующий дописать значительную часть кода?

**Comment by miks1965** [comment]
1. Это не баг. 
2. Это поведение как вы понимаете нетрудно сделать задокументированным
3. Слабый вывод перегрузок по сравнению с C# - это не ошибка - это свойство языка. Поэтому изменение этого - это улучшение.
4. Поручить студенту алгоритм, который лежит в сердце компилятора, - самоубийство
5. Лучшие времена наступят несомненно. 
6. Улучшать алгоритм выбора перегруженной функции - надо писать десятка три issues. Эта - одна из них. Проблему мы знаем. Поэтому несколько странно оставлять тут один этот issue

**Comment by SunSerega** [comment]
Понятно... Тогда может лучше сделать общую issue про алгоритм вывода перегруженной функции? Мне лично это нужно чтоб следить за обновлениями и когда что то исправляется - править свой код сразу, а не через пару месяцев, когда случайно пойму что работает (если вообще замечу). Для этого же и та issue про костыли в OpenCLABC, в моём репозитории...

**Comment by miks1965** [comment]
conv_data&alg.cs 1348
```
if (left_func.is_generic_function_instance && !right_func.is_generic_function_instance)
  return method_compare.less_method;
```
Фигня полная. 
```
left_func = Threading.Tasks.Task[Int32] Run[Int32](Func[Int32]) 

right_func = Threading.Tasks.Task Run(Func[Threading.Tasks.Task])
```
То есть, левая - инстанция, а правая - нет, и поэтому левая меньше правой и она удаляется!

Во-первых, сама идея абсурдна сравнивать функции на меньше без учета фактических параметров. Во-вторых, в данном случае конечно же это - не сравнимые функции

**Comment by miks1965** [comment]
То есть из Run<int>(Func<int>) и Run(Func<Task>) оставляется последняя версия как наибольшая. Идиотизм!

**Comment by ibond84** [comment]
https://github.com/pascalabcnet/pascalabcnet/actions/runs/782395413
