### ISSUE TITLE
match l with l.A

### ISSUE THREAD

**Issue by miks1965** [pascalabcnet/pascalabcnet#1953]
```
begin
  var l: (A,B,C);
  match l with
    l.A: Print(A);
  end;
end.
```
Должно работать. l.A - это константа перечислимого типа

**Comment by miks1965** [comment]
А это по-прежнему не работает!

**Comment by VanillaFlame** [comment]
Переоткрыт в связи с d6bef4694df884d9d77ade41f81a8635bf58f306

**Comment by miks1965** [comment]
Как мы недавно выяснили, запись l.A будет запрещена. Можно обращаться только Тип.A

Если после этого запрета код в этом Issue автоматически перестанет компилироваться, то закройте этот Issue снова

**Comment by SunSerega** [comment]
В последнем коммите уже убрали `l.A` и откатили `.y` файлы чтоб в паттерн мачинге такую конструкцию снова и не ожидало.

**Comment by miks1965** [comment]
Само наладилось ))
