### ISSUE TITLE
Компилятор не даёт вызвать 1 конструктор из другого, если передать лямбду

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#1956]
```
type
  t1 = class
    
    constructor(f: ()->byte) := exit;
    
    constructor :=
    Create(nil); // Работает
    
    constructor(b: byte) :=
    Create(()->b); //Ошибка: Нельзя вызвать конструктор через объект
    
  end;

begin end.
```
Не обязательно захватывать лямбдой параметр чтоб воспроизвести. Но для тестов лучше использовать этот код, чтоб сразу и с захватом проверялось.

**Comment by miks1965** [comment]
Для отладки:
```
type
  t1 = class
    constructor Create(f: ()->byte);
    begin
      
    end;
    
    constructor Create(b: byte);
    begin
      Create(()->b);
    end;
  end;

begin
end.
```

**Comment by miks1965** [comment]
Вот источник ошибки:
```
type
  t1 = class
    constructor Create(i: integer);
    begin
    end;
    
    constructor Create();
    begin
      var a := 1;
      Create(1);
    end;
  end;

begin
end.
```
Если конструктор этого же класса вызывается не первым (в .NET это нельзя), то генерируется ошибка "Нельзя вызвать конструктор через объект". То есть, логика такая: другой конструктор можно вызывать только первым - тогда это будет именно вызов конструктора, а последующие вызовы будут вызовами его как обычного метода, что запрещено.

Лямбды вмешиваются  в это так: для параметра -лямбды генерируется дополнительный код в прологе конструктора, и второй конструктор вызывается уже не первым оператором, что и приводит к ошибке.

**Comment by miks1965** [comment]
То есть, вызов конструктора из конструктора при наличии лямбд в конструкторе всегда будет приводить к ошибкам.

**Comment by SunSerega** [comment]
> Если конструктор этого же класса вызывается не первым (в .NET это нельзя)

> То есть, вызов конструктора из конструктора при наличии лямбд в параметре конструктора всегда будет приводить к ошибкам

Ничего подобного. Это правило - защита от дурака. Но JIT принимает IL код в котором что то идёт до вызова другого конструктора.

Если не верите - посмотрите на #1502. Сейчас там производятся действия до вызова конструктора предка, и этот код выполняется без проблем.
