### ISSUE TITLE
Компилятор не может выбрать между operator implicit и приведению к предку, когда у operator implicit не подходит тип шаблона

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#1957]
```
type
  t1<T> = abstract class
    
    static function operator implicit(o: T): t1<T>;
    
  end;
  
  t2<T> = class(t1<T>) end;
  
static function t1<T>.operator implicit(o: T): t1<T> :=
new t2<T>; //Ошибка: Возможны два преобразования типов

begin end.
```
На сколько я понял - компилятор видит как будто к `new t2<T>`  можно ещё раз рекурсивно применить тот же `operator implicit`.

Но это не так, если применить `operator implicit` - на выходе получаем `t1<t2<T>>`, который не совместим с `t1<T>`, поэтому его должно отсеивать.

И поэтому вызываться должно именно преобразование к предку.

**Comment by miks1965** [comment]
По-моему, Вы сами запутались. Согласно вашему коду возможны два преобразования типов

1. От t2<T> к предку t1<T>
2. От любого T к t1<T>. В частности, в качестве T можно использовать t2<T>. 

То есть ваша ошибка в том, что вместо T можно подставить t2<T>, а вы этого не видите. Ошибки нет.

**Comment by SunSerega** [comment]
> От любого T к t1. В частности, в качестве T можно использовать t2.

Я же говорю, это тут не работает!

> Но это не так, если применить operator implicit - на выходе получаем `t1<t2<T>>`, который не совместим с `t1<T>`, поэтому его должно отсеивать.

**Comment by SunSerega** [comment]
А если считаете что не очень то полезная фича - подумайте, пожалуйста, ещё раз, потому что без этого OpenCLABC будет неюзабелен.

**Comment by miks1965** [comment]
А, да, согласен.

Да, здесь вывод маломощный - не может отсеять одну из близких версий

**Comment by miks1965** [comment]
```
type
  t1<T> = class
    static function operator implicit(o: T): t1<T> := nil;
  end;
  t2<T> = class(t1<T>) end;

procedure p<T>(r: t1<T>);
begin
  r := new t2<T>;
end;

begin 
end.
```

**Comment by miks1965** [comment]
convertion_data_and_algoritms.cs 1095
```
ptc = type_table.get_convertions(factparams[i].type, formal_param_type);
```

**Comment by miks1965** [comment]
Описанная ошибка - ерунда.
Вот гораздо более опасная ошибка:

```
type
  t1<T> = class
    static function operator implicit(o: T): t1<T> := nil;
  end;
  t2<T> = class end;

procedure p<T>(r: t1<T>);
begin
  r := new t2<T>;
end;

begin 
end.
```
Всё приводится и не мявкает.

Надо конечно приводить только t2<T> к t1<t2<T>> и т.п. Но по моим оценкам это - весьма весьма сложный алгоритм со скрупулёзным тестированием и тонкими запретами на какие-то частные случаи.

**Comment by miks1965** [comment]
@SunSerega, в любом случае быстро не поправим. Здесь надо или что-то решительно запрещать или писать серьёзный алгоритм.

**Comment by SunSerega** [comment]
Для `OpenCLABC` запрет будет значить то, что надо писать ` as CommandQueue<КакоеТоИмя>` на каждой второй строчке. При чём какое имя в `<>` - новичку будет сложно догадаться.

Лучше уже если это займёт больше времени, но чтоб работало.

Или - у меня завтра последний экзамен, дальше более-менее свободен буду. Если объясните что как работает - могу попробовать сам сделать...

**Comment by miks1965** [comment]
Там непредсказуемый алгоритм. Пока смотрю. Может, получится просто.
Если нет, там скорее всего на месяц работы - такого времени нет.
