### ISSUE TITLE
uses Namespace; ... n: SubNamespace.Name не работает

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#1959]
Скорее всего, из за фикса #1941 - перестало компилироваться следующее:
```
uses System;

begin
  var n: Numerics.BigInteger; //Ошибка: Неизвестное имя 'Numerics'
end.
```
Фикс #1941 должен влиять только на uses, а случай из кода выше - встречается уже в много где, и не у меня одного (у @AIexandrKotov тоже проект перестал собираться из за этого)

**Comment by miks1965** [comment]
Так и должно быть. Мы это запретили.

**Comment by MrFresnel** [comment]
> у @AIexandrKotov тоже проект перестал собираться из за этого

Это его проблемы, а не языка.

**Comment by AIexandrKotov** [comment]
А почему вы так решили?
Код тестируемой библиотеки:
```
using System;

namespace Lib
{
    namespace L1
    {
        public class T
        {
            public T()
            {
                Console.WriteLine(1);
            }

        }
    }
    namespace L2
    {
        public class T
        {
            public T()
            {
                Console.WriteLine(2);
            }

        }
    }
}
```
Код на PascalABC.NET:
```
{$reference 'lib.dll'}
uses Lib;
uses Lib.L1;
uses Lib.L2;

begin
  var a := new T(); //2, так как Lib.L2 подключено последнем
  var b := L1.T; // Неизвестное имя 'L1'
end.
```
Из-за этой хрени теперь к одинаковым именам разных пространств имён одного исходного пространства можно обратиться только напрямую, а значит только к одному из них, тому, который подключён последним. Это бред!

**Comment by miks1965** [comment]
Нет, нельзя. В C# ровно так же сделано. И правильно

**Comment by miks1965** [comment]
А вот почему L1 - неизвестное имя, - это я не пойму.
