### ISSUE TITLE
Падение компилятора

### ISSUE THREAD

**Issue by frninja** [pascalabcnet/pascalabcnet#196]
```
function f<T>(t1: T): sequence of T; 
  where T: System.IComparable<T>; forward;

function f<T>(t1: T): sequence of T; 
begin
  if true then
    begin
    end;
end;

begin
end.
```

**Comment by frninja** [comment]
Без forward-предописания нормально

**Comment by miks1965** [comment]
Да, это баг. А скажите, для чего Вам понадобились forward-объявления? Обычно они плохо сочетаются с синтаксическим сахаром. Никак без них нельзя обойтись?

**Comment by frninja** [comment]
Мне необходимо forward-объявление глобальной (не в классе) функции с yield, чтобы внутри нее работали ее рекурсивные вызовы

**Comment by frninja** [comment]
Точнее, чтоб не падал метод-хелпер для определения типов локальных переменных в этой функции (он помещается выше самой функции, и если внутри есть рекурсивные вызовы, нужен forward)

**Comment by ibond84** [comment]
завтра залью исправление. тесты долго прогонять.
