### ISSUE TITLE
Внутренняя ошибка при сталкивании метода расширения с константой класса при обращении через переменную

### ISSUE THREAD

**Issue by AIexandrKotov** [pascalabcnet/pascalabcnet#1960]
```
type
  T = class //(ну или record)
    const c1 = 1;
  end;
  
function c1(self: T); extensionmethod := 2;

begin
  var a := new T;
  writeln(a.c1);
end.
```

Стек:
```
Внутренняя ошибка компилятора в модуле [pabcnetc.exe] :'System.Exception: System.InvalidCastException: Не удалось привести тип объекта "PascalABCCompiler.TreeRealization.class_constant_definition" к типу "PascalABCCompiler.TreeRealization.common_function_node".
   в PascalABCCompiler.TreeConverter.compilation_context.check_unique_or_predefined(common_function_node fn)
   в PascalABCCompiler.TreeConverter.syntax_tree_visitor.visit(function_header _function_header)
   в PascalABCCompiler.TreeConverter.syntax_tree_visitor.visit(procedure_definition _procedure_definition)
   в PascalABCCompiler.TreeConverter.syntax_tree_visitor.visit(declarations _subprogram_definitions)
   в PascalABCCompiler.TreeConverter.syntax_tree_visitor.visit(block _block)
   в PascalABCCompiler.TreeConverter.syntax_tree_visitor.visit(program_module _program_module)
   в PascalABCCompiler.TreeConverter.SyntaxTreeToSemanticTreeConverter.CompileInterface(compilation_unit SyntaxUnit, unit_node_list UsedUnits, List`1 ErrorsList, List`1 WarningsList, SyntaxError parser_error, Hashtable bad_nodes, using_namespace_list namespaces, Dictionary`2 docs, Boolean debug, Boolean debugging)
   в PascalABCCompiler.Compiler.CompileUnit(unit_node_list Units, unit_or_namespace SyntaxUsesUnit)
   в PascalABCCompiler.Compiler.Compile()'
```

И весьма интересный вопрос в том, что с этим делать.

**Comment by AIexandrKotov** [comment]
Например, в случае с
```
type
  T = (A, B);
  
function A(self: T); extensionmethod := 2; //Program90.pas(4) : Имя функции используется для определения другого типа объекта (не функции)

begin
  var d: T;
  writeln(d.A);
end.
```

Но в нашем случае пересечение этого не должно ломать метод расширения, ибо к константе можно и через имя типа обратиться.

**Comment by SunSerega** [comment]
> ибо к константе можно и через имя типа обратиться.

С НЕ_анонимным энумом так же. А для анонимного - `extensionmethod` и не сделаешь.

**Comment by AIexandrKotov** [comment]
Тогда здесь два выхода:
1. Запретить обращение к константе для неанонимных типов через переменную
2. Запретить обращение к константе для неанонимных типов, если хоть один экстеншенметод пересекается с константой, и в данном случае ставить в приоритет, разумеется, метод расширения

Я больше склоняюсь к первому.

**Comment by miks1965** [comment]
А зачем вообще нужны константы в классе?

**Comment by SunSerega** [comment]
Чтоб собирать константы в отдельное пространство имён. + если с этими константами производятся какие то действия (как `case`) - удобно чтоб класс был не_статичный, и в нём самом все методы и разместить.

К примеру, в модуле OpenCL который я сейчас делаю:

![image](https://user-images.githubusercontent.com/27270190/58369588-34dd6780-7f05-11e9-8516-6fb2573392fd.png)

**Comment by miks1965** [comment]
А, ну да - все эти константы - статические для класса

**Comment by SunSerega** [comment]
Мне кажется обращение к константам через переменную сделано как раз для анонимных энумов:
```
begin
  var d: (A, B);
  writeln(d.A);
end.
```
@AIexandrKotov выше предложил 2 варианта исправления:
https://github.com/pascalabcnet/pascalabcnet/issues/1960#issuecomment-495908736

И я тоже считаю первый более хорошим.
+ он вроде более простой в реализации.

**Comment by miks1965** [comment]
Надо разрешить обращение к константам класса только через имя класса, а не экземпляра.

**Comment by AIexandrKotov** [comment]
> как раз для анонимных энумов

Для анонимных записей тоже.

**Comment by AIexandrKotov** [comment]
Но если тип анонимный (запись, энум), то для него оставить эту возможность. Определить им метод расширения всё равно нельзя, там пересекаться и не будет.

**Comment by miks1965** [comment]
Для анонимных энумов я бы эту запись тоже запретил

**Comment by AIexandrKotov** [comment]
```
var
  R: record
    const c1 = 1;
  end;
  
  E: (
    A,
    B,
    C
  );
  
begin
  R.c1.Println;
  E.A.ToString.Println;
end.
```
А как тогда к константам обращаться?

**Comment by SunSerega** [comment]
> Для анонимных энумов я бы эту запись тоже запретил

Тогда это и не должно работать: https://github.com/pascalabcnet/pascalabcnet/issues/1953

Но лучше всё же оставить...

**Comment by miks1965** [comment]
Ну, оно работает потому что вообще l.A работает. Когда запретим - перестанет
