### ISSUE TITLE
"Невозможно явно преобразовать тип _ к типу Func<integer>", при передаче лямбды в operator explicit

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#1961]
```
begin
  var f := Func0&<integer>(()->5);
end.
```
`Невозможно явно преобразовать тип  к типу Func<integer>`

**Comment by miks1965** [comment]
А эта хотелка уже где-то в Issues была - использовать функциональный тип в операции приведения типа

**Comment by SunSerega** [comment]
https://github.com/pascalabcnet/pascalabcnet/issues/964
Там ошибка другая.

А эта issue в первую очередь про неправильную ошибку. В тексте данной ошибки название первого типа полностью пропущено, а это даже хуже чем кишки показывать.

**Comment by miks1965** [comment]
Тогда я исправляю текст ошибки и закрываю Issue.
