### ISSUE TITLE
Сбой при записи pcu

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#1964]
```
unit u2;

interface

type
  
  
  // И зачем то ещё нужно это
  // Если убрать - не воспроизводится
  OtherClass = class
    
    static function f0 := default(int64); // возвращать должно что угодно кроме integer
    
    static procedure p1;
    begin
      new byte[f0]; // скобочки ставить нельзя, если написать f0() - не воспроизводится
    end;
    
  end;

implementation
end.
```

**Comment by SunSerega** [comment]
> Возможно подобное ещё где то проявится

Долго ждать не пришлось, через несколько мин после того как словил эту ошибку - сделал маленькое изменение в `OpenCLABC` и сразу получил #1965.

Эта ошибка - редко встречающаяся, но очень важная в исправлении. Добавьте, пожалуйста, 2 соответствующие метки.

**Comment by ibond84** [comment]
Поменял issue. К генерикам это не имеет никакого отношения.
