### ISSUE TITLE
Внутренняя ошибка при {$savepcu false} +использовании поля шаблонного класса

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#1965]
```

unit u;
{$savepcu false} // обязательно вырубить .pcu - иначе на второй компиляции не воспроизведётся

interface

type
  
  t1 = class
    
    static procedure p1<T>;
    
  end;
  
implementation

type
  // обязательно в implementation
  // если перенести в interface - не воспроизводится
  t2<T> = class // обязательно шаблонный класс
    
    b: byte;
    
  end;

static procedure t1.p1<T>;
begin
  var a: t2<T>; // обязательно <T> - то есть взять параметр шаблона данного метода
  
  a.b := 5; // обязательно любым способом взаимодействовать с любым полем
  
end;

end.
```
[Архив с модулем и программой для воспроизведения](https://github.com/pascalabcnet/pascalabcnet/files/3220238/0.zip)

Если подключить этот модуль к любой программе (или компилировать 0.pas из архива выше) - получаем это:
```
() : Внутренняя ошибка компилятора в модуле [pabcnetc.exe] :'System.Exception: System.NullReferenceException: Ссылка на объект не указывает на экземпляр объекта.
   в PascalABCCompiler.NETGenerator.ILConverter.ConvertCommonGenericInstanceTypeMembers(ICommonGenericTypeInstance value)
   в PascalABCCompiler.NETGenerator.ILConverter.ConvertTypeInstancesMembersInFunction(ICommonFunctionNode func)
   в PascalABCCompiler.NETGenerator.ILConverter.ConvertTypeMemberHeaders(ICommonTypeNode[] types)
   в PascalABCCompiler.NETGenerator.ILConverter.ConvertFromTree(IProgramNode p, String TargetFileName, String SourceFileName, CompilerOptions options, String[] ResourceFiles)
   в PascalABCCompiler.Compiler.Compile()'
```

Похоже на #1964 но это - другая ошибка, потому что тут - нужно `{$savepcu false}` для стабильного воспроизведения.
Иначе вторая и следующие компиляции - пройдут успешно.

**Comment by SunSerega** [comment]
Исправьте, пожалуйста, побыстрее, в основе одной из главных фич OpenCLABC - стоит подобный код, поэтому я постоянно получаю внутренние ошибки.

Без `{$savepcu false}` - кое как компилируется, но не совсем, ибо без него - эта ошибка не пропадает, а становится плавающей.

**Comment by AIexandrKotov** [comment]
> но это - другая ошибка
Правда? А стек абсолютно тот же. Пожалуй, правило написания issue нужно довести до ума. Если стек ошибок полностью совпадает, то стоит дополнить уже написанную issue, а не писать новую.

**Comment by SunSerega** [comment]
@ibond84 а вы как думаете, стоит ли в отдельную или это дубли?
