### ISSUE TITLE
Программа использующая System.Windows.Forms без $reference - запускается, но не компилируется

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#1967]
```
begin
  var f: System.Windows.Forms.Form;
end.
```
Если откомпилировать - не видит `Forms`.
А если запустить - пишет что откомпилировалось нормально.

**Comment by SunSerega** [comment]
Взято отсюда:
http://www.cyberforum.ru/pascalabc-net/thread2460173.html

**Comment by MrFresnel** [comment]
PascalABC.NET style...

**Comment by SunSerega** [comment]
У некоторых так же воспроизводится и с System.Drawing, всё в последней версии (2069).

На всяк - вот видео пруф:
https://youtu.be/VABFb30nZ0o

**Comment by SunSerega** [comment]
Ещё, что может быть неправильно - wf и gdi подключаются сами, без `$reference`:
![image](https://user-images.githubusercontent.com/27270190/58495697-ca386000-8180-11e9-9f7d-f21506951ebd.png)

**Comment by miks1965** [comment]
Это связано с тем, что программа, запущенная по F9, запускается в режиме связи с оболочкой.
При этом подключается модуль __RedirectIOMode (его можно посмотреть) и в нем есть
{$reference 'System.Windows.Forms.dll'}

При чистой компиляции приложение не прилинковывает к себе ничего лишнего

**Comment by SunSerega** [comment]
В таком случае issue закрывать?
