### ISSUE TITLE
Вызывает не ту перегрузку, если передать T(nil)

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#1972]
```
begin
  var s1 := Seq('abc','def');
  var s2 := s1 + string(nil); //Вызывает это: function operator+<T>(a, b: sequence of T): sequence of T; extensionmethod;
end.
```
Из за того что вызывает сложение 2 последовательностей а не последовательности и объекта - получаем ошибку.

Если `string(nil)` заменить на `string('')` - ошибки нет.

**Comment by AIexandrKotov** [comment]
Уточняю, string(nil) "воспринимается" как sequence of string.

**Comment by miks1965** [comment]
А в каком смысле вы понимаете string(nil)? Какого оно типа?

**Comment by SunSerega** [comment]
`string`, конечно. Для чего ж иначе это преобразование.
