### ISSUE TITLE
Разрешить предописание классов в пространствах имён

### ISSUE THREAD

**Issue by AIexandrKotov** [pascalabcnet/pascalabcnet#1975]
```
namespace Spacename;

type

T1 = class; // Предописание типов в пространствах имен недопустимо

T1 = class
  
end;

end.
```

Предописание классов имеет важное ограничение — предописание класса должно быть в одном блоке type с описанием. Это не должно давать возможности предописать класс в одном файле пространства, а описать — в другом.

Но вот в одном файле это разрешить нужно.

Находится всё в том же syntax_tree_visitor'е

**Comment by ibond84** [comment]
Предописания классов не нужны. Классы можно описывать где угодно, в любом файле. Он будет виден везде (как в C#)

**Comment by SunSerega** [comment]
А как тогда делать циклические зависимости классов?
И для него же надо и #1974.
