### ISSUE TITLE
Лямбда не захватывает переменную в методе класса наследующего от шаблонного, когда это всё в модуле

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#1976]
`0.pas`:
```
uses u;

begin
  var a := new t1;
  a.p1;
end.
```
`u.pas`:
```
unit u;

type
  t0<T> = class end;
  
  t1 = class(t0<byte>)
    
    procedure p1;
    begin
      var b: byte := 5;
      
      var p: procedure := ()->
      begin
        
        writeln(b); // выводит 0
        
      end;
      p();
      
    end;
    
  end;
  
end.
```

При первой компиляции #1880, не обращайте сейчас на это внимания. Потому что при второй - получаем на много более опасную ошибку!

Вместо того чтоб захватить `b` - в лямбде создаётся новая переменная, у которой значение, разумеется, обнулено. Поэтому выводит эта программа 0 а не 5.

Похоже, это проблема с записью .pcu после получения внутренней ошибки.

**Comment by miks1965** [comment]
Само наладилось
