### ISSUE TITLE
Разрешить объявлять имя пространства в пространствах имён

### ISSUE THREAD

**Issue by AIexandrKotov** [pascalabcnet/pascalabcnet#1977]
```
namespace Spacename;

type
  Spacename = class end; // Повторно объявленный идентификатор Spacename

end.
```
Поскольку это не модуль, стандартный класс с именем пространства не создаётся. А значит, ничего не мешает разрешить данную конструкцию.

И всё это не просто хотелки, так должно быть. Думаю, после этих трёх issue, полноценно использовать пространства имён уже будет можно. Пусть пока и без анализатора кода

**Comment by miks1965** [comment]
У меня вообще Undefined filename при компиляции этого. 

Пространства имен сильно не доделаны

**Comment by AIexandrKotov** [comment]
Пространства имён нельзя запускать. Их нужно подключать к чему-то. Только так они и работают.

![image](https://user-images.githubusercontent.com/44296606/59070831-e9439a00-88c4-11e9-9cfe-e1ad2b7eaa12.png)

**Comment by miks1965** [comment]
Запускать можно всё. Если кнопочка Run доступна, ЭТО обязательно будут запускать. Нужно приличную реакцию на ошибку

**Comment by ibond84** [comment]
>как можно доделывать в том, что сильно не доделано

ну, лямбды коих issues тут 90%, как-то доделываются... ошибку с undefined name исправлю.
