### ISSUE TITLE
dispose(pointer) не принимает бестиповый указатель

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#1979]
```
begin
  var p: pointer;
  dispose(p); //Ошибка: Неправильный тип параметров подпрограммы
end.
```
Вызов `dispose` для `^byte` выглядит так:
```
      Program.dispose((void*&) ref numPtr, Marshal.SizeOf(typeof (byte)));
```
А его тело (дотпик сдох на нём, поэтому только IL):
```
    IL_0000: ldarg.0      // ptr
    IL_0001: ldind.i
    IL_0002: call         void [mscorlib]System.Runtime.InteropServices.Marshal::FreeHGlobal(native int)
    IL_0007: ldarg.0      // ptr
    IL_0008: ldnull
    IL_0009: stind.i
    IL_000a: ret
```
Как видите, второй параметр (размер памяти) вообще не используется.
`Marshal.FreeHGlobal` не нужно знать размер неуправляемой памяти чтоб освободить её.
А значит `dispose` можно вызывать и для бестиповых указателей.

**Comment by miks1965** [comment]
Ну правильно, в Delphi тоже не принимает

**Comment by SunSerega** [comment]
Ну а дельфи тут при чём то?
По крайней мере, надо выкинуть этот мусор в виде второго параметра, его только зря считает.
Но раз .Net позволяет - почему не разрешить?

**Comment by miks1965** [comment]
PascalABC.NET в старом коде реализует функциональность Delphi. C# тут вообще ни при чём. Делать реализацию функций старого кода более эффективной - мы не будем.
