### ISSUE TITLE
Re: Компилятор не может выбрать между operator implicit и приведению к предку, когда у operator implicit не подходит тип шаблона

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#1981]
#1957 всё ещё воспроизводится, если вместо присвоения будет передача параметром в подпрограмму:
```
type
  t0<T> = class
    static function operator implicit(o: T): t0<T> := nil;
  end;
  
  t1 = class(t0<byte>) end;
  
// не обязательно шаблонная процедура
// если принимать t0<byte> - всё равно воспроизводится
procedure p1<T>(q: t0<T>) := exit;

begin
  var prog_Q: t1;
  p1(prog_Q); //Ошибка: Возможны два преобразования типов
end.
```

**Comment by SunSerega** [comment]
Исправьте, пожалуйста, поскорее, ибо в итоге в #1957 вы исправили то - что мешало только внутри `OpenCLABC`, а в самих программах с ним мешает именно эта issue.

Из за этого, вместо:
```
  var prog_Q :=
    prog['TEST'].NewQueue.Exec(10,
      
      A.NewQueue.WriteData(
        ArrFill(10,1)
      )
      
    );
```
Приходится писать:
```
  var prog_Q :=
    prog['TEST'].NewQueue.Exec(10,
      
      A.NewQueue.WriteData(
        ArrFill(10,1)
      ) as CommandQueue<KernelArg>
      
    ) as CommandQueue<Kernel>;
```
И, как я ещё сказал так - какой тип надо ставить в `<>`  - не понятно, не залезая в кишки `OpenCLABC`, что не хорошо, особенно для обучения.

**Comment by SunSerega** [comment]
Недавно состояние оператора `implicit` ухудшилось. Вот это перестало компилироваться:
```
uses OpenCLABC;

begin
  var b := new Buffer(1);
  Context.Default.SyncInvoke(
    b.NewQueue
    .AddProc(b->raise new Exception($'{b.Size}, TestOK'))
  );
end.
```
Теперь тут тоже надо `as CommandQueue<Buffer>`.

Я не ожидаю что вы прямо сразу будете исправлять, но я хотел чтоб вы знали, если сделали это случайно...

**Comment by ibond84** [comment]
https://github.com/pascalabcnet/pascalabcnet/actions/runs/467007796

**Comment by ibond84** [comment]
Последнее тоже работает
