### ISSUE TITLE
Graph3D.RGB в режиме без ускорения даёт ошибку компиляции

### ISSUE THREAD

**Issue by miks1965** [pascalabcnet/pascalabcnet#1987]
```
library lib;

uses Graph3D;

end.
```

```
{$reference lib.dll}

begin
  var a := Graph3D.RGB(148,136,136);
  Print(1);
end.
```
a.pas(6) : Неизвестное имя 'RGB'

**Comment by SunSerega** [comment]
Вы имели в виду что в первой программе в начале должно быть `library lib;`?

**Comment by ibond84** [comment]
Почему вдруг RGB должен быть виден? Он не зашивается в dll, потому что не используется в инициализационной части модуля Graph3D.

**Comment by SunSerega** [comment]
`.dll` это не `.exe`, в `.dll` надо зашивать всё, как из основной программы, так и из модулей, потому что не известно что из этого будет использовано дальше.

**Comment by ibond84** [comment]
Да глупости.

**Comment by ibond84** [comment]
Посмотрите на размер PABCRtl.dll. Пихать это все в dll это мягко говоря плохо.

**Comment by SunSerega** [comment]
Ну так `PABCRtl.dll` это же `.dll` а не модуль, её и пихать незачем.

**Comment by ibond84** [comment]
Ошибки нет. Поступило предложение ввести ключевое слово import для импортирования всего модуля.
