### ISSUE TITLE
Сломалось прямое замыкание статических методов классов

### ISSUE THREAD

**Issue by AIexandrKotov** [pascalabcnet/pascalabcnet#1991]
В коде, который я 3 месяца не трогал (но успешно компилировал) перестала работать данная конструкция:
```
type
  T = class
    public static procedure p1(a: integer) := exit;
    
    public static procedure P := &Array.ForEach(Arr(0), x -> p1(x)); // В данной версии компилятора не поддерживается замыкание данного типа символов
  end;

begin
  
end.
```
Началось в версии 2090 (последняя, доступная на сайте)
Если обратиться T.p1, то всё работает.

**Comment by AIexandrKotov** [comment]
В 2069 работает нормально:
![image](https://user-images.githubusercontent.com/44296606/59271760-1396ae00-8c5d-11e9-875f-613bd26d427f.png)

**Comment by miks1965** [comment]
Это из-за fix 891.

**Comment by miks1965** [comment]
Вернул
