### ISSUE TITLE
t0<T> - При захвате лямбдой локальной переменной и статического поля обобщенного надкласса

### ISSUE THREAD

**Issue by miks1965** [pascalabcnet/pascalabcnet#1993]
```
type
  t0<t> = class
    public static a1: byte := 2;
  end;
  t1 = class(t0<integer>)
    private procedure p1;
    begin
      var a2: word := 3;
      var pp1: ()->integer := ()->a1+a2;
      Assert(pp1=5);
    end;
  end;

begin 
  t1&<integer>.Create.p1
end.
```
Неаккуратное исправление #1968 

Сейчас вдобавок ко всему - падает

**Comment by SunSerega** [comment]
У меня не падает. Мне надо было кое что проверить только что, поэтому я собрал новую версию. И у меня эта программа успешно выполняется и `Assert` проходит.

**Comment by Terky** [comment]
Падало и без моего исправления, но я понял, постараюсь поправить

**Comment by Terky** [comment]
Хорошо, я правильно понимаю что вот такой код должен работать?
Данный код приводит к ошибке "Ожидалось имя переменной" в строке `t1&<integer>.Create.p1`

`type
  t0<t> = class
    public static a1: byte := 2;
  end;
  t1 = class(t0<integer>)
    private procedure p1;
    begin
      var a2: word := 3;
      var pp1: ()->integer := ()-> t0&<integer>.a1 + a2;
      Assert(pp1=5);
    end;
  end;

begin 
  t1&<integer>.Create.p1
end.`

**Comment by miks1965** [comment]
Нет, он должен выдавать ошибку - t1 - не обобщенный класс. Ошибка наверное должна быть другая, но падать - точно не должно. Должен работать код с 
```
t1.Create.p1
```

**Comment by Terky** [comment]
Тогда аналогичный тому что я написал с заменой на просто t1 падает с исключением в NETGenerator.cs

**Comment by miks1965** [comment]
Не понял. ЧТо падает? Приведите полный код - не говорите загадками

**Comment by Terky** [comment]
Вот такой код

```
type
  t0<t> = class
    public static a1: byte := 2;
  end;
  t1 = class(t0<integer>)
    private procedure p1;
    begin
      var a2: word := 3;
      var pp1: ()->integer := ()-> t0&<integer>.a1 + a2;
      Assert(pp1=5);
    end;
  end;

begin 
  t1.Create.p1
end.
```

**Comment by miks1965** [comment]
Надо посмотреть на то, какое формируется синтаксическое дерево. И если есть ошибка на уровне IL, то выявить код БЕЗ ЛЯМБД. который её даёт. Но скорее всего виноваты именно лямбды. Скажем, второй обход.

В любом случае ошибку надо исправлять

**Comment by SunSerega** [comment]
Да, если заменить лямбды на их реализацию компилятором - ошибки нет:
```
type
  t0<t> = class
    public static a1: byte := 2;
  end;
  
  local_var_class1 = class
    a2: word;
    
    function lambda1: integer :=
    t0&<integer>.a1 + a2;
    
  end;
  
  t1 = class(t0<integer>)
    private procedure p1;
    begin
      var o := new local_var_class1;
      o.a2 := 3;
      var pp1: ()->integer := o.lambda1;
      Assert(pp1=5);
    end;
  end;

begin 
  t1.Create.p1
end.
```

**Comment by miks1965** [comment]
Вот и надо нормально заменить лямбды на их реализацию компилятором, а не говорить, что что-то на IL-коде не работает.
