### ISSUE TITLE
Инициализировать значение переменной цикла значением левой границы цикла

### ISSUE THREAD

**Issue by AIexandrKotov** [pascalabcnet/pascalabcnet#1994]
Этот код компилируется:
```
begin
  for var i := -3 to i do // жесть
  begin
    write(i);
  end;
end.
```
И выводит, соответственно: `-3-2-10`, поскольку i в момент инициализации имеет значение по умолчанию.

Для обычных циклов даже такой код ошибочным являться не будет:
```
begin
  var i: integer;
  for i := i to i do write(i);
end.
```

**Comment by miks1965** [comment]
Вот аналогичный код на C#. Он компилируется и работает:
```
for (var i = 0; i <= i; i++)
       Console.Write($"{i} ");
```
После того как вы описали переменную, вы можете делать с ней что захотите

**Comment by ibond84** [comment]
issue надо закрыть. переменная i в правой части цикла вычисляется один раз, жести здесь никакой нет.

**Comment by miks1965** [comment]
Думаю, AIexandrKotov переживает, что i инициализируется нулём, а не -3

**Comment by ibond84** [comment]
Ну, во всех компиляторах паскаля такое же поведение. Не вижу здесь ничего криминального.

**Comment by AIexandrKotov** [comment]
А во всех компиляторах паскаля есть конструкция for var? Мне кажется, только в PascalABC.NET (быть может в Oxygene, но я его не знаю), так что это часть вашего стандарта кода, которого ещё нет.

Но вообще, необходимость данной конструкции весьма сомнительна.

**Comment by ibond84** [comment]
>Но вообще, необходимость данной конструкции весьма сомнительна.

Ну, никто не запрещает вам определять переменную цикла "по старинке", на экран выше, в блоке описаний...

**Comment by ibond84** [comment]
for var ничем семантически не отличается от for. все то же самое.

**Comment by SunSerega** [comment]
Да, но так же писать нельзя:
```
begin
  var i: integer := i;
end.
```
И во всех остальных местах в языке, в выражении, которое присваивается переменной, там где она объявлена - не может быть использование самой этой переменной.

Это запрещено даже в местах где в этом есть не-говно_кодская польза:
```
begin
  var p: procedure := ()->
  begin
    if ReadBoolean then p; //Ошибка: Неизвестное имя 'p'
  end;
end.
```
Поэтому странно разрешать это в случае `for`.

**Comment by AIexandrKotov** [comment]
Нет, к моменту объявления правой границы цикла, i уже существует в контексте.

**Comment by ibond84** [comment]
Не буду запрещать

**Comment by miks1965** [comment]
Запрещать не надо. Но - тут вот какая проблема.
```
uses A;
begin
  var i: integer := i; // i в инициализации приходит из модуля A
end.
```
А тут 
```
uses A;
begin
  for var i := -3 to i do // i используется из for
end.
```
Правильно ли это? Я бы использовал из модуля A или может использовал определённую из цикла for, но инициализированную в -3. Последнее решение вполне нормально, поскольку for образует легковесное пространство имен. Не глянете - технически это сложно сделать?

**Comment by ibond84** [comment]
Все правильно. В for i уже определен, а в инициализации нет

**Comment by miks1965** [comment]
Согласен. Просто инициализация в цикле - это не инициализация переменной при создании.

**Comment by miks1965** [comment]
Вообщем, оставляем issue и будем инициализировать i значением -3

**Comment by ibond84** [comment]
В паскалях все-таки вычисляется сначала правое значение. Поэтому программа работает правильно. Не нужно тут ничего переделывать.

**Comment by AIexandrKotov** [comment]
Как сделано в Oxygene?

**Comment by miks1965** [comment]
Посмотрите

**Comment by miks1965** [comment]
> В паскалях все-таки вычисляется сначала правое значение. Поэтому программа работает правильно. Не нужно тут ничего переделывать.

А откуда такое, что в паскалях вычисляется правое значение?

**Comment by ibond84** [comment]
Ну проверьте сами
