### ISSUE TITLE
Лямбда, захватывающая поле и ещё что-нибудь - сломалась

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#1997]
Похоже, после исправления цепочки #1880 - полетело это:
```
type
  t1 = class
    f := 1;
    
    public procedure p1;
    begin
      var v := 2;
      
      var p: procedure := ()->
      begin
        var nf := f; //Ошибка: f не объявлен в типе <>local_variables_class_0
        
        // обязательно захватить что то ещё, не важно поле или параметр
        // но НЕ ещё 1 поле, с 2 полями не воспроизводится
        var nv := v;
        
      end;
      
    end;
    
  end;

begin end.
```
При чём, наблюдается феномен:
В больших программах, где такая конструкция наверняка встречается и не раз - этой ошибки нет.
Наверное, её можно заглушить нагромождением ещё чего то поверх, но не знаю чего...

Пожалуйста, не забудьте добавить эту программу в тесты, ибо это же 1 из базовых возможностей лямбд. Надо чтоб сразу видно было если от каких то изменений - такая программа сломается.

**Comment by miks1965** [comment]
А когда это работало?

**Comment by miks1965** [comment]
https://github.com/pascalabcnet/pascalabcnet/issues/891 - похожая была.

**Comment by miks1965** [comment]
```
type
  t1 = class
  public 
    f: integer;
    procedure p1;
    begin
      var v := 2;
      var p: procedure := ()->
      begin
        var nv := v;
        var nf := f;
      end;
    end;
  end;

begin 
end.
```
Код для тестирования

**Comment by miks1965** [comment]
Исправил. Ошибка важная. Залил на сайт
