### ISSUE TITLE
Лямбда не должна захватывать Result функции

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#1999]
```
function f1: byte;
begin
  
  System.Threading.Tasks.Task&<real>.Run(()->
  begin
    Result := 0.0; //Ошибка: Нельзя преобразовать тип real к byte
  end);
  
end;

begin end.
```
`Result` не должен захватываться, никогда, это создаёт тонну неопределённостей.

И, вне `Task&<T>.Run` `Result` как раз не захватывается:
```
function f1: byte;
begin
  
  var f: ()->real := ()->
  begin
    Result := 0.0; // ok
  end;
  
end;

begin end.
```

**Comment by miks1965** [comment]
По поводу первого кода - вроде всё правильно. В лямбде 
```
()->
  begin
    Result := 0.0; // ok
  end;
```
это её Result. Согласно одной из перегрузок параметром является функция, возвращающая Task<real>, что несовместимо с 0.0

Закрывать?

**Comment by SunSerega** [comment]
> У меня пишет
>
> 0.pas(5) : Нельзя преобразовать тип real к System.Threading.Tasks.Task

Это в первом коде? Потому что у меня так не пишет.

**Comment by SunSerega** [comment]
Возможно это исправилось с последними фиксами #1744...
Если так то проблема остаётся только в #1952, тогда можете закрывать.
