### ISSUE TITLE
Можно получить элемент перечисления через точку с помощью другого элемента перечисления

### ISSUE THREAD

**Issue by VanillaFlame** [pascalabcnet/pascalabcnet#2005]
Успешно компилируется и исполняется:
```
type Foo = (One, Two, Three, Four);
begin
  print(Foo.One.Two.Three.Four.Four.Two.One);
end.
```

Работает и так:
```
begin
var l: (A, B, C);
  print(l.A.B.C.A.a.a.a.a.a.a.a.a);
end.
```

**Comment by SunSerega** [comment]
Ну, это то должно работать:
```
begin
  var l: (A, B, C);
  print(l.A);
end.
```
Вы предлагаете разрешить такое только 1 раз и только после имени переменной?

**Comment by ibond84** [comment]
>Ну, это то должно работать:
нет

**Comment by AIexandrKotov** [comment]
Почему нет? Как тогда анонимными энумами пользоваться?

**Comment by SunSerega** [comment]
Ну, всё ещё работает так...
```
begin
  var l: (A, B, C);
  print(A);
end.
```

**Comment by miks1965** [comment]
```
begin
var l: (A, B, C);
  print(l.A);
end.
```
Это не должно работать

**Comment by AlexRnD61** [comment]
> Это не должно работать. Это надо запретить.
Однозначно не должно. Это противоречит синтаксису использования перечислений.
