### ISSUE TITLE
Процедурная переменная без скобок считается вызовов в некоторых случаях

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#2010]
```
function f0: integer;
begin
  writeln('f0');
end;

begin
  var f: ()->integer := f0;
  
  var o: object := f0;  // при присвоении переменной на строчке с var, если указать тип
  o := f0;              // при присвоении ранее объявленной переменной
  writeln(f0);          // при передачи в виде параметра
  
end.
```
Какие ещё есть различные случаи?

**Comment by miks1965** [comment]
Здесь везде - вызов функции f0. Ни одного вызова процедурной переменной тут нет. Вы путаете термины

**Comment by SunSerega** [comment]
А, тупил немного утром. Исправил.

Случаи где это воспроизводится то я и так знаю, просто `f0` вместо `f` написал во всех...

**Comment by miks1965** [comment]
Да, тут всё верно. Три последних оператора дают вызов. Первый - ссылка.

Посмотрите форум. Мы привели наше решение, которое де-факто имеется в PascalABC.NET.
