### ISSUE TITLE
Неверно работает алгоритм выбора нужной функции при подключении (посредством uses) модулей, содержащих одноименные функции с одинаковым списком параметров, но возвращающие результаты разного типа

### ISSUE THREAD

**Issue by AlexRnD61** [pascalabcnet/pascalabcnet#2012]
Пусть имеется основная программа
```
uses m;

function f(a: integer) := 10;

begin
  var r := f(0);
  Writeln('Тип r=', r.GetType)
end.
```
Пусть также имеется модуль m
```
unit m;

function f(a: integer) := int64(20);

begin
  Println('Модуль m:', f(0))
end.
```
По логике должна вызываться функция f из основной программы, но вызывается f.m. Если сделать одинаковый возвращаемый тип, будет вызываться f из основной программы. Если типы возвращаемого результата приводимы один к другому, выбирается функция, у которой результат имеет более общий тип. Если же типы неприводимы, то компилятор фиксирует ошибку, диагностируя возможность вызова нескольких функций, т.е. он "не понимает", какую из функций выбрать. Например, если один тип результата integer, а второй real, всегда будет выбираться та из функций, у которой тип real, но если один тип integer, а второй - string, будет зафиксирована ошибка.

**Comment by miks1965** [comment]
Должна вызываться функция f из основной программы. Поведение абсолютно не ожидаемо.

**Comment by ibond84** [comment]
Код вверху вообще некорректный. Скобка не закрыта, r не объявлен

**Comment by ibond84** [comment]
Поправил
