### ISSUE TITLE
Разрешить синонимы типов в пространствах имён

### ISSUE THREAD

**Issue by AIexandrKotov** [pascalabcnet/pascalabcnet#2014]
```
namespace Spacename;

type //Unit1.pas(3) : В пространство имен можно описывать только классы, записи, перечислимые и процедурные типы
  T = Action<byte>;

end.
```

**Comment by ibond84** [comment]
Не вижу в них никакого смысла, они не CLS-compliant.

**Comment by AIexandrKotov** [comment]
Синонимы типов это одна из годных фич оригинального паскаля. Кроме того, что они помогают визуально, с помощью них, при подключении двух и более пространств имён с общими именами, можно переопределить имя типа как синоним одного, наиболее нужного, чтобы не писать полное имя.

**Comment by SunSerega** [comment]
> Они не CLS-compliant

Тем не менее, в библиотеках они работают, то есть как то всё же пакуются.

> Не вижу в них никакого смысла

Ну, кроме того что без этого не будут работать старомодные фичи вроде статичных массивов...

По моему, лучшее применение им - визуальное разделение 1 типа на несколько и возможность легко редактировать тип сразу в куче мест в программе. То есть:

```
  cl_platform_id                = IntPtr;
  cl_device_id                  = IntPtr;
  cl_context                    = IntPtr;
  cl_command_queue              = IntPtr;
  cl_mem                        = IntPtr;
  cl_program                    = IntPtr;
  cl_kernel                     = IntPtr;
  cl_event                      = IntPtr;
  cl_sampler                    = IntPtr;
```
(это из OpenCL.pas)

1. Видя подпрограмму, которая принимает `cl_command_queue` - сразу понятно что туда надо передавать дескриптор очереди команд. Если бы принимало `IntPtr` - того же эффекта не было.

2. Вдруг оказывается, что дескриптор `OpenGL.QueryName` это не `IntPtr` а `UInt32`. Я не отфига взял, я действительно сначала думал что он `IntPtr` как всё в OpenCL. Без синонимов надо было бы поменять в тонне мест, при чём пропустить какое то 1 место или поменять что не надо - было бы легче простого. А с синонимом - я в 1 месте поменял, в самом заголовке модуля, и всё.

**Comment by ibond84** [comment]
Ну, чистые синонимы CLS-совместимых типов можно разрешит. Статические массивы, короткие строки и прочий атавизм нет.

**Comment by SunSerega** [comment]
А чем статические массивы и т.п. не CLS совместимы? Их же всё равно отдельными классами реализовывает, которые уже совместимы.

**Comment by ibond84** [comment]
Это костыли, внутренняя реализация.

**Comment by SunSerega** [comment]
Да понятно что костыли, но они же всё равно CLS совместимы, разве нет?

Но, вопрос вообще не в ту сторону направлен получился. Лучше спросить, надо ли дописывать отдельный код в компиляторе чтоб работал и старомодный говнокод. Или он сам станет работать, если разрешить синонимы в пространствах имён. Если последнее - то и запрещать нечего.
