### ISSUE TITLE
Никак не реагирует на uses <несуществующее пространство имён> в пространствах имён

### ISSUE THREAD

**Issue by AIexandrKotov** [pascalabcnet/pascalabcnet#2015]
```
namespace Spacename;
uses CHTOUGODNO; //Никак не реагирует

end.
```

**Comment by ibond84** [comment]
Пространства имен подключаются к основной программе. И все классы видны отовсюду (как в C#)

**Comment by AIexandrKotov** [comment]
Тут имена пространств отличаются же, но прописано `uses Spacename1;`, значит все имена этого пространства должны включиться в контекст. Даже Intellisense нормально видит, почему компилятор не воспринимает?

**Comment by ibond84** [comment]
Приведите полный код, включая код основной программы. У меня все работает

**Comment by AIexandrKotov** [comment]
А, я имя не так написал. Тогда тут в другом прикол.
```
namespace Spacename;
uses CHTOUGODNO; //Никак не реагирует

end.
```
