### ISSUE TITLE
Разрешить методы расширения в статических классах

### ISSUE THREAD

**Issue by AIexandrKotov** [pascalabcnet/pascalabcnet#2017]
```
type
  T = static class
    public static function Sqr(self: integer): integer; extensionmethod := self*self;
  end;

begin
  writeln(5.Sqr);
end.
```

Пока вызывает ошибку:
`Program48.pas(3) : Атрибут extensionmethod допустим только для глобальных подпрограмм`

**Comment by ibond84** [comment]
Да, надо разрешить определять в статических классах

**Comment by AIexandrKotov** [comment]
А может разрешите в любых классах? С единственным запретом, что в качестве типа self не может использоваться класс, в котором extensionmethod описан. Пересекаться self всё равно не будут, ибо ВСЕ методы расширений ВСЕГДА СТАТИЧЕСКИЕ.

**Comment by miks1965** [comment]
А в чём глубинный смысл разрешить объявлять в статических классах? Они ж при вызове нигде не фигурируют?

**Comment by AIexandrKotov** [comment]
Изначально issue была про то что из-за этого необоснованного ограничения невозможно определять методы расширения в пространствах имён.

**Comment by miks1965** [comment]
@ibond - мне кажется, этот Issue надо убить.

**Comment by ibond84** [comment]
Там много переделывать. Сделал проще: разрешил подпрограммы в пространствах имен
