### ISSUE TITLE
Re: Компилятор не даёт вызвать 1 конструктор из другого, если передать лямбду

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#2020]
```
type
  t1 = class
    
    constructor(f: ()->byte) := exit;
    
    constructor :=
    Create(nil); // Работает
    
    constructor(b: byte) :=
    Create(()->b); //Ошибка: Лямбда-выражения как параметры конструктора запрещены в этом контексте
    
  end;

begin end.
```
Как я и сказал в #1956, в IL коде можно вызывать что угодно до вызова конструктора, а значит это можно исправить не_костылём.

**Comment by miks1965** [comment]
Не настаивайте. Мы это запретили. Странно открывать такой же повторный Issue

**Comment by SunSerega** [comment]
Это очень нужная фича, нельзя это запрещать!

**Comment by miks1965** [comment]
Вы странно себя ведёте. Вы придумали, что это возможно, хотя в нескольких "больших" языках это запрещено: в C++, C#, Java вызов конструктора предка делается всегда до вызова конструктора потомка. 
После этого написали Issue. Её закрыли.
И теперь пишете - "без особой причины"

**Comment by SunSerega** [comment]
Я не предлагаю разрешить писать код перед вызовом конструктора предка.

Но передавать лямбду из 1 конструктора в другой - возможно. Именно про это я говорю, что вы без причины запретили.

> Вы странно себя ведёте

В последнее время вы стали очень часто делать запреты только потому что на нормальную реализацию надо больше времени и сил. Я всегда против такого выступал, сейчас лишь больше поводов.

**Comment by miks1965** [comment]
Понял. Ну, у нас архитектура конструкторов другая нежели в C#. И лямбды разворачиваются в код когда - требуется пара дополнительных операторов перед вызовом конструктора. А значит, конструктор становится не первым и всё падает.

Это невозможно победить. Отсюда такое ограничение

**Comment by SunSerega** [comment]
Да я же говорю, `System.Reflection.Emit` не даёт такого ограничения! Это всё в коде компилятора. А значит можно поставить исключение, если в операторе есть недопустимые знаки, как `<>` или `$`, что бывает только у внутренней реализации разного сахара - значит разрешить.

**Comment by miks1965** [comment]
Я говорю про архитектуру компилятора. Надо либо полностью менять архитектуру компилятора, либо писать новый.

К тому же, не забывайте, что с точки зрения теории типов Emit разрешает те вещи, которые нельзя разрешать с точки зрения безопасности типов. Я тут не знаю теории и могу лишь полагаться на принятые в нескольких языках решения.
