### ISSUE TITLE
Разрешить оператор у которого возвращаемое значение совпадает с типом, в котором он объявлен

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#2021]
```
type
  r1 = record end;
  r2 = record end;
  r3 = record
    
    public static function operator*(a: r1; b: r2): r3 :=
    default(r3);
    
  end;

begin end.
```

**Comment by miks1965** [comment]
Определите в r2

**Comment by SunSerega** [comment]
В `r2` не видно `r3`. У меня эта ситуация в OpenGL, и там такое циклично. Поэтому если я перемещу `r2` на после `r3` - в OpenGL будет та же ошибка.

Кроме всего, в чём причина запрета таких операторов?

**Comment by miks1965** [comment]
Это формальное ограничение. Когда мы ищем, где определена операция a*b, мы смотрим только типы операндов a и b. А при вашем подходе необходимо вообще перебирать все возможные классы. И - это приводит к коллизиям.

То, что вам удобно это для вашего проекта OpenGL - не оправдание, а скорее противопоказание. Нельзя вводить странную фичу, отсутствующую в других языках, со словами "мне так удобно"

**Comment by SunSerega** [comment]
Ладно, в C# так же... Ну, хорошо хоть `extensionmethod` для операторов есть...
