### ISSUE TITLE
Разрешить применять [MarshalAs] к Result

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#2029]
```
    [return: MarshalAs(UnmanagedType.LPStr)]
    static function GetString(name: GLGetStringQueries): string;
    external 'opengl32.dll' name 'glGetString';
```
`Ошибка: Данная конструкция не поддерживается текущей версией компилятора`

Синтаксис не обязательно должен быть такой, это я просто стырил из C#. Лучше вообще `Result: ` а не `return: `...
Но какой то способ указать это - обязательно должен быть!

**Comment by miks1965** [comment]
Ой ты мама дорогая. Я бы это запретил.
Жду, что скажет ibond.

**Comment by SunSerega** [comment]
Вы что! Может сразу и половину атрибутов запретите? Это функционал у которого нет достойных аналогов.
Пожалуйста, перестаньте запрещать от не желания исправлять...

**Comment by miks1965** [comment]
Вы путаете. Мы ничего не запрещаем. Это вы пишете, что хотите что-то запретить. 

Этот функционал просто не реализован.

**Comment by SunSerega** [comment]
Вы написали:

> Я бы это запретил

Как я понял - вы хотели запретить форму записи `[применение: ИмяАтрибута]`.
Ну а то что не реализовано - это понятно, и ошибка об этом говорит...

**Comment by SunSerega** [comment]
Я так понял, вы разрешили указывать и `return: ` и `result: `? Если что - это прекрасно, но я чуть точно знать.
