### ISSUE TITLE
Проблема с использованием Result в yield

### ISSUE THREAD

**Issue by miks1965** [pascalabcnet/pascalabcnet#203]
```
function f: sequence of integer;
  begin
    for var i:=1 to 5 do
      yield i;
    Result := Seq(1,2,3);  
  end;
  
begin
  
end.  
```
Program1.pas(5) : Нельзя преобразовать тип IEnumerable<integer> к boolean

**Comment by miks1965** [comment]
Нет, не работает.
Еще раз - что я имею в виду:
1. Result := Seq(1,2,3); приводит к ошибке 
Program1.pas(5) : Нельзя преобразовать тип IEnumerable<integer> к boolean
2.     Result := True;  приводит к ошибке 
Program1.pas(5) : Нельзя преобразовать тип IEnumerable<integer> к boolean

Замкнутый круг.

Кстати, я там закомментировал проверку приваивания Result поскольку у Вас она работала некорректно на тот момент, возвращая сообщение что нельзя использовать Result в случае 

yield Seq(1,2,3)

**Comment by frninja** [comment]
Если раскомментировать эту проверку, то ошибки 1 и 2 обрабатываются верно, yield Seq(1,2,3)
Program1.pas(3) : Нельзя преобразовать тип IEnumerable<integer> к integer
Т.е операндом yield служит тип указанный в sequence of, логично.
И не предполагалось что yield умеет возвращать коллекцию, вот что говорит код на C#
        public IEnumerable<int> TestSeqYield()
        {
            yield return Enumerable.Range(1, 3);
        }
Error	1	Cannot implicitly convert type 'System.Collections.Generic.IEnumerable<int>' to 'int'
