### ISSUE TITLE
Кажущаяся ужасной ошибка при свойствах A и GET_A

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#2030]
```
type
  t1 = class
    
    property A: integer read 0;
    property GET_A: integer read 0; //Ошибка : Повторно объявленный идентификатор GET_A
    
  end;

begin end.
```
Как минимум, надо выдавать нормальную ошибку, потому что с этой совершенно не понятно что произошло.

Но - `IL` код принимает 2 одинаковых имени, и компилятор должно быть не сложно заставить нормально их воспринимать. Потому что 1 имя - функция, а другое - свойство. А значит легко понять что именно нужно программисту. Более того, то имя что функция - всё равно не видимо...

**Comment by miks1965** [comment]
Ну это спорный момент. Мы уже писали о нем. Действительно, свойства автоматически генерируют методы Get_Имя и Set_Имя. И идентификатор - повторно объявленный.

**Comment by SunSerega** [comment]
Ещё раз, ужасное тут то - что сложно понять что именно хочет компилятор.
У меня это было типе, у которого где-то 50 свойств, и я далеко не сразу понял что тут такая ситуация.

Кроме того, как я и сказал - даже если разрешить это, а не делать другое сообщение об ошибке - НИЧЕГО СЛОМАТЬСЯ НЕ ДОЛЖНО! IL разрешатет, а компилятор смотреть на имя-функцию и не будет, с чего ему туда смотреть вообще...

**Comment by AIexandrKotov** [comment]
А разрешить, я так понимаю, просто: для обычных (не авто) свойств имена акцессоров начинать со спец. символа.

**Comment by SunSerega** [comment]
Нет, тогда свойства в библиотеке сломаются, потому что в C# и всех остальных .Net языках - спец символа там нет.

Но разрешить ещё проще - просто не давать ошибку. Я уже 2 раза сказал, то что там будет 2 одинаковых имени в 1 пространстве имён - совсем ничего не сломает.

**Comment by SunSerega** [comment]
Кстати, так работает:
```
type
  t1 = class
    
    property GET_A: integer read 0;
    property A: integer read 0;
    
  end;

begin end.
```
И как видите, всё работает, даже виртуальность:
```
type
  t1 = class
    
    property GET_A: integer read 1; virtual;
    property A: integer read 2; virtual;
    
  end;
  t2 = class(t1)
    
    property GET_A: integer read 3; override;
    property A: integer read 4; override;
    
  end;

begin
  
  var a := new t1;
  a.GET_A.Println;
  a.A.Println;
  
  a := new t2;
  a.GET_A.Println;
  a.A.Println;
  
end.
```
Поэтому, если не выдавать ошибку - всё уже нормально работает.
