### ISSUE TITLE
Падение компилятора в yield Seq(x->x);

### ISSUE THREAD

**Issue by miks1965** [pascalabcnet/pascalabcnet#204]
```
function f: sequence of integer;
  begin
    for var i:=1 to 5 do
      yield Seq(x->x);
  end;
  
begin
  
end.  
```

**Comment by frninja** [comment]
Не падает, но что есть Seq(x->x) не понятно. Без yield та же ошибка

**Comment by frninja** [comment]
Если имеется в виду yield сразу коллекции, так такое в С# насколько понимаю не предусмотрено - надо писать foreach по коллекции и внутри yield

**Comment by miks1965** [comment]
Не падает - и хорошо. Просто, падений быть не должно
