### ISSUE TITLE
End не работает как имя метода

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#2041]
```
type
  t1 = static class
    
    static procedure &End := exit;
    
  end;
  
begin
  t1.End; //Ошибка: Встречено 'End', а ожидался оператор
end.
```
Со всеми остальными ключевыми словами - это работает.
В OpenGL есть функция `gl.End`, поэтому это довольно неприятно...

**Comment by AlexRnD61** [comment]
Не со всеми. Например, с loop не работает.

**Comment by SunSerega** [comment]
Понятно... Ну, надо всё равно по всем ключевым словам пройтись. Есть куча тех что ключевыми словами считаются, но не подсвечиваются и в Ctrl+Space не показывает.

Я смогу где то начиная с суботы, сейчас я практически без компа...
