### ISSUE TITLE
Перегрузка Task.Run выбирается нестабильно (плавающая гадость с Task.Run)

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#2048]
Недавно были issue про то что для `Task.Run` выбирает не ту перегрузку... Однако так просто тут не отделаться))

Несколько недель назад я заметил что все программы, использующие `OpenCLABC` - иногда просто так пишут что задача была отменена и вылетают. Это бред, потому что у меня в `OpenCLABC` нету функционала для отмены операций. При чём - эта ошибка пропадает так же неожиданно как появляется.

[0.zip](https://github.com/pascalabcnet/pascalabcnet/files/3412727/0.zip)

Тут исходники 1 из примеров `OpenCLABC` + немного устаревшая версия `OpenCLABC` (в которой 100% что воспроизводится) + 2 .exe файла, с ошибкой и без (у них приписки в названиях, `err` и `ok` соответственно).

Что не так в .exe, дающим ошибку - сейчас объясню. Но для начала, кроме самого существования этих 2 .exe - я так же могу подтвердить этим видео:
[Воспроизведение плавающей Task.Run](https://youtu.be/YEAjroNNeOc)

На всяк, вот весь текст ошибки:
```
System.AggregateException: Произошла одна или несколько ошибок. ---> System.Threading.Tasks.TaskCanceledException: Отменена задача.
   --- Конец трассировки внутреннего стека исключений ---
   в System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   в System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   в System.Threading.Tasks.Task.Wait()
   в OpenCLABC.Context.SyncInvoke[T](CommandQueue`1 q) в C:\Users\Master in EngLiSH\Desktop\0\OpenCLABC.pas:строка 516
   в OpenCLABC.Kernel.Exec(UIntPtr[] work_szs, CommandQueue`1[] args) в C:\Users\Master in EngLiSH\Desktop\0\OpenCLABC.pas:строка 1483
   в OpenCLABC.Kernel.Exec(Int32[] work_szs, CommandQueue`1[] args)
   в OpenCLABC.Kernel.Exec(Int32 work_sz1, CommandQueue`1[] args) в C:\Users\Master in EngLiSH\Desktop\0\OpenCLABC.pas:строка 421
   в SimpleAddition.Program.$Main() в C:\Users\Master in EngLiSH\Desktop\0\SimpleAddition.pas:строка 22
---> (Внутреннее исключение #0) System.Threading.Tasks.TaskCanceledException: Отменена задача.<---
```

Как видите, ни от удаления .pcu, ни от перезагрузки IDE не воспроизводится. Но потом воспроизводится в случайный момент. По крайней мере я не вижу зависимости воспроизведения от моих действий, ни 1 из моих шаблонов по поиску багов тут не помогает. Поэтому и минимальный код найти я не могу...

Кстати, обычно воспроизводится в ~50% случаев, это повезло тут так, что только 2 компиляции дали сломанный .exe .

---

Генерируемые .exe:
-

Первое что сразу бросается в глаза - .exe с ошибкой весит на много меньше (80KB vs 238KB). Но это какой то побочный эффект. В .exe с ошибкой не добавляются неиспользуемые типы из `implementation` части `OpenCLABC`, то есть в .exe с ошибкой на самом деле всё правильнее.

Но хоть это и побочный эффект, пока что у меня все .exe с ошибкой были меньше всех .exe без ошибки, поэтому это, наверное, хорошая зацепка...

Но что в сломанном .exe не правильно - так это вот эта строчка (509 в исходнике `OpenCLABC`):
```
      Result := Task&<T>.Run(костыль_для_Result); // костыль_для_Result имеет тип "()->T"
```
Которая разворачивается в правильном .exe в:
```
      return Task.Run<T>(new Func<T>(костыль_для_Result));
```
А в .exe с ошибкой:
```
      return Task.Run<T>((Func<Task<M0>>) new Func<T>(костыль_для_Result));
```
Это преобразование к `Func<Task<M0>>` - придумал декомпилятор. На самом деле там нет преобразования, оно бы как раз хотя бы дало понятную ошибку.

В место этого в тихую вызывается перегрузка принимающая `Func<Task<M0>>`, но передаётся в неё единственным параметром - `new Func<T>(костыль_для_Result)`. Ну и... **Я так понимаю**, где то в кишках, при вызове метода `Task<M0>` для объекта типа `T` (а точнее в данном случае в `T` подставляется `OpenCLABC.Kernel`) - свойство `Task.IsCanceled` выводит какой то мусор, который считает за `true`, отсюда ошибка.

**Comment by SunSerega** [comment]
Однако, в этот раз я не пытался попасть на юбилейную issue... Но эта очень даже достойна того)))

**Comment by miks1965** [comment]
OpenCLABC вообще странно компилируется. Всякий раз создаётся pcu нового размера. Это значит, что при создании pcu возникает ошибка.

**Comment by miks1965** [comment]
А скажите, есть ли разница между первой компиляцией и последующими? Если удалять pcu и перезапускать среду, то результат всегда будет один?

А то у нас там информация по используемым NET-типам кешируется - вроде ни на что не должно влиять, но на всякий случай спрашиваю

**Comment by SunSerega** [comment]
> А скажите, есть ли разница между первой компиляцией и последующими?

Я не сильно тестировал, потому что я вообще не вижу ни 1 закономерности... Но на видео которое я скинул в первом посте видно:

- Ошибка ни разу не воспроизвелась сразу после удаления `.pcu` (это ещё не значит что `.pcu` уже должны быть, но исключает `$savepcu false` как способ ловли)
- Ошибка воспроизвелась 1 раз на второй компиляции из IDE. После этого я перезагрузил IDE - и уже воспроизвелось на первой же компиляции. То есть, перезагрузка IDE (и компиляция из папки) так же не могут являться способом ловли.

Ну и я не вижу никакой другой закономерности. Поэтому и сказал, ни 1 из известных мне способов ловли ошибок - не работает.

> Еще один вопрос - если задаться трудом и слить все модули в одну большую программу, ошибка останется плавающей?

Хорошо, я попробую чуть позже...

**Comment by miks1965** [comment]
Моделирую вашу ошибку. Вот в такой программе:
```
uses System.Threading.Tasks;

procedure p<T>(q: List<T>);
begin
  var f: ()->integer := ()->1;
  Task&<T>.Run(f);
end;

begin 
  var l := new List<integer>();
  p(l);
end.
```
её нет. Никогда. Код для p получается такой:
```
public static void p<T>(List<T> q)
{
	Func<int> function = new Func<int>(Program.<>lambda1<T>);
	Task.Run(function);
}
```
Всегда. Всё детерминированно.

Ищите пожалуйста минимальную неработающую программу. Иначе непонятно как отлаживать

**Comment by SunSerega** [comment]
Кажется - я смог найти способ стабилизировать ошибку. Правда пока что алгоритм воспроизведения какой то через 5 точку. Сейчас попробую найти проще и минимальный код...

**Comment by SunSerega** [comment]
[0.zip](https://github.com/pascalabcnet/pascalabcnet/files/3464457/0.zip)
[Воспроизведение плавающей Task Run v2.0](https://youtu.be/lukxpgbeLOw)

`0.pas`:
```
uses u;

begin
  p1;
end.
```
`u.pas`:
```
unit u;

procedure p1;
begin
  
  var f: ()->byte := ()->0;
  var t := System.Threading.Tasks.Task&<byte>.Run(f);
  t.Wait;
  
end;

end.
```

**Comment by SunSerega** [comment]
Однако, если запускать сам `0.pas` - ошибки нет никогда. То есть и плавающее свойство полностью пропало (что немного пугает, возможно там есть ещё что то...)

Я понимаю если бы компилирование `0.pas` - отключало пересоздание `.pcu` . Но нет, `.pcu` как раз пересоздаётся всегда. Но почему то если запускать `u.pas` - `.pcu` создаётся сломанный.

В первую очередь надо разобраться - почему срабатывают разные алгоритмы компиляции, в зависимости от того - какой файл открыт. Иначе вполне вероятно что этой 1 ошибкой не отделаться.

**Comment by miks1965** [comment]
Разные алгоритмы - это более менее понятно почему может происходить. У нас там словарь методов-кандидатов, и потом из этого словаря отбирается одна. В словаре данные идут в недетерминированном порядке. Еще у нас могут отождествляться функции с параметром Func<T> и Func<Task<T>>. И - вот причина. В любом случае это место надо найти. Сломанный pcu - это следствие. На правильных данных он не ломается.

**Comment by miks1965** [comment]
> Однако, если запускать сам `0.pas` - ошибки нет никогда. То есть и плавающее свойство полностью пропало (что немного пугает, возможно там есть ещё что то...)

Так я не понял, для ошибки что запускать надо?

**Comment by SunSerega** [comment]
> Так я не понял, для ошибки что запускать надо?

На видео видно (которое я уже слал выше):
https://youtu.be/lukxpgbeLOw
Там показан список действий, которые нужны для воспроизведения.

Если нажать ПКМ по файлу программы и "Сделать активным" - можно нажимать кнопку запуска и когда открыт файл модуля, а не программы, всё равно запустится программа. Вот если запускать модуль - воспроизводится. А если запускать программу - НЕ воспроизводится.

**Comment by miks1965** [comment]
Ага, спасибо, увидел.

Видео помогают не всегда. Но в данном случае помогло.

**Comment by miks1965** [comment]
Смешно сказать, но в Debug-версии всё работает. Именно когда надо отлаживать...

**Comment by miks1965** [comment]
Нужно, чтобы вы откомпилировали Debug-версию с Github и добились ошибки в Debug-версии

**Comment by SunSerega** [comment]
Дайте готовый установщик Debug версии. А то у меня сейчас норм компьютер в нерабочем состоянии, а на ноутбуке сборка компилятора это пару часов насилования CPU.

**Comment by miks1965** [comment]
Нет Вы не поняли. Скачайте с GitHub. И откомпилируйте проект в Студии. Это минуты две на самом медленном ноуте.

**Comment by SunSerega** [comment]
Нет, я именно про это. Не знаю какие у вас там ноутбуки, но моему, если поотключать в .bat все тесты и остальное не самое нужное - надо пол часа минимум.

Тут ещё оказалось что то что у меня в пути к студии есть русские буквы - это огромная проблема. Вроде я кое как перевёл кодировку в .bat файле (ноутпедом++) чтоб русские буквы принимало. Но всё равно пишет "не удалось найти указанный путь"... Короче ещё в другую точку теперь ещё переустанавливать...

Вообще, для начала попробуйте в этом коде:
https://github.com/pascalabcnet/pascalabcnet/files/3412727/0.zip
Сделать активной программу, а запустить находясь во вкладке OpenCLABC, в дебаг версии компилятора. Если это не сработает - то и минимальный код мне не из чего в дебаг-версии находить, и нечего мучаться со сборкой...

**Comment by miks1965** [comment]
Не надо собирать инсталлят!
Надо откомпилировать сборку без тестов и стандартных модулей.
Из Студии.

**Comment by miks1965** [comment]
Согласен. Проверил. В Debug-версии всё работает. Идей - нет.

**Comment by SunSerega** [comment]
А, прямо из студи... Ну, она уже ставиться на новом расположении (без русских букв) в любом случае... И с инсталятом всё же быстрее, чтоб найти минимальный код - надо пробовать запускать пару сотен раз. А из студии всё же запуск хоть и быстрее инсталята, но медленнее и требует больше оперативки чем если полностью компилятор поставить...

**Comment by SunSerega** [comment]
Кроме всего прочего, как вы себе представляете воспроизведение прямо из студии? Ведь для воспроизведения нужна IDE паскаля.

**Comment by miks1965** [comment]
Ну да. Я откомпилировал проект VisualPascalABC и по Ctrl-F5 запустил. Всё работает. Ошибки нет.

**Comment by SunSerega** [comment]
А, собственно, вы случаем не ожидали ошибки компилятора? Ошибка то в готовом .exe ... В общем вот наконец руки дошли VS запустить - и у меня воспроизвелось. Сейчас видео сделаю...

**Comment by SunSerega** [comment]
https://youtu.be/PybMa2q83g0

Там так же в конце показана ошибка компилятора касающаяся несовместимости .pcu . Делать для неё отдельную issue?

**Comment by ibond84** [comment]
https://github.com/pascalabcnet/pascalabcnet/actions/runs/782537241
