### ISSUE TITLE
pabcnetc и pabcnetcclear создают не совместимые .pcu

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#2049]
[0.zip](https://github.com/pascalabcnet/pascalabcnet/files/3424772/0.zip)

Все файлы кроме `test.pas` (который вызывает консольные компиляторы) - пустые, так что сюда выставлять их содержимое - бесполезно. А вот что надо о них знать:

В папке `1` есть модули `u1` и `u2`, в `u2` есть `uses u1`.
Их компилирует с помощью `pabcnetc.exe` и копирует в папку `2`

В папке `2` находится программа `0`, содержащая `uses u2`.
Если компилировать её с помощью `pabcnetcclear.exe` -  получаем ошибку чтения `.pcu` файла.

Если компилировать модули с помощью `pabcnetcclear.exe`, или программу с помощью `pabcnetc.exe` (или и то и то) - не воспроизводится.

**Comment by miks1965** [comment]
Непонятное объяснение. Я везде в программе test.exe поставил pabcnetcclear.exe. Запустил - ошибки нет. В чем проблема?

**Comment by SunSerega** [comment]
> Я везде в программе test.exe поставил pabcnetcclear.exe. Запустил - ошибки нет. В чем проблема?

> Если компилировать модули с помощью pabcnetcclear.exe, или программу с помощью pabcnetc.exe (или и то и то) - не воспроизводится.

Запустите `test.pas` не меняя ничего. Тогда воспроизведётся.

**Comment by miks1965** [comment]
![изображение](https://user-images.githubusercontent.com/10325391/61858763-6a83da00-aecf-11e9-9a15-614310191ad2.png)
Вот результат моего запуска. Еще раз повторю - pabcnetc.exe не предназначен для запуска не из консоли и без диалогового режима. 

Возможно, pcu, создаваемые pabcnetc.exe и pabcnetcclear.exe несовместимы, тогда это проблема, но тест должен быть ручным и другим

**Comment by SunSerega** [comment]
> Еще раз повторю - pabcnetc.exe не предназначен для запуска не из консоли и без диалогового режима.

Ну, я уже понял что он не предназначен... Но если компилировать модули из папки (ПКМ по .pas файлу>>компилировать) - та же ошибка, дело именно в несовместимых .pcu . Ну и если компилировать из IDE - тоже.

Если хотите ручной тест - уберите из `test.pas` всё кроме запуска `pabcnetcclear.exe`. И всё что убрали (компиляция .pcu и их перенос в другую папку) - делайте вручную.

**Comment by miks1965** [comment]
Если можно, сделайте алгоритм типа: откомпилировал один модуль одним компилятором, другой - другим и при сборке exe вылетает ошибка

**Comment by SunSerega** [comment]
1. Откомпилировать чем угодно **кроме** `pabcnetcclear.exe` модуль `1\u2.pas` (к нему подключен `u1.pas`, поэтому он сам откомпилируется).
2. Перенести `.pcu` файлы (их должно быть 2) из папки `1` в папку `2`.
3. Откомпилировать с помощью `pabcnetcclear.exe` программу `2\0.pas`.

**Comment by miks1965** [comment]
Ага, спасибо, понятно

**Comment by miks1965** [comment]
```
unit u1;
end.
```
и 
```
unit u2;
uses u1;
end.
```
При компиляции pabcnetcclear.exe u2.pas размер u1.pcu - 260 байт, а при компиляции pabcnetc.exe u2.pas размер u1.pcu - 251 байт. 

Отсюда и несовместимость.

**Comment by miks1965** [comment]
Вроде сделал. Проверяйте

**Comment by SunSerega** [comment]
Да, по крайней мере автоматический тест из заголовка этой issue - теперь работает.

**Comment by miks1965** [comment]
Там дело было в том, что один консольный компилятор запаивал в pcu выходной каталог, а второй - нет. Теперь - одинаково нет
