### ISSUE TITLE
В последней версии сломался условный оператор

### ISSUE THREAD

**Issue by AIexandrKotov** [pascalabcnet/pascalabcnet#2051]
```
begin
  if true then ;
end.
```
Program8.pas(3) : Встречено 'end', а ожидалось else

```
begin
  
end.
```
Отваливается из-за __RunMode.pas(29) : Встречено 'if', а ожидалось else

Я так понимаю, что из-за https://github.com/pascalabcnet/pascalabcnet/commit/5eec60e885e9797fa94c99ea1d27ae267eedfc3b

Пока не пофиксите, не смогу подтвердить/опровергнуть ту внутреннюю ошибку на новой версии.

**Comment by miks1965** [comment]
Ничего себе! Сейчас исправлю

**Comment by miks1965** [comment]
Пофиксил. 

Очень слабый парсер грамматик не видит ошибку. Внёс её в тесты
