### ISSUE TITLE
Выбор перегрузки .Max всё ещё сломан

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#2055]
Вроде уже много времени прошло с того как `.Max` чинили... Но оказывается недофиксили, причём - в таком простом случае:
```
type
  t1 = class
    o: integer;
  end;
  
begin
  var sq: sequence of t1;
  var i: integer := sq.Max(a->a.o); //Ошибка : Нельзя преобразовать тип real к integer
end.
```
И не обязательно чтоб поле имело тип `integer`. Главное чтоб оно использовалось, и возвращался в итоге `integer`:
```
type
  t1 = class
    s: string;
  end;
  
begin
  var sq: sequence of t1;
  var i: integer := sq.Max(a->a.s.Length); //Ошибка : Нельзя преобразовать тип real к integer
end.
```
Не понятно только, как я раньше этот баг не нашёл, я ведь `.Max` повсюду использую...
Может, эта проблема появилась относительно недавно, в качестве побочного эффекта какого то другого фикса?

**Comment by miks1965** [comment]
Ну, там другая ошибка. Алгоритм выбора перегруженной функции пока еще слабый.
