### ISSUE TITLE
Неопределённость в выборе методов из системного модуля при компиляции программы, которая ссылается на пользовательскую библиотеку, в которой использован тот же метод

### ISSUE THREAD

**Issue by AIexandrKotov** [pascalabcnet/pascalabcnet#2056]
lib.pas:
```
library lib;

type
  
  T = class
    public static function f(s: string) := s.ToWords;
  end;

end.
```

pg.pas:
```
{$reference 'lib.dll'}

begin
  var s := '22'.ToWords; //pg.pas(4) : Несколько подпрограмм могут быть вызваны
end.
```

[Архив ZIP - WinRAR.zip](https://github.com/pascalabcnet/pascalabcnet/files/3439168/ZIP.-.WinRAR.zip)

Похоже, что в контексте два PABCSystem.

**Comment by miks1965** [comment]
Да, проблема понятна. Действительно, в каждой dll есть свой кусочек PABCSystem. Это нормально - это кусок специфики Паскаля, реализующий ввод-вывод, работу со встроенными множествами и файлами. В библиотеке используются для неё свой PABCSystem, в программе - свой. Проблема в том, что методы расширения, определенные в библиотеке, выносятся на самый верхний уровень и видны в основной программе. Но в ней же видны все методы расширения из её PABCSystem. Коллизия.

Получается, что все используемые методы расширения из PABCSystem в библиотеках будут приводить к таким же последстваиям. Это - архитектурный промах.

Будем думать, как это погасить.

**Comment by miks1965** [comment]
Теперь любые функции и классы, пришедшие в библиотеку из PABCSyastem и PABCExtensions, полностью изолированы и недоступны в других сборках. 

Спасибо за хорошую ошибку )
