### ISSUE TITLE
"Generic-функция не может быть вызвана", если на результате .OrderBy использовать пользовательскую функцию

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#2058]
```
// обязательно имя как у любого .Net-овского extensionmethod-а
function Skip<T>(self: sequence of T; f: T->T): sequence of T; extensionmethod := nil;

begin
  var l: sequence of byte;
  l.OrderBy(t->t).Skip(o->o) //Ошибка: Generic-функция Skip не может быть вызвана с данным набором фактических параметров
end.
```

**Comment by miks1965** [comment]
Ну то есть это неправильное сообщение об ошибке - верно?

**Comment by SunSerega** [comment]
Ошибки вообще не должно быть. Если убрать `.OrderBy` - её нету.
И если добавить `AsEnumerable` между `.OrderBy` и `.Skip` - ошибки тоже нету.

**Comment by miks1965** [comment]
Но получается, что мы переопределяем стандартный метод расширения. А это нельзя. Или он не ровно такой?

**Comment by SunSerega** [comment]
> А это нельзя. Или он не ровно такой?

Я выбрал `Skip` в виде примеру, потому что он хорошо известен и у него явно по смыслу не может быть параметра - лямбды.
То есть да, параметры другие, а значит переопределять так можно.

**Comment by miks1965** [comment]
```
function Skip(self: sequence of integer; f: integer->integer): sequence of integer; extensionmethod := nil;

begin
  var l: sequence of byte;
  l.OrderBy(t->t).Skip(o->o)
end.
```
Так оже не работает

**Comment by miks1965** [comment]
Логика (неправильная) у нас щас такая:

Вначале Skip ищется в IOrderedEnumerable<T>. И находится стандартный, но не подходящий по параметрам (types.cs 3382):
```
List<SymbolInfo> sil = compiled_find(name);
``` 

Так вот, только если на этом шаге ничего не найдено, начинает искаться в предках IOrderedEnumerable<T> - в частности, в IEnumerable<T> (types.cs 3389)

**Comment by miks1965** [comment]
Связанная ошибка - #2256

Они семафорят - исправление одной приводит к появлению другой
