### ISSUE TITLE
Добавить partial классы

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#2060]
Чтоб неймспейсы работали порядко-независимо.

https://github.com/pascalabcnet/pascalabcnet/issues/2057#issuecomment-516323288

**Comment by AIexandrKotov** [comment]
Оказывается, partial-классы в PascalABC.NET уже есть...

```
type
  T = partial class
    public a: integer = 1;
  end;
  
  T = partial class
    public b: integer = 2;
  end;

begin
  var a := new T();
  write(a.a + a.b);
end.
```

**Comment by SunSerega** [comment]
@miks1965, кстати, а как собственно они могут помочь с порядконезависимость в неймспейсах?

**Comment by miks1965** [comment]
А, ну вот - в справке еще нет :) Сделаем. 

С порядконезависимостью - никак. Вы же сами пишете, что этого и в C# нет.

**Comment by SunSerega** [comment]
> Вы же сами пишете, что этого и в C# нет.

Чего именно? Порядконезависимость описания типов там есть.

**Comment by miks1965** [comment]
А, да. В Object Pascal никогда не было.

**Comment by AIexandrKotov** [comment]
Ну так а зачем тогда запрещать директивы? Внутрь pabcproj-файла лазить сложнее, чем менять порядок директив просто в программе. Нечего убирать рабочие вещи, только из-за слова "include" в названии. От include-подобности (она же и порядкозависимость) НЕ УБЕЖАТЬ!

**Comment by miks1965** [comment]
include - это устаревшая парадигма, провоцирующая ошибки.

**Comment by AIexandrKotov** [comment]
Внутри проектов всё равно будет тот же include

изменение названия сути не поменяет

**Comment by miks1965** [comment]
В Object Pascal (Delphi) порядконезависимости никогда не было. Потому что тут другая парадигма: порядок компиляции модулей чётко определён. 

Как только вы пытаетесь внедрить в эту модель ДРУГУЮ модель компиляции в стиле C#, где свалка из файлов в одном проекте, и нет порядка, в котором они компилируются, вы неизбежно получаете проблемы.

Попытка сделать это include-файлами ничего по сути не меняет, только переносит эти проблемы на другой уровень. И - они неустранимы.

По-моему, надо смириться как-то с тем, что в паскале модуль - это единица компиляции, и другого быть не может. И в проектах есть всё равно основная программа и подключённые к ней модули. Как только вы делаете всё плоским (без модулей), вы получаете ворох проблем. Паскаль под это не заточен. С этим как-то надо смириться.

**Comment by AIexandrKotov** [comment]
Я и не выступал за порядкоНЕзависимость, ибо мне и так ясно, что в паскале такое невозможно. Я выступал ПРОТИВ ЗАПРЕТА директив. Можете изменить название директивы, убрать include из названия, чтобы это хотя бы сходу не ассоцциоровалось с древними парадигмами. А так, если привязывать к проектам (то есть IDE), вам придётся ещё и окошко создать, в котором можно будет настроить этот порядок подключения файлов. Не, если сделаете и будет удобно — вопросов нет, пусть будут. Но я считаю, что **директивы убирать не нужно**.

Впрочем, это всё не сильно важно. Сделайте, пожалуйста, **определения методов после класса**. Это уже исправит проблему, о которой я писал в предыдущей issue. Сделать это не сложно! Я бы и сам сумел, если бы знал где у вас в компиляторе определения методов и как их сделать в syntax_tree_visitor'e. Пока что, если заставить компилятор игнорировать ошибку, описание метода класса просто не видит.

**Comment by miks1965** [comment]
Так есть же определения методов после класса. В Object Pascal только так и можно было.

**Comment by SunSerega** [comment]
Вот а проблема в том, что в неймспейсах реализация методов после класса - нету. И отсюда куча проблем. Нужна или порядконезависимость или реализация методов вне класса. Иначе многие конструкции становятся невозможны и программирование превращается в минное поле.

**Comment by AIexandrKotov** [comment]
Я имею ввиду, что определение методов после класса надо разрешить в пространствах имён!

**Comment by miks1965** [comment]
Как это нету?

Я вот продолжаю говорить, что это конструкции крайне неготовые и сырые, которыми в каком-то продакшне пользоваться еще нельзя.

Я прошу также - когда пишете Issue - писать ровно о проблеме, а не о том, как её по-вашему решить. А то я реагирую на странный способ решения, а суть - что какой-то базовой возможности в недокументированных пространствах имен нет - остаётся за кадром

**Comment by SunSerega** [comment]
> Как это нету?

@ibond84 запретил. Или скорее отказался реализовывать со словами "так и задумано".

**Comment by miks1965** [comment]
Этого я не знаю. Это странное ограничение. Видимо, оно какое-то техническое. Но это конечно надо реализовывать. Переоткрывайте. Это ведь не C#, где классы можно писать в любом порядке.

**Comment by SunSerega** [comment]
Мы не можем переоткрывать issue, которую закрыл разработчик. Кнопки нету.

**Comment by AIexandrKotov** [comment]
Переоткройте #2057, там достаточно подробно описана суть проблемы

**Comment by miks1965** [comment]
Предлагаю открыть новую Issue. Эту старую я понимал 3 дня. Там длинная часть, и из неё лишь понятно, что вам нужна порядковонезависимость.
