### ISSUE TITLE
Запретить генерацию стандартного конструктора в partial-классах

### ISSUE THREAD

**Issue by AIexandrKotov** [pascalabcnet/pascalabcnet#2061]
Либо генерировать его после всех частей класса (предложение от @SunSerega)

На C# так можно:
```
    public partial class Class1
    {

    }

    public partial class Class1
    {
        public Class1()
        {

        }
    }
```

На PascalABC.NET этот же код вызовет ошибку:
```
type 
  T = partial class 
  
  end; 
  
  T = partial class 
    public constructor := exit; //Program19.pas(7) : Повторное объявление 
  end;
```

**Comment by miks1965** [comment]
Совсем запретить нельзя. Это у нас зашито в архитектуре. Нужно исправить заголовок - генерировать один раз

**Comment by miks1965** [comment]
Кстати, а что вас смущает? Тут всё верно. Первый раз такой конструктор генерируется. В паскале - детерминированный порядок компиляции, поэтому противоречий нет. Захотел написать - напиши первый раз

**Comment by SunSerega** [comment]
В неймспейсах это будет плохо работать. Непонятно какую из частей (если они в разных неймспейсах) будет считать первой...

**Comment by miks1965** [comment]
Понятно. Да, если как в C# все файлы сваливать в одну кучу, то не будет работать. И не пространства имен виноваты, а то, что вы пытаетесь натянуть модель компиляции C# на PascalABC.NET. Меня сбило, что вы прикрываетесь неимспейсами. Они тут ни при чем.
