### ISSUE TITLE
Не может вывести тип по лямбде, если передавать её в метод t1<T>, где T -  тип шаблона подпрограммы

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#2067]
```
type
  t1<T> = class
    
    procedure p1<T2>(f: T->T2) := exit;
    
  end;

procedure p1<T>;
begin
  var o: t1<byte>;
  o.p1(b->''); // ok
end;

procedure p2<TSource>;
begin
  var o: t1<TSource>;
  o.p1(b->''); //Ошибка: Невозможно вывести типы-параметры generic-подпрограммы f1 (укажите типы-параметры явно)
end;

begin end.
```
Отличия в `p1` и `p2` только в том - что в `p2` вместо `t1<byte>` стоит `t1<T>`, то есть используется шаблонный параметр процедуры.

Эта issue из серии:
#2067, #2068, #2069

**Comment by miks1965** [comment]
Это слабый вывод.

**Comment by SunSerega** [comment]
А как вообще тип шаблонного параметра `t1` влияет на способности вывода типа? Мне кажется это всё же баг...

**Comment by miks1965** [comment]
Нет, не баг. В обобщенных функциях в этом случае не выводит. Но - надо делать

**Comment by SunSerega** [comment]
Только что собрал новый билд - всё ещё воспроизводится.
И в тесты вы не тот код добавили.

**Comment by ibond84** [comment]
https://github.com/pascalabcnet/pascalabcnet/actions/runs/486217931
