### ISSUE TITLE
Компилятор путает 2 типа-шаблона между собой, если передавать лямбду в метод t1<T>, где T - тип шаблона подпрограммы

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#2068]
```
type
  t1<T> = class
    
    procedure p1<T2>(f: T->T2) := exit;
    
  end;

procedure p1<TSource>;
begin
  var o := new t1<TSource>;
  o.p1&<string>(b->
  begin
    Result := '';
    var a: TSource := b; //Ошибка: Нельзя преобразовать тип string к TSource
  end);
end;

begin end.
```
У `b` тип `TSource` а не `string`.

Эта issue из серии:
#2067, #2068, #2069

**Comment by miks1965** [comment]
```
// #2068
type
  t1<T> = class
    procedure p1<T2>(f: Action<T>); begin end;
  end;

procedure p1<TSource>;
begin
  var o := new t1<TSource>;
  o.p1&<string>(b->
  begin
    var a: TSource := b; //Ошибка: Нельзя преобразовать тип string к TSource
  end);
end;

begin 
end.
```

**Comment by miks1965** [comment]
Как это ни удивительно, но исправил достаточно быстро. Думал, уйдёт больше времени.

У нас не были реализованы generis-методы внутри generic-классов. Вообще. 

Нужно, чтобы кто-то потестировал различные комбинации. С типами возвращаемых значений тоже.

**Comment by SunSerega** [comment]
Ну, я попробовал потыкаться... Нашёл проблемы с `where`, но как сделал минимальный код - оказалось что с этой issue вообще не связано.

Ну, бесцельно перебирая пересечения фич сложно найти что то стоящее. Лучше всего сразу на чём то типа `OpenCLABC` тестировать. Там полно жести с шаблонами. Оттуда же и вся эта серия issue. Но пока #2218 - я на `OpenCLABC` не смогу протестировать.
