### ISSUE TITLE
params разворачивается в немного говнокода

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#2080]
```
procedure p1<T>(params a: array of T) := exit;

begin
  p1(1,2,3);
end.
```
Разворачивается в:
```
procedure p1<T>(params a: array of T) := exit;

var $intarr1: array of integer;

begin
  
  var num := 0;
  if $intarr1 <> nil then
    num := $intarr1.Length;
  
  System.Array.Resize($intarr1, 3);
  
  $intarr1[0] := 1;
  $intarr1[1] := 2;
  $intarr1[2] := 3;
  
  p1($intarr1);
  
end.
```
1. `$intarr1` должен быть локальной переменной.
2. Зачем там `num`? Чтоб кода мало не было?))
3. Не `System.Array.Resize` а 1 IL оператор `newarr`. Ну то есть `new integer[3]`, если по-паскалевски.

**Comment by AIexandrKotov** [comment]
```
begin
  write(1, '2', 3, 4, '5');
end.
```
Тоже не особо хорошо развернётся. Но важно не это, а вот это:
```
    public static object[] $intarr1;
    public static object[] $intarr2;
    public static object[] $intarr3;
```
Зачем ещё два массива на каждый params?

Если продублировать:
```
begin
  write(1, '2', 3, 4, '5');
  write(1, '2', 3, 4, '5');
end.
```

То массивов уже 6!
```
    public static object[] $intarr1;
    public static object[] $intarr2;
    public static object[] $intarr3;
    public static object[] $intarr4;
    public static object[] $intarr5;
    public static object[] $intarr6;
```

А если взять программу какого-нибудь школьника, который часто использует write?

![image](https://user-images.githubusercontent.com/44296606/63128174-b35e1880-bfcd-11e9-87aa-d8d6f321c8b8.png)

на это страшно смотреть... ))

**Comment by SunSerega** [comment]
Мне кажется что дублирование переменной это отдельная проблема.
И я не могу воспроизвести её ни с чем кроме `Write`...

**Comment by ibond84** [comment]
Этот говнкод еще не потокобезопасный. Семантика не должна генерировать этот хлам. Это задача генератора кода, в котором тупо генерируются команды, а не создаются костыли из семантических деревьев в виде глобальных переменных (наверно из-за инициализируемых полей)

**Comment by miks1965** [comment]
Желательно немного оптимизировать - там изза одной команды IL-spy отображает это ужасно

**Comment by miks1965** [comment]
Открою новый Issue
