### ISSUE TITLE
sizeof неверно показывает размер типа-enum'а

### ISSUE THREAD

**Issue by AIexandrKotov** [pascalabcnet/pascalabcnet#2081]
Библиотека:
```
namespace ClassLibrary1
{
    public enum Enum1: byte   //<- важно наличие типа констант enum'ов
    {
        A = 0, B = 127, C = 255
    }
    public static class Class1
    {
        public static int GetSize = sizeof(Enum1);
    }
}
```
Program.pas:
```
{$reference 'ClassLibrary1.dll'}
uses ClassLibrary1;

begin
  writeln(Class1.GetSize);
  writeln(sizeof(Enum1));
end.
```

Вывод:
```
1
4
```

**Comment by AIexandrKotov** [comment]
Кстати, вы не думали сделать перечисления такими же как в C#? Ну, с возможностью выбора целочисленного типа констант.
Вроде такого:
```
type
  Enum: byte = (A = 1, B = 2);
```

**Comment by miks1965** [comment]
Нет, не думали. Не может быть всё как в C# ))

**Comment by AIexandrKotov** [comment]
А issue-то зачем закрывать? Это 1. **баг** 2. Это весьма легко реализуется.
sizeof(enum) равен размеру типа `enum.GetType.GetFields(BindingFlags.Public|BindingFlags.NonPublic|BindingFlags.Instance|BindingFlags.Static)[1].GetRawConstantValue`
А тип оно может иметь только целочисленный (то есть знаковые и беззнаковые 1,2,4,8-байтовые числа).

на PascalABC.NET:
```
{$reference 'ClassLibrary1.dll'}
uses ClassLibrary1;
uses System.Reflection;
  
begin
  writeln(Class1.GetSize);
  Runtimesizeof(typeof(Enum1).GetFields(BindingFlags.Public or BindingFlags.NonPublic or BindingFlags.Instance or BindingFlags.Static)[1].GetRawConstantValue.GetType).PrintLn;
end.
```
Вывод:
```
1
1
```
Каждый раз писать это слишком громоздко.

**Comment by SunSerega** [comment]
Не надо получать поля, достаточно:
```
System.Runtime.InteropServices.Marshal.SizeOf(typeof(Enum1).GetEnumUnderlyingType).Println;
```
Но да, `sizeof` для энумов должен работать.

**Comment by miks1965** [comment]
Сделал
