### ISSUE TITLE
uses-in создаёт .pcu не в той папке, если компилировать из IDE

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#2083]
[0.zip](https://github.com/pascalabcnet/pascalabcnet/files/3514986/0.zip)

Если скомпилировать программу (в папке "2") из IDE - .pcu создаст в папке с программой.
Если скомпилировать программу из папки (pabcnetcclear) - .pcu создаст в папке с модулем.

Правильно создавать в папке с модулем, иначе появляется куча проблем, даже если исправить тот факт что созданный .pcu просто не видит, потому что ищет его в другой папке.

**Comment by miks1965** [comment]
@SunSerega, Это исправится с вашим пулл реквестом?

**Comment by SunSerega** [comment]
Да, и поидее закроется автоматически, во время мержа моего пула.
