### ISSUE TITLE
Вложенный uses-in не работает

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#2084]
[0.zip](https://github.com/pascalabcnet/pascalabcnet/files/3523246/0.zip)

https://youtu.be/YsidWujgDBk

При компиляции `0.pas` модуль `u2.pas` пытается искать в папке `2\u2.pas` вместо `1\2\u2.pas`.

Путь надо брать относительно файла - содержащего `uses-in`, а не того, с которого начали компилировать.

**Comment by ibond84** [comment]
Это безобразие надо вообще запретить. В делфи uses in допустим только для программ и библиотек.

**Comment by SunSerega** [comment]
Не надо пожалуйста. Вложенный uses-in позволяет очень удобно организовывать проект. А в дельфи, как вы рассказываете - с запретами дело обстоит даже хуже чем в C#.
