### ISSUE TITLE
Наследование от EqualityComparer не работает, если в типе шаблона указать пользовательский тип

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#2086]
```
type
  // Компилируется нормально
  Comp1 = class(System.Collections.Generic.EqualityComparer<byte>)
    
    public function Equals(x, y: byte): boolean; override :=
    x = y;
    
    public function GetHashCode(obj: byte): integer; override :=
    obj.GetHashCode;
    
  end;
  
  t0 = class end;// не важно класс или запись, главное какой то пользовательский тип
  
  //Ошибка: Конструктор по умолчанию в базовом классе EqualityComparer<t0> не найден
  Comp2 = class(System.Collections.Generic.EqualityComparer<t0>)
    
    public function Equals(x, y: t0): boolean; override :=
    x = y;
    
    public function GetHashCode(obj: t0): integer; override :=
    obj.GetHashCode;
    
  end;
  
begin end.
```

**Comment by SunSerega** [comment]
Ну и с шаблонным типом та же история:
```
type
  Comp<T> = class(System.Collections.Generic.EqualityComparer<T>)
    
    public function Equals(x, y: T): boolean; override :=
    x = y;
    
    public function GetHashCode(obj: T): integer; override :=
    obj.GetHashCode;
    
  end;
  
begin end.
```
Добавьте это тоже в тесты, пожалуйста.

**Comment by SunSerega** [comment]
Пока что, в качестве костыля - можно наследовать от `IEqualityComparer`. Единственное что надо поменять тогда - убрать слово `override` из объявления обоих функций.

**Comment by miks1965** [comment]
syntax_tree_visitor.cs 4029
context.converted_type.has_default_constructor
в первом случае возвращает true, во втором почему-то false

**Comment by miks1965** [comment]
18757
List<SymbolInfo> sil = _ctn.base_type.find_in_type(compiler_string_consts.default_constructor_name, _ctn.base_type.Scope);

не оказывается в базовом типе EqualityComparer<T0> конструктора по умолчанию (compiled_generic_instance_type_node). А для byte оказывается (compiled_type_node)

**Comment by miks1965** [comment]
NetHelper.cs 1488 
List<MemberInfo> mis = GetMembers(t, name);
