### ISSUE TITLE
Запретить явный вызов акцессоров свойств

### ISSUE THREAD

**Issue by AIexandrKotov** [pascalabcnet/pascalabcnet#2087]
```
type
  T = class
    public property Prop: integer read 999;
  end;

begin
  T.Create.get_Prop.PrintLn; //999
  typeof(T).GetMethod('get_Prop').IsPublic.Println; //true
end.
```
Intellisense в приложениях эти методы скрывает. Но вот с библиотеками это уже становится проблемой: pascalabcnet/pascalabcnetide#139.

**Comment by miks1965** [comment]
Они публичны. И в IL-коде публичны. И на C# публичны.
И что с этим делать? Какая такая проблема в этом?

**Comment by SunSerega** [comment]
Пример значит плохой. Но изначальная проблема, почему была написана эта issue:
```
type
  T = class
    public static property Prop: integer read 999;
  end;

begin
  T.get_Prop().Println;
end.
```
Проблема в том что это кишки. Ожидается что все нормальные языки - сами скроют их.
В C# компилятор не видит геттеры и сеттеры, не зависимо от их уровня доступа.

**Comment by ibond84** [comment]
Не надо запрещать. В паскале они могут переопределяются. Ссылаться не C# бессмысленно, там совершенно другой синтаксис свойств.
