### ISSUE TITLE
params всё ещё разворачивается в немного говнокода

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#2090]
Re: #2080.
```
procedure p1<T>(params a: array of T) := exit;

begin
  p1(1,2,3);
end.
```
Превращается в:
```
    public static void $Main()
    {
      int[] numArray1 = new int[3];
      int[] numArray2 = numArray1;
      numArray2[0] = 1;
      numArray2[1] = 2;
      numArray2[2] = 3;
      Program.p1<int>(numArray1);
    }
```
Переменные вообще не нужны. Надо заменять несколько последних параметров в вызове на выражение `new int[3](1,2,3)`. То есть делать всё не сохраняя в локальных переменных.

**Comment by ibond84** [comment]
Переменные нужны и они в IL активно используются. В частности, C# генерирует тот же самый IL-код.

**Comment by SunSerega** [comment]
Нет, C# использует только 1 переменную.
