### ISSUE TITLE
"Generic-функция не может быть вызвана" если вместо шаблонного интерфейса передавать класс

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#2092]
... у которого в наследовании между ним и интерфейсом есть шаблонный класс.

```
type
  I1<T>=interface end;
  C1<T>=class(I1<T>) end;
  C2=class(C1<integer>) end;

procedure p1<T,T1>(self: sequence of T; l: T->T1; o: I1<T1>); extensionmethod := exit;
procedure p2<T,T1>(self: sequence of T; o: I1<T1>); extensionmethod := exit;

begin
  // любая 1 из этих строк даёт ошибку:
  Seq&<byte>.p1(b->0,new C2);
  Seq&<byte>.p2(new C2);
end.
```

**Comment by miks1965** [comment]
C2 не реализует интерфейс I1<T>. Всё верно. Это и в C# так  - проверьте

**Comment by AIexandrKotov** [comment]
В C# этот же код работает:

```C#
    interface I1<T>
    {

    }
    class C1<T>: I1<T>
    {

    }
    class C2: C1<int>
    {

    }
    static class extensions
    {
        public static void p1<T, T1>(this IEnumerable<T> self, Func<T, T1> l, I1<T1> o)
        {
            return;
        }
        public static void p2<T, T1>(this IEnumerable<T> self, I1<T1> o)
        {
            return;
        }
    }
    class Program
    {
        static IEnumerable<T> Seq<T>()
        {
            yield return default(T);
        }
        static void Main(string[] args)
        {
            Seq<byte>().p1(b => 0, new C2());
            Seq<byte>().p2(new C2());
        }
    }
```

**Comment by SunSerega** [comment]
> C2 не реализует интерфейс I1. Всё верно. Это и в C# так - проверьте

Реализует. Посмотрите внимательно, `C2` на следует от `C1`, которое уже реализует.

**Comment by miks1965** [comment]
Ясно. Нет, у нас другая модель. Нужно написать явно. Напишите явно и проверьте

**Comment by SunSerega** [comment]
> Ясно. Нет, у нас другая модель. Нужно написать явно. Напишите явно и проверьте

В смысле другая? Реализация интерфейсов наследуется, это правило в IL. Это не то что вы можете по своему сделать.

**Comment by AIexandrKotov** [comment]
Лучше бы вы "по своему" (а точнее как в VB.NET) разрешили var self extensions))

**Comment by miks1965** [comment]
> Реализация интерфейсов наследуется, это правило в IL
Это где такое? Ссылку приведите.

В C++ как у нас

**Comment by miks1965** [comment]
Оставляйте. Посмотрим, как это сделать.

**Comment by ibond84** [comment]
https://github.com/pascalabcnet/pascalabcnet/actions/runs/658746354
