### ISSUE TITLE
Вызов метода шаблонного типа через экземпляр наследника даёт BadImageFormatException, если запускать модуль

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#2099]
```
uses u;

begin
  var q: t1;
  q.p1;
end.
```
```
unit u;

type
  
  t0<T> = class
    procedure p1 := exit;
  end;
  t1 = class(t0<byte>) end;

end.
```
[0.zip](https://github.com/pascalabcnet/pascalabcnet/files/3594521/0.zip)
```
Ошибка времени выполнения: System.BadImageFormatException: Была сделана попытка загрузить программу, имеющую неверный формат. (Исключение из HRESULT: 0x8007000B)
Стек:
   в 0.Program.$Main()
   в 0.Program.Main()
```
Если посмотреть в IL код - в программе происходит что то такое:
```
uses u;

begin
  var q: t1;
  (q as t0<???>).p1;
end.
```
В качестве шаблона `t0` выбирает шаблонный параметр `$Main` по индексу 0. Вот только у `$Main` нету шаблонных параметров, отсюда `BadImageFormatException`.

Чтоб воспроизвести надо открыть оба файла в IDE, сделать активным файл программы, переключится на файл модуля и нажать F9. Если пытаться воспроизводить по-другому - ошибка становится плавающей.

То есть ситуация примерно такая же как в #2048, только в этот раз в более часто встречающемся случае.

**Comment by miks1965** [comment]
А без модуля это не происходит?

**Comment by SunSerega** [comment]
Нет, я же говорю, дело в ломании .pcu если запускать когда открыта вкладка модуля, как и в случае #2048.
