### ISSUE TITLE
Записи без оператора сравнения не правильно сравниваются в некоторых случаях

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#2101]
.dll написана на C#, чтоб не было оператора сравнения по-умолчанию:
```
using System;

namespace TestLib
{
	public struct Rec1
	{
		public int a, b;
		
		public Rec1(int a, int b)
		{
			this.a = a;
			this.b = b;
		}
		
	}
}
```
```
{$reference TestLib.dll}

var
  a := new TestLib.Rec1(1, 2);
  b := new TestLib.Rec1(1, 2);
  c := new TestLib.Rec1(3, 4);

begin
  
  writeln( a = b);  // False, неправильно
  writeln( a <> b); // True,  неправильно
  writeln( a = c);  // False, правильно
  writeln( a <> c); // True,  правильно
  
  var a1 := a;
  var b1 := b;
  var c1 := c;
  writeln( a1 = b1);  // True,  правильно
  writeln( a1 <> b1); // False, правильно
  writeln( a1 = c1);  // False, правильно
  writeln( a1 <> c1); // True,  правильно
  
end.
```
[0.zip](https://github.com/pascalabcnet/pascalabcnet/files/3612743/0.zip)

Паскаль использует всюду `IL` оператор `ceq` для всех сравнений.
`ceq` не работает для записей которые хранятся в куче (то есть как поле класса, в том числе и статическое).

Можно загружать записи в локальные переменные (как `a1`, `b1`, `c1` в примере выше) или сравнивать по 1 полю (так делает C#).

**Comment by miks1965** [comment]
Если запись создаётся по new, то она всё равно не хранится в куче - только на стеке. Поэтому непонятно, почему в одних случаях это работает, в других - нет.

**Comment by SunSerega** [comment]
> Если запись создаётся по new, то она всё равно не хранится в куче - только на стеке

Дело не в `new`.

`a`, `b` и `c` хранятся в глобальной переменной, то есть в статичном поле. Поэтому в куче.

**Comment by miks1965** [comment]
Ладно. Но такой пример без dll работает:
```
type Rec1 = record
  a,b: integer;
  constructor (aa,bb: integer);
  begin
    a := aa;
    b := bb;
  end;
end;

var
  a := new Rec1(1, 2);
  b := new Rec1(1, 2);
  c := new Rec1(3, 4);

begin
  
  writeln( a = b);  // False, неправильно
  writeln( a <> b); // True,  неправильно
  writeln( a = c);  // False, правильно
  writeln( a <> c); // True,  правильно
  
  var a1 := a;
  var b1 := b;
  var c1 := c;
  writeln( a1 = b1);  // True,  правильно
  writeln( a1 <> b1); // False, правильно
  writeln( a1 = c1);  // False, правильно
  writeln( a1 <> c1); // True,  правильно
  
end.
```
Почему?

**Comment by SunSerega** [comment]
Потому что паскаль генерирует оператор сравнения (сравнивающий по 1 полю) и его использует вместо `ceq`.

**Comment by miks1965** [comment]
А почему в dll он не генерирует?

**Comment by SunSerega** [comment]
Потому что .dll сделана на `C#`.

**Comment by ibond84** [comment]
>C# не генерирует стандартные операторы сравнения. Вместо этого если в коде вызывается сравнение записей у которых оператор сравнения не определён - это сравнение разворачивается в сравнение каждого отдельного поля.

Неправильно, компилятор C# выдает сообщение об ошибке

**Comment by ibond84** [comment]
Надо просто вызывать Equals

**Comment by miks1965** [comment]
Таки Issue надо закрывать?

**Comment by SunSerega** [comment]
С чего вдруг? ibond о том как правильнее исправлять, а вы закрывать...

**Comment by miks1965** [comment]
A-a-a...
