### ISSUE TITLE
Оператор не вызывается для шаблонной записи из шаблонной подпрограммы

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#2102]
```
type
  t1<T> = record
  class function operator=(a, b: t1<T>): boolean;
  begin
    Writeln('operator='); 
    Result := false;
  end;
  class function operator<>(a, b: t1<T>): boolean;
  begin
    Writeln('operator<>'); 
    Result := true;
  end;
  end; 
  
begin
  var o: t1<byte>;
  writeln(o=o);
  
end.
```

**Comment by miks1965** [comment]
У нас для записей вшито сравнение на равенство, ПОЭТОМУ И НЕ ВЫЗЫВАЕТСЯ.

Кстати, и для не generic тоже

**Comment by SunSerega** [comment]
Кхм, наверное недотестил что то, но вроде это переставало воспроизводится с не_шаблонной записью...

Ну тогда вот пример лучше:
```
function operator=<T1,T2>(a, b: System.ValueTuple<T1,T2>): boolean; extensionmethod;
begin
  Writeln('operator=');
  Result := false;
end;

procedure p1<T1,T2>(o: System.ValueTuple<T1,T2>);
begin
  Writeln( o=o );
end;

begin
  var o := System.ValueTuple.Create(1,2);
  
  p1(o);
  
end.
```
У `ValueTuple` нету стандартного оператора `=`. А в `p1`, вроде, вызывается IL оператор `ceq` для сравнения.

**Comment by miks1965** [comment]
Это недоработки .NET. Мы про них не знали. 

Мы запретим вызывать operator= для типов из dll, у которых не определен operator=

**Comment by SunSerega** [comment]
В смысле, зачем? Надо только дать ему меньший приоритет. А `ceq` в целом работает для сравнения записей.

**Comment by miks1965** [comment]
Не понял. Какой может быть меньший приоритет у o=o? Там нет других операндов?

Я вижу, что сравнение на равенство не вызывается. Если это из-за IL кода, то мы это запретим поскольку повлиять на это никак не можем

**Comment by SunSerega** [comment]
Я говорю про то что если есть оператор-`extensionmethod` - надо выбирать его. А если нет - вызывать `ceq` в IL коде.

`ceq` работает для сравнения записей поэтому не надо его ломать.
Но если есть определённый ручками оператор сравнения - надо использовать именно его вместо `ceq`.

**Comment by miks1965** [comment]
Но тут же вы пишете, что не работают в каких-то случаях:
https://github.com/pascalabcnet/pascalabcnet/issues/2101
Я не понимаю кстати из-за чего там не работают. Вот вроде свой оператор не определен и мы используем ceq

**Comment by ibond84** [comment]
Гораздо более комактный пример

```
type
  t1<T> = record
  class function operator=(a, b: t1<T>): boolean;
  begin
    Writeln('operator='); 
    Result := false;
  end;
  class function operator<>(a, b: t1<T>): boolean;
  begin
    Writeln('operator<>'); 
    Result := true;
  end;
  end; 
  
begin
  var o: t1<byte>;
  writeln(o=o);
  
end.
```

Странно, в IL генерируется вызов op_Equality, но JIT его не вызывает..

**Comment by ibond84** [comment]
Изменил issue, так как код неправильный. Описывается зачем-то метод расширения, если можно описать внутри записи. Пожалуйста, не переусложняйте. Это сбивает. 
Ошибка заключается в том, что в IL добавляются два метода op_Equality

**Comment by ibond84** [comment]
И ваш код правильно не работал. Методы расширения расширяют, а не переопределают! Где-то видел issue, что надо бы ошибку выдавать (или предупреждение)

**Comment by SunSerega** [comment]
Однако, мне при декомпиляции t1 показывает дубли обоих методов:
```
    public static bool operator ==(t1<T> a, t1<T> b)
    {
      PABCSystem.PABCSystem.Writeln((object) "operator=");
      return false;
    }

    public static bool operator !=(t1<T> a, t1<T> b)
    {
      PABCSystem.PABCSystem.Writeln((object) "operator<>");
      return true;
    }

    public static bool operator ==(t1<T> a, t1<T> b)
    {
      return true;
    }

    public static bool operator !=(t1<T> a, t1<T> b)
    {
      return false;
    }
```
