### ISSUE TITLE
Вызывает не ту GetEnumerator для объектов типа ICollection

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#2105]
```
begin
  var o: ICollection<byte>;
  var enm: IEnumerator<byte> := o.GetEnumerator;
end.
```
`Нельзя преобразовать тип function: IEnumerator к IEnumerator<byte>`

Если объявить `o` как `IEnumerable` - всё в порядке, потому что выбирает вторую `GetEnumerator`, ту что возвращает шаблонный `IEnumerator`.

**Comment by SunSerega** [comment]
Похоже, на массивы это тоже распространяется:
```
begin
  var a: array of string;
  var enmr: IEnumerator<string> := a.GetEnumerator(); //Ошибка: Нельзя преобразовать тип System.Collections.IEnumerator к IEnumerator<string>
end.
```
Это должно работать, потому что так работает:
```
begin
  var a: array of string;
  var enmr: IEnumerator<string> := a.AsEnumerable.GetEnumerator;
end.
```

**Comment by ibond84** [comment]
>Похоже, на массивы это тоже распространяется:

Нет, у массивов свой метод GetEnumerator, который возвращает System.Collections.IEnumerator
