### ISSUE TITLE
Запретить множественное наследование через partial-классы

### ISSUE THREAD

**Issue by AIexandrKotov** [pascalabcnet/pascalabcnet#2127]
```
type
  T1 = class public procedure p := Writeln('333'); end;
  
  T2 = class public procedure p := Writeln('444'); end;
  
  T = partial class(T1) end;
  
  T = partial class(T2) end;

begin
  T.Create.p;
end.
```

Это безобразие сейчас компилируется!!!!

Но на практике второй базовый тип просто заменяет первый.

**Comment by AIexandrKotov** [comment]
В C# на это даётся ошибка:
```
Ошибка	CS0263	Разделяемые объявления "T" не должны указывать различные базовые классы.
```

**Comment by SunSerega** [comment]
Простейший способ исправить - заставить программиста ставить одинаковый список наследников в каждый `partial` класс.
Но, пожалуйста, не делайте так. В `OpenCLABC` такая конструкция позволит красиво сэкономить несколько сотен строк кода:
```
unit u;

interface

type
  t1 = partial class end;
  t2 = partial class end;
  
implementation

type
  // t0 не должен быть доступен пользователю модуля
  t0 = class
    // общий для t1 и t2 функционал
  end;
  
  t1 = partial class(t0)
    
  end;
  t2 = partial class(t0)
    
  end;
  
end.
```
---

Предлагаю сделать так:

Если предыдущее объявление `partial` класса не содержало класс в наследниках (интерфейсы не считаются) - следующее объявление может (но не обязательно) содержать класс в списке наследников.

Но если предыдущее объявление уже наследовало от класса - значит и следующее должно. Это надо потому что:
1. Если класс уже был указан в наследниках - он уже точно виден.
2. Так сложнее допустить ошибку, забыв от чего наследует `partial` класс.
3. Иначе это ещё +несколько issue, такой код сейчас ведёт себя довольно криво:
```
unit u0;

type
  t0 = class end;
  
  t1 = partial class(t0) end;
  t1 = partial class end;
  
end.
```

**Comment by AIexandrKotov** [comment]
Это неправильно, доступность базового класса никогда не должна быть ниже его наследников

**Comment by SunSerega** [comment]
> доступность базового класса никогда не должна быть ниже его наследников

С чего вдруг? Обычно так получается. Но с чего ты решил что это правило?

`///--` я сейчас использую, но вообще это плохо, потому что пользователю модуля хоть и не показывает, но всё равно даёт использовать внутренние классы, которые не должны использоваться вне модуля.

Так же обратите внимание, что интерфейс типов `t1` и `t2` (то есть публичные методы и свойства) всё равно могут находится только в `interface` части модуля. Содержимое скрытого базового класса - всегда будет только внутренним функционалом.

**Comment by AIexandrKotov** [comment]
> С чего вдруг? Обычно так получается. Но с чего ты решил что это правило?

Это запрещено в .NET. И как мы с тобой уже проверили с помощью Reflection.Emit, это теоретически позволяет получить доступ к internal-членам другой сборки. Именно поэтому это запрещено.

**Comment by SunSerega** [comment]
> теоретически позволяет получить

А я (в личке) 3 раза успел объяснить что такое наследование через `partial` класс, какое я тут объясняю - не позволит получить член с приватным типом сборки.

**Comment by ibond84** [comment]
>// t0 не должен быть доступен пользователю модуля
>  t0 = class

Это плохой дизайн, не соответствующих принципам ООП
