### ISSUE TITLE
Missing type information in editor

### ISSUE THREAD

**Issue by sglienke** [pascalabcnet/pascalabcnet#2132]
First of all kudos for getting the type inference working properly - before I had to explicitly type a few things, now I could remove all explicit typing and it just works!

Following code is a complete and working program, however the editor is missing some type information (probably only a visual glitch as it compiles and runs properly):

```
{$reference 'System.Reactive.dll'}

uses
  System,
  System.Diagnostics,
  System.Reactive.Linq;
    
begin
  var interval := Observable.Interval(TimeSpan.FromMilliseconds(500));
  var groups := interval.GroupBy(x -> x mod 10);
    
  var sw := Stopwatch.StartNew;
  groups.Subscribe(g -> 
    begin 
      Writeln('Group started with key: ', g.Key); 
      g.Subscribe(x -> Writeln(sw.ElapsedMilliseconds, ': ', x)); 
    end);
  Readln;
end.
```

Tooltip for interval shows: `var interval: IObservable<>;` however tooltip for `Observable.Interval` properly shows that it returns `System.IObservable<Int64>`.

Following types are also all missing the `Int64` part - for example tooltip for `g` shows:
`parameter g: IObservable<IGroupedObservable<IObservable<>, function(x: T):>>;`.

And finally tooltip for `x` shows `parameter x: IObservable<IGroupedObservable<IObservable<>, function(x: T): >>;` while it simply should show `Int64`.

**Comment by SunSerega** [comment]
1. IDE issues have been moved to separate dummy repository:
https://github.com/pascalabcnet/pascalabcnetide/issues
What you are showing here are issues of code analyser, which is an IDE feature. And generally, every problem which isn't connected with pressing compile button is IDE issue.

2. Upload that .dll, so that noone need to search for that old issue.

3. Or better - remove parts of the code which are unnecessary for getting those code analyser glitches (including references of types from non-default .dll-s, if possible), so that every glich has it's own minimal code. And then put all the minimal codes in separate issues. Grouping problems in single issue really complicates fixing them.

**Comment by SunSerega** [comment]
> To understand what is compiler and what is IDE I would have to know about the internal architecture

Code analyser reuses parts of compiler code, but they can't be the same, as code analyzer must work in real time and with non-full programs.

And as you noted yourself - your program compiles successfully, so you can be sure that problem isn't in compiler code. This is a logic i used when saying:

> generally, every problem which isn't connected with pressing compile button is IDE issue.

---

> I would have to write equally complex types to showcase this issue.

No you don't. Only thing that can cause issue - is what directly used in pascal program part (+ maybe other overloads of used functions). In your case there is not much of a code to begin with, so even if you aren't experienced in it - finding minimal code should take you ~20 min.

That said - it's just a way to contribute. Harder then throwing code with minimal explanation into issue, but much easier then making pull request. But thing is, finding minimal code is much easier for you, as you know what parts of code do what and more-less experienced with that .dll.

**Comment by miks1965** [comment]
Кто-нибудь перенесите это в Issue для IDE

Если можно - без строчки несуществующего 
{$reference 'System.Reactive.dll'}

**Comment by SunSerega** [comment]
"перенести" это однозначно работа разработчиков. А .dll вам сказали, в nuget скачивается.
