### ISSUE TITLE
Нельзя преобразовать тип file of integer к file of integer

### ISSUE THREAD

**Issue by miks1965** [pascalabcnet/pascalabcnet#2133]
```
begin
  var f: file of integer;
  
  f := OpenFileInteger('');
  f := CreateFileInteger('');
end.
```
Program1.pas(12) : Нельзя преобразовать тип file of integer к file of integer

**Comment by AIexandrKotov** [comment]
Это потому что **file of integer** это тип из PABCSystem, а OpenFileInteger и CreateFileInteger функции из PABCExtensions?

**Comment by miks1965** [comment]
Трудно сказать
