### ISSUE TITLE
Потеря контекста при захвате Result функции лямбдой-процедурой

### ISSUE THREAD

**Issue by AIexandrKotov** [pascalabcnet/pascalabcnet#2136]
```pas
function f: integer;
begin
  var x: Action0 := () ->
  begin
    Max(Result, 1).Print;
  end;
end;

begin
  
end.
```
```
Undefined FileName(0) : Неизвестное имя '$rv_f'
```

**Comment by AIexandrKotov** [comment]
Вот что интересно: эта ошибка воспроизводится начиная с версии 2090, а в 2069 этот код вызывает ошибку:
```
Program2.pas(11) : В данной версии компилятора не поддерживается замыкание данного типа символов
```
Следовательно, это было сломано где-то в конце мая / начале июня.

**Comment by AIexandrKotov** [comment]
Интересно, что в этом случае:
```pas
type
  T1 = class
    i: integer;
  end;

begin
  var x: Func0<T1> := () ->
  begin
    Result.i.Print
  end;
end.
```

Result просто не видит:
```
Program3.pas(9) : Неизвестное имя 'Result'
```

**Comment by SunSerega** [comment]
Вот на самом деле минимальный код:
```
function f: integer;
begin
  var p: ()->() := () ->
  begin
    var a := Result;
  end;
end;

begin end.
```
Ошибка та же что в заголовке.

Когда то вы собирались запретить захват Result верхнего уровня в лямбдах полностью. В том числе в лямбдах-процедурах.
@miks1965 говорил об это только в #873.
А @ibond84 вроде более напрямую высказывался про запрет на форуме. Но поиск форума меня не любит.

Я поддерживаю это полностью. Захват `Result` верхнего уровня - провоцирует ошибки. Особенно при рефакторинге кода.
Хотя @AIexandrKotov -у вроде тоже было что сказать. Стоит дождаться его мнения перед тем как принимать решение.

**Comment by AIexandrKotov** [comment]
Ну вот, например, код параллельного перемножения массивов:
```pascal
uses System;
uses System.Threading.Tasks;

function Mult(a, b: array of integer): array of int64;
begin
  Result := new int64[a.Length];
  Parallel.For(0, a.Length, i ->
  begin
    Result[i] := a[i] * b[i];
  end);
end;

begin
  Mult(ArrRandom(10, 1, 10), ArrRandom(10, 1, 10)).Print;
end.
```
Как вы сможете оставить уровень производительности такой же, как у этого кода, но учитывая запрет захвата Result? Ну, лично я не вижу никаких адекватных возможностей для этого, разве что:
```pascal
uses System;
uses System.Threading.Tasks;

type
  Тупой_костыль = static class
    private static returnvalue: array of int64;
    private static leftarray, rightarray: array of integer;
    
    private static procedure __lambda1(i: integer);
    begin
      returnvalue[i] := leftarray[i] * rightarray[i];
    end;
    
    public static function Mult(a, b: array of integer): array of int64;
    begin
      returnvalue := new int64[a.Length];
      leftarray := a;
      rightarray := b;
      Parallel.For(0, returnvalue.Length, __lambda1);
      Result := returnvalue;
    end;
  end;

function Mult(a, b: array of integer): array of int64;
begin
  Result := Тупой_костыль.Mult(a, b);
end;

begin
  Mult(ArrRandom(10, 1, 10), ArrRandom(10, 1, 10)).Print;
end.
```
Ну это прямо вообще извращение какое-то. Если вам это нравится, то, конечно, можно запретить всякие эти Result в лямбдах-процедурах, но лично мне первый код нравится больше.

Какие ошибки это может вызвать? У лямбды с возвращаемым значением свой Result, и тогда, разумеется, она не имеет права обращаться к Result функции, а вот когда лямбда это процедура, то тут никаких альтернатив у неё и нет, так как своего Result она не имеет.

Это моё мнение по поводу этого. Запрещать ничего не нужно. А проблемы реализации в данном случае это не мои проблемы (иду, похоже, по стопам сами-знаете-кого)
> Захват Result верхнего уровня - провоцирует ошибки. Особенно при рефакторинге кода.

А это пока ничем не подкреплено, жду аргументов.

**Comment by SunSerega** [comment]
Как и сказал в вк - доп. переменные:
```
function Mult(a, b: array of integer): array of int64;
begin
  var res := new int64[a.Length];
  Parallel.For(0, a.Length, i ->
  begin
    res[i] := a[i] * b[i];
  end);
  Result := res;
end;
```
> оставить уровень производительности такой же

JIT очень хорош в убирании лишних переменных.

> Захват Result верхнего уровня - провоцирует ошибки. Особенно при рефакторинге кода.

Я имею в виду, когда тип параметра принимающего делегат меняется между процедурой и функцией. Тогда можно недоглядеть и оставить `Result` в теле лямбды.
У меня в `OpenCLABC` такое изменение по несколько раз между пулами происходит.

**Comment by miks1965** [comment]
Итог - запретить захват Result в лямбде внутри функции

**Comment by miks1965** [comment]
Result в теле лямбда-выражения делает её функцией. Но только при присваивании. Если присваивания нет, то это лямбда-процедура, и имя Result неизвестно. Здесь единственная проблема - неверная ошибка

**Comment by miks1965** [comment]
Это благополучно работает:
```
// #2136
function f: integer;
begin
  Result := 2;
  var x: ()->integer := () ->
  begin
    Result := 5;
    Max(Result, 777).Print;
  end;
  Result := x();
end;

begin
  f.Print;
end.
```

**Comment by AIexandrKotov** [comment]
Пожалуйста, сделайте информативную ошибку для этого случая, вроде:

`Result функции не может быть использован в теле процедурного лямбда-выражения, используйте дополнительную переменную.`

Я даже не сразу подумал о таком очевидном решении, а про возможности вашего оптимизатора так вообще хорошо известно лишь тем, кто часто декомпилирует код.

Также, нужна нормальная ошибка для случая, когда лямбда-процедура, захватывающая Result, находится не в функции, а в другой лямбде (здесь Undefined FileName не возникает):
```
begin
  var f: () -> integer := () ->
  begin
    Result := 1;
    var x: Action0 := () ->
    begin
      Result.Print; //Program13.pas(7) : В данной версии компилятора не поддерживается замыкание данного типа символов
    end;
  end;
end.
```

**Comment by miks1965** [comment]
Исправил. Очень трудное исправление. Точный контекст так и не удалось восстановить.

Но Result внутри лямбды уже не трактуется как захват - он считается Result этой лямбды. Result из внешнего контекста не только нельзя захватывать - он игнорируется.

**Comment by SunSerega** [comment]
> В последнем примере сообщение абсолютно верное

Оно не верное хотя бы потому - что говорит "в данной версии", как будто это не реализованная фича.

А ещё это слишком общее сообщение. В большом коде - оно совершенно не будет объяснять что именно не правильно написано.

**Comment by miks1965** [comment]
Да, спасибо. Подкорректировал сообщение об ошибке
