### ISSUE TITLE
Падение компилятора при вызове Delegate и при использовании лямбды

### ISSUE THREAD

**Issue by ibond84** [pascalabcnet/pascalabcnet#2138]
```
uses System;

begin
  var d: Delegate := ()->Writeln(1);
  d();
end.
```

**Comment by SunSerega** [comment]
У меня не падает. Даёт обычную ошибку:
`Program1.pas(5) : Ожидалось имя процедуры или функции`

И - приложите, пожалуйста, полный текст ошибки со стеком. Это надо когда я перед тем как запостить issue - проверяю чтоб это не был дубль.

**Comment by miks1965** [comment]
У меня нет ошибки:
![изображение](https://user-images.githubusercontent.com/10325391/80922307-dc555200-8d84-11ea-9e92-879ab2204b49.png)

**Comment by ibond84** [comment]
Не падает
