### ISSUE TITLE
Реализовать вывод лямбды по элементу массива - params параметра

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#2139]
```
procedure p1(params fs: array of Action0) := exit;

begin
  //Ошибка: Неверный тип переменной, которой присваивается лямбда-выражение
  p1(()->
  begin
    
  end);
end.
```
Это должно быть не сложно сделать:
Если у параметра есть атрибут `params` - он точно не делегает (не бывает типов которые сразу и массив и делегат). Поэтому если встречена лямбда - сразу понятно что надо вычислять её тип по типу элементов массива.

То есть в данном случае при выводе типа лямбды - надо смотреть не на `array of Action0`, а на `Action0`, потому что есть `params`. А это всего +1 условие в компиляторе.

**Comment by ibond84** [comment]
https://github.com/pascalabcnet/pascalabcnet/actions/runs/466895902
