### ISSUE TITLE
Ошибка при наследовании типа class(T1<T2<T3>>), когда T2 пред-описан, но ещё не описан

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#2140]
```
type
  // для воспроизведения не обязательно 2 разных типа, но и не обязательно один и тот же
  TBase<T1> = class
    f1: T1;
  end;
  
  TErrBase<T2> = class
    f2: T2;
  end;
  
  
  
  // обязательно до TDer только предописание TErr
  // если поставить полное описание TErr перед TDer - ошибки нет
  TErr<T3>=class;
  
  TDer<T4> = class(TBase<TErr<T4>>)
    
    procedure p1;
    
  end;
  
  TErr<T3> = class(TErrBase<T3>) end;
  
procedure TDer<T4>.p1;
begin
  f1.f2 := default(T4); //Ошибка: Нельзя преобразовать тип T4 к T3
end;

begin end.
```
С точки зрения класса `TDer<T4>` - его поле `f1` имеет тип `TErr<T4>`.
А значит `f1.f2` имеет тип `T4`.
А компилятор почему то думает что у него тип `T3` (который вообще не существует в данном контексте).

**Comment by miks1965** [comment]
Здесь надо запретить наследовать от объявленных, но не описанных классов. В Delphi - так.

**Comment by SunSerega** [comment]
В этой программе нет наследования от не описанного типа. Есть только использование не описанного типа как шаблонного параметра. А это нельзя запрещать, иначе это будет вообще никак невозможно реализовать:
```
type
  t0<T> = class end;
  
  t1 = class;
  t2 = class;
  
  t1base = class(t0<t2>) end;
  t2base = class(t0<t1>) end;
  
  t1 = class(t1base) end;
  t2 = class(t2base) end;
  
begin end.
```
И такой такой запрет моментально сломает OpenCLABC, потому что подобное там много где используется.

**Comment by miks1965** [comment]
Попробуйте сделать такое на C#
Это явный запрет, это не должно работать нигде.

**Comment by SunSerega** [comment]
С чего вдруг такому не работать? Это не циклическое наследование, в типах шаблонов может быть что угодно. Это позволяет создавать более сложные патерны, к примеру, всем известный:
```
MyValueType = record(IComparable<MyValueType>)
```
У конструкции которая падает - тоже есть применения в качестве очень удобных паттернов. Более сложных и менее известных, но не менее полезных.

Что касается C#:
```
namespace Test1
{
	class TBase<T1>
	{
		public T1 f1;
	}
	class TErrBase<T2>
	{
		public T2 f2;
	}
	
	class TDer<T4> : TBase<TErr<T4>>
	{
		void p1()
		{
			f1.f2 = default(T4);
		}
	}
	class TErr<T3> : TErrBase<T3>
	{
		
	}
	
	static class Program
	{
		public static void Main() {}
	}
}
```
```
namespace Test1
{
	class t0<T> { }
	
	class t1base : t0<t2> {}
	class t2base : t0<t1> {}
	
	class t1 : t1base {}
	class t2 : t2base {}
	
	static class Program
	{
		public static void Main() {}
	}
}
```
Оба этих кода компилируются успешно. И я бы чрезвычайно удивился, если бы это давало ошибку.

**Comment by miks1965** [comment]
Ага. Ясно

**Comment by SunSerega** [comment]
И - в первую очередь смотреть какая для вас конструкция страшная и ужасаться - это плохо. Лучше тратить больше времени но делать качественнее. Я предлагаю в первую очередь думать в каком случае что то нереализуемо.

Вот к примеру циклическое наследование нереализуемо, потому создаёт типы с бесконечным размером.

А в случае шаблонных параметров - не важно что в них засунуть. По крайней мере я не могу представить примера где засовывание чего то циклического в шаблонные параметры - могло привести к какой то нереализуемой конструкции.

Если нереализуемых конструкций с фичей нету - значит и запрещать нечего.

**Comment by ibond84** [comment]
Запретить глубокоие инстанцирование недоописанным классом. Сравнивать с C# нет смысла. Там компилятор многопроходный и порядок следования имен не имеет значения.

**Comment by ibond84** [comment]
```
type T1<T> = class;
T2<T> = class(T1<integer>)
end;

T1 = class
  
end;
begin
  
end.
```
Такое не компилируется и правильно

**Comment by SunSerega** [comment]
> Там компилятор многопроходный и порядок следования имен не имеет значения.

Так а тут это при чём? В чём проблема заполнять тело класса уже после того как создали ему наследника?

Кроме того, перед тем как что то запрещать - введите способы добиться того же по-другому.
А то получается что вы вырезаете из языка то, что уже работает.

**Comment by ibond84** [comment]
Ну, опишите TErr3 в начале и все. Вы же не удивляетесь, когда компилятор запрещает наследовать от недоопределенного класса.

**Comment by SunSerega** [comment]
Я уже не помню, но вроде аналог TErr в изначальном коде, где я эту issue словил, тоже было проблематично двигать, из за какого то другого запрета...
Ну да это и не важно, потому что второй код так просто не заменить:
```
type
  t0<T> = class end;
  
  t1 = class;
  t2 = class;
  
  t1base = class(t0<t2>) end;
  t2base = class(t0<t1>) end;
  
  t1 = class(t1base) end;
  t2 = class(t2base) end;
  
begin end.
```

**Comment by SunSerega** [comment]
Хотя то что вы хотите запретить - затронет на много больше кода. Так что такая махина не нужна.
Вот проще и реалистичнее пример:
```
  t1 = class(IConvertableTo<t2>) end;
  t2 = class(IConvertableTo<t1>) end;
```

**Comment by miks1965** [comment]
Если рассматривается только пример в начале, то надо запретить предописание обобщённого класса. 

```
TErr<T3>=class;
```

Это снимет ошибку.

**Comment by SunSerega** [comment]
Ещё лучше...
```
type
  TChild<T> = class;
  
  TOwner<T> = class
    child: TChild<T>;
  end;
  
  TChild<T> = class
    owner: TOwner<T>;
  end;
  
begin end.
```
Что с этим кодом тогда?

> Это снимет ошибку.

Это ужасный способ мыслить. Что хорошего в решении "лишь бы побыстрее issue закрыть"?

Лучше закрывать issue медленнее, но при этом тратить время на улучшение языка, а не на раздумывание "что бы ещё такого запретить".

**Comment by miks1965** [comment]
Ладно. Тогда например так: нельзя наследовать от предописанного класса

**Comment by ibond84** [comment]
На самом деле здесь надо запретить предописание шаблонного класса, если в описании потом будет наследование от класса и ограничение where.

**Comment by ibond84** [comment]
>Лучше закрывать issue медленнее, но при этом тратить время на улучшение языка, а не на раздумывание "что бы ещё такого запретить".

Плодить костыли для исправления якобы багов это куда хуже запретов

**Comment by SunSerega** [comment]
Если у вас сейчас хватит времени и сил только на костыли - лучше вообще ничего не трогать.
Запрет этот тоже костыль, только ещё более ленивый, чем костыли с которыми хоть как то работает.

**Comment by miks1965** [comment]
Значит, давайте не называть это костылями. Потому что вы потом пойдёте на всякие форумы и будете всем рассказывать, что у нас всё на костылях. Это очень неприятно.

Это стройность языка. Возможно, это излишние ограничения. Но если они просто формулируются и запоминаются - это не костыли. Многие языки имеют ограничения.

Ещё раз формулирую ограничение и причину.

Ограничение мы сделаем такое: мы запретим предописание класса если в описании другого класса этот класс будет использован как предок или в ограничении where.

Причина проста: в Delphi предописание классов используется крайне ограниченно (почитайте на досуге эти правила)

В частности, в Delphi не работает такой код 
```
program Project1;

type
  A = class;
  B = class(A)

  end;
  A = class

  end;

begin
end.  
```
с ошибкой 
![изображение](https://user-images.githubusercontent.com/10325391/82302726-ab9b2c80-99c2-11ea-966d-96e23dd98666.png)

**Comment by SunSerega** [comment]
> потом пойдёте на всякие форумы и будете всем рассказывать, что у нас всё на костылях

Это уже на ptsd походит)) Не все делают первое что придёт в голову.

В данном случае я борюсь за язык в котором не будет запретов потому что "мы не хотим это реализовывать".
Или, тем более, как в случае заголовка этой issue - потому что 1 очень редкая ситуация с фичей даёт странную ошибку.

Поэтому и писать на старых заборах вроде куберфорума мне нет смысла. Смысл есть говорить это напрямую тем, кто собственно этими фичами занимается.
Или, по крайней мере, я на это надеюсь. Хотя от "не нравится - пишите код нашего проекта за нас" (в случае с `IntPtr` на форуме) эта надежда немного да пошатнулась...

---
По теме:

> Это стройность языка. Возможно, это излишние ограничения. Но если они просто формулируются и запоминаются - это не костыли. Многие языки имеют ограничения.

Из [вики](https://ru.wikipedia.org/wiki/Костыль_(значения))

> Костыль — в программировании, быстрое "уродливое" решение проблемы, иначе требующей долгогосрочного и ресурсоемкого исправления.

Нормально видеть что в определённый момент нет ресурсов на реализацию фичи и поэтому делать затычки. Но:

1. То что в других языках есть затычки - не делают их безответственное добавление оправданным.
Правильно взвешивать не только то, на сколько вам трудно или не хочется, а так же все возможные последствия запрета.

2. Только когда уже собираетесь отправлять язык "на пенсию" - имеет смысл делать затычки "лишь бы юзверям не показывало странные ошибки".
В остальных случаях, если вам так уж не нравится какую показывает ошибку - можно запретить конкретный случай дающий эту ошибку, выдавая "это + это + это пока не работает".  И только временно, оставляя issue чтоб в итоге не забыть когда то всё же реализовать.

3. Теперь к наследованию от предописанных классов. Я и не говорил про него, это ibond привёл в пример. Но теперь, для, пожалуй, самого важного из 3 пунктов - очень кстати:

> если они просто формулируются и запоминаются

Нет, конечному пользователю это вообще не важно.
Важно только как легко будет придумать способы обхода этого ограничения в разных случаях. Это потому, что узнать об ограничении придётся 1 раз, а обходить - много.
И раз вы целитесь на язык в котором удобно писать по-простому - про это тем более нельзя забывать.

Запрет наследования предописанных классов легко обходить: Цепочка наследования всегда идёт в 1 сторону.
В качестве бонуса - этот запрет наставляет на более чёткий порядок следования классов. Хорошо это или плохо - дело вкуса.
Но в старых традициях паскаля - выстрелить себе в ногу получается таки сложнее.

С другой стороны, когда обходить затычку не просто сложно, а невозможно (для некоторого давно работающего кода + ещё бОльшего кол-ва потенциальных паттернов) - это никогда того не стоит.
Особенно ради того чтоб заткнуть 1 странную ошибку...

**Comment by miks1965** [comment]
Ещё раз по поводу ограничений. 

То, что этот код компилируется, - простой наш недосмотр. В линейке языков Delphi это не работает.

```
program Project1;

type
  A = class;
  B = class(A)

  end;
  A = class

  end;

begin
end. 
```

Мы не затыкаем странную ошибку. Мы приводим наш язык к стандарту Delphi. И странно, что мы натыкаемся на такую агрессивную критику с фразами "костыль", "затычки", "безответственное добавление".

Вы боретесь за другой язык - мы это понимаем. 

Паттерны использования этого мы тоже понимаем, но в разных языках - резные паттерны. К примеру, в C++ можно вообще всё делать с параметрами шаблонов, и это удобно. Но это - другой язык.

По поводу безответственного поведения. Я не называю ваше поведение таким, но обратите внимание, что когда вы пишете на нашем форуме или на киберфоруме про компьютерную графику, вы всячески принижаете возможности графических библиотек PascalABC.NET, говоря об их неэффективности. Это не так. Их область применения - не для быстрой графики. И их надо применять вместо того чтобы писать большой код на C# для визуализации чего-то там. А вы некоторыми утверждениями разрушаете то, что мы делали годами. Это странно.

**Comment by SunSerega** [comment]
> То, что этот код компилируется, - простой наш недосмотр

А он компилируется? У меня нет.

И ещё раз, я и не говорю что его есть смысл разрешать. Речь шла только про запрет этого кода:
```
type
  t0<T> = class end;
  
  A = class;
  B = class(t0<A>)
    
  end;
  A = class
    
  end;
  
begin end.
```

**Comment by miks1965** [comment]
Да, запретим. Разумеется. Там предописанный класс используется в предке.

**Comment by miks1965** [comment]
SunSerega - вам надо посмотреть, как я поправил OpenCLABC и немного причесать

**Comment by SunSerega** [comment]
С `OpenCLABC` я всё ещё жду пока вы придумаете "нормальную замену partial классам". А так - там уже всё равно много переписано и перефасовано.

В старой версии нет смысла править если вы ничего не ломали, а только местами меняли.
