### ISSUE TITLE
Разрешить имя пространства в качестве имени типа

### ISSUE THREAD

**Issue by AIexandrKotov** [pascalabcnet/pascalabcnet#2141]
Re: #1977

```
program NS;

type
  NS = class end;
  
begin
  
end.
```

Это сейчас не компилируется:
```
Program3.pas(4) : Повторно объявленный идентификатор NS
```

В программах это должно работать, потому что у программ имя базового класса — Program. В библиотеках должно только если не определены нигде глобальные переменные, процедуры и функции.

В модулях пространства имён запрещены, так что с ними это работать не обязано.

**Comment by miks1965** [comment]
Это - повторно объявленный идентификатор. 

Странные просьбы - разрешить повторно объявлять идентификатор.

**Comment by AIexandrKotov** [comment]
Этот код эквивалентен:

```c#
namespace NS
{
    class NS
    {

    }

    class Program
    {
        //$Main и прочие
    }
}
```

В пространствах имён МОГУТ содержаться типы, которые имеют имя пространства имён. В PascalABC.NET на таком принципе работают модули! И я думаю, что просто забыли убрать проверку на совпадение для пространств имён.

**Comment by AIexandrKotov** [comment]
В случае библиотеки без глобальных имён, генерируется класс с именем библиотеки:

```
  [$GlobAttr]
  public class Program3
  {
    static Program3()
    {
      PABCSystem.PABCSystem.$_Init_();
    }
  }
```

Однако, этот класс по сути не нужен, ибо он пустой. Инициализацию PABCSystem вообще надо перенести в статический конструктор самого PABCSystem.

**Comment by miks1965** [comment]
Нет, нам именно такое поведение нужно в нескольких местах. В частности, для работы задачника. Там PABCSystem.PABCSystem.$_Init_(); помнится мне вызывается явно несколько раз

**Comment by AIexandrKotov** [comment]
Ладно, тогда остаётся изначальный код, который в шапке issue, который должен работать. program меняет имя пространства имён, класса же NS.NS не существует, так что ничего не мешает это разрешить.

**Comment by miks1965** [comment]
В Delphi это не работает:
```
program Project1;

var Project1: integer;

begin
end.

```

**Comment by AIexandrKotov** [comment]
Ну, ещё +одна причина, по которой я никогда не буду работать с Delphi))

У вас платформа .NET. Так что в синтаксисе определения имён стоит ориентироваться именно на .NET.

А по сути: 
```
program Program4;

type
  T = class end;

begin
  
end.
```

Развернётся в:
```
namespace Program4
{
  [$GlobAttr]
  public class Program4
  {
    public static bool $is_init;

    public static void $Main()
    {
    }

    public static void $_Init_()
    {
      if (Program4.Program4.$is_init)
        return;
      Program4.Program4.$is_init = true;
      PABCSystem.PABCSystem.IsConsoleApplication = true;
      PABCSystem.PABCSystem.__CONFIG__.Add("locale", (object) "ru");
      PABCSystem.PABCSystem.__CONFIG__.Add("full_locale", (object) "ru-RU");
      PABCSystem_implementation______.PABCSystem_implementation______.$Initialization();
      PABCExtensions_implementation______.PABCExtensions_implementation______.$Initialization();
      __RunMode_implementation______.__RunMode_implementation______.$Initialization();
    }

    public static void $_InitVariables_()
    {
    }
  }

  public class Program
  {
    public static void Main()
    {
      Program4.Program4.$_Init_();
      Program4.Program4.$_InitVariables_();
      Program4.Program4.$Main();
      PABCSystem_implementation______.PABCSystem_implementation______.$Finalization();
    }
  }

  public class T
  {
    public void $Init$()
    {
    }

    public T()
    {
      this.$Init$();
    }
  }
}
```

Ага, теперь я понял... А в чём вообще смысл в том что так сделано? Ведь всё что есть в классе Program4.Program4 можно запросто перенести в класс Program. Так и так имя Program давным давно запрещено как имя типа.

**Comment by miks1965** [comment]
То, во что это разворачивается, - это внутренняя реализация. Это необязательно так может реализовываться.

А правила языка, на который мы опираемся, - это правила языка.
