### ISSUE TITLE
В dll не видит классы, не вложенные в пространство имён

### ISSUE THREAD

**Issue by GlebBrykin** [pascalabcnet/pascalabcnet#2143]
Если скомпилировать следующую простую библиотеку на C#:

```C#
using System;

public static class Lib
{

    public static void CallMe()
    {
        Console.WriteLine("Hello, World!");
    }

}
```

После чего попытаться из Паскаля обратиться к классу Lib, то выводится ошибка, что не найдено имя Lib.

```Pascal
{$Reference 'Lib.dll'}
begin
    Lib.CallMe(); // Здесь ошибка.
end.
```

**Comment by SunSerega** [comment]
Я так понимаю, это потому что компилятор путает пространство имён Lib и класс Lib. Стоит отдавать приоритет классу, а затем так же проверять и пространство имён.

**Comment by GlebBrykin** [comment]
Нет. Пространства имён в самой библиотеке нет. В корне лежит класс Lib, без каких-либо оболочек.

**Comment by miks1965** [comment]
Понятно. Это из-за отсутствия пространства имён.
