### ISSUE TITLE
.dll-ки копирует в папку с исходником, даже если .exe создаёт в другой папке

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#2144]
http://forum.mmcs.sfedu.ru/t/topic/143/1539?u=sun_serega

Несколько месяцев назад был спор о том - что делать с .dll, подключённым по $reference но лежащим не в папке куда генерирует .exe . Проблема с этом в том, что .exe не запускается если в папке с ним нету .dll .

Тогда вы решили что надо копировать .dll в папку с .exe при компиляции. И правильно, студия тоже так делает.

Но при этом не предусмотрели опцию "Выходные файлы генерировать в директорию" (которая у студии, по сути, вообще всегда включена). А стоит предусмотреть. И фикс должен быть не сложным, 1-2 строчки.

**Comment by miks1965** [comment]
Если стоит опция "Выходные файлы генерировать в директорию" , то exe создаётся там, а dll не копируется, и программа падает при запуске
