### ISSUE TITLE
Внутренняя ошибка при обращении к extension-операции, если она не описана

### ISSUE THREAD

**Issue by AIexandrKotov** [pascalabcnet/pascalabcnet#2153]
```
begin 
  var (a, b) := (1, 2);
  a.operator+=(a, b).Print;
end.
```
```
Внутренняя ошибка компилятора в модуле [pabcnetc.exe] :'System.Exception: Compile internal error: Invalid method kind'
```

Исправляется добавлением в начале:
```
function operator+=(a: integer; b: integer): integer; extensionmethod := a + b;
```

Нужно проверять существование функции-операции. И, прошу вас, не запрещайте обращение в виде .operator+=().

**Comment by miks1965** [comment]
Все операции определяются как классовые функции. А Вы вызываете через объект

**Comment by SunSerega** [comment]
Ну в целом да, правильно статичный вызов делать. Вот только
1. Внутренней ошибки всё равно быть не должно. Именно о ней эта issue, исходя из заголовка.
2. Статичный вызов тоже падает, только по другому, во время выполнения:
```
begin 
  var (a, b) := (1, 2);
  integer.operator+=(a, b).Print;
end.
```
```
Ошибка времени выполнения: System.InvalidProgramException: Среда выполнения Common Language Runtime обнаружила недопустимую программу.
Стек:
   в 0.Program.$Main()
   в 0.Program.Main()
```
Стоит делать новую issue? По моему это всё можно считать одним багом.
