### ISSUE TITLE
Запретить операцию * на число для множеств

### ISSUE THREAD

**Issue by miks1965** [pascalabcnet/pascalabcnet#2157]
```
begin
  var h := HSet(1,3,5,7,9);
  Print(h * 2);
end.
```
Неожиданно
[1,3,5,7,9,1,3,5,7,9] 

Надо не определять умножение на число для последовательностей - это приводит к вот таким последствиям

**Comment by AIexandrKotov** [comment]
fixed in https://github.com/pascalabcnet/pascalabcnet/commit/1aeb653f85623634b0e84a61e06a1227cb34a042
Закрывайте issue.
