### ISSUE TITLE
Undefined FileName при описании лямбды, тип параметра которой находится в пространстве имён

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#2168]
```
uses u;

begin
  var cb: DT1 := i->exit();
end.
```
```
unit u;

type
  DT1 = procedure(i: System.IntPtr);
  
end.
```
`Undefined FileName(0) : Неизвестное имя 'IntPtr'`
[0.zip](https://github.com/pascalabcnet/pascalabcnet/files/4017526/0.zip)

Надо описывать тип параметра лямбды как `System.IntPtr` а не `IntPtr`.

**Comment by miks1965** [comment]
Так тоже не работает:
```
type
  DT1 = procedure(i: System.IntPtr);

begin
  var cb: DT1 := i->exit();
end.
```

**Comment by miks1965** [comment]
```
begin
  var cb: PInteger -> ();
  cb := i->exit();
end.
```
А тут вот что получаем: 
IntPtr.pas(5) : Тип-указатель не может выступать в качестве параметра управляемого шаблона

**Comment by miks1965** [comment]
Собственно, и это также падает: 
```
begin
  var cb: System.Action<System.IntPtr>;
  cb := i->exit();
end.
```
Undefined FileName(0) : Неизвестное имя 'IntPtr'

**Comment by miks1965** [comment]
Виноват ConvertSemanticTypeToSyntaxType - съедает System для IntPtr
