### ISSUE TITLE
pabcnetcclear.exe съедает ошибку отсутствия файла ресурса

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#2171]
```
{$resource 'не существующий файл'}

begin end.
```
Если откомпилировать это с "pabcnetcclear.exe" - пишет OK, но .exe не создаёт.

**Comment by miks1965** [comment]
А pabcnetc.exe создаёт?

**Comment by SunSerega** [comment]
Нет, `pabcnetc.exe` делает всё правильно: Даёт ошибку "Файл {file_name} не найден".
```
[0][1,3] 0.pas: Resource file 'не существующий файл' not found
```

**Comment by miks1965** [comment]
Мы предназначали pabcnetclear.exe для олимпиад, где всё минимальное только оставлено. С этой точки зрения не знаю, является ли это ошибкой.

**Comment by SunSerega** [comment]
Какая разница, минимум или нет. Если при компиляции возникла ошибка - `pabcnetclear.exe` должен написать хотя бы `ERROR` вместо `OK`. Он часто не пишет конкретный текст ошибки, но если в выводе не появляется `ERROR` - программа вызвавшая его будет считать что компиляция прошла успешно.

**Comment by miks1965** [comment]
Думаю, Вам самому надо посмотреть эту ошибку

**Comment by SunSerega** [comment]
`Compiler.cs` строка `1998`:
```
                            ErrorsList.Add(new ResourceFileNotFound(cd.directive, cd.location));
```
`pabcnetclear.exe` просто игнорирует эту ошибку. Если заменить на:
```
                            throw new ResourceFileNotFound(cd.directive, cd.location);
```
То всё работает как ожидалось. А ещё компилятор не продолжает компилировать программу, не смотря на то что она неправильная.

Хотя по моему стоит ещё разобраться почему это вдруг `pabcnetclear.exe` игнорирует ошибки и не пришет даже просто "ERROR".

**Comment by miks1965** [comment]
А только ли в этом случае он игнорирует?

**Comment by ibond84** [comment]
Ошибка уже давно выводится
