### ISSUE TITLE
Неверное количество параметров функции при вызове метода расширения внутри наследника класса не через self

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#2180]
```
type
  t1 = class end;
  
function f1(self: t1; x: integer): integer; extensionmethod;
begin
  Writeln(self);
  Result := x.Println;
end;

type
  t2 = class(t1)
    procedure test;
    begin
      writeln(f1(4));
      writeln(self.f1(4)); // так работает
    end;
  end;

begin
end.
```

**Comment by SunSerega** [comment]
@ibond84 а разве можно вызывать через `self`? `self` при инициализации полей вообще не видит.

**Comment by ibond84** [comment]
Инициализаторы полей здесь непричем. Здесь не работает вызов метод расширения без self.

**Comment by miks1965** [comment]
У нас методы расширения вызываются только через переменную. Считайте это особенностью языка.

**Comment by SunSerega** [comment]
Ну ошибка всё равно неправильная. Надо давать что то типа "неизвестное имя", раз `f1` не должно быть видно.

**Comment by SunSerega** [comment]
И вообще, это @ibond84 так код изменил. Мой изначальный код не выглядит как будто это должно работать:
```
type
  t1 = class end;
  
function f1(self: t1; x: integer): integer; extensionmethod;
begin
  Writeln(self);
  Result := x.Println;
end;

type
  t2 = class(t1)
//    n1 := f1(5); //Ошибка: Неверное количество параметров функции
    n2 := f1(nil, 5); // работает, хотя не должно
  end;

begin
  new t2; // выводит nil и 5
end.
```
Он как раз показывает что неправильная ошибка при `f1(5)` + то что `f1(nil, 5)` не должно работать.

**Comment by miks1965** [comment]
Переоткрыл
