### ISSUE TITLE
Операторы как :=, += и т.п. не ожидает в лямбде, начинающейся с "()->"

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#2181]
```
begin
  var x := 0;
  var p1: ()->() := procedure->x := 1; // работает
  var p2: ()->() := ()->loop 1 do x := 1; // работает
  var p3: ()->() := ()->x := 2; //Ошибка: Встречено ':=', а ожидалось ';'
end.
```
Вы уже давно утвердили, что `:=` это оператор и никогда не выражение.
А значит имеет смысл при встрече в лямбде `:=`, `+=` и т.п. - автоматически считать её лямбдой-процедурой. Так же как при встрече, к примеру, `loop`.

**Comment by miks1965** [comment]
По той же причине - неоднозначности в грамматике. Мы бы и рады были это разрешить, но увы.
