### ISSUE TITLE
if в корне лямбды перестало считать оператором

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#2183]
```
begin
  var x := 0;
  var p1: ()->() := ()->Writeln(); // работает
  var p2: ()->() := ()->loop 1 do if true then Writeln() else Writeln(); // работает
  var p3: ()->() := ()->if true then Writeln(); //Ошибка: Встречено ';', а ожидалось else
  var p4: ()->() := ()->if true then Writeln() else Writeln(); //Ошибка: Невозможно преобразовать функциональный тип в процедурный тип
end.
```
Ещё недавно это работало. Я так понимаю, это из за синтаксиса выражений, где вместо `?:` - `if-then-else`.

Надо в корне лямбды:
- Или в первую очередь ожидать `if` который оператор.
- Или, **что лучше но сложнее**, сначала определять может ли быть `if` оператором по содержимому.\
То есть если хотя бы 1 ветка `if` является не выражением а оператором - делать весь `if` оператором.

Ну и что касается `p3` - если у `if` нету `else` то это 100% оператор, без дополнительных проверок. Это вообще исправляется отдельно от этой issue, но отдельную под это создавать - как то странно.

**Comment by miks1965** [comment]
if - оператор конкурировал В ГРАММАТИКЕ с if-выражением.
Нет никакой возможности на уровне грамматики определять, это выражение или оператор. Типы тут еще не работают.

**Comment by SunSerega** [comment]
> Нет никакой возможности на уровне грамматики определять

Я же говорю, это и не надо определять на уровне грамматики. На уровне грамматики надо разрешать и выражение и оператор. Или отсеять потом тоже проблематично?

> А это вы на какой версии пробуете?

Воспроизводилось на последней версии когда писал.
Сейчас в последней попробовал не воспроизводится.
Но зато снова перестало работать так:
```
begin
  var x := 0;
  var f1: ()->integer := ()->if true then x else x;
end.
```
То есть, похоже, вы сделали так, чтоб в лямбде ожидало только `if`-оператор, но не `if`-выражение.

**Comment by miks1965** [comment]
так и есть. Мы запретили в лямбдах if-выражение на верхнем уровне. Для желающих есть ? :
