### ISSUE TITLE
Считает класс абстрактным, если наследовать от типа в другом модуле, с приватной виртуальной цепочкой

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#2184]
```
uses u1;

type
  
  // обязательно t3 - тип из другого модуля
  //Ошибка: Абстрактный класс не может иметь атрибут sealed
  t4 = sealed class(t3) end;
  
begin
  Writeln('test');
end.
```
```
unit u1;

type
  
  t1 = abstract class
    // обязательно видимость private
    private function f1: byte; abstract;
  end;
  t2 = class(t1)
    private function f1: byte; override := 0;
  end;
  
  // обязательно ещё 1 промежуточный тип между t2 и t4
  t3 = class(t2) end;
  
end.
```
[0.zip](https://github.com/pascalabcnet/pascalabcnet/files/4075169/0.zip)

Самое интересное - если сделать программу активной и запускать модуль, программа компилируется и запускается успешно.

**Comment by ibond84** [comment]
Ну, это упущение. Абстрактные приватные методы надо запретить от греха подальше.

**Comment by ibond84** [comment]
Все абстрактные методы должны быть видны из всех наследников

**Comment by SunSerega** [comment]
Не запрещайте, пожалуйста. Это позволяет сделать `f1` невидимой из `t4`, что очень полезно.

**Comment by ibond84** [comment]
Непонятно, чем это может быть полезно. Хотите что-то скрывать - выделяйте интерфейсы.

**Comment by SunSerega** [comment]
В интерфейсах не бывает реализации, поэтому это не подходит:
```
  t1 = abstract class
    // обязательно видимость private
    private function f1: byte; abstract;
    
    public procedure p1;
    begin
      // какой то общий публичный функционал
      Writeln(f1);
    end;
    
  end;
```
Кроме того, скрывать реализацию интерфейсов невозможно, потому что у вас запрещены все модификаторы доступа кроме `public` для элементов интерфейса.

**Comment by ibond84** [comment]
На самом деле этот "баг" можно рассматривать как фичу. Абстрактный класс с приватными абстрактными методами можно использовать (точнее создавать неабстрактные наследники) только в модуле.

**Comment by SunSerega** [comment]
Нет, это не правильно. Если наследники должно быть можно создавать только в модуле - все конструкторы должны быть видны только из этих модулей.

А этот баг делает невозможным некоторый код с виртуальными цепочками.

Ну и кроме того, каждый желающий может наследовать от `t2` вместо `t3`. Если `t3` находится в разделе интерфейса - то `t2` тоже.

**Comment by SunSerega** [comment]
Насчёт редко встречается...
```
{$reference PresentationFramework.dll}
uses System.Windows.Controls;

type
  //Ошибка: Класс MyTextBox абстрактный и не может иметь атрибут sealed, потому что метод CreateRenderScope не реализован
  MyTextBox = sealed class(RichTextBox)
    
  end;
  
begin end.
```
