### ISSUE TITLE
Беззвучный вылет при чтении o.a, где "o=nil" и "a: BigInteger"

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#2188]
```
type
  t1 = class
    a: BigInteger;
    
    procedure p1(o: t1);
    begin
      self.a := o.a;
    end;
    
  end;
  
begin
  var a := new t1;
  a.p1(nil);
end.
```
При запуске эта программа не пишет никакой ошибки, но через пару секунд появляется окно "прекращение работы программы".

Я не нашёл ничего неправильного в IL. А на случай если это что то плавающее:
![image](https://user-images.githubusercontent.com/27270190/73187910-ce12ec80-412a-11ea-9640-83896102cda2.png)

**Comment by miks1965** [comment]
![изображение](https://user-images.githubusercontent.com/10325391/73331007-7c29ae00-4273-11ea-85df-506db015fbba.png)
Всё работает. У вас антивирус наверное срабатывает

**Comment by SunSerega** [comment]
У меня нет антивируса. И так работает только с BigInteger.

**Comment by SunSerega** [comment]
Со своей записью, похожей на `BigInteger` тоже выдаёт нормальную ошибку, кстати:
```
type
  r1 = record
    i: array of integer;
  end;
  
  t1 = class
    a: r1;
    
    procedure p1(o: t1);
    begin
      self.a := o.a;
    end;
    
  end;
  
begin
  var a := new t1;
  a.p1(nil);
end.
```
Вылет именно на `BigInteger`.

Переоткройте, пожалуйста, issue и приложите хотя бы .exe с которым у вас не вылетает.

У меня вылетает с этим: [0.zip](https://github.com/pascalabcnet/pascalabcnet/files/4126564/0.zip)

**Comment by miks1965** [comment]
![изображение](https://user-images.githubusercontent.com/10325391/73347485-ba859400-4298-11ea-8e8f-4020e26a959c.png)
Запустил ваш exe

**Comment by miks1965** [comment]
Переоткрывать не буду - всё работает
