### ISSUE TITLE
Ошибка при extensionmethod-е в uses-in модуле

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#2189]
[0.zip](https://github.com/pascalabcnet/pascalabcnet/files/4124764/0.zip)

```
// обязательно подключать сначала uiu, а потом u
uses uiu in '..\uiu.pas';
uses u;

begin end.
```
```
unit u;

uses uiu in '..\uiu.pas';

end.
```
```
unit uiu;

function f1(self: byte): word; extensionmethod := 0;

end.
```
Без `uses-in` не воспроизводится.

Для воспроизведения надо сделать активным файл программы и запустить файл `u.pas`.

**Comment by ibond84** [comment]
У меня возникает только одна правильная ошибка: Невозможно запустить модуль. Прошу не лениться и уточнять, какая именно ошибка возникает

**Comment by SunSerega** [comment]
> Для воспроизведения **надо сделать активным файл программы** и запустить файл u.pas.

Прошу читать полностью, а не бегло первое что бросается в глаза.

И `ПКМ по файлу и "сделать активным"` уже далеко не первый раз позволяет стабильно воспроизводить плавающие ошибки.

**Comment by ibond84** [comment]
Не воспроизводится

**Comment by SunSerega** [comment]
![image](https://user-images.githubusercontent.com/27270190/74103458-c3a61900-4b54-11ea-985b-6a9776eb8936.png)

Версия последняя.

**Comment by SunSerega** [comment]
Запускать надо именно `u` а не `uiu`, если что.

**Comment by SunSerega** [comment]
Ну так чего игнорите то? И если не разобрались - чего закрывать сразу?
