### ISSUE TITLE
Не захватывается локальное  имя типа в yield

### ISSUE THREAD

**Issue by miks1965** [pascalabcnet/pascalabcnet#219]
```
function f(): sequence of integer;
type T = integer;
begin
  var t2: T := 1;
  yield t2;
end;

begin
end.  
```

**Comment by ibond84** [comment]
Странно, изменил немного PABCSystem.pas. yield-ов в нем нет, но выбрасывается исключение:
Внутренняя ошибка компилятора в модуле Compiler.Compile[Compiler] :'System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei YieldDesugarSyntaxTreeConverter.YieldDesugarSyntaxTreeConverter.Convert(syntax_tree_node root)

**Comment by ibond84** [comment]
А, это какая-то наведенная ошибка.

**Comment by miks1965** [comment]
Это прикольная ошибка - захват имени типа непонятно как делать. Локальная переменная t2 преобразуется в поле класса, а вот тип этого поля - T, и где описывать T - неясно - в классе описаний типов нет.

**Comment by miks1965** [comment]
Думаю, надо запретить локальные определения типов в функциях с yieldами. Жуть.
