### ISSUE TITLE
Шаблонное наследование от "c1<T> = class where T: c1<T>" не работает

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#2193]
```
type
  
  c1<T1> = class where T1: c1<T1>;
    
  end;
  
  //Ошибка: Несоответствие спецификатора whеre спецификатору where базового класса
  c2<T2> = class(c1<T2>) where T2: c1<T2>;
    
  end;
  
begin end.
```
Как продолжение #2191, но ошибка совсем другая, и по-другому исправляется.

**Comment by SunSerega** [comment]
Насчёт правильности кода, потому что это может быть довольно запутано:

Я специально сделал разные имена шаблонным параметрам в `c1` и `c2`, чтоб было легче понять и объяснить.

`c2` наследует от `c1<x>`. Значит по ограничению `c1` - вместо `x` надо передать класс, наследующий от `c1<x>`.

В качестве `x` передали `T2`. Значит `T2` должен наследовать от `c1<T2>`.

> `T2` должен наследовать от `c1<T2>`

Это ограничение записано в виде второго `where`, значит весь код правильный.

**Comment by miks1965** [comment]
Да, понятно. Это сложное для реализации улучшение.

**Comment by SunSerega** [comment]
Ну, шаблонное наследование это только дополнительное что я протестировал.
Мне самому хотя бы обычное, то есть #2191. А то и костыль не сделаешь...

**Comment by ibond84** [comment]
> Да, понятно. Это сложное для реализации улучшение.

И главное, где это вообще может пригодиться...

**Comment by SunSerega** [comment]
Я уже давал пример, в #2190. Там же и такое было бы надо. Вот только я немного изменил базовую архитектуру, что сделало ` c2<T2> = class(c1<T2>) where T2: c1<T2>` не нужным лично для моего проекта. Но в похожих ситуациях эта конструкция остаётся нужной.

**Comment by ibond84** [comment]
https://github.com/pascalabcnet/pascalabcnet/actions/runs/468684058
