### ISSUE TITLE
Компилятор не заставляет вызвать конструктор предка, при наследовании через 1 класс

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#2194]
```
uses u;

type
  t2 = class(t1)
    
  end;
  t3 = class(t2)
    
     // Неправильно, потому что конструктор t1 никак не вызван
     // Но при этом ошибка не выдаётся
    constructor := exit;
    
  end;
  
begin
  new t3;
end.
```
```
unit u;

type
  t1 = class
    
    public constructor(b: byte) :=
    Writeln($'Инициализация t1 с {b}');
    
    // Даже если добавить приватный конструктор - его всё равно вызовет
    // Вместо ошибки о том, что надо вызвать публичный конструктор
//    private constructor := raise new System.NotImplementedException;
    
  end;
  
end.
```
[0.zip](https://github.com/pascalabcnet/pascalabcnet/files/4130169/0.zip)

Раз в `t2` нет конструкторов - значит они унаследованы от `t1`.

Поэтому то что в `t3` можно описать конструктор, не вызывающий `inherited Create(byte(...))` - неправильно.

**Comment by miks1965** [comment]
Не понятно, что вы тут написали. В Object Pascal необязательно вызывать в потомке конструктор предка. 

Поясните чётко простыми словами, что вы имеете в виду

**Comment by SunSerega** [comment]
> В Object Pascal необязательно

А в .Net обязательно. Это важнее.

Если убрать `t2` как промежуточный класс - выдаётся ожидаемая ошибка:
```
uses u;

type
  t3 = class(t1)
    
    //Ошибка: Необходимо вызвать конструктор предка
    constructor := exit;
    
  end;
  
begin
  new t3;
end.
```
```
unit u;

type
  t1 = class
    
    public constructor(b: byte) :=
    Writeln($'Инициализация t1 с {b}');
    
    private constructor := raise new System.NotImplementedException;
    
  end;
  
end.
```
Это правильно в .Net поведение, если нет конструктора предка без параметра - надо явно вызывать другой конструктор предка.

Ну а то что есть конструкторов нет - они наследуются от предка, это то что вы сами говорили. Вроде из дельфи взято.

**Comment by miks1965** [comment]
Там у нас для каждого класса генерится конструктор по умолчанию и вызывается в потомке если не вызван другой

**Comment by SunSerega** [comment]
И вот это неправильно, потому что неравномерно и небезопасно. В .Net всегда должен быть вызван конструктор предка, без обходных путей в виде промежуточного пустого класса.

Наследование конструкторов действительно существует:
```
uses u;

begin
  //Ошибка: Неверное число параметров
  new t2;
end.
```
```
unit u;

type
  t1 = class
    
    public constructor(b: byte) := exit;
    private constructor := exit;
    
  end;
  
  t2 = class(t1) end;
  
end.
```
Это правильная абсолютно ошибка.

При наследовании через 1 класс - тоже должно так же работать, чтоб всюду работало равномерно.

**Comment by miks1965** [comment]
А почему вы всё время пишете с модулем? Без модуля это поведение не воспроизводится?

**Comment by SunSerega** [comment]
Без модуля `private` не работает.

**Comment by miks1965** [comment]
Понятно. 
Тут - сложно. В первом примере, который вы приводили, есть две ситуации. Первая - конструкторов в модуле вообще нет. Тогда генерируются конструкторы по умолчанию - и всё работает. Я уже говорил, что у нас это - правильное поведение. 

Если в самом базовом классе добавить приватный конструктор по умолчанию, то происходит следующее. В классе t2 генерируется тоже приватный (!) конструктор по умолчанию. Он вызывает приватный конструктор по умолчанию предка из другого модуля.

Теперь самая главная тонкость. Класс t3 находится в том же модуле, что и t2. Поэтому для него приватный конструктор виден (!). Он и вызывается в явно описанном конструкторе t3.

Запрещать это мы не будем. Это логичное поведение где-то на задворках - специально такой код писать очень странно. Можно спорить и предлагать какие-то другие варианты логичного поведения. Но мы оставим этот - потому что он - на задворках.
