### ISSUE TITLE
Undefined FileName при вызове конструктора предка из конструктора параметрами, когда у предка есть пустой приватный конструктор

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#2195]
```
uses u;

type
  t2 = class(t1)
    
    // обязательно конструктор с параметрами в t2
    constructor(b: string) :=
    inherited Create(0);
    
  end;
  
begin end.
```
```
unit u;

type
  t1 = class
    
    public constructor(b: byte) :=
    Writeln($'Инициализация t1 с {b}');
    
    // обязательно пустой приватный конструктор
    private constructor :=
    raise new System.NotImplementedException;
    
  end;

end.
```
[0.zip](https://github.com/pascalabcnet/pascalabcnet/files/4130507/0.zip)

`Undefined FileName(0) : Необходимо вызвать конструктор предка`

**Comment by miks1965** [comment]
Undefined filename мы уберем. Но сообщение об ошибке правильное. 

В .NET всегда конструктор потомка вызывает конструктор предка. В Object Pascal это необязательно, поэтому мы вынуждены генерировать конструктор у каждого класса без параметров. Именно он и вызывается у потомка. Если его явно написали вы - он не генерируется. Но разумеется пытается вызваться. А его не видно, поскольку он private/ поэтому компилятор и просит вызвать хотя б какой-то

**Comment by miks1965** [comment]
У вас в t2 не определен конструктор по умолчанию. Он генерируется автоматически и вызывает конструктор по умолчанию предка. Но вы его спрятали - потому и ошибка

**Comment by SunSerega** [comment]
Публичный конструктор по-умолчанию имеет смысл генерировать только тогда, когда нет других конструкторов.

Если все типы можно создавать из воздуха (без параметров) - это минус половина безопасности ООП.
`raise new System.NotImplementedException`, конечно, тоже работает. Но тогда, получается что нет проверки на этапе компиляции, что всегда плохо.

И на практике - если программист описывает свои конструкторы - значит конструкторы по-умолчанию ему не нужны (по крайней мере вне класса).

**Comment by miks1965** [comment]
Не апеллируйте к опыту C# и других языков. В PascalABC.NET сделано по-другому. Это другая концепция. Не говорите, как по-вашему надо было бы сделать если бы делать язык с нуля. Потеряете время. 

В вашем Issue - единственная проблема - в том, что сгенерированный конструктор по умолчанию для потомка берется из воздуха, и вызываемый в нём автоматически сгенерированный вызов конструктора по умолчанию предка вызван быть не может, потому что вы его спрятали. Проблема только в том чтобы доходчиво это сказать.

В PascalABC.NET - плохое проектирование - это делать приватный конструктор по умолчанию у предка. Но даже это можно побороть если у всех потомков явно определять конструктор по умолчанию. Но вы этого не делаете.

Поэтому ваш пример - это ошибочное проектирование и ошибочное апеллирование к объектной модели других языков. Наша проблема - плохое сообщение об ошибке да еще и с потерей контекста.

**Comment by miks1965** [comment]
Предложение по ошибке - такое. 

В автоматически сгенерированном конструкторе по умолчанию невозможно вызвать конструктор по умолчанию предка

**Comment by miks1965** [comment]
Необходимо иметь в виду, что у нас все private-методы транслируются в internal-методы, а модификатор private проверяется на уровне компилятора. Это никакого особенного значения не имеет - всё равно такими методами нельзя пользоваться за пределами сборки - просто как деталь.
