### ISSUE TITLE
Undefined FileName при захвате Result лямбдой

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#2204]
```
function f1: byte;
begin
  
  var p: ()->() := ()->
  begin
    Result := 0;
  end;
  
end;

begin end.
```
`Undefined FileName(0) : Неизвестное имя '$rv_f1'`

Разумеется, `Result`, в первую очередь не должен быть виден.

Ну и, по моему, это уже исправлялось. Добавьте, пожалуйста, тесты.

**Comment by miks1965** [comment]
Запретить захватывать переменную Result
