### ISSUE TITLE
"sizeof(IntPtr)" падает

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#2205]
```
begin
  var sz := sizeof(System.IntPtr);
end.
```
```
() : Внутренняя ошибка компилятора в модуле [pabcnetc.exe] :'System.Exception: System.NullReferenceException: Ссылка на объект не указывает на экземпляр объекта.
   в PascalABCCompiler.NETGenerator.TypeFactory.GetPrimitiveTypeSize(Type PrimitiveType)
   в PascalABCCompiler.NETGenerator.ILConverter.visit(ISizeOfOperator value)
   в PascalABCCompiler.NETGenerator.ILConverter.AssignToLocalVariableNode(IExpressionNode to, IExpressionNode from)
   в PascalABCCompiler.NETGenerator.ILConverter.ConvertStatement(IStatementNode value)
   в PascalABCCompiler.NETGenerator.ILConverter.visit(IStatementsListNode value)
   в PascalABCCompiler.NETGenerator.ILConverter.ConvertBody(IStatementNode body)
   в PascalABCCompiler.NETGenerator.ILConverter.ConvertFunctionBody(ICommonFunctionNode func)
   в PascalABCCompiler.NETGenerator.ILConverter.ConvertFunctionsBodies(ICommonFunctionNode[] funcs)
   в PascalABCCompiler.NETGenerator.ILConverter.ConvertFromTree(IProgramNode p, String TargetFileName, String SourceFileName, CompilerOptions options, String[] ResourceFiles)
   в PascalABCCompiler.Compiler.Compile()'
```

**Comment by SunSerega** [comment]
@miks1965

1. `IntPtr` это не единственный тип с размером указателя. И кроме `UIntPtr` - ещё могут быть другие стандартные типы. Поэтому это надо не так фиксить.

2. Определить размер `IntPtr` можно. Только делать это надо не на этапе компиляции.
`sizeof(IntPtr)` это то же самое что `sizeof(pointer)`, а последнее нормально работает.

Правильно смотреть на поля записи, и если в ней есть указатель или ссылка - размер записи можно определить только на этапе выполнения.

**Comment by miks1965** [comment]
sizeof принципиально вычисляет на этапе компиляции. В C# он тоже выдает ошибку. Приведите пожалуйста все типы, для которых надо запретить вычисление sizeof

**Comment by miks1965** [comment]
Добавил UIntPtr

**Comment by SunSerega** [comment]
> В C# он тоже выдает ошибку

Хорошо, в таком случае надо запрещать `sizeof` не для `IntPtr` и `UIntPtr`, а для `pointer` (и для типизированных указателей тоже).

В C# `sizeof(void*)` так же запрещён.
Если запретить `sizeof(pointer)` - это автоматом запретит и `IntPtr`, и `UIntPtr`, и любые записи, с не_статичным размером, которые могут добавить в будущем в ядро .Net .

---

Далее, это тоже надо запретить, для равномерности:
```
type
  r1 = record
    o: object;
  end;
  
begin
  sizeof(r1).Println;
end.
```

---

И, если уже и запрещаете - добавьте в текст ошибки что то такое:
```
(рекомендуется использовать System.Runtime.InteropServices.Marshal.SizeOf)
```
`#Develop` добавляет этот текст в конец ошибки `sizeof`.
Насчёт студии - не знаю, нет лишней оперативки её сейчас запускать.
