### ISSUE TITLE
После исправления FixPointer перестал работать GCHandleType.Pinned

### ISSUE THREAD

**Issue by miks1965** [pascalabcnet/pascalabcnet#2206]
Из-за вот этой дурацкой правки
https://github.com/pascalabcnet/pascalabcnet/issues/1159
перестал работать следующий код:
```
type
 TPerson = record
  fam: string[15];
  name: string[10];
  id: integer;
 end;
type
  PPerson = ^TPerson; 
var x: array[1..1] of TPerson;
    p: PPerson;
begin
  p := @x[1];
  writeln(p);
end.
```
который до этого работал. Предлагаю вернуть всё назад

Было:
```
private void FixPointer()
        {
            il.Emit(OpCodes.Call, TypeFactory.GCHandleAlloc);
            il.Emit(OpCodes.Pop);
        }
```
Стало
```
private void FixPointer()
        {
            il.Emit(OpCodes.Ldc_I4, (int)GCHandleType.Pinned);
            il.Emit(OpCodes.Call, TypeFactory.GCHandleAllocPinned);
            il.Emit(OpCodes.Pop);
        }
```
Вот после того как запиннили указатель, этот код перестал работать

**Comment by SunSerega** [comment]
Без `GCHandleType.Pinned` в этой блокировке и смысла то нету.
Весь смысл использовать `GCHandle` при получении элемента массива в том, чтоб сборщик мусора не двигал массив, пока есть указатель на его элемент.
Если не добавить `Pinned` - сборщик мусора не будет только удалять объект, но всё ещё будет его двигать.

**Comment by SunSerega** [comment]
Код который вы привели - в любом случае неправильный, потому что `string[...]` у вас при компиляции превращается в просто `string`. А блокировать записи, содержащие ссылочные типы - нельзя.

Ну, `GCHandle` таки слишком привередливый. Это ему тоже не нравится:
```
type
  r1 = record
    ch: char;
  end;
  
begin
  var x := new r1[1];
  var p := @x[0];
end.
```
И даже это:
```
type
  r1 = record
    ch: DateTime;
  end;
  
begin
  var x := new r1[1];
  var p := @x[0];
end.
```
Ну, я всё ещё не нашёл никакой альтернативы `GCHandle`.

Я так же пробовал вызывать внутренние методы-реализацию `GCHandle` напрямую, но они тупо вылетают с какой то системной ошибок, если запись содержит что то типа `string` или `char`.

**Comment by miks1965** [comment]
Код, который я привёл, благополучно работал у нас, пока в IL не сделали дурацкую правку с Pinned. Напоминаю: 

Было:
```
private void FixPointer()
        {
            il.Emit(OpCodes.Call, TypeFactory.GCHandleAlloc);
            il.Emit(OpCodes.Pop);
        }
```
Стало

```
private void FixPointer()
        {
            il.Emit(OpCodes.Ldc_I4, (int)GCHandleType.Pinned);
            il.Emit(OpCodes.Call, TypeFactory.GCHandleAllocPinned);
            il.Emit(OpCodes.Pop);
        }
```

Собственно, нам написал известный автор учебника о том, что код, который был описан у него как работающий, внезапно в старших версиях работать перестал

**Comment by SunSerega** [comment]
Если не блокировать содержимое массива - код может и работать, но это не безопасно. Сборщик мусора может в любом момент сдвинуть массив, сломав указатель.

Правка была совершенно не дурацкая. Теперь, с моим опытом в модулях `OpenGL` и `OpenCL`, вплотную работающими с неуправляемыми .dll - я это окончательно понял.

`@a[...]` (где `a` - массив) это всегда неправильно. Потому что компилятор не может знать, когда указатель станет не нужен. А значит надо:
1. Или не блокировать. Но тогда такая запись неюзабельна, ибо всегда не безопасно;

2. Или блокировать и оставлять массив навсегда заблокированным. Но это утечка памяти, потому что сборщик мусора не может удалять заблокированный массив;

3. Или вообще запретить `@a[...]`, чтоб люди, приходящие из старых паскалей - не стреляли себе в ногу по незнанию. У этой записи всё равно нет нормальных применений, так что не страшно если она перестанет работать.

До правки было 1. В данный момент происходит 2. Ну а, по моему, правильнее всё же запретить.

Указатели на объекты из кучи в .Net - это то, что практически никогда происходить не должно. Есть только некоторые редкие исключения, как для быстрого чтения строки, через указатели.

Всё остальное должно происходить через `var` параметры + возможно часть неуправляемого кода.

---

И ещё, объясните, чего вы переживаете за учебники, учащие использовать статические массивы?

Поддерживать большинство фич старых паскалей - это, конечно, надо. Но вы никак не заставите указатели работать как в старых паскалях, потому что .Net .

Ну а лепить костыли, чтоб код из старых паскалей хоть как то работал, но при этом время от времени рандомно падал - точно не стоит.

---

P.S. Вообще, другой вариант есть - сделать статические массивы именно статическими массивами, а не костыльными башнями, стоящими на динамических массивах. То есть размещать их содержимое на стеке.

Тогда и код станет более совместимым со старыми паскалями. И языку такая фича однозначно не помешала бы. Потому что это -1 устаревшая и, в целом, не нужная фича.

**Comment by miks1965** [comment]
Этот код работал не в старых паскалях, а в PascalABC.NET, о чем и было объявлено в учебнике.

О статическом массив я не говорю - меня интересует строка. 

Очень странно, что нельзя закрепить строку и не перемещать её.

**Comment by SunSerega** [comment]
Строку отдельно закрепить можно. А массив, содержащий запись, содержащую строку - нельзя.

Как я и сказал, это бредовое ограничение. Но я сам успел намучиться с `GCHandle`.
В этом коде я тоже "уверен", что всё должно работать:
```
type
  r1 = record
    ch: DateTime;
  end;
  
begin
  var x := new r1[1];
  var p := @x[0];
end.
```
Это такая защита от дурака у `GCHandle`, которую не обойдёшь.

Как я и сказал, я пробовал много чего, даже вызывать внутренние (приватные) методы `GCHandle`.

Но, конечно, содержимое записи вообще никак не должно влиять на возможность заблокировать массив, потому что размер записи остаётся одинаковым, вне зависимости от того, содержаться ли в ней динамические типы как строки.

Ну, вообще, что я не сильно то пытался - поискать информацию, что те кто писали код `GCHandle` думают, зачем такое ограничение нужно.

**Comment by SunSerega** [comment]
@ibond84 это не потоко безопастно. Вы читаете и изменяете глобальную переменную `notPinnableTypes` без `lock`, и вызываете метод `__FixPointer` без `lock`.

**Comment by miks1965** [comment]
Приведите более подробный код пожалуйста

**Comment by SunSerega** [comment]
В это было добавлено в `PABCSystem` фиксом, на который ссыль показана выше:
```

var
  ...
  notPinnableTypes := new HashSet<&Type>;

[System.Diagnostics.DebuggerStepThrough] 
function __FixPointer(obj: object): GCHandle;
begin
  if obj <> nil then
  begin
    try
      if notPinnableTypes.Contains(obj.GetType()) then
        Result := GCHandle.Alloc(obj)
      else
        Result := GCHandle.Alloc(obj, GCHandleType.Pinned);
    except
      notPinnableTypes.Add(obj.GetType());
      Result := GCHandle.Alloc(obj);
    end;
  end;
end;
```
При этом в компилятор было добавлено условие, чтоб `__FixPointer` вызывалось когда можно при каждом `@a[...]` в коде. Несколько `@a[...]` могут быть вызваны из нескольких потоков одновременно, в таком случае `notPinnableTypes.Add` или `notPinnableTypes.Contains` может упасть.

**Comment by miks1965** [comment]
Вы предлагаете 
```
if obj <> nil then
lock(obj)
```
?

**Comment by SunSerega** [comment]
> lock(obj)

Это что вообще? Я такой подпрограммы не знаю.
Я говорю про `lock notPinnableTypes do`.

**Comment by SunSerega** [comment]
В общем если лень разбираться - замените реализацию на это:
```
function __FixPointer(obj: object): GCHandle;
begin
  if obj <> nil then
  begin
    try
      var is_non_pinnable: boolean;
      lock notPinnableTypes do is_non_pinnable := notPinnableTypes.Contains(obj.GetType);
      if is_non_pinnable then
        Result := GCHandle.Alloc(obj)
      else
        Result := GCHandle.Alloc(obj, GCHandleType.Pinned);
    except
      lock notPinnableTypes do notPinnableTypes.Add(obj.GetType);
      Result := GCHandle.Alloc(obj);
    end;
  end;
end;
```
А вообще лучше переоткрыть issue и дождаться @ibond84. Он фикс этой issue коммитил и он лучше разбирается в данной теме.

**Comment by miks1965** [comment]
Ну, пусть  @ibond84 отпишется

**Comment by SunSerega** [comment]
@ibond84 так а `notPinnableTypes.Contains` блокировать?

**Comment by miks1965** [comment]
Зачем?

**Comment by SunSerega** [comment]
Проблема не только если `notPinnableTypes` изменяется из 2 потоков, но и если 1 поток изменяет пока другой читает.

**Comment by SunSerega** [comment]
Хотя, я сейчас посмотрел исходники `HashSet` - не вижу ничего, что сломалось бы от `.Contains` одновременно с `.Add` .

Но, это в текущей реализации. Но `HashSet` принципиально не потоко-безопасен, как и все остальные стандартные коллекции из .Net, поэтому я бы не надеялся что это так и останется.

**Comment by miks1965** [comment]
Никаких проблем не будет. Если второй не успеет добавить, первый вернет false и исключение просто вызовется повторно.
