### ISSUE TITLE
Не переименовывается переменная в tuple

### ISSUE THREAD

**Issue by miks1965** [pascalabcnet/pascalabcnet#221]
```
var
  a, b: integer;

begin
  a := 1;
  b := 2;
  (a, b) := (b, a);
end.
```
При попытке переименования b например

**Comment by MikhailoMMX** [comment]
313b91aac82c49deaa8030ba1b6448e5090bc3cd
Проявляется слабое место визиторов - при добавлении узлов в синтаксическое дерево надо проходить по всем визиторам и дописывать код.
Эту ошибку поправил, но остались еще нереализованные visit'ы.

**Comment by miks1965** [comment]
03.07.2016 3:20, MikhailoMMX пишет:
> 313b91a
> <https://github.com/pascalabcnet/pascalabcnet/commit/313b91aac82c49deaa8030ba1b6448e5090bc3cd>
> Проявляется слабое место визиторов - при добавлении узлов в
> синтаксическое дерево надо проходить по всем визиторам и дописывать код.
> Эту ошибку поправил, но остались еще нереализованные visit'ы.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/pascalabcnet/pascalabcnet/issues/221#issuecomment-230128458>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AJ2Nj6Y0b9OKMawWHJ5FW7c81-bc3oAZks5qRwA6gaJpZM4JDvsz>.
>
Да, понятно, но а какие варианты? При появлении новых конструкций во 
многих прикладных визиторах их надо обходить

**Comment by miks1965** [comment]
Можно ли этот Issue закрывать?

**Comment by MikhailoMMX** [comment]
Формально - можно.
Но я бы вечером просмотрел какие еще узлы не реализованы визиторами, постарался бы привести визитор в соответствие с набором имеющихся в синтаксическом дереве узлов и вот тогда и закрывал бы.
Надо же эту работу как-то систематизировать. А то могут быть еще ошибки, вызванные ровно этой же причиной.

**Comment by miks1965** [comment]
Я бы сделал новый issue, а этот закрыл

**Comment by MikhailoMMX** [comment]
Согласен
