### ISSUE TITLE
Инициализатор массива не работает в yield функции

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#2211]
```
function f1: sequence of word;
begin
  var a: array of char := ('a','b'); //Ошибка: Нельзя преобразовать тип array of char к array of char
  yield 0;
end;

begin end.
```

**Comment by miks1965** [comment]
Да, это мы не досмотрели. Инициализаторы массивов и записей не могут встречаться в контексте функции с yield

**Comment by SunSerega** [comment]
Можете добавить в текст ошибки следующий текст?

> Используйте синтаксис `new ИмяТипа[](элементы_массива)`

**Comment by AIexandrKotov** [comment]
тот, кто знает про yield, это по идее и так должен знать

**Comment by miks1965** [comment]
Нет знаете ли. Я бы использовал здесь инициализатор Arr('a','b') и вообще не описывал бы тип.

Пользователь, увидевший запрет, сам найдёт подходящую конструкцию
