### ISSUE TITLE
В режиме отладки у переменной StringBuilder отображается предыдущее значение при присваивании ''

### ISSUE THREAD

**Issue by ProMix0** [pascalabcnet/pascalabcnet#2213]
```
begin
  var s: stringbuilder := 'sdg';
  s := '';
  write(s);
end.
```

**Comment by AIexandrKotov** [comment]
Нормально всё отображается.

![Ы332](https://user-images.githubusercontent.com/44296606/76418638-05beb680-63b0-11ea-9dd1-99e9a435f054.png)

**Comment by AIexandrKotov** [comment]
И вообще, IDE-issue должны быть в другом репозитории, https://github.com/pascalabcnet/pascalabcnetide/issues

**Comment by miks1965** [comment]
Перенесите пожалуйста Issue в другой репозитарий. Эту мы закроем

**Comment by SunSerega** [comment]
Однако странно, я тоже не вижу проблему. @miks1965 если вы поняли в чём дело - можете объяснить?
