### ISSUE TITLE
IDE also with English Menu available

### ISSUE THREAD

**Issue by harrysch** [pascalabcnet/pascalabcnet#2217]
Is there any chance to change the Gui from russian to english?

**Comment by AIexandrKotov** [comment]
![image](https://user-images.githubusercontent.com/44296606/76682489-93e3a880-660d-11ea-91fd-6501fea54cc7.png)

![Ы333](https://user-images.githubusercontent.com/44296606/76682522-c9889180-660d-11ea-8124-8a8a4bd6e3f9.png)

![Ы334](https://user-images.githubusercontent.com/44296606/76682538-e7ee8d00-660d-11ea-86c2-8c677d156ac2.png)

@miks1965, может быть ставить при первой установке тот язык, который используется системой?

**Comment by miks1965** [comment]
The translations of GUI elements and errors are here:
"C:\Program Files (x86)\PascalABC.NET\Lng\Eng"\
