### ISSUE TITLE
partial класс из интерфейса модуля не видит интерфейс из implementation (запретить partial-классы между interface и implementation)

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#2222]
```
unit u;

interface

type
  t1 = partial class end;
  
implementation

type
  I1 = interface end;
  
  //Ошибка: Неизвестное имя 'I1'
  t1 = partial class(I1) end;
  
end.
```

**Comment by miks1965** [comment]
Запретить partial-классы

**Comment by SunSerega** [comment]
Зачем? Я только успел более-менее переорганизовать OpenCLABC, чтоб нормально скрыть из интерфейса всё, что пользователю ни к чему. Что без `partial` классов никак.

А взялся за это только потому что потестил основные ситуации с `partial` классами и оказывается они на много стабильнее чем я думал.

**Comment by miks1965** [comment]
А вы их в namespacах используете или в модулях?

**Comment by SunSerega** [comment]
OpenCLABC это таки модуль, неймспейсы там не при чём. Ну, `partial` класс описанный в интерфейсе и реализации модуля - превращается во вполне адекватный класс, хранимый в интерфейсе модуля.

А все члены объявленные в части которая в реализации модуля - будут невидимыми вне модуля. Как раз увидев это - я и решил что `partial` классы всё же достаточно стабильны.

Ну а те проблемы с общим `partial` классом описанным в нескольких модулях - никак не касаются OpenCLABC, потому что это 1 модуль.

**Comment by SunSerega** [comment]
Это тоже не работает:
```
unit Program1;

interface

type
  t1 = partial class end;
  
implementation

var x := 5;

type
  t1 = partial class//(I1)
    y := x;
  end;
  
end.
```
`TreeConverter\TreeConversion\compilation_context.cs`, строка 2521:
```
            List<SymbolInfo> sil = find_only_in_namespace(name);
            if (sil == null)
            {
                if (is_partial)
                {
                    sil = find(name);
                    if (sil != null)
                    {
                        List<common_type_node> ctn_list = new List<common_type_node>();
                        foreach(SymbolInfo si in sil)
                        {
                            if (si.sym_info is common_type_node && (si.sym_info as common_type_node).IsPartial)
                                ctn_list.Add(si.sym_info as common_type_node);
                        }
                        common_type_node first_ctn = null;
                        if (ctn_list.Count > 0)
                            first_ctn = ctn_list[0];
                        
                        for (int i = 1; i < ctn_list.Count; i++)
                        {
                            ctn_list[i - 1].scope.PartialScope = ctn_list[i].scope;
                            first_ctn.Merge(ctn_list[i]);
                        }
                        partial_class = first_ctn;
                        return null;
                    }
                }
                return null;
            }
```
Если я правильно понял - как раз тут должны добавляться дополнительные скоупы. Это единственное место, где `PartialScope` что то присваивается.

`find_only_in_namespace(name)` находит первое описание `t1` и поэтому даже не проверяет, является ли класс `t1` - `partial`-классом.

**Comment by SunSerega** [comment]
Ну, что то я да исправил, но потом сделал объемлющие тесты и... Кажись слишком объемлющие, потому что сразу словил ещё несколько мелочей. Ну, это уже не сегодня. И вечером ещё и занят буду...

В общем я к тому что можете поигнорить пока `partial` классы, чтоб избежать потом лишних проблем с мерджем кода.

**Comment by miks1965** [comment]
Не тратьте время - partial-классы в этом виде мы запретим. Их нельзя использовать через границу модулей. Если их использовать для ваших целей - чтобы открывать в секции интерфейса только то, что нужно, то это непонятно по многим причинам. ВО-первых, в NET всё видно в метаданных. Во-вторых, то, что вы хотите, это не partial-классы, а другая концепция, которую надо специально, долго и тщательно внедрять в язык.

**Comment by SunSerega** [comment]
`partial` классы между границами модулей я уже в своём фиксе запретил, потому что это невозможно сделать детерминировано. Хотя бы потому что не понятно в какое пространство имён сувать `partial` класс.

> ВО-первых, в NET всё видно в метаданных

При чём тут это? Главное чтоб тот кто подключается модуль - не наталкивался на какие то странные типы и методы, которые ему, оказывается, и не нужны.

> Во-вторых, то, что вы хотите, это не partial-классы, а другая концепция, которую надо специально, долго и тщательно внедрять в язык.

Я очень рад что вы понимаете что это таки надо сделать. Но я вообще то подобное в языке уже не 1 и не 2 года жду.

`partial` классы по крайней мере временно позволили бы покрыть большинство случаев.
Да и на 100% костылём это не назовёшь. Всё работает интуитивно - части `partial` класса в `implementation` скрыты, а в `interface` - видны.

**Comment by miks1965** [comment]
Это не partial-класс. Это другая концепция, которую Вы придумали для PascalABC.NET. Я не говорю, что она плохая. Но нет никаких Use Cases кроме уже упомянутого вами - занаследовать partial-классом от скрытого интерфейса или класса, который не будет виден в interface модуля. 

Это всё имеет очень узкое применение и делается также другими методами. Например, вместо partial-класса создаётся нужный вам интерфейс, который виден в разделе interface и класс, реализующий этот интерфейс в разделе implementation. И потом где-то нужна создающая функция, возвращающая этот интерфейс, а вместо него подставляющая объект этого класса.

Всё. Никакие partial-классы в этой ситуации не нужны.

**Comment by SunSerega** [comment]
> Это не partial-класс. Это другая концепция, которую Вы придумали для PascalABC.NET

То что я говорю в основном про пример который мне ближе к сердцу - не значит что `partial` классы не будут `partial` классами.

> Их нельзя использовать через границу модулей

Это вы сами сказали. Остальное я ничего не запрещал. И сделаю так чтоб `partial` классы работали примерно так же как до моих фиксов. Только немного стабильнее.

Обходные пути как тот про который вы говорите - разумеется, всегда существуют. Если воспользоваться кодогенерацией, коей я уже давно не боюсь - проще сделать 2 версии каждого класса из интерфейса, вторую версию засунув в `implementation`. При этом из всех методов класса интерфейса  - вызывать соответствующие методы класса `implementation`.

Но, как и то что я предлагаю с `partial` классами - это костыль. Но в отличии от того что я предлагаю - это на много более уродливый костыль.

**Comment by miks1965** [comment]
Давайте еще раз. 

partial-классы мы уберем. Уберём также и все зависимости от них.

На что мы их заменим и заменим ли - зависит от вас.

Мне надо понять, какую всё-таки принципиальную задачу вы решаете partial-классами. Первое - вы скрываете наследование от другого класса в implementation - правильно ли я понимаю? Вы не хотите, чтобы предка видели из других модулей. Так?

Ещё? Какие ещё причины и примеры?

**Comment by SunSerega** [comment]
> Вы не хотите, чтобы предка видели из других модулей. Так?

Да, это основная задача.

Хотя `partial` классы так же дают бОльшую свободу в месте описания членов класса.
Что я успел изменить в OpenCLABC - я оставил в `interface` части модулей только члены классов, которые должно быть видны вне модулей.

Все остальные члены - находятся в 1 или нескольких `partial` классах в `implementation`. Это позволяет группировать части разных классов по их функционалу, вместо того чтоб в 10 разных классах делать регион с общим именем.
Так на много проще редактировать код. Особенно считая, как часто я кардинально меняю имена и кол-во параметров методов.

**Comment by miks1965** [comment]
Запретить partial-классы. Это основная причина метки "Важное"

**Comment by AIexandrKotov** [comment]
Не надо их запрещать. Запретите partial-классы между interface и implementation модуля и добавьте, наконец, **модификаторы доступа для типов** (public и internal, других-то и не существует). Тогда и эта issue будет закрыта.

**Comment by miks1965** [comment]
```
unit u;

interface

var I1: integer;

type t1 = partial class end;
  
implementation

type
  I1 = interface end;
  
  t1 = partial class(I1) end;
  
end.
```
Здесь - u.pas(12) : Повторно объявленный идентификатор I1

**Comment by miks1965** [comment]
Исходная ошибка исправляется добавлением такого кода в конец 

```
 public List<SymbolInfo> find(string name)
```
в compilation_context.cs

А последняя ошибка - нет. Надо выяснить, это две разных ошибки или нет.

**Comment by SunSerega** [comment]
Вы решили всё же заставить `partial` классы работать между `interface` и `implementation`? Если так то в `OpenCLABCBase` нет необходимости, то есть #2414 можно закрыть и вместо этого мне надо соединить `OpenCLABC` и `OpenCLABCBase`.

Но, кстати, в этой issue всё наследование от интерфейсов, но в `OpenCLABC` мне надо было наследование от класса, потому что в первую очередь нужна общая скрытая реализация у нескольких наследующих классов.

**Comment by miks1965** [comment]
Надо ещё потестировать в разных ситуациях

**Comment by SunSerega** [comment]
Ну, всё что в голову пришло я, конечно, сразу протестировал. А так надо на практике тестировать, к примеру соединяя `OpenCLABC` и `OpenCLABCBase`.
Ну и я таки уже начал, я спрашивал только в смысле "стоит использовать или вы потом всё равно собираетесь убрать/переделать".

Пока ничего критичного не нашёл. Единственное - можете, пожалуйста, разрешить делать так:
```
unit u0;

interface

type
  t1 = partial class
    procedure p1;
  end;
  
implementation

type
  t1 = partial class
    procedure p1;
    begin
      
    end;
  end;
  
end.
```
То есть реализация метода класса из интерфейса описана внутри этого же класса но в реализации.
