### ISSUE TITLE
Уберите это предупреждение!!!

### ISSUE THREAD

**Issue by Ze2QvoQxxKeu** [pascalabcnet/pascalabcnet#2224]
Уберите предупреждение "параметр цикла должен записываться в заголовке цикла"!
Школьники правильно пишут код, но видят эту дрянь и у них истерика! Прекратите самоуправство! Нет в паскале такого правила! Тонны жалоб уже сыпятся!
Одна из них: https://otvet.mail.ru/question/219464948

**Comment by miks1965** [comment]
Это не ошибка, а предупреждение о стиле программирования. Необходимо понимать, что PascalABC.NET - другой язык и в PascalABC.NET другой рекомендуемый стиль программирования нежели в старых паскалях. И эта рекомендация - одна из важнейших.

**Comment by Ze2QvoQxxKeu** [comment]
> Это не ошибка, а предупреждение

Это нам понятно. Попробуйте объяснить это детям, которые пишут как их учили, пишут правильно, а тут видят это предупреждение. Сделайте хотя бы возможность его отключения в настройках. Те, кто учится ещё, не понимают этого. Надеюсь просьба не останется без внимания.

**Comment by miks1965** [comment]
Не осталась конечно. Не отключим. 

Это то немногое, что мы можем сделать для того чтобы школьники начинали учить современные языки программирования. И учителям это надо принять к сведению.

Пожалуйста, откройте сайт pascalabc.net и прочитайте миссию этого языка. Этот язык никогда не создавался как клон устаревших языков и сред программирования.

Мы читаем ваш форум - там есть и вполне правильные решения в стиле PascalABC.NET.
У вас на форуме есть возможность это объяснять. Если они пишут как их учили и это не работает или работает как-то не так, то может дело в том, что как-то не так учат.

**Comment by AlexRnD61** [comment]
Как по мне - я бы в будущем вообще запретил описывать переменные цикла вне его тела. Ибо в ряде случаев это вообще ведет к тупым, причем трудно находимым ошибкам в работе программы.

**Comment by savoptik** [comment]
> > Это не ошибка, а предупреждение
> 
> Это нам понятно. Попробуйте объяснить это детям, которые пишут как их учили, пишут правильно, а тут видят это предупреждение. Сделайте хотя бы возможность его отключения в настройках. Те, кто учится ещё, не понимают этого. Надеюсь просьба не останется без внимания.

Вообще, продукт [распространяется](http://pascalabc.net/litsenzionnoe-soglashenie) под одной из самых свободных [лицензий](https://ru.wikipedia.org/wiki/GNU_Lesser_General_Public_License), какие только приходили в голову святому Стоуману. Сделайте форк, уберите, чего хотите, и плодите себе на здоровье говнокодеров, от которых на гитхабе не продохнуть стало.

**Comment by AlexRnD61** [comment]
> какие только приходили в голову святому Стоуману

А разве он не Столлман?

**Comment by savoptik** [comment]
> > какие только приходили в голову святому Стоуману
> 
> А разве он не Столлман?

Благодарю. поправил. :-)

**Comment by declard** [comment]
Как по мне - я бы в будущем запретил циклы, заменив их на хвостовую рекурсию. Пусть школьники отучаются от шаблонов кода прошлого столетия.

**Comment by alexey-sveshnikov** [comment]
Какой любопытный тикет, какая любопытная ситуация.

Уверен, что школьники - непростая и своеобразная аудитория, и меня как программиста конечно задевает, когда их учат по учебникам 30-летней давности. Но прекрасно могу понять людей, которые действительно не понимают в чем суть варнинга и паникуют.

Смотрите, как про ошибку сообщает Arduino IDE - среда, которая также ориентировна на новичков:

![image](https://user-images.githubusercontent.com/447089/80213574-0a7ab980-8642-11ea-86ef-717dc650df1d.png)

А вот ошибка от Docker:
![image](https://user-images.githubusercontent.com/447089/80213890-8e34a600-8642-11ea-9e78-a4780c7fedc1.png)

@miks1965, кажется, что это могло бы быть возможным решением подобных проблем - в подобные ошибки/варнинги добавлять ссылку на раздел сайта с пояснением, что это такое и как ее избежать.

**Comment by ulysses4ever** [comment]
Схожая идея: иметь для каждого предупреждения и ошибки свой цифро-буквеный код -- для облегчения поиска и обсуждения этих объектов. [Недавно было предложено для GHC такое сделать](https://github.com/ghc-proposals/ghc-proposals/pull/325) -- там по ссылке много примеров из других языков, начиная со всеми любимой Visual Studio...

**Comment by AlexRnD61** [comment]
"добавлять ссылку на раздел сайта с пояснением"

Это же сколько контента надо в сайт влить, чтобы не только расписать каждую ошибку, но растолковать ее суть и дать рекомендации, как такие ошибки избежать. Фактически, это будет сборник статеек "Научите меня программировать!". Абсолютно нереально это для такого объемного языка. Да и некому делать. Разве что автор предложения возьмется...
