### ISSUE TITLE
Убрать лишнюю локальную переменную при вызове Params

### ISSUE THREAD

**Issue by miks1965** [pascalabcnet/pascalabcnet#2226]
Сейчас из-за этого при компиляции
```
begin
  Arr(1,2,3);
end.
```
ILSpy отображает это ужасно:
![изображение](https://user-images.githubusercontent.com/10325391/80283670-19d13400-8722-11ea-83e8-4e0d84a1a769.png)
Хотя лишняя IL-команда всего одна.

Для такого кода
```
begin
  Arr(new integer[](1,2,3));
end.
```
всё хорошо:
![изображение](https://user-images.githubusercontent.com/10325391/80283697-56049480-8722-11ea-9094-a4efd03b128a.png)

**Comment by SunSerega** [comment]
> Хотя лишняя IL-команда всего одна.

Нет, 2. Сохранение в локальную переменную и сразу загрузка этого же значения назад.
