### ISSUE TITLE
Можно ли, и если да, то как, использовать pascalabc.net в других ide вроде VSCode, intellij idea и тд

### ISSUE THREAD

**Issue by zvshka** [pascalabcnet/pascalabcnet#2230]
Оригинальная IDE очень не нравится, хотелось бы иметь возможность работать в более привычной

**Comment by SunSerega** [comment]
Компилятор паскаля легко использовать программно. В ProgramFiles 2 файла - pabcnetc.exe и pabcnetcclear.exe . Первый выводит больше инфы.

А чтоб работал анализатор кода в других IDE - надо его собственно написать для этих других IDE. Готового, вроде, ничего нет.

**Comment by zvshka** [comment]
Ок, спасибо!
