### ISSUE TITLE
Предложить поведение функции с yield, не возвращающей значения

### ISSUE THREAD

**Issue by miks1965** [pascalabcnet/pascalabcnet#224]
```
function f(): sequence of integer;
begin
end; 
```
Она должна возвращать Sequence.Empty 
Или нужно ввести аналог yield break

**Comment by ibond84** [comment]
А в чем ошибка? Пустая функция, которая возвратит nil. Здесь нету yield-ов вообще..

**Comment by miks1965** [comment]
nil и пустая последовательность - разные вещи. Тут жутковатое сообщение об ошибке если последовательность воспринимать как набор последовательных данных, а не как объект. Возможно, надо возвращать Enumerable.Empty

**Comment by miks1965** [comment]
Закрываю. Тут ошибка возвращения nil. Никто не знает, что мы собираемся использовать yieldы
Наличие любого yield - даже по нулевой ветке - убирает эту ошибку.

И - из функции с yield можно выходить обычным exit.
