### ISSUE TITLE
Re: Не выбирает более подходящую перегрузку если вызывать метод, возвращающий наследника, без скобок

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#2243]
https://github.com/pascalabcnet/pascalabcnet/issues/2156

Это я слишком много вырезал. Вот код ближе к оригинальному:
```
type
  t1<T> = class;
  
  t0 = class
    
    // Обязательно метод t0
    // Если сделать extensionmethod - не воспроизводится
    public function f1<T>: t1<T> := nil;
    
  end;
  t1<T> = class(t0) end;
  
// Эту перегрузку никогда не вызывает
// Вместо этого из следующей перегрузки делает рекурсивный вызов
procedure p1<T>(q: t1<T>) := exit;

// Обязательно вызывать f1 без скобок. Со скобками не воспроизводится
procedure p1(q: t0) := p1(q.f1&<byte>);

begin
  p1(new t0);
end.
```
Тут уже первую перегрузку должно вызывать, потому что шаблонный параметр есть из чего выводить.

**Comment by miks1965** [comment]
Какой-то сложный код. Проще не удаётся?

**Comment by SunSerega** [comment]
Большая часть этого кода - комментарии. Если их убрать - код получается очень маленький.

Ну, упростить я много пытался. Как видите, даже слишком. Вроде ничего больше убрать нельзя.
