### ISSUE TITLE
Неправильно выбирается a.first

### ISSUE THREAD

**Issue by miks1965** [pascalabcnet/pascalabcnet#225]
```
var
  a: System.Collections.Generic.Linkedlist<string>;
  b: System.Collections.Generic.Linkedlistnode<string>;
 
begin
  a := new System.Collections.Generic.LinkedList<string>;
  a.AddFirst ('a');
  b := a.first;
end.
```
Program1.pas(8) : Нельзя преобразовать тип string к LinkedListNode<string>
Это неверно - тип a.first - LinkedListNode<string>, а срабатывает метод расширения

**Comment by ibond84** [comment]
У разрабов дотнета фантазии на имена наверно не хватает. Какие-то сверхперегруженные методы наворотили :(

**Comment by ibond84** [comment]
+ накладывается последствия паскалевского архитектурного ляпа, вроде вызова функции без скобок.
