### ISSUE TITLE
Невозможность работы с TCP и UDP на базе версий 3.6.2 - 3.6.3

### ISSUE THREAD

**Issue by aGrIklololol** [pascalabcnet/pascalabcnet#2251]
### TCP
Имеется следующий код:
![image](https://user-images.githubusercontent.com/60868947/84364512-d9961a00-abd8-11ea-8191-8838da57b52b.png)

При последовательном вводе в программу корректного имени хоста либо IP, а также корректного порта программа завершается на **строке 14** с **_Ошибка времени выполнения: Ссылка на объект не указывает на экземпляр объекта_**.
Замена значения строки 14 на аналогичные `Client.Connect(EP);`, `Client.Connect(IPString, Port);` или на `Client.Connect(ResolveArray, Port);` не исправляет ситуацию и программа завершается с этим же исключением. Также не имеет смысла замена строки 12 на `IP := System.Net.IPAddress.Parse(IPString);`.

Имеется и иной код:
![image](https://user-images.githubusercontent.com/60868947/84372957-9346b800-abe4-11ea-8b5c-50c7bc417657.png)

При введении корректного порта программа корректно слушает и принимает соединение, вплоть до получения сообщения, неравного `nil`, где завершается на **строке 25** с **_Ошибка времени выполнения: Ссылка на объект не указывает на экземпляр объекта_**.

### UDP
Имеется приближённый к первому код, однако же, здесь применяется протокол UDP:
![image](https://user-images.githubusercontent.com/60868947/84382109-d3149c00-abf2-11ea-8555-5db6dafd3b23.png)

Возникает аналогичное исключение на **строке 14** с **_Ошибка времени выполнения: Ссылка на объект не указывает на экземпляр объекта_**. Замена значения строки 14 на аналогичные `Client.Connect(EP);`, `Client.Connect(IPString, Port);` также не возымела смысла, не работает и эта конструкция:
![image](https://user-images.githubusercontent.com/60868947/84383541-212a9f00-abf5-11ea-83be-7ab34f0d59a6.png)
На входе параметры 
`127.0.0.1`
`54321`
`Hello anyone!`.
В чём же проблема, можно узнать? Аналогичный код на C# срабатывает на ура, изучить можно здесь: https://github.com/aGrIklololol/tcp_udp_attempts.

**Comment by SunSerega** [comment]
1. Issue этой репэ предназначены только для стопроцентных багов компилятора.
Сейчас закройте эту issue и идите [на форум](http://forum.mmcs.sfedu.ru/t/pomoshh-novichkam/263/2586). Если останутся вопросы по данной теме - сделайте там ссылку на эту issue и продолжайте спрашивать уже там.

2. Ваш код не аналогичен. Кроме мелких ошибок...
Этот код:
```
static void Main(string[] args)
{
    int i1 = 5;
    var i2 = 7;
}
```
Равен следующему:
```
begin
  var i1: integer := 5;
  var i2 := 7;
end.
```
А код с глобальными переменными:
```
var
  i1, i2: integer;
  
begin
  i1 := 5;
  i2 := 7;
end.
```
В C# выглядел бы так:
```
static int i1, i2;

static void Main(string[] args)
{
    i1 = 5;
    i2 = 7;
}
```
Как и в C# - в паскале плохо хранить переменные в свалке в начале программы.
Если объявлять переменные прямо при/перед первым использованием - и программа становится в несколько раз быстрее, и одновременно с тем компилятор помогает не допускать глупые ошибки.

3. Что касается конкретно вашего случая - учите азы работы с объектами. Странно лезть в сокеты, не зная что делает `new` и что значит `NullReferenceException`.

И пользуйтесь отладчиком (F8,F7 и точки останова (тык слева чтоб поставить/убрать) ), он бы сейчас тоже помог.

**Comment by miks1965** [comment]
И на форуме приводите текст, а не скриншоты
