### ISSUE TITLE
TypeLoadException, если указать больше ограничений where в override методе, чем в методе предка

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#2254]
```
type
  t1 = class
    
    procedure p1<T>; virtual;
    where T: constructor;
    begin
      
    end;
    
  end;
  
  t2 = class(t1)
    
    procedure p1<T>; override;
    where T: record, constructor;
    begin
      Assert(typeof(T).IsValueType);
    end;
    
  end;
  
begin
  var a: t1 := new t2;
  a.p1&<object>;
end.
```
```
Ошибка времени выполнения: System.TypeLoadException: Метод "p1" типа "Program1.t2" из сборки "Program1, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" попытался неявно переопределить метод с более слабыми ограничениями на параметры типов.
Стек:
   в Program1.Program.$Main()
   в Program1.Program.Main()
```

В `override` методе может быть меньше ограничений, но не больше.

Если ограничений меньше - проблемы могут возникнуть только при попытке вызвать метод предка. Но это отдельная issue - #2251.

**Comment by miks1965** [comment]
Так ошибка в чем - что это не запрещено на этапе компиляции?

**Comment by SunSerega** [comment]
Да. Надо чтоб давало ошибку компиляции, если `override` метод имеет ограничение в `where`, которого не было в секции `where` соответствующего метода предка.

**Comment by miks1965** [comment]
В C#:	Ограничения для переопределения и явные методы реализации интерфейса унаследованы от базового метода, поэтому они не могут быть указаны напрямую

То есть, ограничения должны быть такими же, и их не надо явно указывать

**Comment by SunSerega** [comment]
Это в C#. Но там это скорее тяжелое наследование, от которого пытаются избавится в C#8.0 и делают ради этого костыли.

Не обязательно повторять чужие ошибки. `override` метод может содержать меньше ограничений и ничего от этого не сломается.

**Comment by miks1965** [comment]
Понимаете, с некоторых пор мы сформулировали миссию PascalABC.NET на сайте http://pascalabc.net/

Так вот - то, что вы предлагаете, не отвечает этой миссии. И нужно только вам из спортивного интереса. Зачем такое может понадобиться в сфере образования или научных исследований, на которые ориентирован PascalABC.NET, ума не приложу
