### ISSUE TITLE
В GraphABC при использовании кнопок ABCbuttons перестает работать onmouseup

### ISSUE THREAD

**Issue by furlit** [pascalabcnet/pascalabcnet#2260]
В GraphABC при использовании кнопок ABCbuttons перестает работать onmouseup. Слышал, что как то можно исправить модуль ABCbuttons, чтобы проблема больше не возникала. Подскажите что делать, буду благодарен.

**Comment by SunSerega** [comment]
`ABCbuttons` работает поверх `ABCObjects`. А `ABCObjects` не должно использоваться вместе с `GraphABC`.

А вообще - такие вопросы пишите [сюда](http://forum.mmcs.sfedu.ru/t/pomoshh-novichkam/263/2586). Issues - это только для проблем компилятора.

**Comment by miks1965** [comment]
К сожалению, GraphABC устарел, и мы его более не поддерживаем. Только простые описки.
