### ISSUE TITLE
"Предописание не может быть использовано" если указать текущий тип в качестве шаблона предка

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#2264]
```
type
  t0<T> = class end;
  
  // обязательно предописание
  // если убрать - компилируется
  t1 = class;
  
  //Ошибка: Предописание t0<t1> не может быть использовано в качестве базового типа
  t1 = class(t0<t1>)
    
  end;
  
begin end.
```

**Comment by miks1965** [comment]
Так не описывайте. Вам ясно сказал компилятор - нельзя использовать предописания в базовом типе. Никакие.

**Comment by SunSerega** [comment]
Ещё раз, так работает:
```
type
  t0<T> = class end;
  
  t1 = class(t0<t1>)
    
  end;
  
begin end.
```
Это вполне легальный код и встречается у меня много где в POCGL.

А значит и если добавить предописание - работать должно.

**Comment by miks1965** [comment]
Мы запретили наследовать от предописаний. Так - в Delphi.

Пользуйтесь кодом, который вы только что написали

**Comment by SunSerega** [comment]
> Пользуйтесь кодом, который вы только что написали

Да если бы всё было так просто. Я запостил минимальный код, а вообще у меня так:
```
type
  t0<T1, T2> = class end;
  
  t1 = class;
  t2 = class
    constructor(parent: t1) := exit;
  end;
  
  t1 = class(t0<t1, t2>)
    
  end;
  
begin end.
```
И что теперь делать?

> Мы запретили наследовать от предописаний

В этом коде нет наследования от предописаний! Есть только наследование от текущего класса.
А предописание сделано вообще для других целей.

**Comment by miks1965** [comment]
Вы же не будете спорить, что вы предописали класс t1? У нас наследовать от предописаний запрещено

**Comment by SunSerega** [comment]
> Вы же не будете спорить, что вы предописали класс t1?

Ну и что, что предописание где то существует? Тут тоже наследование от предописания?
```
type
  t1 = class;
  
  t1 = class end;
  
  t2 = class(t1) end;
  
begin end.
```

**Comment by SunSerega** [comment]
Возвращаясь к началу - основная проблема в том, что добавление предописания классу ломает код, который работал без этого предописания. Это не может быть правильно.

**Comment by miks1965** [comment]
Правильно. Не добавляйте.

В программировании это сплошь и рядом когда добавление чего-то из лучших побуждений ломает код
