### ISSUE TITLE
Если использовать переменную is-var после yield - она окажется обнулённой

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#2265]
```
function f1(o: object): sequence of object;
begin
  
  if o is object(var a) then
  begin
    var b := a;
    Writeln(a); // object
    yield a;
    Writeln(a); // nil
    Writeln(b); // object
  end;
  
end;

begin
  foreach var o in f1(new object) do
end.
```

**Comment by miks1965** [comment]
yield-движок не считает a0 за описание

**Comment by miks1965** [comment]
переменные в if o is object(var a) then 
не имеют типа до семантики.

С другой стороны, все локальные переменные переходят в поля класса на синтаксисе. Так что, есть проблемы с определением этого типа, и серьёзные.

Проблемы с недовыведенным типом мы решали по первому присваиванию в коде. Однако, тут переменная a получает своё значение методом o.deconstruct(a), что делает невозможным старый путь.

**Comment by miks1965** [comment]
В этой комбинации конструкций наверное правильным будет путь вводить дополнительную переменную
```
  if o is object(var a) then
  begin
    var $$a := a;
    Writeln($$a);
    yield $$a;
    Writeln($$a);
  end;
```
и переименовывать в расширенном блоке if `a` на `$$a`

**Comment by SunSerega** [comment]
Эта конструкция позволяет сделать вот как красиво:
```
        if CommentableProp.Parse(l, t) is CommentableProp(var p) then
          yield p else
        if CommentableEvent.Parse(l, t) is CommentableEvent(var e) then
          yield e else
          
        if CommentableMethod.Parse(l, t) is CommentableMethod(var m) then
          yield m else
        if CommentableConstructor.Parse(l, t) is CommentableConstructor(var c) then
          yield c else
```
Тут `CommentableProp.Parse` возвращает или `CommentableProp`, или `nil`. `nil` не проходит `is-var`, поэтому елдятся только успешно созданные экземпляры.

Если делать это же без `is-var` - кода получится раза в 3 больше.

**Comment by miks1965** [comment]
Да, вижу - красиво

**Comment by miks1965** [comment]
Чтобы не переименовывать так:
```
  if o is object(var a) then
  begin
    var $$a := a;
    Writeln($$a);
    yield $$a;
    Writeln($$a);
  end;
```
было решено переименовать так:
```
  if o is object(var $$a) then
  begin
    var a := $$a;
    Writeln(a);
    yield a;
    Writeln(a);
  end;
```

В результате в ситуации с and 
```
  if o is object(var $$a) and (a = nil) then
  begin
    var a := $$a;
    Writeln(a);
    yield a;
    Writeln(a);
  end;
```
последняя a оказалась без переименований

**Comment by SunSerega** [comment]
Использование переменной в условии позволяет делать так:
```
    public function Equals(obj: object): boolean; override :=
    (obj is WrapperBase<TNtv, TProp>(var wr)) and (self.ntv = wr.ntv);
```
А в чём в проблема переименований?

**Comment by miks1965** [comment]
Это не для вас - это наша техническая информация. Переименование по синтаксическому дереву - непустячная каноническая задача. Во вложенных блоках могут встретиться те же имена - их переименовывать не надо. Количество типов вложенных блоков - значительное. Это - каноническая задача в middle-end компилятора

**Comment by miks1965** [comment]
Работает
