### ISSUE TITLE
"t is (var a, var b)" не работает перед and

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#2267]
```
begin
  var t: (integer, integer);
  var res := (t is (var a, var b)) and (a=b);
end.
```
`Ошибка: Этот вид сопоставления с образцом не поддерживается в данном контексте`

**Comment by miks1965** [comment]
А с чего вы решили, что кортеж должен деконструироваться таким образом? 

Зачем свои хотелки писать в багтрекер???

**Comment by SunSerega** [comment]
> А с чего вы решили
```
begin
  var t: (integer, integer);
  if t is (var a, var b) then
end.
```
```
begin
  var t: integer;
  var b := t is integer(var i);
end.
```
Эти оба кода компилируются. С чего в друг код из заголовка не должен?

**Comment by SunSerega** [comment]
Да и вот это тоже работает:
```
type
  t1 = class
    
    procedure Deconstruct(var a: integer; var b: integer) := exit;
    
  end;

begin
  var t := new t1;
  var res := t is t1(var a, var b);
end.
```
У кортежей - такой же `Deconstruct`, только `extentionmethod`.

**Comment by miks1965** [comment]
Он не может использоваться в контексте, где нет объемлющей секции операторов
