### ISSUE TITLE
Undefined FileName при не_правильном is-var в лямбде-функции, переданной в шаблонную подпрограмму

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#2269]
```
procedure p1(f: Action<array of byte>) := exit;
procedure p2<T>(f: Func<array of byte, boolean>) := exit;

begin
  
//  p1(x->
//  begin
//    //Правильная ошибка: Выражение типа array of byte не может быть сопоставлено с образцом типа Tuple`2
//    if x is (var a,var b) then ;
//  end);
  
  p2(x->
  begin
    if x is (var a,var b) then ;
    Result := false;
  end);
  
end.
```
`Undefined FileName(0) : Item1 не объявлен в типе array of byte`

Правда, этот код неправильный ещё и потому - что тип шаблона `p2` не вывести.
В качестве кода для добавления в тесты используйте этот:
```
procedure p1<T>(self: sequence of T; f: Func<array of byte, boolean>); extensionmethod := exit;

begin
  Seq&<array of byte>
  .p1(x->
  begin
    if x is (var a,var b) then ;
    Result := false;
  end);
end.
```

**Comment by SunSerega** [comment]
Так подождите, это исправляет `Undefined FileName`, но ошибка всё равно другая должна быть. К примеру тут:
```
procedure p1<T>(self: sequence of T; f: Action<array of byte>); extensionmethod := exit;

begin
  Seq&<array of byte>
  .p1(x->
  begin
    if x is (var a,var b) then ;
  end);
end.
```
Говорит:
> Выражение типа array of byte не может быть сопоставлено с образцом типа Tuple`2

А от типа лямбды - текст ошибки не должен меняться.

**Comment by miks1965** [comment]
Это вы слишком многого хотите. Текст ошибки - разный, но он абсолютно правильный. И - это на задворках.

Приводить к одному виду сообщения не будем.
