### ISSUE TITLE
Переход внутрь составного оператора на метку 1 невозможен

### ISSUE THREAD

**Issue by miks1965** [pascalabcnet/pascalabcnet#2271]
```
label 1;

begin
  Arr(3).Select(b -> b);
  if True then
    goto 1;
  1:
end.
```
gotobad0.pas(6) : Переход внутрь составного оператора на метку 1 невозможен

**Comment by AIexandrKotov** [comment]
Всё же правильно, вы запретили метки и лямбды в одном блоке ещё давным-давно, надо только текст ошибки поправить.

**Comment by miks1965** [comment]
Да? Надо же - не помню. Интересно, почему...

**Comment by AIexandrKotov** [comment]
Я точно помню, что от кого-то с форума это слышал. Так ли это на самом деле я не знаю, но запрет есть и я считаю, что обоснованный, метки это низкоуровневый код, нельзя совмещать его с лямбдами.

**Comment by SunSerega** [comment]
>  вы запретили метки и лямбды в одном блоке

А по моему давно назад разрешили, с минимальными ограничениями.
Ну, в любом случае, запрещающая ошибка была с текстом, явно говорящим про запрет лямбд+`goto`, а не вот это вот.

**Comment by miks1965** [comment]
Мне кажется, внутри лямбд они запрещены. Так это понятно.

**Comment by miks1965** [comment]
![изображение](https://user-images.githubusercontent.com/10325391/85551059-47efc900-b62a-11ea-9da5-48bc2a562eb8.png)

Внутри метки - два goto при наличии лямбд. И берется первый, потому идёт не туда.

**Comment by miks1965** [comment]
s_t_v.cs: 8918 - `lab.goto_statements.Add(gs);`

И это происходит дважды (2768):
```
lambdaProcessingState = LambdaProcessingState.TypeInferencePhase;
visit_program_code(_block.program_code);
...
lambdaProcessingState = LambdaProcessingState.FinishPhase;
context.code = visit_program_code(_block.program_code);
```
Поэтому в lab.goto_statements накапливается мусор с первого обхода.

Решение представляется простым - очищать все lab.goto_statements после первой фазы
