### ISSUE TITLE
Плохая ошибка при подставлении абстрактного класса в where-constructor

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#2275]
```
type
  t1<T> = class where T: constructor;
    function MakeObj := new T;
  end;
  
  t2 = abstract class
    public constructor := exit;
  end;
  
begin
  var a := new t1<t2>; //Ошибка: Невозможно инстанцировать, так как у типа t2 нет конструктора без параметров с уровнем доступа public
  Writeln(a.MakeObj);
end.
```
У типа `t2` есть конструктор без параметров с уровнем доступа `public`. Проблема в другому.

`where T: constructor;` значит что должна быть возможность создать экземпляр типа `T`. А создавать экземпляры абстрактных классов - нельзя.

**Comment by AIexandrKotov** [comment]
В C# текст ошибки следующий:
![Ы394](https://user-images.githubusercontent.com/44296606/86721177-67292600-c02e-11ea-82a4-80af2702ce01.png)
