### ISSUE TITLE
Переменная ":= (is-var)" перестала быть видна в остальном выражении

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#2277]
```
begin
  //Ошибка: Неизвестное имя 's'
  var b := ('abc' is string(var s)) and (s='abc');
  b.Println;
end.
```
Совсем недавно это работало. У меня это было в коде `OpenCLABC`, как обновился - модуль перестал компилироваться.

При чём, главное, так всё ещё работает:
```
begin
  var b := ('abc' is string(var s));
  s.Println;
  b.Println;
end.
```

**Comment by miks1965** [comment]
Это произошло при исправлении #2265

**Comment by miks1965** [comment]
Пока закрою - откатил изменения

**Comment by miks1965** [comment]
Там #2282 всё перекрывает. Его исправление - это исправление всех этих проблем. Просто там много работы
