### ISSUE TITLE
Предописания обобщенных классов почему-то не работают

### ISSUE THREAD

**Issue by miks1965** [pascalabcnet/pascalabcnet#228]
```
type 
  clyield1<T> = class;
  clyield1<T> = class
  end;
```
Для обычных классов всё работает

**Comment by ibond84** [comment]
Ну надо запрещать. Там потом where может идти, а невалидная инстанция будет определена. Так что толку от этих предописаний никакого.

**Comment by miks1965** [comment]
Давайте запретим
