### ISSUE TITLE
isvar в сложном and

### ISSUE THREAD

**Issue by miks1965** [pascalabcnet/pascalabcnet#2282]
```
var a := 666;

procedure p;
begin
  var b := (a = 1) or (a = 3) or ('abc' is string(var a)) and (a = 'abc');
  b.Println;
end;

begin  
end.
```
isVar0.pas(5) : Нет перегруженной подпрограммы с такими типами параметров

**Comment by SunSerega** [comment]
Наверное стоит добавить что связано с временным фиксом #2277 и #2265, иначе легко забыть откуда это взялось...

**Comment by miks1965** [comment]
Здесь - всё равно необходимо полное переименование `a` в is var и не только в yield
