### ISSUE TITLE
Ошибка: Возможны два преобразования типа: к типу Tuple<real,real> и к типу Tuple<real,real>

### ISSUE THREAD

**Issue by izhaks** [pascalabcnet/pascalabcnet#2292]
При попытке компиляции программы:  
```
var some_var: (real, real) := (1, 2);
begin end.
```
компилятор выдаёт ошибку:  

> Возможны два преобразования типа: к типу Tuple<real,real> и к типу Tuple<real,real>

Вероятно, имелось в виду: "к типу Tuple<**integer**,**integer**> и к типу Tuple<real,real>",   
но в то же время, странно, что здесь вообще есть ошибка, ведь **"some_var"** явно указан как **(real, real)**.

PascalABC.net версии 3.6.3 сборка 2547 (01/07/2020)

Спасибо.

**Comment by SunSerega** [comment]
У меня в последней (самособранной) версии выдаёт:
`Нельзя преобразовать тип Tuple<integer,integer> к Tuple<real,real>`.

Вообще всегда лучше писать `var some_var := (1.0, 2.0)`, так на много короче.
Ну, стоит ещё дождаться что скажут разработчики.

Если когда то выдавало `Возможны два преобразования типа` - значит, наверное, компилятор пытался преобразовать `(1,2)` в `(real,real)`. То есть алгоритм этого преобразования уже есть в компиляторе, надо только починить.

**Comment by izhaks** [comment]
Предположу, что планировалось автоматическое преобразование компилятором к нужному типу.
Пример [MovingFrameBasedTime.pas](https://github.com/pascalabcnet/pascalabcnet/blob/master/InstallerSamples/Graphics/WPFObjects/MovingFrameBasedTime.pas) содержит строки:

```
Key.Left: c.Direction := (-5, 0);
Key.Right: c.Direction := (5, 0);
Key.Up: c.Direction := (0, -5);
Key.Down: c.Direction := (0, 5);

...

c.Direction := (0, 0);
```
которые как раз не компилируются теперь с этой ошибкой.

_Также нужно добавить `uses GraphWPF;` в  [MovingFrameBasedTime.pas](https://github.com/pascalabcnet/pascalabcnet/blob/master/InstallerSamples/Graphics/WPFObjects/MovingFrameBasedTime.pas) и в [Shooter.pas](https://github.com/pascalabcnet/pascalabcnet/blob/master/InstallerSamples/Graphics/WPFObjects/Shooter.pas)_

**Comment by miks1965** [comment]
Скачайте последнюю версию. 
Ошибка 
```
Нельзя преобразовать тип Tuple<integer,integer> к Tuple<real,real>
```
и она правильная. Никто не предполагал делать преобразование между этими типами.

С простыми, массивами, записями и множествами - это специальные инициализаторы, которые работают и в Delphi. Мы делали это для совместимости. С кортежем - другая история. Это NET-тип и Tuple<integer,integer> и Tuple<real,real> неявно друг в друга не преобразуютсчя. Как и List<integer> и List<real>

Пример MovingFrameBasedTime.pas мы немного исправили - работающая версия на сайте. Но вы пишете об ошибке, которая могла быть в ранних версиях - сейчас её нет.

**Comment by izhaks** [comment]
@miks1965 
Версия 3.6.3, сборка 2657 (15/08/2020):

![image](https://user-images.githubusercontent.com/42379993/90330314-8d8a9b80-dfb4-11ea-84bc-af54dfe02862.png)

**Comment by SunSerega** [comment]
А у меня на той же версии почему то компиляция успешно проходит:

![image](https://user-images.githubusercontent.com/27270190/90330481-a182cd00-dfb5-11ea-8b62-e8dd0cc3f0ec.png)

**Comment by izhaks** [comment]
Я скачал новую версиу от сюда:
http://pascalabc.net/downloads/PascalABCNETSetup.exe

В классе `ObjectWPF `определено свойство `Direction`:
`property Direction: (real,real) read (Dx,Dy) write (Dx,Dy) := (value[0],value[1]);`

т.е. если я правилно понял разработчиков, здесь всё-таки будет ошибка:
`Нельзя преобразовать тип Tuple<integer,integer> к Tuple<real,real>`

Значит, нужно исправить на:
`Key.Left: c.Direction := (-5.0, 0.0);`

Но почему, в последней версии, у меня осталось старое сообщение об ошибке?

**Comment by miks1965** [comment]
А какая у вас версия .NET установлена? Мы замечали, что эта ошибка как-то с ней связана.

**Comment by SunSerega** [comment]
![image](https://user-images.githubusercontent.com/27270190/90343522-bf821900-e019-11ea-9ac0-9fab34d2a26a.png)

**Comment by miks1965** [comment]
У вас всё понятно - у вас всё работает

**Comment by izhaks** [comment]
@miks1965 
У меня установлен и используется .NET версии 4.8.3752.0

![image](https://user-images.githubusercontent.com/42379993/90369604-c2f6be00-e074-11ea-869f-10009e300061.png)
