### ISSUE TITLE
Любая графика (или хотя бы clrscr) в Линукс.

### ISSUE THREAD

**Issue by andreykl** [pascalabcnet/pascalabcnet#2293]
Здравствуйте!
Спасибо всем участникам за вашу работу.

Возник вопрос. Есть ли хоть какая то графика в ОС Линукс?
При попытке подключить `GraphABC` или `GraphWPF` (т.е. просто в тексте программы `uses GraphABC;` например), получаю сообщение вида
`Error at reading PCU file '/usr/share/pascalabcnet/Lib/GraphABC.pcu'`.
При попытке использовать `crt` `[2,6] 1.pas: Unit 'crt' not found`.

Вопросы.
Это проблема неудачной версии или под Линукс нет графики вообще?
Есть ли аналог модуля `crt`? В первую очередь интересует `clrscr` или какой-то способ начать вывод сверху чтобы затереть текущий текст пробелами.

Цель - позволить ученику написать примитивную игру, можно используя псевдографику. Освоили переменные, условный оператор, циклы и кажется что было бы очень интересно использовать это в реальном проекте (на сколько это возможно для 6-7го класса).

Спасибо!

**Comment by andreykl** [comment]
Вы знаете, не в обиду будет сказано ни вам ни мне, но я справку проглядывал, перед тем как написать первую программу. 
Мне видится что если человек не знаком с платформой .net (как я, например), то вряд ли, на мой взгляд, он догадается что Console пришла из .net.
Скорее логично найти какую-то отсылку в документации. Но на нет и суда нет, можно и спросить.
Хотя конечно, если предполагается что каждый пользователь abcpascal.net должен быть уверенным программистом на языках семейства .net, то я как бы поднимаю руки. Тогда мне конечно понятны коннотации  некоторых ваших сообщений и действительно мне не стоило задавать вопросов. Но тогда, чтобы избегать подобных ситуаций, вероятно нужно указать с самого верха в справке крупными буквами что то вроде "Если вы не знаете .net, не задавайте потом вопросов". Или как то так.

Хочу просто пояснить свою позицию: в целом у меня претензий никаких нет. Я благодарен авторам за возможность пользоваться проектом и вам за ответ в том числе. И мне немного непонятен ваш тон, честно говоря. Может быть я где то был не аккуратен в выражениях. Тогда прошу прощения.

Ещё раз предыстория: мне нужна была графика. Я пошёл в справку. Нашёл примеры. Они не заработали. uses crt не заработал тоже (в целом это вполне ожидаемо). Я предполал что линукс не основная платформа, тем не менее раз есть сборка и на офф сайте на неё ссылка, решил задать вопрос. Поскольку на гитхабе нет никаких ссылок на списки рассылки/чаты, то задал в ишьюсах. Получил совет, который меня полностью устраивает. Спасибо большое ещё раз.

**Comment by SunSerega** [comment]
> Хотя конечно, если предполагается что каждый пользователь abcpascal.net должен быть уверенным программистом на языках семейства .net, то я как бы поднимаю руки.

Нет, я имел в виду что преподаватель должен сначала знать - на что учеников подсаживает ;)

В наш век, теоретически, всё ещё можно использовать каменные инструменты в центре москвы, но никто этим не страдает. И даже школах этому не учат.
Так же и в PascalABC.Net - можно, к примеру, по-старинке делать свалку переменных в общем `var` до `begin`, но это плохо. Так не только выполнение значительно медленнее, но и ошибки легче допускать.

Вот чтоб учить какому-нибудь Turbo Pascal - надо понимать основные особенности языка, ещё до того как начинать самому учится писать на нём.

А ученикам знать что такое .Net сразу - вообще не обязательно. Можно, максимум, сказать что это не единственный .Net язык + что все .Net языки похожи, поэтому когда обучитесь - на что то промышленное как C# будет особо просто пересаживаться.

Кстати, разработчики ещё пишут отдельную статью специально для учителей: https://pascalabcnet.github.io/mydoc_for_school_teachers.html
Несколько параграфов всё ещё пустые, но полезной информации уже полно.

> мне не стоило задавать вопросов

Вопросы задавать можно и надо, главное не перед личным поиском информации.

> Может быть я где то был не аккуратен в выражениях.

Нет, это скорее я часто не аккуратен, не принимайте близко к сердцу.

> Поскольку на гитхабе нет никаких ссылок на списки рассылки/чаты, то задал в ишьюсах.

Кстати, @miks1965, может стоит добавить ссыль на форум? Ибо он вообще вот: http://forum.mmcs.sfedu.ru/c/pascalabcnet/10
На него уже есть ссыль на сайте - левая колонка, последняя кнопка. Но из за того что последняя - её легко не заметить...

**Comment by miks1965** [comment]
Здравствуйте!

Почитал тред. Жалко, что немного поздно.

Насчёт графики. Когда-то мы запускали под Wine - graphABC работал. Хотя конечно это не очень удачное решение. Нам даже оболочку удавалось стартовать под Wine.

http://pascalabc.net/wiki/index.php?title=%D0%9A%D0%B0%D0%BA_%D0%B8%D0%BD%D1%81%D1%82%D0%B0%D0%BB%D0%BB%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D1%82%D1%8C_PascalABC.NET_%D0%BF%D0%BE%D0%B4_Linux

Здесь описывается, как настроить оболочку Geany. Хотя весь интеллисенс конечно погибает.

По поводу модуля CRT - он древний, и по-существу является обёрткой над классом Console.

Действительно, надо пользоваться классом Console - в нём всё есть вплоть до позиционирования курсора и настройки цветов. Да, в справке этого класса нет. Ровно как и ещё более 1000 других классов .NET. Да, есть проблема перевода справки Microsoft, ориентированной на C#. Но все методы разумеется можно использовать у нас. 

Ещё конечно под Windows работает Intellisense - набрали Console, нажали точку и вывалилась куча методов с понятными названиями.

Да, надо бы описать используемые школьниками классы NET. Непонятно какие только.

Вопросы конечно лучше задавать на форуме, но здесь тоже можно - мне приходят уведомления. Но форум читает большее количество человек.

**Comment by andreykl** [comment]
SunSerega, спасибо за ответ, за ссылку на статью и за ссылку на форум. Действительно, упустил ссылку на форум, каюсь. Нашёл для себя много полезного в статье.

miks1965, спасибо за ответы. В общем Console пока полностью покрывает мои нужды, так что о графике я особо не волнуюсь. Конечно, запуск через вайн был бы наверное последним решением, но всё таки хорошо что оно существует. Может комут-то пригодится. Джини у меня настроилось автоматически при установке (я использовал deb пакеты). В этом смыле всё прошло гладко. Да, с Intellisense было бы значительно проще, но честно говоря можно глянуть в справку .net, вроде бы там довольно понятно. Благо вряд ли кому то нужна вся тысяча классов одномоментно. 

Что касается перевода документации. Мне кажется, что можно добавить в справку что то вроде модуля с названием crt_help. И в описании этого модуля дать ссылку на документацию по Console на сайте .net. Название модуля будет привлекать тех кто ищет crt.
Просто на правах идеи. 

Спасибо за проект!
