### ISSUE TITLE
Русские тексты ошибок выполнения при английской системе и английском языке IDE

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#2295]
**Внимание**: Я специально открываю в issue компилятора а не IDE, потому что в первую очередь важно - какой .exe генерирует компилятор.
А зависимость языка ошибок от языка IDE - это можно будет потом прикрутить поверх, когда эта issue будет исправлена.

---

В разделе инициализации `PABCSystem` есть эти строчки:
```
  var locale: object;
  var locale_str := 'ru-RU';
  if __CONFIG__.TryGetValue('full_locale', locale) then
    locale_str := string(locale);
  System.Threading.Thread.CurrentThread.CurrentUICulture := System.Globalization.CultureInfo.GetCultureInfo(locale_str);
```
`__CONFIG__`, наверное, задумывалось как способ управлять языком ошибок в генерируемом .exe с помощью настроек IDE, но сейчас этот словарь всегда пусть.

Таким образом `CurrentUICulture` всегда по-умолчанию ставится на русский язык, вне зависимости от настроек системы или IDE.

По моему менять язык `CurrentUICulture` имеет смысл только в том случае, если в переменной `__CONFIG__` что то будет. То есть так правильнее:
```
  var locale: object;
  if __CONFIG__.TryGetValue('full_locale', locale) then
  begin
    var locale_str := string(locale);
    System.Threading.Thread.CurrentThread.CurrentUICulture := System.Globalization.CultureInfo.GetCultureInfo(locale_str);
  end;
```
Таким образом, по крайней мере, если у пользователя стоит англо-язычная windows - все тексты ошибок будут на английском.

---

Вообще процедуру инициализации `PABCSystem` почистить бы, там много легаси кода скопилось...

**Comment by miks1965** [comment]
Смотрите. Проблема в следующем. У нас есть пользователи - школьники - у которых на беду английская Windows. Ну, такой ноутбук им достался. Но сообщения об ошибках - все - должны быть на русском.

**Comment by SunSerega** [comment]
Ну, это не меняет того факта, что на русский язык не надо переключать без причины. Ибо русские школьники явно не вся аудитория (иначе зачем вообще английская версия IDE).

Предлагаю, кроме замены кода на тот что я дал выше - вставлять в `Main()` при компиляции программы (внимание - не библиотеки), перед инициализацией всех модулей, строки вроде этих:
```
__CONFIG__['locale'] := 'ru';
__CONFIG__['full_locale'] := 'ru-RU';
```
Но делать это только если компиляция проходи из IDE. И, может, ещё добавить соответствующие аргументы консольному компилятору.

**Comment by spectatorBH** [comment]
Еще правильнее будет ввести в настройки IDE отдельную опцию "Язык ошибок времени выполнения / Runtime errors language" (под нынешней настройкой "Язык"):

* Как у среды разработки (по умолчанию) / Same as IDE language
* Как в системе / Same as OS language

А настройку "Язык / Language" переназвать "Язык среды разработки / IDE language".

**Comment by ibond84** [comment]
Поменял язык в среде на английский и запустил программу. Ошибки времени выполнения выводятся на английском. Это давным давно было реализована

**Comment by ibond84** [comment]
Даже сгенерированный exe-шник, запущенный вне среды выдает английский текст ошибки, потому что

```
  IL_0030:  ldsfld     class [mscorlib]System.Collections.Generic.Dictionary`2<string,object> PABCSystem.PABCSystem::__CONFIG__
  IL_0035:  ldstr      "full_locale"
  IL_003a:  ldstr      "en-US"
```

Закрываю issue

**Comment by ibond84** [comment]
Если в каком-то случае это не происходит, то укажите конкретные примеры

**Comment by ibond84** [comment]
А, в инсталяте не работает..

**Comment by ibond84** [comment]
В консольный компилятор не передается локаль
