### ISSUE TITLE
Основные подпрограммы для работы с decimal

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#2296]
http://forum.mmcs.sfedu.ru/t/zamechaniya-i-predlozheniya/143/1937?u=sun_serega

Как минимум - подпрограммы чтения с клавиатуры.
Не плохо бы ещё операторы вроде `+=`.

**Comment by miks1965** [comment]
Read(d) читает decimal с клавиатуры

**Comment by SunSerega** [comment]
Пожалуйста, заливайте отдельным коммитом (а не как все изменения в модулях вроде `GraphWPF` - вперемешку с другими фиксами) и сразу. А то ваш комментарий не объясняет что было сделано. Только звучит как практически ничего сделано не было, особенно по сравнению с тем что вы написали на форуме по ссылке в начале.
