### ISSUE TITLE
Readln in program using GraphABC emits "Ding"

### ISSUE THREAD

**Issue by wisemoth** [pascalabcnet/pascalabcnet#2298]
With a simple WPF program:
```
uses GraphABC;

var
    a: integer;
begin
    readln(a);
end.
```

The value `a` can be entered, but if `Enter` is pressed without clicking the Form button then a Windows "Ding" sound is emitted. This is annoying! It would be great if the default `Enter` action was the same as the clicking the form button.

I think it is the same issue as: https://stackoverflow.com/questions/6290967/stop-the-ding-when-pressing-enter

**Comment by SunSerega** [comment]
WPF (Windows Presentation Foundation) and WF (Windows Forms, which in turn uses GDI) are different libraries.
For WPF you use `GraphWPF`.

And actually you should. Support of `GraphABC` has been stopped long time ago, to focus more on `GraphWPF`.
Though you might get fix for something as small as this, there are other known problems that wouldn't get fixed.

**Comment by wisemoth** [comment]
Thanks.  The [Samples](http://pascalabc.net/en/samples)  page guided me to the `GraphABC`.

I've retried my sample code above with `uses GraphWPF`, but the `readln` doesn't appear and allow input.  A form briefly appears on the screen, then disappears and the program quickly comes to the exit - without any blocking to allow input.

**Comment by SunSerega** [comment]
> The Samples page

You should have `C:\PABCWork.NET\Samples` folder on your pc, if you're using windows and didn't redirect it in installer.

> I've retried my sample code above with uses GraphWPF, but the readln doesn't appear and allow input.

For me it works when starting in F9 mode (using input window of IDE) and crashes with "program stopped working" in Shift+F9 mode.
`GraphWPF`'s window doesn't have any build-in way of text input, you should use event handlers like `OnKeyDown` to detect keyboard input.
You can also use WinAPI `AllocConsole` (see `external` keyword) to create console window.

But why do you actually need text input in graphics application?

**Comment by wisemoth** [comment]
> You should have C:\PABCWork.NET\Samples folder on your pc, if you're using windows and didn't redirect it in installer.

I just downloaded the console compiler package, which is proving fine with VS Code and command line.

> But why do you actually need text input in graphics application?

I want to enter a few parameters for exploration of some fractals from the Becker and Dörfler book (all listings in Pascal).  It works "fine" with `GraphABC` apart from the annoying ding per original issue.  I would be happy just entering parameters in text or graphics prior to going into graphics for the fractal render.

**Comment by SunSerega** [comment]
Well, if you want something simple - you can add `Write('')` as first line of program.
`Write`-related subprograms execute `AllocConsole` when called for the first time.

**Comment by wisemoth** [comment]
I'm afraid I can't get that to work:

```
uses GraphWPF;

var
    a: string;
begin
    write('enter a: ');
    readln(a);
    write('entered: ',a)
end.
```

That doesn't allow entry in the console (or the form).  Only `Ctrl+C` quits.

However, commenting out the `uses GraphWPF` allows entry in the no-new-window-console (but then I don't have graphics / Form)

**Comment by SunSerega** [comment]
Well, what OS you actually trying to do this in? As i said, `AllocConsole` is a WinAPI function. If you're using any other OS - you need to use it's own unmaneged function for creating console window.

**Comment by wisemoth** [comment]
Indeed. I'm using Windows, and building `exe` (not sure what `winexe` is).

**Comment by wisemoth** [comment]
Many thanks for fixing this!
