### ISSUE TITLE
Duplicate enum

### ISSUE THREAD

**Issue by Elem8100** [pascalabcnet/pascalabcnet#2300]
How to allow duplicate enum? These code works fine  with Delphi. Dose ABC.net have the same feature?
```
type
  TFoo = (A, B, Foo);
  {$SCOPEDENUMS ON}
  TBar = (A, B, Bar);
  {$SCOPEDENUMS OFF} 

```

**Comment by miks1965** [comment]
Или 

type
  TFoo = enum (A, B, Foo);

**Comment by SunSerega** [comment]
Если уже добавлять такой синтаксис - может сразу разрешить указывать внутренний тип значения:
```
TFpp = int64(A, B, Foo);
```
А то получается что всё что будет делать слово `enum` - убирать значения `A`, `B` и `Bar` из пространства имён модуля. Это странно сочетается с остальным языком.

Зато если объявить это новым синтаксисом, позволяющим больше возможностей (то есть изменение внутреннего типа перечисления) - пропадание значений перечисления из пространства имён модуля будет потому что "более современных подход, не надо его сравнивать со старым синтаксисом".

**Comment by miks1965** [comment]
Закрываю. Это хотелки. Их много
