### ISSUE TITLE
Реализовать опцию /rebuild в pabcnetcclear.exe для внедрения CI/CD в проекте

### ISSUE THREAD

**Issue by spectatorBH** [pascalabcnet/pascalabcnet#2301]
Без этого невозможно доделать автоматизированную сборку и тестирование билдов (по крайней мере средствами GitHub Actions) и наладить надежную работу проекта в режиме CI/CD.

Используемый сейчас в скриптах `pabcnetc.exe /rebuild` не совместим с перенаправлением ввода/вывода, необходимого для работы консольного лога виртуальной машины.

**Comment by spectatorBH** [comment]
Немного статистики из моих предварительных экспериментов: 

1) сейчас общее время **сборки всего проекта без тестов** средствами GitHub (вместе с генерацией 3-х дистрибутивов: для Win7+, WinXP и консольного zip-варианта) ~ **6-7 минут**;
2) время такой же сборки **с полными тестами** ~ **16-17 минут**;
3) при этом компиляция непосредственно С# кода -- не более 40 cек. (повторная для .NET 4.0 -- в 2 раза быстрее), остальное -- компиляция стандартных библиотек, дистрибутивов и вспомогательные функции;
4) обычно ~ **1,5 мин** из общего времени -- технологические издержки инфраструктуры: развертывание VM, клонирование репозитория, установка зависимостей и сервисных средств, работа скриптов, а также время выгрузки готовых файлов (артефактов) во временное хранилище;
5) при значительной нагрузке на облачную инфраструктуру (зависит в т.ч. от времени суток) время работы может иногда увеличиваться: максимально я однажды наблюдал задержки общего времени на 7-9 минут (возможно, это были сервисные работы или апгрейд), но обычно колебания не превышают 1-2 минуты.
6) теоретически общее время можно сократить путем распараллеливания некоторых тестов и/или сборок под разные целевые платформы, но это уже следующий этап и поле для экспериментов;

После перевода проекта в нормальный режим CI/CD стоит подумать над автоматизацией не только тестовых сборок, но и официальных (повторяемых!) релизов с полуавтоматической генерацией сопутствующих журналов изменений и копирования бинарников на различные популярные сервисы онлайн-дистрибуции (желательно либо с полноценной цифровой подписью кода, либо хотя бы с офиц. хэшами, чтобы избежать распространения подделок, левых билдов или троянов).

**Comment by ibond84** [comment]
Для CI это не нужно. Можно вызывать pabcnetc.exe /rebuild /noconsole и в GitHub Actions все работает

**Comment by ibond84** [comment]
Работающий скрипт лежит в _RebuildReleaseAndRunTestsForGitHubActions.bat

**Comment by miks1965** [comment]
Закрываю
