### ISSUE TITLE
Шаблонный operator implicit даёт BadImageFormatException

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#2303]
```
type
  t1 = class
    static function operator implicit<T>(val: T): t1 := nil;
  end;
  
begin
  var a: t1 := 5;
end.
```
```
Ошибка времени выполнения: System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Исключение из HRESULT: 0x8007000B)
Стек:
   в Program1.Program.$Main()
   в Program1.Program.Main()
```
IL:
```
  .method public static void
    $Main() cil managed
  {
    .maxstack 1
    .locals init (
      [0] class Program1.t1 V_0,
      [1] class Program1.Program V_1
    )

    IL_0000: nop

    // [25 7 - 25 33]
    IL_0001: ldc.i4.5
    IL_0002: call         class Program1.t1 Program1.t1::op_Implicit<!!0/*M0*/>(!!0/*M0*/)
    IL_0007: stloc.0      // V_0
    IL_0008: ret

  } // end of method Program::$Main
```
То есть вместо того чтоб вычислить шаблонный тип `T` из выражения `5` - компилятор берёт первый шаблонный тип `Main`. Но `Main` не шаблонная подпрограмма, поэтому JIT падает при попытке загрузить эту строчку.

**Comment by SunSerega** [comment]
Вообще это не единственная проблема, `T` берёт откуда угодно, но не из типа всего выражения.
К примеру:
```
type
  t1 = class
    static function operator implicit<T>(val: T): t1;
    begin
      Writeln(typeof(T));
    end;
  end;
  
  t2<T> = class end;
  
begin
  var a: t1 := new t2<integer>;
end.
```
Тут уже берёт типа шаблона `t2`, то есть `integer`. А надо `t2<integer>`. Это в отдельную issue или всё связано?

**Comment by SunSerega** [comment]
И ещё 1 до кучи:
```
type
  t1 = class
    static function operator implicit<T>(val: T): t1;
    begin
      Writeln('rec');
    end;
    static function operator implicit<T>(val: ^T): t1;
    begin
      Writeln('ptr');
    end;
  end;
  
  t2<T> = class end;
  
begin
  var i := 5;
  var a: t1 := @i;
end.
```
Тут тоже `BadImageFormatException`, но тут ещё другая проблема поверх - выбирает первую перегрузку оператора `implicit`, хотя она никаким боком тут не подходит. Должно выбирать перегрузку, принимающую указатель.

**Comment by SunSerega** [comment]
А сказать что то отдельные ошибки? Неужели так сложно?

**Comment by ibond84** [comment]
>Неужели так сложно?

Сложно. Не надо в одном issue рассказывать про 3 разные ошибки

**Comment by SunSerega** [comment]
А с моей точки зрения, не закапываясь в дебри компилятора - это всё одна и та же история, появляющаяся в разных местах.
Были случаи когда я такое сувал в разные issue а вы начинали рассказывать что я пложу issue, поэтому я теперь заранее спрашиваю.
Нечего игнорировать. Важную информацию об ошибках компилятора несёт не только самое первое сообщение.

**Comment by ibond84** [comment]
Нет это разные проблемы. Лучше уж создавайте лишнюю issue. Одна проблема - одна issue.
