### ISSUE TITLE
Генерация forward-предописания в yield и методы расширения

### ISSUE THREAD

**Issue by miks1965** [pascalabcnet/pascalabcnet#231]
При развёртке yield генерируется зачем-то предописание функции. Мне кажется, оно лишнее. Потестить и убрать

**Comment by miks1965** [comment]
Оно не лишнее - оно нужно, если функция с yield - рекурсивная. Но в случае extension-методов это приводит к падению. Подумать.

**Comment by miks1965** [comment]
Это не работает:
```
function f(self: integer): sequence of integer; extensionmethod;
begin
  yield 1;
end;

begin
  
end.
```

**Comment by ibond84** [comment]
Ну правильно не работает. forward-описания extension-методов запрещены (по техническим причинам). Надо сразу реализовывать метод.

**Comment by ibond84** [comment]
Надо запрещать yield в extension-методах. Проблема обходится просто
```
function ff: sequence of integer;
begin
   yield 2;
   yield 3;
   yield 4;
end;
function f(self: integer): sequence of integer; extensionmethod;
begin
  Result := ff;
end;

begin
  var i: integer;
  foreach var ii in i.f do
  begin
    writeln(ii);
  end;
end.
```

**Comment by miks1965** [comment]
Нет, тут тоньше. yield в extension-методах делать можно - тут не надо предописания. Но если в этом методе есть рекурсия, то сгенерированный код не откомпилируется. То есть, надо одновременно проверять extension и рекурсию. Предописания нужны только чтобы рекурсия работала.

**Comment by ibond84** [comment]
Странно, падает здесь (b\Yield\SyntaxVisitors\YieldVisitors\MarkMethodHasYieldVisitor.cs) с ошибкой последовательность не имеет элементов

var FirstTypeDeclaration = ee.defs.DescendantNodes().OfType<type_declarations>().First();

**Comment by ibond84** [comment]
а ee.defs.DescendantNodes().OfType<type_declarations>() может же не иметь элементов
