### ISSUE TITLE
Генерирует неправильную программу при подставлении шаблонного типа вместо T при вызове operator implicit

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#2311]
```
type
  t1 = class
    static function operator implicit<T>(val: T): t1;
    begin
      Writeln(typeof(T));
    end;
  end;
  
  t2<T> = class end;
  
begin
  var a: t1 := new t2<integer>;
end.
```
Выводит `Int32`, а должно `t2<Int32>`.

Из серии: #2303, #2311, #2312

**Comment by miks1965** [comment]
Это нельзя записать в C#

**Comment by ibond84** [comment]
Ну в C# много чего нельзя записать

**Comment by ibond84** [comment]
Тем более перестанут работать HashSet

class function operator implicit<T>(s: TypedSet): HashSet<T>;

**Comment by SunSerega** [comment]
@miks1965 недавно ibond закрыл одной строчкой issue, которая у вас была "на пол месяца работы". И это исправило большинство проблем с таким `operator implicit`.

Хватит говорить запрещать всё что вам не хочется исправлять. Запрещать шаблонный `operator implicit` потому что эта issue мешает - никаким боком не лезет. Он довольно маленькая часть минимального кода и много что может сам по себе.

Я на составление минимального кода к таким issue обычно трачу от 30 до 60 минут (особенно если забуду что уже была похожая issue, как в данном случае). А вы посмотрите, испугаетесь и "а может лучше всё запретить и не парится?". Для меня это выглядит как ленивая и необдуманная идея, очень обидно такое слышать.

**Comment by SunSerega** [comment]
> Тем более перестанут работать HashSet

И весь `OpenCLABC`, там очень давно всё держится шаблонном `operator implicit`.

**Comment by SunSerega** [comment]
Возможно поздно, но вот код из #2312:
```
type
  t1 = class
    static function operator implicit<T>(val: T): t1;
    begin
      Writeln('rec');
    end;
    static function operator implicit<T>(val: ^T): t1;
    begin
      Writeln('ptr');
    end;
  end;
  
begin
  var i := 5;
  var a: t1 := @i;
end.
```
До этого фикса он снова выдавал `rec` вместо `ptr`. Скажите сразу - после этого фикса он исправился?

**Comment by miks1965** [comment]
@SunSerega вы должны понимать, что компиляторы не всесильны. И критерий для нас, несомненно, C# - если он не может, то никто не может.

А то что Вы хотите это записать в вашей программе - понимаю. Но это не повод реализовывать гиблые вещи, без которых можно обойтись.

Ещё раз загляните на Лицевую сайта - полгода назад мы обновили миссию PascalABC.NET как учебного языка, и силы будем вкладывать в другое.

Данный Issue не может разумеется оставаться - и либо исправим - если просто - либо выдадим ошибку и закроем

**Comment by SunSerega** [comment]
> И критерий для нас, несомненно, C# - если он не может, то никто не может.

Он у вас критерий только когда вам это удобно. А когда не удобно - не критерий.
Но он таки много что не может, как статические индексные свойства. При чём по той же причине почему и шаблонный `operator implicit` - потому что непонятно как красиво сделать в минималистичном синтаксисе C#.

> А то что Вы хотите это записать в вашей программе - понимаю.

А вот и нет. Реализовать кишки `OpenCLABC` без шаблонного `operator implicit` легко.
А реализовать удобный интерфейс, простой для новичков - сложно и требует жертв читабельности в коде, использующем `OpenCLABC`.

Весь смысл `OpenCLABC` (относительно модуля `OpenCL`) в том, чтоб его можно было использовать не зная практически ничего. А вы своими учебными упрощениями, особенно как в #2392 - наоборот задираете планку вхождения в модуль.

Когда дело только во внутренностях моего кода (и пока есть возможность обойти ограничение, даже если более сложным кодом) - я так сильно по этому поводу не прыгаю.
