### ISSUE TITLE
menubar item in russian

### ISSUE THREAD

**Issue by steve64** [pascalabcnet/pascalabcnet#2317]
In the IDE release 3.7.1 the last item under the Tools popup menu is written in Russian. It would be better to translate it in English.

**Comment by SunSerega** [comment]
![image](https://user-images.githubusercontent.com/27270190/94947971-33ec1b00-04e7-11eb-8ee6-215cc5ad15d1.png)

Please add screenshots to have more details on what you mean.

**Comment by steve64** [comment]
Below the screenshot.
Regards,
Stefano
[cid:f714df8b-b78e-4bd4-aedd-5ee2a601a776]
________________________________
Da: Sun Serega <notifications@github.com>
Inviato: venerdì 2 ottobre 2020 18:42
A: pascalabcnet/pascalabcnet <pascalabcnet@noreply.github.com>
Cc: steve64 <s_antoniaz@hotmail.com>; Author <author@noreply.github.com>
Oggetto: Re: [pascalabcnet/pascalabcnet] menubar item in russian (#2317)


[image]<https://user-images.githubusercontent.com/27270190/94947971-33ec1b00-04e7-11eb-8ee6-215cc5ad15d1.png>

Please add screenshots to have more details on what you mean.

**Comment by SunSerega** [comment]
It didn't attach. Please post via github account, not email.

**Comment by miks1965** [comment]
![изображение](https://user-images.githubusercontent.com/10325391/94962580-5c800f00-04ff-11eb-9be9-cdf625174e7e.png)
In English as you see

**Comment by steve64** [comment]
I do not know why on my PC I see it in Russian... just that menu item...
Not a so big issue anyway.

**Comment by miks1965** [comment]
Please check VisualPascalABCNET.dat in "C:\Program Files (x86)\PascalABC.NET\Lng\Eng"\

Check two lines:

M_FORMAT=Format Code
M_UNIT_TESTS=Run unit tests

**Comment by miks1965** [comment]
Maybe install the last version of PascalABC.NET

**Comment by steve64** [comment]
Hi Stanislav,

I added the line:
M_UNIT_TESTS=Run unit tests
in file VisualPascalABCNET.dat and this solved the issue.

Anyway, I'm using version 3.7.1. Is there a new one?

Many thanks and nice weekend,
Stefano A.

[cid:a869c080-33d4-41cc-ab09-c9b59d0feb0a]

________________________________
Da: Mikhalkovich Stanislav <notifications@github.com>
Inviato: sabato 3 ottobre 2020 09:30
A: pascalabcnet/pascalabcnet <pascalabcnet@noreply.github.com>
Cc: steve64 <s_antoniaz@hotmail.com>; Author <author@noreply.github.com>
Oggetto: Re: [pascalabcnet/pascalabcnet] menubar item in russian (#2317)


Please check VisualPascalABCNET.dat in "C:\Program Files (x86)\PascalABC.NET\Lng\Eng"\

Check two lines:

M_FORMAT=Format Code
M_UNIT_TESTS=Run unit tests

**Comment by SunSerega** [comment]
There is an actual button for checking for updates... In the last popup menu.

**Comment by steve64** [comment]
Thanks. I have updated.
