### ISSUE TITLE
Некоторым свойствам стандартных типов не показывает полный тип

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#2320]
```
uses System.Windows.Media.Animation;

{$reference PresentationFramework.dll}
{$reference PresentationCore.dll}
{$reference WindowsBase.dll}

{$apptype windows}

begin
  var ac: AnimationClock;
  ac.CurrentTime;
end.
```
Нескольким свойствам `ac`, в том числе `ac.CurrentTime`, показывает тип `Nullable<>`.
То есть не видно какой тип самих значений у этого свойства.

**Comment by miks1965** [comment]
Перенесите это в ветку IDE - это к языку не отностися

**Comment by SunSerega** [comment]
А, да, извините забыл. Хотя переносить и вы можете, при чём не пересоздавая issue...

**Comment by SunSerega** [comment]
https://github.com/pascalabcnet/pascalabcnetide/issues/199
