### ISSUE TITLE
Symantec false positives

### ISSUE THREAD

**Issue by steve64** [pascalabcnet/pascalabcnet#2329]
Since today I'm starting to get false positive alerts from Symantec Endpoint Protection for some 
of my applications that are EXEs generated by me from Pascal ABC.Net.
Any hints on how to overcome this issue?
Any signing strategy?
Clearly I can't submit to Symantec for whitelisting since I'm changing often such apps.

**Comment by miks1965** [comment]
It's not our problem:

https://www.virustotal.com/gui/url/65bc6041964df16c5f393e5ff37fb1f8c0817c0db50e8324271a475d4565766f/detection

All is clean

**Comment by SunSerega** [comment]
The question was about .exe files generated by compiler, not compiler itself.

But IMO it's still a problem with antivirus. Good antiviruses detect when program is generated by some compiler.

**Comment by miks1965** [comment]
Maybe it is necessary to set some folder as a non-checkable for empirical antivirus analysis.

**Comment by steve64** [comment]
Unfortunately, in general, my users can't set folders as non-checkable by antivirus for a company policy.
I know it's not a problem with the compiler by itself, it's a false positive by the Symantec antivirus.
I just hoped that something could be done when generating exes, like adding a signature / certificate.
Thanks anyway for your kind feedback
