### ISSUE TITLE
Vim support

### ISSUE THREAD

**Issue by nikifkon** [pascalabcnet/pascalabcnet#2331]
Здравствуйте,
Насколько я понял, в текущей версии программы PascalABC.NET нельзя использовать функцию эмулятора консольного редактора VIM. Мне и, я думаю, многим, не хватает этой функции, которая присутствует в большинстве современных IDE или хотя бы доступна в виде дополнения.

Надеюсь люди, которые поддержат эту идею.

**Comment by miks1965** [comment]
Здесь пишутся баги языка. 
Желания усовершенствовать как-то оболочку здесь не пишутся
