### ISSUE TITLE
MoveBy

### ISSUE THREAD

**Issue by miks1965** [pascalabcnet/pascalabcnet#2339]

**Comment by miks1965** [comment]
Сделано

**Comment by SunSerega** [comment]
Пожалуйста, цепляйте коммит, даже если это не исправление бага:
https://github.com/pascalabcnet/pascalabcnet/commit/562699d3fa0fa6426e316efe174e6b727c5ea236
Вам не сложно (ибо issue сама закрывается) + тем кто следит за обновлениями так проще увидеть что именно это значит.
