### ISSUE TITLE
"Неизвестное имя 't1' " на строчке с объявлением класса t1, если использовать его как аргумент лямбды в модуле, где t1 не видим

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#2343]
```
uses u1;

begin
  p1(a->exit());
end.
```
```
unit u1;

uses u2;

procedure p1(p: t1->()) := exit;

end.
```
```
unit u2;

type
  //Ошибка: Неизвестное имя 't1'
  t1 = class end;
  
end.
```
[0.zip](https://github.com/pascalabcnet/pascalabcnet/files/5556071/0.zip)

**Comment by ibond84** [comment]
Ну здесь надо выдавать ошибку: "подключите модуль u2". Доподключение модулей в процессе компиляции технически невозможно. Этим занимается другая сборка вообще.

**Comment by ibond84** [comment]
Параметр {0} имеет тип {1} из неподключенного модуля {2}. Добавьте модуль {2} в секцию uses.
