### ISSUE TITLE
"o->()->0" не компилируется, если по 0 надо вычислить тип шаблона

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#2345]
```
procedure p0<TOtp>(f: real->Func0<TOtp>) := exit;

begin
  //Ошибка: Неверный тип переменной, которой присваивается лямбда-выражение
  p0(
    o->()->0
  );
end.
```

**Comment by SunSerega** [comment]
Пока что, в качестве костыля, можно писать так:
```
procedure p0<TOtp>(f: real->Func0<TOtp>) := exit;

function make_func<TOtp>(f: ()->TOtp) := f;

begin
  p0(
    o->make_func( ()->0 )
  );
end.
```

**Comment by miks1965** [comment]
В C# то же самое: 
![изображение](https://user-images.githubusercontent.com/10325391/99856763-bfeefa80-2b9a-11eb-842d-49b1b38ad5d1.png)

**Comment by SunSerega** [comment]
Так а при чём тут что в C# не реализовали? В данном случае это точно не значит что такое определение типа невозможно реализовать.

**Comment by SunSerega** [comment]
Да, и кроме того, в паскале сейчас выдаётся затычка вместо ошибки. И в паскале, в отличии от C#, есть такой синтаксис:
```
procedure p0<TOtp>(f: real->Func0<TOtp>) := exit;

begin
  //Ошибка: Неверный тип переменной, которой присваивается лямбда-выражение
  p0(
    o->function:integer->0
  );
end.
```
Тут нет вообще никакой неопределённости, но код всё равно не компилируется.

**Comment by SunSerega** [comment]
Да, а про неопределённость я говорю потому - что так уже давно компилируется:
```
procedure p0(f: real->Func0<integer>) := exit;

begin
  //Ошибка: Неверный тип переменной, которой присваивается лямбда-выражение
  p0(
    o->()->0
  );
end.
```
То есть такая конструкция поддерживается, просто не до конца.

**Comment by miks1965** [comment]
Не забывайте, что PascalABC.NET - это учебный язык, и область применения подобных конструкций равна нулю.

Кроме того, мы всегда приглашаем для реализации сложных вещей потратить время сторонних разработчиков

**Comment by SunSerega** [comment]
Тогда, по крайней мере, не закрывайте issue, пока не найдётся тот, у кого есть время (или пока не появится у меня).

А насчёт редкости применения этой конструкции - её чуть ли не всюду в `System.Threading.Tasks` можно вставить.
Ну, с `Task`-ами я ещё как то её избегал, а в этот раз она мне понадобилось для реализации аналога `Parallel.ForEach` (`Parallel.While`, который не существует) с парой особых фич.
Там кода на 20 строк и ничего такого, чем можно было бы напугать ваших новичков.

**Comment by miks1965** [comment]
Посмотрите, как это делается в C#

**Comment by SunSerega** [comment]
Не совсем понимаю где смотреть, в `System.Threading.Tasks` находятся определения функций, а не их вызов с помощью лямбд. Но я так понимаю - в C# эти перегрузки вызываются без лямбд.
