### ISSUE TITLE
Sum(Self: sequence of BigInteger) конкурирует с обычной Sum

### ISSUE THREAD

**Issue by miks1965** [pascalabcnet/pascalabcnet#2348]
```
function Sum(Self: sequence of BigInteger): BigInteger; extensionmethod;
begin
  //Result := 0bi;
  //foreach var a in Self do
  //  Result += a
end;

begin
  //var a := Arr(1bi,2bi,4bi);
  //a.Sum.Print;
  var lst := new List<integer>();
  lst.Sum.Print;
end.
```

**Comment by SunSerega** [comment]
Опять же, закрывайте, пожалуйста, коммитом.

Я ещё, на свою голову, собрал собственный билд с этой проблемой...
Когда issue закрывается - подписавшимся на почту приходит напоминание. Поэтому если бы вы закрыли эту issue коммитом - я бы сразу заметил что надо собрать новый билд.
