### ISSUE TITLE
Определение функции не считает коротким, если в её теле есть ??

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#2350]
```
//Ошибка: Только в коротких определениях функций можно не указывать тип возвращаемого значения 
function f1(b0: boolean?) :=
b0 ?? true;

begin end.
```

**Comment by SunSerega** [comment]
Изменение текста ошибки - это, в данном случае, не исправление проблемы. Код из заголовка правильный и должен компилироваться.

И текст ошибки был более правильный. В коротких функциях где возвращаемый тип нельзя вычислить - есть такая ошибка:
```
//Ошибка: Тип возвращаемого значения функции f1 не определен и не может быть выведен в данный момент. Укажите тип явно.
function f1(x: integer) := f1(x);

begin end.
```
А вы "исправили" абсолютно правильную ошибку, не исправив проблему из данной issue.

Вас никто не торопит, что касается таких мелочей как эта. Поэтому, пожалуйста, если нет времени нормально разобраться - не порьте язык.

**Comment by miks1965** [comment]
В некоторых случаях у нас действительно нельзя вывести. Это как раз тот случай. Синтаксический сахар создаёт несколько узлов - функция перестаёт быть короткой. Ошибка действительно должна быть более общая

**Comment by SunSerega** [comment]
Вот более нормальная ошибка, для случая с похожим синтаксическим сахаром:
```
function f1(x: integer?) := x?.ToString;

begin end.
```
`Выражение с ?. не может фигурировать в коротком определении функции без возвращаемого значения`

А ошибка которую изменили вы - правильная в куче других случаев, которые не стоит менять.

---

Но, по моему, ошибку про отсутствия возвращаемого значения надо давать ещё перед раскрытием сахара, на уровне синтаксиса (то есть после имени функции и параметров должно быть или `:=`, или `: слово`), а после разворачивания синтаксического сахара возвращаемый результат можно вычислять используя алгоритм, который уже описан для лямбд.

Ну, это можно сделать и потом, а сейчас главное вернуть нормальную ошибку в других случаях + добавить объясняющую ошибку в данном случае. Ну или использовать ту же что для `?.` , она хотя бы говорит что мешает.

**Comment by spectatorBH** [comment]
По-моему, текст последней ошибки не совсем корректный, поскольку не бывает функций без возвращаемого значения, но бывают функции без *явно указанного типа* возвращаемого значения. Может быть, лучше так:

``Выражение с ?. не может фигурировать в коротком определении функции без *явного типа* возвращаемого значения``
