### ISSUE TITLE
div и mod неверно работают с отрицательными числами

### ISSUE THREAD

**Issue by Jakupov** [pascalabcnet/pascalabcnet#2351]
Пример:
`###
pr(-78 div 33, -78 mod 33)`

выводит `-2 -12`, тогда как остаток должен лежать между `0` и `32`

Пример на python:
`print(-78 // 33,-78 % 33)`

выводит `-3 21`

**Comment by SunSerega** [comment]
А в `C++` и `C#` выводит так же как в паскале.
В частности, потому что `C#` и паскаль используют один и тот же IL оператор для `div` и `mod`.

Я вам больше скажу:
```
uses GraphWPF;

begin
  DrawGraph(x->System.Math.IEEERemainder(x,2));
end.
```
Это уже метод .Net, применяемый как в паскале, так и в C#.

В какую сторону делать округление результата `div` - это вкусавщина. Главное что `(x div d) * d + (x mod d) = x`.

**Comment by Jakupov** [comment]
Ясно, значит понятия остатка от деления различаются в в математике и программировании.
Насчет вкусовщины не согласен, код, ведущий себя по разному в зависимости от языка программирования, это лишняя головная боль. Но опять же, раз проблема в .Net, то здесь issue лишний.
