### ISSUE TITLE
При сортировке строк неверно сортируется дефис

### ISSUE THREAD

**Issue by Jakupov** [pascalabcnet/pascalabcnet#2352]
```
###
var a:=|'a','-','-a'|;
a.Sort;
a.Prln;
var b:=|'b','+','+b'|;
b.Sort;
b.Prln;
```
Вывод:
```
- a -a

+ +b b

```

**Comment by SunSerega** [comment]
0. В программиронии это обычно минус а не дифис...

1. Вы делаете поспешные выводы насчёт того, как вам оно должно сортироваться. Дело не в минусе, а в плюсе. Читайте справку вместо того чтоб гадать:
https://docs.microsoft.com/en-us/dotnet/api/system.string.compare?view=netframework-4.8

2. Зажмите Ctrl и тыкните на `.Sort`, чтоб посмотреть как оно реализовано. Там напрямую вызывается метод .Net, поэтому паскаля реализация этой процедуры не касается.

3. Не пишите в issue то что не является однозначной проблемой компилятора. Для обсуждений правильно использовать форум:
http://forum.mmcs.sfedu.ru/t/pomoshh-novichkam/263/2707

Не забудьте закрыть за собой эту issue как прочитаете.

**Comment by Jakupov** [comment]
Относительно строк чаще применяется дефис, а не минус. Что касается плюса, то запятая (код 44), сортируется так же, как и плюс (код 43). И в принципе, как и должно сортироваться, по ASCII коду символов.
Судя по ссылке на документацию, проблема как раз в дефисе, он игнорируется, как soft hyphen. Ну раз так задумано в .Net, то и фиксить не вам, согласен.
Про форум не знал, просто заметил неверное, в моем понимании, поведение и создал issue. Видимо, ту так не работает, прошу прощения.

**Comment by SunSerega** [comment]
> по ASCII коду символов.

В .Net символы храняться в кодировке Unicode.
