### ISSUE TITLE
Range(1,10).Sum(e -> e); - опять не работает

### ISSUE THREAD

**Issue by miks1965** [pascalabcnet/pascalabcnet#236]
```
begin
  var t := Range(1,10).Sum(e -> e);
end.
```
Program1.pas(3) : Несколько подпрограмм могут быть вызваны

**Comment by ibond84** [comment]
Здесь конфликт s ```Nullable<integer>```

**Comment by miks1965** [comment]
Да, я понимаю. Вроде это делалось. Посмотрю.
