### ISSUE TITLE
Функция MinMax из модуля School выдает неверный результат в отсортированном по убыванию массиве.

### ISSUE THREAD

**Issue by Jakupov** [pascalabcnet/pascalabcnet#2362]
Пример:
```
uses school;
begin
var a:=arr(10,9,8,7,6);
a.Println;
minmax(a).Println
end.
```
Результат:
```
10 9 8 7 6
(6,-2147483648) 
```
Причина:
Блок else не выполняется.
Соответственно, функция выдаст неверный результат, если первый элемент последовательности максимальный, а остальные строго меньше.

**Comment by SunSerega** [comment]
Вообще, алгоритм этой функции неправильный ещё и потому, что выдаёт `(integer.MaxValue, integer.MinValue)` для пустых последовательностей, вместо ошибки.
Если пользователь хочет получить какое-то особое значение для пустой последовательности - он использует `.DefaultIfEmpty`.

**Comment by SunSerega** [comment]
Предлагаю убрать все текущие перегрузки `MinMax` и заменить на это:
```
function MinMax<T>(self: sequence of T): (T, T); extensionmethod;
  where T: System.IComparable<T>;
begin
  var enmr: IEnumerator<T> := self.GetEnumerator;
  
  //ToDo Текст исключения + может свой класс
  if not enmr.MoveNext then raise new System.InvalidOperationException;
  var min := enmr.Current;
  var max := min;
  
  while enmr.MoveNext do
  begin
    var curr := enmr.Current;
    
    if curr.CompareTo(min) < 0 then
      min := curr else
    if curr.CompareTo(max) > 0 then
      max := curr;
    
  end;
  
  Result := (min, max);
end;

function MinMax<T>(self: sequence of T?): (T?, T?); extensionmethod;
  where T: record, System.IComparable<T>;
begin
  var min: T? := nil;
  var max: T? := nil;
  
  foreach var curr in self do
  begin
    if curr=nil then continue;
    
    if (min=nil) or (curr.Value.CompareTo(min.Value) < 0) then
      min := curr;
    
    if (max=nil) or (curr.Value.CompareTo(max.Value) > 0) then
      max := curr;
    
  end;
  
  Result := (min, max);
end;

begin
  Arr(1,2,3).MinMax.Println;
  Arr(3,1,2).MinMax.Println;
  Arr(3,2,1).MinMax.Println;
end.
```
Правда, вторая перегрузка (для `Nullable`) сейчас не будет работать из за #2364.

**Comment by SunSerega** [comment]
@miks1965 а что не так с моей реализацией?

**Comment by AlexRnD61** [comment]
А чего же не предлагаете заодно перегрузить Enumerable.Min и Enumerable.Max из .NET которые для пустых последовательностей выбрасывают исключение? А также и другие свертки, которые не любят пустых последовательностей?

**Comment by SunSerega** [comment]
> А чего же не предлагаете заодно перегрузить Enumerable.Min и Enumerable.Max из .NET которые для пустых последовательностей выбрасывают исключение?

Вы мне? У них уже есть перегрузки и для `T` (бросающие исключения) и для `T?` (дающие `nil` для пустых последовательностей). По аналогии с ними и делал.

**Comment by AlexRnD61** [comment]
```
##
var a:= new List<integer>;
a.Min.Print
```

**Comment by SunSerega** [comment]
> Попробуйте это:

Ну и что? Я же говорю, чтоб возвращало `nil` - достаточно преобразовать в `integer?`:
```
##
var a := new List<integer>;
Print( a.Cast&<integer?>.Min );
```
> Я намеренно стараюсь в реализации библиотеки School не выйти за пределы подмножества языка, использованного в книге "PascalАВС.NЕТ: Выбор школьника" с тем, чтобы дети при желании смогли понять соотвествующие фрагменты кода.

Хорошо, тогда можно добавить перегрузки с основными типами вместо `T`. Так даже эффективнее будет, хотя кода и больше.
Но возвращать `integer.MinValue`/`integer.MaxValue` для пустой последовательности - это однозначно неправильно, не учите плохому.

Есть ещё что то, что не прописано в вашей книге? Перегрузку для `Nullable` можно не брать в счёт.

**Comment by AlexRnD61** [comment]
Вы хотите сказать, что "классический школьный алгоритм" нахождения минимума терминированной нулем последовательности 
```
begin
  var min := MaxInt;
  while True do
  begin  
    var m := ReadInteger;
    if m = 0 then
      break
    else
      if m < min then
        min := m
  end;
  Print(min)
end.
```
это "учить плохому", потому что он не возвращает nil, если сразу же ввести 0 ? Ну тогда слава богу, что Вы не преподаете школьникам информатику.

**Comment by SunSerega** [comment]
У этого алгоритма надо, хотя бы, исправить вывод:
```
if min=MaxInt then
  Print('Элементов нет') else
  Print(min);
```
Вот только, при вводе `2147483647 0` эта программа всё ещё не даст никакую объясняющую ошибку, а спокойно выведет неправильный результат.

В таких алгоритмах, конечно, всегда можно обработать все крайние ситуации. Но новички всегда отмахиваются от такого, со словами "я пока учусь, поэтому сейчас и так сойдёт". В итоге они учатся плодить мелкие, но жутко сложно-ловимые баги.

Конечно, такие алгоритмы более быстрые. И в них был смысл на старых компьютерах. Но в наш век - это плохая практика.

На самом деле, в ванильном варианте, правильно иметь что то типа отдельной булевой переменной, как `FirstElement`, которая становится `false` после того как хотя бы 1 элемент был обработан. В таком случае обработать крайние ситуации становится предельно просто.

Но именно эту роль в моей реализации выполняет `Nullable<T>`. Оно как раз хранит поле типа `T` + поле типа `boolean`. Вот только в него встроена куча синтаксического сахара. И его легко возвращать как 1 значение.

И - как я и сказал в предыдущем сообщении, может не достаточно явно, но я не говорю добавлять `Nullable` в подпрограммы, принимающие `sequence of integer`, то есть без `Nullable`. Это и неправильно. Главное - не возвращать `integer.MinValue`/`integer.MaxValue` там, где это не правда. В вашем случае правильнее будет кидать исключение, если элементов нет.

**Comment by miks1965** [comment]
Автор School - @AlexRnD61 
Насколько я понимаю, модуль School должен читаться школьниками и быть им привычным.
Насколько я понимаю, минимум пустой последовательности - камень преткновения. Тут для пустой последовательности конечно стоит кидать исключение. Например, в ситуации MinMax(a.Where(x->x>100)). Пограничные значения здесь только всё ухудшают. Но - автор модуля - не я.

**Comment by SunSerega** [comment]
> Автор School - @AlexRnD61

Да, я согласен. Но хотел чтоб меня сначала услышали, вместо того чтоб резко реагировать на все мои слова...

> Ну тогда слава богу, что Вы не преподаете школьникам информатику.

Особенно считая что этот модуль всё активнее используют на куберфоруме.

**Comment by miks1965** [comment]
Резко реагировать - плохо.

Вы - дело говорите. Но код - профессиональный, а модуль школьный. Именно поэтому надо оговорить красную черту. Например, не использовать Nullable, MoveNext и использовать по возможности простые алгоритмы.

С @AlexRnD61 у меня тоже нет согласия во всём. Например, он из-за поддержки странноватой конструкции ReadSeqInteger отказался делать алгоритм MinMax двухпроходным. А казалось бы - просто верни (s.Min, s.Max) - и в школьном модуле этого более чем достаточно. И читается хорошо.
