### ISSUE TITLE
Сделать постфикс 'a's

### ISSUE THREAD

**Issue by miks1965** [pascalabcnet/pascalabcnet#2366]
'a's - строка из одного символа

**Comment by SunSerega** [comment]
А `case string(...) of 's': ` вы оставите? Или это как более широко-применимая замена ему?

**Comment by ibond84** [comment]
А может лучше $'a'? На данный момент это компилируется как символ, что неправильно. Надо компилировать как константную строку.

**Comment by miks1965** [comment]
Да, делаем $'a' имеющим тип string и закрываем Issue

**Comment by AlexRnD61** [comment]
> Да, делаем $'a' имеющим тип string и закрываем Issue

Ну будет потом в заблуждение вводить заголовок issue? Время пройдет, вдруг захочется проверить работу "постфикса" ?
