### ISSUE TITLE
При вызове метода, чьи перегрузки имеют в качестве аргументов procedure и object, выбирается неправильная перегрузка

### ISSUE THREAD

**Issue by AIexandrKotov** [pascalabcnet/pascalabcnet#2368]
Код библиотеки ClassLibrary1.dll ([ClassLibrary1.zip](https://github.com/pascalabcnet/pascalabcnet/files/5720159/ClassLibrary1.zip)):

```
using System;

namespace ClassLibrary1
{
    public class Class1
    {
        public static void p(object o) => Console.Write(111);
        public static void p(Action o) => Console.Write(222);
    }
}
```

Код на паскале:
```
{$reference 'ClassLibrary1.dll'}

procedure x := exit;

begin
  ClassLibrary1.Class1.p(x); //111, а ожидалось 222
end.
```

Поведение в C#:
![image](https://user-images.githubusercontent.com/44296606/102699756-03f02080-4269-11eb-9984-55d854629dcc.png)

Поведение в PascalABC.NET:
![image](https://user-images.githubusercontent.com/44296606/102699777-36018280-4269-11eb-8fb0-e884a7276446.png)

**Comment by miks1965** [comment]
То же самое:

```
procedure p(x: Object) := Print(1);
procedure p(x: Action0) := Print(2);

procedure x := exit;

begin
  p(x); //111, а ожидалось 222
end.
```

**Comment by ibond84** [comment]
https://github.com/pascalabcnet/pascalabcnet/actions/runs/507327545
