### ISSUE TITLE
Yield: захват нестатического поля из статического метода - должна быть ошибка

### ISSUE THREAD

**Issue by miks1965** [pascalabcnet/pascalabcnet#237]
```
type 
  A = class
    v := 2;
    class function f: sequence of integer;
    begin
      var a := 1;
      yield a+v;
    end;
  end;

begin
  A.f.Print;
end.
```
Ошибку надо диагностировать на раннем этапе

**Comment by miks1965** [comment]
Это происходит потому что в ErrorCheckerHelper не проверяется именно содержимое yield - в syntax_tree_visitor узел yield вообще не обрабатывается.

**Comment by miks1965** [comment]
Нет, всё хуже. ErrorCheckerHelper тут ни при чём. Поле <>4__self: A; не инициализируется поскольку метод - статический, после чего <>4__self.v выдаёт ошибку при выполнении

**Comment by ibond84** [comment]
До сих пор падает. git pull сделал
