### ISSUE TITLE
Предложения различных математических подпрограмм

### ISSUE THREAD

**Issue by Anonymous87549236** [pascalabcnet/pascalabcnet#2370]
[Математические подпрограммы.pas.zip](https://github.com/pascalabcnet/pascalabcnet/files/5726129/pas.zip)

**Comment by Anonymous87549236** [comment]
Ещё можно добавить приведение Fraction к Decimal и вычисление иррациональных чисел с округлением с заданной точностью.

**Comment by miks1965** [comment]
Предложения мы не делаем в Issue
