### ISSUE TITLE
Re: Проводится лишняя инициализация записи

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#2377]
Продолжение #1166.

Конструктор - это не единственное что можно присвоить переменной типа записи.
Инициализацию надо пропускать когда переменной присваивается вообще что угодно.

---

```
type
  r1 = record 
    public function InitI1:integer;
    begin
      Result := 1;
      writeln('Поле i1 инициализировалось');
    end;
    
    public i1: integer := InitI1;
    public i2: integer;
    
  end;
  
function f1 := default(r1);

begin
  var a := f1;
  Writeln(a);
end.
```
`default(r1)` это значение типа `r1`, где все поля обнулены (то есть и не инициализированы).
Значение в `a`, в итоге, оказывается правильное, но перед этим делает 2 лишние инициализации:
1. Для переменной `a`;
2. Для переменной `Result` внутри `f1`.

---

```
type
  r1 = record 
    public function InitI1:integer;
    begin
      Result := 1;
      writeln('Поле i1 инициализировалось');
    end;
    
    public i1: integer := InitI1;
    public i2: integer;
    
    public constructor(i2:integer) :=
    self.i2 := i2;
    
    public static function operator implicit(i: integer): r1 := new r1(i);
    
  end;
  
begin
  var a: r1 := 5;
  Writeln(a);
end.
```
Тут `i1` инициализирует:
1. Для локальной переменной `a`, ещё до присвоение;
2. Для переменной `Result` оператора `implicit`;
3. Внутри конструктора.

По моему надо оставить только инициализацию внутри конструктора - во всех остальных случаях значение сразу же перезаписывается и поэтому инициализация лишняя.

---

```
type
  r1 = record 
    public function InitI1:integer;
    begin
      Result := 1;
      writeln('Поле i1 инициализировалось');
    end;
    
    public i1: integer := InitI1;
    public i2: integer;
    
  end;
  
begin
  var a: r1 := (i1: 2; i2: 3);
  Writeln(a);
end.
```
А тут саму локальную переменную `a` инициализирует сразу дважды, перед тем как выкинуть все эти предыдущие значения и перезаписать инициализатором записи `(i1: 2; i2: 3)`.
В данном случае все инициализации надо убрать.

**Comment by ibond84** [comment]
>По моему надо оставить только инициализацию внутри конструктора - во всех остальных случаях значение сразу же перезаписывается и поэтому инициализация лишняя.

Нет, Result инициализируется всегда. Так что должно быть две инициализации

**Comment by SunSerega** [comment]
Ну, в принципе да, потому что может быть так:
```
type
  t1 = record
    x: byte;
    
    function Next: t1;
    begin
      Result.x := self.x+1;
    end;
    
  end;
  
function f1: t1 := Result.Next;

begin end.
```
Но если запретить использовать `Result` в коротких определениях функций - можно будет не инициализировать `Result` для них.

**Comment by ibond84** [comment]
Нет, короткие функции это просто синтаксический сахар. Не надо там никаких исключений

**Comment by SunSerega** [comment]
А определить что первое использование `Result` находится после первого присвоения `Result := ` (или использования вообще нет) - это уже слишком большое усложнение?
