### ISSUE TITLE
Чтение поля t0 из переменной типа T; where T: t0 - выводит мусор, если эта переменная захвачена лямбдой

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#2395]
Продолжение #2247, всё ещё воспроизводится если захватить `o` лямбдой:
```
type
  // Не обязательно auto класс, я добавил только ради конструктора
  t0 = auto class
    f: byte;
  end;
  
procedure p1<T>(o: T); where T: t0;
begin
  Writeln(o.f); // Выводит мусор (обычно просто 0) вместо 123
  
  var p := procedure->
  begin
    var o2 := o;
  end;
  
end;

begin
  p1(new t0(123));
end.
```

**Comment by miks1965** [comment]
А это точно не дубль? По моему было такое. Просмотрите пожалуйста свои Issue, а то вы уже дважды кинули повторные

**Comment by SunSerega** [comment]
Вы не про #2247? Ну, я же специально оставил ссылку на него в заголовке.

Дубли у меня были потому что issue быстро исправлялись и я во всём запутывался, но в данном случае - эту issue я нашёл пока убирал костыли от #2247, поэтому это более узкий случай той issue, а значит пересекаться ему не с чем.

**Comment by ibond84** [comment]
https://github.com/pascalabcnet/pascalabcnet/actions/runs/475467411
