### ISSUE TITLE
"Несоответствие атрибутов partial-класса" если у него есть предописание

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#2422]
```
type
  t1 = class;
  
  //Ошибка: Несоответствие атрибутов partial-класса
  t1 = sealed partial class end;
  
begin end.
```
Можно вообще запретить предописания `partial` классов, потому что всегда можно сделать так:
```
type
  t1 = sealed partial class end;
  
  //OK
  t1 = sealed partial class end;
  
begin end.
```
Но и ошибку тогда надо давать соответствующую.

**Comment by ibond84** [comment]
Да, запретить предописания partial-классов

**Comment by SunSerega** [comment]
У вас теперь тесты фейлятся, потому что неймспейсы используют пред-описания `partial` классов...

**Comment by ibond84** [comment]
Исправил
