### ISSUE TITLE
Компилируется при изменении модификатора доступа перегружаемого метода

### ISSUE THREAD

**Issue by AIexandrKotov** [pascalabcnet/pascalabcnet#2423]
```
type
  T1 = class
    protected procedure p(); virtual := exit;
  end;
  
  T2 = class(T1)
    public procedure p(); override := exit;
  end;
```

Это компилируется.

Поведение в C#:
![image](https://user-images.githubusercontent.com/44296606/106726782-d47c5400-661b-11eb-9ba5-ff41847fef08.png)

**Comment by ibond84** [comment]
Ну, в паскале нельзя только понижать уровень доступа. И в справке это написано

>При переопределении виртуального метода в подклассе его уровень доступа должен быть не ниже, чем в базовом классе. Например, public виртуальный метод не может быть переопределен в подклассе private-методом.
