### ISSUE TITLE
Компилятор видит методы partial класса, описанные в implementation

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#2424]
```
uses u0;

begin
  t1.Create.p1;
end.
```
```
unit u0;

interface

type
  t1 = partial class end;
  
implementation

type
  t1 = partial class
    procedure p1 := exit;
  end;
  
end.
```
Тут, по крайней мере, не согласовано с анализатором кода - он не видит `t1.p1` в основной программе.

Но я считаю что это проблема компилятора. Если что-либо описано только в `implementation`, без предописания в `interface` - его не должно быть видно вне модуля. Хотя бы потому что иначе можно делать такую жуть:
```
uses u0;

begin
  t1.Create.f1.p1;
end.
```
```
unit u0;

interface

type
  t1 = partial class end;
  
implementation

type
  t0 = class
    procedure p1 := exit;
  end;
  
  t1 = partial class
    function f1 := new t0;
  end;
  
end.
```

**Comment by miks1965** [comment]
Нет. Partial классы как и методы расширения работают безотносительно к модулям. Их содержимое видно отовсюду в рамках проекта. Partial классы создавались ровно для поддержки принятых в NET концепций и не соответствуют концепциям Delphi. Их подобное использование в модулях - на страх и риск использующего.

Если будете настаивать, мы вообще запретим Partial-классы.

**Comment by SunSerega** [comment]
О, класс, теперь вы ещё и шантажируете меня? Чего вы, думаете, добьётесь этим?
У меня есть своё мнение смертно юзвера, но я стараюсь чтоб оно не выглядело как "сделайте как я хочу", выделяя его в абзацы вроде "но я считаю" и начиная issue с того - что можно было бы улучшить.
А вы видите только "лишь бы он отстал со своими ишьями"?

Можно было бы хотя бы выслушать меня и подумать "как лучше", а не "как проще ничего не менять".
То есть, в данном случае, можно хотя бы принять во внимание как можно было бы заставить эти две концепции взаимодействовать и какие с этим проблемы. И хотя бы попытаться заставить их работать вместе, языку от этого хуже не будет.

Или, если у вас нет времени, или даже просто лень - можно сейчас оставить как есть и закинуть в долгий ящик. Это явно не критичный вопрос.

Да и, на самом деле, если вы видите больше проблем взаимодействия `partial`-классов и модулей - лучше услышать несколько точек зрения.
Я пока нашёл только это столкновение и подумал что есть простое решение которое полностью его исправит, поэтому написал сразу в issue.

**Comment by ibond84** [comment]
Ну описывайте с модификатором private. Какие проблемы. Ведь члены обычных классов, описанных в implementation имеют видимость internal

**Comment by miks1965** [comment]
Не шантажируем конечно. partial классы не удастся полностью подружить с модулями - это взаимно противоречащие концепции. Поэтому примите это.

Issue я закрываю. Тут всё правильно.

**Comment by SunSerega** [comment]
> partial классы не удастся полностью подружить с модулями - это взаимно противоречащие концепции. Поэтому примите это.

Как вы можете говорить это, не рассмотрев варианты? Это пофигистично-линивое отношение.
