### ISSUE TITLE
При загрузке разорванного (между interface и implementation) partial-класса из .pcu теряется конструктор

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#2425]
[0.zip](https://github.com/pascalabcnet/pascalabcnet/files/5923894/0.zip)
```
uses u0;

begin
  new t1;
end.
```
```
unit u0;

interface

type
  t1 = partial class
    public constructor := exit;
  end;
  
implementation

type
  t1 = partial class end;
  
end.
```
Если компилировать основную программу из папки - первая компиляция проходит успешно, а вторая говорит что у `t1` нет конструкторов.

Ну и, что важнее - если сделать активной программу и запускать модуль, то ошибка проявляется при первой компиляции.

**Comment by ibond84** [comment]
Исправилось с фиксом #2432
