### ISSUE TITLE
В подпрограмму передаёт nil вместо вызова operator implicit, если передавать TPointer(nil), где TPointer - тип указателя

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#2436]
```
type
  t0 = class end;
  
  t1 = class
    static function operator implicit(p: t0): t1 := new t1;
  end;
  
procedure p1(o: t1) := Writeln(o);

begin
  p1(t0(nil));
end.
```

**Comment by miks1965** [comment]
Здесь всё правильно. nil у нас особого типа, и явное приведение типа не делает её переменной другого типа - она остаётся nil. Если хотите получить нужный эффект, присвойте nil типизированной переменной

**Comment by SunSerega** [comment]
Не придумывайте, преобразование типа всегда меняет тип выражения:
```
procedure p1<T>(o: T) := Writeln(typeof(T));

begin
  p1(string(nil));
end.
```

**Comment by SunSerega** [comment]
Вообще то что говорите - правда только на этапе выполнения. Но на этом этапе (если не вызывается `operator explicit`) - явное преобразование типа не делает вообще ничего:
```
type
  t1 = class end;
  t2 = class(t1) end;
  
begin
  var a := new t2;
  var b := t1(a);
end.
```
Если вы декомпилируете - увидите что никакого преобразования тут нет, переменной типа `t1` присваевается значение типа `t2`.

---

На этапе компиляции это не так. Преобразование типа всегда преобразует тип, иначе толку от него.

**Comment by SunSerega** [comment]
И то что вы делали своим ответом - вы придумывали красивое правило чтоб объяснить почему всё правильно.
Даже если это правило вы придумали раньше и даже если оно вам очень нравится - это неправильно.
Это всё равно что говорить "переменные в диалектах паскаля всегда должны быть до `being`, всегда так было, значит только так и правильно".
Принимать решение надо исходя из других факторов.

**Comment by ibond84** [comment]
В C# кстати вызывается оператор преобразования типов

```
class t0 
	{
		
		public static void p1(t0 o)
		{
		}
		
		public static implicit operator t0(t1 x)
		{
			return new t0();
		}
		
	}
	
	class t1
	{
	}
	
	
	class Program
	{
		public static void Main(string[] args)
		{
			t0.p1((t1)null);
			Console.Write("Press any key to continue . . . ");
			Console.ReadKey(true);
		}
	}
```

**Comment by SunSerega** [comment]
А, кстати да, минимальный код не нуждается в указателях:
```
type
  t0 = class end;
  
  t1 = class
    static function operator implicit(p: t0): t1 := new t1;
  end;
  
procedure p1(o: t1) := Writeln(o);

begin
  p1(t0(nil));
end.
```
Так тоже выводит `nil` вместо `t1`.

**Comment by ibond84** [comment]
https://github.com/pascalabcnet/pascalabcnet/actions/runs/586326524
