### ISSUE TITLE
Не может вычислить тип возвращаемого значения лямбды, при использовании синтаксиса "var f := function->..."

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#2443]
```
## var f1 := function(x: real) -> x*x;
```
`Ошибка: Невозможно вывести типы параметров лямбда-выражения, так как явно не указан тип переменной, которой присваивается лямбда-выражение`

Типы параметров не надо выводить, они уже указаны.
Но я так понимаю имеется в виду тип возвращаемого значения - которое таки можно вычислить, лямбды его постоянно вычисляют из типов параметров.

**Comment by miks1965** [comment]
В C# это тоже не работает. Ошибка выводится, она правильная.

**Comment by SunSerega** [comment]
В смысле в C#, в нём вообще есть соответствующий синтаксис?

И каким образом ошибка правильная? Тут тоже?
```
## var f1 := function() -> 5;
```
Типы каких, по вашему, параметров тут сейчас не может вывести?

И, что важнее, в чём проблема их вывода?

Я серьёзно не понимаю зачем вы заходите в issue, закрываете парочку со словами "не, это мы не будем делать" и дальше уходите по своим делам, ничего по сути не сделав.

**Comment by ibond84** [comment]
Надо указывать параметр возвращаемого значения явно, если неизвестен тип делегата. Это основное правило. Все
