### ISSUE TITLE
Класс TypeConverter не является атрибутом.

### ISSUE THREAD

**Issue by derevyaga-sn** [pascalabcnet/pascalabcnet#2447]
Возникает ошибка компиляции "Класса TypeConverter не является атрибутом"
'''
program an_issue;

uses
  System.ComponentModel;

type
  MyClassConverter = class (TypeConverter)
    
  end;
  
  MyClass = class
  private
    fMyField: MyClass;
  public
    [TypeConverter(typeof(MyClassConverter))]
    property MyProperty: MyClass read fMyField;
  end;

begin
  
end.
'''

**Comment by SunSerega** [comment]
Между двумя классами `TypeConverterAttribute` и `TypeConverter` выбирает последний, хотя подходит только первый.

**Comment by SunSerega** [comment]
@derevyaga-sn справа снизу от окна написания ответа есть иконка:
![image](https://user-images.githubusercontent.com/27270190/108162185-3d240000-70f5-11eb-81c8-6700f0a20929.png)
Тыкните её чтоб научиться нормально вставлять код и т.п.

Вы используете кавычку, а надо обратный апостроф (который в англ. раскладке за ё).

**Comment by miks1965** [comment]
В PascalABC.NET выбирается в первую очередь класс с совпадающим именем. Всё правильно.
