### ISSUE TITLE
Локаль консольного компилятора отлична от системной. 

### ISSUE THREAD

**Issue by TheGreatHalva** [pascalabcnet/pascalabcnet#2453]
Здраствуйте. Пытался под линуксами писать на PABC и заметил вот такую вещь. Консольный компилятор по какой-то причине выводит всё на украинском, хотя локаль системы - английский США.
```
$ pabcnetcclear foo.pas
Відсутній файл 'foo.pas'

~/D/Inf
$ locale
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE=C
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=

~/D/Inf
$ 
```
Болячка такая и у портативной консольной версии, и у консольной версии из deb-пакета, пропущенного через debtap в Арче.

**Comment by TheGreatHalva** [comment]
### UPD.

Свежескомпилированный PABC тоже страдает этим.

**Comment by ibond84** [comment]
Обновитесь, откомпилируйте заново и проверьте

**Comment by ibond84** [comment]
Проверил на убунте. Работает
