### ISSUE TITLE
Необработанное исключение: System.IO.IOException: Неверный дескриптор при использовании pabcnetcclear и перенаправления ввода\вывода

### ISSUE THREAD

**Issue by ankutalev** [pascalabcnet/pascalabcnet#2454]
Минимальный репродьюсер:
`cat task.pas`
```
uses Crt;
begin
  Delay(5);
  Writeln('hello!');
end.

```

`pabcnetcclear task.pas && task.exe`  -  работает как надо.
`pabcnetcclear task.pas && task.exe > "output.txt"`  
Выдает следующее:

> Необработанное исключение: System.IO.IOException: Неверный дескриптор.
> 
>    в System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
>    в System.Console.set_CursorSize(Int32 value)
>    в CRT_implementation______.CRT_implementation______.__InitModule()
>    в task.Program.$_Init_()
>    в task.Program.Main()

Возможно, схоже с #118.

**Comment by miks1965** [comment]
Модуль Crt не предназначен для использования с перенаправлением ввода-вывода
