### ISSUE TITLE
Не работает operator implicit для преобразования к set of integer

### ISSUE THREAD

**Issue by miks1965** [pascalabcnet/pascalabcnet#2457]
```
function operator implicit(s: integer): set of integer; extensionmethod;
begin
end;

begin
  var s: set of integer := 1;
end.
```

**Comment by miks1965** [comment]
То же в этой ситуации:
```
function operator implicit<T>(s: T): array of T; extensionmethod;
begin
end;

begin
  var s: array of integer;
  s := 1;
end.
```
Для необобщённого типа работает

**Comment by SunSerega** [comment]
И для указателей тоже:
```
function operator implicit<T>(s: T): ^T; extensionmethod;
begin
end;

begin
  var s: ^integer;
  s := 1;
end.
```
То есть из всего набора типов, использующий `T` как подтип, работают только шаблонные классы:
```
type
  t1<T> = class end;
  
function operator implicit<T>(s: T): t1<T>; extensionmethod;
begin
end;

begin
  var s: t1<integer>;
  s := 1;
end.
```
Ну и это не первый раз - весь набор `t1<T>`, `^T` и `array of T` реализован как то несвязно, так что исправление одного всегда оставляет такой же баг в другом (то есть надо все 3 отдельно исправлять). По моему стоит стандартизировать.

**Comment by ibond84** [comment]
Дело не в множествах, а в том, что implicit для откомпилированных типов к паскалевским не работает
