### ISSUE TITLE
partial-классы требуют статические методы

### ISSUE THREAD

**Issue by derevyaga-sn** [pascalabcnet/pascalabcnet#2463]
Компиляция приведённого ниже кода завершается ошибкой **"Program1.pas(24) : Mетод DoSomething не является статическим для типа T1"**
```
type
  T1 = partial class
    constructor Create;
    begin
      
    end;
    
    procedure DoSomething;
    begin
      
    end;
  end;
  
  T1 = partial class
    procedure DoSomethingElse;
    begin
      
    end;
  end;
  
begin
  
  var obj := new T1;
  T1.DoSomething;
  T1.DoSomethingElse;
  
end.
```

**Comment by SunSerega** [comment]
А при чём тут `partial` классы? Это с любыми так.
Изучите базовый синтаксис ООП. И конкретно это лучше было бы спросить [на форуме](http://forum.mmcs.sfedu.ru/c/pascalabcnet/10).

**Comment by derevyaga-sn** [comment]
> А при чём тут `partial` классы? Это с любыми типами так.

Ну как же. Вот этот код такой ошибки не производит
```
type
  T1 = class
    constructor Create;
    begin
      
    end;
    
    procedure DoSomething;
    begin
      
    end;
  end;
  
begin
  
  var obj := new T1;
  T1.DoSomething;

end.
```

> Изучите базовый синтаксис ООП. И конкретно это лучше было бы спросить [на форуме](http://forum.mmcs.sfedu.ru/c/pascalabcnet/10).

При всём уважении, не надо меня посылать. То там спроси, то тут напиши. И что это за базовый синтаксис в котором мне нужно каждый метод объявлять `static`?

**Comment by SunSerega** [comment]
> Вот этот код такой ошибки не производит

У меня производит.

> `И что это за базовый синтаксис в котором мне нужно каждый метод объявлять static?`

```
type
  T1 = class
    x: byte;
    
    constructor(x: byte) :=
    self.x := x;
    
    procedure DoSomething :=
    Writeln(x);
    
  end;
  
begin
  
  var o1 := new T1(1);
  var o2 := new T1(2);
  T1.DoSomething;
  
end.
```
Не_статические методы это те, которые используют экземпляр, то есть то что создано с помощью `new`.
Раз тут два экземпляра - что должно выводить `T1.DoSomething`?

**Comment by derevyaga-sn** [comment]
>Не_статические методы это те, которые используют экземпляр, то есть то что создано с помощью new.
Это я прекрасно помню. Спасибо, вопрос закрыт.
