### ISSUE TITLE
"Среда выполнения обнаружила недопустимую программу", если попытаться сравнить на равенство запись, у которой нет соответствующего оператора сравнения

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#2474]
```
type
  r1 = record
    val: integer;
    static function operator=(o1: r1; o2: integer) := false;
  end;
  
begin
  var o: r1;
  var b := o = o;
end.
```
```
Ошибка времени выполнения: System.InvalidProgramException: Среда выполнения Common Language Runtime обнаружила недопустимую программу.
Стек:
   в ParserPas.Program.$Main()
   в ParserPas.Program.Main()
```
Этот код вызывает оператор `ceq` для сравнения, а он не может найти соответствующий `operator=` внутри `r1`.
Я так понимаю, стандартный оператор сравнения `operator=(o1, o2: r1)` не генерируется, если определить любой пользовательский оператор сравнения.
В таком случае надо просто выдавать ошибку во время компиляции, а не выполнения.

**Comment by miks1965** [comment]
стандартный оператор сравнения для записей вообще не генерируется

**Comment by ibond84** [comment]
https://github.com/pascalabcnet/pascalabcnet/actions/runs/760396524
