### ISSUE TITLE
Split[^1] - обнаружена недопустимая программа

### ISSUE THREAD

**Issue by miks1965** [pascalabcnet/pascalabcnet#2475]
```
begin
  'asd fas dfa'.Split[^1].Print
end.  
```
System.InvalidProgramException: Среда выполнения Common Language Runtime обнаружила недопустимую программу.

Так работает: 
```
begin
  'asd fas dfa'.Split()[^1].Print
end.  
```

**Comment by ibond84** [comment]
https://github.com/pascalabcnet/pascalabcnet/actions/runs/760319043
