### ISSUE TITLE
begin Create end: Нельзя вызвать конструктор через объект

### ISSUE THREAD

**Issue by miks1965** [pascalabcnet/pascalabcnet#2476]
```
type A = class
  constructor Create(x: integer) := begin Create end;
end;

begin
  
end.
```
constrInh.pas(2) : Нельзя вызвать конструктор через объект

Так можно:
```
type A = class
  constructor Create(x: integer) := Create;
end;

begin
  
end.
```

**Comment by SunSerega** [comment]
Это из за `:=` перед `begin`. Его разворачивает в ещё 1 пару `begin-end`, то есть:
```
  constructor Create(x: integer) := Create;
```
это
```
  constructor Create(x: integer);
  begin
    Create;
  end;
```
Тем временем
```
  constructor Create(x: integer) := begin Create end;
```
это
```
  constructor Create(x: integer);
  begin
    begin
      Create
    end;
  end;
```
То есть чтоб заставить это работать - надо проверять что перед `Create` небыло собственно выполняющих что-либо операторов, а не как сейчас - то что он является самым первым оператором самого первого блока.

**Comment by miks1965** [comment]
Да, точно
