### ISSUE TITLE
Лишняя инициализация записи для переменной foreach

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#2480]
```
type
  t1 = record
    private function InitA: integer;
    begin
      System.Environment.StackTrace.Println;
      Result := ReadInteger;
    end;
    
    public a := InitA;
    public b: integer;
    
    public constructor(b: integer) := self.b := b;
    private constructor := raise new System.InvalidOperationException;
    
  end;
  
begin
  var l := new List<t1>;
  l += new t1(2);
  l += new t1(3);
  foreach var o in l do
    ;
end.
```
`foreach` объявляет `var o: t1` и решает его сразу инициализировать пустым конструктором.
Эта переменная всегда перезаписывается перед первым использованием, поэтому её нет смысла инициализировать.
Если проблема в том что это всё сахар - надо изначально присваивать `var o := default(t1)`.

**Comment by ibond84** [comment]
Сделано. Actions что-то зависли. Прогнал тесты у себя
