### ISSUE TITLE
Позволяет вызывать приватный конструктор, если он пустой

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#2481]
```
unit u0;

type
  t1 = record
    
    public constructor(x: integer) := exit;
    private constructor := raise new System.InvalidOperationException;
    
  end;
  
end.
```
```
uses u0;

begin
  var a: t1;
end.
```
Надо выдавать ошибку, потому что тут не понятно чем инициализировать.
Если пустой конструктор приватный - надо использовать или `var a := default(t1)`, или `var a := new t1(...)`.

**Comment by ibond84** [comment]
Надо запретить непубличные конструкторы по умолчанию для записей, так как они **всегда** вызываются для инициализации записей.

**Comment by SunSerega** [comment]
> они всегда вызываются

Неправда. Я же говорю - если писать `var a := default(t1)` или `var a := new t1(5)` - дефолтный конструктор не вызывается.

**Comment by ibond84** [comment]
Ну при описании переменной вызывается. Запрещать описывать переменную или поле это нонсенс. К тому же default не проводит инициализации полей паскалевских типов (статических массивов, файлов и т.д). Поэтому ни неявное присвоение default, ни отсутствие всякой инициализации, ни тем более запрет описывать переменную не являются разумными решениями.

**Comment by ibond84** [comment]
https://github.com/pascalabcnet/pascalabcnet/actions/runs/838384395
