### ISSUE TITLE
Пример более-менее сложного проекта?

### ISSUE THREAD

**Issue by vimmerru** [pascalabcnet/pascalabcnet#2484]
Добрый вечер,

Подскажите пример более-менее сложного проекта с несколькими модулями и системой сборки для него.

**Comment by SunSerega** [comment]
Для этого есть форум: http://forum.mmcs.sfedu.ru/c/pascalabcnet/10
И нужно более конкретное объяснение что вы делаете, чтоб лучше понимать что вам надо.
