### ISSUE TITLE
Модуль School. Расширение Digits()

### ISSUE THREAD

**Issue by mskorotkov** [pascalabcnet/pascalabcnet#2485]
```
uses school;
begin
  for var num := -10 to 10 do 
    writeln(num.digits());
end.
```

при **num = 0** вывалится следующее:

> Unhandled Exception: System.NullReferenceException: Ссылка на объект не указывает на экземпляр объекта.
>    в School.School.Digits(Int64 n) в C:\Program Files (x86)\PascalABC.NET\LibSource\School.pas:строка 509
>    в School_implementation______.School_implementation______.Digits(Int32 Self) в C:\Program Files (x86)\PascalABC.NET\LibSource\School.pas:строка 524
>    в Program1.Program.$Main() в C:\PABCWork.NET\Program1.pas:строка 5
>    в Program1.Program.Main()Программа завершена, нажмите любую клавишу . . .

забыли 0 в список упаковать

**Comment by miks1965** [comment]
У вас версия наверное какая то старая. Всё работает
