### ISSUE TITLE
Could you adopt GPCP?

### ISSUE THREAD

**Issue by altPOCA** [pascalabcnet/pascalabcnet#2487]
GPCP is a Component Pascal compiler for .NET and JVM.

https://github.com/k-john-gough/gpcp

The professor developed it is well past his retirement and no longer able to actively maintaing it anymore. You developed the PascalABC.NET compiler which is very similar to what GPCP is so I'm sure you have the expertise to do this.

Please save this piece of beautiful software!

**Comment by altPOCA** [comment]
Could you at least add Component Pascal support to the PascalABC.NET IDE?

There is one commercial IDE for Component Pascal.

https://www.cfbsoftware.com/cpide/cpide.htm

But you see, the license fee is not reasonable. From the appearance of it you could clearly see it was built using the very similar technology to PascalABC.NET IDE.

**Comment by altPOCA** [comment]
Please let me know your decisions.

**Comment by miks1965** [comment]
No, PascalABC.NET is not "is very similar to what GPCP is". 

It supports "old" Pascal, but the general line of development is "new generation Pascal" with modern language extensions for simple and effective coding.

As for adding new compiler to PascalABC.NET IDE - it's a very bad idea for us. We are focused on PascalABC.NET only and we we spend a lot of efforts to convince users not to program in old pascal's style.

**Comment by altPOCA** [comment]
> No, PascalABC.NET is not "is very similar to what GPCP is".
> 
> It supports "old" Pascal, but the general line of development is "new generation Pascal" with modern language extensions for simple and effective coding.
> 
> As for adding new compiler to PascalABC.NET IDE - it's a very bad idea for us. We are focused on PascalABC.NET only and we we spend a lot of efforts to convince users not to program in old pascal's style.

Could you add the JVM as a target for the PascalABC.NET compiler? I know, the name clearly states ".NET", but adding JVM platform is a very handy feature. This library could help you manipulate Java Byte Code:

https://asm.ow2.io/

The same library being used on GPCP.

**Comment by miks1965** [comment]
No, multiplatforming isn't a purpose of our project. Our main problem now - to switch code generation to NET Core

**Comment by altPOCA** [comment]
> No, multiplatforming isn't a purpose of our project. Our main problem now - to switch code generation to NET Core

Will the IDE become cross platform? Currently there is only a compiler for Linux. I did see a .NET Core Graphical App also works on Linux. It's here:

https://github.com/VitalElement/AvalonStudio

**Comment by miks1965** [comment]
It is our dream. But our compiler is closely integrated into our IDE. The idea to use AvalonStudio as an IDE seems good but requires some untrivial efforts. But we believe that some external developer pursue our dreams!
