### ISSUE TITLE
Метод последовательностей примененный к ArraySegment<T> ломает CLR

### ISSUE THREAD

**Issue by AIexandrKotov** [pascalabcnet/pascalabcnet#2488]
```
## System.ArraySegment&<integer>.Create(new integer[1], 0, 1).Sum();
```
С помощью дебага и дополнительной переменной удалось узнать что это System.ExecutionEngineException

**Comment by ibond84** [comment]
Падает вызов метода расширения для записи. Вот пример проще
```
begin
  var seg := System.ArraySegment&<integer>.Create(new integer[1], 0, 1);
  seg.Sum();
end.
```

**Comment by ibond84** [comment]
https://github.com/pascalabcnet/pascalabcnet/actions/runs/975928071
