### ISSUE TITLE
System.Drawing.Color.FromArgb(r, g, b).ToArgb возвращает не тот цвет/Microsoft.Office.Interop.Excel принимает не тот цвет

### ISSUE THREAD

**Issue by samuraiGH** [pascalabcnet/pascalabcnet#2500]
```
{$reference 'Microsoft.Office.Interop.Excel.dll'}
{$reference 'System.Drawing.dll'}
 
begin
  var app:= new Microsoft.Office.Interop.Excel.ApplicationClass;
  var ws: Microsoft.Office.Interop.Excel.Worksheet;
  app.DisplayAlerts:=false;//отключаем диалоги

  app.Workbooks.Open('path');//открываем книгу
  ws:=app.Workbooks[1].Worksheets[1] as Microsoft.Office.Interop.Excel.Worksheet;//задаём активный лист
  
  var r:=ws.get_range('a1', 'b2');//получаем диапазон
  r.Interior.Color:=system.Drawing.Color.FromArgb(255, 0, 0).ToArgb;//задаём заливку диапазона
  app.Workbooks[1].Close(true);//сохраняем книгу
  app.Quit;
end.
```
Ожидаемо, что диапазон окрасится в красный, но на выходе получается это:
![image](https://user-images.githubusercontent.com/87191377/128678637-16abb94e-19f8-44e5-bef1-c8ecbcc3ccc5.png)
Как показывает Excel, это чистый синий:
![image](https://user-images.githubusercontent.com/87191377/128678859-2f84cb95-2c7c-4814-9435-fd8916aaabe6.png)
Сначала подумывал о несовпадении форматов данных, но поменяв 
`r.Interior.Color:=system.Drawing.Color.FromArgb(255, 0, 0).ToArgb;` на `r.Interior.Color:=system.Drawing.Color.FromArgb(0, 0, 255).ToArgb;` всё же получил в диапазоне чистый красный

Для эксперимента взял цвет Sienna с сайта https://tools.seo-zona.ru/color.html с более хаотичными значениями(160, 82, 45). 
На выходе получил:
![image](https://user-images.githubusercontent.com/87191377/128679831-8c4e4c3f-6646-4c08-af80-39be2181e377.png)
Получается, что на каком то этапе R и B действительно меняются местами

Версия компилятора: 3.8.0.2899
Версия Microsoft.Office.Interop.Excel.dll: 15.0.4569.1506
Версия System.Drawing.dll: 4.8.3761.0

**Comment by ibond84** [comment]
Ну, это ваш баг. Посмотрите здесь, как цвета передаются.

https://stackoverflow.com/questions/45321680/setting-excel-cell-colours-using-rgb-values/45321735
