### ISSUE TITLE
Не компилируются Win Forms приложения

### ISSUE THREAD

**Issue by Petrprogs** [pascalabcnet/pascalabcnet#2502]
![image](https://user-images.githubusercontent.com/76732207/130038041-aca2a1cc-9232-46ee-8368-300e934d15a6.png)

**Comment by SunSerega** [comment]
Я обновился, создал новый проект wf и откомпилировал - всё нормально.
Когда вы хотите разобраться в том что не так - надо кидать не скриншот с небольшим огрызком информации, а всё что может касаться проблемы.

То есть как минимум:
- Минимальный код для воспроизведения. Пробуйте копировать проект и убирать части кода копии, пока не найдёте без чего точно не падает.
- Весь текст ошибки. Вы можете закрыть окно внутренней ошибки и открыть панель обычных ошибок. Там нажать ПКМ на эту ошибку и кнопку копировать.

**Comment by Petrprogs** [comment]
() : Внутренняя ошибка компилятора в модуле [pabcnetc.exe] :'System.Exception: System.IO.EndOfStreamException: Чтение после конца потока невозможно.
   в System.IO.__Error.EndOfFile()
   в System.IO.BinaryReader.FillBuffer(Int32 numBytes)
   в System.IO.BinaryReader.ReadBoolean()
   в PascalABCCompiler.PCU.PCUReader.GetNamespaceFunction(Int32 offset, Boolean restore_code)
   в PascalABCCompiler.PCU.PCUReader.GetExtNamespaceFunctionByOffset(Int32 offset)
   в PascalABCCompiler.PCU.PCUReader.CreateCommonNamespaceFunctionCall()
   в PascalABCCompiler.PCU.PCUReader.CreateStatement()
   в PascalABCCompiler.PCU.PCUReader.CreateStatementList()
   в PascalABCCompiler.PCU.PCUReader.CreateStatement()
   в PascalABCCompiler.PCU.PCUReader.GetCode(Int32 offset)
   в PascalABCCompiler.PCU.PCUReader.CreateInterfaceMethod(String name, Int32 offset)
   в PascalABCCompiler.PCU.PCUReader.GetClassMethod(Int32 offset)
   в PascalABCCompiler.PCU.PCUReader.GetMethodByOffset(Int32 offset)
   в PascalABCCompiler.PCU.PCUReader.CreateMethodCall()
   в PascalABCCompiler.PCU.PCUReader.CreateCompiledConstructorCall()
   в PascalABCCompiler.PCU.PCUReader.CreateCompiledFunctionCall()
   в PascalABCCompiler.PCU.PCUReader.CreateStatement()
   в PascalABCCompiler.PCU.PCUReader.CreateStatementList()
   в PascalABCCompiler.PCU.PCUReader.CreateStatement()
   в PascalABCCompiler.PCU.PCUReader.GetCode(Int32 offset)
   в PascalABCCompiler.PCU.PCUReader.CreateInterfaceMethod(String name, Int32 offset)
   в PascalABCCompiler.PCU.PCUReader.GetClassMethod(Int32 offset)
   в PascalABCCompiler.PCU.PCUReader.GetMethodByOffset(Int32 offset)
   в PascalABCCompiler.PCU.PCUReader.CreateMethodCall()
   в PascalABCCompiler.PCU.PCUReader.CreateStatement()
   в PascalABCCompiler.PCU.PCUReader.CreateStatementList()
   в PascalABCCompiler.PCU.PCUReader.CreateStatement()
   в PascalABCCompiler.PCU.PCUReader.GetCode(Int32 offset)
   в PascalABCCompiler.PCU.PCUReader.CreateInterfaceMethod(String name, Int32 offset)
   в PascalABCCompiler.PCU.PCUReader.CreateInterfaceInClassMember(Int32 offset, String name)
   в PascalABCCompiler.TreeRealization.BasePCUReader.RestoreSymbols(SymbolInfo si, wrapped_definition_node wdn, String name)
   в PascalABCCompiler.TreeRealization.BasePCUReader.RestoreSymbols(List`1 sil, String name, Int32 index)
   в SymbolTable.ClassScope.FindOnlyInType(String name, Scope CurrentScope)
   в PascalABCCompiler.PCU.wrapped_common_type_node.find_in_type(String name, Scope CurrentScope, type_node orig_generic_or_null, Boolean no_search_in_extension_methods)
   в PascalABCCompiler.TreeConverter.syntax_tree_visitor.dot_node_as_type_ident(type_node tn, ident id_right, motivation mot)
   в PascalABCCompiler.TreeConverter.syntax_tree_visitor.visit(dot_node _dot_node)
   в PascalABCCompiler.TreeConverter.syntax_tree_visitor.convert_semantic_strong(syntax_tree_node tn)
   в PascalABCCompiler.TreeConverter.syntax_tree_visitor.visit_method_call(method_call _method_call)
   в PascalABCCompiler.TreeConverter.syntax_tree_visitor.visit(method_call _method_call)
   в PascalABCCompiler.TreeConverter.returner.visit(expression expr)
   в PascalABCCompiler.TreeConverter.syntax_tree_visitor.convert_strong(expression expr)
   в PascalABCCompiler.TreeConverter.syntax_tree_visitor.visit(procedure_call _procedure_call)
   в PascalABCCompiler.TreeConverter.syntax_tree_visitor.convert_strong(statement st)
   в PascalABCCompiler.TreeConverter.syntax_tree_visitor.visit(statement_list _statement_list)
   в PascalABCCompiler.TreeConverter.syntax_tree_visitor.convert_strong(statement st)
   в PascalABCCompiler.TreeConverter.syntax_tree_visitor.visit_program_code(statement_list program_code)
   в PascalABCCompiler.TreeConverter.syntax_tree_visitor.visit(block _block)
   в PascalABCCompiler.TreeConverter.syntax_tree_visitor.visit(procedure_definition _procedure_definition)
   в PascalABCCompiler.TreeConverter.syntax_tree_visitor.visit(declarations _subprogram_definitions)
   в PascalABCCompiler.TreeConverter.syntax_tree_visitor.visit(implementation_node _implementation_node)
   в PascalABCCompiler.TreeConverter.syntax_tree_visitor.visit_implementation(unit_module _unit_module)
   в PascalABCCompiler.TreeConverter.SyntaxTreeToSemanticTreeConverter.CompileImplementation(common_unit_node SemanticUnit, compilation_unit SyntaxUnit, unit_node_list UsedUnits, List`1 ErrorsList, List`1 WarningsList, SyntaxError parser_error, Hashtable bad_nodes, using_namespace_list interface_namespaces, using_namespace_list imlementation_namespaces, Dictionary`2 docs, Boolean debug, Boolean debugging)
   в PascalABCCompiler.Compiler.CompileUnit(unit_node_list Units, Dictionary`2 DirectCompilationUnits, unit_or_namespace SyntaxUsesUnit, String prev_path)
   в PascalABCCompiler.Compiler.CompileUnit(unit_node_list Units, Dictionary`2 DirectCompilationUnits, unit_or_namespace SyntaxUsesUnit, String prev_path)
   в PascalABCCompiler.Compiler.Compile() System.Exception: System.IO.EndOfStreamException: Чтение после конца потока невозможно.
   в System.IO.__Error.EndOfFile()
   в System.IO.BinaryReader.FillBuffer(Int32 numBytes)
   в System.IO.BinaryReader.ReadBoolean()
   в PascalABCCompiler.PCU.PCUReader.GetNamespaceFunction(Int32 offset, Boolean restore_code)
   в PascalABCCompiler.PCU.PCUReader.GetExtNamespaceFunctionByOffset(Int32 offset)
   в PascalABCCompiler.PCU.PCUReader.CreateCommonNamespaceFunctionCall()
   в PascalABCCompiler.PCU.PCUReader.CreateStatement()
   в PascalABCCompiler.PCU.PCUReader.CreateStatementList()
   в PascalABCCompiler.PCU.PCUReader.CreateStatement()
   в PascalABCCompiler.PCU.PCUReader.GetCode(Int32 offset)
   в PascalABCCompiler.PCU.PCUReader.CreateInterfaceMethod(String name, Int32 offset)
   в PascalABCCompiler.PCU.PCUReader.GetClassMethod(Int32 offset)
   в PascalABCCompiler.PCU.PCUReader.GetMethodByOffset(Int32 offset)
   в PascalABCCompiler.PCU.PCUReader.CreateMethodCall()
   в PascalABCCompiler.PCU.PCUReader.CreateCompiledConstructorCall()
   в PascalABCCompiler.PCU.PCUReader.CreateCompiledFunctionCall()
   в PascalABCCompiler.PCU.PCUReader.CreateStatement()
   в PascalABCCompiler.PCU.PCUReader.CreateStatementList()
   в PascalABCCompiler.PCU.PCUReader.CreateStatement()
   в PascalABCCompiler.PCU.PCUReader.GetCode(Int32 offset)
   в PascalABCCompiler.PCU.PCUReader.CreateInterfaceMethod(String name, Int32 offset)
   в PascalABCCompiler.PCU.PCUReader.GetClassMethod(Int32 offset)
   в PascalABCCompiler.PCU.PCUReader.GetMethodByOffset(Int32 offset)
   в PascalABCCompiler.PCU.PCUReader.CreateMethodCall()
   в PascalABCCompiler.PCU.PCUReader.CreateStatement()
   в PascalABCCompiler.PCU.PCUReader.CreateStatementList()
   в PascalABCCompiler.PCU.PCUReader.CreateStatement()
   в PascalABCCompiler.PCU.PCUReader.GetCode(Int32 offset)
   в PascalABCCompiler.PCU.PCUReader.CreateInterfaceMethod(String name, Int32 offset)
   в PascalABCCompiler.PCU.PCUReader.CreateInterfaceInClassMember(Int32 offset, String name)
   в PascalABCCompiler.TreeRealization.BasePCUReader.RestoreSymbols(SymbolInfo si, wrapped_definition_node wdn, String name)
   в PascalABCCompiler.TreeRealization.BasePCUReader.RestoreSymbols(List`1 sil, String name, Int32 index)
   в SymbolTable.ClassScope.FindOnlyInType(String name, Scope CurrentScope)
   в PascalABCCompiler.PCU.wrapped_common_type_node.find_in_type(String name, Scope CurrentScope, type_node orig_generic_or_null, Boolean no_search_in_extension_methods)
   в PascalABCCompiler.TreeConverter.syntax_tree_visitor.dot_node_as_type_ident(type_node tn, ident id_right, motivation mot)
   в PascalABCCompiler.TreeConverter.syntax_tree_visitor.visit(dot_node _dot_node)
   в PascalABCCompiler.TreeConverter.syntax_tree_visitor.convert_semantic_strong(syntax_tree_node tn)
   в PascalABCCompiler.TreeConverter.syntax_tree_visitor.visit_method_call(method_call _method_call)
   в PascalABCCompiler.TreeConverter.syntax_tree_visitor.visit(method_call _method_call)
   в PascalABCCompiler.TreeConverter.returner.visit(expression expr)
   в PascalABCCompiler.TreeConverter.syntax_tree_visitor.convert_strong(expression expr)
   в PascalABCCompiler.TreeConverter.syntax_tree_visitor.visit(procedure_call _procedure_call)
   в PascalABCCompiler.TreeConverter.syntax_tree_visitor.convert_strong(statement st)
   в PascalABCCompiler.TreeConverter.syntax_tree_visitor.visit(statement_list _statement_list)
   в PascalABCCompiler.TreeConverter.syntax_tree_visitor.convert_strong(statement st)
   в PascalABCCompiler.TreeConverter.syntax_tree_visitor.visit_program_code(statement_list program_code)
   в PascalABCCompiler.TreeConverter.syntax_tree_visitor.visit(block _block)
   в PascalABCCompiler.TreeConverter.syntax_tree_visitor.visit(procedure_definition _procedure_definition)
   в PascalABCCompiler.TreeConverter.syntax_tree_visitor.visit(declarations _subprogram_definitions)
   в PascalABCCompiler.TreeConverter.syntax_tree_visitor.visit(implementation_node _implementation_node)
   в PascalABCCompiler.TreeConverter.syntax_tree_visitor.visit_implementation(unit_module _unit_module)
   в PascalABCCompiler.TreeConverter.SyntaxTreeToSemanticTreeConverter.CompileImplementation(common_unit_node SemanticUnit, compilation_unit SyntaxUnit, unit_node_list UsedUnits, List`1 ErrorsList, List`1 WarningsList, SyntaxError parser_error, Hashtable bad_nodes, using_namespace_list interface_namespaces, using_namespace_list imlementation_namespaces, Dictionary`2 docs, Boolean debug, Boolean debugging)
   в PascalABCCompiler.Compiler.CompileUnit(unit_node_list Units, Dictionary`2 DirectCompilationUnits, unit_or_namespace SyntaxUsesUnit, String prev_path)
   в PascalABCCompiler.Compiler.CompileUnit(unit_node_list Units, Dictionary`2 DirectCompilationUnits, unit_or_namespace SyntaxUsesUnit, String prev_path)
   в PascalABCCompiler.Compiler.Compile()'

**Comment by Petrprogs** [comment]
Перед обновление все работало, код компилировался я даже изменений не вносил, после обновления такая ошибка

**Comment by Petrprogs** [comment]
Решено

**Comment by SunSerega** [comment]
> я даже изменений не вносил

Ну и что? Это не значит что пробовать изменять код это не путь к решению.
Хотя в данном случае у вас просто сломан какой то из .pcu файлов. Удалите их все, они пере-создадутся при следующей компиляции.
