### ISSUE TITLE
(nil=0) выдаёт True

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#2515]
В продолжение #2504:
```
##
var i: integer? := nil;
Writeln(i=0);
```
Пишет `True`, но это неправда.

**Comment by SunSerega** [comment]
На сколько я понял - вы для сравнения преобразовываете обе стороны `=` к `integer?`.
Если так - тогда это часть той же проблемы:
```
##
var i: integer? := nil;
var i2: integer? := 0;
Writeln(i = i2);
```
В качестве простого исправления - можно конвертировать `=` в `.Equals`:
```
##
var i: integer? := nil;
var i2: integer? := 0;
Writeln(i.Equals(i2));
```

**Comment by ibond84** [comment]
https://github.com/pascalabcnet/pascalabcnet/actions/runs/1279572104

**Comment by SunSerega** [comment]
```
type
  r1 = record end;
  
begin
  var n1, n2: r1?;
  Writeln(n1=n2);
end.
```
```
Ошибка времени выполнения: System.InvalidProgramException: Среда выполнения Common Language Runtime обнаружила недопустимую программу.
Стек:
   в Program1.Program.$Main()
   в Program1.Program.Main()
```
Кроме того, просто добавить сравнение `n1.HasValue=n2.HasValue` это не решение, потому что тогда будет лишний раз вызываться `operator=` для двух `default(r1)` - который там вообще ни к месту:
```
type
  r1 = record
    static function operator=(a,b: r1) := false;
  end;
  
begin
  var n1, n2: r1?;
  Writeln(n1=n2); // Должно быть true, без вызва r1.operator=
end.
```
