### ISSUE TITLE
Генерирует неправильный IL, если возвращаемый тип авто вычисляется по последнему выражению в ?:

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#2516]
```
##

procedure p1<T>(o: T) :=
$'T={typeof(T)}, GetType={o.GetType}'.Println;

var s := '123';
p1( false ? s : s.Take(3) ); 
```
Пишет что во время компиляции у выражения `false ? s : s.Take(3)` тип `string`, а во время выполнения - `sequence of char`.
То есть, что происходит в конкретно этом коде - последовательность `s.Take(3)` передаёт в функцию, никак не преобразовывая, и говорит функции будто это строка.
Особо хорошо видно проблему на этом коде:
```
##

procedure p1<T>(o: T);
where T: string;
begin
  o.Length.Println;
end;

var s := '123';
p1( false ? s : s.Take(3) ); 
```
Потому что он выводит мусор.

**Comment by ibond84** [comment]
Ничего не понятно

**Comment by ibond84** [comment]
Ну здесь, конечно, должна обыть ошибка компиляции

**Comment by ibond84** [comment]
Хотя нет. Общий тип должен быть sequence of char

**Comment by ibond84** [comment]
https://github.com/pascalabcnet/pascalabcnet/actions/runs/1283933828

**Comment by SunSerega** [comment]
@ibond84 `is` это проверка времени выполнения. Поэтому:
```
assert(not (l is string));
```
Этот `assert` в первом тесте ничего не проверяет. Неправильный тип то был только во время компиляции.
А среда выполнения как раз вычисляла правильно тип - это было видно из первого кода в этой `issue`.

**Comment by ibond84** [comment]
Ну, изменил тест. Хотя там все равно был еще один равнозначный тест на ошибку компиляции
