### ISSUE TITLE
Использование константного массива в модуле берёт поле вместо копии массива

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#2518]
```
unit u0;

type
  t1 = class
    public const arr: array of string = ('abc', 'def');
    
    public static procedure p1 := Println(arr);
    
  end;
  
end.
```
```
uses u0;

begin
  typeof(t1).GetFields.PrintLines;
  t1.p1;
end.
```
Выводит `nil`, потому что #2517. Но тут отдельная проблема, если посмотреть в декомпилированный код - в `Println(arr)` используется исходный массив, в то время как эта же программа но без модуля - будет использовать копию.
Проблема в том, что в паскале нет `readonly` значений, а значит этот константный массив можно будет изменить, после сохранения в не_константую переменную, если не копировать его.

**Comment by ibond84** [comment]
https://github.com/pascalabcnet/pascalabcnet/actions/runs/1431266915
