### ISSUE TITLE
"Среда выполнения обнаружила недопустимую программу", если сравнить 2 объекта типа "record?" на равенство

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#2527]
#2515 не добита. И я это в ней же добавил комментарий - можно было и не игнорировать, когда я пишу что ваши изменения ломают ранее рабочий код:
```
type
  r1 = record end;
  
begin
  var n1, n2: r1?;
  Writeln(n1=n2);
end.
```
```
Ошибка времени выполнения: System.InvalidProgramException: Среда выполнения Common Language Runtime обнаружила недопустимую программу.
Стек:
   в Program1.Program.$Main()
   в Program1.Program.Main()
```
Кроме того, просто добавить сравнение `n1.HasValue=n2.HasValue` в самом конце это в принципе не решение, потому что тогда будет лишний раз вызываться `operator=` для двух `default(r1)` - который там вообще ни к месту:
```
type
  r1 = record
    static function operator=(a,b: r1) := false;
  end;
  
begin
  var n1, n2: r1?;
  Writeln(n1=n2); // Должно быть true, без вызва r1.operator=
end.
```
Сейчас я обноражил что из за этой проблемы у меня не собирается 1 из моих последних проектов, который помогал мне искать минимальный код.
Без него будет нереально долго раскапывать 12к строк `OpenCLABC` чтоб найти минимальный код для продолжения #2510.

**Comment by ibond84** [comment]
>когда я пишу что ваши изменения ломают ранее рабочий код:

Не придумывайте. Этот код никогда не работал. issue был закрыт в сентябре, а в моем инсталляте от 31.08 такая же ошибка.

**Comment by SunSerega** [comment]
Я не придумываю, я этот код использовал. Ещё до того как `if record? = default(record)` исправили - в моём применении это было неважно, потому что я проверял `if char? = #32` и т.п.

P.S. Разобрался - тут ещё 1 похожая ошибка затесалась незаметно. Из за похожести я не побовал искать минимальный код - но теперь он в #2528.

**Comment by ibond84** [comment]
https://github.com/pascalabcnet/pascalabcnet/actions/runs/1325732922
