### ISSUE TITLE
Virus detected after compilation

### ISSUE THREAD

**Issue by Spoiledpay** [pascalabcnet/pascalabcnet#2529]
HI,
Norton reports that the compiled program has a virus and deletes the program.  
How to solve this problem. With that the program goes to quarantine?

Nome do arquivo: Hello1.exe
Nome da ameaça: Heur.AdvML.B Caminho completo: E:\Projetos\PascalNet3\Exemplo\Hello1.exe

____________________________

____________________________

Nos computadores desde 
06/10/2021 em 22:42:56

Último uso 
06/10/2021 em 22:44:58

Item de inicialização 
Não

Iniciado 
Não

Tipo de ameaça: Vírus heurístico. Detecção de ameaça com base na heurística de malware.

____________________________

Hello1.exe Nome da ameaça: Heur.AdvML.B
Localizar

Muito poucos usuários
Menos de 5 usuários da Comunidade do  Norton já usaram o arquivo.

Muito novo
Este arquivo foi divulgado menos de uma semana  atrás.

Alto
O risco deste arquivo é alto.

____________________________

Origem: mídia externa

Arquivo de origem:
Hello1.exe

____________________________

Ações do arquivo

Arquivo: E:\Projetos\PascalNet3\Exemplo\ Hello1.exe Removido
Arquivo: c:\Users\ferna\AppData\Local\microsoft\CLR_v4.0\usagelogs\ hello1.exe.log Ameaça removida
____________________________

Impressão digital do arquivo - SHA:
55d58e0a2b936b442f10296c718a9187e307adf94ae3a36d1749dacdb6f02601
Impressão digital do arquivo - MD5:
3dc994f8aeaa6d0be3e7901dbd621a4d

**Comment by miks1965** [comment]
Check the resulting exe-file on virustotan.com.
It's a false positive

**Comment by samuraiGH** [comment]
@miks1965 
> virustotan.com

virustotal.com вероятно
