### ISSUE TITLE
Optional argument error

### ISSUE THREAD

**Issue by ghost** [pascalabcnet/pascalabcnet#2530]
![image](https://user-images.githubusercontent.com/7517306/136884370-6faff2b7-2689-4ff8-a30c-f1aa425e9c5a.png)
I get an error message when I try to create a function with optional parameters

**Comment by SunSerega** [comment]
The assignment operator in pascal is `:=`, not `=`.
Also apparently `const` parameters can't have default values, though I don't see any reason for that.

**Comment by marcelomelofreitas** [comment]
in Delphi parameters default assignment operator  is "="   e not  ":="   

I'm sorry, it's just that I have a code that compiles in delphi and doesn't compile in PascalABC.NET and I can't do cross platform because of that
