### ISSUE TITLE
К типу u3.t1 позволяет обращаться как u2.t1 - без синонима в u2

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#2533]
[0.zip](https://github.com/pascalabcnet/pascalabcnet/files/7330075/0.zip)
```
unit u1;

uses u2;

type
  t1 = u2.t1;
  
end.
```
```
unit u2;

uses u3;

end.
```
```
unit u3;

type
  t1 = class end;
  
end.
```

Если не открывать `u3` в IDE, первая компиляция `u1` проходит нормально, а вторая уже даёт ожидаемую ошибку:
```
u1.pas(6) : Неизвестное имя 't1'
```

**Comment by ibond84** [comment]
https://github.com/pascalabcnet/pascalabcnet/actions/runs/1351159732
