### ISSUE TITLE
Разрешить кеш-функции без параметров

### ISSUE THREAD

**Issue by samuraiGH** [pascalabcnet/pascalabcnet#2538]
На данный момент такой код
```
[Cache]
function fun: integer;
begin end;

begin end.
```
вызывает ошибку

> Функции с атрибутом [Cache] должны иметь хотя бы 1 параметр

что неудобно при использовании глобальных переменных и ранее объявленных функций 

http://forum.mmcs.sfedu.ru/t/boltalka-pascalabc-net/2259/1791

**Comment by miks1965** [comment]
Я не пойму, зачем это нужно. Функция без параметров - это фактически константа. Пример можете привести?

**Comment by miks1965** [comment]
Не будем делать. Хороших примеров использования нет.
Ну и непонятно, что будет служит ключом словаря если нет параметров
