### ISSUE TITLE
Вызов делегата-процедуры в корне лямбды не работает, если передавать лямбду в Dispatcher.Invoke

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#2542]
Продолжение #2237, но теперь не могу воспроизвести пользовательской подпрограммой, как `p0` в той issue:
```
## {$reference WindowsBase.dll}

// Обязательно параметр
var p: byte->();

// Не могу воспроизвести пользовательской процедурой вместо .Invoke
//Ошибка: Ожидалась функция, встречена процедура Invoke
System.Windows.Threading.Dispatcher(nil).Invoke(()->p(0));
```

**Comment by miks1965** [comment]
По тому длинному тексту, который вы писали, я ничего не понял.

Видимо, в Issue вы пытаетесь сказать о двух проблемах сразу.
Тогда надо делать две Issue или чётко говорить про две проблемы. Я вижу пока неправильное сообщение об ошибке. Если оно будет таким: Ожидалась функция, встречена процедура p - вас это устроит?

Да, анализ функции из dll и функции из паскалевского модуля у нас разный. Да, может быть немного разное поведение. Это - слабость наших алгоритмов. В чем проблема?

**Comment by ibond84** [comment]
Заменить Ожидалась функция, встречена процедура Invoke на 
Ожидалась функция, встречена процедура

**Comment by ibond84** [comment]
Можно и
Ожидалась функция, встречена процедура p

**Comment by ibond84** [comment]
https://github.com/pascalabcnet/pascalabcnet/actions/runs/1431329002

**Comment by SunSerega** [comment]
У `Dispatcher.Invoke` есть и перегрузка принимающая `()->T`, и перегрузка принимающая `()->()`.
