### ISSUE TITLE
Compiler crashes with StackOverflow on sizeof(class)

### ISSUE THREAD

**Issue by BareGamer** [pascalabcnet/pascalabcnet#2555]
As discovered by @SunSerega the issue is a stackoverflow and a subsequent compiler crash after using sizeof(class), his minimal reproduction code is listed in the comment below. Another issue is that the compilation is still reported as successful and the code still can be run, even though the app won't work at all or will crash as no exe was created but the IDE still tries to run it. The original issue text is listed below.

I was making a patch for pasvulkan's vkxml2pas to compile in PascalABC and later make it generate the bindings that would include PABC too, not only Delphi or fpc. After wrestling with PABC's "specifics", such as one of the identical codeblocks compiling and the other not, the text "An unexpected error occured. Possibly an exe file is absent from the disk. Please try again" appeared in the output window. If the project is launched with logging to the console instead of the GUI, the following console window appears for a brief second before closing:
![IMG_20211105_074554](https://user-images.githubusercontent.com/78811370/140475495-89209580-ec8b-4caf-b70c-e0a53e8bb31b.jpg)
Which isn't strange, considering no exe is being output, however the text at the bottom says "compilation successful(0 lines)" and no compiler warnings are shown. A very weird issue.
Link to the project files(for reproduction purposes): https://github.com/BareGamer/vkxml2pasabc

**Comment by SunSerega** [comment]
Compiler crashes with StackOverflow. Here is minimal code:
```
type
  t1 = class
    o: t1;
  end;
  
begin
  Writeln(sizeof(t1));
end.
```

**Comment by BareGamer** [comment]
Does any sizeof(class) crash the compiler or specifically when there is a value with the type that is the class itself?
And is there a chance this is going to be fixed soon?

**Comment by SunSerega** [comment]
@BareGamer PascalABC and PascalABC.Net are different languages.
PascalABC died long ago, while PascalABC.Net is a .Net language, so the unsafe way you handle pointers in it is unacceptable - you'll have a ton of memory leaks in best case scenario.
In particular, `sizeof(class)` only works for the compatibility purposes, it makes 0 sense under .Net, because actual contents of a class are implementation dependant. And since classes are always stored by reference (so you array only contains pointers) - `MaxListSize` is also useless.

**Comment by BareGamer** [comment]
So in order for this program to compile in PABC.NET, it would require a significant rewrite?

**Comment by SunSerega** [comment]
I don't know about compile, but to make it work - yes, it needs to be written completely differently.
Don't close this issue btw, even if the idea is wrong - the compiler crash is still an issue.

**Comment by BareGamer** [comment]
Maybe I should change the name to something like "Compiler crashes because of a StackOverflow"?

**Comment by SunSerega** [comment]
Sure, but I would propose "Compiler crashes with StackOverflow on sizeof(class)".
Would also help if you prepend the first message of this issue with the info that coincides with the issue's name, marking the rest as old info.
