### ISSUE TITLE
Graph3D.Ortx doesn't work properly if used as a Rectangle3d's normal

### ISSUE THREAD

**Issue by BareGamer** [pascalabcnet/pascalabcnet#2557]
If you set a rectangle3d's normal to (1,0,0), (-1,0,0), ortx or -ortx, the rectangle just doesn't render. But if you use a slightly higher/lower value for both x and y components, it appears. This bug has been here for at least a year.
![image](https://user-images.githubusercontent.com/78811370/140638459-fe844289-c6d8-4aec-9240-5b505085ba80.png)
P.s.: it happens in at least the 3rd overload of graph3d.rectangle3d;
![image](https://user-images.githubusercontent.com/78811370/140638833-81cfc62a-716d-4a49-ba28-876d605d9f40.png)
new Vector3D((-)ortx.X-0.0000001,(-)ortx.Y-0.0000001,ortx.Z)
Now the side faces render

**Comment by miks1965** [comment]
Your Normal and Length direction are equal. Don't use in this overload normal, parallel to ortx

**Comment by BareGamer** [comment]
I was talking about an overload with the parameters x,y,z,width,height,normal,material. I'm not sure what lengthdirection has to do with it. But if it has, why do the orty and ortz parameters work correctly?

**Comment by miks1965** [comment]
Because in your situation normal=ortx is parallel to lengthdirection=ortx. If normal=orty - they aren't parallel
