### ISSUE TITLE
$mainresource сломался в последней версии

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#2558]
Не важно какой файл указать в этой директике - компилятор говорит "файл не найден".
При этом у меня есть старые файлы (ещё со времён [SAC](https://github.com/SunSerega/SAC/blob/582572ff7e73f0d38ec28fd650c733872ea9d2d9/src/SAC.pas#L1)), которые перестали компилироваться из за этого.

**Comment by ibond84** [comment]
Вы бы хотя бы файл ресурсов прикрепили

**Comment by SunSerega** [comment]
Я кинул ссылку на файл из гитхабовского репозитория, использующий неуправляемый ресурс.
Минимальный код тут не вижу смысла прикладывать - потому что из моих тестов, `$mainresource` сломан одинаково во всех ситуациях.

**Comment by samuraiGH** [comment]
хоть бы и такой. 
[res.zip](https://github.com/pascalabcnet/pascalabcnet/files/7507306/res.zip) 

тут действительно можно взять что угодно. если даже будет пустой файл, то ошибка та же самая

**Comment by samuraiGH** [comment]
по крайней мере так на 3.8.2.3016

**Comment by SunSerega** [comment]
Однако, воспроизводится только из IDE. При компиляции из папки или с дебагером из студии - не могу воспроизвести.
