### ISSUE TITLE
SetLength криво реализован для массивов указателей

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#2559]
```
## var a := new PByte[2];
SetLength(a, 1);
```
```
Ошибка времени выполнения: Длина результирующего массива недостаточна. Проверьте значения destIndex и length, а также нижние границы массива.
```

**Comment by SunSerega** [comment]
[Взято отсюда](https://www.cyberforum.ru/pascalabc-net/thread2900646.html)

**Comment by samuraiGH** [comment]
Добавлю, что не только `SetLength`, но и кортежи тоже
```pas
##
var a:= new pointer[3];
var b:= a[0:2];
```

> С данным списком формальных параметров невозможно вызвать ни одну из перегруженных generic-подпрограмм SystemSlice

**Comment by SunSerega** [comment]
Нет, это отдельная проблема - тут надо выдавать более вразумительную ошибку. `SystemSlice` это шаблонная подпрограмма, которую вызывают срезы (которые вы почему то назвали к**а**ртежами), а указатель не может быть подставлен в качестве типа шаблона. То есть чтоб срезы работали на шаблонных массива - надо их полностью переделать, а за это вряд ли кто то возьмётся.

**Comment by samuraiGH** [comment]
> которые вы почему то назвали картежами

перепутал, да

> указатель не может быть подставлен в качестве типа шаблона

тоже убедился. в таком случае проблема действительно отдельная и тут лучше поменять текст ошибки

но тут ещё не работает и 
```pas
##
var a:= new pointer[3];
var b:= new pointer[2];
a.CopyTo(b, 1);
```
с такой же ошибкой, что и при `SetLength`. или думаете, что это тоже отдельная проблема?

**Comment by SunSerega** [comment]
Нет, прочитайте описание `.CopyTo`.

**Comment by ibond84** [comment]
https://github.com/pascalabcnet/pascalabcnet/actions/runs/1487305009
