### ISSUE TITLE
Статические массивы в IL-коде при вызове Print

### ISSUE THREAD

**Issue by miks1965** [pascalabcnet/pascalabcnet#256]
В такой программе
```
begin
  Println(1,2);
  Println(1,2);
  Println(1,2);
  Println(1,2);
end.
```
создаётся 8 статических массивов в IL-коде. Должно создаваться 4 и локальных.

**Comment by ibond84** [comment]
>Должно создаваться 4

Ну это из-за перегруженности Println. Переменные добавляются в методе get_convertions. На производительность это совершенно не влияет, поскольку переменные не используются.

**Comment by ibond84** [comment]
begin
end.
это не функция. поэтому делаю только функций и методов.

**Comment by ibond84** [comment]
>Переменные добавляются в методе get_convertions.

Их нужно наверно добавлять в convert_function_call_expressions

**Comment by ibond84** [comment]
Нет, все гораздо сложнее. Понятно, почему мы вынесли все в статическую память
```
procedure Test2;
var b2 : array[1..5] of integer := (1,2,3,4,5);
procedure Nested;
begin
assert(b2[1]=1);
```
(1,2,3,4,5); будет создаваться не в функции Test2, а в методе записи активации.

**Comment by miks1965** [comment]
Ничего не понятно. При чём тут старые массивы, переменное число параметров и вложенные функции?

В любом случае моделирование статическими массивами - это убивает многопоточность - это катастрофа.

**Comment by ibond84** [comment]
Ну чтобы понять, надо смотреть код.

**Comment by miks1965** [comment]
Вообще, кошмар. Если Print в методах класса, то создаются куча переменных-полей класса.

**Comment by ibond84** [comment]
В функциях теперь используются локальные переменные. begin end. это статический код, там используются поля.
