### ISSUE TITLE
Конструктор, имеющий единственный параметр params, не вызывается с 0 параметров

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#2566]
```
type
  t1 = class
    a: array of t1;
    
    constructor(params a: array of t1) := self.a := a;
    
  end;
  
begin
  var o := new t1;
  Writeln(o.a);
end.
```
Тут вызывает дефолтный конструктор вместо него, который не заполняет поле `a` - поэтому выводит `nil`.

**Comment by ibond84** [comment]
Ошибки нет. Конструкторы/Процедуры без параметров имеют приоритет перед процедурами с параметрами по умолчанию.

**Comment by SunSerega** [comment]
Неправда, никто там не имеет приоритет ни над кем:
```
function f1(params a: array of byte) := a;
function f1: array of byte := nil;

begin
  // Какую перегрузку выбирает - зависит от порядка объявления перегрузок
  var o := f1;
  Writeln(o);
end.
```
Кроме того, вы снова придумываете красивые правила, забывая о конечном случае.
А в конечном случае - пользовательский конструктор не выбирает, хотя он подходит, и всё это совершенно незаметно.

**Comment by SunSerega** [comment]
Зачем вообще генерировать конструктор по-умолчанию, когда уже есть пользовательский конструктор, который может принимать - параметров? Он только путоницу создаёт.
Конструктор по-умолчанию нужен только чтоб можно было создавать экземпляр, когда не понятно из чего его создавать.

**Comment by SunSerega** [comment]
Если таки дать приоритет конструктору по-умолчанию - компилятор будет провоцировать дубли кода, то есть придётся писать:
```
  t1 = class
    a: array of t1;
    
    constructor := self.a := new t1[0]; // То же самое лишний раз
    constructor(params a: array of t1) := self.a := a;
    
  end;
```
Тут дубль мелкий, но в реальном коде конструктор скорее будет делать какие-то преобразования `a`.

---

Если подумать только о том что неправильно игнорировать полностью подходящий конструктор с `params`, выдавая "Несколько конструкторов могут быть вызваны" - получится что конструктор по-умолчанию существует, но его невозможно вызвать.
Это, конечно, не лучше.

---

Как насчёт такого:
Если пользователь определил конструктор, который можно вызвать с 0 параметров, но не определил конструктор по-умолчанию, генерируемый конструктор должен вызвать пользовательский конструктор с 0 параметров.
Тогда конструктор по-умолчанию всё равно будет существовать всегда, но не будет мешать пользовательскому коду.

**Comment by ibond84** [comment]
В C# тоже вызовется конструктор по умолчанию. Ошибки нет. Закрываю.

**Comment by samuraiGH** [comment]
@ibond84 часто вижу аргумент, что в шарпе работает так же, по этому менять не будем. Возник такой вопрос. А что за этим стоит? Какие-то ограничения .Net? Просто это достаточно странно, pabc.net это же всё таки отдельный язык, а не копия c#

**Comment by ibond84** [comment]
В паскале есть только один способ скрыть конструктор по умолчанию: сделать его приватным. Вне модуля будет виден только конструктор с params. Все остальные способы в виде раздачи каких-то приоритетов это от лукавого.

**Comment by SunSerega** [comment]
В C# есть возможность вызывать такой конструктор, ничего в него не передавая:
```
    class t1
    {
        public int[] a;

        public t1(params int[] a)
        {
            this.a = a;
        }

    }
```
Конструкторы по умолчанию вставляет лично паскаль, поэтому нечего C# приписывать.

И `private` работает только на вне модуля, поэтому как оно работает сейчас - там где можно было хотя бы сказать о проблеме во время компиляции, говорит только во время выполнения. Это всегда плохо.
Поэтому, в данном случае, минимум должно говорить что можно вызвать и конструктор по-умолчанию, и конструктор с `params`.
Но я предложил способ решения, который ничего не ломает и компилируется, при этом делая то, что написано в программе, а не то что себе компилятор нагенерировал.
