### ISSUE TITLE
Point3D + Point3D works properly but Point3D - Point3D doesn't

### ISSUE THREAD

**Issue by BareGamer** [pascalabcnet/pascalabcnet#2573]
Not sure if this is a bug and if it has been fixed since 3.8.1.3005, but if it hasn't been, here's what's going on:

```
uses Graph3D;

var p1:Point3D:=new Point3D(*coordinates*);
var p2:Point3D:=new Point3D(*coordinates*);
var p3:Point3D:=p1+p2;                                 //works
var p4:Point3D:=p1-p2;                                  //doesn't work: "Can't convert from Vector3D to Point3D"
```

Converting either p1 or p2 .ToVector3D in the last statement fixes the issue somehow.

**Comment by miks1965** [comment]
Ну, правильно. При вычитании точек получается вектор, а он не может быть преобразован к точке

**Comment by BareGamer** [comment]
> Ну, правильно. При вычитании точек получается вектор, а он не может быть преобразован к точке
Может прозвучать странно, но почему?
