### ISSUE TITLE
Can't define the same type differently depending on the branch of conditional compilation

### ISSUE THREAD

**Issue by BareGamer** [pascalabcnet/pascalabcnet#2574]
Suppose we have:
```
{$ifdef debug}
type a=uint64;
{$else}
type a=int64; // complains that there is more 
{$endif}         // than one definition for type a
```
This scenario has no reason not to work, as only one of the definitions happen depending on the branch. Plus fpc and Delphi both support this feature.

**Comment by SunSerega** [comment]
I can't reproduce. Also when you compile in debug mode - only `DEBUG` is defined by compiler, not `debug`.

**Comment by BareGamer** [comment]
One moment, I will attach the actual code snippet. I probably should have mentioned that was just pseudo code

**Comment by BareGamer** [comment]
@SunSerega  https://github.com/BareGamer/vkxml2pasabc/blob/main/vkxml2pas.pas

**Comment by SunSerega** [comment]
That's why you should've found a minimal reproducible example, before making this issue.
It's both needed for devs to understand what to fix, and, more likely, in this case, find where you've made a mistake.

**Comment by SunSerega** [comment]
Yeah, well, `{$if ...}`'s from just above error list are ignored, because there is no such directive in PascalABC.Net, and so
```
type qword=uint64;
```
and
```
  {$define OldDelphi}
```
Are both applied unconditionally.

**Comment by BareGamer** [comment]
The fact that there is and $ifend but not an $if is honestly puzzling

**Comment by BareGamer** [comment]
Oh, also: that means that {$if defined()} doesn't work either?

**Comment by SunSerega** [comment]
There is no `{$ifend}`. Only `{$endif}`, which works only with `{$ifdef ...}`.
Look at `Директивы компилятора` page of docs. Even if you don't understand Russian, you'll at least see a list of all valid directives.

**Comment by BareGamer** [comment]
Oh. I just thought that as the compiler didn't complain it must be an undocumented directive. Maybe the compiler should throw warnings(like fpc) or even errors when encountering unknown directives then? Or maybe it would also be great to implement them.
