### ISSUE TITLE
Ускорить IL-код для for

### ISSUE THREAD

**Issue by miks1965** [pascalabcnet/pascalabcnet#258]

**Comment by ibond84** [comment]
Это не получится сделать. 
for i := 1 to 10 do это не for (i =1; i<=10; i++). i после выполнения цикла должен быть 10,  а не 11.
Такой вот паскал неэффективный :)

**Comment by ibond84** [comment]
Можно конечно, присваивать i после цикла значение 10.

**Comment by miks1965** [comment]
Сейчас... Если только дело в этом, то по спецификации Паскаля значение i после выполнения тела цикла не определено. То есть, может быть 10, может быть 11. 

Я вот чего не понимаю. Почему код for, который генерируется по коду foreach мной, выполняется затем быстрее? Почему Вам нельзя генерировать хотя бы такой же код?

Вот пример:

  s := 0.0;
  for var i := 0 to a.Length-1 do
    s += a[i];

  s := 0.0;
  foreach var x in a do
    s += x;

Вот код, который генерируется по двум forам:

```
double num = 0.0;
			int num2 = array.Length - 1;
			int num3 = 0;
			if (num3 <= num2)
			{
				while (true)
				{
					num += array[num3];
					if (num3 >= num2)
					{
						break;
					}
					num3++;
				}
			}
```
И
```
num = 0.0;
			double[] array2 = array;
			int num4 = array2.Length - 1;
			int num5 = 0;
			if (num5 <= num4)
			{
				while (true)
				{
					double num6 = array2[num5];
					num += num6;
					if (num5 >= num4)
					{
						break;
					}
					num5++;
				}
			}
```
Первый код выполняется 71 мс, второй - 51 мс. Вот так-то!

**Comment by ibond84** [comment]
эти два кода абсолютно идентичны.

**Comment by ibond84** [comment]
>Если только дело в этом, то по спецификации Паскаля значение i после выполнения тела цикла не определено. То есть, может быть 10, может быть 11. 

А припоминаю, что мы исправляли логику for специально, чтобы значение счетчика было 10. На форуме нам на это указывали.

**Comment by miks1965** [comment]
> эти два кода абсолютно идентичны.
Откомпилируйте вот такую программу 
```
begin
  var n := 50000000;
  MillisecondsDelta;
  var a := Range(1,n).Select(i->real(i)).ToArray();
  Println('Заполнение:',MillisecondsDelta);

  var s := 0.0;
  for var i := 0 to a.Length-1 do
    s += a[i];
  Println('s += a[i]:',s,MillisecondsDelta);

  s := 0.0;
  foreach var x in a do
    s += x;
  Println('foreach:  ',s,MillisecondsDelta);
end.
```
в Release и запустите по Shift-F9. У меня показывает следующие результаты:
```
Заполнение: 1170
s += a[i]: 1.250000025E+15 70
foreach:   1.250000025E+15 50
```
Это значит, что первый код выполняется медленнее.

Теперь посмотрите на генерируемый код. Я его приводил.

**Comment by ibond84** [comment]
Ну а причем здесь оптимизация s += a[i] и s += x? Я говорю совершенно о другом. О том, что цикл for в паскале неидентичен for-у в C#. Потому что переменная цикла не должна выходить за пределы выражения после to. Мы это один раз делали, это работает.

**Comment by ibond84** [comment]
Вот пример:
type en = (one, two, three);
for var i := one to three do;
куда выходить i после выполнения цикла?
И замечание делали на нашем форуме. ;)
Так что, считаю, issue стоит закрывать.

**Comment by miks1965** [comment]
А, вспомнил, почему не надо выходить за диапазон. Да, наверное.

Циклы в Паскале и C# неидентичны - хорошо.

Но всё-таки Issue - именно об оптимизации for. Вы всё-таки не ответили на вопрос - у Вас отличается время работы for и foreach после проведённой мной оптимизации? Можете привести результаты?

**Comment by ibond84** [comment]
s += a[i]: 1.250000025E+15 170
foreach:   1.250000025E+15 112

s += a[i]: 1.250000025E+15 170
foreach:   1.250000025E+15 90

s += a[i]: 1.250000025E+15 170
foreach:   1.250000025E+15 100

**Comment by miks1965** [comment]
Так. Очевидно, я чего-то недопонимаю. Давайте еще раз.

Если foreach, который переводится в синтаксический for, работает быстрее, то давайте для for сгенерируем такой же код и закроем Issue. Почему этого нельзя сделать? Это ровно наш for - он корректно работает, он - паскалевский.

Вы писали выше, что эти два кода эквивалентны. Но если один работает быстрее другого, значит, неэквивалентны.

**Comment by ibond84** [comment]
Только ради a[i] оптимизировать? А если там будет a[i]+a[i-1] и т.д. Сохранять их в локальные переменные? А где гарантии, что производительность не упадет. Не вижу смысла в оптимизации.

**Comment by miks1965** [comment]
А-а, понятно. Ну тогда раз Вы не видите возможностей оптимизации, - закрываем

**Comment by AIexandrKotov** [comment]
У вас, случаем, за кучу лет мнение не поменялось по этому вопросу? А то это жесть какая.

В чем проблема выхода за диапазон enum'а? В .NET это не страшно. Кроме того, почему бы не сделать генерацию этой проверки только для for i? Зачем генерировать кучу локальных переменных для for var, где i после цикла недоступна?

```
type en = (one = 1, two = 2, three = 3);

begin
  var i := integer(one);
  while (i <= integer(three)) do 
  begin
    writeln(en(i));
    i += 1;
  end;
  writeln('Недоступна в for var - ' + en(i).ToString);
end.
```
