### ISSUE TITLE
Неверная ошибка в условной операции 

### ISSUE THREAD

**Issue by samuraiGH** [pascalabcnet/pascalabcnet#2583]
```pas
##
var s: string;
s:= 1 <> 2 ? 100 : nil; // в false ветке обязательно nil
```

`Нельзя преобразовать тип Nullable<integer> к string`

То есть тип присваиваемого выражения  в true ветке определяется неверно.
Должно быть `Нельзя преобразовать тип integer к string`

**Comment by SunSerega** [comment]
Вы как то странно видите `?:`
```
s:= 1 <> 2 ? 100 : nil;
```
это не то же самое что
```
if 1<>2 then s := 100 else s := nil;
```
Сначала считается результат выражения `?:` - он должен иметь какой то тип ещё на этапе компиляции, до того как посчиталось выражение-условие.
Этот тип `integer?` (он же `Nullable<integer>`), потому что он наиболее натурально хранит любое из 2 значений, `100` и `nil`.

Даже если ссылаться на то что компилятор может посчитать это выражение во время компиляции - такое действие было бы оптимизацией, а оптимизация алгоритма никогда не должна влиять на результат.

**Comment by ibond84** [comment]
Ошибка правильное. Выражение имеет тип ```Nullable<integer>``` , а не integer. Закрывайте

**Comment by samuraiGH** [comment]
@SunSerega 
> Сначала считается результат выражения ?: - он должен иметь какой то тип ещё на этапе компиляции

Не думал, что в данном случае сравнение типов идёт после выведения типа всего выражения, а не по отдельности. 

Извините
