### ISSUE TITLE
Короткой строке можно присвоить nil в условной операции

### ISSUE THREAD

**Issue by samuraiGH** [pascalabcnet/pascalabcnet#2584]
```
##
var s: string[20];
s:= 1<>2 ? nil : 'asd';
```

Компилируется, но падает в рантайме

```
Ошибка времени выполнения: System.NullReferenceException: Ссылка на объект не указывает на экземпляр объекта.
Стек:
   в PABCSystem.PABCSystem.ClipShortString(String s, Int32 len) в D:\PascalABC.NET\LibSource\PABCSystem.pas:строка 13722
   в Program1.Program.$Main() в D:\PABCWork.NET\Program1.pas:строка 3
   в Program1.Program.Main()
```

**Comment by SunSerega** [comment]
То же замечание что в #2583, только добавлю что `?:` вообще не при чём:
```
## var s: string[1];
var s0 := default(string);
s := s0;
```
Не понятно стоит ли давать этому падать, но как общая рекомендация - не используйте устаревшие короткие строки.
И тем более не мешайте их с кодом, расчитаным на ссылочные лишний раз.

**Comment by samuraiGH** [comment]
@ibond84 
только сейчас посмотрел, как конкретно это исправили. просто присваивать пустую строку вместо nil? серьёзно? теперь это конечно не падает, за то является костылём и создаёт ещё больше проблем программисту, который нарвётся на ту же проблему.

в справе явно написано 

> Короткой строке в отличие от обычной нельзя присвоить nil. 

тогда уж меняйте справку...

**Comment by ibond84** [comment]
Нельзя присвоить константу nil, а так можно делать

```
begin
  var s2: string := nil;
  var s: string[10] := s2;
end.
```

И ничего криминального здесь нет. Библиотеки .NET могут возвращать nil, и это надо как-то обрабатывать. nil и пустая строка имеют здесь один и тот же смысл. Поэтому это просто конвертируется в пустую строку
Так что не переусложняйте...

**Comment by samuraiGH** [comment]
@ibond84 
одно дело, когда nil возникает в рантайме, другое дело, когда он явно есть в коде. 
> nil и пустая строка имеют здесь один и тот же смысл

нет, не один. пустая строка, это строка, в которой нет символов. nil -- строка в принципе не подразумевается 
> Библиотеки .NET могут возвращать nil, и это надо как-то обрабатывать

по идее, должно выбрасываться исключение

в конце концов можно вообще убрать проверку на попытку присвоить nil литерал, а просто всегда кидать Exception. это хотя бы приведёт к однообразию
