### ISSUE TITLE
Неверные предупреждения в коде с yield

### ISSUE THREAD

**Issue by miks1965** [pascalabcnet/pascalabcnet#259]
При компиляции кода с yield выдаются неверные предупреждения вида

PABCSystem.pas(7913) : Возвращаемое значение функции '<yield_helper_error_checkerr>Step' не определено

В функции, возвращающей последовательность, могут быть либо yield и yield sequence либо Result.

**Comment by ibond84** [comment]
А во что все это переводится в семантическом дереве?

**Comment by ibond84** [comment]
Какой-то странный код генерируется в MoveNext
if false then
goto

**Comment by ibond84** [comment]
<yield_helper_error_checkerr>Step
```
// loop start (head: IL_0003)
		IL_0003: ldc.i4.1
		IL_0004: brfalse IL_0016

		IL_0009: nop
		IL_000a: ldloc.1
		IL_000b: stloc.2
		IL_000c: ldloc.1
		IL_000d: ldloc.1
		IL_000e: ldc.i4.1
		IL_000f: add
		IL_0010: stloc.1
		IL_0011: br IL_0003
	// end loop

	IL_0016: ldloc.0
	IL_0017: ret
```
Какой-то бесконечный цикл. Предупреждения правильно выдаются.

**Comment by ibond84** [comment]
<yield_helper_error_checkerr> нигде не используется. зачем они нужны?

**Comment by miks1965** [comment]
Я могу прислать, какой код генерирует yield.

Может, неэффективный, но ничего там не зацикливается

**Comment by ibond84** [comment]
Ну я выше же привел код, который зацикливается...

**Comment by ibond84** [comment]
Это методы ```<yield_helper_error_checkerr>*```

**Comment by miks1965** [comment]
<yield_helper_error_checkerr>* не генерирует код - он выкусывается из семантического дерева в самом конце. Поэтому IL-код по нему генерироваться не может. Поэтому я не понял, откуда взядся приведенный IL-код.

Недостижимый код образуется вот как: в результате Loaweringа для 
```
while True do
...
```
образуется
```
if not True then
  goto #lb_1
```
и этот код недостижим действительно. Беда в том, что в методе, который мы используем - преобразование синтаксических деревьев - ничего не известно о семантике True (вдруг есть локальная переменная с именем True) и поэтому выкусить этот if на этапе синтаксиса не представляется возможным (хотя честно говоря, если бы мы определили переменную с именем True, то код всё равно бы лёг). Поэтому надо что-то решить в отношении этого сообщения в сгенерированном коде.

Второе ложное сообщение - это то что функция с yield не возвращает значения. Она возвращает, но особым образом. Это ложное сообщение тоже нужно как-то убрать. 

Может, сделать специальный атрибут и помечать им эти процедуры, а потом принимать их во внимание при предупреждениях?

**Comment by miks1965** [comment]
Избавился от сообщения "Обнаружен недостижимый код". 
Теперь надо избавиться от сообщения 
PABCSystem.pas(3897) : Возвращаемое значение функции '<yield_helper_error_checkerr>Iterate' не определено
