### ISSUE TITLE
[Cache] cached all code in DLL

### ISSUE THREAD

**Issue by retsyo** [pascalabcnet/pascalabcnet#2592]
when I test `fib` and `fib1` in DLL compiled from the following code, both of them run quickly. In other word, even `fib1` uses cached result. However, https://pascalabcnet.github.io/mydoc_release_notes_3_8_1.html says `fib` should be cached, while `fib2` should not be cached.

I reported this as an issue. However, maybe to-cache-all is a accecpted result

```PASCAL
library O;

[Cache]
function fib(n: integer): integer;
begin
  if n in 1..2 then Result := 1
  else Result := fib(n-1) + fib(n-2);
end;

function fib1(n: integer): integer;
begin
  if n in 1..2 then Result := 1
  else Result := fib(n-1) + fib(n-2);
end;

end.
```

**Comment by SunSerega** [comment]
`fib1` calls `fib`.
Also "runs quickly" is not proof, use decompiler(s).

**Comment by retsyo** [comment]
aha, my eyes are blind
