### ISSUE TITLE
Компилятор путает, из какого шаблона брать тип возвращаемого значения

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#2595]
```
type
  t1<T> = class
    
    function f<T2>(o: T2) := default(T);
    
  end;
  
procedure p<T>;
begin
  var o: t1<T>;
  //Ошибка: Нельзя преобразовать тип integer к T
  var b: T := o.f(0);
end;

begin end.
```
Функция `f` возвращает тип `T` из `t1<T>`, но при вызове компилятор решает что надо вернуть `T2=integer`, из `f<T2>`.

**Comment by SunSerega** [comment]
На самом деле мне кажется что я это уже репортил и что уже давно исправили...

**Comment by ibond84** [comment]
https://github.com/pascalabcnet/pascalabcnet/actions/runs/1634249988
