### ISSUE TITLE
Падает считывание из PCU при наличии в PABCSystem перегруженных версий Incremental

### ISSUE THREAD

**Issue by miks1965** [pascalabcnet/pascalabcnet#260]
Пока участок, вызывающий падение в ЛЮБОЙ ПРОГРАММЕ, закомментирован в PABCSystem:

```
function Incremental(Self: sequence of integer): sequence of integer; extensionmethod;
begin
  Result := IncrementalSeq(Self);
end;

function Incremental(Self: sequence of real): sequence of real; extensionmethod;
begin
  Result := IncrementalSeq(Self);
end;
```
Вот минимальный набор, который надо раскомментировать чтобы ошибка появилась

**Comment by ibond84** [comment]
Ошибка не воспроизводится

**Comment by miks1965** [comment]
Ну, если в PABCSystem откомментировать все Incremental, то не проходит уже самый первый тест.

**Comment by ibond84** [comment]
У меня все раскомментировано и тесты проходят.

**Comment by miks1965** [comment]
Ну, пусть повисит какое-то время открытым - я еще опрошу других, проходят ли тесты

**Comment by wisestump** [comment]
У меня тоже проходят все тесты со всеми раскомментированными методами

**Comment by ibond84** [comment]
Ну, вопрос наверно исчерпан..

**Comment by miks1965** [comment]
Да, у меня ошибка исчезла. Закрываю.
