### ISSUE TITLE
В реализации метода не видит where из описания, но только в заголовке

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#2601]
```
type
  t0<T> = class
    where T: record;
  end;
  
  t1 = class
    
    procedure p1<T>(o: t0<T>); where T: record;
    
  end;
  
//Ошибка: Невозможно инстанцировать, так как тип T не является размерным
procedure t1.p1<T>(o: t0<T>);
begin
  
end;
  
begin end.
```
При этом в теле `p1` уже не ругается:
```
type
  t0<T> = class
    where T: record;
  end;
  
  t1 = class
    
    procedure p1<T>; where T: record;
    
  end;
  
procedure t1.p1<T>;
begin
  // OK
  var o: t0<T>;
end;
  
begin end.
```

**Comment by ibond84** [comment]
Ну здесь проблема в том, что определение функции ищется после компиляции всех параметров.

**Comment by SunSerega** [comment]
Вроде я уже видел где-то в компиляторе переключатель, позволяющий не проверять `where` шаблона. Вроде это используется при компиляции классов.

Вообще я за то чтобы заставлять писать такой же `where` в реализации, как в описании.
Правда считая что `where` и короткие функции не совместимы - это довольно неудобно...

**Comment by ibond84** [comment]
На самом деле здесь нет ошибки. Не написал where, сам виноват. Принуждать писать везде where, тоже плохо. Это сломает совместимость.
