### ISSUE TITLE
Показывает кишки компилятора, если λ с неверной условной операцией выступает фактическим параметром

### ISSUE THREAD

**Issue by samuraiGH** [pascalabcnet/pascalabcnet#2603]
```pas
procedure fun(l: (integer, integer)-> integer);
begin end;

BEGIN
  // обязательно указывать в операции те же идентификаторы, что были объявлены для лямбды 
  fun( (a, b)-> if 1 = 1 then a else b ); 
END.
```

> 6 : Нельзя преобразовать тип procedure(_: λ_anytype;_: λ_anytype) к Func<integer,integer,integer>

http://forum.mmcs.sfedu.ru/t/boltalka-pascalabc-net/2259/1833

**Comment by ibond84** [comment]
Ну и что должно показывать?

**Comment by samuraiGH** [comment]
Видимо то же самое, что и тут 
```pas
##
var l: (integer, integer)-> integer:= (a, b)-> if 1 = 1 then a else b;
```

> Ожидалось имя процедуры или функции

**Comment by SunSerega** [comment]
Нет, это точно не должно выдавать. И в случае что вы привели тоже.
Потому что курсор показывает `a` - хотя проблема вообще не в нём.

Вам @miks1965 на форуме сказал, проблема в том что парсер слабый, не может различить `if`-оператор и `if`-выражение.

**Comment by miks1965** [comment]
Мы на форуме ответили, что в лямбдах единственным выражением нельзя использовать if-выражение - оно воспринимается как if-оператор. А значит, лямбда воспринимается как лямбда-процедура
