### ISSUE TITLE
pabcnetc.exe crashes when compiling Sample sources

### ISSUE THREAD

**Issue by 3oheicrw** [pascalabcnet/pascalabcnet#2608]
I'm using only the command line compiler, the full IDE is not installed. The Sample sources were copied from a full IDE installation.

**Comment by 3oheicrw** [comment]
The command line compiler is unreliable. Just don't use it.

**Comment by SunSerega** [comment]
The report is incomplete without a specific source file name, as well as crash info.

Also "Samples" folder isn't installed in the command-line only version for a reason:
Some sources can't be compiled in the environment, where IDE also isn't supported.
Though I don't think the compiler should crash - It is supposed to tell you about missing libraries, etc. instead.
