### ISSUE TITLE
proposal: add _ in number

### ISSUE THREAD

**Issue by retsyo** [pascalabcnet/pascalabcnet#2619]
for large number, it is hard to read. So in some language, for example python, we can add `_` between numbers, and the location of `_` is arbitary. Can pascalabc support this feature?

```python
the following is python code

>>> 1_234_5, 12_34_5
(12345, 12345)
>>> 1_234_5.6_78, 12_34_5.67_8
(12345.678, 12345.678)
>>> 1_2e3_4, 12e34
(1.2e+35, 1.2e+35)

```

**Comment by miks1965** [comment]
No? it can't
