### ISSUE TITLE
bug? xlsx says "Program1.pas(4) : Incompatible types: 'System.String[][][]' and 'Dictionary<string,array of array of string>'"

### ISSUE THREAD

**Issue by retsyo** [pascalabcnet/pascalabcnet#2624]
the code is from https://pascalabcnet.github.io/mydoc_release_notes_3_8_2.html
```pascal
uses XLSX;

begin
  var d: Dictionary<string,array of array of string> := ReadXLSX('test.xlsx').Values.ToArray;
  
end.
```
when I try to compile it, I get
```
Program1.pas(4) : Incompatible types: 'System.String[][][]' and 'Dictionary<string,array of array of string>'
```

**Comment by miks1965** [comment]
fixed

**Comment by retsyo** [comment]
can anyone supply a working `test.xlsx`?
I have downloaded PascalABC.NET 3.8.2 3074 2022/2/7, but it still says
```
Program1.pas(4) : Incompatible types: 'System.String[][][]' and 'Dictionary<string,array of array of string>'
```

**Comment by miks1965** [comment]
Your code is Wrong/ Use code from here:
https://pascalabcnet.github.io/mydoc_release_notes_3_8_2.html

**Comment by SunSerega** [comment]
@miks1965 still, you haven't posted `3.xlsx`, you only fixed the code for opening it.
I also find it confusing, trying to understand without all the source data.
