### ISSUE TITLE
How to use the nuget.exe shipped with PascalABC.NET?

### ISSUE THREAD

**Issue by 3oheicrw** [pascalabcnet/pascalabcnet#2626]
Is it the same as Visual Studio's nuget? Where does it put installed packages? Is there any integrations with the IDE so I could use it within the IDE like Visual Studio? Thanks.

**Comment by SunSerega** [comment]
afaik it's used when you add .Net library as a dependency in a project.
You can create a project with this button:
![image](https://user-images.githubusercontent.com/27270190/151660855-4a3ef835-5f91-4efa-9b3e-15d7d5a762aa.png)

**Comment by miks1965** [comment]
Ask questions on the forum/ Here are Issues only

**Comment by 3oheicrw** [comment]
> afaik it's used when you add .Net library as a dependency in a project. You can create a project with this button: ![image](https://user-images.githubusercontent.com/27270190/151660855-4a3ef835-5f91-4efa-9b3e-15d7d5a762aa.png)

Not work. When Adding new reference via Nuget you click Install package, it will cause unhandled exception or leave you back to the IDE's main window immediately without any new reference added. The only type of reference could be used is GAC. I didn't try Assemblies.

**Comment by 3oheicrw** [comment]
What exactly Package Id the IDE is expecting? For example, I'm trying to install Xwt.

https://www.nuget.org/packages/Xwt/

As you can see on the nuget page you can't see anything about package id. You have to guess and trial and error. I have tried all possibilities from Xwt, xwt to Xwt 0.2.251 and various variants of them and none worked.

**Comment by 3oheicrw** [comment]
I downloaded the .nupkg package and try dragging it to the IDE. Doesn't work, too.

**Comment by 3oheicrw** [comment]
On Visual Studio, it's so easy.

https://docs.microsoft.com/en-us/nuget/quickstart/install-and-use-a-package-in-visual-studio

**Comment by samuraiGH** [comment]
After installing the package, open the add assemblies window on the search for assemblies tab. In the project folder, in the nuget section, select the desired .dll
