### ISSUE TITLE
Print(not f) не работает без скобок если f - указатель на функцию

### ISSUE THREAD

**Issue by miks1965** [pascalabcnet/pascalabcnet#2631]
```pascal
begin
  var f: ()->integer := ()->1;
  Print(f + f);   // выводит 1
  Print(f and f); // ошибка
  Print(not f);   // ошибка
end.
```

**Comment by SunSerega** [comment]
> Print(f + f);   // выводит 1

Тут вызывает сложение делегатов. То есть создаёт делегат, вызывающий `f` два раза и возвращающий последний результат. Ну и сразу его вызывает - поэтому 1.

Я тоже за то что `not f` должно работать, потому что иначе функциональные переменные и функции работают неоднобразно.

Но операции делегатов должны иметь бОльший приоритет чем вызов функций. То есть вызов должен быть только если операция без вызова недопустима. Иначе, к примеру, вызвать сложение делегатов, для 2 функций без параметров - не выйдет.

**Comment by miks1965** [comment]
А, да. Я бы запретил сложение делегатов - функций.

Вообще, у меня ощущениие, что это - не ошибка. Мы описали переменную как указатель на функцию. Значит любые операции - это операции с указателями. И есть одно исключение - когда выражение состоит из единственного имени делегата. Тогда можно сделать вызов функции

**Comment by miks1965** [comment]
Закрываем. Не ошибка. not для делегатов не определен
