### ISSUE TITLE
Сделать пункт меню "Проверить обновления"

### ISSUE THREAD

**Issue by miks1965** [pascalabcnet/pascalabcnet#264]
Все просят, поскольку программа обновляется часто

**Comment by ibond84** [comment]
Сделал. В папке Release создается файлик с версией, его надо вместе с инсталятами загружать на сервер.

**Comment by miks1965** [comment]
У меня ничего не создаётся

**Comment by ibond84** [comment]
Поконкретнее

**Comment by ibond84** [comment]
Файл pabcversion.txt не создается?

**Comment by miks1965** [comment]
А где он должен создаваться? Я его не вижу. В папке Release после сборки инсталлятов его нет

**Comment by ibond84** [comment]
В папке Release.
