### ISSUE TITLE
На PascalABC.NET не решаются некоторые задачи с сайта acmp.ru

### ISSUE THREAD

**Issue by fyodor-menshikov** [pascalabcnet/pascalabcnet#2647]
На сайте решения олимпиадных задач acmp.ru есть несколько компиляторов Паскаля: PascalABC.NET 3.8, Free Pascal 3.2.2, Delphi 7.0.

Один и тот же код решения интерактивной задачи получает Accepted (принято) на Free Pascal и Delphi и Presentation Error 1 (ошибка представления на первом тесте) на PascalABC.NET. Судя по продолжительному статусу Running (исполняется) при сдаче, какая-то сторона не может дождаться данных от другой - или интерактор от решения, скомпилированного PascalABC.NET, или наоборот.

При замене чтения данных с `readln(c);` на `c := Console.ReadLine()[1];` программа получает Accepted (принято). То есть есть основания предполагать, что `readln` пытается прочитать больше символов, чем сейчас доступно для чтения - и блокируется - а потом программу снимают по пределу времени.

Для версии PascalABC.NET 3.5.1 (которая была на сайте до 29.05.2020) есть решения интерактивных задач, которые используют readln. То есть проблемы в 3.5.1 точно нет. В 3.8 и актуальной 3.8.3 проблема есть.

Предположительно в какой-то версии PascalABC.NET после 3.5.1 происходило ускорение ввода - и это ускорение ввода читает слишком много символов вперёд - и это приводит к зависанию решений интерактивных задач. Альтернативно (но менее вероятно) `flush(output);` перестал выполнять свою функцию. Менее вероятно, потому что при чтении через `Console.ReadLine()` программа успешно работает без необходимости `flush(output);`.

Ссылка на условие интерактивной задачи и возможность сдать: https://acmp.ru/index.asp?main=task&id_task=1465

Полный код решения интерактивной задачи на классическом Паскале (принимается на Free Pascal и Delphi, не принимается на PascalABC.NET).
```pascal
var
  mid, left, right: integer;
  c: char;
  
begin
  left := 0; // left < answer
  right := 1000 * 1000 * 1000 + 1; // right > answer
  while true do
  begin
    mid := (left + right) div 2;
    writeln(mid);
    flush(output);
    readln(c);
    if c = '<' then begin
      right := mid;
    end
    else if c = '>' then begin
      left := mid;
    end
    else if c = '=' then begin
      exit;
    end
    else begin
      writeln('неожиданный символ - >', c, '<');
      halt(1);
    end;
  end;
end.
```

Полный код решения, используя чтение .NET - принимается даже несмотря на отсутствие сброса буфера потока output.
```pascal
var
  mid, left, right: integer;
  c: char;
  
begin
  left := 0; // left < answer
  right := 1000 * 1000 * 1000 + 1; // right > answer
  while true do
  begin
    mid := (left + right) div 2;
    writeln(mid);
    c := Console.ReadLine()[1];
    if c = '<' then begin
      right := mid;
    end
    else if c = '>' then begin
      left := mid;
    end
    else if c = '=' then begin
      exit;
    end
    else begin
      writeln('неожиданный символ - >', c, '<');
      halt(1);
    end;
  end;
end.
```

**Comment by miks1965** [comment]
Да, ввод ускоряли.
А это на всех задачах с acmp.ru или на очень редких? 

Эта задача с flush - какая-то уж больно специфическая - есть более простые примеры?

**Comment by fyodor-menshikov** [comment]
> Да, ввод ускоряли. А это на всех задачах с acmp.ru или на очень редких?

На acmp с обычными задачами, где нужно прочитать ввод целиком, а потом выдать ответ целиком - ABC.NET вполне работает. Проблема именно в интерактивных задачах, где нужно задавать вопросы и получать ответы на них.

**Comment by fyodor-menshikov** [comment]
> есть более простые примеры?

Я вижу вот такой более простой пример: на PascalABC.NET пишем программу `b`, где в бесконечном цикле читаем строку из консоли и тут же её выводим на консоль. Также пишем программу `a`, которая раз в секунду печатает одну строку. Тогда вот такая команда запуска `a | b | b` должна раз в секунду печатать строку. Если это происходит реже и большими блоками - то это как раз и показатель, что программа `b` читает не то, что ей уже дано, а ожидает чего-то большего. Также возможно достаточно запуска `a | b`, но я не уверен, потому что интерактивная задача на PascalABC.NET в среде разработки вполне работает - и только при автоматической проверке подвисает.

**Comment by fyodor-menshikov** [comment]
> есть более простые примеры?

Вот, реализовал. Программа `a`:

```pascal
var
  i: integer;

begin
  for i := 1 to 24 * 60 * 60 do
  begin
    writeln(i);
    flush(output);
    sleep(1000);
  end;
end.
```
Если просто запустить `a`, будет выводить числа по порядку раз в секунду.

Программа `b`:
```pascal
var
  s: string;

begin
  while true do
  begin
    readln(s);
    writeln(s);
    flush(output);
  end;
end.
```
Если запустить и написать что-то в консоль вроде `abc` - она тут же выведет `abc` в ответ.

А вот если запустить `a | b` - то первый вывод будет через примерно минуту - и будет содержать числа от 1 до 66 по одному в строке. То есть программа ожидает примерно 256 байт ввода перед тем как сможет на него отреагировать.

**Comment by fyodor-menshikov** [comment]
Замечу, что слово Piped в названии константы - это как раз про перенаправление ввода из другой программы.

**Comment by miks1965** [comment]
Вот как устроен ReadNextBuf:
![изображение](https://user-images.githubusercontent.com/10325391/160482204-5cf98169-798b-4df3-be2e-1c69aa16c9bc.png)
Насколько я понимаю, tr.ReadBlock(buf, 0, buflen); считывает buflen=256 символов (или меньше если ввод завершен)
Но ввод не завершен - просто в первой программе генерируется пауза. 

Именно поэтому ничего не работает. Как решить проблему - не знаю

**Comment by miks1965** [comment]
Судя по трассировке такова природа sleep - пока первая программа не закончится, вывод не будет передан

**Comment by SunSerega** [comment]
Просто уберите `Block` из `ReadBlock`:
https://stackoverflow.com/questions/10497575/what-is-the-difference-between-read-and-readblock-calls-on-textreader

**Comment by fyodor-menshikov** [comment]
> Просто уберите `Block` из `ReadBlock`: https://stackoverflow.com/questions/10497575/what-is-the-difference-between-read-and-readblock-calls-on-textreader

Кажется это решение

**Comment by fyodor-menshikov** [comment]
Когда ожидать публичную версию, доступную для скачивания, с исправлением этого бага?

**Comment by miks1965** [comment]
Уже выложили

**Comment by fyodor-menshikov** [comment]
> Уже выложили.

А куда выложили? На http://pascalabc.net/ssyilki-dlya-skachivaniya версия красными буквами написана 3.8.3, сборка 3090 от 09.03.2022, а в коммите сборка 3093.

**Comment by samuraiGH** [comment]
Там информацию обновляют только когда новые версии выходят. Однако сборки всё равно актуальные под ссылкой

**Comment by fyodor-menshikov** [comment]
На acmp уже можно сдавать интерактивные задачи на PascalABC.NET. Спасибо за оперативность решения вопроса!

**Comment by miks1965** [comment]
Спасибо!
