### ISSUE TITLE
Не разрешает делать лямбду, принимающую параметр шаблонного типа, но только если присваивать её переменной

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#2651]
```
## procedure p0<T>(p: T->()) := exit;

procedure p1<T>;
begin
  // OK
  p0&<T>(v->exit());
  //Ошибка: Недопустимо описание анонимных делегатов, использующих generic-параметры
  var p := procedure(v: T)->exit();
end;
```

**Comment by ibond84** [comment]
Ну, а почему сразу в issue? Не разрешает правильно. Надо задавать тип явно: ```Action<T>```.

**Comment by ibond84** [comment]
> ```p0&<T>(v->exit());```

Ну здесь тип уже известен: ```T->()```  Это не анонимный делегат

Так что все правильно запрещает.

**Comment by SunSerega** [comment]
А ну да... Но почему с анонимным делегатами то не работает? Компилятор ведь умеет объявлять анонимные типы с шаблонным параметром - собственно в случае лямбд с захватом.
