### ISSUE TITLE
Ошибка при чтении символов внутри более чем одной строки через readln при запуске в среде, когда строки имели одинаковое значение

### ISSUE THREAD

**Issue by fyodor-menshikov** [pascalabcnet/pascalabcnet#2658]
Программа
```pascal
var
  a, b: string;

begin
  a := '1';
  b := '1';
  readln(a[1], b[1]);
  writeln(a, b);
end.
```
При вводе `45` ожидаемый ответ `45`, при запуске в среде (F9) ответ `55`, при запуске без связи с оболочкой (Shift+F9) ответ `45`. То есть проблема исключительно при запуске в среде. Инициализация одинаковыми начальными значениями имеет значение. Если начальные значения `a` и `b` сделать разными, проблема не воспроизводится. Причём группировка идёт по начальным значениям. В программе
```pascal
var
  a, b, c, d: string;

begin
  a := '1';
  b := '2';
  c := '2';
  d := '1';
  readln(a[1], b[1], c[1], d[1]);
  writeln(a, b, c, d);
end.
```
При вводе `5678` ожидаемый ответ `5678`, при запуске в среде (F9) ответ `8778`.

Версия PascalABC.NET - самая свежая, 3.8.3 сборка 3104.

**Comment by SunSerega** [comment]
Не могу воспроизвести. Скиньте .exe файл, с которым у вас воспроизводится, и список установленных версий .Net .

Считая что изначальные значения важды - выглядит как будто `String.Copy` не срабатывает. Но до .Net 3.0 (и поидее во всех версиях .Net Framework) оно должно работать.

**Comment by SunSerega** [comment]
А, нет, я понял - дело в rtl (ускорение запуска из под оболочки).
Почему то, когда использование rtl включено - `String.Copy` в .exe не появляются.

**Comment by SunSerega** [comment]
```
library u0;

procedure p0(var ch: char) := ch := '5';

end.
```
```
## {$reference u0.dll}

var s1 := 'abc';
var s2 := 'abc';

p0(s1[2]);
Writeln(s1);
Writeln(s2);
```
Так и без rtl воспроизводится. То есть проблема в подпрограммах из .dll .

**Comment by miks1965** [comment]
А приведите минимальный пример когда String.Copy в dll не появляется. И - где он там - при присваивании строк или символов?

**Comment by SunSerega** [comment]
Минимальный код я уже привёл. Декомпилируйте бинарники, получаемые при компиляции самой первой программы из заголовка с и без rtl, чтобы разобраться.

**Comment by miks1965** [comment]
String.Copy там где встречается?

**Comment by SunSerega** [comment]
В моём втором сообщении:

> Почему то, когда использование rtl включено - String.Copy в .exe не появляются.

Разумеется, раз дело в пересечении подпрограммы и IL кода .exe файла - смотреть надо на сгенерированный вызов подпрограммы.

Может мне вообще не стоило писать, чтобы вы сами во всём по-порядку разобрались?
Потому что я писал с расчётом на то чтобы быстрее натолкнуть вас в сторону источника бага, но теперь выглядит как будто вас это только сбивает и отбивает желание самостоятельно прилагать усилия - авось я за вас всё разжую...

**Comment by miks1965** [comment]
Этот пример показывает, что в режиме ускорения нет string.Copy только для readln
![изображение](https://user-images.githubusercontent.com/10325391/164958072-7e5ec342-bfbd-426f-89b3-a85e6460bb67.png)
То есть, в волшебной функции это сделать забыли
![изображение](https://user-images.githubusercontent.com/10325391/164958076-cee82407-975b-4087-a72b-bfda7da6f6ae.png)

**Comment by SunSerega** [comment]
Нет, не только для волшебной - а для всех, принимающих символ `var`-параметром.
Это показывает мой последний код - пример этого же бага без rtl.

**Comment by ibond84** [comment]
https://github.com/pascalabcnet/pascalabcnet/actions/runs/2215146987

**Comment by fyodor-menshikov** [comment]
Как будет версия для скачивания - напишите, смогу независимо подтвердить, что этот вопрос решён.

**Comment by miks1965** [comment]
Выложили новую версию

**Comment by fyodor-menshikov** [comment]
Подтверждаю, что этот вопрос решён.
