### ISSUE TITLE
Не может захватить переменную внешней лямбды

### ISSUE THREAD

**Issue by miks1965** [pascalabcnet/pascalabcnet#2660]
```
##
var a := Arr(1,2,3);
var d := a.Where(x -> a.Select(y -> х))
```
Странно, мне казалось, что такие простые ошибки уже давно исправлены

**Comment by SunSerega** [comment]
Несколько часов назад я использовал эту конструкцию - то есть в заведомо правильном коде она работает.
Проблема в том что выводит не ту ошибку в заведомо ошибочной ситуации.

То есть так работает:
```
##
var a := Arr(1, 2, 3);
var d := a.Where(x -> a.Select(y -> x).Any)
```
А так выводит другую ошибку (тоже мало что объясняющую):
```
##
var a := Arr(1, 2, 3);
var d := a.Where(x -> a.Select(y -> x <> 0))
```

**Comment by miks1965** [comment]
Ложная тревога. Там одно x набрано как русское х
