### ISSUE TITLE
При установке PascalABC.NET из-под ограниченного пользователя Windows в главном меню Windows этого пользователя не появляется ссылка на среду

### ISSUE THREAD

**Issue by fyodor-menshikov** [pascalabcnet/pascalabcnet#2661]
Сижу под ограниченным пользователем Windows (не администратором), запускаю инсталлятор. Инсталлятор требует прав администратора, ввожу пароль, он устанавливается. В итоге он в Program Files (x86) установлен, у администратора в профиле в главном меню Windows есть группа PascalABC.NET и даже на рабочем столе у администратора есть ярлык. А под пользователем, под которым я начинал установку, в главном меню и на рабочем столе ничего не изменилось.

Я так понимаю более правильно было бы ставить не в профиль "текущего пользователя" (который сменился на администратора при запуске, чтобы писать в Program Files (x86)), а в профиль All Users. Или как вариант не требовать прав администратора и устанавливать исполнимые файлы не в Program Files (x86), а в профиль текущего пользователя. Или предлагать на выбор - устанавливать для всех пользователей компьютера - тогда в Program Files (x86) и требовать права администратора - или устанавливать только для текущего пользователя - без прав администратора и в профиль текущего пользователя.

**Comment by miks1965** [comment]
Перенесите ваш Issue сюда: https://github.com/pascalabcnet/pascalabcnetide/issues

Здесь - Issue только по компилятору.

**Comment by fyodor-menshikov** [comment]
Перенёс https://github.com/pascalabcnet/pascalabcnetide/issues/240
