### ISSUE TITLE
Генерирует сломанный .exe, если параметр override метода имеет тип анонимного делегата

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#2688]
```
type
  t1 = abstract class
    
    procedure p1(p: procedure); abstract; // С virtual тоже сломано, но без диагностики
    
  end;
  t2 = class(t1)
    
    procedure p1(p: procedure); override := exit;
    
  end;
  
begin
  new t2;
end.
```
Желательно детектить такие случае и использовать уже сгенерированный тип-делегат из метода предка.
Но если сделать нормальный текст ошибки, запрещающей анонимные делегаты в параметрах виртуальных функций - тоже неплохо.

**Comment by ibond84** [comment]
https://github.com/pascalabcnet/pascalabcnet/actions/runs/2942633344
