### ISSUE TITLE
Невозможно добавить TensorFlow в проект

### ISSUE THREAD

**Issue by Petrprogs** [pascalabcnet/pascalabcnet#2689]
Установленный через nuget TensorFlow, отказывается работать на PascalABC.Net. При компиляции вылетает следующая ошибка:
`TensorFlow.pas(0) : Ошибка при чтении сборки 'C:\PABCWork.NET\TensorFlow\Tensorflow.Binding.dll'`

**Comment by miks1965** [comment]
Недостаточно данных. Как вы устанавливали nuget, установился ли он, какие dll скачались, все ли зависимости есть.

И - приведите код программы
