### ISSUE TITLE
IDE Code Editor please allow selection of odd font size

### ISSUE THREAD

**Issue by jpgpng** [pascalabcnet/pascalabcnet#2695]
Currently there is only even font size to choose from. I want to be able to select Consolas 11 as Consolas 10 is too small and Consolas 12 is a bit too big on my system. Please help.

**Comment by SunSerega** [comment]
`PABCWork.NET\PascalABCNET.ini`: 
```
  <option name="EditorFontSize">10</option>
```
Though, yeah, the font size in most editors is a text box with a drop-down only as QoL.

**Comment by SunSerega** [comment]
Also, this is an IDE issue. Everything that is not about the compiler should go to:
https://github.com/pascalabcnet/pascalabcnetide/issues
