### ISSUE TITLE
Single-element enum bug

### ISSUE THREAD

**Issue by BareGamer** [pascalabcnet/pascalabcnet#2696]
`     TVkPipelineCacheHeaderVersion=
      (
       VK_PIPELINE_CACHE_HEADER_VERSION_ONE=1
      );`

Doesn't compile with " Expected ",", got ")" "

`     TVkPipelineCacheHeaderVersion=
      (
       VK_PIPELINE_CACHE_HEADER_VERSION_ZERO=0,                                 
       VK_PIPELINE_CACHE_HEADER_VERSION_ONE=1
      );`

This works though. So essentially, you can't have enums with one element.

**Comment by ibond84** [comment]
https://github.com/pascalabcnet/pascalabcnet/actions/runs/2988026976
