### ISSUE TITLE
REPL для PascalABC.NET

### ISSUE THREAD

**Issue by miks1965** [pascalabcnet/pascalabcnet#270]
Реализовать (видимо, в отдельном окне) возможность интерактивного выполнения команд PascalABC.NET

Как это сделать - не знаю, но переменные, которым присвоены значения ранее, должны быть уже известны программе

**Comment by ibond84** [comment]
Назовем это современно, как в студии: окно Immediate. Оно уже есть, только заброшено и не работает. Надо реанимировать :)

**Comment by ibond84** [comment]
Ну это все должно вычисляться отладчиком. Когда отладка запущена, проблем нет. И присваивание там работает. А вот когда не запущена, начинаются проблемы.
