### ISSUE TITLE
Ошибка в ??

### ISSUE THREAD

**Issue by miks1965** [pascalabcnet/pascalabcnet#2701]
```
##
var x: Object := 'h';
var y:= x ?? 10;
print(y.GetType);
```
Не должно, а работает

**Comment by SunSerega** [comment]
А почему не должно то? `integer` можно привести к `object`.
Вместо этого надо исправить беззвучное вылетание этого кода:
```
##
var x: Object := nil;
var y:= x ?? 10;
print(y);
```

**Comment by miks1965** [comment]
Оно не вылетает - просто долго работает - видимо, из-за Print

**Comment by SunSerega** [comment]
`print` медленный, но не так чтобы 3 сек висеть. И он в итоге ничего не выводит.
Поэтому нет, это именно долгий вылет, так часто получается если CLR заглючивает из за кривого IL.

**Comment by samuraiGH** [comment]
Ну что б не потерялось – продублирую и своё
![Screenshot_20220909-065926](https://user-images.githubusercontent.com/87191377/189269055-98d9427e-9908-4cba-bcab-678553869017.png)

**Comment by miks1965** [comment]
В C# не работает, и это верно:
![изображение](https://user-images.githubusercontent.com/10325391/189274724-e9158984-9a74-4e43-9350-bcc6756c8518.png)

**Comment by samuraiGH** [comment]
По-моему, это не тот случай когда обязательно нужно сделать аналогично шарпу

**Comment by miks1965** [comment]
В C# просто это продумывалось огромным коллективом - до этого продумывалось разработчиками Kotlin.

Логика тут простая. Если в дело встумают размерные типы, то тип итоговый должен быть размерным. Вообще ?? - это история в основном про размерные типы.

А тут - 'z' ?? 10
И какой должен быть результат? И нафига он такой?

**Comment by SunSerega** [comment]
> А тут - 'z' ?? 10

Нет, тип во время компиляции важен, поэтому
```
'z' as object ?? 10
```
Ну и у меня это компилируется работает:
```
        static void f(bool b, object i1, int i2)
        {
            var x1 = b ? i1 : i2;
            var x2 = b ? i2 : i1;
            var x3 = i1 ?? i2;
        }
```
Может у вас версия C# устаревшая?

---

Если есть лишнее желание приводить поведение к C# - там можно делать так:
```
        static void f(int? x)
        {
            int i1 = x; // Ошибка - нельзя явно конвертировать
            int i2 = x ?? 5; // OK - результат не нулевой
        }
```
А вы уже пару раз отказались так делать... Самое большое неудобство работы с `Nullable` сейчас.

**Comment by ibond84** [comment]
Мне кажется, это должно работать. Любой тип можно преобразовать в Object.

> И две части не равноценны в отличие от тернарки.

Ну аналогичный код и на паскале не скомпилируется

```
begin
  var x: Object := 'h';
  var y: integer := x ?? 10;
  print(y.GetType);
end.
```

**Comment by ibond84** [comment]
Такое компилируется

```
object o = null;
var tt = o ?? 10;
```

**Comment by ibond84** [comment]
> Вместо этого надо исправить беззвучное вылетание этого кода:

Опять вы в кучу сваливаете разные ошибки. Баг = отдельный issue.

**Comment by ibond84** [comment]
Баг с print исправлять здесь не будем. Исправляется только баги в заголовке issue

**Comment by miks1965** [comment]
В C# работает. Ошибся. Закрываю:
![изображение](https://user-images.githubusercontent.com/10325391/189547993-48ec24e7-6d47-43b2-8bc9-8caa84a9905d.png)
