### ISSUE TITLE
Hash on site is broken

### ISSUE THREAD

**Issue by alealexpro100** [pascalabcnet/pascalabcnet#2706]
Hash of binary (PascalABCNETSetup.exe) on [the site](https://pascalabc.net/downloads/PascalABCNETSetup.exe) tends to be changed often without change of version or revision on the same site.

**Comment by miks1965** [comment]
Dthcbz vtyztncz - d 'njv vj;yj e,tlbnmcz ghb bycnfkkzwbb/ Cfqn yt gjcgtdftn/
