### ISSUE TITLE
Крашится print для упакованного целого в операции ??

### ISSUE THREAD

**Issue by ibond84** [pascalabcnet/pascalabcnet#2707]
```
##
var x: Object := nil;
var y:= x ?? 10;
print(y);
```

**Comment by SunSerega** [comment]
Та не зависание это. Запустите из папки - увидите "программа перестала работать". То есть вывод как при исключении, но CLR его не может поймать, потому что сама CLR крашится. Смотрите на IL код.

**Comment by SunSerega** [comment]
Ну таки да, вот строчка с `y :=`:
```
    // [32 7 - 32 67]
    IL_0005: ldloc.2      // obj
    IL_0006: ldnull
    IL_0007: ceq
    IL_0009: brtrue       IL_0014

    IL_000e: ldloc.2      // obj
    IL_000f: br           IL_0016
    IL_0014: ldc.i4.s     10 // 0x0a
    IL_0016: stloc.1      // V_1
```
То есть тут забыли 10 спаковать (box) в объект. Вместо этого в переменную `y` сохраняет управляемую ссылку с адресом 10, и так ломает CLR.

**Comment by SunSerega** [comment]
Должно генерировать IL как тут:
```
##
var x: Object := nil;
var y:= x ?? 10 as object;
print(y);
```

**Comment by ibond84** [comment]
https://github.com/pascalabcnet/pascalabcnet/actions/runs/3039651248
