### ISSUE TITLE
Запретить goto внутрь блока

### ISSUE THREAD

**Issue by miks1965** [pascalabcnet/pascalabcnet#273]
У нас почему-то такое можно:

```
function f(x: integer): sequence of integer;
label 1;
begin
  goto 1;
  for var i:=1 to 10 do
  begin
    var z := 2;
    1:   
    Print(z);
  end;
end;

```

**Comment by miks1965** [comment]
Там в связи с yield этот код почему-то закомменчен. Разобраться.

**Comment by ibond84** [comment]
можно различить goto_statement по отсутствующему сорс-контексту (созданных по goto_statement.New). и для таких goto_statementов не генерировать ошибку

**Comment by miks1965** [comment]
Да, хорошая идея. Этот код закомментил Олег когда не мог совладать с yield
