### ISSUE TITLE
Рекурсивный `where` интерфейса-наследника не работает без дублирования рекурсивного `where` предка 

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#2736]
```
type
  t1<TSelf> = interface
    where TSelf: t1<TSelf>;
  end;
  //Ошибка: Невозможно инстанцировать, так как тип TSelf не реализует интерфейс t1<TSelf>
  t2<TSelf> = interface(t1<TSelf>)
    where TSelf: t2<TSelf>;
    // А если так то работает:
//    where TSelf: t1<TSelf>, t2<TSelf>;
  end;
  
begin end.
```
1. `TSelf` из `t2` реализует `t2<TSelf>` - это напрямую указано во `where`;
2. Всё что реализует `t2<TSelf>` - реализует и `t1<TSelf>`, потому что наследование;

Значит, `TSelf` из `t2` реализует и `t1<TSelf>`, а ошибка врёт.

А для классов не работает `where` в `t2`, потому что в #2640 и его исправлении я протестил только для методов.
Надо всё то же и для классов посмотреть.

Наверное исправлю сам как руки дойдут...

**Comment by ibond84** [comment]
Ну и чем можно инстанцировать t2, если там все рекурсивно?? Вы хотя бы класс, реализующий интерфейсы написали, чтобы можно было объект создать.

**Comment by ibond84** [comment]
```
 TClass = class(t2<TClass>)
  end;
```
