### ISSUE TITLE
What is the equivalent of C# [STAThread] on PascalABC.NET?

### ISSUE THREAD

**Issue by 3oheicrw** [pascalabcnet/pascalabcnet#2741]
I wanted to use this library with PascalABC.NET: https://github.com/mono/xwt

**Comment by SunSerega** [comment]
1. `[STAThread]` is just a setting of the main thread, you can always create a new thread and let the first die:
   ```
   var thr := new System.Threading.Thread(()->
   begin
     // Main code
   end);
   thr.ApartmentState := System.Threading.ApartmentState.STA;
   thr.Start;
   // End of original main
   ```
2. In PascalABC.Net, the main thread's state depends on the application type.
`{$apptype console}` is default for non-projects. It has the main thread in the MTA state and also creates a console window.
`{$apptype windows}` has the main thread in STA state and also creates no console window, unless:

   - The console window will still appear if any of the `Write`/`Print` subprograms are used: `CurrentIOSystem`'s default value of type `CurrentIOSystem` calls WinAPI `AllocConsole` on the first write.

   - If you start your program using F9 or the green arrow from IDE - even with `{$apptype windows}`, the .exe file will still create a console. This is to make sure the input window in IDE works.

---

For future: Issues are for bug reports. For everything else, we have a [forum](http://forum.mmcs.sfedu.ru/c/pascalabcnet/10).
Or, there are also Discussions in this repo, but fewer people check them.

**Comment by 3oheicrw** [comment]
> For future: Issues are for bug reports. For everything else, we have a [forum](http://forum.mmcs.sfedu.ru/c/pascalabcnet/10). Or, there are also Discussions in this repo, but fewer people check them.

I'm unable to register. It doesn't send verification email.
