### ISSUE TITLE
Перекомпилировать всё перестала работать между 1.01.22 и 09.01.22. Видимо после пуллреквеста SunSerega

### ISSUE THREAD

**Issue by miks1965** [pascalabcnet/pascalabcnet#2742]
Опубликую еще здесь - потому что это ошибки компилятора, а не среды
![изображение](https://user-images.githubusercontent.com/10325391/197358155-7307ca4c-3937-4d43-b285-d865edde2ef1.png)

**Comment by ibond84** [comment]
```
//ToDo то есть Rebuild режим игнорирует .pcu, даже если нет .pas файла?
            // а ещё ниже стоит ещё 1 проверка Rebuild...
            var PCUFileExists = !CompilerOptions.Rebuild && PCUFileName != null;
```

Такого раньше не было. Здесь проверяется Rebuld, но не учитывается, есть ли исходники!
