### ISSUE TITLE
Сделать директиву/атрибут для record отключающий автогенерацию функций сравнения на равенство

### ISSUE THREAD

**Issue by samuraiGH** [pascalabcnet/pascalabcnet#2747]
Так как функции сравнения на равенство являются, по сути, магическими и идентифицируются именно как операторы сравнения только компилятором pabc, была бы полезна возможность вообще их не генерировать. Это было бы удобно для библиотек, которые предполагается использовать не только в pabc.
Польза:
1. В типе не будет видно методов `op_Equality` и `op_Inequality`. По сути они засоряют тип, так как не могут быть использованы по назначению и не имеют интуитивного названия, выбиваются из стилистики нейминга
2. Не нужно писать перегрузки операторов `=`  `<>` что бы скрыть эти самые `op_Equality` и `op_Inequality`

http://forum.mmcs.sfedu.ru/t/mnimye-oshibki-pascalabc-net/1618/121

<details>
<summary>offtop</summary>
Ещё раз отмечу, что всё это можно решить просто генерируя обычные перегрузки операторов сравнения, а не магические методы
</details>

**Comment by ibond84** [comment]
Не буден никаких директив. Операторы сравнения видны теперь в C#

**Comment by samuraiGH** [comment]
@ibond84 в сборке 3206 всё ещё не видны
