### ISSUE TITLE
Записи, содержащие шаблонные подпрограммы, ограниченные классом, рушат компиляцию

### ISSUE THREAD

**Issue by samuraiGH** [pascalabcnet/pascalabcnet#2748]
```pas
type
  Base =  class end;
  
  r1 = record
    procedure pr1<T>(par1: T); where T: Base;
    begin end;
    
  end;
  
begin end.
```

> Program1.pas(4) : Не удалось загрузить тип "Program1.Base" из сборки "Program1, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null".

**Comment by ibond84** [comment]
https://github.com/pascalabcnet/pascalabcnet/actions/runs/3507673494
