### ISSUE TITLE
Что-то связанное с лямбдами и модификаторами доступа 

### ISSUE THREAD

**Issue by samuraiGH** [pascalabcnet/pascalabcnet#2749]
```pas
library lib;

interface
  
type
  c1 = class
    protected
    f1: string;
    
    procedure pr1;
    begin
      var arr1: array of integer;
      if arr1.All( item-> true ) then begin
        print(f1);
      end;
    end;

  end;

implementation end.
```
По такому коду генерится вот такое
![image](https://user-images.githubusercontent.com/87191377/202902816-45d171d0-0d9b-4a5d-b8f6-5827a711a1fa.png)

**Comment by SunSerega** [comment]
Кхм, ну в данном случае этих методов и не должно быть, потому что к ним нету доступа из лямбды.
Но вообще эти методы генерирует потому что чтобы лямбда видела `f1`. Ближайшая альтернатива это вложенные классы, которые паскаль не умеет генерировать.

Тем не менее, должно быть достаточно пометить эти методы как `internal`.

**Comment by samuraiGH** [comment]
@SunSerega а зачем это надо, если лямбда генерится в пределах класса? она же, по идее, и так должна видеть `f1`

**Comment by SunSerega** [comment]
> [@SunSerega](https://github.com/SunSerega) а зачем это надо, если лямбда генерится в пределах класса? она же, по идее, и так должна видеть f1

Зря удалили, ибо вы всё правильно говорите. Если лямбда не захватывает локальные переменные - её уже генерирует внутри класса (и в данном случае - статическим методом, потому что `self` тоже не захвачено).

Лучше генерировать эти вспомогательные методы для поля по необходимости, когда их запрашивает визитор лямбды.
