### ISSUE TITLE
Генерирует кривой IL для foreach по коллекции функций

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#2758]
```
##

procedure p1<T>(a: array of ()->T; v: T) :=
a[0] := ()->v;

var a := new Func0<integer>[1];
p1(a, 5);

foreach var x: integer in a do
  // Выводит мусор
  Writeln(x);
```
При чём если в этой же подпрограмме (в данном случае в `$Main`) есть лямбда - `foreach` перестаёт компилироваться, с очень странной ошибкой:
```
##

procedure p1<T>(a: array of ()->T; v: T) :=
a[0] := ()->v;

var a := new Func0<integer>[1];
p1(a, 5);

//Ошибка: Нельзя преобразовать тип integer к Func<integer>
foreach var x: integer in a do
  Writeln(x);

// Из-за этого не компилируется foreach
var p := procedure->exit();
```
Это отдельная issue?

**Comment by ibond84** [comment]
Первый код не должен компилироваться. Второй код правильно не компилируется

**Comment by ibond84** [comment]
https://github.com/pascalabcnet/pascalabcnet/actions/runs/3724526297

**Comment by SunSerega** [comment]
Где вы во втором коде видите преобразование `integer` к `Func<integer>`?

**Comment by ibond84** [comment]
a это массив делегатов. Поэтому идет преобразование.

**Comment by SunSerega** [comment]
Да, преобразование `Func<integer>` к `integer`, а не наоборот.

**Comment by ibond84** [comment]
Согласен

**Comment by SunSerega** [comment]
Так отдельная issue или...?

**Comment by ibond84** [comment]
Нет. Сейчас закоммичу исправление.

**Comment by ibond84** [comment]
https://github.com/pascalabcnet/pascalabcnet/actions/runs/3724924633
