### ISSUE TITLE
[bug] Сломан оператор with ... do

### ISSUE THREAD

**Issue by bormant** [pascalabcnet/pascalabcnet#2759]
Версия 3.8.3.3211

```
type
  TRec = record
    a, b: Real;
  end;

const n=2;
var   a: array [0..n-1,0..n-1] of TRec;
begin
  for var i:=0 to n-1 do for var j:=0 to n-1 do
    with a[i,j] do
      Read(a,b);

  for var i:=0 to n-1 do for var j:=0 to n-1 do
      Write(' ',a[i,j].a,' ',a[i,j].b);
end.
```
Ввод: 
```
1 2 3 4 5 6 7 8
```
Вывод (фактический):
```
 0 0 0 0 0 0 0 0
```
Вывод (ожидаемый):
```
 1 2 3 4 5 6 7 8
```

**Comment by bormant** [comment]
Если ввод переписать без with do
```
  for var i:=0 to n-1 do for var j:=0 to n-1 do
      Read(a[i,j].a, a[i,j].b);
```
то вывод станет соответствовать ожидаемому.

**Comment by miks1965** [comment]
```type
  TRec = record
    a, b: Real;
  end;

begin
  var a: array [0..1,0..1] of TRec;
  with a[0,0] do
    Read(a);

  Print(a[0,0].a);
end.
```

**Comment by miks1965** [comment]
![изображение](https://user-images.githubusercontent.com/10325391/208596150-6cfd790b-138a-4b8c-be8b-a895d748ac09.png)

**Comment by miks1965** [comment]
На одномерных всё нормально. Редкая ошибка

**Comment by miks1965** [comment]
Для такой программы
```
type
  TRec = record
    b: Real;
  end;

begin
  var a: array [0..1,0..1] of TRec;
  a[0,0].b := 2;

  Print(a[0,0].b);
end.
```
нормальный код:
![изображение](https://user-images.githubusercontent.com/10325391/208597330-d93a34d8-ec1f-4d54-a7c1-fa277515b065.png)

**Comment by ibond84** [comment]
Копирование происходит, потому что для горизонтального среза массива (a[0]) заводится локальная переменная

**Comment by ibond84** [comment]
https://github.com/pascalabcnet/pascalabcnet/actions/runs/3775469495
