### ISSUE TITLE
Вернуть ускорение foreach для массивов

### ISSUE THREAD

**Issue by miks1965** [pascalabcnet/pascalabcnet#276]
Вернуть ускорение foreach для массивов

**Comment by miks1965** [comment]
Там были какие-то другие мотивы - по-моему, то, что менялся код, но не в синтаксическом дереве, а на лету, а потом код для лямбд в конце блока повторно проходил и проходил по старому коду и не находил каких-то переменных

**Comment by ibond84** [comment]
А какое именно? Последнее, с заменой на for?

**Comment by miks1965** [comment]
Это моя проблема. Там сложный баг - лямбды повторно обходят старый код, а он уже изменился, и они падают - новую переменную не могут найти.

**Comment by miks1965** [comment]
Вернул ускорение. Несмотря на повторный обход с лямбдой, дело было в генерации кода для for.
