### ISSUE TITLE
Ошибка при распаковке кортежей.

### ISSUE THREAD

**Issue by MihailGutrov** [pascalabcnet/pascalabcnet#2764]
```
### uses school;
var arr:=|12,23,34,45,56,67,78,89|;
arr.Numerate.Nwise(3).where(\(\(a,b),\(b,c),\(c,d)) → a>d).pr
```

При данной распаковке появляется ошибка
` Слишком много переменных при распаковке кортежа`

**Comment by miks1965** [comment]
Проблема хуже:
```
begin
  var arr:=|12,23,34,45,56,67,78,89|;
  arr.Numerate.Nwise(3).where(
    t → begin
      var (fr1,fr2) := t;
      var (a,b) := fr1;
      var (c,d,e) := fr2;
      Result := a>b
    end)
end.
```
a2.pas(7) : Слишком много переменных при распаковке кортежа

**Comment by SunSerega** [comment]
А по моему это как раз правильная ошибка.
- Тип `t` это `array of (integer,integer)`; всего 3 элемента, но только первые 2 распаковывает в переменные
- Тип `fr1` это `(integer,integer)`; распаковка в 2 переменные работает нормально.
- Тип `fr2` это тоже `(integer,integer)`; распаковка в 3 переменные говорит что переменной `e` нечего присвоить.

**Comment by miks1965** [comment]
Да, согласен

**Comment by miks1965** [comment]
Вот неправильная
```
begin
  var arr:=|12,23,34,45,56,67,78,89|;
  arr.Numerate.Nwise(3).where(
    t → begin
      var (fr1,fr2,fr3) := t;
      Result := True
    end
    ).ToArray
end.
```
