### ISSUE TITLE
Синтаксис не ожидает `if`-выражение в под-выражении инициализатора переменной с явным типом

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#2766]
```
##
// С тренарником работает
var x1: byte := (true ? 1 : 2);
// И если if-выражение является корневой нодой тоже
var x2: byte := if true then 1 else 2;
//Ошибка: Встречено 'if', а ожидалось выражение
var x3: byte := (if true then 1 else 2);
```

**Comment by miks1965** [comment]
А это грамматика не позволяет

**Comment by SunSerega** [comment]
Так а почему тренарник работает тогда?

**Comment by SunSerega** [comment]
И синтаксическая ошибка однозначно говорит "ожидалось выражение" - то есть конкретно в этом примере не пытается лямбду пропарсить там где `if`.

**Comment by miks1965** [comment]
Еще раз - в грамматике этого нет потому что при попытке сделать возникают конфликты в грамматике. У второго тернарника не возникают.

Какая ошибка выдается когда этого нет в грамматике - совсем другой вопрос.
