### ISSUE TITLE
SizeOf(), Low(), High() не принимают аргументом переменную не-массив

### ISSUE THREAD

**Issue by bormant** [pascalabcnet/pascalabcnet#2767]
PascalABC.NET версия 3.8.3 сборка 3214 (20.12.2022)

```
var t: Integer;
begin
  t:=SizeOf(t);  // Ошибка: Ожидался тип
  t:=Low(t);     // Ошибка: Нельзя преобразовать тип integer к array
  t:=High(t);    // Ошибка: Нельзя преобразовать тип integer к array
end.
```
При этом и Delphi, и FPC, и Turbo Pascal такой синтаксис понимают, действуя в таком случае в соответствии с _типом_ аргумента.

**Comment by miks1965** [comment]
Это отсутствие в стандартном модуле этих функций, а не ошибка синтаксиса

**Comment by bormant** [comment]
Ок, так и запишем -- запланированная несовместимость.

**Comment by AlexRnD61** [comment]
Я даже придумать затрудняюсь, для чего в современном Паскале может потребоваться SizeOf.

**Comment by miks1965** [comment]
sizeof - хорошая конструкция, но надо понимать, что она делается не средствами языка, а средствами компилятора. sizeof(тип) - такую функцию определить нельзя. Поэтому sizeof (тип)- унарная операция, а sizeof - ключевое слово. А здесь требуют сделать еще и одноименную функцию sizeof(i). Это - большая нерегулярность языка.

**Comment by SunSerega** [comment]
Ну вообще никто не говорил `sizeof(i)` делать функцией в `PABCSystem`...
И средства языка уже есть, встроенные в .Net:
```
## var x := 5;
System.Runtime.InteropServices.Marshal.SizeOf(x).Println;
```

**Comment by miks1965** [comment]
Issue как раз про это
