### ISSUE TITLE
Внутренняя ошибка компилятора при попытке описать обобщенную переменную в ML.NET

### ISSUE THREAD

**Issue by miks1965** [pascalabcnet/pascalabcnet#2768]
```
{$reference Microsoft.ML.Core.dll}
{$reference Microsoft.ML.Data.dll}
{$reference Microsoft.ML.KMeansClustering.dll}

uses Microsoft.ML;
uses Microsoft.ML.Data;
uses Microsoft.ML.Trainers;
 
begin
  var trainer: IEstimator<ClusteringPredictionTransformer<KMeansModelParameters>>;
end.
```
Внутренняя ошибка компилятора в модуле Compiler.Compile[a1.pas] :'System.ArgumentException: GenericArguments[0], "Microsoft.ML.Data.ClusteringPredictionTransformer`1[Microsoft.ML.Trainers.KMeansModelParameters]", в "Microsoft.ML.IEstimator`1[TTransformer]" не удовлетворяет ограничению типа параметра "TTransformer". ---> System.TypeLoadException: GenericArguments[0], "Microsoft.ML.Data.ClusteringPredictionTransformer`1[Microsoft.ML.Trainers.KMeansModelParameters]", в "Microsoft.ML.IEstimator`1[TTransformer]" не удовлетворяет ограничению на параметр типа "TTransformer".
   в System.RuntimeTypeHandle.Instantiate(RuntimeTypeHandle handle, IntPtr* pInst, Int32 numGenericArgs, ObjectHandleOnStack type)
   в System.RuntimeTypeHandle.Instantiate(Type[] inst)
   в System.RuntimeType.MakeGenericType(Type[] instantiation)
   --- Конец трассировки внутреннего стека исключений ---
   в PascalABCCompiler.TreeConverter.syntax_tree_visitor.visit(statement_list _statement_list) в D:\PABC_Git\TreeConverter\TreeConversion\syntax_tree_visitor.cs:строка 18049
   в PascalABCCompiler.SyntaxTree.statement_list.visit(IVisitor visitor) в D:\PABC_Git\SyntaxTree\tree\Tree.cs:строка 752
   в PascalABCCompiler.TreeConverter.returner.visit(statement st) в D:\PABC_Git\TreeConverter\TreeConversion\returner.cs:строка 47
   в PascalABCCompiler.TreeConverter.syntax_tree_visitor.convert_strong(statement st) в D:\PABC_Git\TreeConverter\TreeConversion\syntax_tree_visitor.cs:строка 808
   в ...

**Comment by ibond84** [comment]
Исправлено

**Comment by ibond84** [comment]
https://github.com/pascalabcnet/pascalabcnet/commit/88323a06759ff2e115dd3d8980a0a88d091a9cc4
