### ISSUE TITLE
Подпрограммы не чистят `peek`

### ISSUE THREAD

**Issue by Anonymous87549236** [pascalabcnet/pascalabcnet#2796]
Некоторые стандартные подпрограммы перед своим завершением не очищают `peek` с помощью `read_symbol`, поэтому это влияет на результат подпрограммы, которая выполняется дальше и использует `sym`. Следует вызывать `read_symbol` перед выходом из подпрограммы, если в ней была использована `peek`.
Скорее всего, в приведённом примере упомянуты не все стандартные подпрограммы. Остальные возможно найти, если найти все упоминания `peek` в `PABCSystem`.
```
##
Writeln(ReadlnChar); // нормально
var s: string;
Read(s); // оставляет peek после завершения
Writeln(s);
Writeln(Ord(ReadlnChar)); // поэтому теперь первый вызов вернёт неправильное значение (CR)
Writeln(ReadlnChar); // нормально
s := ReadLexem; // оставляет peek после завершения
Writeln(s);
Writeln(Ord(ReadlnChar)); // поэтому теперь первый вызов вернёт неправильное значение (CR)
Writeln(ReadlnChar); // нормально
```

**Comment by SunSerega** [comment]
Результат `peek` и не должно очищать.
```
##
ReadInteger.Println;
ReadChar.Code.Println;
ReadInteger.Println;
```
При вводе 1 строки:
```
1 2
```
Первый `ReadInteger` читает только число, поэтому следующий `ReadChar` выводит 32 - код пробела. И, после этого, ещё 1 `ReadInteger` может из той же строки прочитать число.
`ln` после `Read` как раз значит прочитать всё до (включая) символа конца строки. Если вы используете `Read` без `ln` - конец строки должен оставаться после прочитанного.

**Comment by miks1965** [comment]
Верно. Используйте readln
