### ISSUE TITLE
"Среда выполнения обнаружила недопустимую программу", если передать в `Print` два делегата

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#2798]
```
## function f1(x: integer) := 0;
Print(f1,f1); // С Write тоже ломается, с доп. танцами с бубном
```
```
Ошибка времени выполнения: System.InvalidProgramException: Среда выполнения Common Language Runtime обнаружила недопустимую программу.
Стек:
   в Program2.Program.$Main()
   в Program2.Program.Main()
```
IL:
```
    IL_0000: nop
    IL_0001: ldc.i4.2
    IL_0002: newarr       [mscorlib]System.Object
    IL_0007: stloc.0      // V_0
    IL_0008: ldloc.0      // V_0
    IL_0009: ldc.i4.0
    IL_000a: ldnull
    IL_000b: ldftn        int32 Program2.Program::f1(int32)
    IL_0011: newobj       instance void Program2.$delegate0::.ctor(object, native int)
    IL_0016: stelem.ref
    IL_0017: ldloc.0      // V_0
    IL_0018: ldc.i4.1
    IL_0019: stelem.ref
    IL_001a: ldloc.0      // V_0
    IL_001b: call         void PABCSystem.PABCSystem::Print(object[])
    IL_0020: nop
    IL_0021: ret
```
Наверное проблема в том, что на стек загружает массив (`IL_0017`) и второй индекс (`IL_0018`), но не само значение, которое в эту ячейку надо записать.

**Comment by miks1965** [comment]
```
function f1(x: integer) := 0;
function f2(x: integer) := 0;

procedure Pri(params p: array of object);
begin
  
end;

begin
  Pri(f1,f2);
end.
```
Здесь тоже падает

**Comment by miks1965** [comment]
А здесь - внутренняя ошибка компилятора:
```
function f1(x: integer) := 0;
function f2(x: integer) := 0;

procedure Pri(p1,p2: object);
begin
  
end;

begin
  Pri(f1,f2);
end.
```
:'System.NullReferenceException: Ссылка на объект не указывает на экземпляр объекта.
   в PascalABCCompiler.NETGenerator.ILConverter.EmitArguments(IParameterNode[] parameters, IExpressionNode[] real_parameters)
   в PascalABCCompiler.NETGenerator.ILConverter.visit(ICommonNamespaceFunctionCallNode value)
   в PascalABCCompiler.NETGenerator.ILConverter.ConvertStatement(IStatementNode value)
   в PascalABCCompiler.NETGenerator.ILConverter.visit(IStatementsListNode value)
   в PascalABCCompiler.NETGenerator.ILConverter.ConvertBody(IStatementNode body)

**Comment by ibond84** [comment]
https://github.com/pascalabcnet/pascalabcnet/actions/runs/4096082414
