### ISSUE TITLE
Тесты под Линуксом не работают

### ISSUE THREAD

**Issue by ulysses4ever** [pascalabcnet/pascalabcnet#28]
В `bin/TestRunner.pas` захардкожены виндосовские разделители в путях (`\`), соответственно, `bin/TestRunner.exe` не может ничего найти. Я хотел исправить на `/` (кажется, работает везде) или хотя бы на `Path.DirectorySeparatorChar`, но не получилось скомпилировать `bin/TestRunner.pas`, пишут

> [4,3] TestRunner.pas: Assembly 'CodeCompletion.dll' not found

Действительно, не вижу этой dll.

**Comment by ulysses4ever** [comment]
Кстати, при попытке запуска `TestRunner.exe` в Виндовсе он крашится с жалобами, что не может найти `"d:\err.txt"`. Ужас какой-то.

**Comment by ibond84** [comment]
>Кстати, при попытке запуска TestRunner.exe в Виндовсе он крашится с жалобами, что не может найти "d:\err.txt". Ужас какой-то.

Исправлено.

**Comment by ibond84** [comment]
Но у вас где-то ошибка. Исключений в TestRunner не должно быть. Посмотрите, что выскакивает в окне Assert

**Comment by ibond84** [comment]
Прогон тестов под Линукс сделаю позже.

**Comment by ulysses4ever** [comment]
![default](https://cloud.githubusercontent.com/assets/6832600/12024022/f2a9a046-adb0-11e5-8913-00141dd0c14b.png)

**Comment by ibond84** [comment]
Вы пересобрали проект?

**Comment by ulysses4ever** [comment]
Извиняюсь, действительно не собрал. Пытаюсь тут понять, как правильно перемещаться по истории, чтобы и ваши изменения учесть, и кодировки проверить.

**Comment by ulysses4ever** [comment]
> Прогон тестов под Линукс сделаю позже.

Да в принципе, я бы и сам мог, если там только в сепараторе проблема. Но сейчас задумался про #30.

**Comment by ibond84** [comment]
Так, тесты под Linux работают. Пришлось исключить несколько тестов с указателями. Они под Mono не заработали. Думаю, на это можно забить. 
Я изменил инструкции сборки в README.md. Теперь все выполняется одной командой. Желательно установить свежую Mono (4.2). В репах Ubuntu какая-то доисторическая версия 3.2.

**Comment by ulysses4ever** [comment]
Спасибо большое! Пока времени проверить нет, так что, наверное, имеет смысл
закрывать, я потом посмотрю.

Указатели, думаю, действительно, не нужны.
