### ISSUE TITLE
При попытке завершения работы Windows - сообщение об ошибке

### ISSUE THREAD

**Issue by miks1965** [pascalabcnet/pascalabcnet#280]
если не сохранил программу, то при попытке завершения работы или выхода из пользователя выдается сообщение об ошибке

**Comment by ibond84** [comment]
Ну, наш консольный компилятор при завершении стартуется заново (если только сама среда не закроет). Непонятно, почему Windows игнорирует порядок Parent-Child и посылает всем подряд сообщение WM_CLOSE. Короче, ошибка неисправляема. И нечего так завершать Windows.  Закрываю.
