### ISSUE TITLE
GraphABCHelper: Неправильный параметр в b2.UnlockBits

### ISSUE THREAD

**Issue by softexe** [pascalabcnet/pascalabcnet#2800]
Дважды освобождается блок bmpData1 вместо bmpData2, в Windows проходит, в Linux вызывает exception.

```
  b2.UnlockBits(bmpData1);
  b1.UnlockBits(bmpData1);
```

https://github.com/pascalabcnet/pascalabcnet/blob/ccbf5c8d5ba3096bcf21487970229a895f31985a/bin/Lib/GraphABCHelper.pas#L118

**Comment by SunSerega** [comment]
Если уже конкретные строки находите - лучше бы PR кинули, вместо issue. Но
1. Тут допустим понятно, но всё равно старайтесь описывать подробнее что именно исправляете, вместо "если так поменять - у меня всё работает".
2. Как показывает #1573 - даже решение проблемы, на которую постоянно натыкаются школьники на куберфоруме, не является хорошей причиной лезть в это легаси.

**Comment by softexe** [comment]
> 1. Тут допустим понятно, но всё равно старайтесь описывать подробнее что именно исправляете, вместо "если так поменять - у меня всё работает".

не понял, тут то явная описка в коде, которую найти, потребовалось изменить код ещё в нескольких местах, чтобы работало под Линукс ибо до этого места просто не доходило.

**Comment by miks1965** [comment]
Исправил так:

  b2.UnlockBits(bmpData2);
  b1.UnlockBits(bmpData1);

После этого в Линуксе всё будет работать?

**Comment by softexe** [comment]
> 

ImageIntersect - да, но для чтобы заработал ABCObjects требуется замена функции GetView

**Comment by miks1965** [comment]
А как заменить - приведите код?

**Comment by softexe** [comment]
```
function GetView(b: Bitmap; r: System.Drawing.Rectangle): Bitmap;

begin

     var bmp := new Bitmap(r.Width, r.Height);

     var gph := Graphics.FromImage(bmp);

     gph.DrawImage(b, new System.Drawing.Rectangle(0, 0, bmp.Width, bmp.Height), r, GraphicsUnit.Pixel);

     gph := nil;

     result := bmp;

end;

```


```

function ImageIntersect(b1,b2: Bitmap): boolean;

// Предполагается, что b1 и b2 - одного размера

type 

  RGB = record

    r,g,b: byte;

  end;

  PRGB = ^uint32;

label 1;

var

  ptr1,ptr2: pointer;

  iptr1,iptr2: IntPtr;

  p1,p2: PRGB;

  rect: System.Drawing.Rectangle;

  bmpData1,bmpData2: System.Drawing.Imaging.BitmapData;

begin

  rect := new System.Drawing.Rectangle(0,0,b1.Width,b1.Height);

  bmpData1 := b1.LockBits(rect, System.Drawing.Imaging.ImageLockMode.ReadWrite, b1.PixelFormat);

  ptr1 := bmpData1.Scan0.ToPointer;

  iptr1 := IntPtr(ptr1);



  bmpData2 := b2.LockBits(rect, System.Drawing.Imaging.ImageLockMode.ReadWrite, b2.PixelFormat);

  ptr2 := bmpData2.Scan0.ToPointer;

  iptr2 := IntPtr(ptr2);



  var pixelFormatSize := Image.GetPixelFormatSize(b1.PixelFormat) div 8;

  var Offset := bmpData1.stride - b1.Width * pixelFormatSize; 

  

  Result := False;

  for var y:=0 to b1.Height-1 do

  begin

    for var x:=0 to b1.Width-1 do

    begin

      p1 := PRGB(pointer(iptr1));

      p2 := PRGB(pointer(iptr2));

      //writeln(p1^.R,' ',p1^.G,' ',p1^.B,'  ',p2^.R,' ',p2^.G,' ',p2^.B);

   //  if ((p1^.R and p1^.G and p1^.B)<>$FF) and ((p2^.R and p2^.G and p2^.B)<>$FF) then

      if (p1^<>$FFFFFFFF) and (p2^<>$FFFFFFFF) then

      begin

        Result := True;

        goto 1;

      end;

      iptr1 := iptr1 + pixelFormatSize;

      iptr2 := iptr2 + pixelFormatSize;

    end;

    iptr1 := iptr1 + Offset;

    iptr2 := iptr2 + Offset;

  end;

1:  

  b2.UnlockBits(bmpData2);

  b1.UnlockBits(bmpData1);

end; 

```

**Comment by SunSerega** [comment]
> ```
> ptr2 := bmpData2.Scan0.ToPointer;
> iptr2 := IntPtr(ptr2);
> ```

У `bmpData2.Scan0` и так тип `IntPtr`.

**Comment by softexe** [comment]
> > ```
> > ptr2 := bmpData2.Scan0.ToPointer;
> > iptr2 := IntPtr(ptr2);
> > ```
> 
> У `bmpData2.Scan0` и так тип `IntPtr`.

ругалось на преобразование типов, переделывать не стал...
![изображение](https://user-images.githubusercontent.com/7357924/218803428-4581a839-84b2-4a85-aab5-78554eaa0b66.png)

**Comment by SunSerega** [comment]
> ругалось на преобразование типов, переделывать не стал...

Ну вы разве не видите `.ToPointer` на предыдущей строчке?

**Comment by softexe** [comment]
> > ругалось на преобразование типов, переделывать не стал...
> 
> Ну вы разве не видите `.ToPointer` на предыдущей строчке?

Честно не вникал, делал, только то что явно не работало.

А так - да. получается и без этих дополнительных переменных.
```

function ImageIntersect(b1,b2: Bitmap): boolean;

// Предполагается, что b1 и b2 - одного размера

type 

  RGB = record

    r,g,b: byte;

  end;

  PRGB = ^uint32;

label 1;

var

  ptr1,ptr2: IntPtr;

  p1,p2: PRGB;

  rect: System.Drawing.Rectangle;

  bmpData1,bmpData2: System.Drawing.Imaging.BitmapData;

begin

  rect := new System.Drawing.Rectangle(0,0,b1.Width,b1.Height);

  bmpData1 := b1.LockBits(rect, System.Drawing.Imaging.ImageLockMode.ReadWrite, b1.PixelFormat);

  ptr1 := bmpData1.Scan0;



  bmpData2 := b2.LockBits(rect, System.Drawing.Imaging.ImageLockMode.ReadWrite, b2.PixelFormat);

  ptr2 := bmpData2.Scan0;



  var pixelFormatSize := Image.GetPixelFormatSize(b1.PixelFormat) div 8;

  var Offset := bmpData1.stride - b1.Width * pixelFormatSize; 

  

  Result := False;

  for var y:=0 to b1.Height-1 do

  begin

    for var x:=0 to b1.Width-1 do

    begin

      p1 := PRGB(pointer(ptr1));

      p2 := PRGB(pointer(ptr2));

      //writeln(p1^.R,' ',p1^.G,' ',p1^.B,'  ',p2^.R,' ',p2^.G,' ',p2^.B);

//      if ((p1^.R and p1^.G and p1^.B)<>$FF) and ((p2^.R and p2^.G and p2^.B)<>$FF) then

      if (p1^<>$FFFFFFFF) and (p2^<>$FFFFFFFF) then

      begin

        Result := True;

        goto 1;

      end;

      ptr1 := ptr1 + pixelFormatSize;

      ptr2 := ptr2 + pixelFormatSize;

    end;

    ptr1 := ptr1 + Offset;

    ptr2 := ptr2 + Offset;

  end;

1:  

  b2.UnlockBits(bmpData2);

  b1.UnlockBits(bmpData1);

end; 
```

**Comment by miks1965** [comment]
Что то подозрительно GetView короткая. Мне кажется, она у вас существенно медленнее работает.

Я конечно уже не помню все детали, но хорошо бы потестировать на производительность и сравнить. Ну там 1000 объектов и один перемещается.

**Comment by softexe** [comment]
> она у вас существенно медленнее работает

Где то на 20% (20 vs 18 fps) медленее вариант с Draw, чем существующая реализация на примере gr_MovingObjects с 1000 объектами на win10 .  На линукс в виртуалке средний фпс получается 7-7.5 с этим же кодом. Но тут тормоза добавляет виртуалка, надо проверить на "железе"  Зато этот вариант компактен в реализации и работает везде.

Есть ещё альтернативная реализация GetView на основе Buffer.MemoryCopy. На виндовс даёт практически те же цифры фпс, что и текущая реализация (20-21), но под линукс работает медленее (6.5), возможно также из за виртуалки.

**Comment by SunSerega** [comment]
На самом деле, `Bitmap` поидее может хранить содержимое в памяти `GPU` - для этого собственно семантика `.LockBits`
В таком случае блокирование и копирование на стороне CPU будет даже медленнее.

Ну и я думаю `Graphics.DrawImage` правильно обрабатывает форматы. К примеру `w * pixelFormatSize` в оригинальном `GetView` вместо `bmpData.Stride` это глупость:
```
function GetView(b: Bitmap; r: System.Drawing.Rectangle): Bitmap;
var 
  w,h,stride,padding,pixelFormatSize: integer;
  ptr,start: System.IntPtr;
  rect: System.Drawing.Rectangle;
  bmpData: System.Drawing.Imaging.BitmapData;
begin
  w := b.Width;
  h := b.Height;
  rect := new System.Drawing.Rectangle(0,0,w,h);
  bmpData := b.LockBits(rect, System.Drawing.Imaging.ImageLockMode.ReadWrite, b.PixelFormat);
          
  ptr := bmpData.Scan0;
  b.UnlockBits(bmpData);
  

  pixelFormatSize := Image.GetPixelFormatSize(b.PixelFormat) div 8;
  
  r := System.Drawing.Rectangle.Intersect(r,rect);
  start := (System.IntPtr)(integer(ptr) + w * pixelFormatSize * r.Y + r.X * pixelFormatSize);

  stride := w * pixelFormatSize;
  padding := stride mod 4;
  if padding<>0 then 
    stride := stride + 4 - padding; //pad out to multiple of 4

  Result := new Bitmap(r.Width,r.Height,stride,b.PixelFormat,start);
end;
```

**Comment by SunSerega** [comment]
@softexe скиньте тот пример с вашими настройками, архивом, чтобы сразу работало - я протесчу на своей машине с норм GPU. На Win10 и арч линуксе.

**Comment by softexe** [comment]
> @softexe скиньте тот пример с вашими настройками, архивом, чтобы сразу работало - я протесчу на своей машине с норм GPU. На Win10 и арч линуксе.

[TestABC.zip](https://github.com/pascalabcnet/pascalabcnet/files/10773871/TestABC.zip)
В архиве измененный ABCObjects с переопределенными функциями GetView и ImageIntersect из GraphABCHelper (чтобы не тянуть с собой GraphABC и GraphABCHelper модули)
Для тестов производительности использовал gr_MovingObjects с 1000 объектами.

GetView представлен несколькими вариантами, по умолчанию используется из GraphABCHelper, который не работает на Linux. Убираем суфиксную часть в названии функции, например в GetViewC это будет "С" и тогда будет использоваться эта функция, в данном случае с использованием Bitmap.Clone. Это вариант показал себя лучше всего на обеих платформах. GetView1 близка к оригиналу, но есть сомнения в её корректной работе в линукс в виртуалке, на реальной линукс машине работает с результатами близкими к оригинальной функции.

**Comment by miks1965** [comment]
Неправильный параметр давно исправил. Закрываю.

**Comment by SunSerega** [comment]
Чуток закопался в теорию... В GDI вроде как есть графическое ускорение, но то что обёртывает WinForms - это всё на стороне CPU.

Ну, тем не менее, раз уж взялся... Ни остаётся ничего, кроме как приделать нитро-выхлоп к вашему трактору:
```
  var iter := procedure->
  begin
    for var i:=0 to Objects.Count-1 do
      Move(Objects[i]);
    if AnimationIsFast then
      RedrawObjects;
  end;
  loop 2 do iter;
  
  var sw := new Stopwatch;
  var timings := |1,3,5,10,50,100|.ConvertAll(sz->
    new Queue<System.TimeSpan>(ArrFill(sz,System.TimeSpan.Zero))
  );
  var timings_min := ArrFill(timings.Length, real.NaN);
  var timings_max := ArrFill(timings.Length, real.NaN);
  
  var k := 0;
  while True do
  begin
    sw.Start;
    iter;
    sw.Stop;
    k += 1;
    
    var title := new StringBuilder;
    title += $'{k,5}f: {k/sw.Elapsed.TotalSeconds,5:f3}';
    foreach var q in timings index i do
    begin
      var prev := q.Dequeue;
      q.Enqueue(sw.Elapsed);
      if k<q.Count then continue;
      var curr := q.Count/(sw.Elapsed-prev).TotalSeconds;
      timings_min[i] := |curr, timings_min[i]|.Min;
      timings_max[i] := |curr, timings_max[i]|.Max;
      title += $'; {q.Count}f: {curr,5:f3} ({timings_min[i],5:f3}..{timings_max[i],5:f3})';
    end;
    Window.Title := title.ToString;//Format('{0:f5}',k/sw.Elapsed.TotalSeconds)+' кадров в секунду';
    System.Windows.Forms.Clipboard.SetText(Window.Title);
  end;
```
В начале ещё:
```
  Window.Maximize;
```
И в `ABCObjectsFix.pas`:
```
function GetView(b: Bitmap; r: System.Drawing.Rectangle) := GetView0(b,r);
```
(чтобы проще подменять)

P.S. В процессе ещё нашёл `b.UnlockBits` отгружающее `Scan0` до первого использования в нескольких местах. Но крашатся первые 2 в линуксе и без него.

---

Win10:

- `GetView0`:   250f: 1.909; 1f: 1.901 (1.853..1.938); 3f: 1.895 (1.888..1.925); 5f: 1.898 (1.891..1.922); 10f: 1.897 (1.895..1.920); 50f: 1.904 (1.904..1.915); 100f: 1.907 (1.907..1.913)
- `GetView1`:   250f: 1.923; 1f: 1.934 (1.881..1.954); 3f: 1.932 (1.899..1.942); 5f: 1.932 (1.900..1.940); 10f: 1.936 (1.901..1.937); 50f: 1.930 (1.912..1.933); 100f: 1.930 (1.914..1.930)
- `GetView2`: ~0.25, ну его
- `GetViewС`:   250f: 1.915; 1f: 1.911 (1.889..1.941); 3f: 1.918 (1.900..1.931); 5f: 1.919 (1.901..1.926); 10f: 1.919 (1.905..1.925); 50f: 1.917 (1.909..1.918); 100f: 1.917 (1.911..1.917)
- `GetViewDI`:   250f: 1.430; 1f: 1.446 (1.379..1.464); 3f: 1.431 (1.391..1.457); 5f: 1.433 (1.394..1.456); 10f: 1.426 (1.398..1.453); 50f: 1.438 (1.402..1.445); 100f: 1.440 (1.413..1.443)
- `GetViewMC`:   250f: 1.891; 1f: 1.909 (1.860..1.913); 3f: 1.902 (1.873..1.903); 5f: 1.895 (1.877..1.903); 10f: 1.898 (1.880..1.900); 50f: 1.895 (1.885..1.895); 100f: 1.894 (1.887..1.894)
- `GetViewIB`: ~0.24
- `GetViewEx`: ~0.50
- `GetViewEx2`:   250f: 1.698; 1f: 1.683 (1.558..2.472); 3f: 1.663 (1.598..2.450); 5f: 1.664 (1.623..2.450); 10f: 1.674 (1.647..2.442); 50f: 1.819 (1.662..1.820); 100f: 1.744 (1.665..1.745)

Стоит заметить, любое взаимодействие с виндой, даже открытие авто-сворачивающейся панели задач, снижало fps до ~1.3 во всех случаях...
В итоге мерял с закрытым браузером и даже без музыки на фоне)) Теперь так же с линуксом...

---

Arch Linux (только обновил всё, даже aur) + Mono:

- `GetView0`: Краш
- `GetView1`: Краш
- `GetView2`: ~0.1
- `GetViewС`:   250f: 6.751; 1f: 6.609 (4.786..9.468); 3f: 6.938 (5.509..8.809); 5f: 6.793 (5.725..8.697); 10f: 6.859 (5.931..8.127); 50f: 6.982 (6.156..7.558); 100f: 6.973 (6.379..7.125)
- `GetViewDI`:   250f: 6.177; 1f: 7.386 (4.617..8.351); 3f: 7.067 (5.078..7.474); 5f: 6.452 (5.435..7.349); 10f: 6.127 (5.511..7.267); 50f: 6.070 (5.949..6.532); 100f: 6.083 (6.047..6.424)
- `GetViewMC`:   250f: 6.473; 1f: 4.972 (4.762..8.357); 3f: 5.649 (5.300..7.845); 5f: 5.824 (5.565..7.700); 10f: 6.034 (5.606..7.582); 50f: 6.208 (5.978..6.870); 100f: 6.508 (6.326..6.690)
- `GetViewIB`: ~0.1
- `GetViewEx`: ~0.23
- `GetViewEx2`: ~0.31

При этом всюду где было >1fps - наблюдалось значительное использование GPU
Но, в то же время, были артефакты - края звёздочек в некоторых местах размазывались

И ещё, тут явно не хватало синхронизации
К примеру `Window.Maximize` в начале программы срабатывало после того как большую часть объектов уже поместило в форму меньшего размера 
Возможно это так же является причиной артефактов

Попробовал ещё с Wine.
Сначала он решил поставить ещё 1 Mono (хотя вроде бы их костыльный .Net уже стоял). Как поставил - вообще отказался что-либо запускать.
Попробовал компилятор тоже запускать из под Wine - и к сожалению теперь всё заработало. Но не забыло параллельно покрыть мне экран ошибками типа "не могу запустить":

- `GetView0`:   250f: 2.634; 1f: 2.739 (2.078..3.606); 3f: 2.774 (2.170..3.547); 5f: 2.690 (2.216..3.435); 10f: 2.541 (2.294..3.325); 50f: 2.511 (2.440..3.128); 100f: 2.528 (2.477..2.841)
- `GetView1`:   250f: 2.516; 1f: 2.604 (2.022..3.484); 3f: 2.473 (2.200..3.243); 5f: 2.347 (2.281..3.178); 10f: 2.480 (2.338..3.066); 50f: 2.453 (2.394..2.623); 100f: 2.446 (2.446..2.584)
- `GetView2`: ~0.15
- `GetViewС`:   250f: 2.670; 1f: 2.655 (2.036..3.554); 3f: 2.661 (2.304..3.420); 5f: 2.707 (2.383..3.298); 10f: 2.664 (2.440..3.208); 50f: 2.554 (2.523..3.128); 100f: 2.556 (2.544..2.863)
- `GetViewDI`:   250f: 2.605; 1f: 2.714 (2.035..3.301); 3f: 2.364 (2.128..3.174); 5f: 2.426 (2.213..3.111); 10f: 2.478 (2.362..3.073); 50f: 2.469 (2.427..2.992); 100f: 2.456 (2.442..2.853)
- `GetViewMC`:   250f: 2.640; 1f: 2.608 (2.137..3.325); 3f: 2.581 (2.338..3.228); 5f: 2.624 (2.400..3.161); 10f: 2.523 (2.436..3.077); 50f: 2.569 (2.553..2.871); 100f: 2.576 (2.576..2.705)
- `GetViewIB`: ~0.14
- `GetViewEx`: ~0.41
- `GetViewEx2`:   250f: 2.155; 1f: 2.037 (1.742..2.750); 3f: 2.044 (1.813..2.734); 5f: 2.005 (1.859..2.724); 10f: 2.043 (1.891..2.660); 50f: 2.015 (1.958..2.567); 100f: 1.988 (1.973..2.464)

Ну, ничего нового.
Под Wine работает всё.
Даже если не должно работать.
Даже если рассказывает что не работает.
Зато какой ценой...

**Comment by softexe** [comment]
Мощно!

> И ещё, тут явно не хватало синхронизации
> К примеру `Window.Maximize` в начале программы срабатывало после того как большую часть объектов уже поместило в форму меньшего размера
> Возможно это так же является причиной артефактов

Артефакты заметны, особенно в примере с броуновским движением объектов, там текстовый блок стабильно пачкает, причём  на всех реализация, не смотрел подробно.

Я так понял, на Линуксе FPS выше, чем на Вин10 получились?

и по общим результатам - вариант с **Bitmap.Clone** хоть и не получился самым самым быстрым во всех случаях,  но зато самый стабильно работающий и понятный, без алхимии копирования кусков памяти?

**Comment by SunSerega** [comment]
Да, всё так.
