### ISSUE TITLE
Компилятор не видит членов предварительно объявленного класса

### ISSUE THREAD

**Issue by samuraiGH** [pascalabcnet/pascalabcnet#2802]
```pas
type
  c1 = class;
  
  c2 = class
    procedure pr1;
    begin
      // ---> f1 не объявлен в типе c1 <---
      c1.f1.Print;
    end;
  end;
  
  c1 = class
    static f1: integer;
  end;

begin end.
```

**Comment by SunSerega** [comment]
И не должен. Если классы ссылаются друг на друга телах своих объявлений - они оба должны быть предописаны.
Или, лучше, используйте `partial` классы - их недавно исправили в анализаторе кода, теперь предописания классов однозначно устарели.

**Comment by samuraiGH** [comment]
> @SunSerega  _Если классы ссылаются друг на друга телах своих объявлений - они оба должны быть предописаны_

почему? это же работает
```pas
type
  c1 = class;
  
  c2 = class
    f1: c1;
  end;
  
  c1 = class
    f1: c2;
  end;

begin end.
```

да и код в шапке второе предописание не оживит

**Comment by SunSerega** [comment]
Я имел в виду на содержимое друг друга. Если на заголовок - да, достаточно чтобы был только один заголовок.

**Comment by SunSerega** [comment]
Плохо только что сейчас так не работает:
```
type
  c1 = partial class end;
  
  c2 = partial class
    procedure pr1;
  end;
  
  c1 = partial class
    static f1: integer;
  end;
  
  c2 = partial class
    procedure pr1;
    begin
      c1.f1.Print;
    end;
  end;
  
begin end.
```
Если у модуля есть раздел `implementation` - приходится даже такие простенькие и маленькие подпрограммы выносить в другую половину модуля, раделяя таким образом логику на неполные детали.

**Comment by samuraiGH** [comment]
> @SunSerega Я имел в виду на содержимое друг друга.

с двумя предописаниями это тоже не работает 
```pas
type
  c1 = class;
  с2 = class;
  
  c2 = class
    procedure pr1;
    begin
      c1.f1.Print;
    end;
  end;
  
  c1 = class
    static f1: integer;
  end;

begin end.
```

**Comment by ibond84** [comment]
Это не должно компилироваться. Паскаль не C#.

**Comment by samuraiGH** [comment]
> @ibond84 Это не должно компилироваться

По каким идеологическим принципам? Паскаль против всего циклического?

**Comment by ibond84** [comment]
В паскале как и в C++ имена используются после их объявления
