### ISSUE TITLE
Как пересоздать Localization/DefaultLang.resources

### ISSUE THREAD

**Issue by mikhailnov** [pascalabcnet/pascalabcnet#2810]
Пытаюсь собрать pascalabcnet на ROSA 12 (rosa2021.1), mono 6.12.0-90.4, получаю ошибку:

Copying file from '/home/mikhailnov/rpmbuild/BUILD/pascalabcnet-8ac4966a520093b0cbfd9d4a20d03f2181a20b53/Localization/DefaultLang.resources' to '/home/mikhailnov/rpmbuild/BUILD/pascalabcnet-8ac4966a520093b0cbfd9d4a20d03f2181a20b53/Localization/obj/release/PascalABCCompiler.DefaultLang.resources'

CSC: error CS1566: Error reading resource file `obj/release/PascalABCCompiler.DefaultLang.resources

Это бинарный файл, лежащий прямо в git. Очевидно, что стоит попробовать пересоздать его, наверное, это делается как-то с помощью resgen в mono, но непонятно, как именно. Не могли бы вы задокументировать или просто подсказать, как его пересоздать?

**Comment by mikhailnov** [comment]
Видимо, он делается с помощью Utils/DefaultLanguageResMaker/

**Comment by ibond84** [comment]
Исправлено. LanguageResMaker теперь работает под Linux

**Comment by ibond84** [comment]
Надо бы еще добавить в _RebuildReleaseAndRunTests.sh

**Comment by mikhailnov** [comment]
Спасибо!
