### ISSUE TITLE
Невозможно собрать из исходников на ROSA/Fedora/Ubuntu/Debian etc.

### ISSUE THREAD

**Issue by mikhailnov** [pascalabcnet/pascalabcnet#2811]
Этот пост больше для информации. Сейчас pascalabcnet невозможно собрать из исходников на ROSA, Fedora, Ubuntu и пр. дистрибутивах, которые собирают mono из исходников.
Дело в том, что компилятор csc из них пока что не собирается, по крайней мере никто не обеспечил ее, и вряд ли это сделать просто, если вообще возможно, см. https://bugzilla.redhat.com/show_bug.cgi?id=1718439
mono патчится, чтобы запускал mcs вместо csc.
А собираемый в mono из исходников компилятор mcs не может собрать pascalbcnet, спотыкается на неподдерживаемом им синтаксисе.
В ALT Linux csc просто подкладывают скачанными с сайта mono бинарниками в пакет с mono.
Судя по https://github.com/dotnet/roslyn/blob/main/docs/infrastructure/cross-platform.md , теоретически можно попробовать собрать csc, но там nuget — подкачка из интернета, могут возникнуть разной степени серьезности проблемы при сборке без интернета. Также еще потребуется MSBuild, https://github.com/dotnet/msbuild/blob/main/documentation/wiki/Building-Testing-and-Debugging-on-.Net-Core-MSBuild.md , его тоже не просто будет нормально собрать.
Не знаю, подойдет ли такой csc для mono.

Если будут какие-то подвижки, отпишусь здесь.

**Comment by miks1965** [comment]
ОК. Правильно ли я понимаю, что это не PascalABC.NET нельзя собрать из исходников, это компилятор csc, который компилирует PascalABC.NET, нельзя собрать из исходников?

**Comment by mikhailnov** [comment]
> ОК. Правильно ли я понимаю, что это не PascalABC.NET нельзя собрать из исходников, это компилятор csc, который компилирует PascalABC.NET, нельзя собрать из исходников?

Да. Чисто теоретически собрать crc можно, но это будет очень большая работа.

**Comment by miks1965** [comment]
Ну, всё же тут PascalABC.NET ни при чем - надо решать другую задачу.

И - я не верю в реальность того, что компилятор csc как-то там дискредитирован, поэтому будет собирать дискредитированный код, который будет генерировать дискредитированный код. Я как разработчик компиляторов считаю эту ситуацию вымышленной.

**Comment by mikhailnov** [comment]
> Кстати, странно - под Alt Linux я просто устанавливал пакет Monodevelop и компилировал им PascalABC.NET - я был уверен, что Monodevelop использует компилятор mono. Поэтому то, что Вы пишете, выглядит странно

Они берут csc блобами и подкладывают в пакет mono

https://git.altlinux.org/gears/m/mono.git?p=mono.git;a=blob;f=.gear/update-monolite.sh;h=3d457670fa955ebb2aa556c960b303e0923da3e2;hb=87c70230bd8d3c44ec0154c46a3224cb92454577

https://git.altlinux.org/gears/m/mono.git?p=mono.git;a=blob;f=.gear/mono.spec;h=a0d4dfa1d080b175b29f78029aa4b8618879842c;hb=87c70230bd8d3c44ec0154c46a3224cb92454577#l536

Внутри monolite.tar.gz https://git.altlinux.org/gears/m/mono.git?p=mono.git;a=blob_plain;f=.gear/monolite.tar.gz;hb=87c70230bd8d3c44ec0154c46a3224cb92454577 в т.ч. mcs.exe:

![image](https://user-images.githubusercontent.com/15802528/223549514-8a740f18-114c-4e6b-b503-ac08401604bb.png)

**Comment by mikhailnov** [comment]
Как смотрите на то, чтоб наладить выпуск официальных RPM-пакетов с pascalabc.net? spec могу написать и прислать, пакет должен получиться универсальным для ROSA, ALT, Fedora, CentOS и т.д. Собирать rpm можно будет на любой системе, где есть RPM: ROSA, ALT, Fedora, CentOS, Debian, Ubuntu, FreeBSD и т.д.

**Comment by miks1965** [comment]
Отлично смотрю! 

Как раз скоро версию 3.8.4 будем выпускать

**Comment by mikhailnov** [comment]
Откуда будем брать артефакты для запаковки в RPM? Есть 3 варианта:

1) бинарник(-и) из некой папки
2) zip-архив, который вы сейчас собираете в качестве релизного
3) собирать с нуля при сборке RPM

Как будет удобнее?

**Comment by miks1965** [comment]
Мне кажется, надо как-то синхронизироваться с Alt Linux. Они для репозитория сделали такой rpm-пакет. Они его собирают из исходников.

Я кстати не знаю, можно ли узнать, что там у rpm внутри. Мы там договаривались о структуре каталогов в частности.

**Comment by miks1965** [comment]
Меня смущает эта папка: pascalabcnet-3.8.3.3226
Зачем она привязана к релизу? Мы релизы выпускаем часто - зачем плодить папки?

**Comment by mikhailnov** [comment]
Это стандартная практика - класть документацию по пакету в папку /usr/share/doc/имя-версия. Ничего страшного в этом нет, на линуксе пакетный менеджер знает о каждой папке и файле внутри пакета, при установке другой версию папка от старой будет просто удалена.

Меня в это структуре смущает вообще сама папка /usr/lib и то, что в ней лежат небинарные файлы. Для официального пакета я бы сделал `/opt/pascalabc`. Но это некритично, просто некрасиво.

**Comment by mikhailnov** [comment]
Официальному пакету от разработчиков и пакету из репозитория дистрибутива нет необходимости иметь одинаковую структуру папок. Если они будут называться одинаково - pascalabcnet - то установка одного приведет к удалению другого, и проблем не возникнет. Разве что с точки зрения документации это нехорошо, если в ней нужно указать какие-то пути.

**Comment by miks1965** [comment]
Давайте. Там есть несколько фатальных мест в ядре компилятора - если не соберётся, то - всё. Но если это не они - исправим.

**Comment by miks1965** [comment]
> Давайте сделаю LiveCD - ISO образ для запуска и/или установки - в который будет встроено все, что нужно для сборки собранным из исходников mono (т.е. из репозиториев дистрибутива), и напишу, как запускать сборку. 

Ну, я с нетерпением жду - хотелось бы выяснить, какие ошибки в msc

**Comment by mikhailnov** [comment]
Образ ОС: https://abf.io/platforms/rosa2021.1/products/340/product_build_lists/45977 , скачивать файл [ROSA_2021.1_PLASMA5_x86_64_45977.iso](https://file-store.rosalinux.ru/api/v1/file_stores/1d362aa2fbf7707c7361fd1c9ce76c8d6291221c)

Видео инструкция со звуком: https://file-store.rosalinux.ru/download/62395413c70e03d278d0a41c0d829d6f1dc906cc (simplescreenrecorder-2023-03-15_02.01.48.mkv)

Патч: https://clbin.com/IYJyS

**Comment by SunSerega** [comment]
Сразу при запуске батника:

> xbuild tool is deprecated and will be removed in future updates, use msbuild instead

То есть я правильно понял, вы используете устаревший инструмент, потому что это проще?

В этом случае заменять конструкции компилятора на более древние, потому что устаревший инструмент их не понимает - не очень хорошее решение.

Можно ли всё же заставить `msbuild` работать?

**Comment by mikhailnov** [comment]
Как уже написал выше, теоретически собрать msbuild + csc из исходников без интернета можно, на практике пока не удалось ни в одном дистрибутиве.

**Comment by softexe** [comment]
> Можно ли всё же заставить `msbuild` работать?

пишут, что через установку .Net Core

**Comment by ibond84** [comment]
Обновитесь и выполните следующие команды

```
sudo apt install gnupg ca-certificates
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
echo "deb https://download.mono-project.com/repo/ubuntu stable-focal main" | sudo tee /etc/apt/sources.list.d/mono-official-stable.list
sudo apt update
sudo apt-get install mono-devel
sudo apt-get install mono-complete
sudo apt-get install mono-roslyn
sudo apt-get install msbuild
```

Затем вызовите ./_RebuildRelease.sh

msbuild работает. xbuild устарел и не поддерживает современные конструкции C#

**Comment by ibond84** [comment]
DefaultLang.resources создается автоматически.

**Comment by ibond84** [comment]
Протестировано в Ubuntu 22.04

**Comment by mikhailnov** [comment]
> Обновитесь и выполните следующие команды
> 
> ```
> sudo apt install gnupg ca-certificates
> sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
> echo "deb https://download.mono-project.com/repo/ubuntu stable-focal main" | sudo tee /etc/apt/sources.list.d/mono-official-stable.list
> sudo apt update
> sudo apt-get install mono-devel
> sudo apt-get install mono-complete
> sudo apt-get install mono-roslyn
> sudo apt-get install msbuild
> ```
> 
> Затем вызовите ./_RebuildRelease.sh
> 
> msbuild работает. xbuild устарел и не поддерживает современные конструкции C#

Это-то понятно, я писал не про просто сборку под Линуксом, а про опакечивание в репозиторий.

**Comment by miks1965** [comment]
Повторил всё что в видео.
Патча нет по указанному пути.

Те проблемы, которые отображаются на последнем экране, тоже переделываются наверное. Не знаю, возникнут ли фатальные.

Патч пришлёте?

**Comment by mikhailnov** [comment]
Ссылка на патч выше рабочая, проверил: https://clbin.com/IYJyS
Также этот же файл на всякий случай во вложении:
[pascal.txt](https://github.com/pascalabcnet/pascalabcnet/files/11012057/pascal.txt)

**Comment by ibond84** [comment]
> его тоже не просто будет нормально собрать.

Вы пробовали его собрать?

**Comment by miks1965** [comment]
> Ссылка на патч выше рабочая, проверил: https://clbin.com/IYJyS
> В образ он не встроен, нужно скачать.
> Также этот же файл на всякий случай во вложении:
> [pascal.txt](https://github.com/pascalabcnet/pascalabcnet/files/11012057/pascal.txt)

Ну да, патч применил, следующую ошибку исправил. Дальше какие-то ошибки о том, что какие то типы неизвестны, хотя они известны. Мы не разрабатываем без IDE. Нет возможности установить MonoDevelop и в нем разрабатывать? А то всё время пытаться угадывать - слишком сложный проект

**Comment by mikhailnov** [comment]
> > его тоже не просто будет нормально собрать.
> 
> Вы пробовали его собрать?
Немного пробовали, пока не собрали. msbuild, скорее всего, относительно легко соберется, а вот со сборкой csc будет намного сложнее. xbuild ничем не мешает, если бы был csc, то xbuild бы справился вместо msbuild, в Альте справляется (где csc подложен блобом).

> Ну да, патч применил, следующую ошибку исправил. Дальше какие-то ошибки о том, что какие то типы неизвестны, хотя они известны. Мы не разрабатываем без IDE. Нет возможности установить MonoDevelop и в нем разрабатывать? А то всё время пытаться угадывать - слишком сложный проект

На счет MonoDevelop не знаю, если его можно будет настроить использовать mcs вместо csc, то, наверное, да. Сейчас попробую и отпишусь.

**Comment by mikhailnov** [comment]
Monodevelop заброшенный проект, смог запустить на Росе их версию для CentOS 7, она тащит свой mono вместо mono из репозитория, в нем есть и csc, и mcs, но выбора между ними в настройках Monodevelop не нашел. Как ею пользоваться, тоже не понял, попытался запустить сборку, получил ошибку без лога:
![2023-03-20_00-30](https://user-images.githubusercontent.com/15802528/226210954-462c2ee5-fa6d-47b7-b67d-6a3de379775d.png)

Установка monodevelop для CentOS 7 на Росу:

Удаляем системный mono:
`sudo dnf remove 'mono*'`

Подключаем репозиторий для CentOS 7:
`sudo wget https://download.mono-project.com/repo/centos7-vs.repo -O /etc/yum.repos.d/mono-centos7-vs.repo`

Ставим пакеты:

`sudo dnf --excludepkgs lib64gdiplus0 install wget http://mirror.centos.org/centos/7/os/x86_64/Packages/openssl-libs-1.0.2k-19.el7.x86_64.rpm http://mirror.centos.org/centos/7/os/x86_64/Packages/libpng-1.5.13-8.el7.x86_64.rpm monodevelop gsettings-desktop-schemas`

**Comment by miks1965** [comment]
Делаю второй раз. Вот последний результат. Алгоритм не работает
![изображение](https://github.com/pascalabcnet/pascalabcnet/assets/10325391/fbd16158-6f7d-47d9-a6e0-411bc7449ad6)

**Comment by miks1965** [comment]
Я поступил по-другому. В Ubuntu я запустил _RebuildRelease.sh и всё собралось.

Я не понимаю, зачем это делать и использовать устаревший запрещенный xbuild, но я изменил в скрипте msbuild на xbuild - и всё снова собралось.

Я так понимаю, что issue можно закрывать.

![изображение](https://github.com/pascalabcnet/pascalabcnet/assets/10325391/7ed60054-b5b2-43f0-92a6-dc7779f14435)

**Comment by mikhailnov** [comment]
Оно собралось через xbuild, потому что собиралось через csc, а не через mcs. Вся эта issue о невозможности сборки через mcs, а xbuild или msbuild, не имеет значения.
Вы поставили mono с официального сайта mono. Если поставить его из родных репозиториев Ubuntu, то будут описанные в этой issue проблемы, потому что там тоже не смогли собрать csc из исходников без Интернета.

Инструкцию по monodevelop проверю.

**Comment by mikhailnov** [comment]
Надо как-то заставить monodevelop собирать через системный mono, а он в качестве зависимости тащит несистемный и на системном не работает. Либо переключить тащимый им mono на mcs. В самом monodevelop в прошлый раз таких настроек не нашел. Есть пара мыслей, может, получится.

Без этого monodevelop не сможет помочь в отладке кода под mcs (не настаиваю, что этим нужно заниматься...).

**Comment by mikhailnov** [comment]
Но даже если мы сможем отпинать разлагающийся труп monodevelop, чтобы собрать код старым mcs, непонятно, что дальше делать, как все разработчики будуь дальше писать код...

**Comment by SunSerega** [comment]
> даже если мы сможем отпинать разлагающийся труп monodevelop

Уже пытаются. Я вот это видел: https://github.com/dotdevelop/dotdevelop
Правда опять почти 3 месяца без новостей...

**Comment by miks1965** [comment]
> Но даже если мы сможем отпинать разлагающийся труп monodevelop, чтобы собрать код старым mcs, непонятно, что дальше делать, как все разработчики будуь дальше писать код...

Полностью согласен.

**Comment by miks1965** [comment]
Я закрываю этот Issue? Проблема решена в https://github.com/pascalabcnet/pascalabcnet/issues/2871?

**Comment by miks1965** [comment]
Закрываю, поскольку проблема решена. Всё компилируется и собирается.
