### ISSUE TITLE
Не даёт объявить литерал строки из одной экранированной скобки

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#2813]
```
//Ошибка: Встречена неправильная форматная строка
## var s := $'{{';
```
Сейчас ближайший код дающий то же самое:
```
## var s := '{'+'';
```
Но по моему стоит разрешить и так писать:
```
## var s := $'{';
```
Если нет закрывающейся скобки, даже если открытая не экранирована, нечего пытаться её пропарсить как вставленное значение.

**Comment by miks1965** [comment]
Надо заменять {{ на { и }} на } 
Я думаю - это решение

**Comment by ibond84** [comment]
>Но по моему стоит разрешить и так писать:

Нет

**Comment by ibond84** [comment]
https://github.com/pascalabcnet/pascalabcnet/actions/runs/4397097344
