### ISSUE TITLE
Компилятор выпускает сборки без TargetFrameworkAttribute

### ISSUE THREAD

**Issue by samuraiGH** [pascalabcnet/pascalabcnet#2814]
Как я понимаю, это сделано что бы не привязываться к конкретной версии, а просто использовать ту, которая есть у пользователя. 

Однако это порождает проблемы, когда сторонние либы проверяют для какой версии собран exe, а вместо результата получают `nil` из `System.AppDomain.CurrentDomain.SetupInformation.TargetFrameworkName`

К сожалению, не все либы корректно обрабатывают такой ответ. В том числе и WindowsForms. Из-за этой особенности становится бесполезна, например, вся секция [System.Windows.Forms.ApplicationConfigurationSection](https://learn.microsoft.com/ru-ru/dotnet/framework/configure-apps/file-schema/winforms/). 
<details>
<summary>Спойлер: Может быть проблема в другом?</summary>
Нет, проблема именно в этом. Я  пропатчил компилятор, что бы он добавлял TargetFrameworkAttribute(4.8) и проблема решилась
</details>

Я думаю, необходима директива компилятора, которой можно будет явно задавать TargetFramework

**Comment by miks1965** [comment]
Приведите пример, как Вы хотите чтобы это выглядело

**Comment by samuraiGH** [comment]
> @miks1965 как Вы хотите чтобы это выглядело

директива? думаю, можно сделать в стиле csproj
`{$TargetFramework net48}`
или прямо так, как нужно передавать в конструктор 
`{$TargetFramework '.NETFramework,Version=v4.7.1'}`
менее красиво в коде, зато парсить не придётся 

В `ILCoverter.ConvertFromTree()` вызывать что-то вроде
```cs
cab = new CustomAttributeBuilder(typeof(TargetFrameworkAttribute).GetConstructor(new Type[] { typeof(string) }), new object[] { options.TargetFramework });
ab.SetCustomAttribute(cab);
```
сейчас подобное делается только для `PABCRtl`
![image](https://user-images.githubusercontent.com/87191377/224488432-42e52acc-e7f0-477c-9147-1b7ab3950770.png)

**Comment by miks1965** [comment]
Ну, сделайте pull request - мы потестируем

**Comment by samuraiGH** [comment]
> @miks1965 сделайте pull request

Я пытался разобраться, но у Вас директивы глубоко закопаны. Не смог толком понять, просто идя по колстеку
>И что тогда?

Не запустится, на сколько я знаю

**Comment by samuraiGH** [comment]
Хотя оказалось, что не так уж и сложно. Я думал надо в парсер лезть. Попробую

**Comment by samuraiGH** [comment]
А компилятор вообще не делает никаких привязок к версии фреймворка? Или если CLR ниже 4, то всё-таки не запустится?
