### ISSUE TITLE
Контекст ошибок `InvalidPathError` не выводится в IDE

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#2820]
Скопировал [отсюда](https://github.com/pascalabcnet/pascalabcnet/pull/2819#issue-1620006044), потому что вы там проигнирили.

---

В самом компиляторе, при бросании этого исключения, контекст ошибки имеется. Проверил и в дебагере, и в релиз версии вставкой MessageBox.Show(loc.ToString());

Но при этом и консольный компилятор, и IDE - информацию об имени файла, в котором эта ошибка произошла, не получают. То есть даже не Undefined Filename, а вообще пустая строка.

И +, если запускать IDE из под студии, то проблемы на этом заканчиваются.
Но если собрать и установить билд, запущенная отдельно IDE не показывает даже номер строчки.

Вот как это выглядит:
[youtu.be/dDd_utCwOTM](https://youtu.be/dDd_utCwOTM)

Обратите внимание, это воспроизводится и в последнем официальном билде, если с сайта скачать и поставить, то есть дело не в моих изменениях (из #2819).
Но в том пуле тоже воспроизводится, потому что я использовал тот же класс - не представляю что с ним делать.

P.S. Вот то же самое в официальном билде (до мержа #2819):
[youtu.be/0i6dFhqhdNA](https://youtu.be/0i6dFhqhdNA)

**Comment by ibond84** [comment]
>Скопировал https://github.com/pascalabcnet/pascalabcnet/pull/2819#issue-1620006044, потому что вы там проигнирили.

Не ленитесь писать отдельные issue для ошибок. И тогда не будет ничего игнорироваться

**Comment by SunSerega** [comment]
Ну так это связанная тема. Как вообще можно мержить пулл, не прочитав его описание...

**Comment by ibond84** [comment]
Ну в пулле можно написать хоть 10 ошибок. И что мне с ними делать потом? Принимать, не принимать? Пишите issue и все
