### ISSUE TITLE
модули для ненаучной работы предполагаются?

### ISSUE THREAD

**Issue by Apollon-Theos** [pascalabcnet/pascalabcnet#2825]
Например:
LDAP
SSH
HTTP(S)/FTP(S)
WinRM

а работа с базами данных?
MS SQL
PostgeSQL
MySQL (MariaDB)
MS Access
MS Excel
LibreOffice Calc
LibreOffice Base

или всё же придётся оставаться на php?

**Comment by samuraiGH** [comment]
А зачем, если есть nuget?

**Comment by Apollon-Theos** [comment]
а nuget - это уже если не хватит возможностей стандартных модулей из поставки.

**Comment by Apollon-Theos** [comment]
а вдруг TOT удасться скомпилировать под PascalABC.Net ? TUI иногда полезнее GUI :)
