### ISSUE TITLE
`where T1: T2` не добавляет информацию о T2, если он тоже шаблонный параметр

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#2829]
```
type
  c1<T1,T2> = class
    // Если объявить сначала "where T1" - тоже должно работать
    where T2: IComparable<T1>;
    where T1: T2;
    
    procedure p1(o: T1);
    begin
      //Ошибка: Неизвестное имя 'CompareTo'
      o.CompareTo(o).Print;
    end;
    
  end;
  
begin
  var a := new c1<string,string>;
  a.p1('abc');
end.
```
На самом деле, некоторую информацию добавляет... `T1` насильно делает ссылочным, как будто прописано `T2: class` - хотя в этом коде `T2` может быть записью.

**Comment by SunSerega** [comment]
Тут то же самое:
```
type
  c1<T1> = class
  where T1: IComparable<T1>;
    
    procedure p1<T2>(o: T2);
      where T2: T1;
    begin
      {T1}(o).CompareTo({T1}(o)).Print;
    end;
    
  end;
  
begin
  var a := new c1<string>;
  a.p1('abc');
end.
```
`T2` тоже насильно делает ссылочным, но при этом не делает реализацией `IComparable<T1>`.

**Comment by ibond84** [comment]
> Если объявить сначала "where T1" - тоже должно работать
??

**Comment by SunSerega** [comment]
Что не понятно то? Я имею в виду:
```
  c1<T1,T2> = class
    // Если объявить сначала "where T1" - тоже должно работать
    where T1: T2;
    where T2: IComparable<T1>;
```
`T1` тут так же реализует `IComparable<T1>`. Порядок `where` нигде в других местах не меняет поведение, поэтому и тут не должен.

**Comment by SunSerega** [comment]
Ну или если не хотите заморачиваться, надо хотя бы ошибку, помогающую в правильном порядке описывать `where`.
Что то типа: "where для типа T2, являющегося предком типа T1, должны быть раньше where для типа T1"
Но такое ограничение сделает код менее читабельным в некоторых случаях, когда для логики кода правильнее будет всё же первым объявить `where T1`.

**Comment by ibond84** [comment]
Почему вдруг должно работать? Порядок важен

**Comment by SunSerega** [comment]
Приведите пример, где порядок объявлений `where` что то меняет.
