### ISSUE TITLE
Редактор позволяет прятать процедуры

### ISSUE THREAD

**Issue by Nikita-bunikido** [pascalabcnet/pascalabcnet#2835]
## Проблема
Если на первой строке поставить достаточно много пробелов то всё что написано после них будет физически невозможно увидеть через встроенный редактор IDE.

На скриншоте ниже, на первой строке спрятана процедура **writeln()**, печатающая строку _'123'_. Но горизонтальный скролбар не даёт пользователю просмотреть полное содержимое первой строки. Программа выведет _'123'_, а не _'Исходная строка'_, как могло показаться

![ex1](https://user-images.githubusercontent.com/85186722/230612169-40238ae1-8bef-43ed-9dfa-2da8a0ec002c.png)

Но если открыть файл в другом редакторе, то можно отчётливо увидеть присутствие процедуры с изменённой английской буквой '**е**' на русскую '**е**'

Код буквы (UTF-8) | Буква
:-:|:-:
0x65 | e
0xD0, 0xB5 | е

![ex2](https://user-images.githubusercontent.com/85186722/230612863-bdefe622-e653-4ee2-96a6-0feda8b0080b.png)

Вызов поддельной версии и осуществляется в теле программы.

## Версия

Пример тестировался на версии _PascalABC.NET 3.8.3_.

## Файл

Файл примера выложил [сюда](https://disk.yandex.ru/d/mHco3-jJDOzUEQ).

**Comment by SunSerega** [comment]
Да, странно себя ведёт. Даже при переходе к спрятанному тексту стрелочками скроллбар не расширяется. Но если попробовать там что-то редактировать - всё исправляется.

> Файл примера выложил [сюда](https://disk.yandex.ru/d/mHco3-jJDOzUEQ).

Лучше прямо в issue выкладывать...

**Comment by SunSerega** [comment]
P.S. Вы в issue компилятора написали. Вот для IDE:
https://github.com/pascalabcnet/pascalabcnetide/issues?q=

**Comment by Nikita-bunikido** [comment]
> P.S. Вы в issue компилятора написали. Вот для IDE: https://github.com/pascalabcnet/pascalabcnetide/issues?q=

Хорошо, дублирую в IDE
