### ISSUE TITLE
Генерация кода после "end."

### ISSUE THREAD

**Issue by Apollon-Theos** [pascalabcnet/pascalabcnet#2837]
Если докрутить исходник до конца и поставить курсор после end.
то двойной клик на пункте меню генерирует и всквдяет код после "конца программы" :
![image](https://user-images.githubusercontent.com/46534073/230772346-9de0fd7b-b923-4b04-bacb-75b3207bdeb2.png)

даже если курсор стоит перед end. , на предыдущей строке, то новый код для пункта меню вставляется после  end. и попытки сгенерировать код для следуюзего пунтка меню выводят ошибку:
![image](https://user-images.githubusercontent.com/46534073/230772447-b883bb78-0c73-4952-b1e6-83c779c7fdfa.png)

ручное перставление "end." исправляют ситуацию до последующей попвтки генерации кода для пунтка меню и всё повторяется.

![image](https://user-images.githubusercontent.com/46534073/230772506-d0b459ba-3b7c-4711-a170-d33ed8b31b5c.png)

**Comment by SunSerega** [comment]
Это фича IDE: https://github.com/pascalabcnet/pascalabcnetide/issues?q=

**Comment by Apollon-Theos** [comment]
а перенести туда можно, или надо пересоздавать?

**Comment by SunSerega** [comment]
@ibond84 перенесите пожалуйста...
Вообще, если делать шаблоны issue в настройках репозиторий - я видел как люди делают там кнопки, которые вместо создания issue перенаправляют на другой сайт.
Можно перенаправлять на issue IDE, чтобы каждый новый человек об это не спотыкался.

**Comment by Apollon-Theos** [comment]
https://github.com/pascalabcnet/pascalabcnetide/issues/267

**Comment by Apollon-Theos** [comment]
перенес
