### ISSUE TITLE
Form.Close отсутствует

### ISSUE THREAD

**Issue by Apollon-Theos** [pascalabcnet/pascalabcnet#2838]
https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.form.close?view=netframework-4.8

а форму приходится закрывать, как посоветовали в 
https://stackoverflow.com/questions/9646684/cant-use-system-windows-forms

потому что у формы нет метода Close:
![image](https://user-images.githubusercontent.com/46534073/230773042-c6bdb4fa-bcd8-4b29-abf0-e0f92542adc1.png)

хотя в референсной документации он описан.

**Comment by Apollon-Theos** [comment]
переносимость кода ой как страдает ....

**Comment by SunSerega** [comment]
Что если попробовать вызвать .Close, хоть его и не показывает?
И что показывает анализатор кода, когда вы наводите мышку?

**Comment by SunSerega** [comment]
А, собственно из скриншота видно. `Form1` это тип формы. Вы можете создать несколько форм-экземпляров этого типа.
Какой из них должен закрыться, если вы к типу обращаетесь? Параметр `sender` у вас не для красоты...

**Comment by SunSerega** [comment]
> а форму приходится закрывать, как посоветовали в

Вы точно правильную ссылку кинули? Я не вижу там ничего про закрытие формы...

**Comment by Apollon-Theos** [comment]
> Что если попробовать вызвать .Close, хоть его и не показывает? И что показывает анализатор кода, когда вы наводите мышку?

Как ни странно, но вроде проходит компиляцию. И даже отрабатывет, вроде как положено, форма закрывается.
Скрытый метод?

**Comment by Apollon-Theos** [comment]
> > а форму приходится закрывать, как посоветовали в
> 
> Вы точно правильную ссылку кинули? Я не вижу там ничего про закрытие формы...

извиняюсь, перепутал окна, вот правильная:
https://stackoverflow.com/questions/4752355/generic-way-to-exit-a-net-application

**Comment by Apollon-Theos** [comment]
в принципе, через System.Windows.Forms.Application.Exit(); отрабатывает, не привычно просто не видеть методы, которые оказывается есть.

**Comment by Apollon-Theos** [comment]
> А, собственно из скриншота видно. `Form1` это тип формы. Вы можете создать несколько форм-экземпляров этого типа. Какой из них должен закрыться, если вы к типу обращаетесь? Параметр `sender` у вас не для красоты...

с чего бы это "тип формы", когда это уже экзкмпляр класса Forms
![image](https://user-images.githubusercontent.com/46534073/230776725-211de64f-454f-48bc-8ea6-f9ca651c47b1.png)

**Comment by SunSerega** [comment]
> Как ни странно, но вроде проходит компиляцию. И даже отрабатывет, вроде как положено, форма закрывается.

И правда очень странно. У меня вот в более простом примере не компилируется:
```
{$reference System.Windows.Forms.dll}
{$apptype windows}

uses System.Windows.Forms;

begin
  var MainForm := new Form;
  
  //Ошибка: Mетод Close не является статическим для типа System.Windows.Forms.Form
  Form.Close;
  
  Application.Run(MainForm);
end.
```

Скиньте архив с проектом. Не обязательно весь ваш проект, главное минимум где `.Close` на имени типа компилируется.

**Comment by SunSerega** [comment]
> в принципе, через System.Windows.Forms.Application.Exit(); отрабатывает

Ну да, но это не совсем то же самое. И в любом случае надо разобраться.
К примеру `MainForm.Close` в моём коде видно, как положено - он никакой не скрытый.

**Comment by Apollon-Theos** [comment]
![image](https://user-images.githubusercontent.com/46534073/230781124-b5d740f4-dc8c-421a-b274-5330096d65fc.png)
сама процедура, где использую Clоse:
![image](https://user-images.githubusercontent.com/46534073/230781175-bfddd7be-a21b-45e6-9fb6-4e1ec009ae09.png)

**Comment by Apollon-Theos** [comment]
компилируется и отрабатывет

**Comment by Apollon-Theos** [comment]
сначала даже вписал в методы Destructor Close; с выполнением System.Windows.Forms.Application.Exit(); , но потом, после Ваших слов, удалил.

**Comment by samuraiGH** [comment]
> @Apollon-Theos сама процедура, где использую Clоse:

Тут Вы используете неявное `self.Close` а не `Form1.Close` как хотели выше

**Comment by SunSerega** [comment]
> компилируется и отрабатывет

Ну так это же не то же самое что у вас не работало в начале - не надо всё в кучу...
И это как раз долго показываться в Ctrl+Space. И в `self.Close` - потому что это то же самое, но более явно: Вы обращаетесь к `self` (текущему объекту, чей метод был вызван), а не к типу (`Form1`).

Кроме того, в этот раз работает, но так делать очень не красиво:
Я попросил код (при чём архив со всеми файлами) - чтобы я мог у себя открыть и попробовать получить такое же поведение. А по вашим скриншотам это гадание. Может вы ещё что то по-другому сделали и не сказали.

**Comment by SunSerega** [comment]
> сначала даже вписал в методы Destructor Close

А так работает вообще? Он же `destroy` должен называться. Так же как конструктор должен быть `Create` (но его можно не указывать).
И дейструкторы вообще существуют только для совместимости...

**Comment by SunSerega** [comment]
Ну, проблемы компилятора или IDE в итоге тут небыло - не забудьте закрыть issue.
И на будущее, если есть вопросы, где вы не знаете в чём проблема, лучше пишите:
- В телеграмме: https://t.me/PABCofficial/8279
- На форуме: https://forum.mmcs.sfedu.ru/c/pascalabcnet/10

**Comment by Apollon-Theos** [comment]
> > @Apollon-Theos сама процедура, где использую Clоse:
> 
> Тут Вы используете неявное `self.Close` а не `Form1.Close` как хотели выше

А что делать? Для системных и .Net "модулей", нет даже интерфейсных .dcu вот и приходится искать на ощупь.
Комплект докумнтации в поставке только про часть библиотек. Мог и напутать.

**Comment by SunSerega** [comment]
> нет даже интерфейсных .dcu

При чём тут кэш компилятора дельфи? Это не документация, даже если вы можете достать из них сигнатуры.

Документацию вы нашли и кинули ссылку в своём первом сообщении.
.Net это продукт майкрасофта, поэтому документация и должна быть на их сайте.
Копировать её в дистрибутив данного языка было бы не практично и неправильно.

---

Но тут вы допустили ошибку потому что запутались в базовых принципах ООП.
Документация вам и не помогла бы, потому что она даёт сухие данные, а вам нужен образ мышления.

```
var i: integer;
```
Вы же понимаете что `integer` тут тип данных, а `i` - переменная этого типа (хранящая экземпляр типа `integer`)?
И разумеется, написать `var x := integer + 5;` вы не можете. Но зато можете `var x := i+5;`.
Но зато вы можете написать `var x := integer.MaxValue;`, потому что это значение не принадлежит ни одному отдельному экземпляру типа `integer`.

Там вот, `integer` это запись, реализованная на C# (там это структура): https://referencesource.microsoft.com/#mscorlib/system/int32.cs,225942ed7b7a3252
`System.Windows.Forms.Form` это так же реализованный тип: https://referencesource.microsoft.com/#System.Windows.Forms/winforms/Managed/System/WinForms/Form.cs,71d66965280a3f7b
Основное отличие - форма является классом, а не записью, поэтому переменные этого типа содержат ссылку на экземпляр, а сам экземпляр находится в куче (heap, управляемая (средой выполнения) часть оперативки).
