### ISSUE TITLE
Атрибут, запрещающий оптимизатору удалять типы и т.п. из конечных бинарников

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#2844]
[Видео демонстрация кривого поведения](https://youtu.be/G6G2NKVv2J8).

Запускаю каждый раз с F9.
Но если при запуске открыт файл модуля - получаю ошибку, которая говорит что для `PVCK_Vector` нет реализации.
Если упомянуть типы-реализации из основной программы - ошибка перестаёт проявляться.

---

### Подробнее

Такая ситуация:
```
  ParValCombo = abstract class(MutiKindXMLItem<ParValCombo, ParValComboKind>)
    
  end;
  
  ParValComboVector = sealed class(ParValCombo)
    
    private sz: integer;
    public constructor(sz: integer) := self.sz := sz;
    private constructor := raise new InvalidOperationException;
    static constructor := DefineLoader(PVCK_Vector,
      br->new ParValComboVector(br.ReadInt32)
    );
    
    public property Size: integer read sz;
    
  end;
  
  // Другие реализации ParValCombo 
```
`ParValCombo` это тип, загружаемый с помощью `System.IO.BinaryReader`
В заголовке значений этого типа стоит перечисление `ParValComboKind`:
```
  ParValComboKind = (PVCK_Invalid = 0
    , PVCK_Vector = 1
    // Другие значения перечисления
  );
```
`MutiKindXMLItem` реализован так, что чтобы добавить реализацию `ParValCombo` - достаточно вызвать процедуру `DefineLoader` из статического конструктора реализации.
Нигде в других частях модуля упоминать эту реализацию не надо - таким образом минимизируются возможности допустить ошибку.

---

### Проблема

Проблема в том, что в зависимости от того, как я компилирую программу, оптимизатор может взять и выкинуть `ParValComboVector` из .exe файла.
На сколько я понимаю, это происходит когда `ParValComboVector` загружает из `.pcu` файла (а точнее не загружает, потому что оптимизатор не видит его использование)

В принципе неправильно когда оптимизации компилятора ломают иначе рабочий код.
Но проводить автоматическую диагностику в данном случае не практично - загрузка `ParValComboVector` происходит через рефлекцию:
```
    static constructor; // MutiKindXMLItem<TItemFork, TKind>
    begin
      var item_fork_t := typeof(TItemFork); // ParValCombo - базовый абстрактный тип
      if item_fork_t.IsGenericType then
        raise new InvalidOperationException(item_fork_t.Name);
      foreach var t in item_fork_t.Assembly.GetTypes do
      begin
        if t = item_fork_t then continue;
        if not item_fork_t.IsAssignableFrom(t) then continue;
        if t.IsAbstract then
          raise new InvalidOperationException(t.Name);
        // Вызов статического конструктора ParValComboVector и других реализаций
        System.Runtime.CompilerServices.RuntimeHelpers.RunClassConstructor(t.TypeHandle);
      end;
    end;
```

---

### Решение

Поэтому для таких случаев стоит иметь атрибут, что то типа:
```
  [PCUAlwaysRestore]
  ParValComboVector = sealed class(ParValCombo)
```
Обратите внимание - это касается не только типов. К свойствам, методам и т.п. тоже есть смысл применять этот атрибут - ко всему, что оптимизатор может выкинуть.
В `OpenGL.pas` уже давно похожая ситуация со свойствами. Но там это происходит в кодогенерируемой части, поэтому я решил проблему тупо задублировав кучу кода.
Если добавить такой атрибут - можно ещё будет значительно сократить `OpenGL.pas`.

**Comment by ibond84** [comment]
Сделано
