### ISSUE TITLE
Компилятор не читает x86 dll, собранные им же

### ISSUE THREAD

**Issue by samuraiGH** [pascalabcnet/pascalabcnet#2846]
```pas
{$platformtarget x86}
library l;

begin
  
end.
```

```pas
{$platformtarget x86} 
{$reference 'l.dll'}
begin

end.
```

> p.pas(2) : Ошибка при чтении сборки 'l.dll'

**Comment by samuraiGH** [comment]
@ibond84 в смысле? Другие-то 32битные либы он читает как-то. Так только с теми, что pabc сгенерировал

**Comment by ibond84** [comment]
Какие другие?

**Comment by samuraiGH** [comment]
@ibond84 например эту 
[MediaBase.zip](https://github.com/pascalabcnet/pascalabcnet/files/11339902/MediaBase.zip)

**Comment by ibond84** [comment]
В ILDasm не открывается Protected module -- cannot disassemble

**Comment by SunSerega** [comment]
В dotPeek открывается.
