### ISSUE TITLE
`AllDelimiters` не учитывает апострофы

### ISSUE THREAD

**Issue by Anonymous87549236** [pascalabcnet/pascalabcnet#2848]
Предлагаю заменить в `AllDelimiters` `''` на `#39`, а именно: убрать `''` и добавить в конец `AllDelimiters` `#39`.

**Comment by SunSerega** [comment]
Имелось в виду что апострофы это как раз не знаки препинания, а 1 из символов, которые встречаются внутри слова.
То Есть в случае:
```
## 'don''t'.ToWords(Alldelimiters).Print;
```
Получим 2 слова.

**Comment by miks1965** [comment]
Ну, передавайте вместо Alldelimiters другую константу - какие проблемы
