### ISSUE TITLE
Сделать $'{X} {Y}'

### ISSUE THREAD

**Issue by miks1965** [pascalabcnet/pascalabcnet#285]
Сделать форматную строку $'{X} {Y}'

**Comment by miks1965** [comment]
Конечно, это здорово. Но мало. Имелось в виду, что в {} можно будет писать любые выражения.
```
begin
  var x := 1;
  Print($'{x+1}');
end.
```

**Comment by AlexRnD61** [comment]
А что сейчас можно? Я сколько не пробовал - все бракует.

**Comment by miks1965** [comment]
Только одиночные переменные

**Comment by AlexRnD61** [comment]
Понятно. "Гора родила мышь" (с)

**Comment by ibond84** [comment]
>Имелось в виду, что в {} можно будет писать любые выражения - как в C#.

не нужно. таким макаром можно и REPL запихать

**Comment by ibond84** [comment]
единственное назначение форматных строк это чтобы не мучаться с нумерацией переменных, но не создавать вот такое:

year{(age == 1 ? "" : "s")} old

При отстутсвии подсветки, интеллисенса польза от этого мягко говоря сомнительная.

**Comment by AlexRnD61** [comment]
> таким макаром можно и REPL запихать

А чем это плохо? В Python запихнули же? Но речь, как я понимаю, не о том.
Форматные строки позволяют не заморачиваться с конструкциями ("строка", значение, "строка", значение, ...), заменяя все одной строкой, которая также и форматы содержать может. А реализация - она разве сложна?. Фактически, простенький препроцессор с внутренним преобразованием указанной строки в paramarray для обычного Write.

**Comment by ibond84** [comment]
Реализация как оказывается очень проста. Выражения внутри строк будут. ;)
