### ISSUE TITLE
После загрузки `<TSelf>` из .pcu к условиям `where` добавляет `constructor`

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#2853]
[0.zip](https://github.com/pascalabcnet/pascalabcnet/files/11409543/0.zip)
(запуск 0.bat из архива сразу воспроизводит ошибку)

```
uses u;

type
  t2 = abstract class(t1<t2>) end;
  
begin end.
```
```
unit u;

type
  t1<TSelf> = abstract class
    where TSelf: t1<TSelf>;
  end;
  
end.
```
При компиляции основной программы, после создания `u.pcu`:

> 0.pas(4) : Невозможно инстанцировать, так как тип t2 не должен быть абстрактным

`generics.cs`, строка 194:
```
if (gpe.has_default_ctor)
```
Это условие проходит, то есть после загрузки из .pcu `t1` выглядит как будто его объявили так:
```
  t1<TSelf> = abstract class
    where TSelf: t1<TSelf>, constructor;
  end;
```

**Comment by ibond84** [comment]
generic_instance_type_node не переопределяет свойство IsAbstract и конструктор по умолчанию генерируется в TSelf
