### ISSUE TITLE
What about something like h2pas for PascalABC.NET?

### ISSUE THREAD

**Issue by 97tn** [pascalabcnet/pascalabcnet#2858]
### Discussed in https://github.com/pascalabcnet/pascalabcnet/discussions/2854

<div type='discussions-op-text'>

<sup>Originally posted by **97tn** May  9, 2023</sup>
Auto parsing of C headers to generate Pascal bindings.</div>

**Comment by miks1965** [comment]
Discussions are here: https://github.com/pascalabcnet/pascalabcnet/discussions
