### ISSUE TITLE
 (a,b) := (Random,Random) без скобок не работает

### ISSUE THREAD

**Issue by miks1965** [pascalabcnet/pascalabcnet#286]
```
begin
  var a,b: real;
  (a,b) := (Random,Random);
end.
```

**Comment by ibond84** [comment]
Не вижу ошибки. Random перегруженная функция. Компилятор не может знать, какой именно функцией Random инстанцируется Tuple и берет первую попавшуюся, а она с параметрами. Поэтому надо использовать скобки.

**Comment by miks1965** [comment]
```
  var a := Random;
  write(a);
```
Так работает

**Comment by ibond84** [comment]
Да, мы здесь пошли на компромисс, сделав приоритет вызову функции. Но для a можно явно указать тип переменной, если мы хотим использовать указатель на функцию. А как это сделать в скобочной нотации туплов, если мы отдадим приоритет вызову функции??

**Comment by miks1965** [comment]
На мой взгляд, к сожалению для нас, надо анализировать тип того, чему мы присваиваем, и если какая-то компонента - это не указатель на функцию, то преобразовывать это в вызов функции. Просто это долго анализировать, зато всё по-честному

**Comment by ibond84** [comment]
Здесь это не работает. Надо чем-то инстанцировать Tuple.Create в самом начале.

**Comment by miks1965** [comment]
Ну почему не работает. Это может работать именно в конструкции присваивания, а не в выражении. В выражении делать ничего не надо. А тут:
```
(a,b) := (Random,Random) 
```
надо анализировать тип a и b и либо преобразовывать Random к вызову функции либо нет.
При описании
```
(var a, var b) := (Random,Random) 
```
надо преобразовывать всегда поскольку это более штатный случай

**Comment by ibond84** [comment]
Ну а такие ситуации?

var obj := (Random, Random)
var obj: object :=  (Random, Random)

Ведь это все сводится к инстанцированию Tuple.Create. Не работает

**Comment by ibond84** [comment]
Придется отдать приоритет вызову функции. В FP для этих целей добавили @ для функций. Это разруливает все конфликты из-за этого ужасного архитектурного ляпа паскаля
