### ISSUE TITLE
A language server for PascalABC.NET?

### ISSUE THREAD

**Issue by 97tn** [pascalabcnet/pascalabcnet#2860]
### Discussed in https://github.com/pascalabcnet/pascalabcnet/discussions/2857

<div type='discussions-op-text'>

<sup>Originally posted by **97tn** May  9, 2023</sup>
I think this is the most reasonable move. There are many text editors out there supporting LSP. You could transform them into a powerful PascalABC.NET IDE. Of course, one could miss the form designer. Never mind. The form designer could be implemented as a standalone application like Qt's QtDesigner or GTK's Glade.</div>

**Comment by miks1965** [comment]
In issues we publish only bugs in PascalABC.NET. Any discussions are here: https://github.com/pascalabcnet/pascalabcnet/discussions
