### ISSUE TITLE
Непонятно какую версию сборки качаешь с сайта https://pascalabc.net

### ISSUE THREAD

**Issue by neurofreak-alt** [pascalabcnet/pascalabcnet#2865]
Здравствуйте!

Не совсем понятно какую версию качаешь с сайта. 
По этой ссылке скачивается архив с названием PABCNETC.zip: https://pascalabc.net/downloads/PABCNETC.zip

Вот если бы к имени архива добавлять ещё версию и номер сборки.

В самом дистрибутиве сборки нет какого нибудь текстового файла What's New c версией и описанием изменений.

Прошу учесть данные замечания. Развития вам!

**Comment by SunSerega** [comment]
https://pascalabc.net/downloads/pabcversion.txt

Этот файл не показывает, но его обновляет вместе со всеми остальными установщиками (и этим .zip файлом).
Вообще он существует для кнопки "Проверить обновления" в IDE, но можете скачивать его сразу с архивом.

**Comment by SunSerega** [comment]
По моему вопрос не закрыт... Желательно хотя бы сделать так, чтобы существование `pabcversion.txt` не было тайными знаниями.
