### ISSUE TITLE
Разрешает вызвать шаблонную функцию с неопределённым типом шаблона, если сразу использовать её результат

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#2867]
```
##
function f1<T> := 1;
var x := 2 + f1;
```
```
Ошибка времени выполнения: System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Исключение из HRESULT: 0x8007000B)
Стек:
   в 1.Program.$Main()
   в 1.Program.Main()
```
Очень напоминает #2154...
И так же как там, если вызывать `f1()`, то получаем ожидаемую ошибку:

> Невозможно вывести типы-параметры обобщённой подпрограммы f1 (укажите типы-параметры явно)

**Comment by SunSerega** [comment]
@ibond84 тест не прошёл же...

**Comment by ibond84** [comment]
Все прошло, внимательней читайте сообщения от гитхаба

**Comment by SunSerega** [comment]
А, вижу, его сбросило тестом следующего коммита...

Тест который показывает гитхаб таки оборвался на половине. Вот тот что прошёл:

https://github.com/pascalabcnet/pascalabcnet/actions/runs/6724381876

**Comment by SunSerega** [comment]
https://github.com/pascalabcnet/pascalabcnet/blob/master/.github/workflows/buildandruntests.yml#L14
```
cancel-in-progress: true
```
Я это добавил как оптимизацию, чтобы несколько тестов друг поверх друга не выполнялись, но если вам удобнее сразу несколько коммитов пушить - можно и убрать. Тогда тест устаревшего коммита сбрасывать не будет.

**Comment by ibond84** [comment]
Там не мой был коммит
