### ISSUE TITLE
Compile error CS0589

### ISSUE THREAD

**Issue by Pro-pra** [pascalabcnet/pascalabcnet#2871]
XBuild Engine Version 14.0
Mono, Version 6.12.0.182

```
DEBUG: ParserTools/DefaultLanguageInformation.cs(547,36): error CS0589: Internal compiler error during parsingSystem.NotImplementedException: type pattern matching
DEBUG: 				  at Mono.CSharp.CSharpParser.case_963 () [0x0002d] in <3373b3b314104edfb5261b9d1c5a1853>:0 
DEBUG: 				  at Mono.CSharp.CSharpParser.yyparse (Mono.CSharp.yyParser.yyInput yyLex) [0x04182] in <3373b3b314104edfb5261b9d1c5a1853>:0 
DEBUG: 				  at Mono.CSharp.CSharpParser.parse () [0x0002e] in <3373b3b314104edfb5261b9d1c5a1853>:0 
DEBUG: 			Task "Csc" execution -- FAILED
DEBUG: 			Done building target "CoreCompile" in project "/builddir/build/BUILD/pascalabcnet-3.8.3.3257/ParserTools/ParserTools.csproj".-- FAILED

```

В коде это строки:
https://github.com/pascalabcnet/pascalabcnet/blob/b7bc01e0027606e1ca93fdec63951562adea2340/ParserTools/ParserTools/DefaultLanguageInformation.cs#L547

что в них за ошибка синтаксиса csharp может быть?

**Comment by Pro-pra** [comment]
Сборку пока запускаю командой 
MONO_IOMAP=case xbuild /p:Configuration=release /p:TargetFrameworkVersion="v4.5" pabcnetc.sln

**Comment by SunSerega** [comment]
> Internal compiler error during parsingSystem.NotImplementedException

Это не ошибка неправильного синтаксиса, это сообщение что `csc` не реализовало компиляцию паттерн мачинга.
И раз внутренняя ошибка компилятора - наверное стоит писать в issue того компилятора, а не сюда?

**Comment by Pro-pra** [comment]
Откуда я знаю к чему это относится. не сюда так не сюда.

**Comment by SunSerega** [comment]
> Откуда я знаю к чему это относится

Из текста ошибки, которую вы же и скинули... Ну, теперь будете знать что такое `Internal compiler error`.

**Comment by Pro-pra** [comment]
разработчики mono теперь недружественны к вопросам из России.
В Альт линукс как-то умудрились собрать, в Роса пока вот так.

**Comment by SunSerega** [comment]
> разработчики mono теперь недружественны к вопросам из России.

Мда, я сам с Украины, но меня такое уже изрядно достало. Но по моему надо отдельных ублюдков прибивать, которые политику тащат в опенсорс, а не на весь проект клеймо вешать.

**Comment by miks1965** [comment]
Собирайте с помощью msbuild. У нас есть скрипт для сборки _RebuildRelease.sh

**Comment by Pro-pra** [comment]
https://github.com/pascalabcnet/pascalabcnet/issues/2811

msbuild пока нету в репозитарии, я даже не знаю в каком он проекте :(

**Comment by Pro-pra** [comment]
пока встало на: 
```
DEBUG: 	SugarVisitors/UnpackLambdaParametersVisitor.cs(74,65): error CS0012: The type `PascalABCCompiler.SemanticTree.ITypeNode' is defined in an assembly that is not referenced. Consider adding a reference to assembly `SemanticTree, Version=3.8.3.3257, Culture=neutral, PublicKeyToken=null'
DEBUG: 				/builddir/build/BUILD/pascalabcnet-3.8.3.3257/bin//TreeConverter.dll (Location of the symbol related to previous error)
```
Я так понимаю оно хочет чтобы был прописан этот TreeConverter.dll
пробовал так в csproj вписать:
```
+    <Reference Include="bin/Release/TreeConverter.dll" />
+    <Assemblies Include="SemanticTree, Version=3.8.3.3257, Culture=neutral, PublicKeyToken=null" />
```

**Comment by miks1965** [comment]
Да, у меня подобные ошибки возникали при сборке с xbuild. Странно но в проекте все эти зависимости есть и по msbuild всё собирается

**Comment by Pro-pra** [comment]
как-то я их не вижу в проекте, может не там смотрю?

**Comment by Pro-pra** [comment]
ага! логи видят все
```
		Project "/builddir/build/BUILD/pascalabcnet-3.8.3.3257/SyntaxVisitors/SyntaxVisitors.csproj" (default target(s)):
			Target PrepareForBuild:
				Configuration: Release Platform: AnyCPU
				Created directory "bin/Release/"
				Created directory "obj/Release/"
			Target ResolveAssemblyReferences:
/usr/lib/mono/xbuild/14.0/bin/Microsoft.Common.targets:  warning : Reference 'bin/Release/TreeConverter.dll' not resolved
				For searchpath {CandidateAssemblyFiles}
				Warning: {CandidateAssemblyFiles} not supported currently
				For searchpath {HintPathFromItem}
				HintPath attribute not found
				For searchpath {TargetFrameworkDirectory}
				Considered 'bin/Release/TreeConverter' as an assembly name, but it is invalid.
				For searchpath {PkgConfig}
				Considered bin/Release/TreeConverter, but could not find in any pkg-config files.
				For searchpath {GAC}
				Considered 'bin/Release/TreeConverter' as an assembly name, but it is invalid.
				For searchpath {RawFileName}
				Considered 'bin/Release/TreeConverter' as a file, but the file does not exist
				For searchpath bin/Release/
				Considered '/builddir/build/BUILD/pascalabcnet-3.8.3.3257/SyntaxVisitors/bin/Release/bin/Release/TreeConverter' as a file, but the file does not exist
				Considered '/builddir/build/BUILD/pascalabcnet-3.8.3.3257/SyntaxVisitors/bin/Release/bin/Release/TreeConverter.exe' as a file, but the file does not exist
				Considered '/builddir/build/BUILD/pascalabcnet-3.8.3.3257/SyntaxVisitors/bin/Release/bin/Release/TreeConverter.dll' as a file, but the file does not exist
```

**Comment by miks1965** [comment]
И в чем дело?

**Comment by Pro-pra** [comment]
действительно не подхватилась  SemanticTree.dll
Я уже начал как-то разбираться в этом месиве лога, алгоритмы подучу, пойду на джуна по mono :))

**Comment by Pro-pra** [comment]
гуд вписал в SyntaxVisitors.csproj и дело пошло дальше, но надо еще это же в другие части вписывать.
```
    <ProjectReference Include="..\SemanticTree\SemanticTree.csproj">
      <Project>{613E0DDA-AA8A-437C-AC45-507B47429FF9}</Project>
      <Name>SemanticTree</Name>
    </ProjectReference>
```

**Comment by Pro-pra** [comment]
хм... скомпилировалось...

**Comment by miks1965** [comment]
С помощью xbuild в росе?

**Comment by Pro-pra** [comment]
xbuild или msbuild это не покаазатель, вы же выяснили ранее что msc компилирует на самом деле.

вот такой патч:
https://abf.io/import/pascalabcnet/blob/rosa2023.1/pascalabcnet-csc.patch

Пока что добавлено в репозитарий контриб платформы 2023.1

**Comment by miks1965** [comment]
Посмотрел патч. Я могу переписать все эти новомодные pattern matching из нового C# - если только в этом дело.

Вот эта правка представляется неправильной:
```
else if (st.typ is SemanticCheckType.MatchedExpression)  // Это безобразие - SemanticCheckType в TreeHelper.cs помещать!!!
+            else if
+                ((SemanticCheckType)st.typ == SemanticCheckType.MatchedExpression)
```
1. Код в первой строчке должен работать и в msc - это обычный оператор is - он работал всегда.

2. Заменять is на точное соответствие типов может быть некорректно - is работает также с подклассами.

А Вы делали этот патч вручную или как-то автоматически?

**Comment by mikhailnov** [comment]
> А Вы делали этот патч вручную или как-то автоматически?

@Pro-pra доработал патч из https://github.com/pascalabcnet/pascalabcnet/issues/2811#issuecomment-1475365033 вручную, на глаз

**Comment by Pro-pra** [comment]
вай зачем на глаз, я логи читаль.

[miks1965](https://github.com/miks1965) эта правка переехала из предыдущего варианта патча, может и не нужна, попробовать запросто можно, но после 12мск.

Вот эту добавку вобще не помешало бы из патча взять в основной код. Я так понял что msc который щас в моно, не умеет автоматически определять assembles. В новых версиях у вас оно само определять умеет и подтягивает.
```
<ProjectReference Include="..\SemanticTree\SemanticTree.csproj">
      <Project>{613E0DDA-AA8A-437C-AC45-507B47429FF9}</Project>
      <Name>SemanticTree</Name>
    </ProjectReference>
```

**Comment by Pro-pra** [comment]
@miks1965 проверил сборку с убранной частью патча SemanticCheckType.MatchedExpression, не собирается. Много ошибок:
```
TreeConversion/syntax_tree_visitor.cs(21303,50): error CS0118: `PascalABCCompiler.SyntaxTree.SemanticCheckType.MatchedExpressionAndType' is a `Unresolved' but a `type' was expected
```

**Comment by Pro-pra** [comment]
Ок. исправил патч
https://abf.io/import/pascalabcnet/blob/rosa2023.1/pascalabcnet-csc.patch

**Comment by mikhailnov** [comment]
@miks1965 Еще решите, как поступим: надо либо внести этот патч в апстрим и продолжать писать код, как писали ранее, надеясь, что он будет собираться mcs, либо мы пока в Росе оставим этот патч, в апстрим его не внесем и будем ждать, пока получится собрать csc.

**Comment by miks1965** [comment]
Нет. Мы поступим по-другому. Я внес уже правки в код - избавился от всех этих новомодных switch по типам. 

Теперь нужно некоторое время - я избавлюсь от зависимости от SemanticTree в части проектов - ее там не должно быть - это недостаток проектирования.

То есть, Вы пока можете проверить и исправить патч, убрав из него весь код (это должно сработать - я копировал ваш), а зависимость от SemanticTree в патче оставить. Как только я от нее избавлюсь, необходимость в патче пропадет.

**Comment by Pro-pra** [comment]
А где релизы выкладываются? у Альтов версия новее (3.8.3.3257) чем релизные в гите и ссылки нету откуда они качали.

**Comment by miks1965** [comment]
Качаете с Git и собираете. 

Пока это Beta 3.9, но там уже похоже всё оттестировано - скоро выпустим Release. Это будет пометкой к коммиту. 

Но пересобрать под РОСу надо до этого. Я тогда в релизе напишу, что собран из исходников под Росу.

**Comment by Pro-pra** [comment]
из гита удобно тащить архив по tags или релиз, у вас tags не проставляются, а тащить по коммиту более сложно.

по tags или release можно еще скриптом делать автообновление.

>Но пересобрать под РОСу надо до этого. Я тогда в релизе напишу, что собран из исходников под Росу.

эту фразу я не понял, под Роса у нас уже собрано - можно писать. Как и все сборщики, я есть любить релизы и не любить брать напрямую из коммита.

**Comment by miks1965** [comment]
Мы внесли изменения в проект. Кроме тех изменений, которые были в коде в pattern matching, мы внесли изменения в архитектуру, ликвидировав зависимость от SemanticTree.dll.

По идее должно пересобираться под Росой безо всяких патчей.

Просим Вас попробовать пересобрать.

**Comment by mikhailnov** [comment]
> А где релизы выкладываются? у Альтов версия новее (3.8.3.3257) чем релизные в гите и ссылки нету откуда они качали.

Тут нет тегов, версия просто текстов в файл внутри git пишется, мы можем собирать по хешу коммита (http://wiki.rosalab.ru/en/index.php/Template_Spec_Files#Spec_file_when_building_a_git_snapshot) , а версию брать из файла

https://github.com/pascalabcnet/pascalabcnet/commit/af9b6acb91ff1102959fcea07c26a2b4c501bbda#diff-79d252c2115e3c9fe62646570998655948888a2fbcc8ea0a280df3dec14be3d9

**Comment by Pro-pra** [comment]
>Тут нет тегов, версия просто текстов в файл внутри git пишется

ну так я и говорю, были бы теги - было бы легче собирать. То что сейчас версия из файлов берется, это понятно. Но вдруг возьмут и теги прикрутят.

прям таки намекаю:
> из гита удобно тащить архив по tags или релиз, у вас tags не проставляются, а тащить по коммиту более сложно.

**Comment by miks1965** [comment]
Ну вы попробуйте собрать.

**Comment by Pro-pra** [comment]
с крайним коммитом гита:
```
SyntaxTreeConvertersController/SyntaxTreeConvertersController.cs(44,27): error CS0246: The type or namespace name `SyntaxSemanticVisitors' could not be found. Are you missing an assembly reference?
			Task "Csc" execution -- FAILED
```

**Comment by miks1965** [comment]
Ничего не понимаю. Мы создали новый проект - LambdaAnySynToSemConverter.csproj
Именно в нем находится пространство имен SyntaxSemanticVisitors.

Проект LambdaAnySynToSemConverter.csproj подключен как зависимый к проекту Compiler.csproj 

    <ProjectReference Include="..\LambdaAnySynToSemConverter\LambdaAnySynToSemConverter.csproj">
      <Project>{27d9800e-2689-4aa1-a2d6-128e4a9bae98}</Project>
      <Name>LambdaAnySynToSemConverter</Name>
    </ProjectReference>

SyntaxTreeConvertersController.cs как раз принадлежит проекту Compiler.csproj  - пространство имен SyntaxSemanticVisitors должно быть в нем видимо.

Это всё очень странно. У нас нет версий. У нас всё собирается.

В предыдущем случае была транзитивная зависимость - под mono надо было подключать в цепочке A->B->C к проекту A не только проект B, но и проект C. Но здесь - прямая зависимость - мы один проект подключаем к другому. Всё должно быть видно.

**Comment by Pro-pra** [comment]
вот нашел в логе:
```
/builddir/build/BUILD/pascalabcnet-af9b6acb91ff1102959fcea07c26a2b4c501bbda/pabcnetc.sln:  warning : /builddir/build/BUILD/pascalabcnet-af9b6acb91ff1102959fcea07c26a2b4c501bbda/Compiler/Compiler.csproj: ProjectReference '..\LambdaAnySynToSemConverter\LambdaAnySynToSemConverter.csproj' not found, neither by guid '27d9800e-2689-4aa1-a2d6-128e4a9bae98' nor by project file name '/builddir/build/BUILD/pascalabcnet-af9b6acb91ff1102959fcea07c26a2b4c501bbda/LambdaAnySynToSemConverter/LambdaAnySynToSemConverter.csproj'.
```

**Comment by miks1965** [comment]
Да, спасибо - добавил во все проекты. Теперь должно компилироваться везде. Issue закрывать?

**Comment by Pro-pra** [comment]
Ну проверю сборку, отпишу, и закроем

**Comment by Pro-pra** [comment]
без такого патча не собирается:
```
--- a/LambdaAnySynToSemConverter/LambdaAnySynToSemConverter.csproj	2023-05-31 14:04:04.000000000 +0300
+++ b/LambdaAnySynToSemConverter/LambdaAnySynToSemConverter.csproj	2023-06-04 08:37:03.690644106 +0300
@@ -62,6 +62,10 @@
       <Project>{1c9c945a-586d-42a2-a06b-65d84fa7ff78}</Project>
       <Name>TreeConverter</Name>
     </ProjectReference>
+    <ProjectReference Include="..\SemanticTree\SemanticTree.csproj">
+      <Project>{613E0DDA-AA8A-437C-AC45-507B47429FF9}</Project>
+      <Name>SemanticTree</Name>
+    </ProjectReference>
   </ItemGroup>
   <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />
 </Project>
```

**Comment by miks1965** [comment]
Добавил проект SemanticTree к LambdaAnySynToSemConverter.csproj

Проверьте пожалуйста - теперь собирается без патчей?

**Comment by Pro-pra** [comment]
да, теперь все хорошо стало. можно закрыть issue.

**Comment by mikhailnov** [comment]
Ничего подобного, консольный компилятор собрался, а GUI не собрался

```
DEBUG: MonoDebugging/Soft/SoftDebuggerAdaptor.cs(1120,34): error CS0589: Internal compiler error during parsingSystem.NotImplementedException: type pattern matching
DEBUG: 				  at Mono.CSharp.CSharpParser.case_963 () [0x0002d] in <3373b3b314104edfb5261b9d1c5a1853>:0 
DEBUG: 				  at Mono.CSharp.CSharpParser.yyparse (Mono.CSharp.yyParser.yyInput yyLex) [0x04182] in <3373b3b314104edfb5261b9d1c5a1853>:0 
DEBUG: 				  at Mono.CSharp.CSharpParser.parse () [0x0002e] in <3373b3b314104edfb5261b9d1c5a1853>:0 
DEBUG: 			Task "Csc" execution -- FAILED
DEBUG: 			Done building target "CoreCompile" in project "/builddir/build/BUILD/pascalabcnet-8e268912e7c4506489803edd6e4ad1aff23cfeab/VisualPascalABCNETLinux/VisualPascalABCNETLinux.csproj".-- FAILED
DEBUG: 		Done building project "/builddir/build/BUILD/pascalabcnet-8e268912e7c4506489803edd6e4ad1aff23cfeab/VisualPascalABCNETLinux/VisualPascalABCNETLinux.csproj".-- FAILED
DEBUG: 	Task "MSBuild" execution -- FAILED
DEBUG: 	Done building target "Build" in project "/builddir/build/BUILD/pascalabcnet-8e268912e7c4506489803edd6e4ad1aff23cfeab/PascalABCNETLinux.sln".-- FAILED
DEBUG: Done building project "/builddir/build/BUILD/pascalabcnet-8e268912e7c4506489803edd6e4ad1aff23cfeab/PascalABCNETLinux.sln".-- FAILED
DEBUG: Build FAILED.
```

@Pro-pra В скрипте https://github.com/pascalabcnet/pascalabcnet/blob/master/_RebuildReleaseAndRunTests.sh set -e - падение при неудаче промежуточной - вынесено в шебанг, а ты его в спеке запускаешь через sh -x, -e теряется, в результате GUI в пакете нет вообще.

Надо переоткрывать issue.

**Comment by Pro-pra** [comment]
У меня нет кнопки Reopen.

MonoDebugging/Soft/SoftDebuggerAdaptor.cs внесли совсем не давно и там видимо надо править синтаксис

**Comment by miks1965** [comment]
Переоткрыл

**Comment by Pro-pra** [comment]
MonoDebugging/Soft/SoftDebuggerAdaptor.cs можете исправить синтаксис как до этого в других исправляли подобное?

**Comment by ibond84** [comment]
У меня xbuild и новые конструкции компилирует. Так что проверять не могу. Смотрите, компилируется ли сейчас

**Comment by SunSerega** [comment]
@Pro-pra можете попробовать воспроизвести в GitHub Action?

**Comment by Pro-pra** [comment]
Спасибо, щас собралось нормально.

На гитхабе это наверное не вопроизвести т.к. нужен xbuild причем не тот который от майков, а самосборный. Собственно в actions Rosa прописать можно?

**Comment by mikhailnov** [comment]
Дело не в xbuild/msbuild, а в том, что xbuild запускает - csc или mcs. Если Росу в actions нельзя, то можно прописать ubuntu, но с mono из официального репозитория, в котором тоже нет csc, а есть mcs.

**Comment by miks1965** [comment]
Тогда мы ждем некоторое время - и если всё ОК - напишите - закроем.

**Comment by Pro-pra** [comment]
У меня запускается нормально. версия 3.9.0.3305.
