### ISSUE TITLE
Выбирает разный тип счётчика `for`, в зависимости от того, в каком порядке указать границы

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#2875]
https://forum.mmcs.sfedu.ru/t/for-loop-with-very-large-index/4122/6
```
##
var a := 1;
var b := 5000000000; // 5 миллиардов

TypeName(a).Print; // integer
TypeName(b).Print; // int64
// Ожидаемо выбирает более вместительный тип
TypeName(Max(a,b)).Println; // int64

for var i := a to b do
begin
  // Вычисляет тип i из a, игнорируя тип из b
  TypeName(i).Print; // integer
  break;
end;
for var i := b downto a do
begin
  // А тут наоборот, берёт тип из b, игнорируя тип из a
  TypeName(i).Println; // int64
  break;
end;
```
---

Такой заголовок:
```
for var i := a to b do
```
Неинтуитивно вызывает беззвучное переполнение, в то время как в других местах, к примеру при вызове `Max(a,b)` выбирается более подходящий тип.

**Comment by ibond84** [comment]
Не понял, в чем ошибка. Тип переменной определяется первым присваиванием, а не вторым и не десятым..

**Comment by SunSerega** [comment]
Первое присвоение это детали реализации. В заголовке присваивается весь диапазон - которому может выбирать не подходящий тип, приводя к переполнению.

**Comment by SunSerega** [comment]
И я вынес значения в переменные `a` и `b` чтобы небыло магических чисел.

По ссылке выше новичок попробовал делать что то типа:
```
for var i := 1 to 5000000000 do
```
Это сработало не так как ожидается, потому что вместо того чтобы использовать `int64` или сказать что верхняя граница не поместится в авто-вычисленный тип `integer` - компилятор сделал из большого числа мусор, и пошёл использовать его без какой-либо диагностики.

**Comment by SunSerega** [comment]
Проблема не интуитивного поведения так же исправится если выдавать предупреждение, когда верхняя граница имеет более вместительный тип.
Но в других местах, как при вызове `Max(1, 5000000000)`, тип выбирается сразу правильный, без насилования программиста.

**Comment by miks1965** [comment]
Нет, неверно. Переменная описывается вот здесь: var i := 1

Если нужен другой тип - описываем

for var i: int64 := 1

Никакого "полного диапазона" здесь нет.
