### ISSUE TITLE
Optional method parameters in Delphi, FreePascal and Oxygene are assigned with the "=" operator and in PascalABC this generates a compilation error.

### ISSUE THREAD

**Issue by MarcelloMello2** [pascalabcnet/pascalabcnet#2900]
Follows images on the 3 most popular compilers

Delphi
![Delphi](https://github.com/pascalabcnet/pascalabcnet/assets/100455548/2d57788a-ef17-403b-95ef-fa20037d973c)

Delphi with const
![Delphi-with-const](https://github.com/pascalabcnet/pascalabcnet/assets/100455548/1b00505b-7cf9-4e9f-96f2-838d32af5d24)

FreePascal
![FreePascal-Lazarus](https://github.com/pascalabcnet/pascalabcnet/assets/100455548/5eec94c9-f969-47b4-b1e3-aaa4c2cfc93c)
l

FreePascal with const
![FreePascal-Lazarus-with-const](https://github.com/pascalabcnet/pascalabcnet/assets/100455548/95ff10a7-4fb7-469b-8c2b-98cba9df9a16)

Oxigene with const
![Oxigene-with-const](https://github.com/pascalabcnet/pascalabcnet/assets/100455548/2287018f-17a8-4eeb-a2f5-4456759b82aa)

**Comment by MarcelloMello2** [comment]
The 2 test programs follow the code below.

program Test;

procedure TestDefaultArgValue(const AValue: string = 'my string');
begin
  Writeln(AValue);
end;

begin

  TestDefaultArgValue();
  TestDefaultArgValue('one string');

end.

![image](https://github.com/pascalabcnet/pascalabcnet/assets/100455548/b62732bd-2aad-448e-9494-1fe9992542ec)

**Comment by miks1965** [comment]
It's a bad solution in Delphi and Ohygene.

PascalABC.NET is an another Pascal dialect, uncomparable in some features that were appeared in Delphi later.

In PascalABC.NET for default parameters we have also named arguments with syntax:

```
p(name1 := 5);
```
It's impossible to use = here
