### ISSUE TITLE
Проблема с установкой и задачником

### ISSUE THREAD

**Issue by unniclever** [pascalabcnet/pascalabcnet#2904]
Win7 x64

Процесс установки залипает на некоторых шагах (скрин). 
![image](https://github.com/pascalabcnet/pascalabcnet/assets/55545289/4cfbb57d-e26c-4a10-b94a-5b3b4c9c51da)
 
![image](https://github.com/pascalabcnet/pascalabcnet/assets/55545289/975d23e6-37e6-4247-af82-6c2cb76c6257)

Пробовал убивать процесс ExecHide.exe в диспетчере, установка продолжается. Потом еще несколько раз.
Потом устанавливал еще несколько поверх старой, пока процесс установки не прошел без вмешательства в него.

При старте "задачника" (кнопка L) все ок, но если его закрыть, повторно уже не открыть.

**Comment by SunSerega** [comment]
`gacutil` может долго работать на старом железе, это нормально. У меня на более-менее современном несколько сек некоторые файлы обрабатывает.

В диспетчере задач показано что он всё ещё что-то делает, или именно зависает? И сколько времени вы ждали чтобы отвисло?

**Comment by miks1965** [comment]
Какой именно инсталлят вы скачиваете?

**Comment by unniclever** [comment]
> `gacutil`может долго работать на старой железе, это нормально. У меня есть несколько секционных файлов.
> 
> В диспетчере задач показывает, что он всё ещё что-то делает, или именно зависает? И сколько времени вы ждали, чтобы отвисло?

На то, сколько тянет процесс в диспетчере, внимание не обратил. Но оставлял на пол-часа и продвижений не было.
Он не зависал, как обычно происходит с процессами, когда курсор "вращается" над окном проги и предлагает либо дождаться, либо завершить. Т.е. просто процесс ExecHide есть в диспетчере, но сама установка просто "засыпает" на одном из этапов.

Установил не с первой попытки на другой диск. Но с "задачником" проблема не решилась.
Перезагружать пк пробовал

**Comment by miks1965** [comment]
Попробуйте установить [PascalABC.NET для Windows XP](https://pascalabc.net/downloads/PascalABCNETWithDotNet40Setup.exe)

Для некоторых старых Windows 7 установка может не работать.

Антивирус отключите

**Comment by unniclever** [comment]
> Попробуйте установить [PascalABC.NET для Windows XP](https://pascalabc.net/downloads/PascalABCNETWithDotNet40Setup.exe)
> 
> Для некоторых старых установка Windows 7 может не работать.
> 
> Антивирус отключите

забыл сказать, Каспер у меня давно отключен

**Comment by unniclever** [comment]
версия для ХР стала без проблем, правда, поверх установленной стандартной и фреймворк не ставил, т.к. на пк есть версия 4.8.
В общем, при нажатии L, задачник стартует
![image](https://github.com/pascalabcnet/pascalabcnet/assets/55545289/1a82663c-ddb1-491c-99c4-8bd097a80644)

Если нажать Отмена, он уже не запустится, удаление процесса PT4Load.exe не спасает, только перезагрузка пк.
Если нажать Ок, загружаются данные на страничку. Если ее закрыть (открыв новую), тоже повторно уже не запустить.

У других нормально все открывается повторно? Может это баг?

**Comment by SunSerega** [comment]
У меня открывается повторно, но выглядит вот так:
![image](https://github.com/pascalabcnet/pascalabcnet/assets/27270190/bcc7650e-334f-4d0d-bd0e-6d5dd835ebfc)

**Comment by miks1965** [comment]
Трудно сказать. Задачник не наш. Windows 7 - старый уже. И потом Вы возможно что то испортили предыдущей инсталляцией.

Напишите автору задачника - ptaskbook.com

**Comment by miks1965** [comment]
Задачник - внешний софт - мы Вам ничем не поможем.
