### ISSUE TITLE
Не компилируется пример с Microsoft.ML

### ISSUE THREAD

**Issue by ForNeVeR** [pascalabcnet/pascalabcnet#2905]
1. Собрать VisualPascalABCNET из исходного кода (коммит `c1c9225bddd1e20824def07712143f46e6bf5d0e`).
2. Создать новый проект.
3. Добавить ссылку на NuGet-пакет **Microsoft.ML**.
4. Написать в редакторе [код из примера](https://pascalabcnet.github.io/mydoc_release_notes_3_9_0.html):
   ```pascal
   uses Microsoft.ML;
   uses Microsoft.ML.Data;
   uses Microsoft.ML.Trainers;
   uses Microsoft.ML.Transforms;
   
   type 
     HouseData = auto class
     public  
       Size: single;
       Price: single;
     end;
     Prediction = class
     public  
       [ColumnName('Score')] 
       Price: single;
     end;
     
   function HD(sz,pr: single) := new HouseData(sz,pr);  
   
   begin
     var mlContext := new MLContext;
     var hData := Arr(HD(1.1,1.2),HD(1.9,2.3),HD(2.8,3.0),HD(3.4,3.7));
     var data := mlContext.Data.LoadFromEnumerable(hData);
   
     var opt := new SdcaRegressionTrainer.Options; 
     opt.LabelColumnName := 'Price'; // Зависимое значение
     opt.maximumNumberOfIterations := 100;
   // Все независимые значения - Features - объединяются в массив
     var pipeline := mlContext.Transforms.Concatenate('Features', Arr('Size')) 
       .Append(mlContext.Regression.Trainers.Sdca(opt)); 
       
     var model: ITransformer := pipeline.Fit(data);
     
     var size := new HouseData(3.5,0);
     var engine := mlContext.Model.CreatePredictionEngine&<HouseData, Prediction>(model);
     var price := engine.Predict(size);
     
     Println(price.Price);
   end.
   ```
5. Скомпилировать. Появляется ошибка:
   > Undefined name reference 'Sdca'
   <img width="956" alt="image" src="https://github.com/pascalabcnet/pascalabcnet/assets/92793/d7fadad6-707b-4b89-964f-4079919b69db">

Код проекта — во вложении: 
- [Project11.zip](https://github.com/pascalabcnet/pascalabcnet/files/12138937/Project11.zip)

**Comment by ForNeVeR** [comment]
Коммит `6720eef46e9c0d82b550003a68420f72f6604df2` (до вливания #2720) успешно компилирует тот же самый проект.

**Comment by miks1965** [comment]
Несомненно, хорошо бы чтобы с вашим Pull Requestом этот проект снова заработал. Поскольку мы позиционировали версию 3.9 как первую версию, которая может работать с Microsoft.ML. 

Если Вы посмотрите разницу, там у нас были вшиты в компилятор сборки, начинающиеся на Microsoft. Как это сделать правильно, мы тогда не разобрались и отложили. 

Если бы Вы посмотрели и возможно вернули ту строчку с явно вшитыми в компилятор сборками Microsoft - по крайней мере пока - было бы здорово. А то я честно пока не знаю, что делать с версией 3.9.

**Comment by ibond84** [comment]
Ну, там была специальная ветка для Microsoft.ML (грязный трюк), но работало

**Comment by ForNeVeR** [comment]
Первое различие, которое нашёл, в `PascalABCCompiler.TreeConverter.syntax_tree_visitor.visit_method_call`.

В хорошем случае (когда всё компилируется):
<img width="1003" alt="image" src="https://github.com/pascalabcnet/pascalabcnet/assets/92793/d58a405b-8498-436a-be33-eddda3e8180c">

В плохом случае (когда ничего не компилируется):
<img width="429" alt="image" src="https://github.com/pascalabcnet/pascalabcnet/assets/92793/c4bc44db-8899-4d33-b9c3-4a610121948e">

Типы с виду одинаковые.
<img width="894" alt="image" src="https://github.com/pascalabcnet/pascalabcnet/assets/92793/481333eb-6678-415e-8b9b-6ffff836d495">

<img width="820" alt="image" src="https://github.com/pascalabcnet/pascalabcnet/assets/92793/8e0cd7b0-2383-4db8-be1d-22a8f0b0cf7f">

**Comment by ForNeVeR** [comment]
Подозрительная особенность: в процессе «хорошего» компилятора я вижу одну сборку `Microsoft.ML.Data`, а в процессе «плохого» — аж 19 штук (в обоих случаях я мог компиляцию перезапустить несколько раз).
<img width="674" alt="image" src="https://github.com/pascalabcnet/pascalabcnet/assets/92793/a19443f9-47b5-4344-9cab-68fe344b1196">

<img width="645" alt="image" src="https://github.com/pascalabcnet/pascalabcnet/assets/92793/32345ce6-ef11-40ff-88ea-4cdc1eddb0d9">

Скорее всего, мои изменения сломали кэширование сборок, потому что именно сборки от Microsoft до этого специально загружались через `LoadFrom`, и поэтому дедуплицировались на уровне рантайма:
https://github.com/pascalabcnet/pascalabcnet/pull/2720/files#diff-ce0fd729e7f10f568af5a25050f87d0b468535f2ab7c2b2a432965e27e0be6f7L413-L426
```csharp
			try
            {
				System.IO.FileStream fs = System.IO.File.OpenRead(name);
				byte[] buf = new byte[fs.Length];
           		fs.Read(buf, 0, (int)fs.Length);
            	fs.Close();
                curr_inited_assm_path = name;
                if (!System.IO.Path.GetFileName(name).ToLower().Contains("microsoft."))
                    a = System.Reflection.Assembly.Load(buf);
                else
                    a = System.Reflection.Assembly.LoadFrom(name);
                a.GetTypes();
            	buf = null;
            	//Thread th = new Thread(new ThreadStart(collect_internal));
            	//th.Start();
			}
```
