### ISSUE TITLE
Компилятор не может найти сборку

### ISSUE THREAD

**Issue by samuraiGH** [pascalabcnet/pascalabcnet#2908]
В данном проекте следующая структура зависимостей

```
program
└─Npgsql
  ├─System.Threading.Tasks.Extensions
  ├─SomeAsm1
  ├─SomeAsm2
  ├─...
```

В папке лежат `Npgsql.dll` и `System.Threading.Tasks.Extensions.dll`. Остальные зависимости для проявления ошибки не нужны

Пытаемся скомпилировать следующий `program.pas`

```pas
{$reference 'npgsql.dll'}
//{$reference 'System.Threading.Tasks.Extensions.dll'}
## 
```

Получаем очень увесистый вывод из повторения следующих строк
```
Не удается загрузить один или более запрошенных типов. Обратитесь к свойству LoaderExceptions для получения дополнительных сведений.
Не удалось загрузить файл или сборку "System.Threading.Tasks.Extensions, Version=4.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51" либо одну из их зависимостей. Не удается найти указанный файл.
```
И затем 
```
[0][1,3] program.pas: Ошибка при чтении сборки 'D:\dev\test\npgsql\npgsql.dll'
```
Несмотря на то, что dll лежит рядом

Если раскомментрировать второй `reference`, то компиляция проходит нормально

С остальными зависимостями Npgsql такой проблемы не возникает 
[source.zip](https://github.com/pascalabcnet/pascalabcnet/files/12148621/source.zip)

**Comment by samuraiGH** [comment]
Вот тут 
https://github.com/pascalabcnet/pascalabcnet/blob/1d5f101a64f7bf0575b8ad358f57a27aacfb15b6/TreeConverter/NetWrappers/NetHelper.cs#L452
возникает `ReflectionTypeLoadException`

**Comment by samuraiGH** [comment]
`e.LoaderExceptions[0].FusionLog` 

![image](https://github.com/pascalabcnet/pascalabcnet/assets/87191377/0beed19e-9918-4e76-9b15-f8c15089c327)

Осталось понять, почему оно ищет везде, кроме папки с `Npgsql.dll`

**Comment by miks1965** [comment]
Поясните пожалуйста, в какой папке что лежит? dll лежат в папке .pas-файла? Или нет? При чём тут структура папок? В .NET все dll ищутся только в папке проекта

**Comment by samuraiGH** [comment]
> Поясните пожалуйста, в какой папке что лежит?

всё в одной папке. как в архиве

> При чём тут структура папок?

Вы про то, что в самом начале? это структура зависимостей, а не папок. то есть, что на что ссылается

**Comment by samuraiGH** [comment]
Причина в следующем

Как было сказано выше, структура зависимостей следующая

```
program
└─Npgsql
  ├─System.Threading.Tasks.Extensions
  ├─SomeAsm1
  ├─SomeAsm2
  ├─...
```

Когда компилятор пытается получить типы из `Npgsql.dll`, рефлексия обнаруживает, что для этого необходимо подгрузить ещё и `System.Threading.Tasks.Extensions.dll`. Для этого она берёт свойство `.CodeBase` сборки `Npgsql.dll` и пытается найти необходимую сборку в той же папке. 

И тут собственно проблема. `Npgsql.dll` была загружена примерно так 
```cs
var bytes = File.ReadAllBytes(name);
return Assembly.Load(bytes);
```
в результате Assembly.CodeBase этой сборки превращается в `file:///D:/dev/pascalabcnet/bin/TreeConverter.dll`, и рефлексия ищет в  папке `D:/dev/pascalabcnet/bin/`

**Comment by ibond84** [comment]
Проверьте, работает ли сейчас

**Comment by samuraiGH** [comment]
Работает

**Comment by miks1965** [comment]
Закрывать Issue?

**Comment by samuraiGH** [comment]
если обе сборки положить в подпапку lib, то работать уже не будет конечно, но это уже другая issue
