### ISSUE TITLE
Неверно вычисляется с longword  хотя тип верный

### ISSUE THREAD

**Issue by miks1965** [pascalabcnet/pascalabcnet#2910]
```
begin
  var a: longword := 2000000000;   
  Print(TypeName(a * 2),a*2);    
end.
```

**Comment by miks1965** [comment]
Вот генерируемый код:
![изображение](https://github.com/pascalabcnet/pascalabcnet/assets/10325391/9ed3a035-4856-4113-b93f-ada58062852a)

**Comment by SunSerega** [comment]
Дубль #2721. Смысл тот же, только операция другая.

**Comment by SunSerega** [comment]
А ILSpy, кстати, неверно показывает. Он думает что результат `num*2` превращает в `int`, но на самом там этого приведения нет.
Компилятор паскаля оставил 2 противоречивых типа на стеке вычисления (`a` имеет тип `UInt32`, `2` имеет тип `Int32`), поэтому CIL делает наименьшее зло и приводит оба операнда к `Int32` ещё до операции, чтобы хотя бы в случае с меньшими значениями переполнений не было.
Я думаю это вообще плохо, давать CIL решать к какому типу приводить - это ж платформо-зависимое поведение.

**Comment by SunSerega** [comment]
Кхм или не так всё же... IL оператор `mul` всегда работает над беззнаковыми целыми. Но в C#:
```
		uint a = 2000000000, b = 2;
		Console.WriteLine(a*b);
```
Результат умножения, который `int`, преобразовывает к `uint`, поэтому проблема не наблюдается. А паскаль преобразовывает к знаковому `int64`, поэтому значение не возвращается к ожидаемому.

**Comment by ibond84** [comment]
https://github.com/pascalabcnet/pascalabcnet/actions/runs/5705306038
