### ISSUE TITLE
Разная реакция на подобное условие в repeat

### ISSUE THREAD

**Issue by unniclever** [pascalabcnet/pascalabcnet#2914]
Где-то ошибка в коде или баг?

![image](https://github.com/pascalabcnet/pascalabcnet/assets/55545289/d7805503-b7c1-4693-9515-c8c5a21c9fc7)

на левом скрине все работает, на правом - выходит из цикла раньше времени. И так с числами 3+

**Comment by unniclever** [comment]
program repeatt;
var x:real;
begin
repeat
  writeln('x1: ', x);
  writeln('какая-то операция');
  x += 0.2;
  writeln('x2: ', x, #10);
until x > 3;
end.

**Comment by samuraiGH** [comment]
Про арифметику с плавающей точкой почитайте
