### ISSUE TITLE
Не могу вызвать системную функцию

### ISSUE THREAD

**Issue by Anixx** [pascalabcnet/pascalabcnet#2918]
Код:
```
uses NtApiDotNet, System.Diagnostics;
const DenyAccessSddl = 'O:BAG:SYD:(A;;RC;;;IU)(A;;DCSWRPSDRCWDWO;;;SY)';
begin
var ntObject := NtObject.OpenWithType ('Section', '\Sessions'+System.Convert.ToString(Process.GetCurrentProcess().SessionId)+'\Windows\ThemeSection', 
            nil, GenericAccessRights.WriteDac);
  try
    ntObject.SetSecurityDescriptor(new SecurityDescriptor(DenyAccessSddl), SecurityInformation.Dacl);
  finally
    ntObject.Free;
  end;
end.
```

Ошибка:
Project3.pas(4) : Отсутствует подпрограмма OpenWithType, соответствующая указанному списку аргументов

Уже всё проверил, GPT-4 говорит, что PascalABC не может вызвать эту функцию из-за отсутствия нормальной поддержки указателей.

**Comment by SunSerega** [comment]
Используйте маркдаун для выделения кода.

---

`PascalABC` и `PascalABC.Net` это разные языки, а ChatGPT знает вообще только про древнепаскальный.
Если бы вы хотя бы использовали что то вроде phind - оно смогло бы прогуглить этот вопрос...

И найти какие то огрызки информации, о том что указатели в .Net языках (в том числе и C#) использовать плохо.
Точнее их надо использовать только для связи с неуправлямым кодом. Но когда понимаете что делаете - указатели работают.

Ещё, надо понимать что голая модель (без плагинов) будет вам выдавать то, что вы спросили. Если у вас будет каша из не связанных терминов в вопросе (или терминов оно не понимает как связать, как паскаль и .Net) - оно начнёт придумывать, так чтобы использовать части вопроса и чтобы звучало адекватно.

---

Вам ошибка явным образом говорит что тип параметров который вы передали - не совпадает. Наведите мышку на `.OpenWithType` и посмотрите какие параметры вам показывает. Или, если там несколько перегрузок - их вам покажет при открытии скобки после этого имени.

И в коде, как минимум, не хватает `$reference` к библиотеке - как вы её вообще подключили без него? Или вы сюда огрызок запостили? Постите так, чтобы можно было откомпилировать у себя и увидеть эту же ошибку, иначе слишком много приходится гадать.

**Comment by SunSerega** [comment]
https://github.com/googleprojectzero/sandbox-attacksurface-analysis-tools/blob/c7ca3db6c2fb59eec3bceb4d5a731821f84f663a/NtApiDotNet/NtObject.cs#L321
Эту перегрузку вызвать пытались?

**Comment by Anixx** [comment]
> https://github.com/googleprojectzero/sandbox-attacksurface-analysis-tools/blob/c7ca3db6c2fb59eec3bceb4d5a731821f84f663a/NtApiDotNet/NtObject.cs#L321 Эту перегрузку вызвать пытались?

Ну да

**Comment by SunSerega** [comment]
> Я использовал Bing, так что, он гуглил.

Это скорее игрушка (или просто демонстрация) чем инструмент. Ему прикостыляли самый минимум функционала. Не то чтобы редактировать дерево диалога - он даже не знает синтаксис самого поисковика, как то что `-` перед словом исключает его из результатов.

И тем не менее, не понятно откуда взялись указатели. Неужели он сам это придумал, исходя из вашего кода, где ничего связанного с указателями нету?

> Код я запостил полный. Никаких $reference не вижу. Имя библиотеки есть в списке подключенных сборок проекта.

Ну, файл проекта это тоже текстовый файл и часть программы... Но вообще странно для такой мелкой программы целый проект создавать. Когда тестите что-то - удобнее всё в 1 файле иметь. А директива компилятора `$reference` это то, как подключаются библиотеки без проектов.

> Оригинальный код на C#:

Зачем тогда у вас `System.Convert.ToString`? `$' {...} '` есть и в паскале. А ещё у всех объектов можно вызвать `.ToString` (или `?.ToString`, если может быть `nil`), а числа в паскале можно складывать со строками и без всяких преобразований.

---

Покопался ещё в коде этой библиотеки... Похоже там ожидает что будет использовано вот это преобразование:
https://github.com/googleprojectzero/sandbox-attacksurface-analysis-tools/blob/c7ca3db6c2fb59eec3bceb4d5a731821f84f663a/NtApiDotNet/AccessMask.cs#L62

Но в паскале сейчас не находит преобразование, для которого надо сначала скастовать к предку:
```
type
  t1 = class end;
  t2 = class(t1) end;
  
  t_err = class
    
    static function operator implicit(x: t1): t_err := nil;
    
  end;
  
begin
  var x: t_err;
  x := new t2;
end.
```
Вы можете преобразовать к `Enum` явно или сделать свой оператор преобразования. Что то типа:
```
type
  t1 = class end;
  t2 = class(t1) end;
  
  t_err = class
    
    static function operator implicit(x: t1): t_err := nil;
    
  end;
  
// Можно описать для любых типов, в том числе для чужих и стандартных
function operator implicit(x: t2): t_err; extensionmethod := x as t1;

begin
  var x: t_err;
  x := new t2;
end.
```

**Comment by Anixx** [comment]
> Зачем тогда у вас System.Convert.ToString? $' {...} ' есть и в паскале.

Мне Бинг сначала так и написал, но система ругалась на нессответствие типов аргументов и Бинг посоветовал попробовать ToString. Я сам в синтаксисе не очень.

Дальше ваш ответ не понял, но GenericAccessRights.WriteDac я просто заменил на константу $40000.

После этого Паскаль ругается на ntObject.Free. Не знаю, нужно это или нет, я его удалил.

После этого ругается уже во время выполнения, что пут не найден (под админом тоже).
