### ISSUE TITLE
Выражение sizeof(integer) не является константой

### ISSUE THREAD

**Issue by DjArt** [pascalabcnet/pascalabcnet#2921]
Невозможно объявить константу:
```
const Bytes = sizeof(integer)
```
хотя размер `integer` известен до компиляции.

**Comment by DjArt** [comment]
Мне кажется, что [данное](https://github.com/pascalabcnet/pascalabcnet/commit/a63a4899685e6b776666d382d85d69a8ea36cc96#diff-8e2e1e083278cd854fa5d66cf38a525a183450bb921ba90faedc9bafedaa6adfR17) определение константы недопустимо.

Размер структуры со ссылками и классами невозможно получить во время компиляции, ведь неизвестно заранее, на какой платформе будет выполнятся код. По всей видимости способ исполнения модулей позволяет избежать данной проблемы, но при компиляции в IL-сборку такая константа будет неверной в ряде случаев. Т. е. объявить константный размер экземпляра типа со ссылками невозможно.

**Comment by ibond84** [comment]
Константы иногда реализуются просто как статические поля.

**Comment by DjArt** [comment]
А как же потом их различать? Статическое поле нельзя сделать, например, параметром по умолчанию, или задать как значение в атрибутах `StructLayout` или `FieldOffset`.

**Comment by ibond84** [comment]
>Статическое поле нельзя сделать, например, параметром по умолчанию, 

В паскале можно

**Comment by ibond84** [comment]
>, или задать как значение в атрибутах StructLayout или FieldOffset.

Ну зачем это для статических полей, если они всегда лежат в одном месте?

**Comment by DjArt** [comment]
Тем не менее я с этой проблемой я столкнулся именно в контексте использования атрибутов над записями для автоматического сопоставления набора байт в запись по ссылке.

**Comment by DjArt** [comment]
> > , или задать как значение в атрибутах StructLayout или FieldOffset.
> 
> Ну зачем это для статических полей, если они всегда лежат в одном месте?

Нет, немного наоборот - есть поле в записи, над ним атрибут, и в нём хочется использовать константу.

**Comment by SunSerega** [comment]
> Статическое поле нельзя сделать, например, параметром по умолчанию, или задать как значение в атрибутах `StructLayout` или `FieldOffset`.

Покажите подробнее как вы сравнение делаете. Вообще в CLR расчёт на то что `FieldOffset` только для маршлинга в неуправляемые типы, а не того что в управляемом коде происходит. Грубо говоря, если достаёте указателями из `a: record s: string; end;` байты для сравнения - всегда есть маленькая но вероятность что `a=a` даст `false`. Это неправильное использование указателей.
