### ISSUE TITLE
Ошибка `ONE_TYPE_PARAMETER_MUSTBE_WITHOUT_PARENTHESES` 

### ISSUE THREAD

**Issue by samuraiGH** [pascalabcnet/pascalabcnet#2922]
```pas
procedure pr1(act: (array of byte)-> () );
begin end;

begin end.
```

```
test.pas(1) : SEMANTICERROR_ONE_TYPE_PARAMETER_MUSTBE_WITHOUT_PARENTHESES
```

Однако у этой ошибки префикс `%PREFIX%=PASCALABCPARSER_`

Вот тут возникает исключение
https://github.com/pascalabcnet/pascalabcnet/blob/43383d6f11f0d39e3118d607df3229e9fde48536/TreeConverter/TreeConversion/syntax_tree_visitor.cs#L21086

**Comment by SunSerega** [comment]
ИМО ошибки не должны быть, но это #2923, а тут issue про то, что название ошибки не переведено на русский...

**Comment by ibond84** [comment]
Ошибка какая-то надуманная и выводится при семантическом анализе

**Comment by SunSerega** [comment]
А зачем `is array_type`? Это же не единственный тип, который через `of` пишется...
```
procedure pr1(act: (sequence of byte)-> () );
begin end;

begin end.
```

**Comment by SunSerega** [comment]
Проверил - с `sequence` таки не работает.

**Comment by SunSerega** [comment]
@ibond84 проверка с ошибкой `!(en.enumerators[i].name is named_type_reference)` такая же надуманная тут. А то что вы для массивов её обошли - костыль.

Для типов которые пишутся через `of` и не подходят уже есть другая, более точная ошибка на уровне семантики:
```
  //Ошибка: Тип типизированного файла не может выступать в качестве параметра обобщения
  var p: ()->file of byte;
```
Сейчас её показывает для типа результата. А для типов параметров даёт такую же не-интуитивную ошибку:
```
  //Ошибка: В качестве типа ожидался идентификатор
  var p: (file of byte, file of byte)->();
```
Это глупость - `file of byte` уже уникально идентифицирует 1 тип. А из за этого надуманного запрета не даёт использовать тут `sequence` и не выдаёт более подробную ошибку для `file`.

**Comment by ibond84** [comment]
Согласен
