### ISSUE TITLE
Комиплятор ломает лямбду с массивом в аргументе

### ISSUE THREAD

**Issue by samuraiGH** [pascalabcnet/pascalabcnet#2923]
```pas
procedure pr1( task: array of integer -> () );
begin
end;

begin
  var task: array of integer -> ();
  task.ToString;
end.
```

```cs
public static void pr1(Action<int>[] task)
{ }

public static void $Main()
{
  Action<int>[] actionArray;
  actionArray.ToString();
}
```

Вместо `Action<int[]>` создаётся `Action<int>[]`

**Comment by SunSerega** [comment]
Лямбда это конкретная функция (хоть и анонимная), а тут тип-делегат, описанный в стиле лямбды (со стрелочкой).
Вы всё ещё можете описать `Action<array of integer>` напрямую. 

Но конкретно синтаксис в стиле лямбды действительно не однозначный. `array of integer -> ()` одинаково правильно интерпретировать и как массив делегатов, и как делегат принимающий массив.
Для таких случаев стоило бы разрешить скобки для 1 параметра:
- `(array of integer) -> ()`
- `array of (integer->())`

Сейчас скобки разрешает для 0 и 2+ параметров, но не 1, потому что эту проблему не ожидали...

Ну а неоднозначный случай (`array of integer -> ()`) по моему стоит запретить, чтобы об это не спотыкались, а явно указывали скобками, что имеется в виду.

**Comment by SunSerega** [comment]
А, `array of (integer->())` сейчас работает, но делает картёж с 1 элементом... По моему это глупость.
Картёж из 1 элемента может быть нужен только компилятору (к примеру как в C# картёж из 8 элементов реализуется: [в виде 7+1 элементов](https://referencesource.microsoft.com/#mscorlib/system/tuple.cs,968)).
Лучше будет если делегаты в стиле лямбды и т.п. можно описывать с лишними скобками, а картёж из 1 элемента описывать только в стиле `System.Tuple<...>`.

**Comment by ibond84** [comment]
Ничего там не ломается: array of T имеет приоритет.

**Comment by samuraiGH** [comment]
По-моему, это плохая политика, что все сложные ситуации с `keyword of T` нужно решать через синоним

**Comment by ibond84** [comment]
Нормальная практика

**Comment by samuraiGH** [comment]
Такая политика идёт в разрез с общей лаконичностью Pascal
