### ISSUE TITLE
русские ключевые слова

### ISSUE THREAD

**Issue by budden** [pascalabcnet/pascalabcnet#2953]
Доброго времени суток. Как насчёт того, чтобы сделать опционально русские ключевые слова? Как вариант, если файл начинается со слова "программа" или "модуль", то лексер переходит в русскоязычный режим и понимает русскоязычные слова. Я сегодня сел и подправил один файлик:

```
+++ b/Parsers/PascalABCParserNewSaushkin/Keywords.cs
@@ -65,16 +65,20 @@ namespace GPPGParserScanner
             keywords.Add(Convert("where"), (int)Tokens.tkWhere);
             keywords.Add(Convert("array"), (int)Tokens.tkArray);
             keywords.Add(Convert("begin"), (int)Tokens.tkBegin);
+            keywords.Add(Convert("нач"), (int)Tokens.tkBegin);
             keywords.Add(Convert("case"), (int)Tokens.tkCase);
 ```
У меня какая-то старая версия 68e50baf9da5da7 от 2021 года, т.к. у меня Ubuntu 20 и были некоторые проблемы со сборкой. Возможно, этот файл куда-то переехал. С несколькими изменениями такого рода в этом списке следующая программа скомпилировалась и заработала:

```
программа a;

конст b = 7;

проц Главная();(*  азя-базя *)
нач
если 1 = 1 то нач
 println();
 println('!!!!!!!!!!!');
 println('Привет, мир');
 println('!!!!!!!!!!!') кон; кон;

нач
Главная кон.
```

Если в целом интересно, давайте обсудим. Я нашёл, что изменения надо вносить во многих местах, но можно начать хотя бы с консольного компилятора. Откуда брать ключевые слова - отдельная песня. Логично вроде брать из КуМира, т.к. он тоже школьный, но у меня затык возник уже со словом `алг`, которое в КуМире - и процедура и функция, а в Паскале это два слова. Но вообще полно языков с русскими ключевыми словами, есть списки, вот два:

https://www.вече.программирование-по-русски.рф/viewforum.php?f=13

Второй на compiler.su, но он прилёг отдохнуть.

**Comment by budden** [comment]
![ПаскальЧШЩ](https://github.com/pascalabcnet/pascalabcnet/assets/13260934/2837fccb-54b1-4c60-9540-2b819a2f6001)

**Comment by SunSerega** [comment]
Выше в этом же файле, если посмотрите на реализацию `Convert` - оно уже берёт замены ключевым словам из файла `C:\Program Files (x86)\PascalABC.NET\keywordsmap.pabc` (или куда у вас паскаль на убунте установлен)
А добавлять русские ключевые слова в основной пакет - звучит как плохая идея, это годится максимум поиграться или на первые пару занятий. Всё равно символы как `@#$[]{}'` - всё в англ. раскладке. Лучше учится на англ. набирать.

> были некоторые проблемы со сборкой

Ну, надо сейчас попробовать тогда. А вообще подозреваю что дело в #2890... Вырежьте у себя тест который эту пакость даёт.

**Comment by budden** [comment]
А, спасибо про файл замен. Оно и для раскраски тоже работает? Вопрос про раскладку решается отдельно, у меня есть решение. Основной объём работы - это документация. Я, кстати, не очень понял, почему не открывается справка (ubuntu 20), но это видимо надо отдельную задачу заводить.

**Comment by budden** [comment]
Проблемы со сборкой состояли в том, что для одних версий не указана версия Ubuntu, поэтому я развернул 20-ю, но у вас оказалась 22-я. На втором этапе установился mono без msbuild. Потом в итоге я разворачивал mono по инструкции из коммита, к-рый в первом сообщении, и у меня собралась та же версия, а потом и master, правда в конце распечатал какой-то стек, но среда запустилась. Далее, не видно тега для последней версии, остаётся только гадать, из каких исходников оно собрано.

**Comment by SunSerega** [comment]
> Оно и для раскраски тоже работает

Нет, подсвечивание описано в:
```
C:\Program Files (x86)\PascalABC.NET\Highlighting\PascalABCNET.xshd
```

**Comment by budden** [comment]
Спасибо, вот такой файл замен keywordsmap.pabc сработал:
```
procedure процедура
function функция
if если
then то
else иначе
begin нач
end кон
program программа
```
Он должен быть в кодировке unicode, вангану, что это utf-16, но я просто в исходнике в этом месте поставил Utf-8, без этого падало (и да, там перехватывались все исключения, поэтому было сложно это понять без отладки, я это сразу на всякий случай убрал, и чутьё не подвело). 

(я не видел, чтобы он был где-то описан, пусть тут будет, может кому пригодится). Подсвечивание уже раньше нашёл и подправил (для 2-3 слов), см. скриншот.

**Comment by miks1965** [comment]
Закрываю. Можно обсуждать здесь. Дело хорошее. 
Добавлять в основной пакет не будем.
