### ISSUE TITLE
Выбирает первое попавшееся имя, если они отличаются только регистром

### ISSUE THREAD

**Issue by samuraiGH** [pascalabcnet/pascalabcnet#2954]
```cs
using System;

namespace ns1
{
	public class myclass
	{
		public myclass()
		{ 
			Console.WriteLine("lowercase");
		}
	}

	public class MYCLASS
	{
		public MYCLASS() 
		{
			Console.WriteLine("uppercase");
		}
	}
}
```
```pas
## {$reference 'l1.dll'}
uses ns1;
var var1:= new MYCLASS;
```
```
lowercase
```

**Comment by ibond84** [comment]
Ну это UB. В паскале все case insensitive

**Comment by samuraiGH** [comment]
Это понятно. Не понятно, что с этим делать.
Случай не слишком распространённый и срочного фикса не требует, но по факту это проблема

Возможно стоит выбирать в зависимости от регистра при обнаружении таких коллизий

**Comment by miks1965** [comment]
Паскаль - регистронезависимый

**Comment by SunSerega** [comment]
Та понятно, но ситуация всё равно неправильная. Никакой диагностики, никакой возможности это обойти.

**Comment by samuraiGH** [comment]
Вам приносят репорты на реально проблемные моменты, которым нет адекватного объяснения. А вам лишь бы issue закрыть побыстрее. Не хотите сами реализовывать что-то, дак может кто-то из сообщества возьмётся

Ладно, давайте делать вид, что проблемы, порождённые дизайном языка, это вовсе не проблемы, а так, маленькие сюрпризы

Надоело уже конкретно

**Comment by samuraiGH** [comment]
С #2956 тоже самое. Падает компилятор не понятно почему -- ну и что? пусть люди сами разбираются. Один смог, другие тоже догадаются, зачем нам адекватные сообщения об ошибке

**Comment by ibond84** [comment]
Найдите хоть одну реальную dll, где такое встречается

**Comment by ibond84** [comment]
Это неопределенное поведение. Выбирается случайный тип. Это нормально.

**Comment by samuraiGH** [comment]
Вы ничего нового не сказали. Конечно можете считать, что не иметь возможности чётко понимать, что делает код это норма. Для меня это не норма

**Comment by miks1965** [comment]
Еще раз повторю - Паскаль - регистронезависимый. C# - регистрозависимый. В этой ситуации не надо использовать dll C#. И нечего спорить.

**Comment by SunSerega** [comment]
> В этой ситуации не надо использовать dll C#

Вы в серьёз предлагаете это как решение???

То же самое можно сказать об абсолютно любой issue. Только что из этого будет...

**Comment by samuraiGH** [comment]
Тут C# даже не при чём. Это CIL регистрзависимый

И если не хотите обращать внимание на проблемы интеграции с .NET, то зачем вообще этот постфикс в названии языка?

> В этой ситуации не надо использовать dll C#

Это звучит даже не серьёзно. Если так подходить к решению проблем, то pabc полноценным .NET языком никогда и не станет

**Comment by miks1965** [comment]
А как вы предлагаете эту проблему решать?

**Comment by SunSerega** [comment]
К примеру, при загрузке таблице имён из .dll - использовать `.GroupBy` со `StringComparer.OrdinalIgnoreCase`. Если в какой то из групп оказывается несколько типов (имя, отличающееся только регистром), можно:

- Создавать виртуальный тип, который при использовании будет хотя бы кидать ошибку "невозможно выбрать между одноимёнными типами"

- Создавать `List<compiled_type>`, а в функции поиска типа выбирать или единственный тип из этого списка, или тип который полностью подходит по регистру. А если не получается - опять же, кидать осмысленную ошибку.

**Comment by miks1965** [comment]
Ни один вменяемый человек не станет в сборку помещать классы, различающиеся регистром.
