### ISSUE TITLE
Странная ошибка при подключении библиотеки

### ISSUE THREAD

**Issue by samuraiGH** [pascalabcnet/pascalabcnet#2956]
```
## {$reference 'System.Data.SQLite.dll'}
```
Описание ошибки очень занимательное
```
Внутренняя ошибка компилятора в модуле [pabcnetc.exe] :'System.Exception: System.IO.FileLoadException: Не удалось загрузить файл или сборку "file:///D:\dev\units\System.Data.SQLite.dll" либо одну из их зависимостей. Операция не поддерживается. (Исключение из HRESULT: 0x80131515)
Имя файла: 'file:///D:\dev\units\System.Data.SQLite.dll' ---> System.NotSupportedException: Предпринята попытка загрузить сборку из сетевого ресурса, что в предыдущих версиях .NET Framework могло привести к помещению сборки в "песочницу". Этот выпуск .NET Framework не включает политику CAS по умолчанию, поэтому данная загрузка может быть опасной. Если эта нагрузка не предназначена для изоляции сборки, включите переключатель loadFromRemoteSources. Дополнительные сведения см. на странице http://go.microsoft.com/fwlink/?LinkId=155569.
   в System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   в System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   в System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark& stackMark)
   в System.Reflection.Assembly.LoadFrom(String assemblyFile)
   в PascalABCCompiler.NetHelper.NetHelper.LoadAssembly(String name, Boolean use_load_from)
   в PascalABCCompiler.NetHelper.AssemblyResolveScope.PreloadAssembly(String assemblyFilePath)
   в PascalABCCompiler.Compiler.GetReferences(CompilationUnit Unit)
   в PascalABCCompiler.Compiler.CompileUnit(unit_node_list Units, Dictionary`2 DirectCompilationUnits, unit_or_namespace SyntaxUsesUnit, String prev_path)
   в PascalABCCompiler.Compiler.Compile()

 System.Exception: System.IO.FileLoadException: Не удалось загрузить файл или сборку "file:///D:\dev\units\System.Data.SQLite.dll" либо одну из их зависимостей. Операция не поддерживается. (Исключение из HRESULT: 0x80131515)
Имя файла: 'file:///D:\dev\units\System.Data.SQLite.dll' ---> System.NotSupportedException: Предпринята попытка загрузить сборку из сетевого ресурса, что в предыдущих версиях .NET Framework могло привести к помещению сборки в "песочницу". Этот выпуск .NET Framework не включает политику CAS по умолчанию, поэтому данная загрузка может быть опасной. Если эта нагрузка не предназначена для изоляции сборки, включите переключатель loadFromRemoteSources. Дополнительные сведения см. на странице http://go.microsoft.com/fwlink/?LinkId=155569.
   в System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   в System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   в System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark& stackMark)
   в System.Reflection.Assembly.LoadFrom(String assemblyFile)
   в PascalABCCompiler.NetHelper.NetHelper.LoadAssembly(String name, Boolean use_load_from)
   в PascalABCCompiler.NetHelper.AssemblyResolveScope.PreloadAssembly(String assemblyFilePath)
   в PascalABCCompiler.Compiler.GetReferences(CompilationUnit Unit)
   в PascalABCCompiler.Compiler.CompileUnit(unit_node_list Units, Dictionary`2 DirectCompilationUnits, unit_or_namespace SyntaxUsesUnit, String prev_path)
   в PascalABCCompiler.Compiler.Compile()

'
```
[bug.zip](https://github.com/pascalabcnet/pascalabcnet/files/13399988/bug.zip)

**Comment by ibond84** [comment]
Не воспроизводится

**Comment by ibond84** [comment]
Наверно, вы компилируете программу, лежащую на сетевом диске. А там политики безопасности..

**Comment by samuraiGH** [comment]
> @ibond84 Наверно, вы компилируете программу, лежащую на сетевом диске.

В том-то и дело, что нет

**Comment by ibond84** [comment]
Ну, в #2959 у вас как-то подключилась эта библиотека. Нужны подробности..

**Comment by samuraiGH** [comment]
> @ibond84 Ну, в #2959 у вас как-то подключилась эта библиотека

там другая библиотека подключена. они из разных пакетов
![image](https://github.com/pascalabcnet/pascalabcnet/assets/87191377/ae7a28fe-db84-4200-8e6b-a34d31a76069)
В этой issue binary-bundle

В той просто binary

**Comment by ibond84** [comment]
https://ru.stackoverflow.com/questions/441645/windows-10-%D1%81%D0%B1%D0%BE%D1%80%D0%BA%D0%B0-%D0%B7%D0%B0%D0%B2%D0%B5%D1%80%D1%88%D0%B0%D0%B5%D1%82-%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D1%83-%D1%81%D1%80%D0%B0%D0%B7%D1%83-%D0%BF%D0%BE%D1%81%D0%BB%D0%B5-%D0%B7%D0%B0%D0%BF%D1%83%D1%81%D0%BA%D0%B0

**Comment by ibond84** [comment]
Долго мучался чтобы побороть такое поведение, и не заставлять клиентов каждый раз снимать галки с dll. Одно из решений: не отдавать пользователям готовый конфиг файл, а генерить его при первом запуске приложения. Тогда он создается уже без признака небезопасного. Например так:

static void Main()
    {
        if (!(File.Exists(Process.GetCurrentProcess().MainModule.FileName + ".config")))
        {
            File.WriteAllText(Process.GetCurrentProcess().MainModule.FileName + ".config", Properties.Resources.App);
            Process.Start(Process.GetCurrentProcess().MainModule.FileName);
        }
        else
        {
            Application.EnableVisualStyles();
            Application.SetCompatibleTextRenderingDefault(false);
            Application.Run(new MainForm());
        }
    }
В конфиг файле при этом должна быть разрешена загрузка из удаленных источников:

<runtime>
    <loadFromRemoteSources enabled="true"/>
</runtime>

**Comment by samuraiGH** [comment]
<img width="282" alt="image" src="https://github.com/pascalabcnet/pascalabcnet/assets/87191377/37119da8-859d-4a48-bdf3-73362b5c0d92">
а, вот в чём дело

надо бы как-то детектить это перед загрузкой сборки в компилятор

**Comment by miks1965** [comment]
Закрывайте issue

**Comment by samuraiGH** [comment]
Зачем? Компилятор падать не должен в любом случае

**Comment by SunSerega** [comment]
Куда вы спешите всё закрывать?

**Comment by miks1965** [comment]
Если пару dll еще удалить, компилятор точно упадет. Вы подсовываете коррумпированные dll и хотите чтобы адекватно работало. Сообщение об ошибке - нормальное - среда не падает. Компилятор не может понять, что с вашей dll не так и почему вы ее плохо скачали из интернета. Компилятор выводит проблему.

**Comment by SunSerega** [comment]
Среда не падает, но компилятор падает. И это окно "Внутренняя ошибка компилятора" сразу предлагает репортить это дело разработчикам. А теперь вы придумываете почему надо менять как можно меньше. Если вы не хотите сами тратить время - зачем вообще issue трогать?

**Comment by samuraiGH** [comment]
В возникновении `#2957` тоже виноват тот, кто писал код -- не обозначил тип лямбды, там где это необходимо. Давайте это тоже не фиксить, среда же не падает, а просто проблему выводит. Не понятно правда, зачем программисту на стектрейс компилятора смотреть, но пусть просвещается

**Comment by miks1965** [comment]
Еще issue неправильно сформирован. И заголовок неправильный. Странная ошибка - это не локализация ошибки. Переоткройте новый issue и четко укажите условия, при которых везде возникает ошибка.
