### ISSUE TITLE
Отсутствие методов расширения Print и Println для типов single и decimal

### ISSUE THREAD

**Issue by MPuchkin** [pascalabcnet/pascalabcnet#2961]
https://github.com/pascalabcnet/pascalabcnet/blob/6bc05f0f9073f5e60288689e954e1a70cdf1f543/bin/Lib/PABCSystem.pas#L9850

Нет реализации методов расширения Print и Println для типов single и decimal. Насколько они востребованы - большой вопрос, раз до сих пор это не всплыло. Но, кажется, для порядка можно было бы добавить.

**Comment by miks1965** [comment]
Я бы закрыл это issue/ Там гибельная туча целых типов - для каждого определять метод расширения Print и Println - это замусоривать все пространства имен классов.

**Comment by SunSerega** [comment]
Там у каждого типа своё пространство имён. Обилие глобальных методов можно назвать замусориванием, потому что сложнее найти то что надо. Но даже это сомнительный минус. Если будет проблемой - можно улучшить поиск. А что "замусоривается" в этом случае, 1 методом в каждом списке по точке для нескольких типов?

**Comment by miks1965** [comment]
Print изначально вводился для начинающих - для наиболее распространенных типов. Там и останется. 
Тем более, автор issue пишет о сомнительной полезности. А мы не занимаемся сомнительными полезностями.
