### ISSUE TITLE
Лямбды не работают при инициализации глобальных переменных

### ISSUE THREAD

**Issue by miks1965** [pascalabcnet/pascalabcnet#297]
```
var a := ArrGen(10,x->x);
begin
end.
```
Жуткая ошибка - () : Операция ':=' не применима к типу  
По-моему, Роман писал что не всё разобрал. Просмотреть переписку с ним

**Comment by miks1965** [comment]
```
var a :=SeqGen(10,x->x+2);
begin
end.
```
Тут сообщение лучше но всё равно не работает

**Comment by ibond84** [comment]
Ну это надо запрещать, так как это тоже запрещено. 
```
procedure test;
var a := ArrGen(10,x->x);
begin
  
end;
```

**Comment by ibond84** [comment]
кстати, не надо ничего запрещать. вот такое работает
```
function test := ArrGen(10,x->x);
var a := test();
begin
  writeln(a);
end.
```
достаточно в визиторе обернуть инициализатор вызовом короткой функции
