### ISSUE TITLE
3.9.0.3386 linux build failed

### ISSUE THREAD

**Issue by Pro-pra** [pascalabcnet/pascalabcnet#2979]
В продолжении https://github.com/pascalabcnet/pascalabcnet/issues/2871
пробую собрать 3.9.0.3386:
```
AppConfigUtil.cs(115,42): error CS1525: Unexpected symbol `(', expecting `,', `;', or `='
AppConfigUtil.cs(117,83): error CS1525: Unexpected symbol `.', expecting `,', `;', or `='
AppConfigUtil.cs(151): error CS1525: Unexpected symbol `}'
			Task "Csc" execution -- FAILED
```

**Comment by Pro-pra** [comment]
Школы хотят чтобы было вот это:

> Там очень важное обновление для олимпиад появилось. Пошаговый отладчик. Без него ide на олимпиаду не допускается

**Comment by ibond84** [comment]
Проверьте, компилируется ли сейчас

**Comment by miks1965** [comment]
Проверяйте - всё должно собираться

**Comment by Pro-pra** [comment]
Спасибо, компилируется.
