### ISSUE TITLE
Компилятор падает, если пытается использовать PCU, сгенерированный предыдущей версией компилятора

### ISSUE THREAD

**Issue by samuraiGH** [pascalabcnet/pascalabcnet#2981]
Не могу точно сказать, какой именно версией скомпилировано было.
Ориентировочно скачивал 3 декабря или 19 ноября.

```
[0]Внутренняя ошибка компилятора в модуле Compiler.Compile[main.pas] :'System.IndexOutOfRangeException: Индекс находился вне границ массива.
   в PascalABCCompiler.TreeConverter.syntax_tree_visitor.visit(statement_list _statement_list)
   в PascalABCCompiler.TreeConverter.syntax_tree_visitor.convert_strong(statement st)
   в PascalABCCompiler.TreeConverter.syntax_tree_visitor.visit_program_code(statement_list program_code)
   в PascalABCCompiler.TreeConverter.syntax_tree_visitor.visit(block _block)
   в PascalABCCompiler.TreeConverter.syntax_tree_visitor.visit(program_module _program_module)
   в PascalABCCompiler.TreeConverter.SyntaxTreeToSemanticTreeConverter.CompileInterface(compilation_unit SyntaxUnit, unit_node_list UsedUnits, List`1 ErrorsList, List`1 WarningsList, SyntaxError parser_error, Hashtable bad_nodes, using_namespace_list namespaces, Dictionary`2 docs, Boolean debug, Boolean debugging, Boolean for_intellisense, List`1 CompiledVariables)
   в PascalABCCompiler.Compiler.CompileUnit(unit_node_list Units, Dictionary`2 DirectCompilationUnits, unit_or_namespace SyntaxUsesUnit, String prev_path)
   в PascalABCCompiler.Compiler.Compile() System.IndexOutOfRangeException: Индекс находился вне границ массива.
   в PascalABCCompiler.TreeConverter.syntax_tree_visitor.visit(statement_list _statement_list)
   в PascalABCCompiler.TreeConverter.syntax_tree_visitor.convert_strong(statement st)
   в PascalABCCompiler.TreeConverter.syntax_tree_visitor.visit_program_code(statement_list program_code)
   в PascalABCCompiler.TreeConverter.syntax_tree_visitor.visit(block _block)
   в PascalABCCompiler.TreeConverter.syntax_tree_visitor.visit(program_module _program_module)
   в PascalABCCompiler.TreeConverter.SyntaxTreeToSemanticTreeConverter.CompileInterface(compilation_unit SyntaxUnit, unit_node_list UsedUnits, List`1 ErrorsList, List`1 WarningsList, SyntaxError parser_error, Hashtable bad_nodes, using_namespace_list namespaces, Dictionary`2 docs, Boolean debug, Boolean debugging, Boolean for_intellisense, List`1 CompiledVariables)
   в PascalABCCompiler.Compiler.CompileUnit(unit_node_list Units, Dictionary`2 DirectCompilationUnits, unit_or_namespace SyntaxUsesUnit, String prev_path)
   в PascalABCCompiler.Compiler.Compile()'
```
[bug.zip](https://github.com/pascalabcnet/pascalabcnet/files/13624085/bug.zip)

**Comment by ibond84** [comment]
У меня перекомпилируется модуль и ничего не падает

**Comment by ibond84** [comment]
Потому что дата PABCSystem.pcu старше, чем ConsoleUtils.pcu. Все правильно. pcu это не dll-ки, они только для кеширования дерева

**Comment by SunSerega** [comment]
У меня падает на сборке, созданной 1 декабря.

**Comment by miks1965** [comment]
Ну это всегда падало. Надо перекомпилировать все pcu

**Comment by SunSerega** [comment]
Скорее всего проблема в том что после какого то изменения формата .pcu файла - забыли увеличить его версию, поэтому после обновления старый .pcu остался валидным, но при чтении отвалился.

Но есть подозрение что это не единственная причина - эта issue давно назревала, у @samuraiGH только сейчас наконец получилось стабильно поймать.
Интересно что у него вроде как такое постоянно время от времени случается, хотя я никогда не замечал.

Поэтому стоит внимательнее изучить этот .pcu . Если есть версия компилятора на которой он работает, а затем в следующей что то поменялось, но номер формата .pcu забыли увеличить - можно просто кинуть ссылку на комит и закрыть. Но надежда на то что дело не в этом.

**Comment by miks1965** [comment]
Ну поизучайте этот вопрос. Я как то с самого начала считал, что pcu несовместимы и всё падает

**Comment by SunSerega** [comment]
Нет, несовместимость .pcu всегда вызывала перекомпиляцию модуля (если соответствующий .pas файл найдёт).

**Comment by miks1965** [comment]
Не уверен. У школьников падает когда старый pcu в папке. Ну поразбирайтесь почему вдруг эта ошибка вылезает

**Comment by SunSerega** [comment]
То есть получается не только у @samuraiGH это воспроизводится - вы тоже такую пакость видели значит.
Если у вас воспроизведётся - попробуйте тоже поймать архив со исходными и .pcu файлами, с которыми падает вместо того чтобы пересоздать .pcu
Эта проблема плавающая, поэтому мало примеров не будет

**Comment by ibond84** [comment]
Как раз если версию PCU не поменять, то падает. Значит, надо перед каждым релизом увеличивать версию формата PCU. И это уже не формат PCU, а версии стандартных модулей. Либо завести отдельное поле Build

**Comment by miks1965** [comment]
Ну это очень хорошая идея. Поле Build мне вообще нравится. Оно же будет версией формата pcu. Всё равно pcu одних версий не могут использоваться в других версиях
