### ISSUE TITLE
sh _RebuildReleaseAndRunTests.sh - error

### ISSUE THREAD

**Issue by sergrych** [pascalabcnet/pascalabcnet#2996]
на борту mac os - 10.15.7
при запуске sh _RebuildReleaseAndRunTests.sh
вылетает в
	Native Crash Reporting
=================================================================
Got a abrt while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries
used by your application.

подробней в логе, прикрепил
[log.txt](https://github.com/pascalabcnet/pascalabcnet/files/13783996/log.txt)

**Comment by SunSerega** [comment]
Уже известная проблема: https://github.com/pascalabcnet/pascalabcnet/issues/2890

**Comment by miks1965** [comment]
А какая версия mono в MacOs?

В mono Linux всё собирается

**Comment by SunSerega** [comment]
> В mono Linux всё собирается

В GitHub Actions которые линуксе не собирается (и поэтому их давно вырубили, оставили только те что на windows).
А версия в log.txt показывается в куче мест.

**Comment by SunSerega** [comment]
@miks1965 скажите сразу какая у вас версия mono, под которой собирается, я попробую её в GitHub Actions поставить.

**Comment by miks1965** [comment]
Не помню. Самая последняя, которая на сайте моно

**Comment by SunSerega** [comment]
Тестирую на арче с mono 6.12.0.205-1 (только всё обновил)

Падает так же на тесте с явной реализацией интерфейса:
```
Compile file /home/sun_linux/0Prog/pascalabcnet/TestSuite/explicitinterface10.pas
requested token for MethodOnTypeBuilderInst
```

**Comment by SunSerega** [comment]
Кхм только этого другой файл, у автора issue там explicitinterface13 - почему то в самом начале тестирования.
Это наверн как уже система файлы перечисляет.
Ну, тем не менее - ошибка с последним mono есть. В #2890 я сказал что проблема только если интерфейс паскалевский. Если закрыть его чтобы получить готовый `System.Type` и использовать его - должно работать.

**Comment by miks1965** [comment]
Да, явная реализация интерфейсов в mono не работает. Мы не углублялись, почему.

Уберите этот тест из тестов в Линуксе.

**Comment by SunSerega** [comment]
Нет ну если найти версию mono в которой это небыло проблемой - это уже мощно будет, можно будет хотя бы запустить тесты в GitHub Actions для линукса...

**Comment by miks1965** [comment]
На самой последней версии моно есть этот косяк

**Comment by miks1965** [comment]
После того как убрали этот тест - проект под mac os собрался?

Issue закрывать?
