### ISSUE TITLE
 Arr(1,2,3)[^2] - ошибка компиляции

### ISSUE THREAD

**Issue by miks1965** [pascalabcnet/pascalabcnet#2998]
```
begin
  Arr(1,2,3)[^2];
end.
```
Program1.pas(8) : Ожидалось имя процедуры или функции

Странная ошибка

**Comment by ibond84** [comment]
Все правильно. Выражения как операторы в паскале недопустимы

**Comment by ibond84** [comment]
Только вызовы функций и операторы

**Comment by SunSerega** [comment]
Код действительно неправильный, но ошибка таки ничего не объясняет.

На самом деле проблема в том что в паскале выражение (что-то с результатом) не может существовать отдельно - оно должно что-то выполнять или быть куда-то присвоено.

Именно об этом должна говорит ошибка.
И так же в других случаях:
```
## 3 + 5; //Ошибка: Встречено '+', а ожидалось ':'
```
```
## 'abc'; //Ошибка: Встречено ';', а ожидалось '.'
```
Тут вообще выводит рандомные ошибки синтаксиса, вместо того чтобы объяснить в чём на самом деле проблемма.

В процессе обучения такие ошибки это вообще ужас, после них программист учится делать костыли а не разбираться что не так.

**Comment by ibond84** [comment]
Причем тут ожидалось. Это семантическая ошибка. Надо просто выдавать Ожидался оператор или вызов процедуры/функции

**Comment by miks1965** [comment]
Да, точно
