### ISSUE TITLE
Регрессии после смены кодировки (8826c33)

### ISSUE THREAD

**Issue by ulysses4ever** [pascalabcnet/pascalabcnet#30]
Нашёлся тест, который больше не компилируется: `BookWormABCNET.pas`, а именно

    arr,work: array ['а'..'я'] of integer;

пишет: ожидался порядковый тип.

**Comment by ulysses4ever** [comment]
Ещё: `Case3.pas` (нельзя преобразовать тип string к char).

**Comment by ulysses4ever** [comment]
Что-то непонятное происходит: тот же самый `Char2.pas`, который не компилируется компилятором из репозитория, отлично компилируется с помощью среды, скаченной с сайта.

**Comment by ibond84** [comment]
Консольный компилятор не поддерживает автоопределение кодировки файла. Проблемой занимаемся

**Comment by ulysses4ever** [comment]
А, круто, а то я собрался тупо повписывать cp1251-символы вместо юникодных в эти тесты. Тогда не буду, наверное. Была ещё идея откатиться назад и исключить файлы тестов при смене кодировок.

**Comment by ibond84** [comment]
Исправлено.
