### ISSUE TITLE
[Console compiler] Support "response files"

### ISSUE THREAD

**Issue by iahung2** [pascalabcnet/pascalabcnet#3034]
On some systems (such as older UNIX systems and certain Windows variants) command-lines have relatively limited lengths. Windows compilers therefore support "response files". These files are mentioned on the command-line (using the "@file") syntax. The compiler reads these files and inserts the contents into argv, thereby working around the command-line length limits.

https://stackoverflow.com/questions/61799140/is-it-possible-to-put-a-bunch-of-wno-gcc-flags-into-a-file-and-reference-th

**Comment by miks1965** [comment]
Ничего не понял. Что, когда и где не работает?

Issue построен неправильно - говорится, что где то что-то не работает без какой то возможности, но ничего не говорится про PascalABC.NET

**Comment by ibond84** [comment]
Это хотелки

**Comment by ibond84** [comment]
>The maximum command line length for the CreateProcess function is 32767 characters.
