### ISSUE TITLE
Расширить типы в case на константные tuples

### ISSUE THREAD

**Issue by miks1965** [pascalabcnet/pascalabcnet#307]
Расширить типы в case на объекты и на tuples

**Comment by ibond84** [comment]
В case-ах всегда константы и там проверяется, не дублируются ли константы. Иначе смысл case-ов пропадает. Или вы предлагаете ограничить только константными туплами и массивами?

**Comment by miks1965** [comment]
Да, ограничить константными. Я вообще имел в виду только Tuples. Как сделать массивы - не знаю

**Comment by ibond84** [comment]
Собрался реализовывать, а тут такое
```
begin
  var t := (1,2);
  case t of
  (1,2): writeln(2);
  (2,3): writeln(3);
  end;
end.
```

Синтаксическая ошибка :  Встречено ',', а ожидалось ')'

А в case разве не expression?

**Comment by ibond84** [comment]
думаю, это задача pattern matching-a. а case останется какой есть.

**Comment by miks1965** [comment]
Да. Закрываю.
