### ISSUE TITLE
Очередная проблема с .NET 4.0 на XP

### ISSUE THREAD

**Issue by spectatorBH** [pascalabcnet/pascalabcnet#3088]
Решил проверить свежую версию (3.9.0.3454 от 07.04.2024) на WinXP, перекомпилировав стандартную библиотеку:

`PABCSystem.pas(4278) : Empty не объявлен в типе array`

```
ObjectToStringUtils.ContentsToString(o: Object; prev: Stack<object>; res: TextWriter);
...
val := mi.Invoke(o, &Array.Empty&<object>);
...
```

**Comment by SunSerega** [comment]
А, ну да...
Если заменить на `new object[0]` - что то ещё падает?

**Comment by SunSerega** [comment]
Ошибка `PCUReader`-а - это обычно так потому что вы откомпилировали зависимый, но не зависящий от него модуль. К примеру, что с `PABCExtensions`?

> Это уже известный баг?

Да, я всегда удаляю дубль в своих issue... Хотя надо бы исправить конечно.

**Comment by SunSerega** [comment]
Кинул пулл
