### ISSUE TITLE
Плохое сообщение об ошибке

### ISSUE THREAD

**Issue by miks1965** [pascalabcnet/pascalabcnet#309]
Сделать хорошее сообщение.
```
function fib(n: integer) := n<2 ? n : fib(n-1) + fib(n-2); 
begin
end.
```

**Comment by cergean** [comment]
А оно в таком виде вообще должно работать? Вроде ничего криминального нет, обычная рекурсия

**Comment by SunSerega** [comment]
@cergean да, интересно, я тоже не сразу понял, но посмотри на тип возвращающего значения:
Выбор идёт между `integer` и функцией принимающей ничего(но использующий как бы внешнюю переменную `n`) и возвращающей какой то результат, а процедуры и функции имеют больший приоритет в случаях выбора.
