### ISSUE TITLE
После компиляции и запуска приложения выскакивает ошибка

### ISSUE THREAD

**Issue by mokeev1995** [pascalabcnet/pascalabcnet#31]
Файл 
```
Compiler/RemoteCompiler.cs
```
Here it is:
![screenshot 3](https://cloud.githubusercontent.com/assets/8450876/12026298/09cc4c20-adc9-11e5-8757-6c126a58857c.png)

Visual Studio 2015 Update 1 Enterprise + ReSharper 10.1

**Comment by mokeev1995** [comment]
на сколько я понял, необходима предварительная компиляция самого компилятора, почему же она не включена в зависимость сборки приложения?

**Comment by ibond84** [comment]
Проект pabcnetc и VisualPascalABCNET не зависят друг от друга, поэтому перед первым использованием надо делать Rebuild.

**Comment by mokeev1995** [comment]
Ребилд делал, собственно. всего солюшена. ну, если из студии делать ребилд -- то всё крашится с куууучей ошибок.
![screenshot 3](https://cloud.githubusercontent.com/assets/8450876/12031605/1c0bf2ae-ae1f-11e5-9a48-26a2e36d7bbb.png)

**Comment by ibond84** [comment]
А Clean не помогает?

**Comment by mokeev1995** [comment]
нет, там проблемы с зависимостями в проекте. 
![screenshot 4](https://cloud.githubusercontent.com/assets/8450876/12034684/90d53b24-ae45-11e5-8b6e-468c88d08a6f.png)

**Comment by mokeev1995** [comment]
@ibond84 может хорошая идея была бы сделать зависимость не на DLL, а на проект, который бы билдился вместе с билдом самой программы?

**Comment by ibond84** [comment]
Это сторонние dll и они почти никогда не меняются.

**Comment by ibond84** [comment]
Какие-то баги студии. Студия ищет подключаемые сборки в следующем порядке:

    Files from the current project – indicated by {CandidateAssemblyFiles}.
    $(ReferencePath) property that comes from .user/targets file.
    %(HintPath) metadata indicated by reference item.
    Target framework directory.
    Directories found in registry that uses AssemblyFoldersEx Registration.
    Registered assembly folders, indicated by {AssemblyFolders}.
    $(OutputPath) or $(OutDir)
    GAC
http://stackoverflow.com/questions/1882038/hintpath-vs-referencepath-in-visual-studio

А OutputPath у нас /bin. Я переподключил эти dll, чтобы добавился HintPath.
