### ISSUE TITLE
uses a in 'f\g/a.pas'; можно - ужас

### ISSUE THREAD

**Issue by miks1965** [pascalabcnet/pascalabcnet#3116]
![изображение](https://github.com/pascalabcnet/pascalabcnet/assets/10325391/c18921eb-ceba-4739-aaed-51781d0598fd)

Всё игнорируется, берется только имя файла

**Comment by SunSerega** [comment]
У вас включена опция "Генерировать выходные файлы в папку"?

Я ещё давно писал о том что это глупость, оттуда .pcu брать, когда включено - вы вроде сказали лучше оставить как есть.

**Comment by SunSerega** [comment]
Сейчас дошёл проверить - там и правда какая то жесть твориться. Даже без .pcu файла, и даже если .pas файл в той же папке - это всё равно работает. Пойду в компиляторе копаться...

P.S. @miks1965 проверьте и примите #3111 пожалуйста. Иначе с исправлением данной issue будут лютые конфликты.
