### ISSUE TITLE
Объявление переменной в `yield` функции не может вызвать одноимённую функцию

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#3125]
```
function V(n: byte) := 0;

function f1: sequence of integer;
begin
  //Ошибка: Ожидалось имя процедуры или функции
  var v := V(0);
  // Если закомментировать эту строчку - предыдущая строчка работает
  yield v;
end;

begin
  
end.
```

**Comment by ibond84** [comment]
Тут еще проблема, что компиляция многопроходная

**Comment by ibond84** [comment]
Ошибка в этой строчке (RenameSameBlockLocalVarsVisitor). Вроде как не надо заменять initial_value, так как var a := a вообще не должно компилироваться. А 2103 компилируется и без этой строчки

ProcessNode(newVS.inital_value); // SSM 10.06.2020 #2103

**Comment by ibond84** [comment]
В BlockNamesStack теперь добавляется после обхода inital_value. Это вроде исправило ошибку и логичнее. 
```
ProcessNode(newVS.inital_value); // SSM 10.06.2020 #2103
            foreach (var key in newNameCache.Keys)
                BlockNamesStack[CurrentLevel][key] = newNameCache[key];
```
