### ISSUE TITLE
type MyEnum = (One, Two = 2, Three); не работает

### ISSUE THREAD

**Issue by miks1965** [pascalabcnet/pascalabcnet#3157]
```
type MyEnum = (One, Two = 2, Three);
```
RosettaEnum.pas(3) : Необходимо явно указать значение константы перечислимого типа

**Comment by ibond84** [comment]
A зачем это должно работать?

**Comment by miks1965** [comment]
Честно сказать, особо незачем. В C++ просто следующие константы автоматически инкрементировались на 1

**Comment by ibond84** [comment]
А что с этим например делать?

type MyEnum = (One, Two = 2, Three, Four=3);

**Comment by miks1965** [comment]
Честно - чёрт его знает

**Comment by miks1965** [comment]
Закрывайте наверное - ну его
