### ISSUE TITLE
BigInteger(1) / 2 в режиме ускорения имеет тип BigInteger а в обычном - real

### ISSUE THREAD

**Issue by miks1965** [pascalabcnet/pascalabcnet#3172]
```
begin
  var b := BigInteger(1);
  var b1 := b / 2;
  Print(TypeName(b1));
end.
```

**Comment by SunSerega** [comment]
Можно суффикс использовать, так проще:
```
## TypeName(1bi / 2).Print;
```

**Comment by SunSerega** [comment]
@ibond84 ой вы невовремя начали баги исправлять - тут небольшой Армагеддон после переименования проекта

**Comment by miks1965** [comment]
Ibond - всегда вовремя. Этот застарелый баг давно надо исправить. 

А проект уже пересобирается
