### ISSUE TITLE
Неправильный вывод массива объектов - без []

### ISSUE THREAD

**Issue by miks1965** [pascalabcnet/pascalabcnet#3181]
```pascal
begin
  var a: array of integer;
  a := Arr(1,2,3);
  Println(a);
  var a1: array of object;
  a1 := new object[3](1,2,3);
  Println(a1);
end.
```
Вывод
```
[1,2,3]
1 2 3

```
Вероятно это случилось в новом ObjectToString

**Comment by SunSerega** [comment]
Вы в Println принимаете `params a: array of object`. Только недавно сами постили пост в канале об этом крайнем случае...

**Comment by miks1965** [comment]
А, да - прикольно :)

**Comment by SunSerega** [comment]
Вообще можно было бы ввести паскалевский атрибут на этот случай, запрещающий передавать массивы как-есть в определённый метод - в том числе `Println` и `Writeln`. Чтобы их всегда оборачивало в ещё 1 массив.
