### ISSUE TITLE
About 64-bit

### ISSUE THREAD

**Issue by lianquke** [pascalabcnet/pascalabcnet#3199]
Hello,

Thank you for providing such an excellent tool. I am a new user, and I have a question regarding 64-bit programs. I am a Windows user, and it seems that the programs compiled with the built-in compiler are all 32-bit. I haven't found any settings to compile 64-bit programs. If there is a way to do this, please let me know. Thank you.

**Comment by SunSerega** [comment]
Btw, there are:
- Discussions: https://github.com/pascalabcnet/pascalabcnet/discussions
- Forum: https://forum.mmcs.sfedu.ru/c/pascalabcnet/10
- Telegram group, with a "newcomer help" channel (this is the most active, tho also overwhelmingly in Russian): https://t.me/PABCofficial/8279

Meanwhile, issues in this repo are meant for bugs.
