### ISSUE TITLE
Building PascalABC.NET in Ubuntu 22.04

### ISSUE THREAD

**Issue by dvyavna** [pascalabcnet/pascalabcnet#3201]
Compiled: 43/43
Executing the native assembler: "as" --64  -o /tmp/mono_aot_6BXmAp.o /tmp/mono_aot_6BXmAp
Executing the native linker: "ld" -shared -o /home/yavna/compile/pascalabcnet/bin/Errors.dll.so.tmp  /tmp/mono_aot_6BXmAp.o 
JIT time: 6 ms, Generation time: 1 ms, Assembly+Link time: 11 ms.
Загружаю ядро...
PascalABCCompiler.Core v3.10.0.3537
Copyright (c) 2005-2024 by Ivan Bondarev, Stanislav Mikhalkovich
OK 44,736ms
Предупреждение: ни один парсер не подключен!
Подключены преобразования: Optimizer; 
Компилирую сборку RebuildStandartModulesMono.pas...
[1]CompilationStarting RebuildStandartModulesMono.pas...
[2]CompilationFinished RebuildStandartModulesMono.pas...
Ready.
[0]Не могу выбрать подходящий парсер для файла 'RebuildStandartModulesMono.pas'

**Comment by dvyavna** [comment]
Сборка проходит без проблем, но тесты не запускаются. Аналогично при попытке запустить компилятор жалуется на парсер:
yavna@denis-inspiron3521:~/compile/pascalabcnet/bin$ ./pabcnetc hello.pas 
Загружаю ядро...
PascalABCCompiler.Core v3.10.0.3537
Copyright (c) 2005-2024 by Ivan Bondarev, Stanislav Mikhalkovich
OK 51,539ms
Предупреждение: ни один парсер не подключен!
Подключены преобразования: Optimizer; 
Компилирую сборку hello.pas...
[0]Не могу выбрать подходящий парсер для файла 'hello.pas'

То же самое происходит и в IDE. Там ещё скрипт bin/PascalABCNET не является исполняемым и запускает не создаваемый при сборке PascalABCNETLinux.exe, а PascalABCNET.exe...
![Screenshot_abcpascal](https://github.com/user-attachments/assets/a1631d72-9dfa-49da-93b0-9830dc201e88)

**Comment by SunSerega** [comment]
Не давно были изменения в загрузке языковых плагинов, были некоторые проблемы где плагин-ядро с языком самого паскаля не подгружался. Надо сделать какой то более подробный вывод чтобы понять что у него там не получается...
