### ISSUE TITLE
Переход на Visual Studio 2022

### ISSUE THREAD

**Issue by keyboardcrash32** [pascalabcnet/pascalabcnet#3208]
Visual Studio 2022 поддерживается? Если нет, то планируете ли вы перейти на разработку на Visual Studio 2022?

**Comment by SunSerega** [comment]
Некоторые проекты всё ещё должны быть на .Net 4.0, потому что это последняя версия которую поддерживает WinXP - всё ещё стоящая на многих российских школах. Но они переходят на линукс и в какой то момент поддержку .Net 4.0 можно будет наконец то дропнуть...

Пока что можно поставить VS2019 и VS2022 поверх друг друга, но при этом VS2019 не использовать - VS2022 всё открывает и компилирует без проблем.
