### ISSUE TITLE
operator := не вызывается из dll

### ISSUE THREAD

**Issue by miks1965** [pascalabcnet/pascalabcnet#3223]
dll такая

```pascal
library lib2;

type
  MyS<T> = record
    hs: HashSet<T> ;
    static function operator:= (my: MyS<T>; my1: MyS<T>): MyS<T>;
    begin
      Println(':=');
      my.hs := my1.hs.ToHashSet;
    end;
  end;
end.
```

а основной файл такой

```
{$reference lib2.dll}

begin
  var s1,s2: MyS<integer>;
  s1 := s2;
end.
```

Генерируется обычное присваивание ссылок

**Comment by samuraiGH** [comment]
А IL вообще позволяет перегружать оператор присваивания?

Если нет, то в общем-то это поведение правильное. Мы конечно может сделать костыли с атрибутами допустим, но для других .NET языков они работать не будут, что не верно я считаю

**Comment by miks1965** [comment]
Это для паскалевских множеств.
