### ISSUE TITLE
Неправильная компиляция кода с override

### ISSUE THREAD

**Issue by sanyarnd** [pascalabcnet/pascalabcnet#325]
[Файл проекта](http://rgho.st/6pBmbvQBx)

Компилятор выдает следующий код (dll развернул dotPeek'ом):

```
using Robocode;

namespace PABCRobocode
{
  public class TestRobot : Robot
  {
    static TestRobot()
    {
      PABCSystem.PABCSystem.\u0024_Init_();
    }

    public TestRobot()
    {
      this.\u0024Init\u0024();
      base.\u002Ector();
    }

    public void \u0024Init\u0024()
    {
    }

    public virtual void Run()  <------- это баг
    {
    }
  }
}
```

**Comment by ibond84** [comment]
Все правильно компилируется. Это ошибка в dotPeek. В IL нет override, а есть только virtual и newslot (reintroduce). Метод, помеченный virtual, автоматически становится override, если в базовом классе есть такой же метод.

**Comment by sanyarnd** [comment]
Спасибо за прояснение!
