### ISSUE TITLE
Убрать подключение PABCSystem при создании своих dll

### ISSUE THREAD

**Issue by sanyarnd** [pascalabcnet/pascalabcnet#326]
Есть ли возможность не включать при компиляции в код dll весь модуль PABCSystem?
Для примера, вот одинаковые модули скомпилированные на C# и PascalABC.NET.

![2016-12-27_160622](https://cloud.githubusercontent.com/assets/6544384/21500964/0404505c-cc55-11e6-8dcb-2c9f7806c63d.png)

**Comment by ibond84** [comment]
Ключа компиляции нет, но можно воспользоваться таким трюком:
Создать в папке проекта файл PABCSystem.pas со следующим содержимым
```
unit PABCSystem;

{$savepcu false}

interface

implementation

end.
```

**Comment by sanyarnd** [comment]
Ок, а такое как побороть:

() : Ошибка чтения PCU файла 'C:\Program Files (x86)\PascalABC.NET\Lib\__RedirectIOMode.pcu'

**Comment by ibond84** [comment]
этот issue закрываю. новый issue https://github.com/pascalabcnet/pascalabcnet/issues/330
