### ISSUE TITLE
function CompareToTup3<T1>(v1: (T1,T2); v2: (T1,T2)) := True; - неверное сообщение об ошибке

### ISSUE THREAD

**Issue by miks1965** [pascalabcnet/pascalabcnet#332]
```
function CompareToTup3<T1>(v1: (T1,T2); v2: (T1,T2)) := True;
begin
  
end.
```
Program1.pas(1) : Повторно объявленный идентификатор T1 - странное сообщение об ошибке

**Comment by ibond84** [comment]
Все правильно. (T1,T2) рассматривается здесь уже как перечислимый тип (так как T2 не найден), а T1 уже описан в области видимости

**Comment by miks1965** [comment]
Ой какая классная неошибка! Точно! Закрываю!
