### ISSUE TITLE
Реализовать возможность переименовывать стандартный класс - пространство имён

### ISSUE THREAD

**Issue by miks1965** [pascalabcnet/pascalabcnet#336]
Видимо, с помощью директив компилятора

**Comment by ibond84** [comment]
а что значит "стандартный класс - пространство имён"? есть класс-обертка над глобальными функциями модуля, есть пространство имен, в котором содержится этот класс. это разные вещи.

**Comment by miks1965** [comment]
По идее, с помощью директив компилятора надо иметь возможность устанавливать и то и то.

**Comment by miks1965** [comment]
program имя и так переименовывает - по крайней мере, один класс :)

**Comment by miks1965** [comment]
Закрываю. Не вижу особой практической необходимости. Может, кто скажет веские причины - снова откроем

**Comment by YashiroShow** [comment]
Я так полагаю, всё ниже перечисленное относится к пространствам имён. На данном этапе при компиляции библиотек есть проблема. Если подключать внутри библиотеки, например, System.IO, то при подключении этой библиотеки уже в программе, где тоже используется System.IO, будет беда - в System.IO окажутся только те методы, которые мы использовали на момент компиляции библиотеки. Я так однажды хотел сделать dll для исключений одного конкретного приложения, и столкнулся с этой проблемой, таки потом пришлось переделывать в модуль. Не спрашивайте, почему хотел именно DLL :)
