### ISSUE TITLE
Изменение x в foreach. Должна быть ошибка

### ISSUE THREAD

**Issue by miks1965** [pascalabcnet/pascalabcnet#338]
```
begin
  var a := Arr(1,2,3);
  foreach var x in a do
  begin
    x := x;
    Print(x);
  end;
end.
```
Из-за оптимизации ее нет. Проверять раньше специальным визитором

**Comment by ibond84** [comment]
Ну, убрать оптимизацию. Там неразрешимая задача: на синтаксическом уровне нельзя запретить передачу x по ссылке.

**Comment by miks1965** [comment]
Да, надо убрать оптимизацию. Уберу.
