### ISSUE TITLE
operator+<T1,T2,T3,T4> падает

### ISSUE THREAD

**Issue by miks1965** [pascalabcnet/pascalabcnet#35]
function operator+<T1,T2,T3,T4>(a: System.Tuple<T1,T2>; b: System.Tuple<T3,T4>): System.Tuple<T1,T2,T3,T4>;
begin
  Result := Rec(a.Item1,a.Item2,b.Item1,b.Item2)
end;

begin
  Print(Rec(1,2)+Rec(3,4));
end.

**Comment by ibond84** [comment]
Не падает. Просто выдает корректное сообщение об ошибке:
Перегруженная операция должна быть статической функцией

**Comment by ibond84** [comment]
<script>alert("ok")</script>
