### ISSUE TITLE
Добавте вертикальные линии у блока кода

### ISSUE THREAD

**Issue by EvolutionPixels** [pascalabcnet/pascalabcnet#351]
Вот ссылка на пример кода с вертикальной визуальной линией - http://imgur.com/a/2Lc9S
С ней код будет читаться лучше.

**Comment by miks1965** [comment]
Компонент редактора это не позволяет

**Comment by EvolutionPixels** [comment]
Жаль что нельзя. А ведь с ним было бы проще.
