### ISSUE TITLE
Почему редактор кода не умеет форматировать в табы вместо пробелов по нажатию клавиши TAB?

### ISSUE THREAD

**Issue by EvolutionPixels** [pascalabcnet/pascalabcnet#354]
Я когда пытаюсь работать с кодом в редакторе, то таб не работает.
А при попытке форматировать существующий код, он преобразует все в пробелы где отступы кода.
Не очень удобно работать с кодом когда нужно постоянно удалять пробелы нескольким нажатием клавиши (backspace) <---

Добавте возможность нормального форманирования 4 пробелов в таб.
И замену на таб как такового при попытке форматировать код.

**Comment by ibond84** [comment]
>Не очень удобно работать с кодом когда нужно постоянно удалять пробелы нескольким нажатием клавиши (backspace)

Alt+Backspace удаляет весь таб из пробелов.

**Comment by EvolutionPixels** [comment]
А как на счет того что когда нажимаешь TAB то вместо него пробелы? Как быть?
Мне нужен настоящий таб.
И то же самое и с форматированием кода.

**Comment by miks1965** [comment]
Закрываем. Просим аналогичными вопросами не засорять Issues и писать на форум проекта.
