### ISSUE TITLE
При попытке переключится в меню настроек с пункта меню на другой пункт редактор несколько секунд думает и после переключается

### ISSUE THREAD

**Issue by EvolutionPixels** [pascalabcnet/pascalabcnet#355]
Версия Net Framework используется последняя на данный момент, и та что шла в комплекте с вашей ide.

**Comment by ibond84** [comment]
Ну это проблемы Windows. Во вкладке загружается список шрифтов. Поэтому приходится первый раз чуток подождать

**Comment by EvolutionPixels** [comment]
Это проиходит и после того как все прогрузилось, но менее заметно. Но все таки есть.
