### ISSUE TITLE
Добавление нового типа присваивания

### ISSUE THREAD

**Issue by EvolutionPixels** [pascalabcnet/pascalabcnet#356]
Что если добавить новый тип присваивания = вместо := а вместо навенства = поменять на == ?
Так код будет читаться легче и станет более приближен к современным языкам программирования.

Плохой вид присваивания:
```pascal
var a: integer := 12;
```
Лучше вот так:
```pascal
var a: integer = 12;
```
А еще лучше вот так:
```pascal
var integer a = 12;
```
или
```pascal
integer a = 12;
```

**Comment by ibond84** [comment]
это уже C получится какой-то, а не паскаль

```var a: integer = 12;```

в паскале = используется только для констант, а для присваивания выделен специальный символ :=

**Comment by EvolutionPixels** [comment]
Хорошо больше не буду про это просить.

Мне просто не понравилось то как нужно присваивать через := а не =.
