### ISSUE TITLE
i.ToString  в лямбде неправильно работает

### ISSUE THREAD

**Issue by miks1965** [pascalabcnet/pascalabcnet#360]
```
begin
    writeln(2);
    Range(1,100).Select(i->i.ToString).Println;
end.
```

**Comment by ibond84** [comment]
Ну, инстанцируется делегатом i.ToString. Ошибки не вижу. Раз нет разруливания спорной ситуации в пользу делегата (у нас нет @ для делегатов), то надо отдавать предпочтение делегату.

**Comment by miks1965** [comment]
У нас же если функция без параметров, то всегда в пользу вызова функции предпочтение.
```
var s := i.ToString;
```
- тут же вызов метода происходит!
