### ISSUE TITLE
Дополнения в библиотеки

### ISSUE THREAD

**Issue by miks1965** [pascalabcnet/pascalabcnet#362]
#Здесь будут описываться желательные дополнения в библиотеки PascalABC.NET. 
По мере реализации этих дополнений они будут убираться из данного текста.

1. Стандартная функция генерации последовательности всех перестановок или, возможно, функция NextPermutation.

**Comment by EvolutionPixels** [comment]
4. Время жизни переменной или функции.

**Comment by AlexRnD61** [comment]
Для матрицы - a.Elements, возвращающая одномерную последовательность (i,j,a[i,j]) - так вроде же сделали ElementsWithIndexes ?

**Comment by miks1965** [comment]
Закрыл как неиспользуемый
