### ISSUE TITLE
Readln EOF infinite loop

### ISSUE THREAD

**Issue by andrew-boyarshin** [pascalabcnet/pascalabcnet#369]
[PABCSystem.pas#L4483](https://github.com/pascalabcnet/pascalabcnet/blob/master/bin/Lib/PABCSystem.pas#L4483)

## English
If input stream is redirected, Readln (parameterless) incorrectly handles EOF (hangs in infinite loop). It is better to also check for end of stream (```read_symbol < 0``` when ```Console.IsInputRedirected```). Hangs testing systems without deadlocks implemented. The workaround was to append ```\n``` to input string, although that seems hackish.

## Русский (Russian)
Readln (без параметров) не обрабатывает конец перенаправленного потока ввода (вешается в бесконечном цикле). Стоит добавить проверку на значение ```read_symbol < 0``` если поток ввода перенаправлен (```Console.IsInputRedirected```). Не все тестировщики умеют прибивать по таймауту программы. Временным решением стало добавление ```\n``` в конец входного потока.

**Comment by miks1965** [comment]
Непонятный Issue. Нельзя ли расшифровать подробнее? Что такое перенаправленный поток ввода - приведите пример?

**Comment by andrew-boyarshin** [comment]
```Console.SetIn``` для потока. Полагаю, что из файла без конечной пустой строки также будет infinite loop.

**Comment by miks1965** [comment]
И всё-таки подробнее. Приведите пример полной программы, которая не будет работать. И - Вы же говорили, что Readln не работает, а сейчас говорите про какой-то Console.SetIn

**Comment by andrew-boyarshin** [comment]
```
uses System;
uses System.IO;
begin
    var a, b: int64;
    Console.SetIn(new StringReader('1 2' + NewLine));
    readln(a, b);
    writeln(a + b);
end.
```

Без NewLine вечный цикл.

**Comment by andrew-boyarshin** [comment]
Аналогично из файла без пустой конечной строки:
```pascal
uses System;
uses System.IO;
begin
    var a, b: int64;
    Console.SetIn(new StreamReader('out1.txt'));
    readln(a, b);
    writeln(a + b);
end.
```

**Comment by miks1965** [comment]
```
uses System;
uses System.IO;
begin
    var a, b: int64;
    Console.SetIn(new StringReader('1 2' + NewLine));
    readln(a, b);
    writeln(a + b);
end.
```
После запуска этой программы оболочка дестабилизируется так, что приходится её закрывать. Нельзя ли сделать, чтобы оболочку можно было приводить в рабочее состояние без перезагрузки?

**Comment by vkopichenko** [comment]
Вот ещё довод в пользу решения этой проблемы.

source.pas (https://ideone.com/itdAqx):
```
var
  k: longint;
begin
  readln(k);
  writeln(2*k);
end.
```
Запускаем с перенаправлением ввода-вывода:

> source.exe <input.txt >output.txt

Если в файле input.txt было только число без следующего за ним перевода строки, то программа, скомпилированная Pascal ABC, зависнет навечно, а при компиляции через Turbo или Free Pascal - завершится успешным выводом в output.txt правильного ответа.

Это неожиданное отличие в поведении Pascal ABC сильно затрудняет автоматизированное тестирование написанных на нём решений.
Например, мы недавно добавили поддержку компилятора Pascal ABC на образовательном портале http://dl.gsu.by, но оказалось, что теперь в некоторых задачах не проходят по времени авторские решения.
В таких случаях помогает вручную добавить недостающие переводы строки в конце проблемных тестов. Но вручную так мигрировать множество задач слишком затратно, а автоматизированно опасно, т.к. в некоторых случаях с нечисловым вводам лишний перевод строки в тестах может всё поломать.

Надеюсь проблему удастся разрешить внутри readln в Pascal ABC, приведя её в соответствие с остальными реализациями Паскаля.
Необходимо трактовать EOF точно так же как и EOL.

**Comment by vkopichenko** [comment]
Возможно, пригодится для фикса: https://stackoverflow.com/questions/6455150/how-can-i-tell-when-ive-reached-the-end-of-the-file-when-using-the-readblock-me

**Comment by vkopichenko** [comment]
Дополнительное обсуждение тут: http://forum.mmcs.sfedu.ru/t/zamechaniya-i-predlozheniya/143/303.

**Comment by miks1965** [comment]
Понятно. На основе последнего простого примера увидели и прониклись.
Пока для олимпиад в PABCSystem.pas сделайте следующую правку: вместо
```
procedure IOStandardSystem.readln;
begin
  while CurrentIOSystem.read_symbol <> END_OF_LINE_SYMBOL do;
end;
```
напишите 
```
procedure IOStandardSystem.readln;
begin
  while True do
  begin
    var sym := CurrentIOSystem.read_symbol;
    if (sym = END_OF_LINE_SYMBOL) or (sym = char(-1)) then
      exit;
  end;
end;
```

и перекомпилируйте PABCSystem, поместив pcu в Lib поверх старого

**Comment by vkopichenko** [comment]
Подтверждаю, что с версией v3.3.0.1590 проблема уже не воспроизводится.

**Comment by SunSerega** [comment]
Да, воспроизводится. Вот без лишних файлов:
```
uses System;
uses System.IO;

begin
  Console.SetIn(new StringReader('abc'));
  ReadlnString.Print;
end.
```
Если строки 4529-4539:
```
    var sb := new System.Text.StringBuilder;
    // SSM 8.04.10
    var c := char(peek()); // первый раз может быть char(-1) - это значит, что в потоке ввода ничего нет, тогда мы читаем символ
    while (c <> #13) and (c <> #10) do 
    begin
      c := read_symbol;
      if (c <> #13) and (c <> #10) then // SSM 13.12.13
        sb.Append(c);
      c := char(peek());
    end;
    x := sb.ToString;
```
Заменить на:
```
    var sb := new System.Text.StringBuilder;
    
    while true do
    begin
      var c := peek;
      if (c = 13) or (c = 10) or (c = -1) then break;
      sb += read_symbol;
    end;
    
    x := sb.ToString;
```
Должно работать.

**Comment by vkopichenko** [comment]
> Оказалось, что проблема прошла для чтения числа, но всё ещё актуальна при чтении строки:
> 
> ```
> var
>   k: string;
> begin
>   readln(k);
>   writeln(k);
> end.
> ```
> `source.exe <input.txt`
> 
> Вызов зависает, если в файле не будет перевода строки в конце.
> Другие реализации Паскаля с этим успешно справляются.

Любопытно, что даже при замене `readln` на `read` от вечного зависания избавиться не получается в данном случае.

**Comment by miks1965** [comment]
Я думаю, стоит поступить так. 
Мы вряд ли это сделаем быстро. Дело в том что ввод - это то, чем все пользуются, и совершить тут ошибку - это сущий кошмар. Поэтому у мея такое предложение. Если кто-то возьмётся исправить эту ошибку в стандартном модуле как SunSerega и ПРИЛОЖИТЬ ВСЕ ТЕСТЫ, свидетельствующие о том, что всё во всех случаях корректно работает как и раньше, то мы включим эту правку.

**Comment by miks1965** [comment]
Необходимо обеспечить по возможности более-менее полное покрытие всех комбинаций вводов: строка потом символ, целое-символ, целое с readln, потом символ, символ-строка и т.д.

То же по Shift-F9.

И из текстового файла (если затрагивает) - в частности, после Assign(input,'a.txt');

Мы однажды переделывали ввод - и допустили ошибку. Это был сущий кошмар. Поэтому из-за такого мелкого недочёта переделывать ввод даже с небольшой вероятностью что всё рухнет, - я боюсь

**Comment by vkopichenko** [comment]
Имеется в виду переделка ввода ради этой же заявки в конце 2017-го?
Если тогда аргументов о насущности и смелости хватило и частично проблема решилась, то теперь её, может, совсем чуть-чуть дожать осталось.
