### ISSUE TITLE
Dictionaries doesn't work

### ISSUE THREAD

**Issue by derit** [pascalabcnet/pascalabcnet#370]
sample code

program test;
begin

var Capital := Dict('Russia'=>'Moscow','Germany'=>'Berlin','France'=>'Paris','Italy'=>'Rom');
  Println(Capital['France'],Capital['Germany']);
end.

result error 
Program3.pas(4) : Found '>' but expected expression

**Comment by miks1965** [comment]
Это и не должно работать. Операция => у нас не определена

**Comment by derit** [comment]
how to solve this problem?

**Comment by miks1965** [comment]
```
begin
  var Capital := Dict(('Russia','Moscow'),('Germany','Berlin'),('France','Paris'),('Italy','Rom'));
  Println(Capital['France'],Capital['Germany']);
end.
```

**Comment by derit** [comment]
i look example *Dictionaries* in http://pascalabc.net/en/samples
it seems need for update

**Comment by miks1965** [comment]
Thank you! We changed this page and corrected some examples. Are you from USA?

**Comment by derit** [comment]
i'm from indonesia

2017-04-08 22:44 GMT+07:00 Mikhalkovich Stanislav <notifications@github.com>
:
