### ISSUE TITLE
Не работает вызов двух методов расширения подряд

### ISSUE THREAD

**Issue by ForNeVeR** [pascalabcnet/pascalabcnet#373]
Написал вот такую программу с двумя методами расширения, объявленными для integer:

```pascal
function integer.Print1(): integer;
begin
  write(Self);
  Result := Self;
end;

function integer.Print2(): integer;
begin
  write(Self);
  Result := Self;
end;

begin
  var i := 1;
  i.Print1().Print2();
end.
```

На строке `i.Print1().Print2();` компилятор ругается:

```
[0][15,5] main.pas: A var or const argument must be an assignable variable
```

Мне кажется, что это поведение неверное, и программа должна компилироваться. По отдельности методы расширения `i.Print1()` и `i.Print2()` вызвать можно.

У меня в загашнике есть ещё более сложный случай с вызовом двух методов расширения на результате обобщённого статического метода (`AppBuilder.Configure&<App>.UseWin32.UseDirect2D1;`), который вообще бросает internal compiler error, но давайте для начала разберём описанный выше более простой случай — вдруг он и не должен работать.

**Comment by ibond84** [comment]
Структурные типы должны передаваться по ссылке, так как внутри могут метода могут меняться поля. Поэтому точечная нотация в данном синтаксисе невозможна.

Но вы можете использовать другой синтаксис, если не хотите передавать self по ссылке и гарантируете тем самым отсутствие побочных эффектов

```
function Print1(self: integer): integer; extensionmethod;
```

**Comment by ForNeVeR** [comment]
Привет. Спасибо за ответ. Значит, действительно, как я и подозревал, всё-таки это я сам ошибся. Прошу баг в течение пары дней не закрывать — я буду дальше делать [MCVE](http://ru.stackoverflow.com/help/mcve) к своему примеру с internal compiler error.

**Comment by ForNeVeR** [comment]
Разобрался. В моём случае в программе была синтаксическая ошибка: `AppBuilder.Configure&<App>.UseWin32.UseDirect2D1` следовало записать как `AppBuilder.Configure&<App>().UseWin32().UseDirect2D1()`.

Воспроизвести проблему с ошибкой компилятора при использовании только extension-методов, написанных на PascalABC.NET не удалось, так что, наверное, корень проблемы лежит с интероперабельностью с C#: там несколько сборок, каждая из которых предоставляет один из extension-методов.

Проблему считаю не критичной (всего лишь вылетает ошибка компилятора вместо ошибки синтаксиса в каких-то запутанных сценариях), так что предлагаю на неё забить :)
