### ISSUE TITLE
yield не работает с распаковкой кортежа в переменные

### ISSUE THREAD

**Issue by miks1965** [pascalabcnet/pascalabcnet#375]
```
type
  TF=(integer,integer);

function f(a:TF):sequence of integer;
begin
  var p,q:integer;
  (p,q):=a;
  yield p;
  yield q;
end;

begin
  f((-3,5)).Println
end.
```
Причина - в проверочном узле остается старое имя т.к. он не обходится

**Comment by AlexRnD61** [comment]
Есть ли какой-нибудь прогресс в решении проблемы? Или хотя бы есть недалёкие планы этим заняться?

**Comment by miks1965** [comment]
Прогресса нет. Причина понятна - она написана. Но там нужно менять архитектурное решение. Как - непонятно. Планы заняться - несомненно, есть. В отличие от многих Issue причина понятна абсолютно. Наберитесь терпения. Плохие архитектурные решения будут провоцировать ошибки в будущем
