### ISSUE TITLE
преобразования object

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#382]
`var a:object := 5;`
`var i:integer := a;`

выдаёт ошибку нельзя преобразовать object к integer, и так с любым типом

`var i := integer(a);`

а так работает... можно и вторым способом но чаще первый удобнее, к примеру если переменная объявлена раньше...

**Comment by miks1965** [comment]
Правильно не работает. integer - наследник object, поэтому DownCast - только явным приведением типа. Это - принцип подстановки.

**Comment by SunSerega** [comment]
ну а как насчёт к примеру кортежей? или переменных процедур?

**Comment by miks1965** [comment]
Пожалуйста - дискуссии на форуме
