### ISSUE TITLE
Среда виснет var s: string := '{$';

### ISSUE THREAD

**Issue by miks1965** [pascalabcnet/pascalabcnet#393]
```
begin
  var s: string := '{$';
end.
```

**Comment by ibond84** [comment]
у меня не виснет

**Comment by miks1965** [comment]
У меня виснет зверски

**Comment by ibond84** [comment]
а, это если во внешнем процессе компилировать, виснет.

**Comment by ibond84** [comment]
ну ясно. 

if (yytext.Contains("\n"))
    Console.WriteLine("({0},{1})  {2}",tokLin,tokCol,"error: LF into directive");
