### ISSUE TITLE
min(b,255) врет

### ISSUE THREAD

**Issue by miks1965** [pascalabcnet/pascalabcnet#396]
```
begin
  var b: byte := 10;
  Print(min(b,255));
end.
```
Вызывается перегруженный min(shortint,shortint)    !
Полная ерунда! Возможно, shortint перепутали со smallint

**Comment by ibond84** [comment]
Ничего не перепутано, это у нас такой алгоритм выбора перегруженной функции...

**Comment by miks1965** [comment]
Ну, это совсем неправильно.
shortint имеет диапазон -128..127
то есть заведомо меньше, чем каждый из операндов.
Непонятна логика того, кто придумал такой алгоритм поиска перегруженной функции
