### ISSUE TITLE
Процедура, переданная как параметр, не работает в лямбде

### ISSUE THREAD

**Issue by miks1965** [pascalabcnet/pascalabcnet#398]
```
procedure p;
begin
  Print(666);
end;

procedure Cycle(p: procedure);
begin
  10.Times.ForEach(x->p()); // Всё остальное работает
end;


begin
  10.Times.ForEach(x->Write(x));
  10.Times.ForEach(x->p());
end.
```

Так работает:

```
procedure Cycle(p: procedure);
begin
  10.Times.ForEach(x->begin p() end); 
end;
```
Это не работает сахар преобразования функцию в процедуру по-видимому

**Comment by SunSerega** [comment]
прошло 2 с половиной месяца... всё ещё висит тут... ещё если есть до лямбды описанная в var процедура p то исключение не вызывается и в лямбду подставляется p из var... долго пришлось выяснять что в программе не так, исправьте  наконец пожалуйста

да, всё это у меня было внутри класса, как с общим var работать будет я не знаю
