### ISSUE TITLE
Падение компилятора  ((true,true,true)).ToString;

### ISSUE THREAD

**Issue by miks1965** [pascalabcnet/pascalabcnet#399]
```
begin
  var s := ((true,true,true)).ToString;
end.
```

**Comment by ibond84** [comment]
Проблема в парсере. dot_node.left==null у ((true,true,true)).ToString

**Comment by miks1965** [comment]
Всё гораздо серьезнее.

Проблемы у нас давние - с грамматикой. Проблема вот в этом правиле:
```
variable  : tkRoundOpen expr tkRoundClose         
```
То есть после написания круглых скобок любое выражение может выступать в качестве addressed_value. Что моментально приводит к падению не для addressed_value

Этот код тоже не работает
```
begin
  var s := (1:2).ToString;
end.
```

**Comment by ibond84** [comment]
все так же падает

**Comment by miks1965** [comment]
Попробуйте сейчас. Видимо, забыл закачать на GIT

**Comment by ibond84** [comment]
работает
