### ISSUE TITLE
-[1,2] - плохое сообщение об ошибке

### ISSUE THREAD

**Issue by miks1965** [pascalabcnet/pascalabcnet#401]
```
begin
  var s := -[1,2];
end.
```
a1.pas(2) : Неверное число параметров функции

Заодно:

```
begin
  var s := not nil;
end.
```
a1.pas(2) : Операция not не может быть применена к типу

**Comment by ibond84** [comment]
а что взамен? у nil нет типа, вот честно и не выводится имя
