### ISSUE TITLE
Падение компилятора - параметр по умолчанию в классовой процедуре

### ISSUE THREAD

**Issue by miks1965** [pascalabcnet/pascalabcnet#407]
```
type
    b = record
    end;
    a = class
      class procedure aa(i: integer; nb: ^b := nil);
      begin
      end;
    end;

   begin
     a.aa(0);
   end.
```

**Comment by ibond84** [comment]
падения не наблюдается

**Comment by SunSerega** [comment]
точно прогу скопируйте, если значение по умолчанию будет не  nil, или процедура будет не классовой - не работает... раньше такое было в любой процедуре, я помню делал так что в место массива передавал процедуре nil но уже не воспроизводит, надо просто дочистить то

P.S. терь когда я это вспомнил и потестил - так тоже компилятор падает
'''
type
    b = record
    end;
    a = class
      class procedure aa(i: integer; nb: ^b);
      begin
      end;
    end;

   begin
     a.aa(0,nil);
   end.
'''

**Comment by ibond84** [comment]
а, ну само исправилось сегодняшним коммитом после рефакторинга в генераторе кода. закрываю.
