### ISSUE TITLE
Сделать срезы матриц

### ISSUE THREAD

**Issue by miks1965** [pascalabcnet/pascalabcnet#414]
a[1:2,1:4]
a[5,:] - как одномерный массив

**Comment by AlexRnD61** [comment]
И a[:,4] - тоже как одномерный массив. Тогда a.Row() и a.Col() будут использоваться для получения последовательностей, а срезы - для получения именно массивов.
И надо определиться, как быть с массивом, определенным в виде array of array - применимы ли к нему срезы и если да, то что они должны возвращать?

**Comment by MrSpecular** [comment]
Думаю, что **array of array of T** надо рассматривать как частный случай **array of T**, где T - тип массива.

**Comment by MrSpecular** [comment]
1) Считаю, что будет логично, что любой срез матрицы **array [,...] of T** будет возвращать матрицу того же типа, но с выбранными элементами из **первой**.
2) Интуитивно понятное поведение среза **matrixName[from:to,:]**, на мой взгляд, - возврат матрицы, включающей все строки, начиная с **from** до **to**. Аналогично и для **matrixName[:, from:to]** - возврат матрицы, включающей все столбцы, начиная с **from** до **to**. И, наконец, **matrixName[from1:to1, from2:to2]** - возврат матрицы, включающей все строки, начиная с **from1** до **to1**, которые включают элементы столбцов от **from2** до **to2**.

**Comment by miks1965** [comment]
#2406
