### ISSUE TITLE
System.Nullable<T>; where T: record; - не проверяется условие на T в параметрах

### ISSUE THREAD

**Issue by miks1965** [pascalabcnet/pascalabcnet#420]
```
function DQNToNullable<T> (ff: System.Nullable<T>; v: T): System.Nullable<T>; where T: record;
begin
  Result := new System.Nullable<T>(nil,v);
end;

begin
end.
```
a2.pas(1) : Невозможно инстанцировать, так как у типа T нет конструктора без параметров с уровнем доступа public

**Comment by miks1965** [comment]
Ошибка не исправлена. Пытаюсь сделать это в системном файле - та же ошибка:

PABCSystem.pas(10697) : Невозможно инстанцировать, так как у типа T нет конструктора без параметров с уровнем доступа public

**Comment by ibond84** [comment]
А ну проблема не решаема с текущим синтаксисом. Компилятор должен обойти все параметры, чтобы найти описание метода.

Такой синтаксис мог бы решить проблему
```
function DQNToNullable<T: record>(ff: System.Nullable<T>; v: T): System.Nullable<T>;
```
Pascal-style. и where и не нужен даже. Описываем ограничитель сразу в шаблоне, а не где-то на задворках.

**Comment by ibond84** [comment]
хотя нет, это то же самое.

**Comment by ibond84** [comment]
трудно

**Comment by miks1965** [comment]
Почему не решаема? where - это вначале синтаксис. where входит в заголовок функции. Вот мы имеем весь синтаксис и начинаем разбирать семантику. А в семантике разбираем в любом порядке. Вначале - имена типов в обобщениях и сразу же - условия на них в where. А потом всё остальное.
