### ISSUE TITLE
Поправить сообщение по обновлению версии

### ISSUE THREAD

**Issue by AlexRnD61** [pascalabcnet/pascalabcnet#422]
![2017-06-09_124706](https://user-images.githubusercontent.com/28169041/26970406-f48b6c12-4d11-11e7-9fc4-95994f9e3842.jpg)
PascalABC.NET 3.2, сборка 1473 от 08.06.2017

**Comment by spectatorBH** [comment]
Желательно также сконструировать сообщение в виде:

`Вы используете версию 3.2.0.xxxx от DD.MM.YYYY`
`Более новой версии дистрибутива не обнаружено... / Обнаружена новая версия 3.2.0.уууу от DD.MM.YYYY`

или

`Вы используете самую последнюю доступную версию 3.2.0.xxxx от DD.MM.YYYY`
`Обновление не требуется. / Доступно обновление до версии 3.2.0.уууу от DD.MM.YYYY`

Т.е. чтобы в этом окне всегда была видима информация о текущей установленной версии и дате билда, вне зависимости от того есть новая версия или нет.

**Comment by AlexRnD61** [comment]
Версия билда и так видна по отдельному запросу, какой смысл повторяться? Либо версия актуальна, либо есть обновление - этого вполне достаточно. Как оно, собственно, и было.

**Comment by spectatorBH** [comment]
Смысл в том, что установленная версия и версия обновления -- это связанная информация, одно для другого является контекстом. И вообще, избыточность где-либо -- это не всегда плохо, если это оборачивается реальным удобством для конечных пользователей, избавляя их от необходимости регулярно совершать лишние действия. К примеру, синтаксический сахар -- по определению явление избыточное, но это повышает комфорт и удобство при работе.

На мой взгляд, в данном случае это также удобно и логично -- всегда видеть текущую версию в одном и том же диалоге, задавшись вопросом, а не появилось ли обновление. Поскольку это контекст. Справедливо и обратное утверждение, поэтому в большинстве популярных приложений все это обычно объединено в общую функциональности About Box'а.

**Comment by AlexRnD61** [comment]
>  а не с целью разводить тут дебаты с пользователями
Ах, простите подлого пользвателишку, осмелившегося осквернить своей недостойной писаниной Ваше божественные очи!
Но только так уж сложилось, что разработчики, которых не интересует мнение презренных пользователей, пишут у себя дома. На обоях. Ибо больше никому их творчество не нужно.

P.S. Видимо поставщики коммерческого софта Вас не берут на работу (и правильно делают), потому что в любом нормальном продукте по справке "About...никогда не выдается сообщение вида "Эй, ты, лузер, пора обновить софтинку, не работай на этом дряхлом отстое!"

**Comment by spectatorBH** [comment]
[Offtopic:] @AlexRnD61 Извините, Вас что, в школе выгнали из драмкружка? К чему эта театральщина и кривляние здесь? Да, если Вам так хочется, я высокомерный и эгоистичный Буратино, а Вы Пьеро, а теперь закиньте руки к небу и повторите свой текст повыразительнее...

Ближе к теме: я как раз и выразил здесь своё мнение разработчикам относительно моих пожеланий в реализации конкретной фичи, привел аргументы. Они могут его принять или отклонить: их проект -- их право, никаких претензий. Но Вы то к этому каким боком? Я не понимаю людей, которые начинают встревать и категорично отвергать чужие идеи, которые в любом случае не им реализовывать. Я своим предложением Вас как-то дискриминировал? Отчего такая болезненная реакция? Или Вам так одиноко и просто похоливарить больше не с кем? Тогда откройте Вконтактик и тренируйтесь там на кошечках.

Извините за переход на личности, но Вы меня вынудили в этот раз.

P.S. Вот пишу из-под Fx, зашел в About, а он, представляете, мне там сразу обновление предлагает?! Наверное, его не профессионалы пишут, подумал я.

P.P.S И, если не жалко, пришлите мне обоев подлиннее, а то запарился уже на дискеты сохраняться...
[/Offtopic]

**Comment by AlexRnD61** [comment]
> я высокомерный и эгоистичный Буратино

Место под солнцем для буратинок всем известно, но я не могу себе позволить обсценной лексики, коя используется для общения с буратинками, посему - "щаслива аставацца"

**Comment by spectatorBH** [comment]
Ауффидерзейн, студент! Поумерь свой гонор и больше не нарывайся.

**Comment by miks1965** [comment]
Действительно, не работает
