### ISSUE TITLE
Transform для массивов не интеллисенсится

### ISSUE THREAD

**Issue by miks1965** [pascalabcnet/pascalabcnet#426]
```
begin
  var a := Arr(1,2,3);
  a.Transform(x->x*x);
end.
```
Для списков всё работает.
Дело в том, что я сделал общий метод расширения для интерфейса IList

**Comment by spectatorBH** [comment]
Аналогичная проблема и с IndexMin, IndexMax, LastIndexMin, LastIndexMax, Replace и Fill.

**Comment by miks1965** [comment]
Мы знаем эту проблему. Она описана в Issue. Все эти методы расширяют IList<T>. Это правильно, но интеллисенс пока с этим не справляется
