### ISSUE TITLE
Падает при выполнении yield переменной типа множество

### ISSUE THREAD

**Issue by ibond84** [pascalabcnet/pascalabcnet#440]
```
type CharSet = set of char;
function Test: sequence of CharSet;
begin
  var set1 := ['a','b'];
  yield set1;
end;

begin
  assert(test().First = ['a','b']);
end.
```

**Comment by miks1965** [comment]
Ну, ясно почему. При обходе поля типа множество в конструктор добавляется специальный код инициализации множества. А тут ввиду синтаксического сахара set1 имеет специальный тип, который определяется потом. Но потом - код уже не добавляется.

**Comment by ibond84** [comment]
ну, ничего непонятно. код-то добавляется в семантике. a Yield-визиторы вроде меняют только синтаксическое дерево и подают его семантическому анализатору.

**Comment by miks1965** [comment]
Yield-визиторы в основном реализуются на ситнаксическом уровне, но есть пара исключений, связанных с выводом типов полей. Они выполняются на семантическом уровне позже обхода полей. Вот из-за этого не работает

**Comment by ibond84** [comment]
А где расположен этот код в семантике?

**Comment by miks1965** [comment]
Он размазан конечно. Найдите вот этот код в visit(assign) в syntax_tree_visitor:

```
// SSM 26.06.16 - правка в связи с автовыведением типов в yieldах
                if (to.type is auto_type)
```
Тут исправляется to.type, но если он является типом множества и to - поле класса, то добавление инициализации множества в конструктор не делается
