### ISSUE TITLE
Помеченный var

### ISSUE THREAD

**Issue by AlexRnD61** [pascalabcnet/pascalabcnet#442]
```
label L;
begin
  var m:=ReadInteger;
  if m>0 then goto L;
  Writeln('m<=0');
  Exit;
L:
  var n:=m*m;
  Writeln('n=',n)
end.
```
Я понимаю, что разработчики придерживаются категорического экзорцизма меток (и это уже не раз было продемонстрировано всевозможными запретами), я понимаю, что в паскале от Н.Вирта действительно нельзя было перейти к неисполняемому описанию var, но в данном-то случае мы имеем все же не описатель, а оператор присваивания.
Хочу чтобы меня тоже поняли хотя бы один раз, когда речь заходит о метках. Отлично, когда пишем все "в новом стиле", но давайте не забывать, что существуют опубликованные в различной литературе алгоритмы, где эти метки все же есть и перед тем, как от меток избавляться, надо сначала набрать алгоритм "как есть", чтобы убедиться, что он работает. К сожалению, форум опять "помер", а тут не место для дискуссий, потому что далеко не всякий "BS-алгоритм" (от Bowl of Spagetti) может быть легко и незатратно структирирован.

**Comment by ibond84** [comment]
>что существуют опубликованные в различной литературе алгоритмы, где эти метки все же есть и перед тем, как от меток избавляться, надо сначала набрать алгоритм "как есть", чтобы убедиться, что он работает

в этих программах врядли есть внутриблочные описания с инициализаторами. ;)

Ну а ограничение снимем сахарным преобразованием в виде добавления  впереди пустого оператора, на который прыгать разрешено.
