### ISSUE TITLE
Сделать встроенное множество синонимом HashSet

### ISSUE THREAD

**Issue by miks1965** [pascalabcnet/pascalabcnet#45]
По идее, это теперь возможно, переопределив все операции

**Comment by ibond84** [comment]
Вопрос, а нужно ли это делать? Там со множествами огромная морока была. Их надо в типизированный файл сохранять (причем только set of byte). Множества надо копировать при присваивании и передаче по значению. HashSet очень убог для таких вещей

**Comment by miks1965** [comment]
После того как появились operator чтото<T> это стало возможно.

В типизированный файл сохранять множества я бы запретил - это анахронизм. В жизни этого не делал

Копирование при присваивании и передаче по значению - с этим бы я точно расстался - это тоже анахронизм. Я не думаю, что это на что-то повлияет. 

Я не помню программ, где множества бы вообще передавались как параметр

Поэтому я бы сделал.

Единственное, что меня сдерживает - это страшная ошибка в PCU когда я в PABCSystem написал 

```
function HashSet<T>.operator=(x,y: HashSet<T>): boolean;
begin
  Result := x.SetEquals(y)
end;

function HashSet<T>.operator<>(x,y: HashSet<T>): boolean;
begin
  Result := not x.SetEquals(y)
end;
```

программа 
```
begin
  var l := new HashSet<integer>;
  write(l = l);
end.
```
стала падать. Так что я бы исправил эту ошибку и грохнул бы старые множества

**Comment by ibond84** [comment]
>То есть, 60 миллисекунд против 2300. Это очень долго.

Ну это из-за того, что множества основаны на базе Hashtable. Я бы объявил само определение set of устаревшим и ничего бы там не менял.  И использовал бы конструкцию HSet для современных ссылочных множеств.

**Comment by miks1965** [comment]
Почти согласен.

Только конструкцию [1,2,3,4] очень жалко использовать на что-то устаревшее. Я бы использовал ее как раз для HashSet например. 

Правда, как тогда поддерживать устаревшие множества, неясно.

А в чём всё-таки причина такой жалости к старому set of T? Ведь set of T по-прежнему можно будет использовать. И - я опросил тут всех наших преподавателей - никто не задумывался о том, что семантика у наших set of T - размерная. Ну то есть, никто не передавал множества как параметр. И практически никто не присваивал множества. Обычно множества в стиле [] используются как что-то одноразовое: ch in ['a','e','i','o','u','y']

**Comment by ibond84** [comment]
>Ну то есть, никто не передавал множества как параметр. 

Да это еще полбеды. Множества в паскале размерные в том смысле, что компилятору их надо инициализировать при описании (как статические массивы). а HashSet это ссылочный тип.

**Comment by ibond84** [comment]
>Только конструкцию [1,2,3,4] очень жалко использовать на что-то устаревшее. Я бы использовал ее как раз для HashSet например. 

Ну как вариант добавить оператор impilicit в TypedSet и HashSet. а [1,2,3,4] сделать новым множеством

**Comment by miks1965** [comment]
Да, согласен. Неинициализированные - это плохо. Закрываю.
