### ISSUE TITLE
Потеря контекста при выводе сообщения об ошибке

### ISSUE THREAD

**Issue by miks1965** [pascalabcnet/pascalabcnet#469]
```
{$reference 'PresentationFramework.dll'}

type Colors = System.Windows.Media.Colors1;
  
begin
  
end.  

```
Файл Undefined FileName не найден

**Comment by ibond84** [comment]
Ну это баг в парсере. named_type_reference не имеет сорсконтекста.

**Comment by ibond84** [comment]
В master не залиты исправления. Вручную закрывать issue не нужно. Если в коммите написать bug fix #469, то github автоматически закроет issue.
