### ISSUE TITLE
В основной программе  и в PABCSystem разное повеление

### ISSUE THREAD

**Issue by miks1965** [pascalabcnet/pascalabcnet#47]
Пишу в основной программе

```
function HashSet<T>.operator in(Self: HashSet<T>; x: T): boolean;
begin
  Result := Self.Contains(x);
end;
```
errin.pas(3) : Недопустимо описывать метод для синонима шаблонного типа

Это правильно.

Но в модуле PABCSystem это проходит - никто не ругается. У меня есть подозрение, что дальше с этим какие-то глюки будут. 

Либо везде разрешить, либо - запретить

**Comment by ibond84** [comment]
Ошибки нет. HashSet определен в подключенном пространстве имен System.Collections.Generic, поэтому компилятор берет его оттуда.

**Comment by ibond84** [comment]
Поэтому не нужно ничего запрещать.
