### ISSUE TITLE
Ошибка в типе возвращаемого методом класса результата

### ISSUE THREAD

**Issue by AlexRnD61** [pascalabcnet/pascalabcnet#471]
```
type
  MinHJ=class

  function F(a:integer:=1; b:integer:=2):array of integer;
  begin
    Result:=Arr(a,b);
  end;
  
end;

function G(a:integer:=1; b:integer:=2):array of integer;
  begin
    Result:=Arr(a,b);
  end;

begin
  var oL:=new MinHJ;
  var r:=oL.F();
  Writeln('F()-> ',r.GetType);
  var s:=oL.F;
  Writeln('F  -> ',s.GetType);
  // s.Println выдает, как следствие, ошибку
  
  // а так все работает
  var u:=G();
  Writeln('G()-> ',u.GetType);
  var v:=G;
  Writeln('G  -> ',v.GetType);
  v.Println
end.
```

Результат работы:
```
F()-> System.Int32[]
F  -> Program1.$delegate0
G()-> System.Int32[]
G  -> System.Int32[]
1 2
```
Ошибки не будет, если параметр в функции F один.

**Comment by miks1965** [comment]
Это извечная проблема. Если f - функция без параметров, то как трактовать 
```
var v := f;
```
Я уже не помню, какое решение принимали мы. Мне кажется, мы приняли решение, что f здесь - это вызов функции, но не везде переделали.

В случае же 
```
function f := 1;

begin
  var v: ()->integer := f;
  System.Console.WriteLine(v.GetType);
  Print(v.Invoke());
end.
```
тип должен быть делегатом, и это правильно - и это так и есть.

Вывод - для вызова методов мы это не исправили

**Comment by AlexRnD61** [comment]
А как можно еще трактовать var y:=f, если объект f описан, как функция и не описан как либо еще?

**Comment by miks1965** [comment]
Есть две трактовки. Первая - вызов функции. Вторая - указатель на функцию. Мы считаем, что в этом случае следует отдавать предпочтение вызову функции. Для указателя тип f надо описывать явно.
