### ISSUE TITLE
Режим сохранения файлов перед компиляцией - Program1

### ISSUE THREAD

**Issue by miks1965** [pascalabcnet/pascalabcnet#477]
Предложение такое. Сейчас режим сохранения файлов перед компиляцией стал работать правильно.
Но неудобно в случае компиляции несохранённого Program1. 

Предложение - пусть режим сохранения файлов перед компиляцией не распространяется на ещё не сохранённые файлы. То есть, при их компиляции не выдавать запрос на сохранение.

**Comment by ibond84** [comment]
Сделал
