### ISSUE TITLE
Выдавать предупреждение при использовании read(string)

### ISSUE THREAD

**Issue by ibond84** [pascalabcnet/pascalabcnet#481]

**Comment by miks1965** [comment]
А какое предупреждение и почему?

**Comment by vkopichenko** [comment]
Описание проблемы: http://forum.mmcs.sfedu.ru/t/opasnost-pri-chtenii-strok/1361

**Comment by miks1965** [comment]
Этой проблемы нет. Никаких предупреждений быть не должно. На форуме разъясняли, что этот код ошибочен. Считывать строку в цикле с помощью read в корне ошибочно.

**Comment by ibond84** [comment]
Ну вот. Просто в старом PascalABC этот код ошибочно работал. Мне уже несколько раз присылали письма, почему не работает этот неработающий read(string). Как-то надоело реагировать. Сделать предупреждение чтобы эту бяку не использовали и все.
