### ISSUE TITLE
Не работает var (a,b) := (1,1) глобально

### ISSUE THREAD

**Issue by miks1965** [pascalabcnet/pascalabcnet#484]
Некуда писать операторы

**Comment by ibond84** [comment]
о чем идет речь??

**Comment by miks1965** [comment]
Имеется в виду такая программа:

```
var (a,b) := (1,1);

begin
end.
```
Там в грамматике этого нет. Но когда я пытался сделать это в грамматике, я положил и внутриблочную возможность. Наверное, что-то неаккуратно делал.

Кроме того, после того как это будет сделано в грамматике, надо выносить это как множественные описания в раздел описаний, а эта инфраструктура еще не создана.
