### ISSUE TITLE
Build VisualPascalABCNET to UBUNTU

### ISSUE THREAD

**Issue by Level0r0s** [pascalabcnet/pascalabcnet#493]
Hello
I'm starting my studies with PascalABC and I have some doubts.

is it possible to compile VisualPascalABCNET with monodeveloper to run on Ubuntu?

or is it reluctant to compile with VisualStudio on Windows and run on Ubuntu with Wine?

**Comment by miks1965** [comment]
Нет, откомпилировать VisualPascalABCNET под mono нельзя. И это не ошибка
