### ISSUE TITLE
Код в лямбде неправильно читается

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#496]
```
type
  t1 = class
    
    procedure Redraw;begin end;
    
    constructor(Redraw: boolean);
    begin
      if Redraw then
        self.Redraw;
    end;
  
  end;
  
  t2 = class
    
    procedure Redraw;begin end;
    
    constructor(Redraw: boolean);
    begin
      var p:procedure := ()->
      begin
        if Redraw then
          self.Redraw;
      end;
    end;
  
  end;

begin
end.
```
конструктор класса t2 не будет компилироваться потому что:
`0.pas(22) : Нельзя преобразовать тип procedure к boolean`

P.S. если использовать лямбду не для переменной, а для запуска потока - выдаст внутреннюю ошибку компилятора.

**Comment by ibond84** [comment]
>P.S. если использовать лямбду не для переменной, а для запуска потока - выдаст внутреннюю ошибку компилятора.

пожалуйста, для каждой ошибки отдельный issue вместе с неработающим кодом.
