### ISSUE TITLE
Константа типа cardinal или uint64 неправильно преобразуется к integer

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#498]
```
const
  nn: cardinal = 10000;

begin
  var n: cardinal;
  loop nn do
    n += 1;
  writeln(n);
end.
```
Выводится 16, так же c `uint64`.

**Comment by miks1965** [comment]
Это всё следствие вот этого:
```
const nn: cardinal = 257;

begin
  var i: integer := nn;
  Print(i);
end.
```

**Comment by SunSerega** [comment]
@miks1965 почему `loop` не поддерживает другие целые типы? `integer` конечно удобно когда хочешь написать что то простенькое, но мне очень важно то что на паскале можно писать просто и сложно, очень не приятно когда часть *cложно* становится недоступна...

**Comment by miks1965** [comment]
Дело не в loop. Спасибо, что заметили ошибку. Но она в преобразовании из cardinal в integer
