### ISSUE TITLE
Как-то у нас с константными выражениями всё плохо

### ISSUE THREAD

**Issue by miks1965** [pascalabcnet/pascalabcnet#50]
```
var n: integer := 2;

const a = n*2; // компилируется, что неверно

const b = n; // не компилируется, что верно

begin
end.
```

**Comment by ibond84** [comment]
Константы в паскале вообще непонятно что. Например 
const b = sin(2); 
работает. Кажется, такие ужасы идут со времен Turbo Pascal-а

**Comment by miks1965** [comment]
Ну, тут понятно. sin(2) можно вычислить на этапе компиляции. n*2 нельзя

**Comment by ibond84** [comment]
Ну не совсем понятно. А как можно определить, можно ли вычислить функцию на этапе компиляции? И у нас функции не вычисляются на этапе компиляции по указанной выше причине. Поэтому такой код компилируется

```
var a: integer;
function f(x: integer): integer;
begin
  Inc(a);
  Result := 2;
end;
const x = f(3);
begin

end.
```

**Comment by miks1965** [comment]
С функциями ладно. Можно вообще считать, что с функциями любое выражение неконстантно.

А вот const a = n*2; можно проверить, что всё входящее - константа - или нет

**Comment by VladislavMoldovan** [comment]
```
var 
n := 2; 
function f() := n; 

const 
a = f(); // Это не константа. Если мы считаем, что с функциями любое выражение неконстантно, то это должна быть ошибка компиляции.

begin 
Writeln(a); 
end. 
```
