### ISSUE TITLE
writeln зависает на сложных структурах классов

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#500]
Я недавно запостил на форуме тему [3 способа сломать паскаль](http://forum.mmcs.sfedu.ru/t/3-sposoba-slomat-paskal/1834/6)

3 способ заключался в том, что когда я пытался выписать с помощью _ObjectToString(который используется writeln-ом) переменную ConnectionT.Whose:Segment - поток зависал. Проблема оказалась в том что в _ObjectToString была часть для выписывания классов, которая когда в классе указана public переменная которая ссылается на `self` - выписывается куча скобочек и обрывается на 30 уровне глубины(ну хорошо хоть какое то ограничение).

Далее после программы:
```
type
  t1 = class;
  t2 = class
  public 
    a: t1;
  end;
  t1 = class
    public a: t2;//да, можно и a: t1, но в принципе не важно, выведет то же самое
  end;

  Segment = class;
  ConnectionT = class
  
  public 
    s1, s2: Segment;
    next: ConnectionT;
  
  end;
  Segment = class
  
  public 
    C: List<ConnectionT>;
  
  end;
  
function New_ObjectToString(o: object): string;
const
  ErrorString = 'Error: Writing too long';
begin
  var Res := ErrorString;
  var Thr := new System.Threading.Thread(()->begin Res := PABCSystem._ObjectToString(o) end);//должно быть StructuredObjectToString(o) а не PABCSystem._ObjectToString(o)
  Thr.Start;
  var TP: word;
  while Thr.IsAlive do
  begin
    Sleep(10);
    TP += 1;
    if TP = 300 then
    begin
      Thr.Abort;
      Result := Res;
      exit;
    end;
  end;
  Result := Res;
end;

begin
  var a := new t1;
  a.a := new t2;
  a.a.a := a;
  
  writeln('a:');
  writeln(New_ObjectToString(a));
  writeln(a);
  
  var S := new Segment;
  S.C := new List<ConnectionT>;
  S.C.Add(new ConnectionT);
  
  S.C[0].s1 := S;
  S.C[0].s2 := new Segment;
  
  S.C[0].s2.C := new List<ConnectionT>;
  S.C[0].s2.C.Add(new ConnectionT);
  
  S.C[0].s2.C[0].s1 := S.C[0].s2;
  S.C[0].s2.C[0].s2 := S.C[0].s1;
  
  S.C[0].next := S.C[0].s2.C[0];
  S.C[0].s2.C[0].next := S.C[0];
  
  writeln('S.C:');
  writeln(New_ObjectToString(S.C));
  writeln(S.C);//112088443 знаков, 82470 mc чтоб создать строку и я так и не дождался пока выпишет
  
end.
```

Если запустить выводится так:
```
((((((((((((((((((((((((((((((((...))))))))))))))))))))))))))))))))
((((((((((((((((((((((((((((((((...))))))))))))))))))))))))))))))))
S.C:
```
Спустя 3 сек ещё:
`Error: Writing too long`
И после этого зависает на 80 сек и когда отвиснет - начинает процесс бесконечного выписывание в консоль паскаля 112088443 знаков, пока выписывает если свернуть паскаль - развернуть его уже не получится(только после удаления процесса в диспетчере задач), кроме того при этом тратится целое ядро процессора, на 1-ядерных компьютерах это скорее всего приведёт к тому что придётся перезагружать комп(а в классах информатики обычно как раз такие).
И это только пустые классы, у меня в программе и у `Segment` и у `ConnectionT` было много параметров из за которых всё зависало более чем на 10 мин, я не стал дальше ждать...

По сути я просто добавил таймер на 3 сек, если время заканчивается - выводится `ErrorString` и прекращаются попытки создать бесконечный текст. Вы можете использовать как хотите содержимое `New_ObjectToString`, авторство указывать не надо, и что там ещё надо для копирайтинга? ;)

**Comment by miks1965** [comment]
Мы поняли, спасибо, но это не ошибка Паскаля - это Ваша ошибка. Он честно пытается сделать то, что Вы ему предлагаете, - и не может
