### ISSUE TITLE
Улучшения удобств работы

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#502]
1. Пункт настроек `сохранять открытые окна`, который будет сохранять какие файлы были открыты и имена свёрнутых частей кода.(В идеале сделать так чтоб была настройка `объединить открытые файлы в проект`, чтоб можно было быстро переключатся между проектами)
2. Сохранение положения настройки `auto hide` окна ввода при выключении паскаля.
3. Сохранение имён типов, подпрограмм и регионов перед форматированием, чтоб весь код не разворачивался.
4. Выделение сразу нескольких строчек для отладки, вместо перетыкивания каждой([подробнее](http://forum.mmcs.sfedu.ru/t/zamechaniya-i-predlozheniya/143/296?u=sun_serega))

**Comment by miks1965** [comment]
2 и 3 не понял. 1 и 4 - хотелки, надо заявителю писать свою оболочку.

**Comment by ibond84** [comment]
>Пункт настроек сохранять открытые окна, который будет сохранять какие файлы были открыты и имена свёрнутых частей кода

Работайте с проектами. Там это реализовано.

>Выделение сразу нескольких строчек для отладки, вместо перетыкивания каждой

Такого нигде не видел. Для этого есть пошаговая отладка по F8

**Comment by SunSerega** [comment]
@miks1965
1. У больших программ действительно не удобно начинать работу с 5-минутного открывания всего что понадобится.
2. Я про эту кнопочку:
![image](https://user-images.githubusercontent.com/27270190/30988871-6c6fb0e6-a4a4-11e7-9c5a-84d5c59d0adb.png).
 Каждый раз её тыкать не сложно... Просто муторно.
3. Сделать так чтоб форматирование не разворачивало свёрнутый код.

Насчёт хотелок - я поделился с разработчиками паскаля мыслями по поводу что мне было не удобно, разве без отзывов, руководствуясь только своим мнением, можно сделать его приятнее в использовании для всех? Да, всё ещё получается грубоватое выражение мысли, но и на месте я не стою.

@ibond84
4. Не знал. Есть централизованное место со всей информацией о наборах клавиш и кнопках интерфейса? Я лично искал только в справке, а на форуме и официальном сайте и намёка на подобное не видел.
