### ISSUE TITLE
в System не все (u)intN

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#504]
Компилятор понимает все `System.(u)int16`-`System.(u)int64`, но не System.(u)int8, а анализатор кода видит только `System.(u)int64`

**Comment by ibond84** [comment]
Все правильно. Типов System.(u)int8 не существует. Есть System.Byte и System.SByte. Анализатор кода показывает синонимы типов. Мелкая неточность, откройте для этого отдельный issue. Не пишите по несколько багов в одном issue. Этот issue закрываю
