### ISSUE TITLE
Анализатор не правильно читает array.ConvertAll

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#514]
```
begin
  var arr1 := arr(1, 3, 5);
  var arr2 := arr1.ConvertAll(a -> (a, a + 1));
end.
```
Анализатор кода будет показывать что у `arr2` тип `array of function(a:T):array of integer`.
Похоже что независимо от того каким будет результат лямбды.

**Comment by ibond84** [comment]
дубль #492
