### ISSUE TITLE
Компилятор не воспринимает описание типа переменной и лямбду на 1 строчке

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#515]
```
begin
  var arr1 := arr(1, 3, 5);
  var o1 := arr1.MinBy(i->i);
  var o2:byte := arr1.MinBy(i->i);
end.
```
На строчке `var o2` выдаст ошибку `встречено '->' а ожидалось ';'`

**Comment by miks1965** [comment]
Это к сожалению особенность инициализации с указанием типа. В инициализаторе не должны быть лямбды. Причина в том, что если указан тип, то набор инициализаторов расширяется, и при добавлении лямбд в грамматике появляются конфликты.
