### ISSUE TITLE
Успешная компиляция sealed abstract классов

### ISSUE THREAD

**Issue by wisestump** [pascalabcnet/pascalabcnet#526]
Нижеприведенный код компилируется на версии 3.3.1548:
```pascal
type
  Example = sealed abstract class
    f1: string
  end;

begin 

end.
```

**Comment by SunSerega** [comment]
Всё правильно. Это удобно чтоб делать классы как `System.Math`, то есть тех которые состоят только из статичных подпрограмм.

**Comment by ibond84** [comment]
Этот код должен компилироваться.
