### ISSUE TITLE
Падение при попытке форматирования файла с namespace

### ISSUE THREAD

**Issue by Ssstlis** [pascalabcnet/pascalabcnet#528]
![image](https://user-images.githubusercontent.com/22175914/31791612-ce0f7e0c-b521-11e7-9389-ffb1619dc01b.png)

**Comment by SunSerega** [comment]
1. Его ещё не доделали же, рано ошибки искать.
2. Что за шрифт такой рукописный?)))

**Comment by Ssstlis** [comment]
Всеми нелюбимый Comic Sans MS. Мне удобен тем, что не давит на глаза.
