### ISSUE TITLE
Translating the IDE interface

### ISSUE THREAD

**Issue by RolandChastain** [pascalabcnet/pascalabcnet#53]
Hello!

Congratulations for this product, that I have just discovered. I would be interested in providing to french-speaking users a french version of the IDE interface. Is it possible? If it is possible, could you explain what I have to do?

PascalABC.NET is announced here:
http://www.developpez.net/forums/d1563718/autres-langages/pascal/outils-telecharger/pascalabc-net-environnement-developpement-net-pascal/

Best regards.

**Comment by ibond84** [comment]
Yes, it is possible. Create the directory "Fre" in the directory bin/Lng and copy all files from the bin/Lng/Eng directory. Modify the file ".LanguageName" and translate all strings

**Comment by RolandChastain** [comment]
Thank you for your answer. I am glad that it is possible. I will make it in the next days.

Best regards.

**Comment by RolandChastain** [comment]
The french version of language files is almost finished. There is a big interest for PascalABC in the french Pascal forum.

I close the issue. When the translation is entirely done and tested, I will send you the files, in case you wish to include them in your distribution.
![screenshot](https://cloud.githubusercontent.com/assets/13957204/12390055/3cc0fbde-bddd-11e5-9aea-d55706fff461.png)
