### ISSUE TITLE
Ошибки возвращающие точку ошибки - Undefined FileName(0)

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#530]
В некоторых случаях как [тут](https://github.com/pascalabcnet/pascalabcnet/issues/529) или [тут](https://github.com/pascalabcnet/pascalabcnet/issues/497) - возвращается место ошибки `Undefined FileName(0)`, то есть ни файл, ни строчка не определена. Поиск причины таких ошибок очень усложняется надоедливым текстбоксом
![image](https://user-images.githubusercontent.com/27270190/31810629-285dfe66-b585-11e7-830f-6bd2b7e85e8b.png)
и тем что курсор переставляет на самое начало файла с которым работал при каждой компиляции. Пожалуйста, сделайте так чтоб текстбокса не было(всё равно в списке ошибок видно `Undefined FileName`) и чтоб курсор никуда не телепортировался, раз точка ошибки не была найдена.

**Comment by miks1965** [comment]
Как только основная ошибка будет устранена, будет устранена и эта. Закрываю.
