### ISSUE TITLE
for var i:=-1 to i do - я бы запретил

### ISSUE THREAD

**Issue by miks1965** [pascalabcnet/pascalabcnet#534]
```
begin
  for var i:=-1 to i do
    Print(i);
end.
```
Неестественное использование i. Ее значение равно 0.
Я бы запретил

**Comment by ibond84** [comment]
Я бы выдавал предупреждение. Там для этого есть инфраструктура (поиск использований переменных), а в семантическом анализаторе такого нет.

**Comment by miks1965** [comment]
А где такая инфраструктура? А то я её пишу для разных целей всякий раз
