### ISSUE TITLE
Неправильный приоритет процедур

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#537]
```
procedure Log(a:object) := writeln(a);

begin
  Log(1);
  Log('2');
end.
```
`2` выписывает, а `1` нет. Похоже на то что используется функция логарифма вместе моей процедуры.

**Comment by ibond84** [comment]
Здесь нет ошибки. Перегрузки ищутся во всех подключенных модулях. Ваша процедура имеет параметр типа object, а в стандартном real, 1 ближе к real, чем к object, поэтому вызывается стандартная функция.

**Comment by miks1965** [comment]
Прошу задавать вопрос на форуме, является ли это ошибкой, прежде чем замусоривать Issue
