### ISSUE TITLE
Падение компилятора в PCU из-за a.AdjacentGroup

### ISSUE THREAD

**Issue by miks1965** [pascalabcnet/pascalabcnet#539]
```
begin
  var a := ArrRandomInteger(20, 0, 2);
  var b := a.AdjacentGroup;
  b.Println;
  foreach var i in b do
  begin
    Write('[');
    i.Print(',');
    Print(']');
    var x := i.Sum() //убираем эту строку все работает правильно
  end;
end.
```
a.AdjacentGroup - я недавно изменил тип возвращаемого значения на sequence of array of T и реализацию.
Дело в PCU...

**Comment by AlexRnD61** [comment]
```
// PascalABC.NET 3.3, сборка 1559 от 01.11.2017

begin
  var a := ArrRandom(20, 0, 2);
  Writeln(a.AdjacentGroup)
end.
```
Компилятор по-прежнему падает

**Comment by miks1965** [comment]
Да, компилятор по-прежнему падает:
Внутренняя ошибка компилятора в модуле Compiler.Compile[Program1.pas] :'System.IO.EndOfStreamException: Чтение после конца потока невозможно.
   в System.IO.__Error.EndOfFile()
   в System.IO.BinaryReader.ReadByte()
   в PascalABCCompiler.PCU.PCUReader.GetTypeReference()

**Comment by AlexRnD61** [comment]
И в новой сборке 1561 от 02.22.1017 падает тоже.
