### ISSUE TITLE
Константы просчитанные функцией не показывают своё значение

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#551]
```
function f1 := 5;

const
  a=f1();

begin end.
```
При наведении на `a` будет писать `a:integer` вместо `a:integer=5`.

**Comment by ibond84** [comment]
я бы просто показывал бы const a = f1()

**Comment by SunSerega** [comment]
1 из довольно приятных удобств констант то что они показывают то чему они будут присвоены, как к примеру когда `a=1000/b`. Вы предлагаете вручную считать это? Зачем если можно заставить компьютер выполнять муторную работу?

**Comment by ibond84** [comment]
Функции в интеллисенсе не вычисляются. Это не его задача. Поэтому выведу просто f1().
