### ISSUE TITLE
Лишнее сворачивание кода

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#552]
![image](https://user-images.githubusercontent.com/27270190/32882764-1c3d64ac-cabe-11e7-9a9b-1f43dd2dacfb.png)
Если в программе нет строчки `program` - точку для сворачивание всей программы ставит на первую считающуюся кодом. И как в этом примере - эта точка не даёт свернуть процедуру `p1`. Честно говоря вообще не понимаю зачем точка сворачивания Всей программы...

**Comment by ibond84** [comment]
ну, пишите program в начале или оберните процедуру регионом. точка сворачивания модуля/программы нужна, так как это тоже блок.
