### ISSUE TITLE
Анализатор кода показывает extensionmethod для шаблона, с неправильным T

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#554]
```
procedure p1(Self:List<integer>); extensionmethod;begin end;

begin
  
  var l := new List<Single>;
  l.p1;
  
end.
```
Анализатор кода считает что `l` может использовать `p1` а компилятор против.

**Comment by ibond84** [comment]
p1 добавляется в List<T>, как и в компиляторе. Фильтровать ради этого сомнительного удовольствия сотню методов, сравнивая каждый раз типы, не хочу.
