### ISSUE TITLE
System.Nullable<T> = record но это не точно

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#556]
![image](https://user-images.githubusercontent.com/27270190/32991203-a0d8d60a-cd3f-11e7-8c86-765c255e5646.png)

![image](https://user-images.githubusercontent.com/27270190/32991166-00d05d86-cd3f-11e7-84f3-32ac35645f6a.png)

```
type
  nbyte = byte?;

begin
  
  var b:byte?;
  b := nil;//работает
  
  var o:object;
  o := 1;
  writeln(lbl as nbyte);//нельзя потому что "не ссылочный тип"
  
end.
```

**Comment by ibond84** [comment]
System.Nullable<T> это record, а не класс. читайте MSDN

https://msdn.microsoft.com/ru-ru/library/b3h38hb0(v=vs.110).aspx

**Comment by miks1965** [comment]
И не пишите Issue почём зря
