### ISSUE TITLE
На синтаксическом уровне сделать узлы, позволяющие вызывать функции из PABCSystem

### ISSUE THREAD

**Issue by miks1965** [pascalabcnet/pascalabcnet#56]
На синтаксическом уровне сделать узлы, позволяющие вызывать функции из PABCSystem

Сейчас это невозможно если кто-то объявит переменную с именем PABCSystem

Сделать видимо наподобие ?PABCSystem

**Comment by ibond84** [comment]
Я, честно, не понял, о чем идет речь и зачем нужны эти узлы.

**Comment by miks1965** [comment]
О, это я сделаю. Это я для себя писал.

**Comment by miks1965** [comment]
Закрываю. Это редко бывает нужно
