### ISSUE TITLE
Паскаль не даёт удалить папку

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#564]
1. Создаём папку, в ней файл .pas, пишем HelloWorld или на что хватит сил и запускаем;
2. Закрываем вкладку этого файла в паскале не закрывая паскаль(новую вкладку, к примеру, создать);
>все файлы из папки удаляются, но саму папку удалить не получается, "используется другим процессом"
3. Закрываем паскаль;
>а теперь нормально

**Comment by ibond84** [comment]
Это везде так. Особенности Windows. Закрываю
