### ISSUE TITLE
Невозможно сгенерировать исходный код.\r\nВозможно, были удалены псевдокомментарии. 

### ISSUE THREAD

**Issue by YashiroShow** [pascalabcnet/pascalabcnet#569]
Что мне делать? Эта ошибка появляется при переходе с дизайнера форм на её код (проект Приложение Windows), Как это можно исправить, подскажите, пожалуйста?
![image](https://user-images.githubusercontent.com/33938421/33185115-842316ec-d091-11e7-8ac9-47dae61ac984.png)

**Comment by ibond84** [comment]
Приведите полный код модуля с формой

**Comment by YashiroShow** [comment]
[ssm.zip](https://github.com/pascalabcnet/pascalabcnet/files/1500027/ssm.zip)
@ibond84 , вот держите)

**Comment by ibond84** [comment]
Замените табы на пробелы перед {$region FormDesigner}

**Comment by YashiroShow** [comment]
@ibond84 Сработало, огромное спасибо)))
