### ISSUE TITLE
Анализатор кода не понимает i/2 где i целое но не integer

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#574]
```
begin
  
  var i: word;
  var a := i / 2;
  
  writeln(a.GetType);
  
end.
```
Анализатор кода думает что у а тип `word`.

**Comment by YashiroShow** [comment]
А вы сами посудите: var (внутри блока кода определяет автоматически тип переменной) a := i(word) / 2(const); Получается Вы определяете переменную в типах так: T := WORD / 2 => T = WORD. Вот и всё, поэтому и "a" получается word. Попробуйте написать так: var a: integer := i / 2;

**Comment by SunSerega** [comment]
@YashiroShow а теперь запустите программу и посмотрите какой тип скажет компилятор. ` writeln(a.GetType);` выписывает тип `System.Double`, то есть `real` по паскалевски. И как раз с `integer` всё работает правильно, я ж так в названии и написал.
