### ISSUE TITLE
Видит циклическую зависимость где её нет

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#577]
```
type
  r1=record
    
    class Empty:r1;
    
  end;

begin end.
```
`test.pas(4) : Циклическая зависимость в записи`

**Comment by YashiroShow** [comment]
А разве здесь её нет? Вы же получается определяете переменную Empty как запись r1, в которой определена переменная Empty как запись r1 и т.д.

**Comment by SunSerega** [comment]
@YashiroShow `Empty` стасична
