### ISSUE TITLE
Описание /// не работает для пред описания класса

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#584]
```
type
  ///тип t1
  t1=class;
  
  t1=class
    
  end;

begin end.
```
Описание всегда ставится перед первым описанием у методов. А тут работает наоборот.

**Comment by ibond84** [comment]
Нет, здесь все правильно. Предописания классов это простые огрызки описания класса только для того, чтобы занести имя класса в таблицу символов. Основное описание (со списком базовых классов и т.д.) идет позже, там и надо ставить документирующие комментарии. К этому описанию и осуществляется переход в интеллисенсе (по Ctrl+Click). Логичнее ожидать, что там будут стоять документирующие подсказки.
