### ISSUE TITLE
Samples\NETLibraries\System.Parallel\Parallel1.pas не работает

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#585]
`Parallel1.pas(5) : Неверный тип переменной, которой присваивается лямбда-выражение`

**Comment by miks1965** [comment]
Так работает:
```
  var a:Action0 := ()->Print(1);
  Parallel.Invoke(a)
```
Так - нет:
```
  Parallel.Invoke(()->Print(1))
```
И так - нет:
```
procedure p(params a: array of Action0);
begin
end;
begin
  p(()->Print(1))
end.
```
А раньше работало. Видимо, после исправления какой-то ошибки с делегатами

**Comment by ibond84** [comment]
Интересно, а где там присваивание..

**Comment by miks1965** [comment]
Какое присваивание? Тут вроде нет нигде присваивания.

Просто когда писался этот пример, он работал
