### ISSUE TITLE
После удаления строчки с { текст не обновляется

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#588]
```
begin
  {
  writeln;
  {}
end.
```
Если убрать строчку `{` - `writeln;` останется зелёным, но это только графический баг.

**Comment by ibond84** [comment]
да все работает

**Comment by miks1965** [comment]
Всё работает

**Comment by SunSerega** [comment]
![image](https://user-images.githubusercontent.com/27270190/33552329-44b6fa5e-d8fd-11e7-8532-a0a722f6c573.png)
Если выделять ведя курсор как показано фиолетовой стрелкой, или использовать Ctrl+X - работает правильно, а если выделять ведя курсор по красной стрелке и нажать Backspace - не обновляется.
