### ISSUE TITLE
Is Visual Studio supported?

### ISSUE THREAD

**Issue by fanoI** [pascalabcnet/pascalabcnet#590]
Hello I'm a Cosmos OS developer and the idea to have a PascalABC.Net OS is intriguing for us.

These are requirement for Cosmos:
1. ABC.Net can be compiled by Visual Studio?
2. Is Net Core / Net Standard 2.0 supported?

Thank you!

**Comment by ibond84** [comment]
1. Visual Studio can be compiled by Visual Studio 2017 Express/Enterprise.
2. No, .NET Core is not supported

**Comment by miks1965** [comment]
1. ABC.Net is compiled by Visual Studio

**Comment by fanoI** [comment]
OK is compiled with Visual Studio but I can compile a Pascal ABC.Net project with Visual Studio? There is some "plug in" for Visual Studio to download?

Net Core / Net Standard 2.0 support is in your road map?

Thank you!

**Comment by miks1965** [comment]
There is some "plug in" for Visual Studio to download?
  No

Net Core / Net Standard 2.0 support is in your road map?
  Maybe in future
