### ISSUE TITLE
В лямбде указатель на функцию имеет больше приоритет чем возвращаемое значение

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#591]
```
type
  t1=class
    
    function f1:byte:=0;
    
    constructor;
    begin
      var a:= new byte[1];
      a.Fill(i->f1);
    end;
    
  end;

begin end.
```
Так не работает потому что в `a.Fill` результату функции пытается присвоить указатель на `f1` вместо её возвращаемого значения. Если поставить `f1()` - работает.

**Comment by YashiroShow** [comment]
А разве имя функции не является статическим указателем на неё? Просто я Си как раз изучаю, и думаю, что в Паскале также, так вот, там запись "f1" - указатель, а "f1()" = "*(f1)()" - разыменование указателя. Ну в Паскале разыменование вроде так выглядит - "^(f1)()"

**Comment by SunSerega** [comment]
@YashiroShow в паскале решено отдать приоритет возвращаемому значению функции, то есть `var b := f1` даст `b` тип `byte`, а `var f:function:byte := f1` присвоит `f` указатель функции. С `C` языком это никак не связано.

**Comment by YashiroShow** [comment]
@SunSerega ну ладно, я таких тонкостей не знаю уже, тогда получается надо исправлять это)
