### ISSUE TITLE
Tuple=System.Tuple вместо Tuple<T1,T2>=System.Tuple<T1,T2> и т.п.

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#595]
![image](https://user-images.githubusercontent.com/27270190/33604032-40926c0e-d9bd-11e7-84ea-91bd47f37bb4.png)
`var a: Tuple<integer,integer>` не работает.

Особенно это не удобно в такой записи:
```
  var l:List<(integer,integer)>;
  l := new ;
```
Тут подсказки дописывают тип `List<Tuple<integer,integer>>` после new, а компилятор это не принимает.

**Comment by miks1965** [comment]
В PascalABC.NET нельзя использовать одно имя типа для Tuple и Tuple<integer>. Используйте System.Tuple<integer,integer> если запись (integer,integer) не нравится
