### ISSUE TITLE
Конструктор предлагает Tuple<T1,T2> вместо (T1,T2)

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#597]
```
begin
  var l:List<(integer,integer)>;
  l := new ;
end.
```
После `new` подсказки дописывают тип List<Tuple<integer,integer>>, а компилятор это не принимает.

**Comment by miks1965** [comment]
Ну, это не ошибка, а сокращённое описание. Пишите List<System.Tuple<integer,integer>>

**Comment by MrSpecular** [comment]
```
uses System; // <-- Решение. 
begin
  var l:List<(integer,integer)>;
  l := new List<Tuple<integer,integer>>();
end.
```

**Comment by SunSerega** [comment]
Да ну понятное дело... Но это костыль.

Кстати, я тогда создал [тему](http://forum.mmcs.sfedu.ru/t/konstruktor-predlagaet-tuple-t1-t2-vmesto-t1-t2/2043) на форуме, раз вы вспомнили - лучше связать всё.
