### ISSUE TITLE
Анализатор кода не видит пред описание класса

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#598]
```
type
  t1 = class;
  
  
  
  t1 = class
  
  end;

begin end.
```
![image](https://user-images.githubusercontent.com/27270190/33666971-3ba579b0-daa4-11e7-9230-e84e99b4c947.png)

**Comment by miks1965** [comment]
Правильно - анализатор кода видит только правильное описание. Предописание - не для анализатора кода
