### ISSUE TITLE
Хотелось бы функцию Sum()

### ISSUE THREAD

**Issue by RustemB** [pascalabcnet/pascalabcnet#599]
```pascal
Sum( 12, 2, 4, 22 );            //=40
Sum( [1, 2, 3] );               //=6
Sum( 12.01, 7.99 );             //=20
Sum( 'Pascal', 'ABC', '.NET' ); //='PascalABC.NET'
```
и т.д.

**Comment by YashiroShow** [comment]
А чём проблема написать свою?
function sum(params values: array of integer): integer;
	begin
	
		foreach var v in values do
			Result += v;
	
	end;

Как вариант использовать перегрузку, можно конечно пошаманить с Generic, но я в них, к сожалению, пока что ни бум-бум :)

**Comment by SunSerega** [comment]
@RustemB `writeln(Arr(1,3,5,7).Sum)`
Для такого есть [замечания и предложения](http://forum.mmcs.sfedu.ru/t/zamechaniya-i-predlozheniya/143/423) и [помощь новичкам](http://forum.mmcs.sfedu.ru/t/pomoshh-novichkam/263/287), а гитхаб только для грубых ошибок.
