### ISSUE TITLE
Руководство по сборке (желательно multi-OS)

### ISSUE THREAD

**Issue by ulysses4ever** [pascalabcnet/pascalabcnet#6]
Хотелось бы иметь какое-то простое руководство для сборки. Желательно, под разные OS. До тех пор вряд ли стоит рассчитывать на подключение сторонних сил.

**Comment by ibond84** [comment]
Добавил руководство в README.md. Проверял на последней убунте.

**Comment by ulysses4ever** [comment]
Спасибо! 

Closed with e8a7e93  and 3 previous commits.
