### ISSUE TITLE
Странности с простой лямбдой

### ISSUE THREAD

**Issue by AlexRnD61** [pascalabcnet/pascalabcnet#603]
Все видно из прикрепленного скрина.
![2017-12-08_194038](https://user-images.githubusercontent.com/28169041/33775755-66e1e4ee-dc50-11e7-8a57-ce6cf1c33231.jpg)

**Comment by miks1965** [comment]
Скопируйте пожалуйста сюда текст программы

**Comment by AlexRnD61** [comment]
function gLen1(s:string):=

s.ToLower.Where(c->c in 'аеёиоуыэюя').JoinIntoString.Length;

begin

var s:='А роза упала на лапу Азора';

var gLen:string->integer:=

w->w.ToLower.Where(c->c in 'аеёиоуыэюя').JoinIntoString.Length;

s.ToWords.Select(w->gLen(w)).Println

end.


  _____
