### ISSUE TITLE
Переменная self доступна только для чтения - так не должно быть

### ISSUE THREAD

**Issue by miks1965** [pascalabcnet/pascalabcnet#61]
```
function Compose(Self: integer->integer): integer->integer;
begin
  Result := x->Self(x);
end;

begin
  
end.
```

**Comment by ibond84** [comment]
В синтаксическом дереве генерируется какой-то странный код: Self := _Self. Что это такое??

**Comment by ibond84** [comment]
```
 public override void visit(SyntaxTree.function_lambda_call _function_lambda_call)
        {
            SyntaxTree.op_type_node _op_type_node = new SyntaxTree.op_type_node(SyntaxTree.Operators.Assignment);
            for (int i = 0; i < _function_lambda_call.parameters.expressions.Count; i++)
            {
                SyntaxTree.assign _assign = new SyntaxTree.assign(_function_lambda_call.f_lambda_def.parameters.expressions[i] as SyntaxTree.addressed_value, _function_lambda_call.parameters.expressions[i] as SyntaxTree.expression, _op_type_node.type);
                ((SyntaxTree.statement_list)_function_lambda_call.f_lambda_def.proc_body).subnodes.Insert(0, _assign);
            }
```

**Comment by ibond84** [comment]
```
function Compose(Self: integer->integer): integer->integer;
begin
  var s := self;
  Result := x->s(x);
end;

begin

end.
```

Здесь вообще выдается странная ошибка без SourceContext-а Неизвестное имя '<>local_variables_class_0'

**Comment by ibond84** [comment]
```
function Compose(Self: integer->integer): integer->integer;
begin
  var s: integer->integer := self;
  Result := x->s(x);
end;

begin

end.
```
Так работает. Замыкать self напрямую нельзя.

**Comment by miks1965** [comment]
Ошибка выдаётся не всегда. Это ошибка,  наведенная предыдущими компиляциями.

Предлагаю Self и все делегаты разрешить захватывать. Вызов функции через делегат не меняет этот самый делегат

**Comment by ibond84** [comment]
>Предлагаю Self и все делегаты разрешить захватывать. Вызов функции через делегат не меняет этот самый делегат 

Это невозможно, так как при текущей реализации замыканий на базе синтаксических вставок придется разрешать присваивать значение переменной Self (выстреливать себе в ногу).

**Comment by miks1965** [comment]
Хорошо. А как быть с плавающей ошибкой, которая выдается или нет в зависимости от предыдущих компиляций? Это тоже важно.

**Comment by ibond84** [comment]
Плавающая ошибка исправлена.
