### ISSUE TITLE
NullReferenceException в процессе компиляции

### ISSUE THREAD

**Issue by madetara** [pascalabcnet/pascalabcnet#610]
Попытка компиляции данной строки вызывает NullReferenceException.
`var realArr := MakeArr&<real>(1, -5, 6.4, 8);`

Указание к её использованию [здесь](http://edu.mmcs.sfedu.ru/mod/assign/view.php?id=11750)

[Отчёт об ошибке](https://pastebin.com/UKimfdGP)
Попытка сохранить отчёт об ошибке приводит к "зависанию" среды разработки и невозможности отправки или сохранения отчёта.

**Comment by SunSerega** [comment]
Обычное `var realArr := Arr&<real>(1, -5, 6.4, 8);` работает нормально, а первая ссылка требует регистрации чтоб посмотреть что это за `MakeArr`.

**Comment by madetara** [comment]
Эта ссылка оставлена в большей степени для разработчика PascalABC - у него должен быть туда доступ. Там просто приведена эта строка с рекомендацией к её использованию

**Comment by miks1965** [comment]
На Github так не делается. На Github публикуется вся программа с ошибкой.

Я например не разобрался вообще, что скачивать, что писать и где ошибка

**Comment by madetara** [comment]
Контекст использования данной строки не имеет значения, потому что она вызывает исключение в любой программе в которую вставляется.

Причины использования: создание массива вещественных чисел.
Ожидаемый результат: создание массива вещественных чисел или ошибка компиляции.
Фактический результат: необрабатываемое исключение в компиляторе.

**Comment by miks1965** [comment]
Ещё раз - Вы не поняли. Выложите СЮДА все исходники с программой, содержащей эту строку.

**Comment by madetara** [comment]
![2017-12-14_14-02-24](https://user-images.githubusercontent.com/31938575/33989140-78704300-e0d7-11e7-9a79-7c873d3c3578.png)

**Comment by SunSerega** [comment]
```
begin
  var a := blablabla&<byte>(0,1,2);
end.
```
Ошибка компиляции происходит при использовании `&<>`, когда должно было выдать ошибку неизвестного имени. Где то забыли проверку на нулевое значение наверное.
