### ISSUE TITLE
В качестве типа - параметра лямбды не принимает кортежи

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#612]
```
procedure p1(a:(byte,(byte,byte))->());
begin end;

begin end.
```
`test.pas(1) : В качестве типа ожидался идентификатор`
Во всяком случае ошибка точно не правильная.

**Comment by miks1965** [comment]
Ошибка правильная. Все типы в скобках должны быть идентификаторами - Вам же написали. Опишите тип одним идентификатором - и можно будет.
