### ISSUE TITLE
Лямбды-процедуры из 1 оператора сломаны

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#613]
```
type
  t1=class
    
    procedure p1(b:byte); begin end;
    
  end;

begin
  var a:array of t1;
  a.ForEach(o->o.p1(1));
end.
```
`test.pas(10) : Нет перегруженной подпрограммы с таким количеством параметров ForEach`

А так ещё хуже, тут ловим ещё 1 `Undefined FileName`:
```
type
  t1=class
    
    procedure p1; begin end;
    
  end;

begin
  var a:array of t1;
  a.ForEach(o->o.p1);
end.
```
`Undefined FileName(0) : Операция ':=' не применима к типам procedure и procedure`

Добавление `begin end` в обоих лямбдах глушит ошибку.

**Comment by AlexRnD61** [comment]
Вот так работает:
```
type
  Cl=class

  procedure p1(i:integer);
  begin
    Write(i:10)
  end;
end;  

begin
  var a:=Arr(3,4,5,6);
  var x:=new Cl;
  a.ForEach(o->x.p1(o))
end.
```

**Comment by miks1965** [comment]
Так работает
```
type
  t1=class
    procedure p1(b:integer); begin end;
  end;

begin
  var a := new t1[1];
  a[0] := new t1;
  a.ForEach(o->begin o.p1(1) end);
end.
```
Это значит, что процедура распознаётся как функция. Это слабая система вывода, а не ошибка. И - плохое сообщение об ошибке - но там всю подсистему ошибок надо переделывать для функциональных параметров

**Comment by miks1965** [comment]
Второй пример принимается. Вот пример проще:
```
procedure p1; begin end;

type
  t1=class
  end;

begin
  var a:array of t1;
  a.ForEach(o->p1);
end.
```

**Comment by miks1965** [comment]
Закрыл. Выводим более приличное сообщение об ошибке. Алгоритм вывода слабый. Это не ошибка
