### ISSUE TITLE
Текст выделяется неожиданным образом

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#616]
```
begin
  
  {$region}
  
  {$endregion}
  
end.
```
Сворачиваем регион;
Ставим курсор где то подальше от него чтоб было виднее:
![image](https://user-images.githubusercontent.com/27270190/34071867-1f477536-e286-11e7-88e8-3e19cd4859af.png)
Делаем одиночный клик на `[...]`;
![image](https://user-images.githubusercontent.com/27270190/34071881-50b757f8-e286-11e7-9b49-a04d8967b702.png)

**Comment by miks1965** [comment]
Это ошибки редактора. Редактор - внешний, его ошибки мы исправлять не будем. Таких ошибок достаточно много.
