### ISSUE TITLE
Почему-то не работает Range!!!

### ISSUE THREAD

**Issue by miks1965** [pascalabcnet/pascalabcnet#62]
```
function integer.R1: sequence of integer;
begin
  Result := Range(1,10);
end;

begin
end.
```
Program1.pas(3) : Неверное число параметров функции

**Comment by ibond84** [comment]
ну в integer есть же Range. надо писать PABCSystem.Range

**Comment by miks1965** [comment]
Да, точно. Надо бы переименовать в Times и возвращать последовательность с нуля
