### ISSUE TITLE
Функции класса полностью перекрывают предыдущие

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#621]
```
function f1(x: real) := x;

type
  t1 = class
    
    a: real;
    
    function f1: real := f1(a);// << тут выдаёт ошибку
    
  end;

begin end.
```
`test.pas(8) : Неверное количество параметров функции`

**Comment by ibond84** [comment]
Все правильно выводится. В справке написано

Поиск перегруженного имени метода осуществляется аналогично: вначале осуществляется просмотр текущего класса, затем его базового класса и т.д. до класса Object, либо до того момента, как будет встречен объект, который не может перегружать предыдущие (имя поля или свойства). Из всех найденных таким образом одноименных методов выбирается наилучший. При этом в разных классах могут быть методы с идентичными параметрами; в этом случае вызывается первый встреченный метод от данного класса к классу Object.
