### ISSUE TITLE
Короткое описание оператора даёт Undefined FileName

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#623]
```
type
  t1=class
    
    class function operator implicit(b:byte) := new t1;
    
  end;

begin end.
```
`Undefined FileName(0) : Возвращаемое значение или параметр должны иметь тип t1`
Если явно указать тип возвращаемого значения - ошибки не будет.

**Comment by ibond84** [comment]
Тип возвращаемого значения в операторах implicit и explicit должен указываться явно. Теперь выводится соответствующее сообщение об ошибке.
