### ISSUE TITLE
Ctrl+Space делает все численные типы с маленькой буквы

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#633]
На `Single` и `Double` это особо хорошо видно, не только в названиях всех методов, что их используют, но и в на странице описании они с большой буквы:

```
type 
  /// Представляет число одиночной точности с плавающей запятой.
Single = record(System.ValueType, System.IComparable, System.IFormattable, System.IConvertible, System.IComparable<Single>, System.IEquatable<Single>)
```

```
type 
  /// Представляет число двойной точности с плавающей запятой.
Double = record(System.ValueType, System.IComparable, System.IFormattable, System.IConvertible, System.IComparable<Double>, System.IEquatable<Double>)
```

Но так со всеми числами, и с целыми тоже.

**Comment by miks1965** [comment]
Не понял, в чем ошибка. По Ctrl-Space Single большими

**Comment by SunSerega** [comment]
@miks1965 
![image](https://user-images.githubusercontent.com/27270190/34594652-04d756da-f1db-11e7-9884-af3b8caa7e7b.png)
Билд последний, 1607

**Comment by ibond84** [comment]
single это стандартный паскалевский тип, поэтому пишется с маленькой буквы

**Comment by SunSerega** [comment]
@ibond84 я не совсем понял вашу логику.

**Comment by ibond84** [comment]
Ну real пишется с маленькой буквы, поэтому и single тоже.
