### ISSUE TITLE
Выбирается не та подпрограмма с лямбдой в неожиданных случаях

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#636]
```
begin
  var a := new byte[1];
  var b := a.Sum(bt->Single(0));
  writeln(b.GetType);
end.
```
`System.Double`

Если поменять тип элементов массива или ещё что то - не воспроизводится, но это не единственный случай. К примеру у меня получилось сделать `Nullable<Single>` в своей программе.

**Comment by SunSerega** [comment]
```
begin
  var a:=Arr(new class(s := Single(0)));
  var s:Single;
  var b := a.Max(o->o.s)*s;
end.
```
`test.pas(4) : Нельзя преобразовать тип Nullable<single> к single`

Анализатор кода при этом всём вообще сходит с ума...

**Comment by ibond84** [comment]
дубль https://github.com/pascalabcnet/pascalabcnet/issues/486
