### ISSUE TITLE
Форматирование не смотрит на $ifdef

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#639]
```
begin
  begin
    if ReadlnInteger=0 then
    begin
      writeln(true);
    {$ifdef DEBUG}
    end else raise new System.Exception;
    {$else}
    end;
    {$endif}
  end;
end.
```
Компилятор такое принимает, а форматирование выдаёт ошибку:
`test.pas(11) : Ожидалось '.'`

**Comment by ibond84** [comment]
Это техническое ограничение. Форматтер строит синтаксическое дерево, игнорирую естественно все директивы препроцессора. Поэтому на вход подается неправильная программа.
