### ISSUE TITLE
Во всех файлах DEBUG оказывается определено по умолчанию

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#640]
```
begin
  {$ifdef DEBUG}
  writeln('DEBUG On');
  {$else}
  writeln('DEBUG Off');
  {$endif}
end.
```
`DEBUG On`

Если это что то нужное компилятору - переименуйте пожалуйста в PABC_DEBUG_BUILD.

**Comment by miks1965** [comment]
Может, Вы переименуете свою константу? Это стандартная константа. Запустите по Shift-F9 - будет Off

**Comment by SunSerega** [comment]
@miks1965 я же и говорю, если это константа паскаля - она не должна занимать общее имя, у неё должно быть имя которое точно ни с чем не пересечётся. PABC_DEBUG_BUILD просто пример.

**Comment by miks1965** [comment]
Ну, integer тоже занимает общее имя

**Comment by SunSerega** [comment]
@miks1965 я имею в виду что DEBUG это имя которое очень удобно использовать, это самое интуитивное имя для того чтобы обозначить DEBUG состояние своего проекта. Посмотрите на это с точки зрения того кто будет программировать на паскале, более интуитивным кажется что просто DEBUG означает состояние своего проекта, в таком случае если понадобится режим компилятора - логичнее называть его каким то именем которое точно ни с чем не спутаешь. Не общее а наиболее удобное.
