### ISSUE TITLE
$undef не работает

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#641]
{$undef <идентификатор>} - исключение имени, используется для *отмены действия директивы $define*.
```
{$define A}
{$undef A}

begin
  {$ifdef A}
  writeln('A defined');
  {$else}
  writeln('A is not defined');
  {$endif}
end.
```
`A defined`

**Comment by miks1965** [comment]
Смешно. Она у нас не определена оказывается :)
