### ISSUE TITLE
Метод Foreach - неверное сообщение об ошибке

### ISSUE THREAD

**Issue by miks1965** [pascalabcnet/pascalabcnet#642]
```
procedure p1; begin end;

begin
  var a:array of integer;
  a.ForEach(o->p1);
end.
```
a1.pas(5) : Нет перегруженной подпрограммы с таким количеством параметров ForEach

**Comment by miks1965** [comment]
Всё правильно. Считает аргумент функцией.

**Comment by SunSerega** [comment]
Ничего в этом правильного.
Эта issue про то, что Foreach принимает процедуру, поэтому понять что ожидается лямбда-процедура реально.

**Comment by miks1965** [comment]
А, да. Сообщение об ошибке неверное

**Comment by SunSerega** [comment]
А почему всё же не попытаться сделать вывод в зависимости от контекста параметров функции?
