### ISSUE TITLE
Остальные ключевые слова которых нет в Ctrl+Space но которые выделяет жирным

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#646]
Те которых не хватает в Ctrl+Space:
```
external
lock
where
library
div
mod
shl
shr
not
as
is
on
goto
exit
overload
internal
```

Те которых нету в Ctrl+Space и выделяет жирным, а я не представляю что делают:
```
template
partial
out
namespace//ну вроде его и не надо в Ctrl+Space
//эти 2 наверное для async and await, но если уже сделали чтоб их выделяло жирным - добавьте в Ctrl+Space
async
asyncparam
```

Те которые не понятно зачем выделяет жирным в редакторе:
```
event
finnaly//это ведь просто безграмотное finally... кстати грамотное finally тоже выделяет.
```

Прошу заметить что все слова что я написал тут выделяет жирным, а кол-во случаев где не ключевое слово выделяется жирным очень ограничено. Поэтому если возникнет какое то не согласие - не закрывайте пожалуйста issue сразу, дайте высказать мою точку зрения или закрыть issue самому если соглашусь с вашим объяснением.

**Comment by ibond84** [comment]
Какие-то вещи (template, partial, namespace) экспериментальные, поэтому выделяются жирными. event это ключевое слово. async зарезервирован на будущее. finnaly уберу

**Comment by SunSerega** [comment]
Ну вот `public` к примеру используется в классе и должно быть для этого зарезервировано, поэтому оно ключевое слово, а почему `event` ключевое слово?

**Comment by ibond84** [comment]
event это событие

**Comment by ibond84** [comment]
Да, в справке про него ничего не сказано. event это аналог события в C#
