### ISSUE TITLE
Изменение переменных в режиме отладки сломано

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#649]
Если нажать на какое то значение - вместо создания TextBox-a - появляется белый прямоугольник с предсмертными судорогами, если после этого нажать на значение другого элемента - появляется MessageBox и сразу же уничтожается, не успев до конца нарисоваться, а окно IDE сворачивается.

![image](https://user-images.githubusercontent.com/27270190/34702123-b63b42f8-f4f4-11e7-9103-da36db1dc0ca.png)

Win 7. сборка 1611

А вот кусок MessageBox-а:
![image](https://user-images.githubusercontent.com/27270190/34702318-c3a5692c-f4f5-11e7-96f1-8f9c4ace3345.png)
После того как нарисовалось это он исчезает.

**Comment by ibond84** [comment]
Сделал readonly. На 64-битных системах перестало работать. Что-то там в COM..

**Comment by SunSerega** [comment]
Прекрасное решение, ничего не скажешь... А оставить issue пока не соберётесь с силами исправить не? Оставлять просто так костыли и забывать про них - это не нормально.
