### ISSUE TITLE
Re: Точка не срабатывает если заменять ею текст

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#652]
#582 не было исправлено

**Comment by ibond84** [comment]
У меня не воспроизводится.

**Comment by SunSerega** [comment]
[bandicam 2018-01-10 03-34-34-817.zip](https://github.com/pascalabcnet/pascalabcnet/files/1617230/bandicam.2018-01-10.03-34-34-817.zip)

Снова редактор?

**Comment by ibond84** [comment]
Щас, ну вы же там нажали точку, окно не появилось, потом стерли ее и снова нажали, подсказка появилась, что правильно

**Comment by SunSerega** [comment]
@ibond84 подсказка должна была сразу появится, а не после того как я стёр точку. Название у issue то про замену текста точкой.

**Comment by miks1965** [comment]
Ну, мне это тоже иногда мешает. Например, я набрал s.Pr и хочу посмотреть другие методы. Выделяю .Pr, нажимаю точку - подсказка не появляется

**Comment by ibond84** [comment]
Если б редактор это позволял... KeyEventHandler вызывается до удаления выделения текста,
