### ISSUE TITLE
Методы расширения sequence имеют больший приоритет чем string

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#657]
```
begin
  var s:string;
  var s2:=s.Print;
end.
```
`s2: sequence of char`
Раз `string` наследник `sequence` - у его методов расширения должен быть больший приоритет. Кроме того `Print` всегда должен возвращать то что его вызвало.

**Comment by ibond84** [comment]
У string нет метода расширения Print. Это метод расширения IEnumerable<T>.
