### ISSUE TITLE
Для массивов безуспешно предлагает конструктор

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#660]
```
begin
  var a:array of byte;
  a := new;
end.
```
Если поставить пробел после `new` - начнёт предлагать конструкторы, но при этом ни 1 из них не будет подходить, разумеется. Мне кажется правильно было бы в таком случает предлагать особенное имя, которое по другому не покажет в списке конструкторов - `byte[]` (и если выбрано - ставить курсор между скобочками).

**Comment by ibond84** [comment]
В интеллисенсах так принято: показывать все классы и пространства имен. В студии так же.
