### ISSUE TITLE
Метаданные даёт компилировать

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#661]
Компиляция всегда(или почти) не проходит, но ошибку выдаёт исходя из текста программы, а надо выдавать ошибку вроде "Метаданные нельзя компилировать или изменять".

**Comment by miks1965** [comment]
Знать бы ещё что такое метаданные...
Пример кода приведите

**Comment by SunSerega** [comment]
Наберите `System.GC`, зажмите Ctrl и нажмите на `GC` - откроется файл с припиской [метаданные] в названии.

**Comment by miks1965** [comment]
Так, ясно. Приведите пример программы, которая не компилируется.

**Comment by SunSerega** [comment]
Любой возьмите. К примеру тот же `GC` - 2 ошибки:
![image](https://user-images.githubusercontent.com/27270190/34992831-18f0cd5e-fad7-11e7-8f77-e78edd82b4e8.png)
и сразу же ещё в список ошибок выписывает:
`GC.pas(1) : Имя модуля должно совпадать с именем файла`

вместо того чтоб сказать что метаданные это не файл исходников, их нельзя компилировать.

**Comment by SunSerega** [comment]
Нет ну не в самом файле ;) Ошибкой обычной или текстбоксом выводить. Лучше обычной ошибкой.

**Comment by miks1965** [comment]
Я не понимаю, о чём Вы говорите. Нельзя компилировать файл метаданных, который Вы получаете по правой кнопке мыши. Нельзя. Если Вы его компилируете, выдаётся дурацкая ошибка. И это правильно. Не компилируйте что ни попадя.

Что Вы хотите? Что за текстбокс такой???

**Comment by SunSerega** [comment]
Дурацкая ошибка не может быть правильной.

Я имел в виду меседжбокс. Я хочу нормальную ошибку с нормальным описанием что сделано не так.
