### ISSUE TITLE
Ошибку выдаёт только в коротком описании функции

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#662]
```
type
  t1 = class
    
   class function GetNew := new t1;
  
  end;

begin end.
```
`0.pas(4) : Ни один конструктор не найден`

Но если заменить
```
    class function GetNew := new t1;
```
на
```
    class function GetNew: t1;
    begin
      Result := new t1;
    end;
```
ошибки нету.

**Comment by ibond84** [comment]
Это не ошибка, а ограничение синтаксического сахара. Компилятор пытается вывести тип GetNew в то время как не определен/сгенерирован конструктор по умолчанию. А оставлять вывод типа возвращаемого значения на потом никак нельзя, поэтому компилируется new t1. 
Во втором случае тело метода компилируется после обхода описаний методов и после того, как был сгенерирован конструктор по умолчанию. Поэтому все работает.
Вывод: описывайте конструктор по умолчанию до метода GetNew.
