### ISSUE TITLE
"результаты поиска символов" обрезает

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#669]
![image](https://user-images.githubusercontent.com/27270190/35196883-ca535172-fee0-11e7-8ca3-23a9511ac04b.png)

Такое меню появляется после ПКМ->найти все ссылки на каком то имени.

**Comment by miks1965** [comment]
Я не вижу этого меню. Где оно появляется? Точно это меню? Вы не путаете термины?

**Comment by SunSerega** [comment]
Возможно путаю, как назвать 1 словом те штуки:
![image](https://user-images.githubusercontent.com/27270190/35244420-b687f92a-ffc8-11e7-84e6-e2699fe73b90.png)

**Comment by miks1965** [comment]
Понятно. Это компонент такой - если не умещается в ширину - обрезает. У меня не обрезает. Это зависит от размера шрифта и еще непонятно от чего.

**Comment by miks1965** [comment]
![default](https://user-images.githubusercontent.com/10325391/35261475-4b1922a0-0021-11e8-9435-c67456f01cc4.png)

**Comment by SunSerega** [comment]
Прикол в том что последняя буква то у меня помещается... Место для неё есть, в смысле. И им же вроде ширину в зависимости от текста в них делает, почему же тогда? У меня экран 1366х768, шрифт `Courier New` с размером 10, то есть то что по умолчанию ставится.
