### ISSUE TITLE
Анализатор кода не просчитывает переполнение в константах

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#672]
```
const
  i:integer = 2147483648;//MaxValue+1

begin
  writeln(i);
end.
```
`-2147483648`
При этом при наведении мышки на `i` будет показывать `2147483648`.

**Comment by ibond84** [comment]
Ну что написано в const, то и выводится. Если написать строковую константу, то будет честно выводится строка. В студии то же самое.
