### ISSUE TITLE
В метаданных интерфейсов добавляет virtual

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#676]
![image](https://user-images.githubusercontent.com/27270190/35936727-b8b0c598-0c4c-11e8-959e-519c5bcced6a.png)
Атрибут `virtual` нельзя использовать в интерфейсах.

**Comment by miks1965** [comment]
В .NET в интерфейсах все функции виртуальные. Проверьте, сгенерировав аналогичный код на C#. Просто писать это слово не надо и нельзя
