### ISSUE TITLE
Intellisence не видит NumLibABC

### ISSUE THREAD

**Issue by AlexRnD61** [pascalabcnet/pascalabcnet#677]
Ощущение, что для Intellisence этой библиотеки просто нет. Не видит даже состава, не то, чтобы параметров.

**Comment by miks1965** [comment]
Всё видит вроде

**Comment by miks1965** [comment]
Пример приведите

**Comment by AlexRnD61** [comment]
Да. Давно так не лопухался. Оказывается, после первой установки надо было компьютер перезагрузить...

"Удаляюсь в пустыню, посыпая главу пеплом..."
Закрывайте Issue.

**Comment by SunSerega** [comment]
@AlexRnD61
Вообще вы сами можете её закрыть. Разработчики что то не спешат.

**Comment by AlexRnD61** [comment]
И правда...
