### ISSUE TITLE
Intellisense не понимает список, полученный из строки

### ISSUE THREAD

**Issue by AlexRnD61** [pascalabcnet/pascalabcnet#686]
![2018-02-20_100947](https://user-images.githubusercontent.com/28169041/36411460-d1bbe534-1626-11e8-87ac-a540405bb66c.png)

**Comment by ibond84** [comment]
в соседнем issue исправлено

**Comment by AlexRnD61** [comment]
Приятно слышать. Оно не смертельно было, но немного неприятно.
