### ISSUE TITLE
Функция Val работает не по стандарту

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#688]
В PABC.Net она реализована так:
```
procedure Val(s: string; var value: число; var err: integer);
begin
  if TryStrToInt(s, value) then
    err := 0
  else err := 1;  
end;
```
То есть в случае ошибки err всегда будет 1, а как утверждает [pioterM](http://forum.mmcs.sfedu.ru/t/nepravilnaya-rabota-funkczii-val-alternativa-standartnomu-kompilyatoru/2166/3?u=sun_serega) - оно должно быть равным индексу первого знака не являющегося цифрой.

**Comment by AlexRnD61** [comment]
Действительно, по канонам TurboPascal, Borland Deplhi и Free Pascal, в err должна быть указана позиция символа, вызвавшего ошибку. У Н.Вирта эта процедура отсутствует вообще.
Интересно, что нигде не сказано, чему будет равно value при возникновении ошибки.

Лично у меня эта процедура вызывает уныние: жаль, что ТурбоПаскаль фактически тут задал стандарт. Значительно больше симпатий вызывает реализация Val в Visual Basic - там нет всех этих благоглупостей, Val - это функция с единственным аргументом - строкой. И возвращает она число того типа ,который строка изображает. А вот и фишка: функция удаляет из указанной строки символы пробелов, табуляции и возврата каретки. Если функция встречает символ, который невозможно преобразовать в число, преобразование заканчивается на этой позиции. Т.е. не ошибка возникает, а получаем вменяемое значение. А если надо что-то "поумнее" - на то другие функции есть.

**Comment by ibond84** [comment]
а оно надо?

**Comment by AlexRnD61** [comment]
Тут уже много что написали, поэтому "оно" - это что?

**Comment by SunSerega** [comment]
Если так посудить то функция `Val` вообще не нужна, раз она в 3 строчки - её можно самому написать. Разве что совместимость... А для совместимости "оно" надо ;)

**Comment by AlexRnD61** [comment]
Еще раз: Val - не функция, а процедура. При программировании в функциональном стиле это как серпом по... э ... по ноге. Если бы она была функцией, ей бы многое можно было простить)))

**Comment by miks1965** [comment]
Val не входит в стандарт Паскаля. Мы не будем менять реализацию

**Comment by AlexRnD61** [comment]
Красивый финт)) Если посмотреть ISO/IEC 7185:1990 там вообще **нет ни одной процедуры или функции для работы со строками.** Чего бы их все не реализовать на свое усмотрение?

**Comment by miks1965** [comment]
Подобная реализация Val трудна - в .NET нет ничего подобного - поэтому потребовалось бы реализовывать руками, захламляя код системного модуля и увеличивая время компиляции. Подобная возможность мало используется - одному человеку понадобилось спустя 10 лет. И - надо сказать - Val сделана хотя бы для какой-то совместимости, надо пользоваться нормальными возможностями

**Comment by AlexRnD61** [comment]
Я нигде не писал, что Val - это нечто, сильно меня интересующее. Меня вообще обычно напрягает реализация в форме процедуры тому, что "сам бог велел" быть функцией. Я заметил лишь, что отсутствие строковых функций в стандарте позволяет реализовать их сколько угодно и как угодно.
