### ISSUE TITLE
Локализовать сообщение "Нажмите любую клавишу" по Shift-F9

### ISSUE THREAD

**Issue by ibond84** [pascalabcnet/pascalabcnet#689]
with Tools | Options menu, General options, When the Language='English' and  'make pause [...]] is not checked (Figure 1),  and the program is run without IDE (Figure 2), the console window closes without pausing, which is as expected (Figure 3) -- OK.
However, when 'make pause [...]' is checked, (Figure 4), and program is run without IDE, the pause-message displayed is all '????', which I am guessing means that there is no equivalent translation for that pause-message.

**Comment by miks1965** [comment]
Сообщение "Программа завершена. Нажмите любую клавишу" у нас вшито
