### ISSUE TITLE
Не компилируется Dynarray.pas в режиме ускорения оболочки

### ISSUE THREAD

**Issue by miks1965** [pascalabcnet/pascalabcnet#69]
H:\PABCWork.NET\Samples!MainFeatures\02_Types\Dynarray.pas

При компиляции по Ctrl-F9 ошибка возникает в этой строчке:
```
a[i] := PABCSystem.Random(100);
```
с сообщением
```
Dynarray.pas(18) : Неизвестное имя 'Random'
```

**Comment by ibond84** [comment]
Ошибка не воспроизводится...

**Comment by miks1965** [comment]
Должна быть последовательность действий.

1. Запустить Dynarray.pas
2. Откомпилировать Dynarray.pas

Режим ускорения оболочки должен быть включён
