### ISSUE TITLE
Локализовать заголовок "Инспектор объектов"

### ISSUE THREAD

**Issue by ibond84** [pascalabcnet/pascalabcnet#690]
with Tools | Options menu, General options, Language= (any language), the Properties tool-window caption is not translated; it does not change when the language setting is changes, even after application is restarted.

**Comment by miks1965** [comment]
А что такое Properties tool-window  - я его не вижу?

**Comment by miks1965** [comment]
А, вижу. Удивительно, но заголовок "Инспектор объектов" локализован. Почему он так отображается...
