### ISSUE TITLE
Настройка цвета шрифта и фона редактора и синтаксической подсветки

### ISSUE THREAD

**Issue by ibond84** [pascalabcnet/pascalabcnet#7]
Делать надо просто и гибко. Добавить два ColorBox для цвета шрифта и фона редактора и FileDialog для выбора пользовательского файла подсветки.

**Comment by ibond84** [comment]
Получается уродство какое-то. Делать не буду

**Comment by Dragon-0609** [comment]
Всем привет! Я написал плагин, который может менять цвета не только редактора, но и интерфейса IDE.
[Вот ссылка на репо](https://github.com/Dragon-0609/Yuki-Theme/)

Вот скриншоты:

![bandicam 2022-01-01 03-45-48-439](https://user-images.githubusercontent.com/80271099/148025749-3bc6bfa2-009e-45a1-9c55-714f4026761e.png)

![bandicam 2022-01-01 03-46-20-020](https://user-images.githubusercontent.com/80271099/148025771-ac6f5c8c-66dc-4d43-989d-0f829a4036c6.png)
