### ISSUE TITLE
Анализатор кода видит методы процедур и функций

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#702]
```
function f1(b:byte):byte; begin end;

begin
  f1.ToString;
end.
```
![image](https://user-images.githubusercontent.com/27270190/37032832-80955484-214c-11e8-8e80-2d570184a55e.png)
А компилятор запрещает:
`Program1.pas(4) : Неизвестное имя 'ToString'`

**Comment by ibond84** [comment]
Это правильное поведение. Студия тоже не проверяет параметры функции. Интелисенсы не должны быть так привередливы как компилятор.

**Comment by SunSerega** [comment]
В студии как раз это окно не показывается для функций переменных по нажатию точки. И дело не в привередливости. Дело в том что анализатор кода не должен вводить в заблуждение программиста, его задача как раз в обратном.

**Comment by ibond84** [comment]
В паскале функции вызываются без скобок. Никакого введения в заблуждение здесь нет. Просто надо язык знать и понимать, что нажав точку, мы пишем неправильный код. А окно выпадает специально, чтобы быстро просмотреть методы возвращаемого значения.

**Comment by SunSerega** [comment]
Аааа... Так это методы возвращаемого значения а не переменной-функции...
