### ISSUE TITLE
Переименование ищет переменную везде

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#707]
```
begin
  
  begin
    var i:integer;
    writeln(i);
  end;
  
end.
```
Если открыто что то громоздкое, вроде `PABCSystem` - при попытке переименовать `i` среда зависает секунд на 5. Если бы её искало только в блоке в котором она описана - это было бы быстрее.

**Comment by miks1965** [comment]
Это домыслы

**Comment by SunSerega** [comment]
Но факт остаётся фактом, открытие `PABCSystem` не должно влиять на скорость переименования переменной внутри блока. Каким ещё образом кроме того что я описал оно может влиять?
