### ISSUE TITLE
Неверный автовывод типа sequence of BigInteger

### ISSUE THREAD

**Issue by AlexRnD61** [pascalabcnet/pascalabcnet#711]
```
// PascalABC.NET 3.3, сборка 1634 от 14.02.2018

begin
  var a:=Arr('972522919974698368767218847121383881549244268321');
  var s:=a.Select(t->t.ToBigInteger);
  s.Sum.Println
end.
```
Упорно считает, что тип s - sequence of string, а не sequence of BigInteger, в результате чего
бракует s.Sum.Println. К сожалению, не дает писать в цепочках программы с использованием  BigInterger по типу 
```
Arr('972522919974698368767218847121383881549244268321').Select(t->t.ToBigInteger).Sum.Println
```

**Comment by SunSerega** [comment]
Это не ещё 1 дубль #486?

**Comment by AlexRnD61** [comment]
Возможно. Только я не видел №486, у него же другой заголовок

**Comment by SunSerega** [comment]
#486 не была закрыта.

**Comment by ibond84** [comment]
дубль #486
