### ISSUE TITLE
PutPixel в GraphWPF

### ISSUE THREAD

**Issue by vdjenjer** [pascalabcnet/pascalabcnet#716]
Большая просьба добавить метод рисования точки в новый модуль графики.

**Comment by SunSerega** [comment]
Проблема в том что `System.Windows.Media.DrawingContext` не умеет рисовать точки, лучшая замена - нарисовать прямоугольник 1х1, но это вы можете и сами сделать. Это довольно высокоуровневое рисование, тут не получится эффективно отрисовывать точки.

**Comment by vdjenjer** [comment]
Это понятно, в С# тоже нет... Прямоугольники рисуем, конечно, но они слишком большие. Пикселями аккуратнее выходит. Печально, если это принципиально невозможно.

**Comment by miks1965** [comment]
Да, к сожалению, это невозможно. Такого примитива в WPF нет и к тому же всё масштабируется если установлено увеличение не 100%. Поэтому точки как прямоугольники 1 на 1 будут размытыми.

**Comment by vdjenjer** [comment]
Понятно. Что ж, будем пользоваться и GraphABC и GraphWPF. Для разных задач -- разные модули.
