### ISSUE TITLE
Problem with overload method matching

### ISSUE THREAD

**Issue by sglienke** [pascalabcnet/pascalabcnet#719]
I encountered two different issues with generic overload method matching. (Version 3.3.5 build 1636)

I am using System.Reactive 4.0.0-preview00001 from nuget

The first one:

```
{$reference 'System.Reactive.dll'}

uses
  System,
  System.Reactive.Linq;
  
begin
  Observable.Range(1, 10).Subscribe(Console.WriteLine);
end.
```

This gives:
Reactive.pas(8) : The best overloaded method match for 'Subscribe' has some invalid arguments

But in fact Console.WriteLine has an overload that matches one of the Subscribe overloads (the one with the onNext parameter)

This however works: Subscribe(x -> Writeln(x));

The second is this one:

```
{$reference 'System.Reactive.dll'}

uses
  System,
  System.Reactive.Linq;
  
begin
  var x := Observable.Interval(TimeSpan.FromMilliseconds(1000)).StartWith(0);
  Readln;
end.
```

Where I get: 
Reactive.pas(8) : Cannot call the generic function 'StartWith' with these arguments

However since Observable.Interval returns an IObservable<Int64> and the StartWith extension method has the overload with params: array of T (where T is in this case Int64) it should find this.

this however works: StartWith(Int64(0));

When writing this it also works as Range returns `IObservable<Integer>`;

Observable.Range(1, 10).StartWith(0)

**Comment by miks1965** [comment]
```
Observable.Range(1, 10).Subscribe(Console.WriteLine);
```
It's an error. Right code:
```
Observable.Range(1, 10).Subscribe(x -> Writeln(x));
```

**Comment by sglienke** [comment]
I think you misunderstood.

This compiles:

```
uses
  System,
  System.Linq;
  
procedure MyPrint(i:Integer); 
begin
  Writeln(i);
end;

begin
  Enumerable.Range(1, 10).ForEach(MyPrint);
end.
```

This does not:

```
{$reference 'System.Reactive.dll'}

uses
  System,
  System.Linq;
  
procedure MyPrint(i:Integer); overload;
begin
  Writeln(i);
end;

procedure MyPrint(i:Int64); overload;
begin
  Writeln(i);
end;

begin
  Enumerable.Range(1, 10).ForEach(MyPrint);
  Readln;
end.
```

So there is clearly a defect with picking the correct MyPrint overload that matches the ForEach method as there is nothing to infer in terms of what T is - it is Integer because the result of Enumerable.Range is `IEnumerable<Integer>`.

As for the second issue it is the same - there is no guessing or infering necessary since T is determined already. It is just a matter if the overload for sequence of T or array of T has to be picked. And the fact that it works for an `IObservable<Integer>` shows that there is some defect when it is an `IObservable<Int64>`

**Comment by SunSerega** [comment]
There is better example:
```
procedure MyPrint(i:Integer);
begin
  Writeln(i);
end;

procedure MyPrint(i:string);
begin
  Writeln(i);
end;

begin
  var p := MyPrint;
  
  p(0);//works
  //p('qefq');//not works
  
  //so p is integer->() ?
  
  //Range(1, 10).ForEach(p);//nope
  
  var p2:integer->() := p;//ok
  Range(1, 10).ForEach(p2);//ok
end.
```
About second issue - developers asked to put individual issue's separately.

**Comment by sglienke** [comment]
@SunSerega I am not so sure if in that example the very first line should even compile. Why should it take the first MyPrint and not the second? (try putting the string one first and watch the p(0) complain. So you just found another issue I guess. Infering from an overload should give a compile error because it cannot determine which one to pick. Only if you would explicitly type p it can.

**Comment by sglienke** [comment]
Here is some more code to show the issue:

```
type
  IFoo<T> = interface
    procedure Test1(action: T -> ());
  end;
  
procedure Test2<T>(Self: IFoo<T>; action: T -> ()); extensionmethod;
begin
end;

procedure PrintIt(i:Integer);
begin
  Writeln(i);
end;

procedure PrintItInt(i:Integer);
begin
  Writeln(i);
end;

procedure PrintIt(i:string);
begin
  Writeln(i);
end;

var
  foo: IFoo<Integer>;
begin
  foo.Test1(PrintIt); // works, properly selected int overload;
  foo.Test2(PrintItInt); // works, explicitly put a non overloaded routine
  
  // does not work
  // extensionmethod seems to not properly select correct overload
  // it knows that T is Integer because foo is IFoo<Integer>
  foo.Test2(PrintIt); 
end.
```

**Comment by miks1965** [comment]
These examples are better.
This is not an error - but only weak type inference algorithm.

Let we keep these examples in Issue - for further enhancements

**Comment by miks1965** [comment]
Более простой пример, для которого не работает: 
```
procedure Test1<T>(action: T -> ()); begin end;
  
procedure PrintIt(i: Integer);
begin
  Writeln(i);
end;

procedure PrintIt(i: string);
begin
  Writeln(i);
end;

begin
  Test1(PrintIt); 
end.
```
DeduceFunction не может вывести обобщенный тип

**Comment by miks1965** [comment]
generics.cs DeduceInstanceTypes 
```
if (dm != null && dm.proper_methods.Count == 1)
                        fact_func = dm.proper_methods[0].simple_function_node;
```

**Comment by ibond84** [comment]
fixed
https://github.com/pascalabcnet/pascalabcnet/actions/runs/672895262
