### ISSUE TITLE
Close tabs with mousewheel click

### ISSUE THREAD

**Issue by sglienke** [pascalabcnet/pascalabcnet#722]
It would be nice if one could close tabs in the IDE with a mousewheel click on them - this behavior is pretty common with tabs (like Visual Studio, Delphi, Notepad++ Chrome or Firefox just to name a few).

Also adding the close button right into the tab would be cool.

**Comment by miks1965** [comment]
Yes but our controls are old and this demands serious change of visual infrastructure
