### ISSUE TITLE
Mixing char and string literals confuses type inference

### ISSUE THREAD

**Issue by sglienke** [pascalabcnet/pascalabcnet#724]
Following code causes a compile error:

```
var a := Arr(1,3,5,7); // works - array of integer
var b := Arr('1','3','5','7'); // works - array of char
var c := Arr('1','3','5','7','11'); // does not work, error
var d := Arr('11','13','15','17'); // works, array of string

begin
end.
```

**Comment by miks1965** [comment]
In C# we have the same error:

```
        static T[] Arr<T>(params T[] a)
        {
            var b = new T[a.Length];
            Array.Copy(a, b, a.Length);
            return b;
        }
        static void Main(string[] args)
        {
            var a = Arr("dsfh", 'h');
        }
```
This is a feature - not a bug :)

**Comment by SunSerega** [comment]
But in C# you can do string with 1 character, `Arr(string('a'),string('b'),'ab')` looks ugly.

**Comment by sglienke** [comment]
Err, no. In C# there is a difference between a string and char, because string has double quotes and char single quote. So, no regardless 1 or more characters, if quotes with double quites it infers properly.

So this is a pascal issue and it should properly infer a single character literal as string if there are other strings in that array.

**Comment by miks1965** [comment]
No, no.

String and Char are DIFFERENT types. Char is casting to string implicitely, but Char has another type.

You improperly understand the algorithm of type inference in generics. This algorithm deduces type T in Arr<T>(t1,t2: T) and after that any casting to another type does not work! It's a standard mistake!

**Comment by sglienke** [comment]
Let's not confuse things here.

This was about string and char - the fact that in pascal they both are quoted with a single quote makes this different from C# where it is clear from the syntax if its a string or a char so the compiler could not confuse a single letter string for a char. In pascal however 'a' can be a string or a char (or a char that can be cast to a string implicitly if you will). So when infering from an `array of T` the compiler could treat any chars as strings if it needs to because there is a string in that array - yes that would be an improvement.

As for the other example you gave with int and int64 - this works as well in C#.

```
var x = Arr(1, 2, 3); // becomes []int
var y = Arr(1, 2, (Int64)4); // becomes []long
```
