### ISSUE TITLE
Не информативная ошибка с указателем

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#728]
```
begin
  var a:byte := 5;
  var p := ^byte(@a);
end.
```
`Невозможно явно преобразовать тип ^byte к типу byte`

А надо что то типа:

`Тип должен быть единым идентификатором`

**Comment by miks1965** [comment]
Вы неправильно трактуете сообщение об ошибке.
```
var p := byte(@a);
```
выдаёт такую же ошибку потому что @a относится к типу ^byte.

**Comment by SunSerega** [comment]
Вы имеете в виду что его воспринимает как `var p := ^(byte(@a));`?
