### ISSUE TITLE
Не правильная ошибка при преобразовании nil к записи

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#729]
```
type t1 = record end;

begin
  var a := t1(nil);
end.
```
`Невозможно явно преобразовать тип nil к типу t1`

Вместо:

`Невозможно явно преобразовать nil к типу t1`

**Comment by miks1965** [comment]
Вы что-то выдумываете. Так тоже верно

**Comment by SunSerega** [comment]
У `nil` нету типа.
