### ISSUE TITLE
Ошибка "нельзя преобразовать тип" не правильно работает для лямбд

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#737]
```
procedure p1(b:byte) := exit;

begin
  p1(()->byte(0));
end.
```
`Нельзя преобразовать тип function:  к byte`
Вместо
`Нельзя преобразовать тип function: byte к byte`

**Comment by miks1965** [comment]
Ну, нельзя, да. Нельзя лямбду преобразовать к байту - всё верно

**Comment by SunSerega** [comment]
То что двоеточие ставит но возвращающий тип отрезает - это не верно.

**Comment by SunSerega** [comment]
То что двоеточие ставит но возвращающий тип отрезает - это не верно.
