### ISSUE TITLE
 &Repeat<T>(Self: T) не работает если вынесена в модуль

### ISSUE THREAD

**Issue by miks1965** [pascalabcnet/pascalabcnet#74]
```
function &Repeat<T>(Self: T): sequence of T; extensionmethod;
begin
  Result := SeqFill(integer.MaxValue,Self);
end;

begin
  1.Repeat.Take(3).Print;
end.
```
Так всё замечательно работает.
Если переносишь функцию в модуль, то не видит Repeat

**Comment by ibond84** [comment]
А память не исчерпается на этом примере? Я побоялся запускать.

**Comment by ibond84** [comment]
Исправлено

**Comment by miks1965** [comment]
Память не исчерпается - я же только 3 члена бесконечной последовательности прошу
