### ISSUE TITLE
Функции с yield-ами не поддерживают короткую запись

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#743]
```
function GetMyByteSeq: sequence of byte :=
  loop 10 do
  begin
    yield 5;
  end;

begin end.
```
`Program1.pas(2) : Встречено 'loop', а ожидалось выражение`
Приходится ставить лишний `begin end`, и, к примеру, тут - он выглядит ужасно, никуда его красиво не впихнёшь.

**Comment by miks1965** [comment]
Да, понятно. loop - синтаксический сахар, который на самом деле состоит из нескольких операторов

**Comment by miks1965** [comment]
А, да: функция поддерживает короткую запись только если справа - выражение, а не оператор
