### ISSUE TITLE
Ошибка при форматировании кода

### ISSUE THREAD

**Issue by vdjenjer** [pascalabcnet/pascalabcnet#752]
Windows 10, PascalABC.NET версия 3.3.5 сборка 1650 от 01.04.2018
При нажатии кнопки "Форматировать код" в редакторе программа
```
begin
  var a := arr(1,2,3);
  a[:2].println
end.
```
либо превращается в 
```
begin
  var a := arr(1, 2, 3);
  a[:22].println
end.
```
т.е. самовольно добавляет двойку в срез, либо (после нескольких повторных нажатий) вызывает "Необрабатываемое исключение в программе". При повторных нажатиях может сначала сделать `a[:22]`, потом `a[:2222]`, а потом выбросить исключение. Баг замечен довольно давно, проявляется до сих пор.

**Comment by SunSerega** [comment]
У меня форматирование тоже копирует то что после `:` (не обязательно число, любой текст копирует), но "Необрабатываемое исключение в программе" не вызывает, вместо этого пишет в нормальный список ошибок `Program1.pas(3) : Слишком большое целое`.

**Comment by vdjenjer** [comment]
Ну, я такое поведение программы наблюдал много раз на компьютерах своих учеников. Исключение выбрасывается, действительно, не всегда, но удвоение строки (т.е. числа, но как строки) происходит почти постоянно...
