### ISSUE TITLE
Using OfType extension method for IEnumerable<T>/sequence of T does not compile

### ISSUE THREAD

**Issue by sglienke** [pascalabcnet/pascalabcnet#755]
Following code does not compile (build 1650) with error:

Program1.pas(14) : Found ';' but expected expression

```
type
  TBase = class
  end;
  
  TFolder = class(TBase)
  end;
  
  TData = class(TBase)
  end;

begin
  var items := new TBase[4](TFolder.Create, TFolder.Create, TData.Create, TData.Create);
//  var folders := items.Where(item -> item is TFolder); // compiles and properly prints 2
  var folders := items.OfType<TFolder>; // does not compile
  Writeln(folders.Count);
end.
```

**Comment by SunSerega** [comment]
Error is pretty bad, but this code shouldn't compile. `<` between `OfType` and `TFolder` considered as operator<. To say compiler that this is specification of template use `&`:
```
var folders := items.OfType&<TFolder>;
```

**Comment by sglienke** [comment]
Is this documented somewhere? And what is the reason it interprets the < as operator?
Furthermore are there any other places where I cannot simply write < but have to prefix it with & in order to make it compile?
