### ISSUE TITLE
Падение компилятора

### ISSUE THREAD

**Issue by miks1965** [pascalabcnet/pascalabcnet#76]
```
function Curry1<T1, T2, TResult>(self: System.Func<T1, T2, TResult>): System.Func<T1, System.Func<T2, TResult>>;
begin
  var s1 := self;
  Result := value1 -> value2 -> s1 (value1, value2);
end;

begin
end.
```
Что-то у нас уже была такая ошибка

**Comment by ibond84** [comment]
Да, только теперь оно до visit_method_call вообще не доходит. То есть

**Comment by ibond84** [comment]
Нельзя мотивировать разработчика лямбд, чтобы он хотя бы посмотрел, в чем дело. А это гадание на кофейной гуще будет

**Comment by miks1965** [comment]
Да, я попробую. Я вспомнил - это была его проблема

**Comment by miks1965** [comment]
Вот что написал Роман:

Здравствуйте, Станислав Станиславович.

Я посмотрел ошибку.

Проблема с выводом типов при использовании вложенных лямбд при присваивании.

На первый взгляд кажется, что достаточно заменить вот эту строчку (строка 15604)

expression_node from = convert_strong(_assign.from);

на это

expression_node from;
var fromAsLambda = _assign.from as function_lambda_definition;
if (fromAsLambda != null)
{
var lambdaVisitMode = fromAsLambda.lambda_visit_mode;
fromAsLambda.lambda_visit_mode = LambdaVisitMode.VisitForAdvancedMethodCallProcessing;
from = convert_strong(_assign.from);
fromAsLambda.lambda_visit_mode = lambdaVisitMode;
}
else
{
from = convert_strong(_assign.from);
}
в методе public override void visit(SyntaxTree.assign _assign).

Проблема была в том, что без этих действий не происходит вывода типов  во вложенной лямбде.
На момент вывода типов в рассматриваемой лямбде должно быть

lambda_visit_mode = LambdaVisitMode.VisitForAdvancedMethodCallProcessing

Это значение имеет смысл при стадии анализа, который называется LambdaProcessingState.TypeInferencePhase.

Эти стадии изменяются при анализе узла типа block.

Смысл стадий описан кратко в дипломной работе, которую прикладываю.

Я проверял только Ваш пример, глубже не смотрел.

**Comment by miks1965** [comment]
Сделал так как сказал Роман. Сработало
