### ISSUE TITLE
Определённая структура программы ломает отладчик

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#764]
```
begin
  var ms :=
  
  Seq(
    Seq(Seq(0))
      .Select(s -> s.Cycle)
      .ToArray
  )
end.
```
Ставим точку останова на строчку `end.` и запускаем, когда программа встанет на точку останова - смотрим значение `ms`:
![image](https://user-images.githubusercontent.com/27270190/38636986-92157cdc-3dd2-11e8-93f4-15bf77a0d050.png)

Если убрать что то 1 из этой программы - отладчик нормально показывает значение `ms`.
Вместо `0` может быть любое выражение.
Вместо `Cycle` может быть любая из стандартных функций `sequence`.

У меня Win7x64, версия паскаля 3.3.5.1659

**Comment by SunSerega** [comment]
Такая последовательность тоже бесконечная, но для неё не отображает пустое окно:
```
begin
  var ms :=
  
  Seq(Seq(0))
    .Select(s -> s.Cycle)
  
end.
```
![image](https://user-images.githubusercontent.com/27270190/38637958-5c0bbcca-3dd5-11e8-97cf-ee09bd362ca7.png)

Кроме того, как я и сказал, вместо `Cycle` может быть любая из стандартных функций, к примеру:
```
begin
  var ms :=
  
  Seq(
    Seq(Seq(0))
      .Select(s -> s.Take(1))
      .ToArray
  )
end.
```
![image](https://user-images.githubusercontent.com/27270190/38638032-99aa5730-3dd5-11e8-8c0c-ea4abbae1cd2.png)

**Comment by ibond84** [comment]
ms имеет разные типы (но одинаковый интерфейс), поэтому по-разному отображаются. в первом случае это сгенерированный нами класс для yield. так что ошибки нету здесь.
