### ISSUE TITLE
Реализовать static

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#772]
```
type
  t1 = static class//статичный класс
    
    static a:byte;//статичное поле
    
  end;

begin end.
```

**Comment by ibond84** [comment]
`type t1 = class class 
class a: byte;
end;`

так лучше наверно. зачем плодить еще одно ключевое слово?

**Comment by SunSerega** [comment]
А с читабельностью что?)) Вообще, по моему, называть статичные поля `class` по мотивам Delphi было ошибкой. Язык ведь для новичков в программировании, а такая запись:
```
t1=record
class a:byte;//class в record?
end;
t2=class class end;
```
Не самая очевидная...

**Comment by miks1965** [comment]
В Oxygene - static class

**Comment by ibond84** [comment]
сделано
