### ISSUE TITLE
protected-члены не видны в yield-функции класса наследника, если класс предок в другом файле

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#775]
0.pas:
```
program prog;//не обязательно основная программа, это может быть и модуль

uses Data;

type
  t2 = class(t1)//t2 и t1 обязательно в разных файлах
  //public//не важно какой уровень доступа тут
    function f1: sequence of byte;
    begin
      a := a;//Ошибка: a не объявлен в типе t2
      
      yield 0;//обязательно функция с yield
    end;
  end;

begin end.
```
Data.pas:
```
unit Data;

type
  t1 = class
  protected //обязательно protected
    a: real;
  end;

end. 
```
[.zip архив](https://github.com/pascalabcnet/pascalabcnet/files/1920620/0.zip)

**Comment by miks1965** [comment]
Да, вижу. Захватывать это нельзя, поскольку создаётся другой класс,а из него доступ запрещен

**Comment by AIexandrKotov** [comment]
Почему запрещён, если это protected-член? Наследники могут видеть protected-члены предков.

**Comment by miks1965** [comment]
Всё просто. При развёртывании yield весь код перемещается в метод другого класса. А в нём никакие protected-члены других классов недоступны.

**Comment by SunSerega** [comment]
Это внутренности компилятора. Внутренности должны быть только удобным способом реализации интерфейса. Если внутренности влияют на интерфейс - это значит только необходимость рефакторинга внутренностей.
Иначе пользователям придётся знать внутренности компилятора, чтоб понимать почему их код не работает. Это явно плохо для обучения.

Ну а если вам, как обычно, ленивое решение - раньше в таких случаях вы ставили проверку, если код находится внутри сахарного класса - ограничения к нему не применяются.

**Comment by miks1965** [comment]
А проверьте, в C# можно ли захватывать protected-переменные

**Comment by SunSerega** [comment]
Конечно:
```
    class t1
    {
        protected int i = 5;
    }

    class t2 : t1
    {
        public IEnumerable<int> f1()
        {
            yield return base.i;
        }
    }
```
В C# полно глупых запретов, но только в виде чрезмерной защита от дурака.
А то что фичи делаются для реализации, вместо реализации для фич - это только у вас так.

**Comment by miks1965** [comment]
А во что этот код превращается в IL? Код с yield должен уходить в другой метод другого класса.

**Comment by SunSerega** [comment]
[ConsoleApp2.zip](https://github.com/pascalabcnet/pascalabcnet/files/4841906/ConsoleApp2.zip)

Тут создаётся вложенный класс.

Вообще, разве запрет на использование `protected` членов прописан не у вас в компиляторе? Это же получается кодосгенерировать:
```
type
  t1 = class
    protected a: real;
  end;
  
  t2 = class(t1)
    function f1: sequence of byte;
    begin
      a := a;
      
      yield 0;
    end;
  end;
  
begin end.
```
Если бы `Reflection.Emit` запрещал генерировать IL с использованием protected члена другого класса - это тоже не компилировалось бы.

А если вы делаете что то типа превращения `protected` в `internal` члены - тем более запрет на использование `protected` членов запрограммирован вручную в вашем коде.

**Comment by miks1965** [comment]
Ну, у нас нет вложенных классов. В этом проблема думаю.

Вы так долго пишете о ленивых решениях. Так вот. Проект - с открытым исходным кодом. Добавляйте захват защищённых полей предков. Это - хорошая задача. На неё можно потратить много времени.

**Comment by SunSerega** [comment]
> В этом проблема думаю.

Я прямо перед этим объяснил почему это не может быть проблемой:

> Если бы `Reflection.Emit` запрещал генерировать IL с использованием `protected` члена другого класса - это тоже не компилировалось бы.
> 
> А если вы делаете что то типа превращения `protected` в `internal` члены - тем более запрет на использование `protected` членов запрограммирован вручную в вашем коде.

---

> Проект - с открытым исходным кодом

Вы последнее время продолжаете об этом говорить... Понимаете - у меня есть пара (или не пара) вещей, как лямбды в вызове конструкторе предка, которые я хотел бы исправить. Но время от времени вы поиздеваетесь вместо ответа как в #2264, или просто закроете issue "как проще". И у меня снова появляется чувство, что я за вами не успею.

У меня есть свои проекты кроме вашего, которые мне более важны. В нормальной ситуации я бы исправлял некоторые открытые issue, когда они особо мешаются под ногами, но поддерживать качество кода - это ваше дело. А если вы не любите свой же проект достаточно, чтоб ставить качество на первый план - странно ожидать что кто то придёт и захочет всё за вами чистить.

---

Если вы хотите сделать временный фикс, просто чтоб основная проблема не мешала простолюдинам, не знающим даже об issue - можно не закрывать issue, а только упомянуть в названии коммита. Вроде `temp for #...`, в коротком варианте.

А последнее время создаётся впечатление, что вы закрываете issue чтобы побыстрее уменьшить их кол-во, как будто оно вам чем то мешает. И таким образом вы сами себе создаёте поощрение делать не качественные исправления.
Иронично, но часто, кроме всего прочего, это приводит к текстам ошибок, которые этим самым простолюдинам явно не понять.
Это я и называл ленивыми решениями.

**Comment by miks1965** [comment]
Предлагаю в пространстве Github не обсуждать отношение к разработчикам, свои более важные проекты, а также ваши предположения о том, что мы любим и то, что мы кому должны. Это низко.

Ещё раз подчеркну открытость проекта - каждый может его улучшить если считает, что может сделать это.
