### ISSUE TITLE
System.NullReferenceException при Ctrl-щелчке

### ISSUE THREAD

**Issue by miks1965** [pascalabcnet/pascalabcnet#781]
При Ctrl-щелчке мышью за текстом программы вываливается необрабатываемое исключение "System.NullReferenceException"

**Comment by SunSerega** [comment]
Это было добавлено только в самой последней версии. У меня не воспроизводилось, но когда я обновил - начало воспроизводится.

**Comment by SunSerega** [comment]
Ой что то вы сильно сломали, ПКМ тоже вылетает... А можно пожалуйста установщик предыдущего билда? Я не могу так работать...
