### ISSUE TITLE
Не может вывести тип возвращающего значения конструктора 

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#783]
```
function f1 := byte(0);

type
  
  t1 = record
    
    constructor(a:byte) := exit;
    
    class function f1 := new t1(f1());//Ошибка
  
  end;

begin end.
```
`Тип возвращаемого значения функции f1 не определен и не может быть выведен в данный момент. Укажите тип явно.`

Это не так, он может быть выведен, какая разница что передаётся как параметры конструктора, если он всё равно возвращает `t1`. И анализатор кода, который не так хорош в выводе типа по определению, справляется с этим.

**Comment by ibond84** [comment]
Вы не правы. f1() передается как аргумент функции, поэтому его тип должен быть задан заранее. Не переусложняйте.
