### ISSUE TITLE
Выдаёт "Невозможно вывести тип возвращаемого значения" для лямбды - процедуры

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#793]
```
procedure p1(i1,i2:integer) := exit;

begin
  Seq(0).ForEach(i1->begin//Ошибка: Невозможно вывести тип возвращаемого значения лямбда-выражения
    
    Seq(0).ForEach(i2 ->p1(i1, i2));//Если добавить begin end для внутренней лямбды - ошибки нет
    
  end);
end.
```

**Comment by SunSerega** [comment]
Да нет, ну подождите, `begin end` не той лямбде добавляется, для которой ошибку показывает. То есть `begin end` ставиться во внутренней, а ошибка пропадает для внешней.

**Comment by miks1965** [comment]
А-а, понятно. Оставляю

**Comment by ibond84** [comment]
Ну, не вижу ошибки. Возвращаемое значение внешней лямбды не может быть вычислено, потому что внутренняя лямбда неправильная.

**Comment by ibond84** [comment]
И локация правильная. Seq(0).ForEach(i2 ->p1(i2)) вне лямбды писать-то можно. Можно закрывать

**Comment by SunSerega** [comment]
1. Внутренняя лямбда правильная, это компилируется:
```
  Seq(0).ForEach(i2 -> p1(0, i2));
```
2. Возможно у вам в другом месте показывает ошибку? У меня её показывает не правильно:
![image](https://user-images.githubusercontent.com/27270190/43959247-d490d910-9cb6-11e8-911c-84c51e4489e4.png)

**Comment by SunSerega** [comment]
Да и в принципе, то что происходит во внутренней лямбде не должно никак влиять на внешнюю. 

Когда в лямбде состоящей из блока (типа `begin end` или `try except end`) нет слова `Result` - эту лямбду считает процедурой и не пытается считать возвращаемое значение. Именно про это написано в названии этой issue.

**Comment by miks1965** [comment]
Внутренняя лямбда считается функцией - из-за этого проблемы. Ошибка позиционируется не на ту лямбду

**Comment by SunSerega** [comment]
Странно, ведь у внутренней `p1()` а не `p1`, значит внутренняя тоже должна считаться процедурой...

**Comment by miks1965** [comment]
Нет, у нас там слабый вывод. Лямбда по умолчанию считается функцией. Иногда вывод догадывается, что можно сконвертировать в процедуру, иногда - нет

**Comment by SunSerega** [comment]
Везде в языке где есть скобки после имени - это считается вызовом, и такую лямбду считает процедурой. Тот же код выше:
```
Seq(0).ForEach(i2 -> p1(0, i2));
```
Если это не находится в другой лямбде - тут лямбду считает процедурой.
