### ISSUE TITLE
Операции над переменной не работают сразу после оператора, на строчке с объявлением типа

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#796]
```
type
  t1 = class
    constructor := exit;
    function f1 := new t1;
    class function operator+(a,b:t1):t1 := new t1;
  end;


begin
  var a := new t1;
  var b := new t1;
  var c := (a + b).f1;//Всё нормально
  var d: t1 := (a + b).f1;//Встречено '.', а ожидалось ';'
  var e: t1 := t1(a + b).f1;//Всё нормально
end.
```
Если это нормальное поведение - надо сделать чтоб анализатор кода не видел `f1` на строчке с `d` и выводить соответствующие сообщение об ошибке.

**Comment by ibond84** [comment]
Ну, наверно ошибка. Если в грамматике не будет конфликтов, добавить надо. Но вот это странно:

> надо сделать чтоб анализатор кода не видел f1 на строчке с d и выводить соответствующие сообщение об ошибке.

Никакого сообщения интеллисенс выводить не должен. И показывать f1 обязан, так как вырезает выражение до := Интеллисенс вообще в идеале показывать подсказки в неправильных программах. Но в силу ограниченности LR-парсеров они не могут строить дерево для неправильных программ. Поэтому многие компиляторы парсят тупым нисходящим спуском.

**Comment by SunSerega** [comment]
>Никакого сообщения интеллисенс выводить не должен

Не анализатор кода а компилятор. `Встречено '.', а ожидалось ';'`. Как то не очень информативно, особенно считая, что в большей части случаев после скобочек - можно ставить точку.

**Comment by miks1965** [comment]
Тут нельзя
