### ISSUE TITLE
sequence.ForEach((T,integer)->()) ломает сворачивание кода

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#797]
```
program prog1;//не обязательно program, но без него поставит точку сворачивания всей программы на строчку с p1

procedure p1;//для p1 тут не ставит сворачивание кода
begin
  
  var a: array of byte;//обязательно объявить отдельной переменной
  a.ForEach((b, i)-> begin end);//обязательно перегрузка которая ForEach((T,integer)->())
  
end;

begin end.
```

**Comment by ibond84** [comment]
Уточнение терминологии.
>обязательно перезагрузка которая

в русском языке принят термин "перегрузка". https://ru.wikipedia.org/wiki/%D0%9F%D0%B5%D1%80%D0%B5%D0%B3%D1%80%D1%83%D0%B7%D0%BA%D0%B0_%D0%BF%D1%80%D0%BE%D1%86%D0%B5%D0%B4%D1%83%D1%80_%D0%B8_%D1%84%D1%83%D0%BD%D0%BA%D1%86%D0%B8%D0%B9

**Comment by SunSerega** [comment]
Спасибо что уточнили) Исправил...
