### ISSUE TITLE
Позволяет начинать виртуальные цепочки в sealed классе

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#799]
```
type
  t1 = sealed class
    
    _a:integer;
    
    procedure p1; virtual := exit;//компилируется
    property a:integer read _a; virtual;//и это тоже
    
  end;

begin end.
```
В C# это запрещено, я проверил.

**Comment by miks1965** [comment]
Ну, я бы не запрещал. Человек сам так решил.

Следует сказать, что отражением такие классы можно продолжать.

И - тут Вам не C#  :)

**Comment by SunSerega** [comment]
Человек, в своём уме, не может так решить, это скорее всего ошибка. А компилятор должен помогать разработчику искать ошибки. Так же и `sealed abstract` классы запрещены, потому же.

**Comment by ibond84** [comment]
Ну код абсолютно корректный. Ну виртуальный метод, ну и что. В ява вот они все виртуальные. Закрываю
