### ISSUE TITLE
Предупреждение без данных о файле и строчке, при вызове исключения из функции

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#801]
```
function f1: byte;
begin
  raise new Exception;//похоже Result := 0 ставит после raise)))
end;

begin end.
```
`() : Обнаружен недостижимый код`

**Comment by miks1965** [comment]
```
function f1: byte;
begin
  raise new Exception;
end;

begin 
  f1; 
end.
```
У меня исключение не передаётся в оболочку. Программа завершается, но никакого сообщения нет. По Shift-F9 всё работает - исключение видно.

**Comment by ibond84** [comment]
У меня все нормально работает

**Comment by ibond84** [comment]
И  это уже другая ошибка (?), не относящаяся к предупреждениям. Закрываю.

**Comment by SunSerega** [comment]
>У меня исключение не передаётся в оболочку

Так а почему issue не создали? Или вы уже сразу и исправили?
