### ISSUE TITLE
Позволяет делать sealed abstract классы, если 1 атрибут в предописании, а другой в описании

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#803]
```
type
  t1 = abstract class;
  
  t1 = sealed class end;//компилируется нормально

begin end.
```
Работает и если поменять `sealed` и `abstract ` местами.

Как по мне - писать атрибут в предописании, но не писать его в описании - надо запретить.

**Comment by ibond84** [comment]
да, предописание это простой огрызок, объявляющий имя. надо запретить там что-то еще доописывать
