### ISSUE TITLE
foreach не может определить тип элементов для не шаблонного IEnumerable

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#804]
```
type
  t1 = class(System.Collections.IEnumerable)
    
    public function GetEnumerator: System.Collections.IEnumerator := Arr(new object).GetEnumerator;
  
  end;

begin
  foreach var o in new t1 do
    writeln(o.GetType);//тут анализатор кода не видит "o"
end.
```
Выводит, как и ожидалось:
`System.Object`

**Comment by miks1965** [comment]
Ну на то он и не шаблонный, что не может. Всё правильно - тип Object. В чем проблема-то?

**Comment by SunSerega** [comment]
С какого момента анализатор кода не должен поддерживать шаблоны? Где такое написано?

**Comment by miks1965** [comment]
Не понял. Тут нет ни одного шаблона. 
System.Collections.IEnumerable возвращает последовательность Object, значит, o должно быть типа Object, что и выводится

**Comment by miks1965** [comment]
Или Вы пишете это как баг Intellisense и только?

**Comment by SunSerega** [comment]
>Не понял. Тут нет ни одного шаблона.

А, да, я не правильно прочитал...

>Или Вы пишете это как баг Intellisense и только?

Да, `writeln(o.GetType);` лишь показывает какой тип должен показывать анализатор кода.
