### ISSUE TITLE
Невозможно вызвать шаблонный метод, когда есть не шаблонный с таким же именем

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#808]
```
type
  I1=interface
    procedure p1;
  end;
  I2<T>=interface
    procedure p1;
  end;

  t1<T>=class(I1,I2<T>)
    public procedure I1.p1 := writeln('I1.p1');
    public procedure p1 := writeln('I2.p1');
  end;

begin
  var a := new t1<byte>;
  a.p1&<byte>;//Ошибка: Спецификация при помощи угловых скобок недопустима для обычных функций (допустима для generic-функций)
end.
```
У меня возникла эта проблема, когда надо было получить `List<T>.GetEnumerator<T>`. На сколько я понимаю - сейчас невозможно получить шаблонный перечислитель для последовательности. Я попробовал ещё `as System.Collections.Generic.IEnumerable<T>`, но оно тоже наследник `System.Collections.IEnumerable`, поэтому не работает.

**Comment by ibond84** [comment]
Так вызывать нельзя. p1 это не генерик-функция. а a.p1 вызывает p1 ```I2<T>``` как и полагается.
