### ISSUE TITLE
Анализатор кода недоговаривает про свойства

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#810]
```
type
  t1=class
    private f1:byte;
    private f2:word;
    
    public property p1:byte read f1 write f1;
    public property p2:word read f2;
  end;

begin
  var a := new t1;
  a;
end.
```
Всё что показывает про `a.p1` и `a.p2`:
![image](https://user-images.githubusercontent.com/27270190/39665505-31669568-509e-11e8-8ff3-b3add8781189.png)
![image](https://user-images.githubusercontent.com/27270190/39665513-488a3db2-509e-11e8-896d-0588e0369590.png)

У стандартных типов ещё показывает `virtual`/`override` и `readonly`, котого в паскале вообще нет:
![image](https://user-images.githubusercontent.com/27270190/39665531-a770af5a-509e-11e8-9f28-01787a00f5de.png)

Добавьте, пожалуйста, возможность видеть `virtual`/`override` и `read write`/`read`/`write` которые бы означали, можно ли читать/перезаписывать свойства.

**Comment by ibond84** [comment]
read write без разделителей выглядит уродливо. к тому же какая разница как там написано. readonly понятно всем. поэтому делаю readonly. write-only это вообще бред какой-то

**Comment by miks1965** [comment]
write свойства существуют - очень редко, но бывают нужны.

Я бы сделал 
```
property t1.p1: byte; read; write; 
```
примерно как в C#.
Виртуальность свойства в C# не отображается
