### ISSUE TITLE
Короткая запись подпрограмм не работает для деструкторов

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#812]
```
type
  t1=class
    destructor d1 := writeln(0);
  end;

begin end.
```
Для конструкторов [сделали](https://github.com/pascalabcnet/pascalabcnet/issues/575), а про деструкторы забыли...

**Comment by ibond84** [comment]
деструкторы не используются.

**Comment by SunSerega** [comment]
В смысле?

**Comment by ibond84** [comment]
В смысле они ниоткуда не вызываются. Имеет ли смысл делать им честь, если они не нужны?

**Comment by ibond84** [comment]
Из справки.
Поскольку в PascalABC.NET память управляется сборщиком мусора, деструктор в PascalABC.NET не играет никакой роли и представляет собой обычную процедуру-метод.

**Comment by miks1965** [comment]
Для деструкторов не будем делать. Они введены исключительно для совместимости кода с Delphi
