### ISSUE TITLE
Не видны переопределенные одноименные методы в предке, определенном в dll

### ISSUE THREAD

**Issue by miks1965** [pascalabcnet/pascalabcnet#815]
```
type
  MyList<T> = class(List<T>)
  public
    function IndexOf(): integer; 
    begin Print(666); end;
  end;

begin
  var l := new MyList<integer>;
  l.IndexOf(7).Print;
end.
```
В  NetHelper.cs пока закомментированы строки:
                            // SSM 2018.05.05
                            //temp.symbol_kind = symbol_kind.sk_overload_function;

Они решают проблему, но не компилируется PABCSystem

В SymbolTable.cs этот код неверно работает. Для функций из dll возвращается symbol_kind.sk_none
и это условие их обрезает. 
Попытка же написать 
```
temp.symbol_kind = symbol_kind.sk_overload_function;
```
пРИВОДИТ К ПАДЕНИЮ В pabcsYSTEMK В РАЙОНЕ ПЕРЕОПРЕДЕЛЕНИЯ bIGiNTEGER OPERATOR DIV
```
        private bool IsNormal(SymbolInfo to, SymbolInfo add)
        {
            return //true;
                (to == null) || (to.scope == null) || ((to.scope != null) && //to.scope == null не нужно?
                (((to.symbol_kind == symbol_kind.sk_none) && (add.symbol_kind == symbol_kind.sk_none)) && (to.scope == add.scope))
                ||
                ((to.symbol_kind == symbol_kind.sk_overload_function) && (add.symbol_kind == symbol_kind.sk_overload_function))
                ||
                ((to.symbol_kind == symbol_kind.sk_overload_procedure) && (add.symbol_kind == symbol_kind.sk_overload_procedure))
                );
        }
```

**Comment by ibond84** [comment]
Этот IsNormal какой-то костыль. Я уже не помню, почему мы ввели плоскую таблицу символов (а не дерево таблиц)? Из-за производительности?

**Comment by miks1965** [comment]
Вообщем, я закрываю этот баг. Не знаю, почему тест не работает в 32-битном режиме. Всё там правильно.
