### ISSUE TITLE
Неправильно отображает тип элементов последовательности при преобразовании ее элементов в System.Nullable<T>

### ISSUE THREAD

**Issue by VladislavMoldovan** [pascalabcnet/pascalabcnet#821]
```
begin
 var S := Arr(1, 2, 3).Select(x -> new System.Nullable<integer>(x));
end.
```
Отображает: `sequence of integer`, но ожидалось: `sequence of System.Nullable<integer>`.
![nullablesequenceintellisenceerror](https://user-images.githubusercontent.com/37166763/39809362-3db79a12-538a-11e8-9548-675f07f33d8b.jpg)

**Comment by ibond84** [comment]
дубль
