### ISSUE TITLE
После копирования исходников - не видит содержимое библиотеки

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#827]
1. Открываем и запускаем программу из `PABCWork.NET\Samples\!MainFeatures\04_Units\CallC#`;
2. Выделяем папку этой программы (`CallC#`) и нажимаем Ctrl+C и Ctrl+V чтоб скопировать;
3. Открываем и запускаем копию;
4. Ошибка: `CallCS.pas(8) : Неизвестное имя 'Class1'`.

Это именно с классами из `dll`, просто классы так не ломаются.

**Comment by miks1965** [comment]
Всё запускается. И по-другому быть не может. dll ищется в текущей папке
