### ISSUE TITLE
Interface в namespace требует описание

### ISSUE THREAD

**Issue by DjArt** [pascalabcnet/pascalabcnet#828]
Весьма странная вещь. Однако, если поменять interface на class, всё компилируется.
![default](https://user-images.githubusercontent.com/1651555/39935216-ced39ab0-5537-11e8-89af-29788b5f203c.png)

**Comment by DjArt** [comment]
Ах да, версия Pascal:
PascalABCCompiler.Core v3.3.5.1662 (11.05.2018), debug version
Runtime version: 4.0.30319.42000
OS version: Microsoft Windows NT 6.2.9200.0
Processor count: 4
WorkingSet: 70580 kb

**Comment by SunSerega** [comment]
Я попробовал без проекта Windows.Forms (в отдельном файле) - ошибки нету.

**Comment by DjArt** [comment]
@Ну таки и у меня никаких формочек нет. Да и вовсе не в этом дело. Суть именно в фиче namespace, если это модуль(unit) или просто файл с основным кодом библиотеки/программы, всё работает как надо.

**Comment by SunSerega** [comment]
Проекты Windows.Forms делают много всего чего не видно. Попробуйте то же самое в отдельном файле, не проекте (закрыв проект).

**Comment by DjArt** [comment]
@SunSerega Пробовал, работает. Ну а если объективно, сами подумайте, при чём тут Windows.Forms, коль компилятор на парсинг исходника ругается? Тут до исполнения кода в принципе дело не дошло, учитывая то, что это при всём этом библиотека, а не исполняемый файл. Мне требуется чистокровный .Net interface в самой обычной .Net библиотеке, без .pcu модулей и прочего(а стандартную библиотеку PascalABC вообще бы предпочёл отдельным dll, а не интегрированным модулем). А писать все интерфейсы в одном файле желанием не горю, учитывая невозможность создавать вложенные namespace с данной ошибкой.

**Comment by SunSerega** [comment]
А вот у меня не воспроизводится на том же билде (1662).

>при чём тут Windows.Forms, коль компилятор на парсинг исходника ругается?

Проекты `Windows.Forms` много чего добавляют в код, не показывая. Вы попробуйте откомпилировать исходники проекта, а не сам проект - компилятор сразу начнёт на всё подряд ругаться. Вот я подумал что это может и в обратную сторону действовать.

**Comment by DjArt** [comment]
Закрыто с исправлениями?

**Comment by ibond84** [comment]
Да, с исправлением. Привязал коммит к issue.

**Comment by DjArt** [comment]
Спасибо, это важно для меня✊
