### ISSUE TITLE
Расширение для Visual Studio

### ISSUE THREAD

**Issue by DjArt** [pascalabcnet/pascalabcnet#830]
Могу заняться сам этим в своё свободное время. Однако, нужен стандарт языка(#278).

**Comment by RustemB** [comment]
В каком смысле стандарт?

**Comment by DjArt** [comment]
@RustemB
Описание синтаксических возможностей и особенностей языка. К примеру, код:
`function Test(var x : string; params b : array of int) : Func<byte, long>; virtual; override;`
1. Аргумент `params b : array of int` всегда ли должен быть последним аргументом в методе?
2. Аргумент `var x : string`, могу ли я воспользоваться им, как эквивалентной конструкцией в C# `out string x`?
3. Каков должен быть порядок модификаторов `virtual;  override;`, ну и важен ли он вообще?
И всякие подобные вопросы, ответы на которые должны быть описаны в стандарте языка.

**Comment by miks1965** [comment]
Используйте справку по языку. Там все ваши вопросы описаны.

**Comment by DjArt** [comment]
@miks1965 это, конечно, известно. Ну а всё же, было бы неплохо его иметь, некоторые задумываемые изменения явно не описаны. Даже если реализация не полностью соответствует стандарту, то хотя бы видно направление.

**Comment by SunSerega** [comment]
А по моему надо сделать сначала работающий прототип, а потом уже в нём редактировать анализатор кода, в особых местах, где реализация не соответствует стандарту в `ABCPascal.y`.
