### ISSUE TITLE
Ошибка компиляции при реализации интерфейса абстрактным классом

### ISSUE THREAD

**Issue by VladislavMoldovan** [pascalabcnet/pascalabcnet#840]
```
type
  ITest = interface
    procedure Invoke();
  end;
  
  T = abstract class(ITest)
    procedure Invoke() := exit;
  end;

begin
end.
```
Или это нормальное поведение?

**Comment by SunSerega** [comment]
Пожалуйста, смотрите на то что написано в ошибке:
`0.pas(6) : Функция класса T, реализующая метод Invoke интерфейса ITest, должна быть нестатической с уровнем доступа public `
Добавляем `public` и компилируется.

**Comment by SunSerega** [comment]
Кстати, @VladislavMoldovan, вы сами можете закрывать issue которые создали.
