### ISSUE TITLE
Реализовать автосвойства

### ISSUE THREAD

**Issue by VladislavMoldovan** [pascalabcnet/pascalabcnet#844]
Например:
```
type
  TMy = class
  public
    auto property Prop: integer;
  end;

begin
end.
```

**Comment by SunSerega** [comment]
И во что оно должно разворачиваться?

**Comment by VladislavMoldovan** [comment]
Думаю в:
```
type
  TMy = class
  private
    _backingFieldProp: integer;
  
  public
    property Prop: integer read _backingFieldProp write _backingFieldProp;
  end;

begin
end.
```

**Comment by miks1965** [comment]
Это хорошее дело. У нас есть автоклассы. Автосвойства тоже хороши.

Надо бы как-то разделить Issue, связанные с ошибками, багами и Issue, связанные с желаемым расширением языка. А то мы задохнёмся.

**Comment by SunSerega** [comment]
Ну, на гитхабе чтоб разделить используют лэйблы, у вас же уже есть `bug` и `enhancement`, только `error` не хватает... А так - удобнее, наверное, будет только с другим сайтом.

**Comment by miks1965** [comment]
Тут проблема в том, что автосвойства в основном используются в C# со спецификаторами get; private set. Как это задать в Паскале синтаксически - я не знаю.

**Comment by SunSerega** [comment]
Ну вон выше писали:
```
    auto property Prop: integer;
```
Можно ещё, раз автоматически выбирается ввод/вывод свойства:
```
    property Prop: integer auto;
```

**Comment by miks1965** [comment]
Нет, не поняли. Как сделать автосвойство с доступом только на чтение, а на запись внутри?

**Comment by miks1965** [comment]
Пока нет чёткой концепции - закрываю. Для исходного предложения следует использовать открытые поля

**Comment by miks1965** [comment]
Переоткрыл. Сделаем в таком виде:

property p: integer read write;

**Comment by devapromix** [comment]
Здраствуйте! Если только для чтения, то:

property p: integer read;

Верно?

**Comment by miks1965** [comment]
Да, разумеется

**Comment by SunSerega** [comment]
А слово `auto`, надеюсь, надо будет всё равно ставить? А то ведь ошибки пойдут не понятные...

**Comment by miks1965** [comment]
Какие?

**Comment by SunSerega** [comment]
В C# `get` и `set` это не функции которые можно вызвать из `Main`, а в паскале `write` и `read`. Из за этого и так уже есть ничего не объясняющие ошибки:
```
type
  t1 = class
    property p: object write write;
  end;

begin end.
```
`Ошибка: Неизвестное имя 'write'`
Если разобраться в кишках компилятора - это конечно логично. Но новичку это будет совершенно не понятно.

А если добавить ещё возможность писать `write` без чего либо после него - ошибки в подобных местах станут ещё более непонятными.

**Comment by miks1965** [comment]
Да. Но к автосвойствам это не имеет никакого отношения.

**Comment by SunSerega** [comment]
У них очень похоже определение:
`property p: integer read write;` (это вы выше написали)
Если будет именно так, а не так:
`auto property p: integer read write;`
То это ещё больше усложнит ситуацию. А значит и может добавить непонятные ошибки. А если будет `auto` перед всем - то у него, получается, есть свой отличительный знак, и ситуацию с обычными свойствами это усложнять не будет.

**Comment by miks1965** [comment]
Сделано
