### ISSUE TITLE
Сделать именованные аргументы для функций, процедур и методов

### ISSUE THREAD

**Issue by VladislavMoldovan** [pascalabcnet/pascalabcnet#846]
Как: [Named and Optional Arguments (C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/named-and-optional-arguments)

**Comment by miks1965** [comment]
Да, понимаю. Не будем делать - у нас грамматика не выдержит. У нас она и так перегружена
