### ISSUE TITLE
4+Seq(1,2,3) не работает хотя должно

### ISSUE THREAD

**Issue by miks1965** [pascalabcnet/pascalabcnet#85]
```
begin
  var sss := 4+Seq(1,2,3);
end.
```
Должно работать поскольку в PABCSystem определен метод

```
function operator+<T>(b: T; a: sequence of T): sequence of T; extensionmethod;
begin
  Result := new T[1](b);
  Result := Result.Concat(a);
end;
```

**Comment by ibond84** [comment]
Если подцеплять к + этот метод, то возникает ошибка "несколько методов может быть вызвано", когда прибавляется символ к строке. причем не компилируется сам PABCSystem.pas

**Comment by ibond84** [comment]
Нужно мерять расстояния между типами и кортежами типов. что-то вроде (char, string) > (char, IEnumerable<char>) . непосредственно перед вызовом return AddError<function_node>(new SeveralFunctionsCanBeCalled(loc,set_of_possible_functions));
