### ISSUE TITLE
Реализация Haskell для PascalABC.Net

### ISSUE THREAD

**Issue by LmTinyToon** [pascalabcnet/pascalabcnet#854]
Доброго времени суток всем. Наверное вопрос не по теме и тут его быть не должно, но решил задать его здесь. Я нашел интересную статью http://pascalabc.net/downloads/DiplomBushHaskell.pdf (реализация Haskell для PascalABC.Net). Очень хотелось бы поиграться с этим. Но насколько я понял, текущий репозиторий не включает поддержку Haskell для PascalABC.Net (Например не нашел папку HaskellParser). C автором пока не связывался, никто не сможет подсказать где это найти?

**Comment by miks1965** [comment]
Нет, это заброшенный давний проект. Не пишите такое в Issue
