### ISSUE TITLE
Захватывается не та Self

### ISSUE THREAD

**Issue by miks1965** [pascalabcnet/pascalabcnet#855]
```
type A = class
  procedure p1(self: integer); 
  begin
    var p: procedure := procedure->begin
      self.Print;
    end;
  end;
end;

begin 

end.
```

**Comment by SunSerega** [comment]
Ну, `Print` и не должно компилироваться, нету его перезагрузки для типа `A`.
```
type A = class
  procedure p1(self: integer); 
  begin
    var p: procedure := procedure->begin
      writeln(self.GetType);
    end;
    p;
  end;
end;

begin 
  (new A).p1(0)
end.
```
Это выводит `Program1.A`.

**Comment by miks1965** [comment]
Должна захватываться Self из параметра

**Comment by miks1965** [comment]
Вообще, надо запретить параметры обычных методов с именем Self - там в таблице символов - ужас - два одинаковых имени Self в одном пространстве имён. Вот это же ругается:
```
type A = class
  procedure p1(); 
  begin
    var self: integer;
  end;
end;

begin 
end.
```
Думаю, Ыуда-переменные разрешили в параметрах из-за extension-vtnjljd/ Ну так только там надо и оставить.

**Comment by miks1965** [comment]
Вообщем, дело тут не в лямбдах. Надо запретить у нас следующий код:
```
type A = class
  self: integer;
  procedure p1(); 
  begin
  end;
end;

begin 
end.
```
и следующий:
```

```

**Comment by miks1965** [comment]
Исправилось само. Закрываю
