### ISSUE TITLE
Анализатор кода сломан для System.Math.DivRem

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#856]
```
begin
  System.Math.DivRem;//при открытии скобочки тут ничего не происходит
end.
```

**Comment by SunSerega** [comment]
И кстати у него не правильное описание. Остаток записывает в параметр `result`, а возвращает как раз результат деления. А написано на оборот.

**Comment by miks1965** [comment]
Думаю, это из-за result в имени var - параметра

**Comment by SunSerega** [comment]
Ошибку анализатора кода исправили, а что с описанием то?

**Comment by miks1965** [comment]
Описание - это к разработчикам .NET
