### ISSUE TITLE
Прикольное сообщение об ошибке

### ISSUE THREAD

**Issue by miks1965** [pascalabcnet/pascalabcnet#87]
```
begin
  foreach var x in 1 do
    Print(x);
end.
```
Сообщение - неправильное:
Невозможно выполнить оператор foreach по выражению типа PascalABCCompiler.TreeRealization.compiled_type_node

**Comment by ibond84** [comment]
Это какой-то новый баг:
 AddError(in_what.location, "CAN_NOT_EXECUTE_FOREACH_BY_EXPR_OF_TYPE_{0}",in_what.type)
Вообще у нас вывод ошибок остался недоделанным. Где-то создаются объекты ошибок, где передаются строки. Это мне не нравится. Раньше было все стройно.
