### ISSUE TITLE
Оболочка не ловит исключение

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#870]
```
procedure p1;
begin
  raise new Exception;
end;

begin
  p1;
end.
```
Запускаем по `Shift+F9` - исключение есть.
Запускаем по `F9` - исключения нет.

**Comment by ibond84** [comment]
у меня все ловит

**Comment by SunSerega** [comment]
А у меня и [вот](https://github.com/pascalabcnet/pascalabcnet/issues/801) у @miks1965 не ловит. Вы в той issue говорили об этом, но отдельную issue не создали.

**Comment by ibond84** [comment]
Все ловит

**Comment by SunSerega** [comment]
Да, теперь и у меня исправилось.
@miks1965 а у вас?
