### ISSUE TITLE
Undefined FileName при кортежном присвоении 8 элементов

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#874]
```
begin
  var (a,b,c,d,e,f,g,h) := (1,2,3,4,5,6,7,8);
end.
```
`Undefined FileName(0) : Item8 не объявлен в типе Tuple<integer,integer,integer,integer,integer,integer,integer,Tuple<integer>>`

**Comment by miks1965** [comment]
Ну тоже закрыт
