### ISSUE TITLE
Не правильно работает с кортежами с >7 элементами

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#876]
```
begin
  var a := (1,2,3,4,5,6,7,8);
  writeln(a.GetType);
end.
```
Тут анализатор кода показывает что все элементы `a` - `integer`, но `a.GetType` показывает что последний элемент это кортеж.

А вообще в `.Net` обычно делают так что если, к примеру, элементов будет 10 - 7 из них засовывает в основную переменную, а из последних трех элементов создаёт кортеж и засовывает его в 8-ой элемент. Правда в C# вроде этого нет из за проблем с бюджетом или чего то типа того.

**Comment by ibond84** [comment]
Интеллисенс показывает то, что написано. var a: (integer,integer,integer,...) а уж правильный ли это тупл, его не интересует.

**Comment by SunSerega** [comment]
Я понимаю с точкой после функции, когда не все параметры введены, то что всё равно показывает действия для возвращаемого значения. Но ради чего тут ему врать?
