### ISSUE TITLE
Из метода расширения для <> не вызывается метод расширения =

### ISSUE THREAD

**Issue by miks1965** [pascalabcnet/pascalabcnet#877]
```
begin
  var a := (1,2);
  var b := (1,2);
  Print(a=b,a<>b);
end.
```

**Comment by miks1965** [comment]
Выводит True

**Comment by ibond84** [comment]
Это связано с изменениями в PABCSystem.pas. Из extension-операторов не видны другие операторы. Кажется там были какие-то проблемы. Если их не удастся решить, то надо изменить extension-операторы в системном модуле (как было раньше)

**Comment by miks1965** [comment]
Закрою я этот Issue и открою пару новых
