### ISSUE TITLE
Сделать IDE более доступной для незрячих

### ISSUE THREAD

**Issue by spectatorBH** [pascalabcnet/pascalabcnet#878]
Формализованный список задач и предложений по мотивам обращения одного из [пользователей](http://forum.mmcs.sfedu.ru/t/zamechaniya-i-predlozheniya/143/479?u=spectatorbh):

1. Дополнить среду и редактор кода недостающими шорткатами:
- [ ] для всех команд главного меню;
- [ ] для всех команд контекстного меню;
- [ ] для навигации по окнам и табам;
- [ ] для эффективного управления редактором без мыши (Redo?).

2. Добиться совместимости редактора для его озвучивания стандартными скрин-ридерами:
- [ ] при выделении текста по Shift-стрелки (влево/вправо/вверх/вниз);
- [ ] ???

3. Дополнить справку:
- [ ] описать все шорткаты среды и редактора (как старые, так и новые) на отдельной странице;
- [ ] ???

**Comment by spectatorBH** [comment]
1. Предлагаю добавить следующие недостающие шорткаты для IDE:

- Меню “Файл”
    - Новый проект **Ctrl + Alt + N**
    - Открыть проект **Ctrl + Alt + O**
    - Сохранить всё **Ctrl + Alt + S**
    - Закрыть **Ctrl + W**
    - Закрыть всё, кроме текущего **Ctrl + Alt + W**
- Меню “Правка”
    - Найти далее **F3** (_вместо Ctrl + L_)
    - Найти ранее **Shift + F3** (_новая возможность?_)
    - Удалить все закладки **Ctrl + Shift + F2**
- Меню “Вид”
    - Окно вывода **Alt + 1**
    - Список ошибок **Alt + 2**
    - Сообщения компилятора **Alt + 3**
    - Результат поиска символов **Alt + 4**
    - Локальные переменные **Alt + 5**
    - Просмотр выражений **Alt + 6**
    - Окно дизассемблирования **Alt + 7**
    - Панель навигации по коду **Alt + 0**
- Меню “Программа”
    - Параметры командной строки… **Alt + F10**
    - Шаг с выходом из подпрограммы **F6**
- Меню “Сервис”
    - Настройки… **F10**
    - Перейти к реализации **Ctrl + Shift + Enter**
    - Сгенерировать реализацию **Ctrl + Shift + I** (_от англ. ‘Implementation’_)
    - Найти все ссылки **Alt + Shift + F**
- Меню “Модули”
    - Сообщить об ошибке **Alt + F1**
---
- Для "скрытых" функций редактора:
    - Восстановить (Redo) **Ctrl + Y**

**Comment by miks1965** [comment]
"Добиться совместимости редактора для его озвучивания стандартными скрин-ридерами:"

Этого мы не сможем сделать

**Comment by miks1965** [comment]
Собственно, ни в одной из просмотренных мной IDE нет такого чтобы все пункты меню покрывались горячими клавишами. Какие-то может быть.

Но в такой постановке как указано в заголовке я этот Issue закрываю.
В такой постановке мы этого не сможем сделать

**Comment by spectatorBH** [comment]
Во-первых, причем тут сравнение с другими IDE -- реальный человек обратился с конкретной проблемой и просьбой, можно же иногда сделать по-своему и лучше, чем другие?

Во-вторых, вы позиционируете свою среду как простую, учебную и легкодоступную для начинающих. Речь же не идет о многих десятках (если не сотнях) пунктов меню и команд профессиональных сред, а всего лишь о 23-24 простых шорткатах. Неужели это такая неподъемная задача? Кстати, её вполне могут реализовать и ваши студенты.

Кроме того, во многих известных мне качественных IDE/редакторах кода (Notepad++, SynWrite, Sublime Text, LightTable, VS Code, Visual Studio, Lazarus, Code Typhon и др.) есть возможность добавить или переназначить комбинацию клавиш вообще для любой команды редактора/среды/плагина/макроса, даже если "из коробки" этого стандартно не определено. Здесь же речь идет о гораздо более простом случае -- жесткой привязке шорткатов к уже реализованным функциям.

И потом, наотмашь закрывать качественно оформленную задачу с конкретными предложениями только на основании того, что вы лично не можете реализовать или проверить один из пунктов? Вполне возможно, в этом могут помочь другие участники сообщества. Может стоило сначала хотя бы посоветоваться с комьюнити и спросить, кто может помочь со специфической фичей?

И даже если не будет ответных предложений, это еще не повод закрывать всю мета-задачу из-за 1 пункта -- по мере реализации остальных этот пункт можно было бы либо вычеркнуть, либо упростить. Он здесь присутствует (как, впрочем, и все остальные) только лишь для полноты реализации конечной цели -- эффективной практической доступности IDE для незрячих студентов.

И последнее, Станислав Станиславович, пожалуйста, не стоит каждую задачу воспринимать на свой личный счет -- никто не заставляет лично вас всё это реализовывать, да еще срочно. Пускай висит, пока у кого-нибудь руки не дойдут. Задача-то достойная -- эти люди и так во всем ограничены...

**Comment by miks1965** [comment]
Нет, Вы не поняли. Шорткаты и незрячие - это две разные цели. Я предлагаю не совмещать в одном Issue две разные цели. Один Issue - одна цель. Оформите Issue с шорткатами  -я его не закрою - будем обсуждать.

**Comment by spectatorBH** [comment]
Хорошо, я пересоздам задачу в урезанном варианте, если считаете, что она слишком громоздка в таком виде. Только зачем же было сразу закрывать, я мог бы просто её отредактировать после обсуждения -- с таким авторитарным стилем управления полноценное открытое коммьюнити (с теми, кто готов писать код) никогда и не появится, скорее потихоньку загнется то немногое, что есть...

По поводу цели: я не взял ёе с потолка -- она фактически была сформулирована человеком, который столкнулся с конкретным набором ограничений в среде. Разумеется, шорткаты могут оказаться полезны и кому-то еще, поэтому соглашусь сделать отдельный issue.
