### ISSUE TITLE
Сделать плагин, позволяющий устанавливать пользовательские горячие клавиши

### ISSUE THREAD

**Issue by spectatorBH** [pascalabcnet/pascalabcnet#881]
По мотивам обращения одного из [пользователей](http://forum.mmcs.sfedu.ru/t/zamechaniya-i-predlozheniya/143/479?u=spectatorbh) предлагаю добавить следующие недостающие шорткаты для уже существующих функций IDE:

- Меню “Файл”
    - Новый проект **Ctrl + Alt + N**
    - Открыть проект **Ctrl + Alt + O**
    - Сохранить всё **Ctrl + Alt + S**
    - Закрыть **Ctrl + W**
    - Закрыть всё, кроме текущего **Ctrl + Alt + W**
- Меню “Правка”
    - Найти далее **F3** (_вместо Ctrl + L_)
    - <del>Найти ранее **Shift + F3** (_новая возможность?_)</del>
    - Удалить все закладки **Ctrl + Shift + F2**
- Меню “Вид”
    - Окно вывода **Alt + 1**
    - Список ошибок **Alt + 2**
    - Сообщения компилятора **Alt + 3**
    - Результат поиска символов **Alt + 4**
    - Локальные переменные **Alt + 5**
    - Просмотр выражений **Alt + 6**
    - Окно дизассемблирования **Alt + 7**
    - Панель навигации по коду **Alt + 0**
- Меню “Программа”
    - Параметры командной строки… **Alt + F10**
    - Шаг с выходом из подпрограммы **F6**
- Меню “Сервис”
    - Настройки… **F10**
    - Перейти к реализации **Ctrl + Shift + Enter**
    - Сгенерировать реализацию **Ctrl + Shift + I** (_от англ. ‘Implementation’_)
    - Найти все ссылки **Alt + Shift + F**
- Меню “Модули”
    - Сообщить об ошибке **Alt + F1**
---
- <del>Для "скрытых" функций редактора:
    - Восстановить (Redo) **Ctrl + Y**</del>

**Comment by miks1965** [comment]
Найти далее F3 (вместо Ctrl + L)

Там все пункты меню на Ctrl - странно делать F3 только потому что кому-то так удобно

**Comment by miks1965** [comment]
Закрыть Ctrl + W
Закрыть всё, кроме текущего Ctrl + Alt + W

У нас школьники постоянно какие-то клавиши нажимают - если при этом что-то закроется - тм более всё - это будет плохо. Это надо оставить без горячих клавиш

**Comment by miks1965** [comment]
Переделал в более общую задачу. Мы не хотим портить базовую оболочку лишними горячими клавишами.

**Comment by spectatorBH** [comment]
Насчет F3: ничего странного и нелогичного -- пара Ctrl-F / F3 классическая, в приложениях Windows используется уже как минимум лет 20 во всех известных мне редакторах/IDE/текстовых процессорах и прочих приложениях. Так, напр., изначально было сделано в MS Office, WPS Office, Softmaker Office, Visual Studio Code, Sublime Text, Notepad++, Notapad2 и прочих. 

Зачем же изобретать велосипед и заставлять использовать нестандартные комбинации для столь универсальных команд? Тем более что нынешняя Ctrl-L объективно менее удобна -- F3 по смыслу обычно нажимается несколько раз подряд после однократного вызова Ctrl-F, что позволяет это делать "вслепую" одной рукой, второй свободно контролируя мышь или клавиши управления курсором.

По причине совместимости c популярным софтом я бы также заменил Ctrl-R на Ctrl-H. А для полноты реализации добавил бы сочетание Ctrl-Y (Redo=повторить операцию) и функцию Shift-F3 (Find Previous=найти предыдущий).

**Comment by spectatorBH** [comment]
> У нас школьники постоянно какие-то клавиши нажимают - если при этом что-то закроется - тем более всё - это будет плохо. Это надо оставить без горячих клавиш

Странная аргументация. Вы что, регулярно обучаете 5-летних детей, у которых еще не развита логика и мелкая моторика пальцев? Как же они у вас под Windows то вообще работают -- там же везде ужасные скрытые комбинации клавиш -- Alt-F4 тоже глобально заблокирован? А Ctrl-A/Ctrl-X? А Win-D?

Вот в этом то и проблема -- люди, которые хотят в среде эффективно работать, а не спотыкаться все время, периодически предлагают что-то изменить или добавить для повышения эффективности труда. Но для вас важнее всего ваши малолетние школьники, для которых вы читаете лекции в воскресной школе. Так зачем же дурить всем остальным головы, претендуя чуть ли не на production use? Пожалуйста, не называйте это "мощной средой разработки", назовите просто "среда Паскаль для воскресной школы" -- и дело с концом, мы все разойдемся, кто уже не ходит в школу. 

P.S. Извините за резкость.

**Comment by ibond84** [comment]
>Вы что, регулярно обучаете 5-летних детей, у которых еще не развита логика и мелкая моторика пальцев?

Да вы предлагаете просто  ужасный шорткат. W стоит на клавиатуре рядом с S. Можно реально промахнуться.  И для этого уже есть нормальный шорткат: Ctrl+F4.

**Comment by ibond84** [comment]
С альтами тоже неочевидно, запоминать цифиры. В студии например Ctrl+E это список ошибок. Просто и понятно

**Comment by spectatorBH** [comment]
Про Alt-ы с цифрами не спорю -- это мой собственный креатив, т.к. ничего широкораспространенного для этих целей нет, в каждой среде могут быть любые свои. Я только пытался поставить себя на место незрячего человека, с обращения которого все и началось: поскольку придумать качественные мнемонические шорткаты для переключения между спец-окнами вряд ли возможно (из-за того что среда изначально русскоязычная), мне пришла в голову идея их просто пронумеровать каким-либо образом и связать с простой клавишей-модификатором -- так, чтобы итоговые комбинации были максимально простыми (т.е. можно было нажимать одной рукой) и ни с чем не конфликтовали.

Что касается Ctrl-W (закрыть файл/документ/таб) -- это опять же не я придумал, так уж издавна заведено у Microsoft и многих других производителей, можете проверить. В нашем случае можно еще добавить опцию с дополнительным окном подтверждения для детей (даже при отсутствии несохраненных изменений). Думаю, такой вариант устроил бы всех.

**Comment by SunSerega** [comment]
Про Ctrl+W, по моему, спор вообще зря, паскаль всё равно спрашивает закрывать ли, если вкладка не сохранена. Так же и у школьников с этим проблем не должно быть.

**Comment by spectatorBH** [comment]
Думаю, решать эту задачу через создание плагина -- излишне. Это будет гораздо сложнее, чем прописать пару десятков шорткатов вручную.

**Comment by spectatorBH** [comment]
Ctrl-F4 хотя бы пропишите в контекстном меню, иначе про него никак не узнать.

Кстати, в Visual Studio Code до сих пор используются оба сочетания, как эквивалентные: и Ctrl-F4, и Ctrl-W. А в "большом" Visual Studio <Ctrl-W>, похоже, просто использовали для других целей, т.к. там своих уникальных команд намного больше. И при этом это чуть ли не единственное исключение -- все остальные развитые среды, очевидно, не считают, Ctrl-W таким уж "ляпом".

**Comment by ibond84** [comment]
> все остальные развитые среды, очевидно, не считают, Ctrl-W таким уж "ляпом".

Ну это их проблемы.
