### ISSUE TITLE
Ctrl+Space не дополняет недописанное имя пространства имён

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#883]
К примеру если после `System.I` нажать Ctrl+Space - он предложит `IO`, но только потому что в `System` есть другие имена начинающиеся на `i`. Но если после `System.IO.comp` нажать Ctrl+Space - он не предлагает `Compression`. А точнее он вообще ничего не предлагает.

**Comment by ibond84** [comment]
Вы уточняйте, что речь идет именно о маленькой букве.

**Comment by SunSerega** [comment]
Ах вот как, я сам не заметил что это из за маленькой буквы...
