### ISSUE TITLE
Анализатор кода не видит переменную лямбды если результат Select сразу передаётся куда то

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#884]
```
procedure p1(b: sequence of byte) := exit;//любая процедура, при том, не обязательно короткая. writeln тоже работает

begin
  var hs := new HashSet<byte>;
  p1(hs.Select(a -> a));//тут анализатор кода не видит a
end.
````

**Comment by miks1965** [comment]
Анализатор кода очень слабо работает с лямбдами - можно сказать, вооще не работает. До прошлого года не работал, в этом году кое-что удалось сделать. 

Считаю, что Issue надо закрыть и закрывать Issue, связанные с лямбдами в Intellisense.

Пусть ibond решит и закроет.

**Comment by SunSerega** [comment]
То есть, раз плохо работает, вообще не исправлять?

**Comment by ibond84** [comment]
> Анализатор кода очень слабо работает с лямбдами - можно сказать, вооще не работает.

Ну если вы о лямбде при одной открытой скобке, то с текущим LR-парсером, не строящим дерево для неправильных программ, врядли возможно соорудить что-то работающее.

**Comment by ibond84** [comment]
да все там просто. флаг не проставлялся, добавляющий a в scope. при выборе перегруженной функции и вычислении типа a, тот не должен добавляться  в scope. исправлено
