### ISSUE TITLE
Комментарий ломает подсвечивание class-end

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#898]
```
type
  t1 = {комментарий} class
    
  end;

begin end.
```
Тут `class`-`end` не подсвечиваются если поставить на них курсор.

**Comment by RustemB** [comment]
Авторы же говорили, что редактор не их. И возиться с ним не будут. Но есть идея: написать редактор самому(😄) или написать плагин для любимого текстового редактора, например VS Code...

**Comment by ibond84** [comment]
class - end подсвечиваем мы сами. и редактор не наш да, но исходники мы меняем иногда (только какие-то несложные багофиксы)
