### ISSUE TITLE
Event'ы не выполняются одновременно

### ISSUE THREAD

**Issue by Julia-321** [pascalabcnet/pascalabcnet#900]
Пока работает функция, вызванная ивентом, никакие другие ивенты не работают. Можно ли исправить это с помощью omp, или это вообще нереально?

**Comment by SunSerega** [comment]
Это [сюда](http://forum.mmcs.sfedu.ru/t/pomoshh-novichkam/263/699) писать, в issue только ошибки. И там же нормально опишите, с примером кода.

**Comment by Julia-321** [comment]
Ок, сорри что не туда

сб, 9 июн 2018 г., 14:31 Sun Serega <notifications@github.com>:

**Comment by ibond84** [comment]
Вам надо реализовывать это самостоятельно. Готовые решения в .NET мне неизвестны.
