### ISSUE TITLE
is(var) не правильно форматируется

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#904]
```
type
  t1 = class end;

begin
  if new object is t1(var a) then
end.
```
Форматируется в:
```
type
  t1 = class end;

begin
  if new object is t1(a) then
end.
```

**Comment by miks1965** [comment]
Пока это вообще не форматируется и интеллисенс не работает. Мы это знаем. Вы это писали уже здесь: https://github.com/pascalabcnet/pascalabcnet/issues/861
