### ISSUE TITLE
Падает IL Generator при наследовании вида TB<T, T2> = class(TA<T>)

### ISSUE THREAD

**Issue by miks1965** [pascalabcnet/pascalabcnet#907]
```
type
  TA<T> = auto class
    X: T;
  end;
  
  TB<T, T2> = class(TA<T>)
    Y: T2;
    constructor Create(x: T; y: T2) := (self.X, self.Y) := (x, y);
  end;

begin
var o:TB<integer, real>;
end.
```

**Comment by miks1965** [comment]
На этот Issue вандалом была сделана ссылка со статьи Википедии 
https://ru.wikipedia.org/wiki/PascalABC.NET 
Этот Issue был мотивировкой к фразе "В PascalABC.Net Не самая лучшая реализация обобщенных типов."
В настоящее время статья в Википедии очищена от вандализма

**Comment by miks1965** [comment]
Более простой пример падает. 
```
type
  TA<T> = class
    X: T;
  end;
  
  TB<T> = class(TA<T>)
    constructor Create(x: T);
    begin
      self.X := x;
    end; 
  end;

begin
end.
```
Причем, через раз

**Comment by miks1965** [comment]
Падает в NetGenerator.cs в строке 1502
```
FieldInfo finfo = fldinfo.fi;
```
через два раза на третий

**Comment by Xitsa** [comment]
А типы T  для этих полей одинаковые?
Может один T из шаблонного класса, а второй из параметризованного типом параметром?

**Comment by miks1965** [comment]
Нет, там всё верно - это на скринах видно - там словарик, показывающий, что X: T преобразуется к X: T1.

Там дело в Self.X

**Comment by ibond84** [comment]
Что-то в семантике генериков. X два раза добавляется. Так не должно быть

**Comment by MrFresnel** [comment]
Закрывайте эту Issue. В ней недостаточно информации для исправления ошибки компилятора.

**Comment by miks1965** [comment]
Всё достаточно. Это уже наши проблемы.
