### ISSUE TITLE
Не всё форматные выражения работают в форматной строке

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#908]
В продолжение к #896
```
begin
  var r:real := 123.123;
  var s1 := string.Format('r is {0,6:N2}',r);//ok
  var s2 := $'r is {r,6:N2}';//Встречено ',', а ожидалось }
  writeln(s1);
end. 
```
Может лучше добавить синтаксис форматных выражений целиком, или при компиляции пробовать подставлять то что после значения в `string.Format`, чем кусками исправлять вот так?

**Comment by ibond84** [comment]
>У .Net форматных выражения там куча всего.

Ну в string.Format пусть и используется. Не хочу в парсер вшивать какие-то малоиспользуемые форматные расширения.

**Comment by SunSerega** [comment]
Это не мало используемые расширения. Указание минимальной длинны чуть ли не самая нужная фича форматных выражений. Вот к примеру:
```
begin
  var a:sequence of (byte,real);
  
  var s := a.Select(
    t->string.Format('b: {0,4}, r: {1,10:N2}',t[0],t[1])
  ).JoinIntoString(#13+#10);
  
  writeln(s);
end.
```
Тут после запятой указано минимальная длинная к которой должно привести выражение.
И замена
```
    t->string.Format('b: {0,4}, r: {1,10:N2}',t[0],t[1])
```
на
```
    t->$'b: {t[0],4}, r: {t[1],10:N2}'
```
сильно увеличивает читабельность.

Насчёт того как реализовать - я ведь предложил. Подставляйте всё что идёт после выражения которое можно посчитать в форматную строку. Если выдаст исключение - выписывайте его в список ошибок. Если не выдаст - значит всё нормально.
