### ISSUE TITLE
Не может вывести generic-параметры из where

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#911]
```
type
  C1<T>=class end;

procedure p1<T1,T2>(a:T1);
where T1: C1<T2>;

begin end;

begin
  p1(new C1<byte>);
end.
```
`Невозможно вывести типы-параметры generic-подпрограммы p1 (укажите типы-параметры явно)`

**Comment by miks1965** [comment]
generic-параметры выводятся ТОЛЬКО по типам фактических параметров - ни по чему больше
