### ISSUE TITLE
{$faststrings} не работает

### ISSUE THREAD

**Issue by miks1965** [pascalabcnet/pascalabcnet#93]
{$faststrings} не работает

**Comment by ibond84** [comment]
что это такое?

**Comment by miks1965** [comment]
Тут это есть
http://pascalabc.net/wiki/index.php?title=Директивы_компилятора

**Comment by ibond84** [comment]
Надо и {$mainresource} выкинуть оттуда. Его больше нет.

**Comment by miks1965** [comment]
А {$faststrings} не будем делать?
Вроде же у нас было когда-то, просто так жалко выкинуть - это быстродействие
