### ISSUE TITLE
Запретить instance-ы интерфейсов

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#930]
```
type 
  tc1[T] = typeclass end;
  
  I1=interface end;
  tc1[I1] = instance end;//не должно компилироваться

begin end.
```
По крайней мере, так я понял из [этого ответа](http://forum.mmcs.sfedu.ru/t/klassy-tipov-v-pascalabc-net/2320/3?u=sun_serega).

**Comment by miks1965** [comment]
Честно говоря, не помню. Но это во-первых известный факт. А во-вторых, классы типов вводятся именно для конкретных типов - никак не для интерфейсов.
