### ISSUE TITLE
Выдает ошибку отсутствия конструктора в методе автокласса

### ISSUE THREAD

**Issue by VladislavMoldovan** [pascalabcnet/pascalabcnet#947]
```
type
  T1 = auto class
    X1: integer;
    
    function Clone() := new T1(X1);
  end;
  
begin end.
```
Ошибка: Program2.pas(4) : No constructor found.

**Comment by miks1965** [comment]
Мы пытаемся вначале найти тип функции, но только при закрытии автокласса в нём генерируется конструктор. Если указать тип возвращаемого значения явно, то работает.

К сожалению, тут исправление долгое, поскольку у нас автоклассы раскрываются на семантическом уровне когда все члены класса обработаны. А тип короткой функции - тоже на семантическом, но раньше - в процессе обработки самой функции.

Чтобы устранить баг, надо по идее раскрывать автоклассы на синтаксическом уровне, но там - свои проблемы - с рекурсивными типами и автовыводом типов полей.

Так что, пока ума не приложу, как этот баг исправить.

**Comment by VladislavMoldovan** [comment]
Как я понимаю, проблема кроется в автовыводе типа именно для функции.

**Comment by miks1965** [comment]
Да, верно. Семантический тип выводится по типу выражения new T1(1); 
А поскольку конструктора еще нет, то возникает ошибка.

**Comment by SunSerega** [comment]
>Вообще, странно - такой код работает

А разве это не потому что содержимое методов читает после прочтения и обработки всего тела класса?

**Comment by miks1965** [comment]
На этот Issue вандалом была сделана ссылка со статьи Википедии 
https://ru.wikipedia.org/wiki/PascalABC.NET 
Это было мотивировкой к фразе "К сожалению, PascalABC.Net не позволяет писать более-менее серьезные проекты"
В настоящее время статья в Википедии очищена от вандализма
