### ISSUE TITLE
Ошибка отсутствия конструктора при одном методе в классе

### ISSUE THREAD

**Issue by VladislavMoldovan** [pascalabcnet/pascalabcnet#948]
```
type
  T1 = class 
    function Clone() := new T1(); 
  end;

begin
end.
```
Но справка говорит: 

> В силу особенностей реализации вызовов конструкторов в .NET в PascalABC.NET всегда создается конструктор без параметров (независимо от того, определен ли другой конструктор).

**Comment by miks1965** [comment]
Тут та же история.
Даже такой код не работает:

```
type
  T1 = class
    X1: integer;
    function Clone() := new T1();
  end;
  
begin end.
```
Вообще, странно - такой код работает:
```
type
  T1 = auto class
    X1: integer;
    procedure p();
    begin
      var t := new T1();
    end;
  end;
  
begin end.
```

**Comment by ibond84** [comment]
Ошибки нет. Тип функции неизвестен и вычисляется на этапе анализа заголовков методов, когда конструкторы еще не созданы.

**Comment by SunSerega** [comment]
Не нужно знать какие есть конструкторы, чтоб узнать какой тип возвращается. А правильность параметров всё равно проверится, на этапе анализа тел методов.

**Comment by ibond84** [comment]
>Не нужно знать какие есть конструкторы

Ну здравствуйте. Он вызывается в возвращаемом значении. Если его еще нет, то его и нельзя вызывать.

**Comment by ibond84** [comment]
Нет, это не ошибка, а объективное техническое ограничение. В справке надо упомянуть, что короткие методы имеют такое ограничение. Больше ничего делать не надо. Все.

**Comment by miks1965** [comment]
Вот так это будет сформулировано в справке:

В телах коротких функций без типа возвращаемого значения запрещено использовать члены этого типа (записи или класса), объявленные позднее. В частности, запрещено использовать конструктор по умолчанию, который генерируется последним если он не был определён пользователем ранее
