### ISSUE TITLE
Нельзя преобразовать t1 к t1 в циклической зависимости 3 модулей

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#951]
`Unit1`:
```
unit Unit1;

interface

uses Unit2;

var a:t1;

implementation

end.
```
`Unit2`:
```
unit Unit2;

interface

uses Unit3;

type
  t1=class end;

implementation

uses Unit1;

function f1: t1 := nil;

begin
  
  Unit1.a := f1();
  
end.
```
`Unit3`:
```
unit Unit3;

interface

implementation

uses Unit1;

end.
```
Всё вместе архивом: [0.zip](https://github.com/pascalabcnet/pascalabcnet/files/2174618/0.zip).

Если попытаться откомпилировать `Unit2` получаем:
`Unit2.pas(18) : Нельзя преобразовать тип t1 к t1`

Если компилировать любой другой модуль - ошибки нет.
Если убрать хотя бы 1 из `uses` - ошибки нет.

Я ещё сделал небольшую диаграммку зависимости этих модулей:
![image](https://user-images.githubusercontent.com/27270190/42430111-dd400796-8345-11e8-9daf-be4d210b039e.png)

Красная сторона - `interface`. Синяя - `implementation`.
К примеру, стрелка от `U3` к красной стороне `U2` значит что `Unit3` подключен к интерфейсу `Unit2`.

Надеюсь поможет понять в чём проблема.

**Comment by miks1965** [comment]
Крутая ошибка! И диаграммка красивая! Спасибо за труд!

**Comment by SunSerega** [comment]
А нельзя ли добавить ещё тесты для этого случая?
