### ISSUE TITLE
Не видит extensionmethod в циклической зависимости 2 модулей

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#955]
`Unit1`:
```
unit Unit1;

interface

uses Unit2;//Если перенести эту строчку в implementation - ошибки нет

implementation

begin
  var a := new t1;
  a.p1;//Ошибка тут
end.
```
`Unit2`:
```
unit Unit2;

interface

type t1=class end;

implementation

uses Unit1;//Если удалить эту строчку - ошибки нет

procedure p1(self:t1); extensionmethod := exit;

end.
```
Всё вместе архивом: [0.zip](https://github.com/pascalabcnet/pascalabcnet/files/2178148/0.zip).

При компиляции любого из модулей получаем:
`Unit1.pas(11) : Неизвестное имя 'p1'`

**Comment by ibond84** [comment]
Ну это не ошибка, а скорее ограничение. Методы расширения размещаются только в implementation-части модуля. И в данном случае implementation-часть Unit2 еще не откомпилирована, поэтому p1 не находится.

**Comment by SunSerega** [comment]
Можно тогда ошибку поясняющую это? Это не хорошо, когда надо знать кишки компилятора чтоб понимать почему программа не компилируется.
