### ISSUE TITLE
Не позволяет переименовать шаблонный тип функции

### ISSUE THREAD

**Issue by VladislavMoldovan** [pascalabcnet/pascalabcnet#956]
![image](https://user-images.githubusercontent.com/37166763/42506066-6e6f798c-8449-11e8-8d60-ef600bdf09bc.png)

```
type
  TFunc<T, TResult> = function(x, y: T): TResult;
  
begin
end.
```

Однако, если напишу:
```
type
  TFunc = function: integer;
  
begin
end.
```
, то:
![image](https://user-images.githubusercontent.com/37166763/42506108-93cef0b8-8449-11e8-94f4-057069f71ccb.png)

**Comment by miks1965** [comment]
Вообще, надо закрыть переименование переменной в оболочке - там очень много ошибок. 
Реализация этого достаточно трудна и времяёмка.

**Comment by ibond84** [comment]
Зачем закрывать? Там все тривиально.  Просто генерики как всегда обделены..

**Comment by miks1965** [comment]
А, ну тогда пусть Issue висит
