### ISSUE TITLE
Ошибка "Заданный конструктор должен быть объявлен в определении базового типа."

### ISSUE THREAD

**Issue by VladislavMoldovan** [pascalabcnet/pascalabcnet#957]
```
type
  TExample1<T> = auto class
    X: T;
  end;
  
  TExample2<T> = auto class(TExample1<T>)
    Y: T;
  end;

var
  A: TExample2<real>;

begin
  A := new TExample2<real>();
end.
```

> Internal compiler error in module [pabcnetc.exe] :'System.Exception: System.ArgumentException: Заданный конструктор должен быть объявлен в определении базового типа.
> Имя параметра: constructor
>    в System.Reflection.Emit.TypeBuilder.GetConstructor(Type type, ConstructorInfo constructor)
>    в PascalABCCompiler.NETGenerator.ILConverter.<>c__DisplayClass114_0.<ConvertCommonGenericInstanceTypeMembers>b__0(ICommonMethodNode icmn)
>    в PascalABCCompiler.NETGenerator.ILConverter.ConvertCommonGenericInstanceTypeMembers(ICommonGenericTypeInstance value)
>    в PascalABCCompiler.NETGenerator.ILConverter.ConvertFromTree(IProgramNode p, String TargetFileName, String SourceFileName, CompilerOptions options, String[] ResourceFiles)
>    в PascalABCCompiler.Compiler.Compile()'

**Comment by miks1965** [comment]
Исправили. Автоклассы конечно не могут иметь предков
