### ISSUE TITLE
Запретить присваивание неконстантного выражения константам

### ISSUE THREAD

**Issue by VladislavMoldovan** [pascalabcnet/pascalabcnet#958]
```
const
  A = Sin(10); // Ведет себя как read-only поле, такого быть не должно.
  
begin end.
```
Либо, если уж на то пошло, исправить справку.

**Comment by miks1965** [comment]
Почему? Константа вычисляется в какой-то момент в программе и потом гарантируется, что она будет неизменна при использовании. Но при создании можно любым выражением - это ничего не нарушает.

**Comment by miks1965** [comment]
А где там в справке что сказано?

**Comment by VladislavMoldovan** [comment]
В справке не сказано, что можно присваивать константам неконстантные значения.
