### ISSUE TITLE
Сделать возможность создания анонимных классов

### ISSUE THREAD

**Issue by VladislavMoldovan** [pascalabcnet/pascalabcnet#959]
Добавить возможность писать следующий код:
```
var
  A: class
       private
         _x, _y: integer;
         
       public
         property X: integer read _x write _x;
         property Y: integer read _y write _y;
        
         constructor Create(x, y: integer) := (_x, _y) := (x, y);
         
         function ToString(): string := $'({_x}, {_y})';
     end;

begin
  A := new (10, 20);
end.
```

**Comment by SunSerega** [comment]
По моему вы что то перепутали... У этой issue содержимое #960, что не подходит к названию.

**Comment by VladislavMoldovan** [comment]
Не перепутал, здесь у меня issue именно про возможность создания анонимных классов. Но никак не про возможность вызова конструктора таких классов.

**Comment by miks1965** [comment]
Ну, это какая-то придумка ваша странная.

В PABC есть new class(Поле1, Поле2) - этого достаточно?

**Comment by VladislavMoldovan** [comment]
Хм, пожалуй да.
