### ISSUE TITLE
Сделать возможность вызова конструктора в виде new() для записей

### ISSUE THREAD

**Issue by VladislavMoldovan** [pascalabcnet/pascalabcnet#960]
```
var
  A: record
       private
         _x, _y: integer;
         
       public
         property X: integer read _x write _x;
         property Y: integer read _y write _y;
        
         constructor Create(x, y: integer) := (_x, _y) := (x, y);
         
         function ToString(): string := $'({_x}, {_y})';
     end;

begin
  A := new (10, 20); // (А как по другому вызывать Create?)
end.
```

**Comment by SunSerega** [comment]
`new A` или `A.create`, как и для классов. Разработчики просили сначала спрашивать такое на форуме. А сюда постить сразу только то, что 100% ошибка.

**Comment by VladislavMoldovan** [comment]
Думаю лучше оба варианта. Ведь есть же возможность для обычных классов и записей писать через них. Лучше чтобы все было более стандартизировано.

**Comment by miks1965** [comment]
Если запись именованная, можно вызывать new Rec()

Если неименованная, то так писать глупо.

Закрою-ка сразу.

Предлагаю, чтобы я не закрывал вот так сразу странные предложения по языку, обсуждать их на форуме - тогда мы меньше будем замусоривать Issue

**Comment by VladislavMoldovan** [comment]
Хорошо.

**Comment by SunSerega** [comment]
А вообще, я сейчас попробовал запустить...

Если указать правильное кол-во параметров конструктора - пишет:
`Нет перегруженной подпрограммы с таким количеством параметров new`

Если указать 1 параметр конструктора - пишет:
`Неправильный тип параметров подпрограммы`

То есть `new` вызывается, но в правильном варианте написания выдаёт явно неправильную ошибку.

**Comment by SunSerega** [comment]
Хотя вызывать конструктор тут - не обязательно. Лучше написать процедуру `Init` или что то типа того.
