### ISSUE TITLE
Добавить sealed для методов

### ISSUE THREAD

**Issue by VladislavMoldovan** [pascalabcnet/pascalabcnet#961]
```
type
  TBase = class
    procedure P1(); virtual := exit;
  end;
  
  TMy = class(TBase)
    procedure P1(); sealed := exit;
  end;
  
begin end.
```

**Comment by SunSerega** [comment]
А в чём его смысл? Я понимаю виртуальный метод делать `sealed`, чтоб его `override` не делали, но тут `Method` не виртуальные ведь.

**Comment by VladislavMoldovan** [comment]
Поправил.

**Comment by miks1965** [comment]
Я хотел закрыть этот Issue. Но пока пообсуждаем.

В C# есть sealed-методы? Для какой цели вообще они нужны?

В Паскале есть reintroduce. Вам этого недостаточно?

**Comment by VladislavMoldovan** [comment]
[Sealed C#](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/sealed)

**Comment by SunSerega** [comment]
`reintroduce` используется в классе-наследнике.

`sealed` методы нужны, если, к примеру, пишешь библиотеку, и из определённых соображений (инкапсуляция, к примеру) не хочешь чтоб определённый метод класса наследовали.

**Comment by miks1965** [comment]
Ну, C# гораздо более сложный язык в этих классификациях.

Я не хочу вводить в язык новое ключевое слово для крайне редкой возможности. 
Я не встречался в своей жизни с ситуацией когда необходимо было бы запрещать переопределение одного метода и никак иначе было бы нельзя.

**Comment by SunSerega** [comment]
А ещё, некоторые оптимизации JIT-компилятора могут сделать вызовы `sealed` методов быстрее, потому что не надо смотреть в виртуальную таблицу. (только что на msdn прочитал)

**Comment by SunSerega** [comment]
>новое ключевое слово

Оно не новое. Но сейчас работает только для классов. А то что вы не встречали - это никогда не показатель, хватит приводить это выражение как причину.

**Comment by miks1965** [comment]
Нет, не будем это делать. Это лишние навороты.

**Comment by SunSerega** [comment]
С чего вдруг передумали?

**Comment by AIexandrKotov** [comment]
Кстати да, будет очень полезной и нелишней вещью.
