### ISSUE TITLE
re: Анализатор не правильно читает array.ConvertAll

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#963]
@ibond84 закрыл #514 сказав что это дубль #492, но это не так. В #492 речь идёт про кортежи, и это работает в любой лямбде. А в #514 дело именно в `array.ConvertAll`:
```
begin
  var a := Arr(1, 3, 5).ConvertAll(i -> i)
end.
```
Тут для `a` показывает тип `array of function(i:T): `.

При чём виноват именно `array.ConvertAll`, `sequence.Select` и `List.ConvertALL` работают нормально.

**Comment by ibond84** [comment]
Это то же самое и дубль. Инстанции генериков реализованы не до конца.
