### ISSUE TITLE
Сделать явное преобразование типа лямбды ft(i -> i)

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#964]
```
type
  ft = integer->integer;

begin
  var f := ft(i -> i);
end.
```
`2.pas(5) : Операция ':=' не применима к типу  `

**Comment by miks1965** [comment]
А что Вы хотели этим неправильным кодом сделать?

**Comment by SunSerega** [comment]
Если он не правильный - то хотя бы получить что то типа `ожидалось <что то>, а встречено "->"`.

А по хорошему нормальную ошибку, почему так делать нельзя.

Ведь это преобразование типа, тут вполне реально вычислить тип лямбды, вариант то всего 1. Конечно, если речь идёт про присвоение результата переменной - такое извращение не нужно. Но к примеру в этом случае:
```
procedure p1(d:System.Delegate) := exit;

type
  ft=byte->byte;

begin
  p1(ft(b->b*2));
end.
```
Это, кстати, даёт внутреннюю ошибку компилятора.

**Comment by miks1965** [comment]
Да, в C# работает. 
Ну, надо выводить тип лямбды по типу делегата. Согласен. Оставляем.

**Comment by miks1965** [comment]
Не будем делать. Сложно и не нужно.
