### ISSUE TITLE
Анализатор кода не правильно читает лямбду, возвращающую функцию

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#965]
```
begin
  var f: integer->integer := i -> i;
  var a := Arr(0).Select(i -> f);
end.
```
Тут для `a` показывает тип `sequence of integer`, хотя он `sequence of integer->integer`.

**Comment by ibond84** [comment]
f с параметрами. поэтому и берет указатель. закрывайте issue

**Comment by SunSerega** [comment]
А, действительно...

**Comment by SunSerega** [comment]
Хотя нет, подождите, тогда наоборот, не прав анализатор кода. Исправил.

**Comment by ibond84** [comment]
Дубль #492
