### ISSUE TITLE
Не правильная ошибка при `Select` без экранирования `<>` и неправильным количеством шаблонных параметров

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#966]
```
begin
  var f:integer->integer := i->i;
  var a: sequence of integer;
  a := Arr(0).Select<integer>(f);
end.
```
`Нет перегруженной подпрограммы с таким количеством параметров Select`

Если экранировать `<>` пишет правильно:
`Число типов-параметров в спецификации generic-подпрограммы Select должно быть равно 2`

**Comment by ibond84** [comment]
Ошибки нет. Без экранирования это операция сравнения

```
(Arr(0).Select) < integer > (f);
```

Select без параметров - ошибка Нет перегруженной подпрограммы с таким количеством параметров Select

**Comment by miks1965** [comment]
Если < в выражении, то это - меньше!!!

**Comment by SunSerega** [comment]
[Теперь](https://github.com/pascalabcnet/pascalabcnet/commit/316295785ad76a242a7d5870093f304b951bc3e0), похоже, будет проверять оба варианта. И сравнение и уточнение шаблона.
