### ISSUE TITLE
Не требует & перед угловой скобкой

### ISSUE THREAD

**Issue by VladislavMoldovan** [pascalabcnet/pascalabcnet#968]
```
begin
  var L: List<integer> := new List<integer>();
end.
```
Перед этой скобкой должен требовать &:
![image](https://user-images.githubusercontent.com/37166763/42614864-59a0764c-85b0-11e8-8f86-e71f5cb0bd90.png)
Почему такая неоднозначность в том плане когда надо употреблять &, а когда нет? В следующем коде, наоборот требует & даже без угловых скобок:
```
begin
  var a := System.Reflection.BindingFlags.&Instance; 
end.
```
Так как & используется для устранения неоднозначности, то следует сделать необходимым его использование только там где это действительно надо.

**Comment by miks1965** [comment]
Исправили. Здесь & можно нигде не писать
