### ISSUE TITLE
При наведении на константу множественного типа показывает внутренности компилятора

### ISSUE THREAD

**Issue by VladislavMoldovan** [pascalabcnet/pascalabcnet#969]
```
const
  A = [1, 2];

begin end.
```
![image](https://user-images.githubusercontent.com/37166763/42615115-5bb6dc72-85b1-11e8-8cdf-7ecab32113a0.png)

**Comment by SunSerega** [comment]
На гитхабе принято стараться делать названия issue как можно короче. Я бы заменил `PascalABCCompiler.SyntaxTree.pasccal_set_constant` на `внутренности компилятора`.
