### ISSUE TITLE
Некорректность во благо оптимизации

### ISSUE THREAD

**Issue by VladislavMoldovan** [pascalabcnet/pascalabcnet#971]
```
begin
  if false then 
    a.b.c.d.q.f.g; // Неизвестные идентификаторы, но проходит компиляцию; если заменить в if true на false, то компилятор начинает адекватно реагировать на эту строку.
end.
```
Вы меня, конечно, извините, но как до такого можно было докатиться? Это не ООП даже, а просто код в 4 строчки... Я очень надеюсь что таких ошибок больше не встречу. 

А вот это выбрасывает некорректное сообщение об ошибке:
```
label l;
begin
  goto l; 
  if false then 
  begin
    l: a.d(); 
  end;
end.
```

> Program1.pas(3) : No label with name 'l'

**Comment by SunSerega** [comment]
Всё правильно. Это называется оптимизация. По вашему, то что в играх стены которые не видно не рисуют - тоже ошибка? Эта часть в любом случае не окажется в готовом `.exe`, зачем на неё  тратить время компилятора?

**Comment by VladislavMoldovan** [comment]
Нет, неправильно. Пользователю не должно быть позволено писать всякий бред, только потому что есть оптимизация. Должна быть ошибка компиляции. Иначе что это за компилятор такой, который только потому что оптимизирует код позволяет творить пользователю все что ему захочется?
