### ISSUE TITLE
Переменная не инициализируются, при присваивании константе значения функции

### ISSUE THREAD

**Issue by VladislavMoldovan** [pascalabcnet/pascalabcnet#979]
```
var
  n := 2;

function f()  := n; 

const
  a = f();

begin
  Writeln(a); 
end. 
```
Выведет 0, хотя должно было бы 2. Хотя, конечно, в идеале, не должно такое компилироваться.

**Comment by miks1965** [comment]
Да, запретим использование вызовов функций как инициализаторов констант

**Comment by miks1965** [comment]
Запретили.

**Comment by miks1965** [comment]
Запрещена инициализация констант пользовательскими функциями

Можно:
const x = sin(0); // стандартная
const x = System.DateTime.Now; // из dll

Нельзя:
var n := 5;
const x = sin(n);
