### ISSUE TITLE
Внутренняя ошибка, при использовании переменной типа KeyValuePair в лямбде в рекурсивных модулях на уровне генерации IL-кода

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#981]
, когда 1 из шаблонных параметров `KeyValuePair` - тип из циклично скреплённого модуля.

`test.pas`:
```
uses Unit1;//Обязательно подключить Unit1
//uses Unit2;//Нельзя подкючать Unit2

begin end.
```
`Unit1.pas`:
```
unit Unit1;
{$savepcu false}//.psu в некоторых ошибках влияли на воспроизведение ошибки, эта строчка на всякий случай

uses Unit2;//Обязательно этот uses, чтоб образовать цикличное подключение модуля

type t0 = class end;//обязательно объявить именно в Unit1

end.
```
`Unit2.pas`:
```
unit Unit2;
{$savepcu false}//.psu в некоторых ошибках влияли на воспроизведение ошибки, эта строчка на всякий случай

interface

implementation

uses Unit1;//Обязательно этот uses, чтоб образовать цикличное подключение модуля

procedure p1;//это может быть процедура, функция, конструктор и т.п. - от этого не зависит
begin
  
  var d := new Dictionary<byte, t0>;//Обязательно словарь. Список работает нормально
                                    //Обязательно 1 из типов шаблона - t0 (тип из Unit1). <t0, word> тоже вызовет ошибку
  
  var a := d.First;//Надо любым способом получить KeyValuePair. foreach тоже даст ошибку
  var p: procedure := ()->
  begin
    a := a;//И после этого надо использовать тот KeyValuePair в лямбде
  end;
  
end;

end.
```
Всё вместе, архивом: [0.zip](https://github.com/pascalabcnet/pascalabcnet/files/2196270/0.zip).

Если компилировать модули - всё в порядке.
Но если компилировать `test.pas` - получаем:
```
() : Внутренняя ошибка компилятора в модуле [pabcnetc.exe] :'System.Exception: System.TypeLoadException: Не удалось загрузить тип "Unit1.t0" из сборки "test, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null".
   в System.Reflection.Emit.TypeBuilder.TermCreateClass(RuntimeModule module, Int32 tk, ObjectHandleOnStack type)
   в System.Reflection.Emit.TypeBuilder.CreateTypeNoLock()
   в System.Reflection.Emit.TypeBuilder.CreateType()
   в PascalABCCompiler.NETGenerator.ILConverter.CloseTypes()
   в PascalABCCompiler.NETGenerator.ILConverter.ConvertFromTree(IProgramNode p, String TargetFileName, String SourceFileName, CompilerOptions options, String[] ResourceFiles)
   в PascalABCCompiler.Compiler.Compile()'
```

**Comment by miks1965** [comment]
Да, это сложная ошибка. Старый сложный алгоритм компиляции модулей вступает в противоречие с лямбдами в случае их рекурсивной завязки

**Comment by miks1965** [comment]
Это для Вас ) Для нас - это наслоение концепций 8-летней и 3-летней давности, отягощённое рекурсивной зависимостью модулей.

Эта ошибка сложна для исправления к сожалению.

**Comment by SunSerega** [comment]
Ну лавно, но issue всё же оставьте, может когда то но соберётесь исправить. Или возможно не вы, а какой нибудь новый разработчик. Это ведь возможно что к вашей команде кто то присоединится в будущем?

**Comment by miks1965** [comment]
Нужен более простой пример. Совершенно невозможно тестировать

**Comment by SunSerega** [comment]
Я не очень представляю куда тут упрощать...

Из кода:
-

Можно попробовать заменить `Dictionary` на `sequence of KeyValuePair`.

И попробовать перенести содержимое `p1` куда то, к примеру в `begin-end.` этого же модуля.

Остальное:
-

Но файлов меньше сделать точно не выйдет, потому что нужна циклическая зависимость, что может быть только у 2 модулей.
И надо файл основной программы, потому что проявляется только на этапе генерации IL.

Хотя, если вы отследили что не так на предыдущих этапах компиляции - от `test.pas`, наверное, можно избавится и компилировать `Unit1.pas`...

**Comment by miks1965** [comment]
Тут вот какое дело. Судя по сообщению об ошибке нельзя развернуть тип t0 на генерации IL. Но механизм лямбд на это не должен влиять. Лямбды вообще не затрагивают класс t0. Поэтому надо искать более простой пример. Взять на себя труд - попереставлять, коренным образом изменить и т.д. 

Лямбды генерируют новый код и в старом меняют захваченные переменные. Всё

**Comment by SunSerega** [comment]
А что, если в сгенерированном лямбдами классе есть какой то неправильный код, на который будет ругаться только при вызове `System.Reflection.Emit.TypeBuilder.CreateType` для него. Но т.к. `t0` использовано в том классе - он тянет его за собой, и поэтому ошибку даёт на нём.

Это довольно смелое и мало чем подкреплённое предположение, но как насчёт попробовать эмитить сначала классы лямбд, перед `t0`?

А так, `t0` же вообще пустой, если его содержимое как то и ломает `TypeBuilder` - вы можете увидеть на отладке, чем отличается содержимое `t0` с кодом дающим ошибку и, в том, где что то убрали (так что оно перестало воспроизводится).
