### ISSUE TITLE
Разрешить писать id символа в 16-ичной системе счисления

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#986]
К примеру:
```
write(#$20)//ожидается что выведет результат #32, то есть пробел
```
Или, возможно, какой то по другому.

**Comment by miks1965** [comment]
Прошу Вас посмотреть, как это сделано в современном Delphi. Я там видел такое. Чтобы была совместимость

**Comment by miks1965** [comment]
А, нет. В Delphi такого нет. Может, в других языках найдёте?

**Comment by SunSerega** [comment]
Ну, я попробовал поискать... В общем лучшее что я нашёл это `U+20`. Как я запрос не задавал (не включая названия языков в него) - выдаёт большую часть таблицами ASCI и UNICODE.

**Comment by SunSerega** [comment]
Но если разрешить писать U20 - не даст называть так переменные (а сейчас можно). И это уже сильный минус совместимости не только с другими языками, но и с предыдущими версиями этого паскаля.

**Comment by ibond84** [comment]
Ну а чем это не устраивает? 
```
writeln(Chr($20));
```

**Comment by ibond84** [comment]
Закрываю. Используйте Chr($20)

**Comment by ibond84** [comment]
$# уже какая-то перловщина

**Comment by SunSerega** [comment]
Это да, но это не повод полностью отказываться. В конце концов, те кто считают это перловщиной - пусть не пользуются.
