### ISSUE TITLE
Анализатор кода видит переопределённый оператор в основном пространстве имён

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#987]
```
type
  t1=class end;

procedure operator+=<T>(a,b:t1) := exit;

begin
  
end.
```

![image](https://user-images.githubusercontent.com/27270190/42846737-82901708-8a22-11e8-83fd-b1d5b1481ba9.png)

**Comment by ibond84** [comment]
Ну а кому он мешает? Не вижу смысла убирать.

**Comment by SunSerega** [comment]
Оно забивает основное пространство имён. Их нельзя вызывать так, поэтому и показывать не должно.

**Comment by SunSerega** [comment]
А, кстати, что то тут ещё не так... Вот к примеру:
```
type
  t1=class end;

procedure operator+=<T>(a,b:t1) := exit;

begin
  var a := new t1;
  a += new t1;
end.
```
Пишет что `+=` не применимо к `t1`.
Если убрать `<T>` - то вообще не компилируется.

```
type
  t1=class end;

procedure object.operator+=<T>(a,b:t1) := exit;

begin
  var a := new t1;
  a += new t1;
end.
```
Тут пишет нормально, что не может вывести `T`.
```
procedure object.operator+=(a,b:object) := exit;

begin
  var a := new object;
  a += new object;
end.
```
А тут, как и ожидалось, всё нормально компилируется и `operator+=` не появляется в Ctrl+Space.

По крайней мере это, получается, по разному работает при разных записях. И писать что `+=` не применимо к `t1`, как в первом случае - точно не правильно.

**Comment by SunSerega** [comment]
Это выводит нормальную ошибку, про то что `<T>` вычислить нельзя:
```
type
  t1=class end;

procedure object.operator+=<T>(a,b:t1) := exit;

begin
  var a := new t1;
  a += new t1;
end.
```
А это выводит странную ошибку:
```
type
  t1=class end;

procedure operator+=<T>(a,b:t1) := exit;

begin
  var a := new t1;
  a += new t1;
end.
```
---

Кроме того, эта issue про то, что `operator+=<T>` появляется в Ctrl+Space. Ни в одной другой записи он не появляется, поэтому это ошибка.

**Comment by miks1965** [comment]
Прошу Вас в одной Issue писать ровно одну проблему
Лучше закройте эту Issue и откройте пару новых

**Comment by SunSerega** [comment]
Нет, ну эта issue про то что анализатор кода не правильно себя ведёт, как и была изначально, её закрывать незачем. Остальное я написал только чтоб подтвердить что это не правильное поведение.

А для остального открою чуть позже доп. issue.

**Comment by miks1965** [comment]
Тут много мусора с обсуждением.
И - я не вижу остального - я вижу одно плохое сообщение об ошибке - больше ничего.

**Comment by SunSerega** [comment]
Ладно, вы правы...
