### ISSUE TITLE
Не правильная ошибка при переопределении оператора, когда 1 из параметров кортеж

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#988]
Ещё и с потерей контекста)))
```
procedure object.operator+=(t:(byte,byte)) := exit;

begin end.
```
`Undefined FileName(0) : Неизвестное имя '?System'`

**Comment by miks1965** [comment]
Ещё раз спасибо Вам за ошибку. Благодаря ней мы полностью переработали и упростили обработку ?System
