### ISSUE TITLE
BadImageFormatException при кортеже с элементом - множеством

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#990]
```
begin
  var tupl := (1,2,[3,4,5]);
  Print(tupl.Item1);
end.
```
У 2 людей с форума воспроизвелось, но не у всех.

**Comment by miks1965** [comment]
У меня работает. У меня 64-битная Win10.

**Comment by SunSerega** [comment]
Вин 7х64 тоже не воспроизводится.

**Comment by miks1965** [comment]
Вот две программы:
```
begin
 var tupl := (1,2,[3,4,5]);
 Print(tupl.Item1);
end.
```
и
```
begin
 var tupl := new System.Tuple<integer,integer,TypedSet>(1,2,[3,4,5]);
 Print(tupl.Item1);
end.
```

Отличие в генерируемом коде в одной строчке:
```
Tuple<int, int, TypedSet> tuple = Tuple.Create<int, int, TypedSet>(arg_5B_0, arg_5B_1, PABCSystem.CreateSet(Program.$intarr1).CloneSet());

```
```
Tuple<int, int, TypedSet> tuple = new Tuple<int, int, TypedSet>(arg_56_0, arg_56_1, PABCSystem.CreateSet(Program.$intarr1));
```
Может, ibond посмотрит, что может быть не так

**Comment by miks1965** [comment]
Эта ошибка долго не будет исправлена.

**Comment by spectatorBH** [comment]
Win7 x64 -- ошибка, но только при вкл. опции "Ускорения запуска из-под оболочки".

**Comment by miks1965** [comment]
Если ни у кого кроме Вас эта редкая ошибка не возникает, мы бы закрыли этот гиблый Issue

**Comment by SunSerega** [comment]
А к кому вы обращаетесь? И, уже ведь, у нескольких людей воспроизвелось.

**Comment by miks1965** [comment]
А, у нескольких... А у скольких кстати?
Ну ладно, открою заново. Это мало что изменит правда. Код генерируется верный

**Comment by SunSerega** [comment]
Я смог насчитать Bronislav, RAlex и spectatorBH. Надо, наверное, чтоб они то же самое на C# откомпилировали в студии. От туда уже плясать, смотреть будет ли ошибка там, и если не будет - в чём различие IL кода.

**Comment by miks1965** [comment]
Различия нет. Мы смотрели. Это что то в PABCRtl.dll неправильное в 32-битном режиме.

**Comment by ibond84** [comment]
Это баг в семантике-генериках
