### ISSUE TITLE
Ошибка преобразования к decimal

### ISSUE THREAD

**Issue by miks1965** [pascalabcnet/pascalabcnet#997]
```
begin
  var c: real;
  var a: decimal;
  a := decimal(c);
  var v := (True ? a : c)
end.
```
Для c: real, single, longword, uint64 какие-то ошибки в этом коде. Преобразование decimal(c) не работает для real и single со странной ошибкой, что возможны два преобразования к decimal

**Comment by VladislavMoldovan** [comment]
Отлично... Ничего кроме того, что компилятор го**о сказать не остается. Это Вам не классы, никакие не фичи, а простейшая программа, в которой **уже** вылез баг. Нормально (особенно для среды для обучения)? Не думаю. Хотя, считайте как хотите, и думайте что хотите на счёт своего творения (PascalABC.Net), но называть это адекватным компилятором язык ни у кого не повернется. Разве что у тех, кто только начал в нем писать (потому что не успели багов насмотреться). И как я Вам когда то сказал - компилятор скоро окончательно развалится, хотите Вы этого или нет. Надо было раньше думать и вовремя исправлять баги, а не копить их. И не закидывать в компилятор всякие новые фичи, баги не исправив. Баги - не шутка, не вылезут сейчас, так вылезут потом в неожиданный момент. А написание костылей - это несерьезно. Хотя, кому я это говорю, Вы же их все время почти и пишите, профессиональные разработчики называется.

**Comment by ibond84** [comment]
Пользователю VladislavMoldovan последнее предупреждение, иначе будет отправлена абуза в администрацию github.

**Comment by VladislavMoldovan** [comment]
Исправляйте среду, а я тогда перестаю терроризировать Вас этими комментариями.

**Comment by SunSerega** [comment]
Её и так исправляют. Ошибок которые отказались исправлять очень мало, и у них всех есть хорошие причины на то. И с чего вы решили что ваше терроризировании что то улучшит?

**Comment by VladislavMoldovan** [comment]
> Её и так исправляют.
Тогда почему баги вылезают в простейших программах? Не скажите ли Вы что ее **хорошо** тестируют?

**Comment by SunSerega** [comment]
> Не скажите ли Вы, что ее хорошо тестируют?

А вы знаете как лучше? Тогда подскажите. Сейчас это выглядит как будто вы расказываете что все всё делают не так.

> И какие же причины? Лень и нежелание? Что на это скажут пользователи, которые любят эту среду и хотят в ней программировать профессионально? 

Им больше не нравится ваша клевета на куберфоруме и хабре, это прекрасно видно на форуме.

**Comment by VladislavMoldovan** [comment]
> Им больше не нравится ваша клевета на куберфоруме и хабре, это прекрасно видно на форуме.
Кривой компилятор - клевета? Нет.

**Comment by SunSerega** [comment]
>клевета? Нет.

Вы много преувеличивали и не пробовали проверять что работает а что нет. К примеру, ваш случай с `internal`:
```
uses Data,Data2;

begin
  //T1.value := 1;//конечно нет
  Data.SetValue(1);//конечно да
end.
```
```
unit Data;

interface

uses Data2;

procedure SetValue(i:integer);

implementation

type
  T2=class(T1)
    
    class procedure SetValue(i:integer) := value := i;
    
  end;

procedure SetValue(i:integer) := T2.SetValue(i);


end.
```
```
unit Data2;

interface

type
  T1=class
    protected class value:integer;
  end;

implementation

end.
```
То есть проблема не в кривоте компилятора, а в том что у вас мало опыта.

**Comment by SunSerega** [comment]
И вы не ответили, вы знаете как сделать лучше?

Да: сделайте;
Нет: хватит рассказывать людям которые понимают больше вас в своей работе - как её надо выполнять.

**Comment by VladislavMoldovan** [comment]
> хватит рассказывать людям которые понимают больше вас в своей работе - как её надо выполнять
Это очень заметно. Особенно по качеству самой среды.

**Comment by miks1965** [comment]
Илья или Владислав. Я переоткрою этот Issue без этих обсуждений. 

Мы знаем ваше резко негативное мнение. Все его прочитали. Мне странно вообще, что целью нормального человека может быть хождение по форумам, сайтам и публикация резко негативных статей - потому что что-то вам не понравилось. К сожалению, форма выражения ваших негативов оказалась такова, что всякое положительное общение с Вами закрылось.

Мне очень жаль, что так получилось, потому что было несколько правильных багов, отмеченных вами. Но мы не будем общаться с вами на нашей территории и в таком тоне и после публикации этой странной статьи на Хабре. Поэтому - увы - окно нашего общения закрыто.

**Comment by miks1965** [comment]
SunSerega, internal означает "сборочный". Он виден отовсюду в пределах exe или dll и не виден из другой сборки. Пример абсолютно корректный
